import styles from "@/components/dsd-experience.module.css";
import { LearningJourneyLink } from "@/components/learning-journey-link";
import { TRAINING_CREDIT_NOTICE } from "@/lib/program/learning-credit";
import Link from "next/link";
import { EngagementRouteMap } from "@/components/multimedia/engagement-route-map";
import { ProgramConnections } from "@/components/program-connections";
import { PROGRAM } from "@/lib/constants";
import { requestedProductContext } from "@/lib/product/request-context";
export const metadata={title:"Find your way | Program orientation"};
const paths=[
["Understand the setting","Meet the organization, see how DHS work connects, and explore the division's place in that wider picture.","/understanding-dhs","Understanding DHS"],
["Ground the work in equity","Explore how equity becomes part of decisions, everyday practices, services, and the way we learn from results.","/operationalizing-equity","Equity in practice"],
["Find your work in the program","Explore One DSD's program areas and scenarios, alongside the broader One DHS resources.","/one-dsd","Explore One DSD"],
["Learn something useful","Find courses, resources, and learning pathways. Follow a current question or an interest you want to develop.","/learn","Explore learning"],
["Put an idea into practice","Work through a scenario, explore a tool, or develop something useful for a real task.","/practice","Explore practice"],
["Connect with colleagues","Discover gatherings, mentoring, well-being, and room for the conversations that make work more human.","/one-dsd/amplify","Meet Amplify Equity"],
["Help shape practical change","Learn alongside the One DSD Team and contribute to equity work across the division in ways that fit your capacity.","/one-dsd/team","Meet the One DSD Team"],
["Find community and shared perspective","Explore DHS employee resource groups and the separate statewide network, with links to their own information.","/employee-resource-groups","Explore employee resource groups"],
["Learn about Minnesota communities","Explore community perspectives and context that can inform relationships, engagement, and service decisions.","/minnesota-communities","Explore Minnesota Communities"],
["Grow your leadership practice","Find your starting point as an aspiring or current leader, build a development map, and explore DEIA across the employee life cycle.","/one-dsd/leadership","Explore DSD leadership"],
["Bring your questions","Browse published answers and download a receipt, PDF, or checklist. Staff pages do not accept typed questions.","/ask","Browse common questions"],
["Find the right support","Connect with professional support when a conversation or additional help would be useful.","/support","Explore support"]];
function renderPath([title,body,href,label]: string[]) { return <article key={href} className={styles.orientationItem}><h3 className="text-2xl font-semibold">{title}</h3><p className="my-4 leading-7">{body}</p><Link className="font-semibold" href={href}>{label} →</Link></article>; }
export default async function Page(){const context=await requestedProductContext();const programShortName=context==="one_dsd"?PROGRAM.oneDsdShortName:"One DHS";return <div className={`${styles.page} wrap max-w-6xl py-10`}><Link href="/start">← Find a starting point</Link><header className={`${styles.hero} my-7 rounded-2xl bg-[#faf7f1] p-7 sm:p-10`}><p className={styles.eyebrow}>{programShortName} · People, Access and Culture</p><h1 className="mt-4 text-4xl font-semibold md:text-5xl">Find your way. Make it your own.</h1><p className="mt-5 max-w-3xl text-xl leading-8">A welcome to the whole program, whether you are new to the agency or bringing years of experience. Find the people, ideas, and practical resources that connect with your work.</p><p className="mt-5 max-w-3xl leading-7">Explore in the order that suits you. Participation in this program is voluntary; existing agency requirements, including required equity analysis, still apply.</p><p className="mt-4 text-sm leading-6">{TRAINING_CREDIT_NOTICE}</p></header><nav className={styles.sectionNav} aria-label="Program orientation"><a href="#program-directory">Explore the program</a><a href="#how-we-connect">How we connect</a><a href="#joining-dsd">Joining the One DSD Team</a></nav><LearningJourneyLink compact /><section id="program-directory"><h2 className="text-3xl font-semibold">A few doors into the same program</h2><EngagementRouteMap doors={paths.map(([title, , href, label]) => ({ title, href, label }))} /><div className={styles.orientationDirectory}>{paths.slice(0, 5).map(renderPath)}</div><details className="mt-7 border-y border-line py-5"><summary className="cursor-pointer text-xl font-semibold">More ways to connect, lead, and find support</summary><div className={styles.orientationDirectory}>{paths.slice(5).map(renderPath)}</div></details></section><ProgramConnections /><section id="joining-dsd" className={`${styles.welcomeNote} rounded-xl border border-line p-7`}><h2 className="text-2xl font-semibold">Joining the One DSD Team?</h2><p className="mt-4 leading-8">Begin with the wider DHS context, equity in practice, and the DSD program areas. Then explore Amplify and the team together. Bring one question or interest to a conversation—there is no need to arrive with all the answers.</p><p className="mt-4"><Link href="/one-dsd/team/learning-lab">Discover Learning Labs and open hours →</Link></p></section></div>}
