import { PROGRAM } from "@/lib/constants";
import type { OneDsdTeamWorkspaceState } from "./schema";

const AT = "2026-09-04T00:00:00.000Z";

export const ONE_DSD_TEAM_SEED: OneDsdTeamWorkspaceState = {
  workspace: {
    id: "one_dsd_team",
    name: PROGRAM.oneDsdTeamName,
    programName: PROGRAM.oneDsdProgramName,
    scopeLabel: PROGRAM.oneDsdScope,
    summary:
      "A shared place for the standing volunteer equity committee to learn together, prepare for monthly meetings and Open Hours, invite staff participation, and follow through on agreed work.",
    status: "preview",
    sample: true,
    createdAt: AT,
    updatedAt: AT,
  },
  memberships: [
    {
      id: "member_program_steward",
      workspaceId: "one_dsd_team",
      displayLabel: "Program steward",
      role: "owner",
      status: "active",
      sample: true,
    },
    {
      id: "member_team_member",
      workspaceId: "one_dsd_team",
      displayLabel: "Team member",
      role: "member",
      status: "active",
      sample: true,
    },
  ],
  channels: [
    ["general", "General", "Committee announcements, shared questions, and conversations that concern the whole team."],
    ["monthly_meetings", "Monthly meetings", "Agendas, meeting preparation, confirmed decisions, and follow-through after each general meeting."],
    ["open_hours", "Open Hours", "Planning and reflection for general staff learning and conversation. Open Hours cannot address complaints, individual cases, accommodations, investigations, legal or safety concerns, or personnel matters."],
    ["learning_together", "Learning together", "Resources, reflections, practice commitments, and conversations that help the team learn together."],
    ["staff_engagement", "Staff engagement", "Book discussions, celebrations, conversations, and welcoming ways for staff to take part."],
    ["work_in_progress", "Work in progress", "Drafts, action items, and proposals that the team is still shaping."],
  ].map(([id, name, purpose], position) => ({
    id,
    workspaceId: "one_dsd_team",
    name,
    purpose,
    access: id === "work_in_progress" ? "private" : "workspace",
    position,
    sample: true,
    updatedAt: AT,
  })),
  channelMemberships: [],
  threads: [
    {
      id: "thread_welcome",
      channelId: "general",
      title: "How this working space is organized",
      createdByLabel: "Program steward",
      createdAt: AT,
      updatedAt: AT,
      pinned: true,
      sample: true,
    },
    {
      id: "thread_learning",
      channelId: "learning_together",
      title: "Choose the first shared learning activity",
      createdByLabel: "Program steward",
      createdAt: AT,
      updatedAt: AT,
      pinned: false,
      sample: true,
    },
  ],
  posts: [
    {
      id: "post_welcome",
      threadId: "thread_welcome",
      parentPostId: null,
      body: "Each discussion area has a clear purpose so conversations, decisions, and follow-through stay connected. The example entries are here to help the team get oriented and can be replaced.",
      authorLabel: "Program steward",
      createdAt: AT,
      updatedAt: AT,
      moderationStatus: "visible",
      sample: true,
    },
    {
      id: "post_learning",
      threadId: "thread_learning",
      parentPostId: null,
      body: "Which resource would give the team a useful common starting point, and what should members be able to apply afterward?",
      authorLabel: "Program steward",
      createdAt: AT,
      updatedAt: AT,
      moderationStatus: "visible",
      sample: true,
    },
  ],
  reactions: [],
  attachments: [],
  meetingSeries: [
    {
      id: "series_general_meeting",
      workspaceId: "one_dsd_team",
      name: "One DSD Team general meeting",
      purpose: "Monthly committee business, learning, decisions, and follow-up.",
      cadence: "monthly",
      scheduleNote: "Schedule to be set",
      sample: true,
    },
    {
      id: "series_open_hours",
      workspaceId: "one_dsd_team",
      name: "One DSD Team Open Hours",
      purpose: "A welcoming monthly opportunity for staff to learn, ask general questions, and strengthen their practice.",
      cadence: "monthly",
      scheduleNote: "Schedule to be set",
      sample: true,
    },
  ],
  meetingOccurrences: [
    {
      id: "meeting_general_next",
      seriesId: "series_general_meeting",
      title: "Next general meeting",
      scheduleNote: "Schedule to be set",
      accessNote: "Add access information and share materials with enough time for members to prepare.",
      status: "planning",
      sample: true,
      updatedAt: AT,
    },
    {
      id: "meeting_open_hours_next",
      seriesId: "series_open_hours",
      title: "Next Open Hours",
      scheduleNote: "Schedule to be set",
      accessNote: "Add access information and clearly explain which questions Open Hours can address and where staff can take other concerns.",
      status: "planning",
      sample: true,
      updatedAt: AT,
    },
  ],
  agendaItems: [
    {
      id: "agenda_first_focus",
      meetingOccurrenceId: "meeting_general_next",
      title: "Confirm the first shared focus",
      ownerLabel: "Program steward",
      minutes: 20,
      position: 1,
      sample: true,
    },
  ],
  decisions: [],
  polls: [
    {
      id: "poll_first_focus",
      channelId: "general",
      question: "Which area should the team prepare first?",
      options: [
        { id: "workplace_culture", label: "Workplace culture" },
        { id: "accessible_practice", label: "Accessible practice" },
        { id: "staff_learning", label: "Staff learning" },
      ],
      status: "draft",
      sample: true,
    },
  ],
  pollResponses: [],
  feedback: [
    {
      id: "feedback_workspace",
      channelId: "general",
      prompt: "What would make this working space useful and accessible to the team?",
      status: "open",
      sample: true,
    },
  ],
  feedbackResponses: [],
  learningActivities: [
    {
      id: "learning_first_activity",
      channelId: "learning_together",
      title: "Select the first shared learning activity",
      description: "Choose a resource, agree on a practical application, and set a reflection question.",
      reflectionPrompt: "What will we do differently in our work after this activity?",
      status: "planned",
      sample: true,
    },
  ],
  notificationPreferences: [],
  notificationDeliveries: [],
  actionItems: [
    {
      id: "action_confirm_schedule",
      workspaceId: "one_dsd_team",
      title: "Confirm the monthly meeting and Open Hours schedule",
      ownerLabel: "Program steward",
      dueNote: "Date to be set",
      status: "planned",
      sample: true,
      updatedAt: AT,
    },
    {
      id: "action_review_workspace",
      workspaceId: "one_dsd_team",
      title: "Review this work page with the One DSD Team",
      ownerLabel: "Program steward",
      dueNote: "Before inviting participants",
      status: "planned",
      sample: true,
      updatedAt: AT,
    },
  ],
  contentProposals: [],
  automationPolicies: [
    {
      id: "automation_microsoft_bridge",
      workspaceId: "one_dsd_team",
      name: "Microsoft access",
      status: "stopped",
      allowedAction: "Microsoft access is off. This space cannot send information to Microsoft or receive information from it.",
      sample: true,
    },
  ],
  automationRuns: [],
  processedKeys: [],
  revision: 1,
};
