export const AMPLIFY_ACTIVITIES = [
  { id: "joy", title: "A little joy", category: "Connect", time: "10–20 minutes", intro: "A favorite book, a garden photo, a craft, or a small discovery. A little enjoyment belongs in the working day.", question: "What has caught your interest or made you smile lately?", steps: ["Offer a small example to get things started.", "Invite people to share, listen, or add a written contribution.", "Finish with whatever people enjoyed; no takeaway is required."], access: "A description works just as well as a photo or an object.", href: "/one-dsd/amplify/well-being", link: "Room to recharge" },
  { id: "minnesota", title: "Minnesota through our eyes", category: "Discover", time: "20–30 minutes", intro: "Discover a place, artist, community institution, or story that broadens your picture of Minnesota.", question: "What is a place or story you would like colleagues to discover?", steps: ["Choose a public reading or invite a contribution someone wants to share.", "Explore what draws people's interest and what they would like to learn.", "Offer a related community reading for anyone who wants to continue."], access: "Use public sources; nobody needs to share personal history or speak for a community.", href: "/minnesota-communities", link: "Explore Minnesota Communities" },
  { id: "story", title: "The story behind it", category: "Connect", time: "15–30 minutes", intro: "A song recommendation, a recipe, an artwork, or a tradition can open an unexpected conversation.", question: "What would you enjoy telling us about this?", steps: ["Bring an example or choose something available publicly.", "Make room for curiosity without asking anyone to represent a group.", "Exchange recommendations if people want to."], access: "No purchases, food contributions, or personal disclosures are needed.", href: "/learn?theme=intercultural", link: "Explore intercultural practice" },
  { id: "borrow", title: "Borrow a good idea", category: "Learn", time: "20–30 minutes", intro: "One team shares something that works. Another imagines how it could fit their own setting.", question: "What small practice has made your work easier?", steps: ["Show a non-sensitive example and explain the need it addresses.", "Ask what would be different in another team's setting.", "Leave an optional resource or possible next step."], access: "Share a written example so people can contribute beyond the conversation.", href: "/practice", link: "Find a practical tool" },
  { id: "question", title: "The question we share", category: "Learn", time: "20–40 minutes", intro: "Different roles, one familiar question: clearer handoffs, useful meetings, or information people can act on.", question: "Where does this question show up in your team's work?", steps: ["Invite perspectives from two willing teams.", "Notice what is shared and what depends on context.", "Choose whether a resource, a further conversation, or a practical suggestion would help."], access: "People can send an example in advance instead of presenting it.", href: "/understanding-dhs", link: "See how the work connects" },
  { id: "listen", title: "Listen, then linger", category: "Discover", time: "15–30 minutes", intro: "A short piece of audio and enough room for the conversation that follows.", question: "What stayed with you, or what would you like to question?", steps: ["Choose an existing program podcast and agree on a short excerpt.", "Offer time to listen or read an available companion resource.", "Invite different interpretations and follow curiosity."], access: "Provide a text alternative; nobody needs to listen in advance.", href: "/learn?theme=structural", link: "Find podcasts and related readings" },
  { id: "known", title: "What I wish I had known", category: "Grow", time: "15–25 minutes", intro: "Useful lessons about finding help, navigating work, or developing a skill—shared generously.", question: "What did you learn the long way that could help someone else?", steps: ["Offer one practical lesson without naming other people's private situations.", "Invite questions and different experiences.", "Share a resource or a willing contact where appropriate."], access: "A colleague's experience is one perspective, not the only way to succeed.", href: "/one-dsd/amplify/mentoring", link: "Explore mentoring and peer learning" },
  { id: "window", title: "A window into my work", category: "Learn", time: "20–30 minutes", intro: "Meet the work behind another team's name and discover where your efforts connect.", question: "What would you like other teams to understand about your work?", steps: ["Use a simple public or fictional example.", "Explain a handoff, decision, or question the team encounters.", "Invite colleagues to describe connections to their own work."], access: "Offer an outline and avoid case or personnel information.", href: "/areas", link: "Explore areas of work" },
  { id: "friction", title: "One less friction", category: "Improve", time: "15–30 minutes", intro: "An unclear message or an avoidable step can be a useful starting point for a small improvement.", question: "What is one thing that could be easier for the people doing or using this work?", steps: ["Describe the process and who experiences it.", "Explore different effects without assuming motives.", "If people want, develop an idea to carry forward."], access: "People can name a difficulty without being expected to solve it.", href: "/one-dsd/amplify/ideas", link: "Give an idea some shape" },
  { id: "pause", title: "A pause that fits", category: "Recharge", time: "5–15 minutes", intro: "A quiet pause, a seated stretch, a casual chat, or an accessible outdoor break—choose what suits you.", question: "What kind of pause would feel useful today?", steps: ["Offer more than one option, including quiet time.", "Let people take part in their own way.", "Finish without asking for health information or a report back."], access: "Movement, cameras, and conversation are optional.", href: "/one-dsd/amplify/well-being", link: "Explore well-being at work" },
  { id: "opportunity", title: "Opportunity exchange", category: "Grow", time: "20–30 minutes", intro: "Make development opportunities easier to understand and easier to find.", question: "What would help someone understand how to access this opportunity?", steps: ["Choose an actual opportunity and confirm its requirements.", "Explain how interest is expressed and who can answer questions.", "Notice any unclear criteria or access barriers worth addressing."], access: "Distinguish actual requirements from informal expectations about fitting in.", href: "/resources/pn-mentoring-sponsorship", link: "Mentoring, sponsorship, and reverse mentoring" },
  { id: "kindness", title: "Small kindnesses", category: "Connect", time: "5–15 minutes", intro: "Notice an everyday act that made work clearer, easier, or more welcoming.", question: "What did someone do that made a difference to your day?", steps: ["Describe the helpful action.", "Ask before naming someone publicly.", "Enjoy the recognition without turning it into a competition."], access: "No public nominations, rankings, or expectation to contribute.", href: "/learn?theme=culture", link: "Explore workplace culture" },
] as const;

export const AMPLIFY_EXTENDED_PAGES = [
  { id: "mentoring", title: "Grow with one another", intro: "A useful conversation can open a door. Find encouragement, exchange practical knowledge, and explore what you want to do next.", sections: [
    ["Support that fits you", "You might want a single conversation, a peer learning partner, a small circle, or an ongoing mentoring relationship. Different people can help with different questions. Begin with what would be useful to you."],
    ["Several ways to connect", ["A question conversation: ask someone with relevant experience about one thing you are working through.", "A peer exchange: colleagues share approaches and learn from each other across roles or teams.", "A mentoring circle: a small group explores shared interests with room for different goals.", "A continuing relationship: agree together on the purpose, availability, and how you will revisit what helps."]],
    ["Make room for different experiences", "Useful mentoring starts with curiosity. Talk about the support, communication, and opportunities that matter to the person. A familiar route to success may not fit everyone's experience, responsibilities, or circumstances."],
    ["Questions worth asking together", ["What would you like to learn or become more confident doing?", "Which expectations are actual requirements, and which are simply familiar habits?", "What opportunities or relationships would you like better access to?", "How would you like feedback, and what would make this conversation useful?", "What might each of us learn from the other's experience?"]],
    ["Advice and opportunity", "Mentoring offers perspective and encouragement. Sponsorship adds active support, such as an introduction or putting someone's work forward for consideration. Both can help, while selection and advancement follow the relevant agency processes."],
    ["A relationship you can shape", "Agree on a manageable starting point. You can change the focus, seek another perspective, or finish when the relationship has served its purpose. No one is expected to teach colleagues about an entire community or disclose personal experiences."],
    ["Find a starting point", "Think of a willing colleague, ask the co-leads for help finding a connection, or bring a question to the Equity and Inclusion Operations Consultant. The conversation planner below can help you prepare."],
  ]},
  { id: "well-being", title: "Room to recharge", intro: "Connection, breathing room, and the way work is organized all shape the working day. Explore what helps you and your colleagues feel supported.", sections: [
    ["A little room in the day", "Enjoy a quiet moment, a shared interest, or a conversation that has nothing to do with the next task. Choose what works for you. Rest and enjoyment do not need a work product to justify them."],
    ["What helps work feel manageable?", ["Clear priorities and a shared understanding of what can wait.", "Meetings with a purpose and more than one way to contribute.", "Helpful handoffs and information that is easy to find.", "Room to ask questions, seek support, and take available breaks.", "Recognition for the everyday work that helps others succeed."]],
    ["Notice the conditions, too", "A useful pause can help in the moment. A recurring difficulty may also deserve a change in how work is arranged. Colleagues can explore an unclear process or avoidable burden and decide whether to carry an idea forward."],
    ["Different ways to take part", "A seated activity, a quiet alternative, a remote connection, or a written contribution can make a gathering work for more people. No one needs to explain a health condition or personal circumstance to choose an option."],
    ["A question for colleagues", "What is something we could make clearer, simpler, or more considerate in our everyday work? Start with a small example and leave room for different experiences."],
    ["Support when you want it", "Use the program's support routes when a question needs individual attention. A gathering can offer connection; personal health or workplace concerns may call for a different conversation."],
  ]},
  { id: "ideas", title: "Ideas into practice", intro: "Notice something that could work better? You can offer a perspective without having a finished solution—or taking on the job of fixing it.", sections: [
    ["Start with what you notice", "A clearer handoff, a more accessible meeting, a development opportunity, or a simpler message can all be useful starting points. Describe the work and its effects. Different experiences can help us understand the same situation more fully."],
    ["Give the idea some shape", "The brief below helps you describe what matters, who could benefit, and what you would like considered. You can leave possible solutions open. Keep names and private personnel or case details out of the draft."],
    ["Choose a conversation", "You can bring your brief to the Amplify co-leads, the One DSD Team, or the Equity and Inclusion Operations Consultant. Agree on what may be shared and where the question belongs."],
    ["What a useful response looks like", ["An acknowledgment that the idea reached the right person or team.", "A clear explanation of what is being considered and any information that would help.", "A response explaining the decision, including when a change is not possible.", "An agreed next step, if there is one, with updates brought back to the people involved."]],
    ["Participation stays yours", "You can contribute an observation, help explore options, or choose to stay involved. Raising an idea does not make you responsible for its implementation. A perspective does not need a majority vote to deserve consideration."],
    ["Learning from a change", "If a change is agreed, ask what became easier and for whom, what remains difficult, and what to adjust. Share an update only with the people and wording agreed for that purpose."],
  ]},
] as const;
