/** Program-authored openings; linked organizations describe their own work. */
export const COMMUNITY_SPOTLIGHTS: Record<string, readonly [string, string, string, string, string]> = {
  hmong: ["History carried forward", "Hmong textile arts bring memory, skill, and imagination into public view. The Minnesota Historical Society’s Hmong collections offer a way to explore this creative work alongside the community’s history in Minnesota. A history of displacement is part of the story—not the whole story.", "Explore Hmong history and creativity", "https://www.mnhs.org/hmong", "When planning a conversation across generations, how could you make room for each person’s knowledge and preferred way of communicating?"],
  karen: ["Making space for new voices", "The Karen Organization of Minnesota connects cultural learning with youth development and community life. Its work includes a weaving circle and opportunities for young people to tell stories through theater. These are places where people share skills and shape what comes next.", "Explore the Karen Organization of Minnesota", "https://mnkaren.org/", "What interests and skills might a young person want you to notice beyond the reason for a referral?"],
  oromo: ["Community told through its own stories", "The Oromo Story in Minnesota brings heritage, early community experiences, and regional differences into view through film. Community storytelling offers a richer starting point than a single label: people can describe the traditions and experiences that matter to them.", "Discover the Oromo Story in Minnesota", "https://www.legacy.mn.gov/projects/oromo-story-minnesota-0", "Whose voices would help you understand the range of experiences behind a community name before planning outreach?"],
  "african-american": ["Black history is Minnesota history", "The Minnesota Historical Society’s Black History, Black Voices resources invite readers to explore Black Americans’ contributions to the state. Learning about community life and leadership alongside injustice makes room for a fuller history—and for people whose lives cannot be reduced to disparities.", "Explore Black History, Black Voices", "https://nrhp.mnhs.org/blackhistory-blackvoices", "How might your description of a neighborhood change if residents’ knowledge and priorities came first?"],
  latino: ["Music connects generations", "The Minnesota Latino Museum’s work includes exploring Mexican and Latin American music in Minnesota. Music offers one way into a much broader story of creativity and belonging, spanning different homelands and generations. No single tradition represents every Latino Minnesotan.", "Explore Latin American music in Minnesota", "https://www.mnlatinomuseum.org/exhibitions/mexican-latin-music-mn", "What would help a family describe its own language, identity, and priorities rather than choose a label that does not fit?"],
  vietnamese: ["A place for history and imagination", "The Vietnamese Minnesotan Museum connects history, art, and cross-cultural learning. Exploring this work offers a view of Vietnamese community life that includes creativity and future aspirations, alongside the histories of migration that brought families to Minnesota.", "Discover the Vietnamese Minnesotan Museum", "https://www.vietmnmuseum.com/", "How could you invite an older adult’s perspective directly while also respecting the people they want involved?"],
  khmer: ["Living art, shared across generations", "Minnesota’s Wattanak Dance Troupe teaches and performs Cambodian classical and folk dance. Its work connects artistic growth with relationships across generations. Dance is a living practice here, not simply a reminder of the past.", "Discover Wattanak Dance Troupe", "https://www.wattanakdancetroupe.org/programs", "What would help you learn about someone’s present-day interests and goals without asking them to revisit painful history?"],
  lao: ["Learning culture by making it", "The Lao Arts and Culture Collective creates opportunities to learn through music, dance, storytelling, and crafts. Its culture camp brings these practices into shared learning in Minnesota. Cultural knowledge grows through participation as well as through reading about it.", "Explore Lao arts and cultural learning", "https://laoartsmn.org/programs/lao-culture-camp/", "How could a community partner help shape a gathering—not only translate an invitation after the plans are finished?"],
  "russian-speaking": ["Art opens a conversation", "The Museum of Russian Art offers a Minnesota starting point for exploring art and history. For this language-based brief, it is one doorway, not a portrait of everyone who speaks Russian. A shared language does not settle a person’s nationality, cultural ties, or political views.", "Explore the Museum of Russian Art", "https://tmora.org/about/", "How would you leave room for a person to name their own identity and preferred language without having to correct your assumptions?"],
  "arabic-speaking": ["Contemporary voices, many perspectives", "Mizna creates space for contemporary Arab and Southwest Asian and North African art and writing. Its work offers an invitation to encounter individual creative voices. These overlapping communities are not identical to a language group, and Arabic-speaking Minnesotans have many different identities.", "Explore Mizna’s creative work", "https://mizna.org/about/", "What could you ask that welcomes a person’s own perspective without expecting them to explain an entire region or faith?"],
  "deaf-deafblind-hard-of-hearing": ["Participation shaped by community voices", "Minnesota’s Commission of the Deaf, DeafBlind and Hard of Hearing shares opportunities for civic participation and engagement with public decisions. Community members are shaping public life—not merely requesting access to it. Communication access makes that participation possible.", "Explore community participation and advocacy", "https://mn.gov/deaf-commission/", "If participants helped design your meeting from the beginning, what might change about how people contribute and make decisions?"],
  rural: ["Start with the place and its people", "The Center for Rural Policy and Development explores the realities of rural Minnesota through research and discussion. A place-based perspective invites better questions about local work, relationships, and opportunity. It also helps keep Greater Minnesota from becoming an afterthought in a statewide plan.", "Explore perspectives from rural Minnesota", "https://www.ruralmn.org/", "What local knowledge would change your plan if you began with the town and its residents rather than a statewide average?"],
  "tribal-nations": ["Relationships begin with sovereignty", "Tribal Nations are contemporary governments as well as communities with distinct histories and cultures. Minnesota Indian Affairs offers a starting point for learning about those government relationships. Respect includes recognizing each Nation’s authority to speak and make decisions for itself.", "Explore Minnesota Indian Affairs", "https://mn.gov/indian-affairs/", "Before shaping a proposal, whose governmental authority and designated consultation process must guide the next step?"],
};
