import type { ContentItem } from "./types";

/**
 * Seed corpus for Early-2027 MVP.
 *
 * Authority posture (TRD T-01 default): no item is labeled Official until the
 * canonical Official corpus is frozen by the practice owner. Program-authored
 * method content is labeled Practice note or Guidance. Public standards are
 * External (verify). Content harvested from the One DHS live application is
 * marked with provenance and remains a migration input, not automatic approval.
 */

const OWNER = "Equity and Inclusion Operations Consultant";
const REVIEW = "2027-03-01";
const V = "0.1.0";

export const CORPUS: ContentItem[] = [
  {
    id: "pn-partnership-spine",
    title: "Six commitments for working in partnership",
    type: "practice_note",
    authority: "practice_note",
    layer: "L1",
    summary:
      "Equity is everyone's work. Build on the people, standards, and relationships already in place. Center lived experience. Follow the evidence. Build trust over time. Work in partnership.",
    whyItMatters:
      "These six commitments help you see whether equity is meaningfully built into a plan. If one is missing, return to that part of the work before moving ahead.",
    body: [
      "Equity is everyone's work: the program or policy owner is responsible for building equity into the work, with support from equity staff.",
      "Build on what already exists: begin with the people, standards, and relationships already in place before creating something separate.",
      "Center lived experience: people affected by a decision should help shape it, with their role, authority, and compensation made clear.",
      "Follow the evidence: look at who receives services, who is denied or delayed, and who may be missing. Review patterns by community, language, disability, and place. Be clear about what the information shows and what it does not show.",
      "Move at the speed of trust: build relationships and explain how input was used before expanding the work. Rebuilding trust after a rushed launch takes time.",
      "Work in partnership: counties, providers, community organizations, Tribal Nations (government-to-government), and Equity Directors bring knowledge and authority to the work. Involve them as partners, not simply as names on a contact list.",
    ],
    nextActions: [
      { label: "Open the equity and access checklist", href: "/resources/ja-launch-embed-checklist" },
      { label: "Choose a learning path", href: "/paths" },
    ],
    tags: ["partnership", "principles", "spine", "lived experience", "trust", "data"],
    intents: ["practice_method", "policy_orientation", "intercultural"],
    pathIds: ["gp-1", "gp-3"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "pn-embed-early",
    title: "Building equity into an idea while it takes shape",
    type: "practice_note",
    authority: "practice_note",
    layer: "L2",
    summary:
      "Equity is easier to shape while an idea is still taking form. Before the design is settled, name who it is for, who may carry the burden, and which access needs may have been assumed. Also name who should be involved, who is responsible for the decision, and when the work will be reviewed.",
    whyItMatters:
      "Adding an equity section after the design is complete may leave the original barriers in place. Asking these questions early can change the design itself.",
    body: [
      "Start with people: who is this for, who may be missing from the design process, and who carries the burden when the service does not work.",
      "Name access assumptions early: broadband, a printer, English literacy, a car, daytime availability, or a phone that takes calls. Each assumption can keep someone from taking part.",
      "Before creating an online option, decide how people can get help by phone, on paper, or in person. Make sure staff are available to support those options.",
      "Identify vital documents and the languages people will need. Plan and budget for translation with human review early rather than waiting until after launch.",
      "Involve the right partners before the design is fixed: an Equity Director, accessibility and language access leads, and community partners with purpose, authority, and compensation agreed.",
      "If the work touches a Tribal Nation, Native children, Tribal data, services, or land, government-to-government consultation comes first. Do not place a Nation in a generic stakeholder list.",
      "Write down who is responsible for the decision and each follow-up, along with the next review date. That clarity turns the checklist into accountable work.",
    ],
    nextActions: [
      { label: "Explore questions for your stage of planning", href: "/paths/gp-1" },
      { label: "Open the equity and access checklist", href: "/resources/ja-launch-embed-checklist" },
      { label: "Request a consultation if the stakes or gaps are high", href: "/support/request" },
    ],
    tags: ["launch", "early planning", "concept", "equity planning", "program design", "digital application", "benefits", "renewal"],
    intents: ["launch_embed", "practice_method"],
    pathIds: ["gp-1"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-launch-embed-checklist",
    title: "Equity and access checklist for new work",
    type: "checklist",
    authority: "guidance",
    layer: "L2",
    summary:
      "A one-page checklist for a new program, service, or digital application. It covers people and purpose, access, language, the effort required of people, evidence, partners, decision responsibility, and review.",
    whyItMatters: "Use it as a working document for your program, with a responsible person for each follow-up and a review date. This makes the next steps clear and accountable.",
    body: [
      "People and purpose: who it is for; who may be missing; what result would show that a disparity was reduced rather than shifted elsewhere.",
      "Access: screen reader, keyboard, magnification tested; equally effective phone, in-person, or paper path; documents meet the accessible-document standard.",
      "Language: languages people will need; vital documents identified for translation with human review; interpreter reachable at first contact.",
      "Time and effort: count the steps, documents, and visits from the person's point of view; consider when deadlines or office hours become barriers to eligibility.",
      "Evidence: current use and denial patterns by community, language, disability, and place; missing community knowledge named with a respectful way to get it.",
      "Partners: Equity Director informed; accessibility and language access leads involved; community partners with purpose, authority, compensation, and report-back; Tribal consultation first where applicable.",
      "Decision responsibility: who decides; which rights, rules, and obligations set the limits; what can still change if a rule must remain.",
      "Review: who is responsible for each follow-up; the next review date; what would lead you to pause, redesign, or seek further guidance.",
    ],
    nextActions: [
      { label: "Build your checklist with the launch path", href: "/paths/gp-1" },
      { label: "Questions about steps, time, and effort", href: "/resources/ja-process-burden" },
    ],
    tags: ["checklist", "launch", "digital application", "program", "service", "equity planning", "early planning"],
    intents: ["launch_embed", "next_actions"],
    pathIds: ["gp-1"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-language-access-checklist",
    title: "Language access checklist",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "Start by identifying the languages people need and the vital documents that require translation and human review. Make a qualified interpreter available at first contact, and make each request specific about language, dialect, requested gender match, and meeting format.",
    whyItMatters:
      "The wrong dialect, an unreviewed translation, or an English-only exception process can keep people from receiving meaningful access.",
    body: [
      "Languages: use current contact data for the people your program serves. Record the language and dialect each person requests rather than relying on an agencywide list.",
      "Vital documents: notices of action, applications, consent forms, appeal rights, and anything a person must understand to get or keep a service. Follow the current language-access requirements for translation and qualified human review before release.",
      "Interpreters: use qualified professional interpreters rather than family members, children, or bilingual staff pulled away from their own work. Bilingual colleagues should not be expected to serve as on-demand interpreters.",
      "Requests: write the language and dialect, such as Standard Somali or Maay, White Hmong or Green Hmong, or S'gaw or Pwo Karen. Also note any requested interpreter gender and whether the meeting is in person, by phone, or by video.",
      "Point of contact: a person should reach an interpreter at the first contact, not after a failed attempt in English.",
      "Written material: plain language first; then translation. A dense English notice becomes a dense translated notice.",
      "Follow current DHS policy before using machine translation. Treat any permitted use as a draft, and have a qualified person review every vital document before it is released.",
    ],
    nextActions: [
      { label: "Learn how to work with a spoken-language interpreter", href: "/resources/lm-interpreter" },
      { label: "Plain language and accessible documents checklist", href: "/resources/ja-plain-language" },
      { label: "Open the community brief for the household's language", href: "/minnesota-communities" },
    ],
    tags: ["language access", "interpreter", "translation", "LEP", "vital documents", "Title VI", "dialect", "somali", "hmong", "spanish"],
    intents: ["access_barriers", "next_actions", "policy_orientation"],
    pathIds: ["gp-2", "gp-3"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-plain-language",
    title: "Plain language and accessible documents checklist",
    type: "checklist",
    authority: "guidance",
    layer: "L2",
    summary:
      "Use short sentences, everyday words, one idea per paragraph, built-in heading styles, descriptive links, useful alternative text, and accessible tables. Before release, follow the current state guidance for accessible documents and ask someone outside the team to read the document.",
    whyItMatters: "If a person cannot read or use a notice, they may not be able to understand or appeal the decision. Accessibility needs to be addressed before release.",
    body: [
      "Structure: use real heading styles in order; one topic per heading; lists for steps; tables only for data, with header rows marked.",
      "Words: everyday words; define any term you must keep; active voice; say who does what by when.",
      "Sentences: aim for 15 to 20 words; one idea each; no double negatives.",
      "Links: describe the destination in the link text; never 'click here'.",
      "Images: describe the important meaning in alternative text. Do not place essential information only inside an image, and do not use color as the only way to communicate meaning.",
      "Contrast and type: body text at least 4.5:1 contrast; avoid all-caps blocks and light gray text.",
      "Forms: give every field a clear label and make sure people can complete the form with a keyboard. Error messages should explain what to fix.",
      "Review: use the built-in accessibility checker, then ask someone outside the team to read the document without added explanation and describe what it means to them.",
    ],
    nextActions: [
      { label: "Checklist for changing a form, notice, or letter", href: "/resources/ja-form-notice-change" },
      { label: "Minnesota accessibility standards (external, verify)", href: "/resources/ext-mn-accessibility" },
    ],
    tags: ["plain language", "accessible documents", "alt text", "headings", "contrast", "notice", "letter", "form", "WCAG"],
    intents: ["access_barriers", "next_actions"],
    pathIds: ["gp-2", "gp-5"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-access-checks",
    title: "Access checks before a meeting, outreach, or session",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "Before meeting with people, confirm the language and dialect and arrange captioning, interpreting, and alternate formats. Check the physical and online spaces, along with timing, transportation, child care, trust, and any process burden you can remove.",
    body: [
      "Language: which languages and dialects; interpreter booked with specifics; translated materials reviewed.",
      "Disability and communication access: arrange captions or real-time captioning, sometimes called CART. Provide a qualified sign-language interpreter when requested, send accessible materials in advance, and make sure both the room and online meeting are usable.",
      "Timing: evening or weekend options for working people; religious observance and school calendars checked; enough notice.",
      "Place: consider transit, parking, an accessible entrance and restrooms, and an online option that does not require an unfamiliar account.",
      "Trust: consider who sends the invitation and who will be present. Explain each person's role, what will happen with the information shared, and what participants will receive in return for their time. Do not assume that contact from a public agency feels reassuring to everyone.",
      "Time and effort: avoid unnecessary registration, forms that ask for more information than you need, or identity-document requirements for a listening session.",
      "Payment and follow-up: explain whether people will be paid and when they will hear what changed.",
    ],
    nextActions: [
      { label: "Open the relevant Minnesota Communities brief", href: "/minnesota-communities" },
      { label: "Community engagement path", href: "/paths/gp-3" },
    ],
    tags: ["access", "meeting", "outreach", "captioning", "interpreter", "timing", "trust", "engagement", "session"],
    intents: ["access_barriers", "intercultural", "facilitation"],
    pathIds: ["gp-3", "gp-5"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-process-burden",
    title: "Questions about the steps, time, and effort a process requires",
    type: "tool",
    authority: "guidance",
    layer: "L3",
    summary:
      "Look at the process from the person's point of view. Count the steps, documents, trips, and hours away from work. Notice when a deadline, mailed notice, or login becomes a barrier. At each step, make sure a person can reach staff for help without using the online option.",
    body: [
      "First contact: how does a person learn that the service exists? Which languages and ways of reaching people are used?",
      "Access at each step: can people complete it with a screen reader, keyboard, interpreter, captioning, or an alternate format?",
      "Each document: what must they already have, and what happens if they do not?",
      "Each wait: how long, and what happens to their service meanwhile?",
      "Each decision: who decides, how is it explained, and can it be appealed in plain language?",
      "Each notice: mailed, emailed, or in an account? Who never sees it?",
      "When the process breaks down: who is left carrying the burden—the person, a family member, a county worker, or a community organization?",
      "Removal: which steps could be removed, combined, or done by the agency instead of the person?",
    ],
    nextActions: [
      { label: "Equity and access checklist for new work", href: "/resources/ja-launch-embed-checklist" },
      { label: "Equity impact questions for policy, budget, technology, and procurement", href: "/resources/ja-equity-impact-questions" },
    ],
    tags: ["journey", "burden", "process", "administrative burden", "steps", "documents", "renewal", "eligibility process"],
    intents: ["launch_embed", "access_barriers", "practice_method"],
    pathIds: ["gp-1", "gp-2"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-equity-impact-questions",
    title: "Equity impact questions for policy, budget, technology, and procurement",
    type: "question_bank",
    authority: "guidance",
    layer: "L3",
    summary:
      "Use this short question set for high-stakes decisions. Consider which authority and rights apply, who benefits, who carries the burden, which assumptions shape the outcome, what can change, and what must stay with the responsible official.",
    whyItMatters:
      "These questions can help frame a decision, but they are not legal advice and do not make the decision for you. After working through them, seek guidance from the appropriate person if a high-stakes procurement, budget, or policy decision has a significant equity impact and no official guidance.",
    body: [
      "Policy: Which laws, rules, rights, and required safeguards apply? Who benefits, who carries added work or risk, and whose needs are missing? Which rules or routine practices shape the result? What can your team change, and what must be reviewed by the person with authority to decide?",
      "Budget: Which costs cover interpreting, translation, accessible formats, and payment for community partners? Which costs have been treated as free? If funding is reduced, whose services would be affected first?",
      "Technology: Are accessibility requirements written into the specifications and tested by people who use assistive technology? What information is collected? Could it be used to sort, rank, or profile people?",
      "Procurement: Do the selection criteria give real weight to accessibility, language access, and community knowledge? Do the requirements create unnecessary barriers for small providers or community organizations?",
    ],
    nextActions: [
      { label: "Policy, form, or notice change path", href: "/paths/gp-2" },
      { label: "Request a consultation for high-stakes decisions", href: "/support/request" },
    ],
    tags: ["policy", "budget", "technology", "procurement", "contract", "equity impact", "high stakes", "vendor"],
    intents: ["launch_embed", "policy_orientation", "escalation"],
    pathIds: ["gp-1", "gp-2"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-stakeholder-map",
    title: "Planning with partners: who to involve",
    type: "tool",
    authority: "guidance",
    layer: "L2",
    summary:
      "Plan who should be involved before the design is settled. Note why their involvement matters, what role they will have, whether they will be paid, and when they will hear how their input was used. Begin with trusted, reviewed partner lists and organizations named by the people affected. Do not choose partners from a quick web search alone.",
    body: [
      "Inside DHS: begin with the Equity Director for the administration and the people responsible for accessibility and language access. Involve communications, the policy or rule owner, procurement, and county or provider partners when the work requires their knowledge or authority.",
      "Community: begin with organizations named by the person or family and existing groups of people with lived experience. Be clear about what you are asking, how their input will be used, and whether they will be paid.",
      "Tribal Nations: if the work touches a Nation, Native children, Tribal data, services, or land, contact the Office of Indian Policy or follow the Tribal liaison process first. Consultation is government-to-government and is distinct from stakeholder engagement.",
      "For each partner, record the purpose, how they will take part, whether they will be paid, who maintains the relationship, and when you will report back.",
    ],
    nextActions: [
      { label: "Open a community brief for partner guidance", href: "/minnesota-communities" },
      { label: "Community engagement path", href: "/paths/gp-3" },
    ],
    tags: ["stakeholder", "partners", "involve", "map", "advisory", "community organization", "engagement"],
    intents: ["launch_embed", "intercultural", "practice_method"],
    pathIds: ["gp-1", "gp-3"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "pn-equity-in-practice",
    title: "Equity in Practice: six perspectives and seven questions",
    type: "practice_note",
    authority: "practice_note",
    layer: "L3",
    summary:
      "Consider a decision from six perspectives: compliance and civil rights, diversity and representation, hearts and minds, inclusion and belonging, organizational learning, and social justice. Then use seven questions to choose a thoughtful response.",
    body: [
      "Compliance and civil rights: start with the rights, protections, and required procedures that apply. Equity work must respect due process.",
      "Diversity and representation: who is present, absent, promoted, heard, and contracted with.",
      "Hearts and minds: notice bias, fear, gaps in knowledge, empathy, and everyday behavior. Question an assumption and consider another person's experience.",
      "Inclusion and belonging: whether people can take part, disagree, contribute, and be themselves without penalty.",
      "Organizational learning: what the team needs to learn, reconsider, or change because important voices were left out earlier.",
      "Social justice: who is harmed, what fairness requires, and what responsibility DHS holds.",
      "Seven questions: What are we deciding or creating? What authority, rights, and obligations apply? Who benefits, carries the burden, faces the risk, or is missing? What assumptions, rules, and routines shape who is affected? What evidence and community knowledge are needed? What can we change or redesign, and what must go to the responsible decision-maker? What changed, how will we know, and how will we report back?",
    ],
    nextActions: [
      { label: "Use the seven questions in a learning path", href: "/paths" },
      { label: "Equity impact questions", href: "/resources/ja-equity-impact-questions" },
    ],
    tags: ["equity in practice", "perspectives", "seven questions", "decision", "reflection", "civil rights", "belonging"],
    intents: ["practice_method", "policy_orientation", "workplace_culture"],
    pathIds: ["gp-1", "gp-2", "gp-4"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    provenance: "Adapted from the owner-authored One DHS source (one-dhs-equity-resource, commit 3aed646, src/lib/program/public.ts). The original source and this revised program version are retained separately.",
    version: V,
  },
  {
    id: "lm-workplace-climate",
    title: "Team climate basics: participation, honest conversation, and fair opportunities",
    type: "learning_module",
    authority: "learning",
    layer: "L2",
    summary:
      "Team climate is what people experience in everyday meetings, supervision, and decisions: whether they can speak openly, disagree, receive credit, and have fair access to opportunities. Supervisors can improve it through specific practices and regular follow-up.",
    whyItMatters:
      "This resource supports everyday team-climate work. For a complaint, investigation, accommodation, or discipline matter, use the appropriate Employee Culture, Human Resources, civil rights, or accommodation process.",
    body: [
      "Participation: who speaks first and most; whether agendas go out in advance; whether written input counts as much as spoken input.",
      "Speaking honestly: can people disagree with a supervisor without being punished or losing opportunities? Are mistakes discussed as problems in the work rather than flaws in a person?",
      "Credit and chances: who gets stretch assignments, visible work, and development time; whether that pattern tracks race, disability, language, or tenure.",
      "Norms: a few written team agreements about meetings, interruptions, and follow-through, revisited on a date.",
      "Access at work: captions on by default, materials in advance, flexible formats for participation, no reliance on informal networks for information.",
      "If the situation involves a complaint, investigation, discipline, or accommodation decision about a named person, follow the established Employee Culture, Human Resources, civil-rights, or accommodation process. A team climate plan cannot replace it.",
    ],
    nextActions: [
      { label: "Team climate action plan template", href: "/resources/ja-climate-action-plan" },
      { label: "Workplace culture learning path", href: "/paths/gp-4" },
    ],
    tags: ["climate", "team", "supervisor", "participation", "candor", "psychological safety", "meetings", "norms", "belonging", "workplace culture"],
    intents: ["workplace_culture"],
    pathIds: ["gp-4"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-climate-action-plan",
    title: "Team climate action plan template",
    type: "tool",
    authority: "guidance",
    layer: "L2",
    summary:
      "Choose three to five actions that team members can see and experience. For each action, name the person responsible, when it will begin, when the team will revisit it, and how the team will know whether it is helping. Do not include names connected to complaints or score individual employees.",
    body: [
      "Practice: describe something a team member could see happening, such as sharing the agenda 48 hours ahead, rotating who opens the meeting, reading written input aloud, or turning captions on.",
      "Responsibility: name the supervisor or volunteer responsible for the action. The supervisor remains accountable for the team's practices.",
      "Dates: choose a start date and a follow-up conversation within three months.",
      "Evidence: describe what the team would notice, without ranking people. This might include a short anonymous check-in or a review of who received assignments.",
      "Use this plan to improve team practices. Follow the established process for complaints, investigations, discipline, and accommodation decisions.",
    ],
    nextActions: [
      { label: "Workplace culture path", href: "/paths/gp-4" },
      { label: "When to seek additional guidance", href: "/resources/pn-when-to-escalate" },
    ],
    tags: ["climate", "action plan", "team", "supervisor", "norms", "follow-up"],
    intents: ["workplace_culture", "next_actions"],
    pathIds: ["gp-4"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "pn-when-to-escalate",
    title: "When to seek additional guidance, and where to begin",
    type: "practice_note",
    authority: "practice_note",
    layer: "L1",
    summary:
      "Many questions can be answered with a checklist, job aid, or other resource. Use the established Employee Culture, Human Resources, civil-rights, or accommodation process for complaints, investigations, discipline, and accommodation decisions. Ask the policy or legal owner when official guidance conflicts or is missing. If the work may affect a Tribal Nation, contact the Office of Indian Policy or designated Tribal liaison before planning engagement. A consultation may help with a new program idea, a high-stakes decision, or a community question that remains unresolved.",
    body: [
      "Start with the available resources: search Resources, open a relevant community brief, or use a checklist. These options may give you what you need without a meeting.",
      "Employee Culture, Human Resources, civil rights, or accommodation: use the appropriate established process for a complaint, investigation, grievance, discipline matter, or accommodation decision about a named person. Keep names and case details out of this program.",
      "Policy or legal owner: contact this person when two sources conflict, a statute or rule needs interpretation, or no official source is available. If you cannot confirm the source, say that clearly and ask the policy or legal owner. Do not create or quote a citation from memory.",
      "Office of Indian Policy or Tribal liaison: any work touching a Tribal Nation, Native children, Tribal data, services, or land. Consultation is government-to-government and comes first.",
      "Equity Director: contact the Equity Director for questions about an administration's pilot, local guidance, or proposed content.",
      "Equity and Inclusion Operations Consultant: consider a consultation when an early program idea or high-stakes decision needs another perspective. A consultation may also help when available guidance does not fully address community-specific work. Go to Support to request a consultation or first review what information you would share. A meeting is optional.",
    ],
    nextActions: [
      { label: "Request a consultation", href: "/support/request" },
      { label: "Support home", href: "/support" },
    ],
    tags: ["escalate", "human", "complaint", "HR", "employee culture", "legal", "policy owner", "tribal", "consult", "who to contact"],
    intents: ["escalation", "uncertainty_authority", "boundary_refusal"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "pn-intercultural-method",
    title: "Using community context without profiling",
    type: "practice_note",
    authority: "practice_note",
    layer: "L1",
    summary:
      "A community brief can help you prepare for Minnesota work, but it cannot describe any one person. Use it to ask better questions, check access, and involve the right partners. People within every community have different experiences. Each person is the authority on their own life.",
    whyItMatters:
      "Applying information about a group to an individual is profiling and can lead to worse service. A respectful approach is direct: ask the person, confirm what they need, and address the access barriers within your control.",
    body: [
      "Use the brief to prepare: consider naming, language and dialect, decision-making, access needs, potential partners, and what not to assume.",
      "Ask the person: how they want to be addressed; which language and dialect; who should be in the room; what would make this work for them.",
      "Check access first: consider language, disability and communication access, timing, transportation, trust, and the time and effort a process requires. Ask what a person needs instead of inferring it from their community.",
      "Involve partners through established channels, with a clear purpose, role, compensation, and plan to report back. Staff who share a background are colleagues; do not expect them to interpret or represent an entire community.",
      "If the brief does not cover something, be clear about what you do not know. Ask the person or seek appropriate guidance rather than relying on assumptions.",
    ],
    nextActions: [
      { label: "Open Minnesota Communities", href: "/minnesota-communities" },
      { label: "Community engagement path", href: "/paths/gp-3" },
    ],
    tags: ["intercultural", "culture", "community", "stereotype", "profiling", "ask the person", "within-group diversity", "somali", "hmong", "latino", "immigrant", "refugee", "personal growth", "own culture"],
    intents: ["intercultural", "practice_method"],
    pathIds: ["gp-3"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-facilitation-session-plan",
    title: "Session plan: purpose, activity, practical use, and access",
    type: "tool",
    authority: "guidance",
    layer: "L2",
    summary:
      "Plan the session around what participants will be able to use afterward. Set one clear learning goal, use an activity based on their work, offer something useful to take with them, and arrange access in advance.",
    body: [
      "Learning goal: write one sentence describing something participants will be able to do, such as drafting the access section of their own notice.",
      "Activity: give participants time to work with their own materials, in pairs or small groups, within a clear amount of time.",
      "Practical use: name what each person will leave with and how they will use it next, such as a program checklist, notice plan, or team climate plan.",
      "Access: arrange captions or real-time captioning, send materials in accessible formats ahead of time, and offer an alternative to activities that require dragging items or working under a time limit. Arrange language interpretation or translated materials when participants need them. Use plain-language slides with built-in headings. Do not rely on icons alone.",
      "Follow-up: choose a date and a way to learn whether participants were able to use what they completed.",
    ],
    nextActions: [
      { label: "Facilitation path", href: "/paths/gp-5" },
      { label: "Access checks before a session", href: "/resources/ja-access-checks" },
    ],
    tags: ["facilitation", "session", "training", "huddle", "agenda", "application task", "learning objective", "slides"],
    intents: ["facilitation", "next_actions"],
    pathIds: ["gp-5"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "lm-facilitation-application",
    title: "Facilitation that participants can use in their work",
    type: "learning_module",
    authority: "learning",
    layer: "L2",
    summary:
      "A useful session helps participants make a meaningful change in their own work. Begin with what they should leave able to do, keep presentations focused, and give them substantial time to practice with real materials.",
    body: [
      "Keep the session connected to practice: limit presentation time so participants can spend at least half the session working with the ideas themselves.",
      "Bring real work: ask participants to bring a notice, a plan, or a meeting they own. Practice on that.",
      "Facilitator role: participants know their own programs. Your role is to offer useful questions, guide the conversation, and keep the group on time.",
      "Access: ask in advance what participants need. Arrange captions, spoken-language or sign-language interpretation, translated or accessible materials, and alternatives to dragging or timed activities. Build access into the session from the beginning.",
      "Follow-up: schedule a short check-in to learn whether participants were able to use what they completed.",
    ],
    nextActions: [
      { label: "Session plan template", href: "/resources/ja-facilitation-session-plan" },
      { label: "Facilitation path", href: "/paths/gp-5" },
    ],
    tags: ["facilitation", "learning", "session design", "application", "practice", "adult learning"],
    intents: ["facilitation", "practice_method"],
    pathIds: ["gp-5"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ja-form-notice-change",
    title: "Checklist for changing a form, notice, or letter",
    type: "checklist",
    authority: "guidance",
    layer: "L2",
    summary:
      "When changing staff- or public-facing text or a process, record who is affected and how. Consider language, disability and communication access, the effort required of people, the current source for every rule or policy, who will address each barrier, and when the work will be reviewed. Never cite a law, rule, or policy from memory.",
    body: [
      "Impact: who receives this; what they must do; what happens if they cannot; which communities, languages, disabilities, and places are most affected.",
      "Language: is it a vital document; which languages; translation with human review scheduled.",
      "Access: complete a plain-language review, follow the current accessible-document standard, provide requested formats, and offer help by phone or in person.",
      "Burden: deadlines, required documents, and return methods examined; what can be removed or done by the agency.",
      "Sources: link to the current rule or policy whenever possible. If you cannot confirm it, say so and ask the person responsible for that policy. Do not cite a law, rule, or policy from memory.",
      "Responsibilities and review: who will address each barrier, by when, and the next date the team will review the work.",
    ],
    nextActions: [
      { label: "Policy, form, or notice change path", href: "/paths/gp-2" },
      { label: "Plain language and accessible documents checklist", href: "/resources/ja-plain-language" },
    ],
    tags: ["form", "notice", "letter", "policy change", "impact", "packet", "citation", "statute", "authority"],
    intents: ["access_barriers", "uncertainty_authority", "policy_orientation"],
    pathIds: ["gp-2"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "lm-interpreter",
    title: "Working with a spoken-language interpreter",
    type: "learning_module",
    authority: "learning",
    layer: "L2",
    summary:
      "Book the right language and dialect, and brief the interpreter before the conversation. Speak to the person, use short sentences, and check understanding. Do not use a family member, a child, or a bilingual colleague pulled from their job as an interpreter.",
    body: [
      "Before the conversation: specify the language, dialect, format, and any request for a gender-matched interpreter. Send materials in advance and allow enough time.",
      "During the conversation: explain the interpreter's role, speak directly to the person in the first person, pause often, and avoid idioms. Check understanding by asking the person to describe the next step in their own words.",
      "After the conversation: note any concerns the interpreter raised about terms or forms, and arrange for needed corrections.",
      "For a vital conversation, use a qualified professional interpreter rather than a child, family member, untrained bilingual coworker, or machine translation.",
    ],
    nextActions: [
      { label: "Language access checklist", href: "/resources/ja-language-access-checklist" },
      { label: "Community brief for the household's language", href: "/minnesota-communities" },
    ],
    tags: ["interpreter", "language access", "dialect", "phone interpreting", "video", "learning"],
    intents: ["access_barriers", "intercultural"],
    pathIds: ["gp-2", "gp-3"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    provenance: "Adapted from the One DHS course 'Working with an interpreter.' The original course and this revised program outline are retained separately.",
    version: V,
  },
  {
    id: "pn-self-check",
    title: "A final review for your working plan",
    type: "practice_note",
    authority: "practice_note",
    layer: "L1",
    summary:
      "A useful working plan names who is responsible, when it will be reviewed, which access needs you considered, who you involved, and what you chose not to assume. Completing the boxes matters only when the follow-up is clear.",
    body: [
      "Responsibilities: every follow-up has a named person.",
      "Review date: choose a specific date within a reasonable window and place it on the calendar.",
      "Access: language and disability/communication access considered for this specific work, not in general.",
      "Who was involved: who took part before the plan was final, what role they had, and how their input was used.",
      "Assumptions avoided: what you chose not to assume about the people affected.",
      "Open questions: note what you still do not know and where you will take it next: Resources, a partner, the person responsible for the policy, or a consultation.",
    ],
    nextActions: [{ label: "Choose a learning path", href: "/paths" }],
    tags: ["final review", "working plan", "responsibilities", "review date", "follow-through"],
    intents: ["practice_method", "next_actions"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "lm-how-this-program-works",
    title: "How to use this program",
    type: "learning_module",
    authority: "learning",
    layer: "L1",
    summary:
      "Start with Ask or Resources. Read a community brief when Minnesota communities or partners are part of the work. Use a learning path to create a checklist or plan for your own work, then review it. After using the available guidance, visit Support when the stakes are high, important questions remain, or another perspective would help.",
    body: [
      "Begin at your own pace with program orientation. Explore the wider DHS context, One DSD, learning, practice, and opportunities to connect through Amplify Equity, the One DSD Team, and employee resource groups. Bring your experience and follow the questions that matter to your work.",
      "Sources and limits: each answer identifies its sources and any important uncertainty. Information here is not official DHS policy unless it is clearly linked to a current official source.",
      "Growing your practice: use what you learn here to strengthen future work and recognize when additional guidance would help.",
      "Responsibility for decisions: the responsible officials and partners continue to make decisions about policy, budgets, procurement, legal matters, personnel, and Tribal consultation.",
      "Sharing: the Share control at the top of every page copies a link that opens that page or resource only, in the program view you are using. If you share from the One DSD view, the person who opens the link sees the One DSD view. Nothing from My Work or from your own questions travels with the link.",
    ],
    nextActions: [
      { label: "Explore program orientation", href: "/orientation" },
      { label: "Find a starting point", href: "/guided-start" },
      { label: "Ask a question", href: "/ask" },
    ],
    tags: ["orientation", "how it works", "program", "getting started", "new staff member"],
    intents: ["next_actions", "policy_orientation"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "reviewed",
    version: V,
  },
  {
    id: "ext-clas",
    title: "National CLAS Standards (culturally and linguistically appropriate services)",
    type: "external_reference",
    authority: "external_verify",
    layer: "L4",
    summary:
      "The national standards for culturally and linguistically appropriate services in health and human services, published by the U.S. Office of Minority Health. Use them as a reference and verify the current text at the source.",
    body: [
      "Fifteen standards under governance, leadership, and workforce; communication and language assistance; and engagement, continuous improvement, and accountability.",
      "This program links to the standards. It does not paraphrase them as policy. Check the source for current wording.",
    ],
    nextActions: [{ label: "Language access checklist", href: "/resources/ja-language-access-checklist" }],
    tags: ["CLAS", "standards", "culturally appropriate", "language assistance", "external"],
    intents: ["policy_orientation", "uncertainty_authority"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://thinkculturalhealth.hhs.gov/clas/standards",
    sourceName: "U.S. Department of Health and Human Services, Office of Minority Health",
    version: V,
  },
  {
    id: "ext-mn-accessibility",
    title: "Minnesota digital accessibility standard (MNIT)",
    type: "external_reference",
    authority: "external_verify",
    layer: "L4",
    summary:
      "Minnesota IT Services publishes the state's digital accessibility standard and accessible-document guidance. Verify the current version at the source before citing.",
    body: [
      "Minnesota's current digital accessibility standard uses WCAG 2.1 Level AA. Check the current state standard before citing it.",
      "Before releasing Word documents, PDFs, or slides, follow Minnesota's current guidance for accessible documents.",
    ],
    nextActions: [{ label: "Plain language and accessible documents checklist", href: "/resources/ja-plain-language" }],
    tags: ["accessibility", "WCAG", "Minnesota", "MNIT", "standard", "documents", "external"],
    intents: ["policy_orientation", "access_barriers", "uncertainty_authority"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://mn.gov/mnit/government/policies/accessibility/",
    sourceName: "Minnesota IT Services",
    version: V,
  },
  {
    id: "ext-ada",
    title: "ADA Title II (state and local government services)",
    type: "external_reference",
    authority: "external_verify",
    layer: "L4",
    summary:
      "Title II of the Americans with Disabilities Act covers state and local government services, including effective communication and web accessibility rules. Verify the current rule and dates at the source.",
    body: [
      "This program does not interpret the ADA. For a specific obligation, contact the appropriate accessibility coordinator or legal counsel.",
    ],
    nextActions: [{ label: "Access checks before a meeting or session", href: "/resources/ja-access-checks" }],
    tags: ["ADA", "Title II", "disability", "effective communication", "external", "law"],
    intents: ["policy_orientation", "uncertainty_authority"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://www.ada.gov/law-and-regs/regulations/title-ii-2010-regulations/",
    sourceName: "U.S. Department of Justice",
    version: V,
  },
  {
    id: "ext-title-vi-lep",
    title: "Title VI and language access for people with limited English proficiency",
    type: "external_reference",
    authority: "external_verify",
    layer: "L4",
    summary:
      "Federal Title VI obligations require recipients of federal funds to provide meaningful language access. The federal LEP site collects guidance and resources. Verify at the source.",
    body: [
      "This program does not interpret Title VI. Before releasing a vital document, follow the current language-access requirements for qualified human review and confirm them with the person responsible for language access in your program.",
    ],
    nextActions: [{ label: "Language access checklist", href: "/resources/ja-language-access-checklist" }],
    tags: ["Title VI", "LEP", "language access", "federal", "external", "law"],
    intents: ["policy_orientation", "uncertainty_authority", "access_barriers"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://www.lep.gov/",
    sourceName: "U.S. Department of Justice, Federal Coordination and Compliance Section",
    version: V,
  },
  {
    id: "ext-dhs-equity-toolkit",
    title: "DHS Equity Analysis Toolkit",
    type: "external_reference",
    authority: "external_verify",
    layer: "L4",
    summary:
      "The DHS Equity Analysis Toolkit helps staff consider who is affected, what evidence is available, and which barriers and alternatives matter. It also addresses access, responsibility, and review. Use the current version available through DHS.",
    body: [
      "The checklist and impact questions in this program can help you prepare, but they do not replace the DHS Equity Analysis Toolkit. Confirm the current toolkit and any required process with the appropriate DHS contact.",
    ],
    nextActions: [
      { label: "Equity and access checklist for new work", href: "/resources/ja-launch-embed-checklist" },
      { label: "Equity impact questions", href: "/resources/ja-equity-impact-questions" },
    ],
    tags: ["toolkit", "equity analysis", "DHS", "scan", "full analysis", "external"],
    intents: ["policy_orientation", "practice_method", "uncertainty_authority"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    sourceName: "Minnesota DHS (intranet)",
    version: V,
  },
];

export function getContent(id: string): ContentItem | undefined {
  return CORPUS.find((c) => c.id === id);
}

/** Staff-default corpus: approved items only ('Under review' is not staff-default). */
export function staffCorpus(): ContentItem[] {
  return CORPUS.filter((c) => c.status === "approved");
}
