import type { ContentItem } from "./types";

/**
 * Domain collection (September 5, 2026 reconstruction).
 *
 * These items convert the recovered domain analysis into staff-usable material across the
 * workforce, policy and service, engagement, access, culture, leadership, and measurement areas,
 * plus tool and framework cards. They were drafted during the reconstruction from the owner's
 * decision baseline and the content recovery report. Each carries the same authority, owner,
 * review-date, scope, and accessibility fields as the permanent seed collection.
 *
 * Release posture: build-authored material is approved for the static staff collection by the
 * owner's reconstruction direction and is listed in the domain release manifest for item-level
 * review. Legal, policy, and institutional claims point to external sources labeled "check before use".
 */

const OWNER = "Equity and Inclusion Operations Consultant";
const REVIEW = "2027-03-01";
const V = "0.2.0";
const PROVENANCE = "Drafted September 5, 2026 from the reconstruction decision baseline and the content recovery report; owner item-level review recorded in the domain release manifest.";

export const DOMAIN_CORPUS: ContentItem[] = [
  /* ---------- Workforce equity ---------- */
  {
    id: "ja-inclusive-hiring-lifecycle",
    title: "Inclusive hiring lifecycle: eight stages from role design to outcomes",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "An eight-stage structure for hiring that tests what the work really requires, opens outreach, uses structured review and interviews, normalizes accommodation, builds bias reflection into deliberation, makes the offer transparent, and examines outcomes stage by stage.",
    whyItMatters:
      "Credential gatekeeping and vague culture-fit judgments were among the clearest advancement barriers DSD staff described. Each stage of hiring is a decision with an owner, so each can be changed.",
    body: [
      "Stage 1. Test essential duties and remove excessive credential barriers. Write down what the job actually requires people to do. For each degree, years-of-experience, or licensure requirement, ask whether it predicts that work or stands in for it. Name credible alternatives such as lived experience, community work, or demonstrated skill.",
      "Stage 2. Expand accessible outreach beyond familiar networks. Post where people outside your usual circles will see it, in plain language, with the salary range and the accommodation statement visible. Ask community partners to share it and tell them how to reach a human.",
      "Stage 3. Use structured review and job-relevant rubrics. Screen every application against the same written criteria tied to the work. Record the reason for each decision so the process can be checked later.",
      "Stage 4. Normalize accommodations without forcing disclosure. Offer accommodation for every stage in the same sentence you use for scheduling. Make the offer to everyone so no one has to identify as disabled to receive it.",
      "Stage 5. Use structured interviews and avoid vague culture fit. Ask every candidate the same core questions tied to the rubric. Replace culture fit with the specific behaviors the team needs, such as working across difference or explaining a decision to a family.",
      "Stage 6. Make bias reflection part of deliberation. Before deciding, have the panel name what impressed them and check it against the rubric. Ask what the panel might be rewarding that is not job related, such as fluency, confidence, or familiarity.",
      "Stage 7. Provide a transparent offer and onboarding. Explain how the salary was set and what advancement requires. Plan the first weeks so a new person knows who to ask and how decisions get made.",
      "Stage 8. Examine stage-by-stage outcomes and improve the process. With your HR partner, look at who applied, who advanced at each stage, and who was hired, at a level that protects small groups. Change the stage where people drop out.",
      "What this is not. This is practice guidance. Selection procedures, classification, labor agreements, and civil-rights obligations are governed by Human Resources, labor relations, and law. Bring this plan to those partners rather than around them.",
    ],
    nextActions: [
      { label: "Start the inclusive hiring and selection path", href: "/paths/gp-6" },
      { label: "Test whether a requirement is job related", href: "/resources/ja-job-relatedness-check" },
      { label: "Plan an accessible interview", href: "/resources/ja-accessible-meetings" },
    ],
    tags: ["hiring", "selection", "workforce", "credentials", "rubric", "accommodation", "onboarding"],
    intents: ["practice_method", "workplace_culture", "next_actions"],
    pathIds: ["gp-6"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "ja-job-relatedness-check",
    title: "Is this requirement job related? A short check before you keep it",
    type: "checklist",
    authority: "guidance",
    layer: "L2",
    summary:
      "A five-question check for any degree, experience, screening, or interview requirement: what work does it predict, what evidence supports that, who does it screen out, what alternative shows the same ability, and who signed off.",
    whyItMatters:
      "Federal guidance on employee selection expects employers to examine procedures that produce adverse impact and to have evidence that they are job related. This check helps you ask those questions before a posting goes out, without removing qualifications the work really needs.",
    body: [
      "Question 1. What part of the work does this requirement predict? Write the specific tasks. If you cannot name them, the requirement may be a proxy.",
      "Question 2. What evidence do we have that it predicts that work? Consider whether current strong performers all meet it, and whether people without it have done the work well elsewhere.",
      "Question 3. Who does this requirement screen out? Think about communities, first-generation professionals, people who built skills outside formal education, and people with disabilities who took different paths.",
      "Question 4. What alternative shows the same ability? Consider a work sample, a portfolio, described experience, a certification, or a structured question in the interview.",
      "Question 5. Who reviewed and signed off? Note the hiring manager, the HR partner, and, where practice calls for it, the Equity Director. Keep the reasoning with the posting.",
      "Do not remove qualifications categorically. Some work requires a license or a specific credential. The point is to know what the work genuinely requires and which credible forms of experience demonstrate capability.",
    ],
    nextActions: [
      { label: "Read the eight-stage inclusive hiring lifecycle", href: "/resources/ja-inclusive-hiring-lifecycle" },
      { label: "Check the federal selection guidelines summary", href: "/resources/tool-eeoc-uniform-guidelines" },
    ],
    tags: ["hiring", "qualifications", "job related", "adverse impact", "credentials"],
    intents: ["practice_method", "policy_orientation", "next_actions"],
    pathIds: ["gp-6"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "pn-pay-classification-advancement",
    title: "Pay, classification, and advancement: what a supervisor can change and what needs a partner",
    type: "practice_note",
    authority: "practice_note",
    layer: "L3",
    summary:
      "Advancement barriers are often invisible: unclear pathways, visible work given by habit, and classification questions that no one owns. This note separates what a supervisor can change this month from what needs Human Resources, labor relations, or leadership.",
    whyItMatters:
      "DSD staff described inconsistent recognition of work and lived experience, classification and pay concerns, and unclear pathways. These are patterns, not individual failings, and they respond to practice.",
    body: [
      "What you can change now. Say out loud what advancement requires in your unit and write it down. Rotate visible assignments deliberately instead of by who is closest. Hold a career conversation with every person, not only the ones who ask. Sponsor people into rooms where decisions are made, not only mentor them about how rooms work.",
      "What needs a partner. Classification questions, reclassification requests, pay equity reviews, and anything governed by a labor agreement go to Human Resources and labor relations. Bring the pattern you noticed and the people affected in general terms, not a case for one person.",
      "What to watch for. Reverse mentoring can be valuable, but it should not become unpaid equity labor for staff from underrepresented communities. Development plans should not be treated as proof of competence or as a hidden record.",
      "Questions to ask yourself. Who on the team has had a stretch assignment in the last year, and how did that come to be? Who has been told plainly what the next step requires? Whose work is visible to leadership, and whose is not?",
    ],
    nextActions: [
      { label: "Mentoring, sponsorship, and reverse mentoring", href: "/resources/pn-mentoring-sponsorship" },
      { label: "Stay conversations and retention", href: "/resources/pn-stay-interviews-and-retention" },
      { label: "Strengthen team climate (Practice path)", href: "/paths/gp-4" },
    ],
    tags: ["advancement", "pay", "classification", "promotion", "sponsorship", "supervisor"],
    intents: ["workplace_culture", "practice_method", "escalation"],
    pathIds: ["gp-4"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "pn-mentoring-sponsorship",
    title: "Mentoring, sponsorship, and reverse mentoring: three different things",
    type: "practice_note",
    authority: "practice_note",
    layer: "L2",
    summary:
      "Mentoring explains how things work. Sponsorship puts your credibility behind someone in a room they are not in. Reverse mentoring lets leaders learn from staff with different experience, if it is voluntary and does not become extra unpaid work.",
    whyItMatters:
      "People who are new to an organization's informal rules often get plenty of advice and very little sponsorship. Advancement usually depends on the second.",
    body: [
      "Mentoring. Regular conversations about how decisions are made, what the next role requires, and how to prepare. Useful, and usually not enough on its own.",
      "Sponsorship. A leader names a person for a stretch assignment, a panel, a project lead role, or a promotion conversation, and stands behind that recommendation. Sponsorship is where advancement actually happens. Track, at a level that protects individuals, who gets sponsored.",
      "Reverse mentoring. A leader learns from a staff member whose experience differs from theirs. It works when the leader asks for it, the staff member chooses it, the time is recognized as work, and the leader acts on what they learn. It fails when it becomes a standing expectation placed on staff from underrepresented communities.",
      "A practical start. Ask each leader in your unit to name one person they will sponsor this quarter and for what. Review the list for who is missing.",
    ],
    nextActions: [
      { label: "Pay, classification, and advancement", href: "/resources/pn-pay-classification-advancement" },
      { label: "Leadership and systems change area", href: "/domains/leadership-systems" },
    ],
    tags: ["mentoring", "sponsorship", "reverse mentoring", "leadership", "advancement"],
    intents: ["workplace_culture", "practice_method"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "pn-stay-interviews-and-retention",
    title: "Stay conversations: learning why people stay before they leave",
    type: "practice_note",
    authority: "practice_note",
    layer: "L2",
    summary:
      "A stay conversation asks a current team member what keeps them, what would make them leave, and what they would change. It is a conversation, not an evaluation, and its value depends on what the supervisor does afterward.",
    whyItMatters:
      "Exit patterns arrive too late to act on. Stay conversations surface barriers while there is still time, and they signal that a person's experience matters.",
    body: [
      "Before. Tell the person what the conversation is and is not. Explain that the conversation is for understanding the employee experience rather than assigning a performance rating. Agree what may be recorded or shared and explain applicable limits; do not promise absolute confidentiality or that no record can exist. Offer to hold it in whatever setting works for them.",
      "During. Ask open questions. What do you look forward to here? What would make you consider leaving? What have you wanted to say that you have not had a chance to? What would you change about how work is assigned or recognized? Listen more than you speak.",
      "After. Choose one thing you can change and tell the person what it is. If a pattern appears across several conversations, take the pattern, not the names, to your leadership or Equity Director.",
      "Boundaries. If the conversation raises a complaint about a named person, harassment, or discrimination, stop and connect the person to the confidential channel. Do not investigate and do not record it here.",
    ],
    nextActions: [
      { label: "Team climate action plan template", href: "/resources/ja-climate-action-plan" },
      { label: "When a question needs a human, and which human", href: "/resources/pn-when-to-escalate" },
    ],
    tags: ["retention", "stay interview", "supervisor", "team", "exit"],
    intents: ["workplace_culture", "practice_method", "escalation"],
    pathIds: ["gp-4"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },

  /* ---------- Policy, program, and service ---------- */
  {
    id: "ja-operational-equity-canvas",
    title: "Operational equity review canvas: eight steps for any decision",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "One pattern that works for policies, forms, services, contracts, budgets, communications, technology, and program design: clarify the decision, identify affected people, examine evidence, name assumptions and risks, compare options, choose accountable owners, define accessible implementation, and schedule follow-up.",
    whyItMatters:
      "Equity cannot be confined to awareness content. This canvas turns it into the working steps of an actual decision while the decision can still change.",
    body: [
      "Step 1. Clarify the decision. What exactly is being decided, by whom, and by when? What is already fixed and what is still open?",
      "Step 2. Identify affected people. Who benefits, who carries the burden, and who is missing from the room? Consider community, language, disability, age, place, and the people who deliver the service.",
      "Step 3. Examine evidence. What do we know by community, language, disability, and place? What do people who use the service say? What does the evidence not show?",
      "Step 4. Name assumptions and risks. What are we assuming about people's access, time, documents, technology, or trust? What could go wrong for the people with the least margin?",
      "Step 5. Compare options. Lay out at least two alternatives and compare who each helps and burdens. Include the option of not proceeding.",
      "Step 6. Choose accountable owners. Who owns each part of implementation and each follow-up? Name people, not units.",
      "Step 7. Define accessible implementation. How will people learn about the change, in which languages and formats, with what human alternative? What burden can still be removed?",
      "Step 8. Schedule follow-up. When will you look at what happened, what will you look at, and who will report back to the people who gave input?",
      "Any figures used as examples in training materials are illustrations, not DSD evidence. Use the real data owners for real numbers.",
    ],
    nextActions: [
      { label: "Equity analysis for a decision (Practice path)", href: "/paths/gp-7" },
      { label: "Equity scan or full analysis: what goes in", href: "/resources/ja-equity-scan-or-full-analysis" },
      { label: "Equity impact questions", href: "/resources/ja-equity-impact-questions" },
    ],
    tags: ["equity review", "decision", "canvas", "policy", "budget", "program", "implementation"],
    intents: ["practice_method", "launch_embed", "next_actions"],
    pathIds: ["gp-7", "gp-1", "gp-10"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "ja-equity-scan-or-full-analysis",
    title: "Equity scan or full equity analysis: what goes in and who decides which applies",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "The DHS equity policy makes an equity analysis part of some decisions. This aid explains the difference between a scan and a full analysis, what each contains, and how to use the Minnesota Equity Analysis Toolkit while the decision can still change. The policy owner decides which applies.",
    whyItMatters:
      "The policy verifies mandatory equity analysis for prolonged or long-term actions going to leadership and other named uses. Doing it well means engaging while choices are open, not documenting after they close.",
    body: [
      "Supports a required process. This page helps you do the analysis well. It is not the official record. The completed analysis is kept where your division or the policy owner keeps decision records. Check the current policy and toolkit version with the policy owner before relying on this summary.",
      "Determine whether a scan or a full analysis applies. A scan is a brief, structured check for decisions with limited reach. A full analysis is the complete process for prolonged or long-term actions and decisions that go to leadership. When in doubt, ask the policy owner or your Equity Director.",
      "Form the right team. Include the decision owner, the people who hold relevant data, staff who deliver the service, and the equity professional for your area. Plan community engagement early enough to change the decision.",
      "Define the decision and the outcomes you want. Write the decision in one sentence and the outcomes in terms of people, not process.",
      "Use quantitative, qualitative, and community evidence. Disaggregate by community, language, disability, and place where the data allows, protect small groups, and record what the evidence does not show.",
      "Identify benefits and burdens. Who gains, who pays, and how do burdens fall on people who already carry more?",
      "Develop alternatives. At least two, compared on benefits and burdens. Include the alternative of not proceeding.",
      "Plan implementation, communication, monitoring, and evaluation. Name owners, languages and formats, the human alternative, what you will watch, and when you will look again.",
      "Report back. Tell the people who gave input what changed and what did not, and why.",
    ],
    nextActions: [
      { label: "Equity analysis for a decision (Practice path)", href: "/paths/gp-7" },
      { label: "Minnesota Equity Analysis Toolkit", href: "/resources/ext-dhs-equity-toolkit" },
      { label: "Operational equity review canvas", href: "/resources/ja-operational-equity-canvas" },
    ],
    tags: ["equity analysis", "equity scan", "equity policy", "toolkit", "leadership decision", "compliance"],
    intents: ["policy_orientation", "practice_method", "launch_embed"],
    pathIds: ["gp-7"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "ja-procurement-contract-equity",
    title: "Equity in contracts, grants, and procurement: where the questions belong",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "Equity belongs in the solicitation, the evaluation criteria, the contract terms, and the monitoring. This aid names the questions for each stage and the partners who own the rules.",
    whyItMatters:
      "Contracts decide who delivers services and how. Adding equity language after award changes little. Procurement and grants offices own the rules; equity professionals help shape the questions in time.",
    body: [
      "Before the solicitation. Who will the service reach, and in which languages and formats? Which communities have providers that could deliver it but rarely win awards, and why? What accessibility requirements apply to the deliverables?",
      "In the solicitation. State accessibility, language access, and community-engagement expectations as requirements, not preferences. Make the application process itself accessible and plain, with a human contact.",
      "In evaluation. Score demonstrated experience with the communities served, accessibility practice, and workforce practice, using written criteria applied the same way to every proposal.",
      "In the contract. Include reporting that lets you see who is served, disaggregated with small-group protection, and a way to raise and fix access problems during the term.",
      "In monitoring. Look at outcomes by community, language, disability, and place with the data owner, and bring what you learn to the next solicitation.",
      "Who owns what. Procurement rules, vendor diversity programs, and contract language have their own owners. Bring these questions to your contracts office and Equity Director before the solicitation is final.",
    ],
    nextActions: [
      { label: "Procurement or contract equity review (Practice path)", href: "/paths/gp-10" },
      { label: "Operational equity review canvas", href: "/resources/ja-operational-equity-canvas" },
    ],
    tags: ["procurement", "contracts", "grants", "vendor diversity", "solicitation", "monitoring"],
    intents: ["launch_embed", "practice_method", "policy_orientation"],
    pathIds: ["gp-10"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "lm-disability-rights-and-service-delivery",
    title: "Disability rights and service delivery: the frameworks DSD works within",
    type: "learning_module",
    authority: "learning",
    layer: "L3",
    summary:
      "An orientation to person-centered planning, supported decision-making, LifeCourse, the ADA and Olmstead, home and community-based services, employment-first practice, and positive supports, and to what each asks of a service design.",
    whyItMatters:
      "Equity in disability services is inseparable from disability rights. A redesign that adds steps, removes choice, or assumes incapacity can be inaccessible and inequitable at once.",
    body: [
      "Person-centered planning. The person directs the plan; the system organizes around their goals, relationships, and preferences. Ask how a process lets the person lead rather than respond.",
      "Supported decision-making. People have the right to make their own decisions with support they choose. Ask whether a process assumes incapacity or offers support.",
      "LifeCourse. A framework for thinking about a good life across a lifetime, using the person's vision and a mix of supports. Useful for planning conversations; it is one framework among several.",
      "ADA and Olmstead. The Americans with Disabilities Act and the Olmstead decision require services in the most integrated setting appropriate. Ask whether a design steers people toward segregated settings by default.",
      "Home and community-based services and employment-first practice. Services in the community and competitive, integrated employment as the first option. Ask whether eligibility, assessment, and authorization steps make the community option harder than the institutional one.",
      "Positive supports. Approaches that build skills and quality of life rather than relying on restriction. Ask whether a process responds to behavior with support or with control.",
      "Each legal or policy claim above needs the current source. Use the external references in the Library and the policy owner for anything that affects a person's eligibility, rights, or services.",
    ],
    nextActions: [
      { label: "ADA Title II reference", href: "/resources/ext-ada" },
      { label: "Operational equity review canvas", href: "/resources/ja-operational-equity-canvas" },
      { label: "One DSD area", href: "/one-dsd" },
    ],
    tags: ["disability rights", "person-centered", "supported decision-making", "LifeCourse", "Olmstead", "HCBS", "employment first", "positive supports"],
    intents: ["policy_orientation", "practice_method"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },

  /* ---------- Community engagement ---------- */
  {
    id: "ja-engagement-influence-ladder",
    title: "Engagement that shares influence: inform, consult, involve, collaborate, co-design",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "Five levels of influence, from informing people about a decision to designing it with them. Choose one honestly, say it plainly, and match the supports, compensation, and report-back to it.",
    whyItMatters:
      "The most common harm in engagement is asking for input that cannot change anything. Naming the level of influence protects trust and tells people what their time is worth.",
    body: [
      "Inform. You tell people what is happening and why. Appropriate when the decision is already made. Say so.",
      "Consult. You ask for input and decide. Appropriate when choices are open and you will explain what you did with the input.",
      "Involve. People work with you throughout and their concerns shape the options. Appropriate when the decision affects them directly and the timeline allows.",
      "Collaborate. People share in developing options and in the decision. Appropriate when you can share authority and want the result to be owned together.",
      "Co-design. People with lived experience lead the design with you. Appropriate when the service is theirs and you are prepared to change how it works.",
      "For any level, plan these. Begin before the decision is fixed. Identify who is affected and who is missing. Understand prior contacts so you do not repeat requests or extract labor. Address compensation, language, disability access, format, schedule, setting, technology, and trusted messenger. Document what was heard, what changed, what could not change, and why. Assign an owner for the ongoing relationship.",
      "Tribal Nations. Do not treat Tribal consultation as community engagement. Sovereignty and government-to-government responsibilities have separate sources, roles, and routing. Contact the Office of Indian Policy or your Tribal liaison first.",
    ],
    nextActions: [
      { label: "Community engagement or co-design (Practice path)", href: "/paths/gp-3" },
      { label: "Report back on what was heard and what changed", href: "/resources/ja-report-back" },
      { label: "Partner map", href: "/resources/ja-stakeholder-map" },
    ],
    tags: ["engagement", "co-design", "influence", "consultation", "community", "compensation", "report back"],
    intents: ["intercultural", "practice_method", "launch_embed"],
    pathIds: ["gp-3"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "ja-report-back",
    title: "Reporting back: what we heard, what changed, what could not, and why",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "A short, accessible record for the people who gave input: what they said in their words, what changed because of it, what could not change and why, and what happens next with a named contact.",
    whyItMatters:
      "DSD's engagement review found that people rarely learned what happened after they gave input. Closing that loop is the difference between engagement and extraction.",
    body: [
      "What we heard. Summarize the main themes in plain language, using participants' own words where you have permission. Do not identify anyone.",
      "What changed. List the decisions or designs that changed because of the input, specifically.",
      "What could not change, and why. Be direct. If a rule, budget, or law prevented a change, say which one and who owns it.",
      "What happens next. Dates, the next chance to influence the work, and a named person people can contact.",
      "How to share it. Use the same languages, formats, and channels the engagement used. Send it to the partners who helped convene, and ask them to pass it on.",
      "Keep it short. One page is usually right. Link to more if people want it.",
    ],
    nextActions: [
      { label: "Engagement that shares influence", href: "/resources/ja-engagement-influence-ladder" },
      { label: "Plain language and accessible documents", href: "/resources/ja-plain-language" },
    ],
    tags: ["report back", "engagement", "feedback loop", "trust", "community"],
    intents: ["intercultural", "practice_method", "next_actions"],
    pathIds: ["gp-3"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "pn-cultural-humility-briefs-as-questions",
    title: "Using community material as questions, not descriptions",
    type: "practice_note",
    authority: "practice_note",
    layer: "L2",
    summary:
      "A community brief or cultural guide is a starting point for respectful inquiry. It can help you ask better questions and plan access. It cannot tell you what any one person wants, believes, or needs.",
    whyItMatters:
      "Generalizations about literacy, oral traditions, health beliefs, or family roles become stereotypes the moment they are applied to a person. The safeguard is a habit: ask, then plan.",
    body: [
      "Read a brief for what to ask, not what to conclude. Turn every statement into a question you could ask the person or the community partner.",
      "Notice the diversity inside every community. Immigration history, faith, language, disability, age, and class differ within a community as much as between communities.",
      "Plan access from what people tell you. Language, interpreter, format, timing, setting, technology, and trusted messenger are decisions to make with people, not for them.",
      "Say what you do not know. A brief that leaves a self-description pending is telling you to go ask.",
      "Check the source. Community material needs authoritative sources and community review before it becomes a program fact. Material still in review is marked, and it is not a description of anyone.",
    ],
    nextActions: [
      { label: "Prepare for intercultural work without making assumptions", href: "/resources/pn-intercultural-method" },
      { label: "Explore Minnesota Communities", href: "/minnesota-communities" },
    ],
    tags: ["cultural humility", "community brief", "assumptions", "stereotype", "intercultural"],
    intents: ["intercultural", "practice_method", "boundary_refusal"],
    pathIds: ["gp-3"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },

  /* ---------- Accessibility and language access ---------- */
  {
    id: "ja-accessible-meetings",
    title: "Accessible and culturally responsive meetings: before, during, and after",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "Send purpose and materials ahead, offer accommodation without forcing disclosure, give people several ways to take part, watch positional power, repair when harm occurs, end with clear decisions and owners, and follow up accessibly.",
    whyItMatters:
      "Meetings are where participation is won or lost. Camera use, eye contact, speed, and silence are not universal evidence of engagement, and treating them that way excludes people.",
    body: [
      "Before. Send the purpose, agenda, and materials at least a few working days ahead in an accessible format. Include the accommodation sentence in every invitation: tell us what you need to take part fully. Turn captions on by default. Check the room or platform for physical, sensory, and technology access.",
      "During. Open with the purpose and how decisions will be made. Offer several ways to contribute: speaking, writing in advance, writing in chat, or following up afterward. Rotate who opens and who summarizes. Read written input aloud so it carries the same weight. Watch who is speaking and who is not, and notice positional power in the room. Slow down when interpretation or captioning is in use.",
      "When harm occurs. Name it, pause, and make repair the responsibility of the person with more power in the room. Do not ask the person harmed to explain or to fix it. Follow up privately with the people involved.",
      "Ending. State each decision, its owner, and its date. Say what happens to input that was not used.",
      "After. Send accessible notes with decisions and owners in the same channels people used. Ask how the meeting worked for people and change the next one.",
      "Notice periods, captioning accuracy claims, and accommodation instructions should follow your division's current accessibility guidance. Check with your accessibility lead.",
    ],
    nextActions: [
      { label: "Plan an accessible meeting (Practice path)", href: "/paths/gp-8" },
      { label: "Access checks before a meeting or outreach", href: "/resources/ja-access-checks" },
      { label: "Team climate basics", href: "/resources/lm-workplace-climate" },
    ],
    tags: ["meetings", "accessibility", "captions", "participation", "positional power", "repair", "facilitation"],
    intents: ["access_barriers", "workplace_culture", "facilitation"],
    pathIds: ["gp-8", "gp-4", "gp-5"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "ja-language-cultural-access-planning",
    title: "Language and cultural access planning aid for a program or contact point",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "Plan language, format, messenger, communication mode, and program design together, using the CLAS standards as a frame: who the program reaches, which languages and formats they need, how an interpreter is available at first contact, which documents are vital, and who reviews translations.",
    whyItMatters:
      "Language access decided one document at a time produces gaps at the first phone call. Planning at the program level puts interpreter availability, translation, and trusted messengers where people actually arrive.",
    body: [
      "Who the program reaches. Use the data owner's information and community partners to name the languages and communities, and note what the data does not show.",
      "First contact. How does a person who does not use English reach a human, in their language, on the first try? Phone, front desk, web, and mail each need an answer.",
      "Vital documents. Identify documents that affect eligibility, rights, benefits, or safety. These need translation and human review before release. Machine translation alone is not enough for vital documents.",
      "Formats. Plain language, large print, accessible electronic documents, audio, and in-person explanation. Ask which formats people use, not which are easiest to produce.",
      "Trusted messengers. Who do people in each community already trust for information? Partner with them and compensate the work.",
      "Cultural responsiveness. Use community material as questions. Check assumptions about family roles, health beliefs, and literacy with the community, not from a guide.",
      "Review and owners. Name who owns the plan, who reviews translations, and when the plan is checked again.",
      "The CLAS standards and DHS language access practice are the authority for these decisions. Check current guidance with your language access coordinator.",
    ],
    nextActions: [
      { label: "Language access checklist", href: "/resources/ja-language-access-checklist" },
      { label: "CLAS standards reference", href: "/resources/ext-clas" },
      { label: "Working with an interpreter", href: "/resources/lm-interpreter" },
    ],
    tags: ["language access", "CLAS", "interpreter", "translation", "vital documents", "trusted messenger", "cultural responsiveness"],
    intents: ["access_barriers", "intercultural", "launch_embed"],
    pathIds: ["gp-1", "gp-2"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "lm-plain-language-carries-complexity",
    title: "Plain language carries complexity: it does not remove it",
    type: "learning_module",
    authority: "learning",
    layer: "L2",
    summary:
      "Plain language helps readers find, understand, and use information. It reduces the work of reading, not the depth of the content. Use progressive disclosure: an immediate answer, why it matters, questions to consider, a practical tool, evidence and sources, and deeper theory for those who want it.",
    whyItMatters:
      "Staff are educated adults doing hard work. Talking down to them costs trust. Burying them costs time. Plain language done well respects both.",
    body: [
      "Start with the answer. Put the main point in the first sentence and the action in the first paragraph.",
      "One idea per sentence. About twenty words. Prefer the common word unless the precise term matters, and then define it once.",
      "Layer the depth. Short answer, why it matters, questions to consider, a tool to use, the sources, and the deeper material. Readers choose how far to go.",
      "Keep intellectual depth. A plain sentence can carry a sophisticated idea. Cutting nuance is not plain language; it is a different message.",
      "Test it. Read it aloud. Ask a colleague what they would do after reading it. If they are unsure, the writing is not finished.",
      "Federal plain-language guidance and DHS plain-language practice are the sources for style decisions. Check DHS examples when they are supplied to you.",
    ],
    nextActions: [
      { label: "Plain language and accessible documents checklist", href: "/resources/ja-plain-language" },
      { label: "Change a form, notice, or policy (Practice path)", href: "/paths/gp-2" },
    ],
    tags: ["plain language", "writing", "progressive disclosure", "communication", "reading level"],
    intents: ["access_barriers", "practice_method"],
    pathIds: ["gp-2"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },

  /* ---------- Culture, intercultural practice, and trust ---------- */
  {
    id: "lm-psychological-safety-and-repair",
    title: "Psychological safety and repair: practices, not personality",
    type: "learning_module",
    authority: "learning",
    layer: "L2",
    summary:
      "People speak when speaking is safe and useful. Safety is built through observable practices: how disagreement is handled, how mistakes are treated, who carries repair, and whether input changes anything.",
    whyItMatters:
      "DSD staff described limited psychological safety, performance pressure, and doubt that their input changes decisions. Those are practice problems with practice answers.",
    body: [
      "Make disagreement normal. Ask for the strongest case against your own idea before deciding. Thank the person who raised the concern, in front of others.",
      "Separate unfamiliarity from intentional harm. Most harm at work comes from not knowing. Respond to unfamiliarity with information and a chance to change. Respond to intentional harm through the confidential channel.",
      "Put repair on the person with more power. When a comment or decision lands badly, the leader names it and takes responsibility for repair. The person harmed should not have to explain, educate, or forgive on a schedule.",
      "Show that input changed something. Every month, say what changed because someone spoke up. If nothing did, say why.",
      "Watch the grind. Constant urgency silences people. Protect time for thinking and for saying no.",
      "None of this replaces the confidential channel. Complaints, harassment, and discrimination go to Employee Culture, Human Resources, or the civil-rights channel.",
    ],
    nextActions: [
      { label: "Team climate basics", href: "/resources/lm-workplace-climate" },
      { label: "Strengthen team climate (Practice path)", href: "/paths/gp-4" },
      { label: "Accessible and culturally responsive meetings", href: "/resources/ja-accessible-meetings" },
    ],
    tags: ["psychological safety", "repair", "team", "trust", "disagreement", "supervisor"],
    intents: ["workplace_culture", "practice_method", "escalation"],
    pathIds: ["gp-4"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "lm-power-and-positional-authority",
    title: "Positional power: seeing it, naming it, and using it well",
    type: "learning_module",
    authority: "learning",
    layer: "L3",
    summary:
      "Supervisors, managers, and people with expertise or tenure hold power that shapes who speaks, who is believed, and whose time counts. Seeing it is the first intercultural skill; using it deliberately is the second.",
    whyItMatters:
      "Dominant-culture defaults feel like neutrality to the people they serve. Naming positional power lets a leader change a room instead of asking others to adapt to it.",
    body: [
      "Where power sits. Role, tenure, credential, language fluency, familiarity with the organization, race, disability, and who the process was designed for all shape who is heard.",
      "What it does. People with less power wait to be asked, soften disagreement, and stop offering ideas that were ignored once. People with more power mistake that quiet for agreement.",
      "What to do with it. Speak last. Ask the newest and the quietest first. Credit ideas to the person who had them. Change the format so contribution does not depend on speaking fast in English.",
      "In supervision. Ask what the person needs from you rather than telling them what you need. Make expectations explicit so people do not have to guess the unwritten rules.",
      "Across difference. Cultural humility means assuming you do not know how your habits land and asking. The Intercultural Development Inventory can help a person see their own orientation; it is one tool, used by qualified administrators, and never a label or a rating.",
    ],
    nextActions: [
      { label: "Prepare for intercultural work without making assumptions", href: "/resources/pn-intercultural-method" },
      { label: "The IDI and the tool registry", href: "/resources/pn-idi-and-tool-registry" },
    ],
    tags: ["power", "positional authority", "supervision", "intercultural", "cultural humility", "personal growth", "self-reflection"],
    intents: ["intercultural", "workplace_culture", "practice_method"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "lm-intersectionality-foundations",
    title: "Intersectionality: why one category at a time misses people",
    type: "learning_module",
    authority: "learning",
    layer: "L3",
    summary:
      "Race, disability, language, gender, age, class, and immigration status shape people's experience together, not one at a time. A program that reviews outcomes by one category can look equitable while failing the people at the intersections.",
    whyItMatters:
      "Legacy data and program rules were built around single categories. Intersectional thinking changes what you disaggregate, who you engage, and which burdens you notice.",
    body: [
      "The idea. Coined in legal scholarship to describe how discrimination against Black women was invisible to claims that looked at race or sex alone. The same pattern appears in services: a deaf Somali elder's experience is not the sum of three separate briefs.",
      "In data. Ask the data owner what can be disaggregated by more than one category with small-group protection. Where numbers are too small, use qualitative evidence and say so.",
      "In engagement. Ask who is missing at the intersections, and plan access for people who face more than one barrier at once, such as interpretation and captioning together.",
      "In design. Test a process against the person with the least margin: the person who needs an interpreter, an accessible format, transportation, and a daytime alternative all at once.",
      "In the workplace. Advancement barriers and climate problems land differently on people who hold more than one marginalized identity. Ask, do not assume.",
    ],
    nextActions: [
      { label: "Structural racism and institutions", href: "/resources/lm-structural-racism-and-institutions" },
      { label: "Measuring without surveillance", href: "/resources/pn-measurement-without-surveillance" },
    ],
    tags: ["intersectionality", "disaggregation", "identity", "structural", "analysis"],
    intents: ["intercultural", "practice_method", "policy_orientation"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "lm-structural-racism-and-institutions",
    title: "Structural racism and institutional power: how neutral rules produce unequal results",
    type: "learning_module",
    authority: "learning",
    layer: "L4",
    summary:
      "Structural racism is the way policies, practices, and norms across institutions produce and maintain racial inequity without requiring anyone's intent. Recognizing it means examining rules, defaults, and histories, not searching for villains.",
    whyItMatters:
      "A program rule can be written without bias and still produce disparities because of the history and conditions it lands on. Equity work that stops at intent cannot change that.",
    body: [
      "History matters. Housing, employment, education, disability services, and public benefits carry histories of exclusion that shape who arrives at your program, with what resources, and with what trust.",
      "Neutral rules are not neutral results. A documentation requirement, a daytime appointment, an English-only phone line, or a degree requirement each lands differently depending on that history.",
      "Institutions reproduce what they do not examine. Defaults persist because they work for the people who set them. Examination is a practice: who benefits, who is burdened, what would change if we chose differently.",
      "Whiteness as a default. Norms about professionalism, communication, time, and expertise often reflect one culture's habits presented as standards. Naming that is not an accusation; it is a design observation.",
      "What to do. Connect the analysis to a decision with an owner. Use the equity review canvas, the data owner, and the community's own account. Change the rule, the default, or the resource, and look again.",
      "This module is an orientation. Deeper research and frameworks are in the Library's external references, each labeled as a public source to check before use.",
    ],
    nextActions: [
      { label: "Intersectionality foundations", href: "/resources/lm-intersectionality-foundations" },
      { label: "Operational equity review canvas", href: "/resources/ja-operational-equity-canvas" },
      { label: "GARE Racial Equity Toolkit reference", href: "/resources/tool-gare-racial-equity-toolkit" },
    ],
    tags: ["structural racism", "institutional power", "history", "defaults", "analysis", "oppression"],
    intents: ["policy_orientation", "practice_method", "intercultural"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "pn-idi-and-tool-registry",
    title: "The IDI and other tools: inputs to practice, not the practice itself",
    type: "practice_note",
    authority: "practice_note",
    layer: "L3",
    summary:
      "The Intercultural Development Inventory is one proprietary assessment among many tools. It can inform qualified professional practice. It does not define this program, its results are never personnel data, and its protected content is not reproduced here.",
    whyItMatters:
      "A single instrument can quietly become the program's definition of competence. That is a governance risk. A registry of tools with owners, evidence, limits, and permitted uses keeps every tool in its place.",
    body: [
      "What the IDI is. A licensed intercultural assessment administered by qualified administrators. It describes a developmental orientation toward cultural difference and is used for individual and group development.",
      "What it is not. It is not a measure of competence for selection, promotion, or performance. A result or an inferred orientation must never become an employee record, an access gate, or a hidden label in this program.",
      "What this program does with it. Describes it, names its owner and license, and routes people to qualified administration if their division offers it. Protected content is not reproduced.",
      "The same discipline applies to every tool. The Minnesota Equity Analysis Toolkit, the GARE Racial Equity Toolkit, CLAS, LifeCourse, implicit-association resources, accessibility methods, and engagement frameworks each have an owner, an evidence base, a license or public status, required qualifications, limits, and permitted uses. The tool cards in the Library record them.",
      "Practical application is decided through the consultant-led, equity-professional-informed practice, in collaboration with Equity Directors, Specialists, and committee members. No tool decides it.",
    ],
    nextActions: [
      { label: "Tool card: Intercultural Development Inventory", href: "/resources/tool-idi" },
      { label: "Tool card: Implicit-association resources", href: "/resources/tool-implicit-association" },
      { label: "Positional power", href: "/resources/lm-power-and-positional-authority" },
    ],
    tags: ["IDI", "intercultural", "tool registry", "assessment", "license", "governance", "personal growth", "own culture", "self-reflection"],
    intents: ["intercultural", "policy_orientation", "boundary_refusal"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },

  /* ---------- Leadership, role-aware support, measurement ---------- */
  {
    id: "pn-role-aware-entry",
    title: "Start from the work you are doing: role-aware entry points",
    type: "practice_note",
    authority: "practice_note",
    layer: "L1",
    summary:
      "A policy analyst designing a program, a hiring manager planning recruitment, a fiscal analyst shaping a budget, and a supervisor preparing a hard conversation need different doors into the same equity knowledge. This program organizes by task and role so you do not have to learn the whole subject to do the next piece well.",
    whyItMatters:
      "Generic awareness training rarely changes a decision. Support that recognizes what you are trying to do can.",
    body: [
      "Program and policy staff usually start with the equity review canvas, the equity analysis path, or the new-program checklist.",
      "Supervisors and managers usually start with team climate, stay conversations, accessible meetings, or advancement practice.",
      "Hiring managers and HR partners usually start with the inclusive hiring lifecycle and the job-relatedness check.",
      "Fiscal, contracts, and procurement staff usually start with procurement equity and the review canvas.",
      "Communications and language access staff usually start with plain language, accessible documents, and the language and cultural access planning aid.",
      "Data, research, and quality staff usually start with measuring without surveillance and the disaggregation guidance.",
      "Service delivery and support planning staff usually start with disability rights and service delivery, community material as questions, and access checks.",
      "Equity Directors and Specialists use all of it and, in the One DSD area, can contribute and review material for their scope.",
      "Role names, responsibilities, and reporting relationships change. If a door does not fit your work, use Ask and describe what you are doing.",
    ],
    nextActions: [
      { label: "Start here", href: "/start" },
      { label: "Areas of work", href: "/domains" },
    ],
    tags: ["roles", "entry point", "task", "navigation", "role-aware"],
    intents: ["next_actions", "practice_method"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "pn-measurement-without-surveillance",
    title: "Measuring whether equity work is working, without scoring people",
    type: "practice_note",
    authority: "practice_note",
    layer: "L3",
    summary:
      "Tell the difference between a platform that works and a program that improves equity. Use a logic model, baselines, mixed methods, disaggregation with small-group protection, and honest limits. Never use individual learning, participation, or assessment results as performance data.",
    whyItMatters:
      "Invented targets, composite scores without validation, and individualized learning surveillance destroy trust and prove nothing. Good measurement is possible and protects people.",
    body: [
      "Two different questions. Does the platform work: can people find, use, and apply material? Does the program improve equity practice or outcomes: are decisions, services, and workplace patterns changing? Measure both, separately.",
      "Logic model. Inputs and activities, outputs, outcomes, and impact. Write what you expect to change and by when before you measure.",
      "Baselines first. No causal claim without a baseline. If there is no baseline, say so and start one.",
      "Mixed methods. Numbers show patterns; people's accounts show why. Use both, and give qualitative evidence equal standing.",
      "Disaggregate with protection. By community, language, disability, and place where the data allows. Set the smallest group you will report, and suppress below it. Ask the data owner about denominators.",
      "Protect private learning. Learning, reflection, Ask, and practice paths are private. Report only combined totals that cannot identify anyone, and never use them for supervision or evaluation.",
      "Never use assessment results as performance data. Intercultural assessments and similar instruments describe development; they are not scores of competence and must not enter personnel decisions.",
      "State the limits. Every report says what the evidence does not show. That sentence is what makes the rest trustworthy.",
    ],
    nextActions: [
      { label: "Measurement and accountability area", href: "/domains/measurement" },
      { label: "Six commitments for working in partnership", href: "/resources/pn-partnership-spine" },
    ],
    tags: ["measurement", "evaluation", "logic model", "baseline", "disaggregation", "privacy", "surveillance"],
    intents: ["practice_method", "policy_orientation", "boundary_refusal"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },

  /* ---------- Tool and framework cards ---------- */
  {
    id: "tool-idi",
    title: "Tool card: Intercultural Development Inventory (IDI)",
    type: "tool",
    authority: "external_verify",
    layer: "L4",
    summary:
      "A proprietary, licensed intercultural assessment administered by qualified administrators. Purpose: individual and group intercultural development. Permitted program use: describe, route to qualified administration, discuss developmental orientations in general terms. Not permitted: reproducing protected content, using results for selection, performance, access, or profiling.",
    body: [
      "Owner and publisher: IDI, LLC. Status: proprietary and licensed. Required qualification: qualified administrator.",
      "Purpose: describes a developmental orientation toward cultural difference along a continuum from monocultural to intercultural mindsets. This program's continuum draws on both: the licensed IDI instrument describes five orientations — Denial, Polarization, Minimization, Acceptance, and Adaptation — and Bennett's developmental model contributes the sixth, Integration. The full continuum moves from not noticing cultural difference, through judging it, through treating it as unimportant next to human sameness, toward genuinely valuing, adapting to, and integrating multiple cultural frames. Used for coaching, group development, and planning.",
      "Evidence base: published validity research by the instrument's developers and independent studies; check current literature.",
      "Limits: describes orientation, not competence or character. Results depend on honest self-report and on qualified debrief. It is not a hiring, promotion, or evaluation instrument.",
      "Misuse risks: treating a stage as a rating, comparing people, using results as personnel data, reproducing licensed content, building hidden profiles.",
      "Program use: this program may describe the IDI and route to qualified administration. It does not administer, score, store, or interpret individual results, and it does not reproduce licensed material. The owner's source record keeps the phrase IBI orientation as an alias for supplied IDI material.",
      "Related tools: implicit-association resources, cultural humility practice, CLAS standards.",
    ],
    nextActions: [
      { label: "The IDI and other tools as inputs to practice", href: "/resources/pn-idi-and-tool-registry" },
    ],
    tags: ["IDI", "tool card", "intercultural", "assessment", "proprietary", "personal growth", "own culture", "self-reflection"],
    intents: ["intercultural", "policy_orientation", "boundary_refusal"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://www.idiinventory.com/",
    sourceName: "IDI, LLC",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "tool-gare-racial-equity-toolkit",
    title: "Tool card: GARE Racial Equity Toolkit",
    type: "tool",
    authority: "external_verify",
    layer: "L4",
    summary:
      "The Government Alliance on Race and Equity describes racial equity tools as structured ways to integrate explicit consideration of racial equity into decisions, policies, practices, programs, and budgets. Public. Permitted use: cite, link, adapt the method with attribution.",
    body: [
      "Owner and publisher: Government Alliance on Race and Equity (GARE). Status: public resource; check reuse terms before reproducing text.",
      "Purpose: a step-by-step process for analyzing a proposal's racial equity impacts, engaging communities, developing strategies, and evaluating results.",
      "Evidence base: practice-based, used across many jurisdictions; the Minnesota Equity Analysis Toolkit is in this lineage.",
      "Limits: a process, not a data source. Quality depends on engagement and evidence. Race-explicit by design; combine with disability, language, and place analysis.",
      "Program use: cite and adapt the method through the equity review canvas and the equity analysis path.",
    ],
    nextActions: [
      { label: "Operational equity review canvas", href: "/resources/ja-operational-equity-canvas" },
      { label: "Minnesota Equity Analysis Toolkit", href: "/resources/ext-dhs-equity-toolkit" },
    ],
    tags: ["GARE", "tool card", "racial equity", "toolkit", "decision"],
    intents: ["policy_orientation", "practice_method"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://www.racialequityalliance.org/",
    sourceName: "Government Alliance on Race and Equity",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "tool-mn-equity-toolkit",
    title: "Tool card: Minnesota Equity Analysis Toolkit",
    type: "tool",
    authority: "external_verify",
    layer: "L4",
    summary:
      "The State of Minnesota's official equity analysis toolkit, published by Minnesota Management and Budget, used with the DHS Equity Policy. Public. Permitted use: cite, link, follow. The policy owner determines when it is required.",
    body: [
      "Owner and publisher: Minnesota Management and Budget. Status: official State resource.",
      "Purpose: a structured process for state agencies to analyze the equity effects of decisions, engage affected communities, compare alternatives, and plan implementation and evaluation.",
      "Relationship to DHS: the DHS Equity Policy requires equity analysis for named decisions and uses this toolkit. The policy owner and your Equity Director confirm which version and process applies.",
      "Limits: a process. It does not supply data or community relationships; those come from the data owner and engagement.",
      "Program use: the equity analysis path and the scan-or-full-analysis aid follow it. This program is not the official record.",
    ],
    nextActions: [
      { label: "Equity scan or full analysis: what goes in", href: "/resources/ja-equity-scan-or-full-analysis" },
      { label: "Minnesota Equity Analysis Toolkit reference", href: "/resources/ext-dhs-equity-toolkit" },
    ],
    tags: ["Minnesota", "equity analysis", "toolkit", "tool card", "MMB"],
    intents: ["policy_orientation", "practice_method"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://mn.gov/mmb/",
    sourceName: "Minnesota Management and Budget",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "tool-clas-standards",
    title: "Tool card: National CLAS Standards",
    type: "tool",
    authority: "external_verify",
    layer: "L4",
    summary:
      "The National Standards for Culturally and Linguistically Appropriate Services, published by the U.S. Department of Health and Human Services Office of Minority Health. Public. Permitted use: cite, link, follow as a frame for language and cultural access planning.",
    body: [
      "Owner and publisher: U.S. Department of Health and Human Services, Office of Minority Health. Status: public federal standards.",
      "Purpose: fifteen standards for governance, workforce, communication and language assistance, and engagement, continuous improvement, and accountability.",
      "Limits: standards, not a plan. Fidelity depends on local implementation and community review. Cultural material still needs sourcing and humility.",
      "Program use: the language and cultural access planning aid uses the standards as its frame.",
    ],
    nextActions: [
      { label: "CLAS standards reference", href: "/resources/ext-clas" },
      { label: "Language and cultural access planning aid", href: "/resources/ja-language-cultural-access-planning" },
    ],
    tags: ["CLAS", "tool card", "language access", "cultural responsiveness"],
    intents: ["access_barriers", "policy_orientation"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://thinkculturalhealth.hhs.gov/clas",
    sourceName: "HHS Office of Minority Health",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "tool-lifecourse",
    title: "Tool card: Charting the LifeCourse",
    type: "tool",
    authority: "external_verify",
    layer: "L4",
    summary:
      "A framework and set of tools for people with disabilities and families to plan a good life across the lifespan, developed at the University of Missouri Kansas City Institute for Human Development. Some materials are licensed; check reuse terms. Permitted use: cite, link, use published tools within their terms.",
    body: [
      "Owner and publisher: LifeCourse Nexus, University of Missouri Kansas City Institute for Human Development. Status: published framework; some tools carry use terms.",
      "Purpose: person-centered planning across life domains using the person's vision, trajectory, and an integrated mix of supports.",
      "Limits: one planning framework among several. Quality depends on the person leading the conversation.",
      "Program use: referenced in service-delivery orientation and in DSD planning scenarios. Tools are linked, not reproduced.",
    ],
    nextActions: [
      { label: "Disability rights and service delivery", href: "/resources/lm-disability-rights-and-service-delivery" },
    ],
    tags: ["LifeCourse", "tool card", "person-centered", "planning", "disability"],
    intents: ["practice_method", "policy_orientation"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://www.lifecoursetools.com/",
    sourceName: "LifeCourse Nexus",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "tool-implicit-association",
    title: "Tool card: implicit-association resources",
    type: "tool",
    authority: "external_verify",
    layer: "L4",
    summary:
      "Public research tools that demonstrate automatic associations. Useful for individual reflection about how bias can operate without awareness. Not a measure of a person's bias, not predictive of behavior on their own, and never a workplace assessment.",
    body: [
      "Owner and publisher: research collaborations such as Project Implicit. Status: public research tools with their own terms.",
      "Purpose: demonstrate that automatic associations exist and can differ from stated beliefs.",
      "Evidence base and limits: substantial research on the existence of implicit associations; considerable debate about individual-level reliability and prediction of behavior. Treat results as a reflection prompt, not a diagnosis.",
      "Misuse risks: labeling a person as biased, using results in hiring or evaluation, treating a single result as stable.",
      "Program use: reference for voluntary private reflection only. The program does not administer, store, or discuss individual results.",
    ],
    nextActions: [
      { label: "The IDI and other tools as inputs to practice", href: "/resources/pn-idi-and-tool-registry" },
    ],
    tags: ["implicit bias", "implicit association", "tool card", "reflection", "personal growth", "own culture", "self-reflection"],
    intents: ["intercultural", "boundary_refusal"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://implicit.harvard.edu/implicit/",
    sourceName: "Project Implicit",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "tool-eeoc-uniform-guidelines",
    title: "Tool card: Uniform Guidelines on Employee Selection Procedures (EEOC)",
    type: "tool",
    authority: "external_verify",
    layer: "L4",
    summary:
      "Federal guidelines on employee selection procedures and the U.S. Equal Employment Opportunity Commission's questions and answers about them. They require careful attention to selection procedures that produce adverse impact and to evidence of job relatedness and validity. Public. Permitted use: cite and link; HR and legal partners interpret.",
    body: [
      "Owner and publisher: U.S. Equal Employment Opportunity Commission and partner agencies. Status: public federal guidance.",
      "Purpose: guidance on how selection procedures should be examined for adverse impact and supported by evidence of job relatedness.",
      "Limits: guidance, applied by HR and legal partners. Do not remove qualifications categorically on the basis of this card; determine what the work requires.",
      "Program use: the job-relatedness check and the inclusive hiring lifecycle follow its questions in practice terms.",
    ],
    nextActions: [
      { label: "Is this requirement job related?", href: "/resources/ja-job-relatedness-check" },
      { label: "Inclusive hiring lifecycle", href: "/resources/ja-inclusive-hiring-lifecycle" },
    ],
    tags: ["EEOC", "selection", "adverse impact", "job related", "tool card"],
    intents: ["policy_orientation", "practice_method"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://www.eeoc.gov/laws/guidance/questions-and-answers-clarify-and-provide-common-interpretation-uniform-guidelines",
    sourceName: "U.S. Equal Employment Opportunity Commission",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "tool-mn-accessibility-standard",
    title: "Tool card: State of Minnesota accessibility standard",
    type: "tool",
    authority: "external_verify",
    layer: "L4",
    summary:
      "The State of Minnesota digital accessibility standard, currently Section 508 plus WCAG 2.1 Level A and AA, and the accessible document guidance that accompanies it. Public. This program keeps WCAG 2.2 Level AA as its own stronger release target.",
    body: [
      "Owner and publisher: Minnesota IT Services and Minnesota Management and Budget. Status: official State standard.",
      "Purpose: the accessibility floor for State digital content, systems, and documents.",
      "Program posture: WCAG 2.2 Level AA is this program's release target, which is stronger than the current State floor.",
      "Program use: accessible document and meeting guidance follow it. Check the current version with your accessibility lead.",
    ],
    nextActions: [
      { label: "Minnesota accessibility reference", href: "/resources/ext-mn-accessibility" },
      { label: "Plain language and accessible documents", href: "/resources/ja-plain-language" },
    ],
    tags: ["accessibility", "WCAG", "Section 508", "Minnesota", "tool card"],
    intents: ["access_barriers", "policy_orientation"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://mn.gov/mnit/about-mnit/accessibility/",
    sourceName: "Minnesota IT Services",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "ext-emerging-leaders-institute",
    title: "State of Minnesota Emerging Leaders Institute",
    type: "external_reference",
    authority: "external_verify",
    layer: "L4",
    summary:
      "The verified public leadership program is the State of Minnesota Emerging Leaders Institute, administered by Minnesota Management and Budget. Public evidence does not document a DHS-owned program by that name. Check eligibility and the current cycle at the source.",
    body: [
      "What it is: a State leadership development program for employees, administered by Minnesota Management and Budget.",
      "Why it is here: leadership pathways should connect to programs that exist. Correcting the record matters; an earlier draft described a DHS-owned Emerging Leaders program that public evidence does not support.",
      "How to use it: check eligibility, timing, and the nomination process at the source. Supervisors can use sponsorship to make sure people from underrepresented communities know about it and are nominated.",
    ],
    nextActions: [
      { label: "Mentoring, sponsorship, and reverse mentoring", href: "/resources/pn-mentoring-sponsorship" },
    ],
    tags: ["leadership", "Emerging Leaders", "MMB", "development"],
    intents: ["policy_orientation", "next_actions"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    href: "https://mn.gov/mmb/",
    sourceName: "Minnesota Management and Budget",
    provenance: PROVENANCE,
    version: V,
  },
  /* ---------- Accessible leadership pathways for staff with disabilities ---------- */
  {
    id: "pn-accessible-leadership-pathways",
    title: "Accessible leadership pathways and sponsorship for staff with disabilities",
    type: "practice_note",
    authority: "practice_note",
    layer: "L3",
    summary:
      "For staff with disabilities, advancement barriers are usually structural and often invisible to the people who run leadership pathways. This note adapts the engagement, analysis, and applied-practice sequence to that reality: hear from disabled staff without forcing disclosure, examine the pipeline stage by stage, and build sponsorship, transparent pathway maps, and accessible leadership programs by default.",
    whyItMatters:
      "Disclosure is a cost. Many staff will not identify as disabled to a supervisor or a program, so pathway design cannot depend on knowing who is disabled. It has to be accessible to everyone and honest about what leadership roles actually require.",
    body: [
      "Engagement without forced disclosure. Work through anonymous aggregate listening, disability employee resource groups, and trusted intermediaries, with small-group suppression in any reporting. Ask about the pathway, not the person: what does it take to be seen as ready for a lead role here, who explains it, and what happens when someone asks for an accommodation during a stretch assignment or interview.",
      "Close the loop publicly. Disabled staff in particular have watched accessibility promises go unfunded. Report what changed, what did not, and who owns the next step.",
      "Examine the pipeline stage by stage: nomination to leadership programs, selection for visible projects, acting assignments, interview formats, and promotion outcomes. Disability is often absent from disaggregated workforce data, so the first finding may be that the organization cannot see the pattern at all. Say so.",
      "Test the job-relatedness of leadership criteria. Executive presence, quick verbal response, travel, long hours, and always-on availability screen out many disabled staff and are rarely tied to what leaders actually do.",
      "Look for the accommodation cliff. Accommodations that exist for the current role are often lost during a rotation, a leadership cohort, or an interview process because nobody owns them across the transition. Name an owner for accommodations across every transition.",
      "Sponsorship, not just mentoring. Mentoring gives advice; sponsorship puts someone's name forward. Pair disabled staff who want it with sponsors who hold decision power, and track at the program level whether sponsorship leads to assignments.",
      "Reverse mentoring, where disabled staff advise leaders on what accessible leadership looks like, with compensation or recognized time and never as a standing expectation.",
      "Accessible leadership programs by default: materials in advance, captioning, flexible participation formats, no timed or drag-based activities, and accommodations carried across every cohort event. The State of Minnesota Emerging Leaders Institute run by Minnesota Management and Budget is the verified public program; DHS-level pathways should be reviewed against the same standard.",
      "Transparent pathway maps that say what a lead or supervisor role requires, which experiences count, and how to get them, so advancement does not depend on informal networks.",
      "Structured leadership interviews with rubrics tied to the work, accommodations offered without asking why, and panel preparation on disability bias.",
      "Stay conversations that ask about growth and access together, and exit patterns reviewed at an appropriate level.",
      "Boundaries this program keeps. No guessing about disability: the program never guesses who is disabled from behavior, accommodation history, or participation. No individual tracking: private learning and reflection stay private, and program-level measures use aggregates with suppression. Accommodation requests, complaints, and personnel decisions go to the confidential channels, never into this program.",
      "Who owns what. ADA and accommodation decisions belong to Human Resources and the accommodation process. Pathway design belongs to leadership and the equity practice. Take each to its owner.",
    ],
    nextActions: [
      { label: "Build a leadership pathway or sponsorship plan (Practice path)", href: "/paths/gp-11" },
      { label: "Leadership criteria: are they job related?", href: "/resources/ja-leadership-criteria-job-relatedness" },
      { label: "Accommodations across transitions", href: "/resources/ja-accommodation-across-transitions" },
      { label: "Mentoring, sponsorship, and reverse mentoring", href: "/resources/pn-mentoring-sponsorship" },
    ],
    tags: ["disability", "leadership pathways", "sponsorship", "advancement", "accommodation", "reverse mentoring", "disclosure"],
    intents: ["workplace_culture", "practice_method", "access_barriers", "escalation"],
    pathIds: ["gp-11", "gp-4"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "ja-leadership-criteria-job-relatedness",
    title: "Leadership criteria: are they job related, or do they screen out disabled staff?",
    type: "checklist",
    authority: "guidance",
    layer: "L2",
    summary:
      "A check for the informal and formal criteria used to nominate, select, and promote people into lead roles: executive presence, quick verbal response, travel, long hours, always-on availability, and similar. For each one, name what leaders actually do that it predicts, or replace it.",
    whyItMatters:
      "Leadership criteria are rarely written down and rarely tested. The ones that live in people's heads tend to reward a narrow style of presence and stamina rather than the work of leading.",
    body: [
      "List every criterion actually used. Include the unwritten ones: who gets called confident, who is seen as ready, who is invited to present.",
      "For each criterion, write the leadership work it predicts. Decisions made, people developed, conflicts resolved, plans delivered, communities served. If you cannot connect it to that work, it is a proxy.",
      "Ask who each criterion screens out. Quick verbal response screens out people who process or communicate differently. Travel and long hours screen out people with energy, mobility, or care constraints. Always-on availability screens out most people with a disability and many without one.",
      "Replace proxies with observable leadership behaviors and give people several ways to show them: written work, a portfolio, a structured conversation, a work sample with time to prepare.",
      "Offer accommodation for every stage in the same sentence you use for scheduling, to everyone, without asking why.",
      "Prepare the panel on disability bias before the interviews, and use a written rubric applied the same way to everyone.",
      "Record who reviewed the criteria: leadership, the HR partner, and the Equity Director. Keep the reasoning with the pathway map.",
    ],
    nextActions: [
      { label: "Accessible leadership pathways and sponsorship", href: "/resources/pn-accessible-leadership-pathways" },
      { label: "Is this requirement job related?", href: "/resources/ja-job-relatedness-check" },
      { label: "Build a leadership pathway or sponsorship plan (Practice path)", href: "/paths/gp-11" },
    ],
    tags: ["leadership", "criteria", "job related", "disability", "promotion", "interview"],
    intents: ["practice_method", "workplace_culture", "access_barriers"],
    pathIds: ["gp-11", "gp-6"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
  {
    id: "ja-accommodation-across-transitions",
    title: "Accommodations across transitions: closing the accommodation cliff",
    type: "job_aid",
    authority: "guidance",
    layer: "L2",
    summary:
      "Accommodations that work in the current role are often lost during a rotation, an acting assignment, a leadership cohort, or an interview process because nobody owns them across the transition. This aid names the transitions, the owner for each, and what to carry.",
    whyItMatters:
      "The cliff is invisible to the people who design pathways and very visible to the people who fall off it. Naming an owner for accommodations across each transition is a small change that removes a structural barrier.",
    body: [
      "Transitions to plan for: nomination and application, interview or selection event, acting or stretch assignment, leadership cohort or program, new team or new supervisor, and return from leave.",
      "For each transition, name one owner responsible for carrying existing accommodations forward and for offering accommodation to everyone entering it. The owner is a person, not a process.",
      "Carry the accommodation, not the diagnosis. The receiving supervisor or program needs to know what works, not why. The accommodation process holds the confidential record.",
      "Offer accommodation to everyone at every transition, in the same sentence used for logistics, so no one has to disclose to receive it.",
      "Design cohort events accessible by default: materials in advance, captioning, flexible participation formats, no timed or drag-based activities, and time to rest.",
      "Check after the transition. Ask everyone, not only people who requested something, whether the arrangements worked, and fix what did not.",
      "Boundaries. Accommodation decisions and disputes belong to Human Resources and the accommodation process. This aid is about pathway design and ownership; it does not decide any accommodation.",
    ],
    nextActions: [
      { label: "Accessible leadership pathways and sponsorship", href: "/resources/pn-accessible-leadership-pathways" },
      { label: "Accessible and culturally responsive meetings", href: "/resources/ja-accessible-meetings" },
      { label: "Find the right person", href: "/support/right-person?matter=advancement_or_leadership_pathway" },
    ],
    tags: ["accommodation", "transition", "disability", "leadership cohort", "rotation", "acting assignment"],
    intents: ["access_barriers", "practice_method", "escalation"],
    pathIds: ["gp-11"],
    owner: OWNER,
    reviewDate: REVIEW,
    status: "approved",
    scope: "agencywide",
    accessibility: "pending",
    provenance: PROVENANCE,
    version: V,
  },
];

export const DOMAIN_CORPUS_IDS = DOMAIN_CORPUS.map((item) => item.id);
