import { defineEditableSurface, type EditableSurfaceValues } from "./editable-surface-contract";
import { WORK_PROFILES } from "./work-learning";

// Companion learning structure, not a replacement for official toolkit steps.
export const EAT_STAGES = [
  { id: "decision" }, { id: "people" }, { id: "options" },
  { id: "participation" }, { id: "review" },
] as const;
export type EquityToolkitStageId = (typeof EAT_STAGES)[number]["id"];
export const EAT_ROLES = WORK_PROFILES.map(([id]) => ({ id }));
export const EAT_CHOICES = ["a", "b", "c"] as const;
export const EAT_DRAFT_FIELDS = EAT_STAGES.map(({ id }) => ({ id: `${id}Draft` as const, stageId: id }));

const wording: EditableSurfaceValues = {
  title: "Equity Analysis Toolkit",
  intro: "Examine how a decision may affect people differently, consider alternatives, and prepare for a conversation about what should happen next.",
  companionNote: "These five learning stages are a program companion, not the official toolkit sequence. Optional practice does not replace the toolkit, required review, or engagement with affected people.",
  roleLabel: "Your area of work", roleIntro: "Choose an area to connect the example with your responsibilities. You can explore any area.",
  noRoleLabel: "Explore without choosing an area", stageNavLabel: "Learning stages",
  objectivesTitle: "After this stage, you can", scenarioTitle: "Try a fictional example",
  consequenceTitle: "What this choice brings into view", practiceLabel: "Optional practice", workLabel: "Your actual work",
  draftTitle: "Your working draft", draftIntro: "Keep your actual work separate from the fictional example. These notes support discussion; they are not an approval or a completed equity review.",
  draftPrivacy: "Use a general description of the work. Do not enter names, case details, or other confidential information. Keep any copy only in a location permitted for your work.",
  draftRetention: "Your notes disappear when you leave or reload this page. Print or save your draft before leaving if you want to keep a copy.",
  backLabel: "Learning and resources",
  clearLabel: "Clear my draft", clearConfirmLabel: "Clear all draft notes", cancelLabel: "Keep my notes", clearedMessage: "Your draft notes have been cleared.",
  printLabel: "Print or save my draft", nextLabel: "Next stage", previousLabel: "Previous stage",
  resourcesTitle: "Toolkit and related resources", resourcesIntro: "Open resources at any time. You do not need to finish a lesson or practice activity.",
  resourceTitle: "Official policy and related resources",
  resourceIntro: "The DHS equity policy and toolkit resource are available here without completing the learning stages. Follow DHS instructions for access to internal materials and any required review. This companion does not submit work to DHS or grant approval. DHS requirements should not be treated as requirements for every Minnesota agency.",
  toolkitLabel: "Open the Equity Analysis Toolkit", briefsLabel: "Explore community briefs",
  scenarioNote: "All people, records, and events in this example are fictional. The consequences illustrate questions to consider; they are qualitative examples, not predictions of real outcomes.",
  culturalContext: "Community briefs can help you ask more informed questions. They do not tell you what an individual believes, needs, or prefers. Confirm preferences with the person and involve affected communities in real decisions.",
  authorityNote: "The people responsible for the decision retain authority. A practice response cannot establish community agreement or replace direct engagement.",
  decisionTitle: "Describe the decision",
  decisionIntro: "Start with the decision itself: what is changing, what can still be changed, and who can decide. A clear scope helps people contribute while their input can still matter.",
  decisionObjectives: ["Write a one-sentence description of the decision.", "Distinguish fixed conditions from choices still open.", "Identify who has decision authority.", "Locate the related questions in the official toolkit."],
  decisionScenario: "A service team is considering replacing mailed appointment reminders with text messages. Alex Rivera works changing shifts and shares one phone with Elena, who helps manage appointments and prefers written information in Spanish. These are their stated circumstances, not assumptions based on their names. What should the team clarify first?",
  decisionChoicea: "Choose text messages now and discuss implementation later.",
  decisionConsequencea: "In this fictional continuation, Elena raises the shared-phone concern after the proposal has been presented as settled. Ask which choices remain open and whether people can still influence them.",
  decisionChoiceb: "Define the reminder decision, its limits, and who can authorize a change.",
  decisionConsequenceb: "The team separates the reminder method from rules it has no authority to change. It can now ask people about options that are genuinely open, while confirming applicable requirements with the responsible reviewer.",
  decisionChoicec: "Keep the existing process without further discussion.",
  decisionConsequencec: "Another fictional household reports unreliable mail delivery. Keeping the process also has effects worth examining; the team still needs to understand the problem and its authority to respond.",
  decisionDraftLabel: "The decision and its limits", decisionDraftHelp: "Describe the decision, what can change, and who has authority. Name any requirement that still needs to be confirmed.",
  peopleTitle: "Consider who may be affected",
  peopleIntro: "Look for differences in access, benefits, and burdens. Separate what the evidence shows from what you are assuming, and identify whose experience is missing.",
  peopleObjectives: ["Identify people who may experience the decision differently.", "Separate evidence from assumptions.", "Name an information gap or missing perspective.", "Write a respectful question to learn more."],
  peopleScenario: "The fictional records show that a text reached Alex's phone. They do not show whether Elena could read it in time. Another household member uses a screen reader, and a different household prefers mail for privacy. What information would you seek?",
  peopleChoicea: "Treat successful delivery as evidence that the reminder was usable.",
  peopleConsequencea: "The delivery record answers a narrow question. It cannot establish who read the message, whether it was understandable, or whether using it was private and accessible.",
  peopleChoiceb: "Ask staff which reminder method most people prefer.",
  peopleConsequenceb: "Staff describe recurring difficulties, which helps identify questions. Their experience does not establish each person's preferences or replace hearing directly from people using the service.",
  peopleChoicec: "Combine available records with accessible conversations about preferences and barriers.",
  peopleConsequencec: "Elena explains when she can access the shared phone. Other people describe different needs. The team has richer information but still checks who could not participate and avoids treating one family as representative of a community.",
  peopleDraftLabel: "People, evidence, and unanswered questions", peopleDraftHelp: "Note potential differences in experience, the evidence available, and whose perspective you still need. Avoid identifying individual clients.",
  optionsTitle: "Compare possible approaches",
  optionsIntro: "Compare workable alternatives, including the current approach. Consider who gains convenience, who takes on additional work, and what could make each approach more accessible.",
  optionsObjectives: ["Describe at least two feasible approaches.", "Identify a potential benefit and burden of each.", "Explain how an adjustment addresses a specific barrier.", "State what remains uncertain before a choice is made."],
  optionsScenario: "The team considers three approaches. In the fictional example, Alex wants texts, Elena needs information she can read in Spanish, and another household relies on paper reminders. Choose an approach to examine, not a final answer.",
  optionsChoicea: "Use text messages as the only reminder method.",
  optionsConsequencea: "Alex sees a reminder quickly during a break, but Elena cannot access the shared phone when she needs it. The team must examine language, shared-device access, privacy, and alternatives for people who cannot use texts.",
  optionsChoiceb: "Continue mailing every reminder.",
  optionsConsequenceb: "A household that prefers paper keeps its familiar method. Another household receives a reminder late. Keeping mail does not resolve all access concerns, and the team needs evidence about those remaining barriers.",
  optionsChoicec: "Offer a choice of reminder methods and confirm communication preferences.",
  optionsConsequencec: "Different households can request different methods. Staff then identify the work needed to record, honor, and update those preferences. Choice deserves examination alongside staffing, accessibility, privacy, and applicable requirements; it is not automatically the best answer in every setting.",
  optionsDraftLabel: "Options and tradeoffs", optionsDraftHelp: "Compare two or more approaches. Include possible benefits, burdens, adjustments, and uncertainties rather than predicting results.",
  participationTitle: "Plan participation and action",
  participationIntro: "Identify who should help shape the decision and what would make participation possible. Explain what people can influence and how they will hear what happened to their input.",
  participationObjectives: ["Identify who should help shape the decision.", "Propose an accessible way to seek participation.", "Assign a responsible person to a proposed action.", "Explain how participants will hear what happened to their input."],
  participationScenario: "Before recommending a reminder approach, the team wants to hear from service users. Alex cannot attend a daytime meeting. Elena would prefer a conversation in Spanish. Which engagement plan would you examine?",
  participationChoicea: "Send one English-only online questionnaire.",
  participationConsequencea: "In the fictional responses, people comfortable with that channel are heard more readily. The team has not established what people excluded by language, disability access, connectivity, or confidence with forms would say.",
  participationChoiceb: "Ask an advisory group to speak for every household.",
  participationConsequenceb: "The group contributes useful experience and questions. Its members cannot represent every household's circumstances. The team still needs to identify missing perspectives and accessible ways to hear them.",
  participationChoicec: "Offer several accessible ways to participate and explain what remains open.",
  participationConsequencec: "People have more ways to contribute, and the team plans language and disability access with participants. It still needs time, responsible staff, and a clear account of how input affected the decision. This practice cannot supply actual community agreement.",
  participationDraftLabel: "Participation and next actions", participationDraftHelp: "Identify people to involve, participation supports, decisions they can influence, responsible staff, and how you will report back.",
  reviewTitle: "Review and revisit",
  reviewIntro: "Plan how people will examine what happens after a decision. Choose information that can reveal problems, name its limits, and agree on when the decision needs another look.",
  reviewObjectives: ["Identify an observable signal worth reviewing.", "Explain what that signal cannot establish.", "Name who will review the information.", "Specify a condition that would prompt reconsideration."],
  reviewScenario: "Suppose the responsible decision-makers authorize a limited change after the required review and engagement. The team now needs a follow-up plan. What would you recommend examining?",
  reviewChoicea: "Count delivered messages and call the change successful if delivery improves.",
  reviewConsequencea: "The count helps assess delivery but does not establish comprehension, access, privacy, or fair outcomes. It could miss a problem even when more messages reach their destinations.",
  reviewChoiceb: "Wait for complaints before scheduling a review.",
  reviewConsequenceb: "Complaints may reveal an important problem, but some people may not know how or feel able to raise one. Without a planned review, silence could be mistaken for evidence that the approach works for everyone.",
  reviewChoicec: "Review several signals with responsible staff and affected people at an agreed time.",
  reviewConsequencec: "The team considers delivery, reported usability, staff workload, and people not reached. It names the limits of each source and agrees what would trigger reconsideration. Those observations inform the team's judgment rather than proving that one change caused an outcome.",
  reviewDraftLabel: "Review responsibilities and reconsideration", reviewDraftHelp: "Name useful signals, their limits, a review date, responsible people, and a condition that would prompt another discussion.",
};

const roleContexts: Record<(typeof WORK_PROFILES)[number][0], string> = {
  leadership: "Consider the decision authority, unresolved tradeoffs, and responsibility for follow-through. Ask what evidence and engagement are needed before a direction is approved.",
  policy: "Compare the reminder options, distinguish policy requirements from local choices, and describe uncertainty in the recommendation.",
  service: "Consider what a person must do to receive and use a reminder. Record barriers for the responsible decision-maker without assuming authority to change policy.",
  management: "Examine staff capacity, consistent practice, and how staff can raise concerns. Identify the support needed to honor communication preferences.",
  workforce: "Consider the skills, learning time, and support staff need to provide accessible service. Examine whether expectations create unequal access to development opportunities.",
  fiscal: "Examine implementation costs and work shifted to households or staff. Identify resource questions without inventing cost estimates or assuming the least expensive option is the fairest.",
  data: "Distinguish message delivery from usable communication. Examine missing information, the limits of comparisons, and whose experiences the available records cannot show.",
  engagement: "Plan how affected people can influence the reminder decision. Consider language, disability access, timing, trust, and how participants will hear what changed.",
  communication: "Examine whether each reminder is understandable and usable in the needed language and format. Plan appropriate translation, accessibility review, and review with service users.",
  equity: "Connect a specific access barrier with the wider decision process. Identify responsible partners and how engagement and follow-through will remain part of the work.",
};

export const EQUITY_TOOLKIT_SURFACE = defineEditableSurface({
  surfaceId: "equity-toolkit.home", route: "/learn/equity-toolkit", scopePolicy: "inheritable", label: "Equity Analysis Toolkit companion",
  fields: [
    ...Object.entries(wording).map(([key, value]) => ({ key, label: key, kind: Array.isArray(value) ? "string-list" as const : "long" as const, required: true, ...(Array.isArray(value) ? { maxItems: 5 } : {}) })),
    { key: "supportingResources", label: "Toolkit and related resource links", kind: "link-list", required: true, maxItems: 20 },
    ...WORK_PROFILES.flatMap(([id]) => [
      { key: `${id}Label`, label: `${id}: name`, kind: "short" as const, required: true },
      { key: `${id}Context`, label: `${id}: work connection`, kind: "long" as const, required: true },
    ]),
  ],
  approvedValues: {
    ...wording,
    supportingResources: [
      { label: "DHS equity policy", href: "https://mn.gov/dhs/assets/equity-policy_tcm1053-646921.pdf" },
      { label: "Equity Analysis Toolkit resource and access details", href: "/library/ext-dhs-equity-toolkit" },
      { label: "Minnesota community briefs", href: "/minnesota-communities" },
      { label: "Learning for your work", href: "/my-work/explore" },
    ],
    ...Object.fromEntries(WORK_PROFILES.flatMap(([id, label]) => [[`${id}Label`, label], [`${id}Context`, roleContexts[id]]])),
  },
});
