/**
 * Practice paths added in the September 5, 2026 reconstruction (GP-6 to GP-10).
 * Same contract as GP-1 to GP-5: scaffold, practice with real work, review, optional handoff.
 * Every path is voluntary and private. GP-7 supports a required DHS process without being its record.
 */
import type { GraduationPath, RubricRule } from "./paths";

const COMMON_RUBRIC: RubricRule[] = [
  { key: "owners", label: "Every follow-up has a named owner", failMessage: "Please name the person responsible for each follow-up." },
  { key: "review_date", label: "A next review date is set", failMessage: "Please choose a specific date to review this work again." },
  { key: "specific_work", label: "This is connected to your specific work", failMessage: "Please name the position, decision, meeting, or contract this is for." },
];

const ACCESS_RULE: RubricRule = { key: "access", label: "Language, disability, and communication access were considered for this work", failMessage: "Please note the access checks you completed, including language, disability and communication access, and the effort the process asks of people." };
const INVOLVED_RULE: RubricRule = { key: "involved", label: "You named who was involved and the role they had", failMessage: "Please list who was involved before the decision was settled and what role or authority they had." };
const NOT_ASSUMED_RULE: RubricRule = { key: "not_assumed", label: "You noted what you chose not to assume", failMessage: "Please note what you chose not to assume about the people affected." };
const SOURCES_RULE: RubricRule = { key: "sources_labeled", label: "Every source has an authority label and can be verified", failMessage: "Please label each source Official, Guidance, or Outside source; check before use. If a citation came from memory, leave it out and ask the policy owner." };
const NO_NAMES_RULE: RubricRule = { key: "no_named_parties", label: "No names of candidates, employees, or complainants are included", failMessage: "Please leave out individual names. Describe the process, not a person." };

export const DOMAIN_PATHS: GraduationPath[] = [
  {
    id: "gp-6",
    title: "Inclusive hiring and selection",
    staffLabel: "I'm hiring or designing a role",
    signals: ["A position description being written or revised", "A hiring panel, rubric, or interview plan", "A screening process that keeps producing the same result"],
    startingCompetence: "You are responsible for a hiring process and want it to find capable people the current process may be screening out.",
    graduatedLooksLike:
      "By the end, you will have an inclusive hiring plan for a specific position: job-related requirements with alternatives, accessible outreach, a structured rubric and interviews, accommodation offered to everyone, a bias check built into deliberation, and a plan to review stage-by-stage outcomes with your HR partner.",
    launchType: "program_service",
    askStarters: [
      "We are rewriting a position description. How do we test whether the degree requirement is really job related?",
      "What should be in our interview rubric so we are not relying on culture fit?",
      "How do we offer accommodation at every stage without making anyone disclose a disability?",
    ],
    steps: [
      { key: "ask", title: "Test what the work requires", guidance: "Use Ask to work through the requirements, the rubric, and the outreach plan for this position. Answers will say what they are based on and what needs your HR partner.", links: [{ label: "Browse common questions", href: "/ask?path=gp-6" }] },
      { key: "ci", title: "Consider community context", guidance: "If outreach names particular Minnesota communities, read the relevant brief for how to reach people and what not to assume.", links: [{ label: "Explore Minnesota Communities", href: "/minnesota-communities" }], optional: true },
      { key: "resources", title: "Choose practical resources", guidance: "Use the eight-stage lifecycle, the job-relatedness check, and the accessible meeting guidance for interviews.", links: [{ label: "Inclusive hiring lifecycle", href: "/resources/ja-inclusive-hiring-lifecycle" }, { label: "Is this requirement job related?", href: "/resources/ja-job-relatedness-check" }, { label: "Accessible and culturally responsive meetings", href: "/resources/ja-accessible-meetings" }] },
      { key: "artifact", title: "Draft your inclusive hiring plan", guidance: "Complete the plan for this position. It is saved in the web browser you are using. Leave out candidate and employee names.", links: [] },
      { key: "selfcheck", title: "Review your work", guidance: "Confirm that each requirement is tied to the work, accommodation is offered to everyone, the rubric is written, the panel is prepared, and outcomes will be reviewed with HR.", links: [] },
      { key: "consult", title: "Take it to the right people", guidance: "Bring the plan to your HR partner and hiring panel. DSD staff can also request a consultation to think through a difficult position.", links: [{ label: "Find the right person", href: "/support/right-person?matter=hiring_or_workforce" }] },
    ],
    artifactTitle: "Inclusive hiring plan",
    artifactFields: [
      { id: "work_name", label: "Position title and unit", help: "The position, not a person.", type: "text", required: true, rubric: "specific_work" },
      { id: "requirements", label: "Requirements and what work each one predicts", help: "One line per requirement: the requirement, the work it predicts, and the credible alternative that shows the same ability.", type: "list", required: true },
      { id: "outreach", label: "Where and how you will reach people outside your usual networks", help: "Include community partners, plain-language posting, visible salary range, and the accommodation statement.", type: "textarea", required: true },
      { id: "rubric", label: "Screening and interview rubric", help: "The written criteria applied the same way to every candidate. Replace culture fit with specific behaviors the team needs.", type: "textarea", required: true },
      { id: "access_checks", label: "Accommodation and access at each stage", help: "How accommodation is offered to everyone, and how each stage is accessible without disclosure.", type: "textarea", required: true, rubric: "access" },
      { id: "involved", label: "Panel, HR partner, and reviewers", help: "Who is on the panel, how they were prepared, and which partners reviewed the plan.", type: "textarea", required: true, rubric: "involved" },
      { id: "not_assumed", label: "What you chose not to assume", help: "About candidates' paths, communication styles, or what confidence looks like.", type: "textarea", required: true, rubric: "not_assumed" },
      { id: "owners", label: "Who owns each follow-up", help: "Including who will review stage-by-stage outcomes with HR.", type: "list", required: true, rubric: "owners" },
      { id: "review_date", label: "Outcome review date", help: "When you will look at who applied, advanced, and was hired.", type: "date", required: true, rubric: "review_date" },
    ],
    rubric: [...COMMON_RUBRIC, ACCESS_RULE, INVOLVED_RULE, NOT_ASSUMED_RULE, NO_NAMES_RULE],
    antiPerformative: {
      fake: ["A diversity statement added to an unchanged posting", "Removing every qualification without testing what the work requires", "A panel chosen for appearance and given no rubric"],
      real: ["Each requirement is tied to the work with an alternative named", "The rubric is written and used", "Outcomes will be reviewed stage by stage with HR"],
    },
    privacy: "Do not include candidate or employee names. Describe the process, not a person. Progress is saved in the web browser you are using and is not used to rank anyone.",
    consultSupportType: "equity_embed_review",
  },
  {
    id: "gp-7",
    title: "Equity analysis for a decision",
    staffLabel: "I'm making or shaping a decision that needs an equity look",
    signals: ["A policy or program change going to leadership", "A budget, rule, or service decision with real reach", "A decision the DHS equity policy may require an analysis for"],
    startingCompetence: "You own or shape a decision and want to build equity into it while it can still change, and to know whether an equity scan or a full analysis is required.",
    graduatedLooksLike:
      "By the end, you will have an equity analysis record for a specific decision: the decision and its deadline, affected people and who is missing, evidence and its limits, benefits and burdens, alternatives, engagement, implementation owners, and follow-up. It supports the DHS process; the official record lives with the policy owner.",
    launchType: "policy_rule",
    askStarters: [
      "We are changing a program rule that goes to leadership. Does this need an equity scan or a full analysis, and what goes in it?",
      "Who benefits and who carries the burden in a budget reduction, and how do we find out?",
      "What alternatives should we compare before we settle a service change?",
    ],
    steps: [
      { key: "ask", title: "Clarify the decision and what applies", guidance: "Use Ask to work through the decision, whether a scan or full analysis applies, and what evidence you need. The policy owner confirms what is required.", links: [{ label: "Browse common questions", href: "/ask?path=gp-7" }] },
      { key: "ci", title: "Consider community context", guidance: "If the decision affects particular Minnesota communities, read the relevant briefs and plan engagement while the decision is open.", links: [{ label: "Explore Minnesota Communities", href: "/minnesota-communities" }], optional: true },
      { key: "resources", title: "Choose practical resources", guidance: "Use the scan-or-full-analysis aid, the equity review canvas, the Minnesota Equity Analysis Toolkit, and the equity impact questions.", links: [{ label: "Equity scan or full analysis: what goes in", href: "/resources/ja-equity-scan-or-full-analysis" }, { label: "Operational equity review canvas", href: "/resources/ja-operational-equity-canvas" }, { label: "Minnesota Equity Analysis Toolkit", href: "/resources/ext-dhs-equity-toolkit" }] },
      { key: "artifact", title: "Draft your equity analysis record", guidance: "Complete the record for this decision. It is saved in the web browser you are using. Leave out names and case details.", links: [] },
      { key: "selfcheck", title: "Review your work", guidance: "Confirm the decision is stated, affected people and who is missing are named, evidence and limits are recorded, at least two alternatives are compared, owners are named, and follow-up is dated.", links: [] },
      { key: "consult", title: "Take it to the right people", guidance: "Bring the record to the policy owner and your Equity Director. DSD staff can also request a consultation for a difficult decision.", links: [{ label: "Find the right person", href: "/support/right-person?matter=policy_or_program_decision" }] },
    ],
    artifactTitle: "Equity analysis record",
    artifactFields: [
      { id: "work_name", label: "Decision name and owner", help: "What is being decided and who owns the decision.", type: "text", required: true, rubric: "specific_work" },
      { id: "applies", label: "Scan or full analysis, and who confirmed it", help: "Which applies under the DHS equity policy, and which policy owner or Equity Director confirmed it.", type: "text", required: true },
      { id: "deadline", label: "When the decision stops being changeable", help: "The real date choices close.", type: "text", required: true },
      { id: "people", label: "Who benefits, who carries the burden, and who is missing", help: "By community, language, disability, age, place, and the people who deliver the service.", type: "textarea", required: true },
      { id: "evidence", label: "Evidence and what it does not show", help: "Data by group with small-group protection, what people who use the service say, and the limits.", type: "textarea", required: true },
      { id: "alternatives", label: "Alternatives compared", help: "At least two, including not proceeding, with who each helps and burdens.", type: "list", required: true },
      { id: "access_checks", label: "Access and burden in implementation", help: "Languages, formats, the human alternative, and burden you can remove.", type: "textarea", required: true, rubric: "access" },
      { id: "involved", label: "Who was involved and with what influence", help: "Team, data owners, staff who deliver the service, communities, and the level of influence they had.", type: "textarea", required: true, rubric: "involved" },
      { id: "not_assumed", label: "What you chose not to assume", help: "About people's access, time, documents, technology, or trust.", type: "textarea", required: true, rubric: "not_assumed" },
      { id: "sources", label: "Sources and their authority labels", help: "Label each source Official, Guidance, or Outside source; check before use.", type: "list", required: true, rubric: "sources_labeled" },
      { id: "owners", label: "Who owns each part of implementation and follow-up", help: "People, not units.", type: "list", required: true, rubric: "owners" },
      { id: "review_date", label: "Follow-up and report-back date", help: "When you will look at what happened and tell the people who gave input.", type: "date", required: true, rubric: "review_date" },
    ],
    rubric: [...COMMON_RUBRIC, ACCESS_RULE, INVOLVED_RULE, NOT_ASSUMED_RULE, SOURCES_RULE],
    antiPerformative: {
      fake: ["An equity section written after the decision was made", "Engagement scheduled after the deadline", "A single option presented as the analysis"],
      real: ["The decision is stated with its real deadline", "At least two alternatives are compared on benefits and burdens", "Owners, follow-up, and report-back are dated"],
    },
    privacy: "Do not include names or case details. This record supports a required DHS process but is not the official record; keep the official copy where your division keeps decision records. Progress here is saved in the web browser you are using.",
    consultSupportType: "equity_embed_review",
    participation: "supports_required",
  },
  {
    id: "gp-8",
    title: "Accessible and culturally responsive meeting",
    staffLabel: "I'm planning a meeting everyone can take part in",
    signals: ["A team meeting, all-staff, or partner meeting you are running", "A meeting where some people rarely speak", "A meeting with interpretation, captioning, or hybrid participation"],
    startingCompetence: "You are running a meeting and want everyone to be able to take part, contribute, and know what was decided.",
    graduatedLooksLike:
      "By the end, you will have a reusable meeting plan: purpose and materials sent ahead, accommodation offered without disclosure, several ways to contribute, attention to positional power, a plan for repair if harm occurs, decisions with owners, and accessible follow-up.",
    launchType: "facilitation_session",
    askStarters: [
      "What should I do before, during, and after a team meeting so everyone can actually take part?",
      "How do I run a hybrid meeting where the people online are not an afterthought?",
      "What do I do in the moment when a comment lands badly?",
    ],
    steps: [
      { key: "ask", title: "Plan for participation", guidance: "Use Ask to work through the purpose, the participation formats, and the access arrangements for this meeting.", links: [{ label: "Browse common questions", href: "/ask?path=gp-8" }] },
      { key: "ci", title: "Consider community context", guidance: "If the meeting includes community partners, read the relevant brief for access, timing, and what not to assume.", links: [{ label: "Explore Minnesota Communities", href: "/minnesota-communities" }], optional: true },
      { key: "resources", title: "Choose practical resources", guidance: "Use the accessible meeting guidance and the access checks.", links: [{ label: "Accessible and culturally responsive meetings", href: "/resources/ja-accessible-meetings" }, { label: "Access checks before a meeting or outreach", href: "/resources/ja-access-checks" }] },
      { key: "artifact", title: "Draft your meeting plan", guidance: "Complete the plan. It is saved in the web browser you are using. Leave out names.", links: [] },
      { key: "selfcheck", title: "Review your work", guidance: "Confirm materials go out ahead, accommodation is offered to everyone, there are several ways to contribute, decisions will have owners, and follow-up is accessible.", links: [] },
      { key: "consult", title: "Take it further if you want to", guidance: "Most meetings need no consultation. If a team pattern keeps recurring, the team climate path may help. DSD staff can request a consultation.", links: [{ label: "Strengthen team climate (Practice path)", href: "/paths/gp-4" }] },
    ],
    artifactTitle: "Accessible meeting plan",
    artifactFields: [
      { id: "work_name", label: "Meeting name, purpose, and who attends", help: "The meeting, not individual names.", type: "text", required: true, rubric: "specific_work" },
      { id: "ahead", label: "What goes out ahead and when", help: "Purpose, agenda, materials, format, and the accommodation sentence.", type: "textarea", required: true },
      { id: "formats", label: "Ways people can contribute", help: "Speaking, writing ahead, writing during, following up after, and how written input gets the same weight.", type: "list", required: true },
      { id: "access_checks", label: "Access arrangements", help: "Captions, interpretation, room or platform access, pace, materials in accessible formats.", type: "textarea", required: true, rubric: "access" },
      { id: "power", label: "How you will handle positional power and repair", help: "Who opens, who speaks last, how you will notice who is not speaking, and what you will do if harm occurs.", type: "textarea", required: true },
      { id: "involved", label: "Who helped plan and who will co-facilitate", help: "", type: "textarea", required: true, rubric: "involved" },
      { id: "not_assumed", label: "What you chose not to assume", help: "About cameras, eye contact, speed, or silence as signs of engagement.", type: "textarea", required: true, rubric: "not_assumed" },
      { id: "owners", label: "Who owns each decision and follow-up", help: "", type: "list", required: true, rubric: "owners" },
      { id: "review_date", label: "Follow-up date", help: "When accessible notes go out and when you ask how the meeting worked.", type: "date", required: true, rubric: "review_date" },
    ],
    rubric: [...COMMON_RUBRIC, ACCESS_RULE, INVOLVED_RULE, NOT_ASSUMED_RULE],
    antiPerformative: {
      fake: ["Captions turned on with nothing else changed", "A round-robin that forces everyone to speak", "Notes sent only to the people who were in the room"],
      real: ["Materials ahead, several ways to contribute, and decisions with owners", "Repair is the responsibility of the person with more power", "Follow-up is accessible and asks how it worked"],
    },
    privacy: "Do not include names. Progress is saved in the web browser you are using and is not used to rank anyone.",
    consultSupportType: "access_language_check",
  },
  {
    id: "gp-9",
    title: "Reviewing a draft for equity, access, and plain language",
    staffLabel: "I'm reviewing a draft before it goes out",
    signals: ["A document, notice, web page, or slide deck about to be released", "A draft someone asked you to check for equity or access", "Material that will reach the public or all staff"],
    startingCompetence: "You have a draft and want a structured way to check it for equity, access, plain language, sources, and burden before release.",
    graduatedLooksLike:
      "By the end, you will have a review record for a specific draft: what it asks of people, who may be excluded, access and language findings, source labels, changes made, and what remains for the owner.",
    launchType: "form_notice",
    askStarters: [
      "Can you review this draft notice for plain language, access, and burden?",
      "What questions should I ask about a draft before it goes to all staff?",
      "How do I tell the author what needs to change without redoing their work?",
    ],
    steps: [
      { key: "ask", title: "Get a structured review", guidance: "Paste the draft into Ask and choose Review my draft. You will receive findings by category, questions for the author, and suggested changes, with the limits of the review stated.", links: [{ label: "Ask: review my draft", href: "/ask?path=gp-9&mode=review" }] },
      { key: "ci", title: "Consider community context", guidance: "If the draft is aimed at or names particular Minnesota communities, read the relevant brief for naming, language, and access.", links: [{ label: "Explore Minnesota Communities", href: "/minnesota-communities" }], optional: true },
      { key: "resources", title: "Choose practical resources", guidance: "Use the plain-language checklist, the language access checklist, and the process burden questions.", links: [{ label: "Plain language and accessible documents", href: "/resources/ja-plain-language" }, { label: "Language access checklist", href: "/resources/ja-language-access-checklist" }, { label: "Journey and burden questions", href: "/resources/ja-process-burden" }] },
      { key: "artifact", title: "Record your review", guidance: "Complete the review record. It is saved in the web browser you are using. Do not paste confidential material.", links: [] },
      { key: "selfcheck", title: "Review your work", guidance: "Confirm findings are specific, sources are labeled, access and burden were checked, and the owner knows what remains.", links: [] },
      { key: "consult", title: "Return it to the owner", guidance: "The author or content owner decides what changes. Your review helps them; it does not approve the draft.", links: [{ label: "Find the right person", href: "/support/right-person?matter=accessibility_barrier" }] },
    ],
    artifactTitle: "Draft review record",
    artifactFields: [
      { id: "work_name", label: "Draft name, owner, and audience", help: "", type: "text", required: true, rubric: "specific_work" },
      { id: "asks", label: "What the draft asks people to do", help: "Steps, documents, deadlines, and return methods.", type: "textarea", required: true },
      { id: "excluded", label: "Who may be excluded or burdened", help: "By language, disability, technology, time, trust, or place.", type: "textarea", required: true },
      { id: "access_checks", label: "Access and plain-language findings", help: "Structure, reading level, formats, languages, alternative contact.", type: "textarea", required: true, rubric: "access" },
      { id: "sources", label: "Sources and their authority labels", help: "Label each claim's source. Flag anything cited from memory.", type: "list", required: true, rubric: "sources_labeled" },
      { id: "changes", label: "Changes you suggest", help: "Specific and short. The owner decides.", type: "list", required: true },
      { id: "involved", label: "Who else should review", help: "Language access, accessibility, communications, or the policy owner.", type: "textarea", required: true, rubric: "involved" },
      { id: "not_assumed", label: "What you chose not to assume", help: "About who reads this and how.", type: "textarea", required: true, rubric: "not_assumed" },
      { id: "owners", label: "Who owns each remaining change", help: "", type: "list", required: true, rubric: "owners" },
      { id: "review_date", label: "Date the owner needs it back", help: "", type: "date", required: true, rubric: "review_date" },
    ],
    rubric: [...COMMON_RUBRIC, ACCESS_RULE, INVOLVED_RULE, NOT_ASSUMED_RULE, SOURCES_RULE],
    antiPerformative: {
      fake: ["Approved with no findings", "A rewrite that changes the meaning without telling the owner", "A reading-level number with no specific change"],
      real: ["Findings are specific and tied to who is affected", "Sources are labeled and unsupported claims are flagged", "The owner knows exactly what remains"],
    },
    privacy: "Do not paste confidential, predecisional, or personal material. Progress is saved in the web browser you are using.",
    consultSupportType: "access_language_check",
  },
  {
    id: "gp-10",
    title: "Procurement or contract equity review",
    staffLabel: "I'm shaping a contract, grant, or solicitation",
    signals: ["A request for proposals, grant announcement, or contract renewal", "Evaluation criteria being written", "A contract whose reporting does not show who is served"],
    startingCompetence: "You are shaping a contract, grant, or procurement and want equity, accessibility, and language access built into the solicitation, evaluation, terms, and monitoring.",
    graduatedLooksLike:
      "By the end, you will have a procurement equity record: who the service reaches, requirements in the solicitation, evaluation criteria, contract reporting and access terms, monitoring by community, and the partners who own the rules.",
    launchType: "procurement_contract",
    askStarters: [
      "We are drafting a request for proposals. Where do equity and accessibility requirements belong?",
      "How do we evaluate proposals for experience with the communities served without excluding smaller providers?",
      "What reporting should the contract require so we can see who is served?",
    ],
    steps: [
      { key: "ask", title: "Place the questions in the right stage", guidance: "Use Ask to work through what belongs in the solicitation, the criteria, the terms, and the monitoring. Procurement rules belong to your contracts office.", links: [{ label: "Browse common questions", href: "/ask?path=gp-10" }] },
      { key: "ci", title: "Consider community context", guidance: "If the service reaches particular Minnesota communities, read the relevant briefs for access and trusted partners.", links: [{ label: "Explore Minnesota Communities", href: "/minnesota-communities" }], optional: true },
      { key: "resources", title: "Choose practical resources", guidance: "Use the procurement equity aid and the equity review canvas.", links: [{ label: "Equity in contracts, grants, and procurement", href: "/resources/ja-procurement-contract-equity" }, { label: "Operational equity review canvas", href: "/resources/ja-operational-equity-canvas" }] },
      { key: "artifact", title: "Draft your procurement equity record", guidance: "Complete the record. It is saved in the web browser you are using. Leave out vendor-identifying and confidential procurement details.", links: [] },
      { key: "selfcheck", title: "Review your work", guidance: "Confirm requirements are in the solicitation, criteria are written, reporting shows who is served with small-group protection, and the contracts office reviewed it.", links: [] },
      { key: "consult", title: "Take it to the right people", guidance: "Bring the record to your contracts or procurement office and your Equity Director before the solicitation is final. DSD staff can also request a consultation.", links: [{ label: "Find the right person", href: "/support/right-person?matter=procurement_or_contract" }] },
    ],
    artifactTitle: "Procurement equity record",
    artifactFields: [
      { id: "work_name", label: "Solicitation or contract name and stage", help: "", type: "text", required: true, rubric: "specific_work" },
      { id: "reach", label: "Who the service reaches and who delivers it", help: "Communities, languages, disabilities, and places; providers who could deliver but rarely win.", type: "textarea", required: true },
      { id: "requirements", label: "Requirements in the solicitation", help: "Accessibility, language access, engagement, and workforce expectations stated as requirements.", type: "list", required: true },
      { id: "criteria", label: "Evaluation criteria", help: "Written criteria for experience with communities served, accessibility practice, and workforce practice.", type: "list", required: true },
      { id: "access_checks", label: "Access in the application process itself", help: "Plain language, accessible format, human contact, and time to respond.", type: "textarea", required: true, rubric: "access" },
      { id: "reporting", label: "Contract reporting and monitoring", help: "What the contract reports by community with small-group protection, and how access problems get fixed during the term.", type: "textarea", required: true },
      { id: "involved", label: "Who reviewed this", help: "Contracts office, Equity Director, program owner, and community partners.", type: "textarea", required: true, rubric: "involved" },
      { id: "not_assumed", label: "What you chose not to assume", help: "About who can apply and who is served.", type: "textarea", required: true, rubric: "not_assumed" },
      { id: "sources", label: "Sources and their authority labels", help: "Procurement rules and policy sources, labeled.", type: "list", required: true, rubric: "sources_labeled" },
      { id: "owners", label: "Who owns each follow-up", help: "", type: "list", required: true, rubric: "owners" },
      { id: "review_date", label: "Monitoring review date", help: "", type: "date", required: true, rubric: "review_date" },
    ],
    rubric: [...COMMON_RUBRIC, ACCESS_RULE, INVOLVED_RULE, NOT_ASSUMED_RULE, SOURCES_RULE],
    antiPerformative: {
      fake: ["An equity clause added after award", "Preferences that are never scored", "Reporting that cannot show who was served"],
      real: ["Requirements and criteria are in the solicitation", "Reporting is disaggregated with protection", "The contracts office reviewed it before release"],
    },
    privacy: "Do not include confidential procurement details or vendor-identifying information. Progress is saved in the web browser you are using.",
    consultSupportType: "equity_embed_review",
  },
  {
    id: "gp-11",
    title: "Leadership pathway or sponsorship plan for staff with disabilities",
    staffLabel: "I'm building a leadership pathway or sponsorship plan",
    signals: ["A lead, supervisor, or leadership cohort pathway being designed or reviewed", "Leadership criteria that live in people's heads", "A sponsorship effort for people who are rarely put forward"],
    startingCompetence: "You shape how people move into lead and leadership roles and want the pathway to work for staff with disabilities without asking anyone to disclose.",
    graduatedLooksLike:
      "By the end, you will have a leadership pathway or sponsorship plan: a transparent pathway map, leadership criteria tested for job-relatedness, sponsors with decision power, an owner for accommodations across every transition, accessible cohort events by default, program-level measures with suppression, and a review date. No one is identified as disabled anywhere in it.",
    launchType: "program_service",
    askStarters: [
      "We are redesigning our lead-worker pathway. How do we make it work for staff with disabilities without asking anyone to disclose?",
      "Which of our leadership criteria are proxies, and what would replace them?",
      "How do we make sure accommodations carry across a rotation or a cohort?",
    ],
    steps: [
      { key: "ask", title: "Test the pathway, not the person", guidance: "Use Ask to work through the criteria, the transitions, sponsorship, and how the division would see the pattern in its data. Answers will say what needs leadership, HR, or the Equity Director.", links: [{ label: "Browse common questions", href: "/ask?path=gp-11" }] },
      { key: "ci", title: "Consider community context", guidance: "If the pathway also aims to reach staff from particular Minnesota communities, read the relevant brief for what not to assume.", links: [{ label: "Explore Minnesota Communities", href: "/minnesota-communities" }], optional: true },
      { key: "resources", title: "Choose practical resources", guidance: "Use the accessible leadership pathways note, the leadership criteria check, the accommodations-across-transitions aid, and the sponsorship note.", links: [{ label: "Accessible leadership pathways and sponsorship", href: "/resources/pn-accessible-leadership-pathways" }, { label: "Leadership criteria: are they job related?", href: "/resources/ja-leadership-criteria-job-relatedness" }, { label: "Accommodations across transitions", href: "/resources/ja-accommodation-across-transitions" }, { label: "Mentoring, sponsorship, and reverse mentoring", href: "/resources/pn-mentoring-sponsorship" }] },
      { key: "artifact", title: "Draft your pathway or sponsorship plan", guidance: "Complete the plan. It is saved in the web browser you are using. Do not name anyone or record who is disabled.", links: [] },
      { key: "selfcheck", title: "Review your work", guidance: "Confirm the pathway map is written, each criterion is tied to leadership work, accommodations have an owner at every transition, cohort events are accessible by default, sponsors hold decision power, measures use aggregates with suppression, and no individual is identified.", links: [] },
      { key: "consult", title: "Take it to the right people", guidance: "Bring the plan to division leadership and your Equity Director. Individual accommodation matters go through the confidential process with HR. DSD staff can also request a consultation.", links: [{ label: "Find the right person", href: "/support/right-person?matter=advancement_or_leadership_pathway" }] },
    ],
    artifactTitle: "Leadership pathway or sponsorship plan",
    artifactFields: [
      { id: "work_name", label: "Pathway, cohort, or sponsorship effort and its owner", help: "The pathway, not a person.", type: "text", required: true, rubric: "specific_work" },
      { id: "map", label: "What the lead or leadership role requires, which experiences count, and how to get them", help: "Write the pathway map so advancement does not depend on informal networks.", type: "textarea", required: true },
      { id: "criteria", label: "Leadership criteria and the leadership work each one predicts", help: "One line per criterion, including unwritten ones. Replace proxies such as executive presence or always-on availability with observable leadership behaviors.", type: "list", required: true },
      { id: "transitions", label: "Transitions and the owner of accommodations at each", help: "Nomination, interview, acting assignment, cohort, new team, return from leave. A named person for each.", type: "list", required: true },
      { id: "access_checks", label: "Accessible by default", help: "Materials in advance, captioning, flexible participation formats, no timed or drag-based activities, accommodation offered to everyone in the same sentence as logistics.", type: "textarea", required: true, rubric: "access" },
      { id: "sponsorship", label: "Sponsorship with decision power", help: "How sponsors are matched with people who want them, what sponsors commit to, and how the program will see whether sponsorship leads to assignments, using aggregates only.", type: "textarea", required: true },
      { id: "engagement", label: "How you heard from disabled staff without forcing disclosure", help: "Aggregate listening, employee resource groups, trusted intermediaries, and how you will report back.", type: "textarea", required: true },
      { id: "involved", label: "Who reviewed this and with what authority", help: "Division leadership, the HR partner, the Equity Director, and the disability employee resource group if there is one.", type: "textarea", required: true, rubric: "involved" },
      { id: "not_assumed", label: "What you chose not to assume", help: "About who is disabled, what accommodation someone needs, or what readiness looks like.", type: "textarea", required: true, rubric: "not_assumed" },
      { id: "owners", label: "Who owns each follow-up", help: "", type: "list", required: true, rubric: "owners" },
      { id: "review_date", label: "Review and report-back date", help: "When you will look at aggregate patterns and tell staff what changed.", type: "date", required: true, rubric: "review_date" },
    ],
    rubric: [...COMMON_RUBRIC, ACCESS_RULE, INVOLVED_RULE, NOT_ASSUMED_RULE, NO_NAMES_RULE],
    antiPerformative: {
      fake: ["A mentoring program with no sponsorship", "A cohort that is accessible on request", "A plan that lists who is disabled"],
      real: ["The pathway map is written and public", "Criteria are tied to leadership work", "Accommodations have an owner across every transition and sponsors hold decision power"],
    },
    privacy: "Never record who is disabled or any accommodation history. Describe the pathway, not people. Progress is saved in the web browser you are using and is not used to rank anyone.",
    consultSupportType: "equity_embed_review",
  },
];
