import type { CoursePack } from "../../source-types";

// Disability Inclusion, Level 2 (Applied inclusion), Module 3: Accommodations and Interactive Problem-Solving.
// Program-authored for supervisors, human resources, program, intake, direct-support and care-coordination staff.
const pack: CoursePack = {
  course: {
    id: "di-accommodations-and-interactive-process",
    indexNumber: 1108,
    seriesLabel: "Disability Inclusion · Applied inclusion",
    title: "Accommodations and Interactive Problem-Solving",
    subtitle: "Recognize a request, run the interactive process in order, keep the focus on the job and the barrier instead of the diagnosis, and know exactly when to bring in human resources or the ADA coordinator.",
    scope: "For supervisors, human resources staff, program staff, educators, customer-service teams, direct-support professionals, care coordinators and intake teams. Four lessons with scenarios, flashcards, sorting activities and knowledge checks. Participation in this program is voluntary and does not replace required training.",
    treatment: "Four lessons of 11 to 14 minutes, each with a scenario, a knowledge check and one applied next step",
    duration: "45–55 minutes",
    author: "One DHS — People, Access and Culture",
    coverImage: "/images/covers/performance-development.jpg",
    coverAlt: "A supervisor and a staff member sit for a one-on-one.",
    introTranscript: "An accommodation request usually arrives as an ordinary sentence: I am having trouble with the new headsets, or I need the instructions in writing. What happens in the next few minutes decides whether the person gets what they need, whether private information stays private, and whether the organization learns anything. This course teaches the interactive process as an ordered sequence you can follow under pressure, keeps the conversation on essential functions and access barriers rather than diagnosis, and shows exactly where a supervisor's part ends and human resources or the ADA coordinator's begins.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Explain the purpose of reasonable accommodation in employment and in services, and recognize a request that starts the process even when it uses no formal words.",
        "Conduct the interactive process as an ordered sequence, respectfully, promptly and confidentially, including an interim arrangement while a request is being resolved.",
        "Ask questions that focus on essential functions, access barriers and effective options, and avoid questions about diagnosis, history or treatment.",
        "Document an accommodation conversation appropriately, keep medical information separate and limited, and follow up to confirm the accommodation is working.",
        "Identify when to involve human resources, the ADA coordinator, legal counsel, disability resource staff or accessibility specialists, and what to hand over.",
      ],
      evidence: [
        "Four scenario decisions with explanations of why each option supports or undermines a respectful, timely process.",
        "Two completed sorts, one of requests that start the process and one of access-focused and diagnostic questions, plus four knowledge checks.",
        "One applied next step: your unit's accommodation route written on a single card and shared with your team.",
      ],
      appliedNextStep: "Find out who your ADA coordinator or human resources accommodation contact is, how a request reaches them, and how long the first response usually takes. Write it on one card, share it with your team, and use the six-step sequence the next time a request reaches you.",
    },
    governance: {
      contentOwner: "One DHS — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: ["Change in ADA, Section 504 or Section 508 guidance", "Change in DHS accessibility or language access standards", "Feedback from disabled staff or participants that a scenario reads as unrealistic or stigmatizing"],
      relatedDoor: "Formal accommodation decisions, medical documentation, undue hardship determinations and legal questions belong to human resources, the ADA coordinator and legal counsel; this course prepares a supervisor or staff member to receive a request well and hand it off correctly, not to decide it alone.",
      toolkitQuestion: "What is the person trying to do, what is in the way, what would remove it, and who needs to be involved to make that happen?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "accommodations-and-interactive-process-1",
        number: 1,
        title: "What reasonable accommodation is for",
        summary: "Understand the purpose of accommodation in employment and in services, and recognize a request when it arrives in ordinary words.",
        minutes: 12,
        learning: {
          objective: "Explain the purpose of reasonable accommodation in employment and in services, and recognize a request that starts the process even when it uses no formal words.",
          takeaways: [
            "Accommodation removes a barrier so a qualified person can do the essential functions of a job, or a person can use a program or service. It does not lower the standard or excuse the requirement.",
            "A request does not need magic words, a form or a diagnosis. “I am having trouble with X because of my health” is enough to start the process.",
            "Undue hardship and fundamental alteration are organizational determinations made by the responsible office with evidence, not a supervisor's first reaction to cost or inconvenience.",
          ],
          evidence: "A completed sort of statements that do and do not start the process, a scenario decision and a knowledge check.",
          appliedNextStep: "Think back over the last month for a sentence from an employee or participant that was probably a request. Write down what you did and what the six-step sequence in the next lesson would have changed.",
        },
        scenario: {
          context: "A direct-support professional tells her supervisor at the end of a shift, “My back has been bad since the surgery and the transfers at the Oak Street house are getting hard. I do not know what to do.” The supervisor says, “Take care of yourself. Let me know if it gets worse,” and goes back to the schedule.",
          prompt: "What has the supervisor missed?",
          options: [
            { label: "Nothing yet. She did not ask for anything, and the supervisor should not assume she is disabled.", response: "She connected a health condition to difficulty with a job task and asked for help. That is a request, in the plain words most requests use. Waiting for a formal one leaves her struggling and leaves the organization exposed to the injury it could have prevented." },
            { label: "The supervisor should have asked for a doctor's note describing her surgery and restrictions before discussing anything.", response: "The first move is a conversation about the task and the barrier, not documentation. If documentation is later needed, human resources or the ADA coordinator requests it, limited to what the decision requires. A supervisor collecting surgical details on the spot is a privacy problem, not a process." },
            { label: "Recognize the sentence as a request, thank her, ask what part of the transfers is hardest and what would help, arrange something workable now, and tell her human resources or the ADA coordinator can put a formal accommodation in place and that the supervisor will start that contact.", response: "This starts the interactive process the moment the request arrives, keeps the conversation on the task, gives her interim relief and routes the formal part to the right office.", recommended: true },
          ],
        },
        transfer: {
          prompt: "What sentences have you heard from employees or participants that were probably requests, and how did the process respond?",
          options: ["List three plain-language sentences that should start the process in your setting", "Check what your team believes a request has to look like, and correct the myth of the form or the magic words", "Find out who makes undue hardship or fundamental alteration determinations in your agency, and confirm it is not the supervisor"],
        },
        blocks: [
          { type: "text", heading: "Removing what is in the way", body: "<p>A reasonable accommodation is a change to how a job is done, how a workplace is arranged or how a program is delivered, so that a person with a disability has an equal chance to do the work or use the service. In employment, the ADA and Minnesota's own human rights law require it for qualified employees and applicants, up to the point of undue hardship for the employer. In programs and services, public entities must make reasonable modifications to policies and practices and provide effective communication, unless doing so would fundamentally alter the program. The purpose in both settings is the same: the person can meet the standard once the barrier is gone. The standard itself stays where it was.</p><p>That is why accommodation is not a favor, a lowered bar or a special deal. A screen reader, a schedule change, written instructions, a stool at a standing station, a transfer device, a quieter workstation: each removes something that was in the way of a person doing what everyone else is asked to do. The Job Accommodation Network, which advises employers across the country, reports from its own surveys that a large share of accommodations cost nothing, and that most of the rest involve a modest one-time expense. Cost is rarely the real obstacle. Not recognizing the request is.</p><p>Recognizing the request is the skill this lesson is about. Requests almost never arrive as “I am requesting a reasonable accommodation under the ADA.” They arrive as “the new headsets give me migraines,” “I cannot do the stairs at that site anymore,” “I keep losing track when instructions are only spoken,” or, from a family member, “she is going to need something different for the lobby.” Any sentence that links a health or disability-related limitation to difficulty with work or with a service is a request. Once you hear one, the process has started, whether or not anyone has filled out a form.</p>" },
          { type: "tabs", heading: "Two settings, one purpose", tabs: [
            { label: "Employment", body: "<p><strong>Who:</strong> applicants and employees who can do the essential functions with or without accommodation.</p><p><strong>Examples:</strong> modified schedules, equipment and software, written instructions, restructured marginal duties, accessible training, leave, a different workstation, reassignment to a vacant position as a last resort.</p><p><strong>Limit:</strong> undue hardship, meaning significant difficulty or expense for the organization as a whole, determined by the responsible office with evidence.</p><p><strong>Not required:</strong> removing an essential function, lowering production or conduct standards that apply to everyone, or providing personal-use items.</p>" },
            { label: "Programs and services", body: "<p><strong>Who:</strong> participants, applicants and members of the public who use a program, service or activity.</p><p><strong>Examples:</strong> a longer appointment, a home or video visit, materials in an alternative format, an interpreter, a modified deadline, a policy exception such as allowing a service animal or a support person.</p><p><strong>Limit:</strong> fundamental alteration of the program or an undue burden, determined by the responsible office, with a duty to find another way to provide access where possible.</p><p><strong>Not required:</strong> changing eligibility criteria that are necessary to the program.</p>" },
          ] },
          { type: "leaderMove", heading: "Hear the request in ordinary words", control: "You control whether a sentence about pain, fatigue, confusion or a barrier is heard as a complaint, a personal problem or the start of a process.", failure: "Do not wait for the word accommodation, a form or a diagnosis. Do not answer a request with sympathy and no action.", next: "Tell your team in your next meeting: if someone links a health condition to trouble doing part of their job, that is a request, and here is what you do with it." },
          { type: "sorting", id: "accommodations-and-interactive-process-1-sort", heading: "Starts the process, or not?", categories: ["Starts the process", "Does not by itself"], items: [
            { text: "“The fluorescent lights in the new area trigger my migraines and I cannot get through a shift.”", category: "Starts the process" },
            { text: "“I would prefer the desk by the window.”", category: "Does not by itself" },
            { text: "“Since my stroke I cannot follow the intake script when it changes without warning.”", category: "Starts the process" },
            { text: "An employee's spouse calls to say the employee is in the hospital and will need changes when she returns.", category: "Starts the process" },
            { text: "“I do not like the new scheduling software.”", category: "Does not by itself" },
            { text: "A participant says, “I cannot fill out forms on a screen; is there another way to apply?”", category: "Starts the process" },
          ] },
          { type: "flashcards", heading: "Terms you will hear", cards: [
            { front: "Reasonable accommodation", back: "<p>A change to the job, the workplace or the way a service is delivered that removes a barrier for a person with a disability. In services, often called a reasonable modification.</p>" },
            { front: "Qualified", back: "<p>In employment, a person who meets the job's requirements and can perform its essential functions with or without accommodation. The question is about the essential functions, not about every task ever assigned.</p>" },
            { front: "Undue hardship", back: "<p>Significant difficulty or expense in light of the organization's overall resources and operations. A high bar, judged for the whole organization, decided by the responsible office. A supervisor's budget line is not the test.</p>" },
            { front: "Fundamental alteration", back: "<p>In services, a change that would alter the essential nature of the program. Rare. Even when one is found, the agency must still look for another way to provide access.</p>" },
            { front: "Interim accommodation", back: "<p>A temporary arrangement that gives the person access while the formal process runs. Often the difference between a good process and a person quietly failing for six weeks.</p>" },
          ] },
          { type: "knowledgeCheck", id: "accommodations-and-interactive-process-1-check", question: "A financial worker tells his lead, “My hearing has gotten worse and I am missing things on the phone intake line.” He does not use the word accommodation. Which statement is accurate?", options: [
            { text: "Nothing is required until he submits a written request and medical documentation.", correct: false },
            { text: "He has made a request. The lead should recognize it, talk with him about the barrier and what would help, and involve human resources or the ADA coordinator for the formal process.", correct: true },
            { text: "The lead should move him off the phone line so the problem is solved.", correct: false },
          ], feedbackCorrect: "Yes. Plain words are enough. The conversation about the barrier starts now, and the formal route runs alongside it.", feedbackIncorrect: "A request does not need a form or the right vocabulary, and moving a person off a duty without asking him is a decision about him made without him. Recognize the request and start the process." },
          { type: "statement", body: "Accommodation does not lower the bar. It clears the path to it." },
        ],
      },
      {
        id: "accommodations-and-interactive-process-2",
        number: 2,
        title: "The interactive process, in order",
        summary: "Follow six steps in sequence, keep them prompt and confidential, and know where the supervisor's part ends and the ADA coordinator's begins.",
        minutes: 14,
        learning: {
          objective: "Conduct the interactive process as an ordered sequence, respectfully, promptly and confidentially, including an interim arrangement while a request is being resolved and a clear hand-off to human resources or the ADA coordinator.",
          takeaways: [
            "The process has an order: receive, clarify the barrier, identify options with the person, weigh feasibility and effectiveness, implement and document, then fix the system if the barrier recurs. Skipping a step is where most failures begin.",
            "The supervisor receives the request, talks about the task and the barrier, arranges interim relief and starts the hand-off. Human resources or the ADA coordinator handles documentation, the formal decision and anything involving medical information.",
            "Timeliness is part of the duty. Weeks of silence are a failure even if the eventual answer is yes.",
          ],
          evidence: "A scenario decision about a request to change how work instructions are given, a knowledge check and a completed conversation record for a real or practice request.",
          appliedNextStep: "Write your unit's version of the six steps on one page, with the name of the person or office that owns each step and the expected time between them. Share it with your team.",
        },
        scenario: {
          context: "An eligibility specialist tells his supervisor, “I need the work instructions in a different form. When the lead explains changes out loud at the huddle I lose them by the time I am back at my desk, and I have made two errors this month because of it. It is related to a disability.” The supervisor has a huddle in ten minutes and a queue of forty cases.",
          prompt: "What is the right sequence for the supervisor?",
          options: [
            { label: "Tell him to email human resources with his diagnosis and a doctor's note, and continue the huddle as usual until they respond.", response: "This skips receiving the request, skips the barrier conversation and skips interim relief, and it asks the employee to send medical detail to start a conversation he has already started. He will keep making errors while the paperwork moves." },
            { label: "Thank him, ask what part of the current method fails and what has worked before, agree today that the lead will post each change in writing after the huddle, tell him that human resources or the ADA coordinator can put a formal accommodation on record and that the supervisor will make that contact, and set a date to check that the written changes are working.", response: "Receive, clarify, identify an option with him, implement an interim arrangement, hand off the formal part and schedule follow-up. Six steps, ten minutes, no diagnosis needed.", recommended: true },
            { label: "Start sending him written instructions privately and say nothing to anyone else, so he is not singled out.", response: "The instinct to protect his privacy is right, but a private workaround with no record, no hand-off and no follow-up will drift, and the next supervisor will not know it exists. Privacy is protected by limiting who knows why, not by leaving the accommodation off the record." },
          ],
        },
        transfer: {
          prompt: "Which step in the sequence does your unit most often skip, and what would it take to stop skipping it?",
          options: ["Walk one past request through the six steps and mark where it stalled", "Write down what interim relief you can offer on your own authority for the three most common requests", "Agree with human resources or the ADA coordinator on what a hand-off from you should contain"],
        },
        blocks: [
          { type: "text", heading: "A sequence you can follow under pressure", body: "<p>The interactive process is the name for the back-and-forth between a person who needs an accommodation and the organization that provides it. It is called interactive because neither side decides alone: the person knows the barrier and often knows what works; the organization knows the job, the program and what is feasible. The law expects the exchange to be prompt and made in good faith. It does not prescribe a form, but the process falls apart when steps are skipped, and it falls apart most often at the beginning, when a request is heard but not received, and at the end, when an accommodation is put in place and never checked.</p><p>The six steps below are in order for a reason. Clarifying the barrier before brainstorming keeps the solution attached to the problem. Weighing feasibility after identifying options, rather than before, keeps a supervisor from vetoing ideas nobody has examined. Documenting after implementing, rather than instead of it, keeps the record honest. The last step, addressing recurring barriers at the system level, is what separates an organization that accommodates from one that keeps re-solving the same problem one person at a time.</p><p>Roles matter as much as order. A supervisor receives the request, has the task-and-barrier conversation, arranges what can be arranged now and starts the hand-off. Human resources or the ADA coordinator owns the formal request, any medical documentation, the undue hardship analysis if one is needed, and the official decision and record. This division protects the employee's privacy, protects the supervisor from decisions they are not equipped to make, and makes the process consistent across the agency. A supervisor who tries to run the whole thing alone is not being helpful; they are being a single point of failure.</p>" },
          { type: "list", heading: "The six steps, in order", ordered: true, items: ["Receive the request with respect and without judgment. Thank the person, confirm you understood that they are asking for a change related to a disability or health condition, and say what happens next and when.", "Clarify the barrier and the functional access need. Ask what task is affected, what part of the current method fails and what has helped before. Do not ask for a diagnosis.", "Identify possible effective options with the person. Start with what they suggest; add what you know about the job and what resources exist. More than one option is normal.", "Consider feasibility, effectiveness, timing, privacy and essential requirements. Which options remove the barrier, can be put in place soonest, keep the person's information contained and leave the essential functions intact? Put an interim arrangement in place now if the formal answer will take time.", "Implement, document and follow up. Make the change, record the request, the barrier, the options, the decision and the follow-up date, and check at that date whether it is working. Hand the formal record to human resources or the ADA coordinator.", "Address recurring barriers at the system level. If the same barrier produces a second and third request, change the default so the fourth person never has to ask."] },
          { type: "accordion", heading: "What each step sounds like", items: [
            { title: "Step 1, receive", body: "<p>“Thank you for telling me. I understand you are asking for a change because of a health condition, and I want to get this right. Here is what happens next: we talk about what is getting in the way, we figure out what would help, I put something in place as soon as I can, and human resources or the ADA coordinator can put a formal accommodation on record. I will follow up with you by Friday.”</p>" },
            { title: "Step 2, clarify", body: "<p>“Walk me through where it breaks down. Is it when the change is announced, when you get back to your desk or when you apply it to a case? Has anything worked before, here or at another job?”</p>" },
            { title: "Step 3, identify options", body: "<p>“What would you want if you could design it? Here is what I can think of on my side: written changes posted after each huddle, a running document you can search, a short recorded summary, a check-in with the lead. What else?”</p>" },
            { title: "Step 4, weigh and bridge", body: "<p>“Written changes after every huddle we can start today. A searchable running document is better and will take the lead a week to set up. Does that work? In the meantime, the written notes start tomorrow.”</p>" },
            { title: "Step 5, implement, document, follow up", body: "<p>“I am writing down that you asked for instructions in writing, that verbal-only changes were the barrier, that we agreed on written notes now and a running document by next week, and that we will check on the 20th. I am sending the request to the ADA coordinator so it is on record; they may contact you and I will not share anything beyond what we discussed.”</p>" },
            { title: "Step 6, fix the system", body: "<p>“This is the third person this year who has asked for changes in writing. From now on, every huddle change gets posted. Nobody has to ask.”</p>" },
          ] },
          { type: "leaderMove", heading: "Bridge the gap with an interim arrangement", control: "You control whether the person has access while the formal process runs, or waits without it.", failure: "Do not let “I have sent it to human resources” be the end of your part. Do not let a request sit for weeks because the formal answer is pending.", next: "For each of the three most common requests in your unit, decide now what interim arrangement you can put in place the same day on your own authority." },
          { type: "artifact", kind: "tagged-document", label: "Practical artifact", title: "Accommodation conversation record", summary: "A one-page record the supervisor completes after the first conversation and hands to human resources or the ADA coordinator. It contains the barrier and the plan, never a diagnosis.", fields: [
            { label: "Request", value: "The date the request was received, in the person's own words where possible, and the task or service it concerns. Example: written work instructions instead of verbal-only changes announced at the huddle." },
            { label: "Barrier and options", value: "What part of the current method fails, what the person suggested, what else was considered, and what was ruled out and why. No diagnosis, no medical history, no speculation about the condition." },
            { label: "Arrangement and follow-up", value: "The interim arrangement and its start date, the longer-term option if different, the person responsible for each, and the date the supervisor and the person will check that it is working." },
            { label: "Hand-off", value: "The date the record was sent to human resources or the ADA coordinator, who received it, and a note that the person was told what was shared and with whom." },
          ], action: "Use this record for the next request you receive. Keep your copy separate from performance files and share it only with the responsible office." },
          { type: "flashcards", heading: "Where the supervisor's part ends", cards: [
            { front: "The supervisor does", back: "<p>Receives the request, holds the task-and-barrier conversation, identifies options with the person, arranges interim relief, records the conversation without medical detail, starts the hand-off and follows up.</p>" },
            { front: "Human resources or the ADA coordinator does", back: "<p>Owns the formal request, requests and holds any medical documentation, conducts any undue hardship analysis, issues the official decision, keeps the confidential record and advises the supervisor on implementation.</p>" },
            { front: "Timeliness", back: "<p>Respond within days, not weeks. If the formal decision will take time, say how long and put interim access in place. Silence is a failure even when the eventual answer is yes.</p>" },
            { front: "Confidentiality", back: "<p>Tell only the people who need to know something, and tell them only what they need: the lead needs to post written changes, not the reason. Keep the record apart from the performance file.</p>" },
            { front: "When the person declines an option", back: "<p>The organization can choose among effective options, but an option that does not remove the barrier is not effective. Go back to step three together before deciding.</p>" },
            { front: "When you are not sure", back: "<p>Call human resources or the ADA coordinator before you answer, not after. Asking early is part of the process, not a sign you have failed at it.</p>" },
          ] },
          { type: "knowledgeCheck", id: "accommodations-and-interactive-process-2-check", question: "A supervisor receives a request on Monday and sends it to the ADA coordinator the same day. Three weeks later the employee, who asked for a modified schedule, is still working the old schedule and has heard nothing. What went wrong?", options: [
            { text: "Nothing. The supervisor handed it off promptly, and the formal process takes time.", correct: false },
            { text: "The supervisor skipped the interim arrangement and the follow-up. The hand-off was correct, but the person should have had a workable schedule and a status update while the formal process ran.", correct: true },
            { text: "The supervisor should have decided the request alone instead of involving the ADA coordinator.", correct: false },
          ], feedbackCorrect: "Yes. The hand-off starts the formal part; it does not end the supervisor's part. Interim access and a follow-up date are steps four and five, and they belong to the supervisor.", feedbackIncorrect: "The hand-off was right. What was missing was access in the meantime and any communication. Timeliness and an interim arrangement are part of the duty, and they sit with the supervisor." },
        ],
      },
      {
        id: "accommodations-and-interactive-process-3",
        number: 3,
        title: "Essential functions and barriers, not diagnosis",
        summary: "Keep every question on the job, the barrier and the options, and leave diagnosis and documentation to the office that is allowed to handle them.",
        minutes: 12,
        learning: {
          objective: "Ask questions that focus on essential functions, access barriers and effective options, and avoid questions about diagnosis, history or treatment.",
          takeaways: [
            "Essential functions are the fundamental duties of the position, the reason the job exists. Marginal functions are the tasks that could be reassigned without changing the job. Accommodation works on how essential functions are done and on whether marginal ones are needed.",
            "You do not need to know the diagnosis to run the conversation. You need to know the task, the barrier and what would remove it.",
            "Medical documentation may be requested only when the disability or the need for accommodation is not obvious, only to the extent needed to establish them, and only by the office designated to hold it.",
          ],
          evidence: "A completed sort of access-focused and diagnostic questions, a scenario decision and a knowledge check.",
          appliedNextStep: "Before your next accommodation conversation, write your questions down and strike any that ask what the person has instead of what the person needs.",
        },
        scenario: {
          context: "A licensing staff member who conducts site visits asks her supervisor for a change: she needs the visit schedule set at least a week ahead and no more than two visits in a day. She mentions a chronic condition that flares unpredictably. The supervisor wants to help and starts asking: “What is the condition? How often does it flare? Are you on medication? Is it going to get worse?”",
          prompt: "Which questions should the supervisor have asked instead?",
          options: [
            { label: "The supervisor's questions are reasonable. You cannot plan a schedule without understanding the condition.", response: "You can plan a schedule from the request itself: a week's notice and two visits a day. The condition, medication and prognosis do not change what the schedule needs to look like, and asking about them collects private medical information a supervisor is not the right person to hold." },
            { label: "“Which parts of the visit schedule are hardest: the short notice, the number of visits or the travel? Would a week's notice and a two-visit limit fully remove the problem, or is there more? What should we do on a day a visit has to move?”", response: "Every question is about the task and the barrier. The supervisor learns what the accommodation needs to do, plans for the flare days, and never needs a diagnosis. If human resources or the ADA coordinator later needs documentation, that request comes from them, limited to what the decision requires.", recommended: true },
            { label: "“Are you sure you can still do this job?”", response: "This turns a request for a schedule adjustment into a challenge to the person's qualification. She is asking for a change in how the essential function is scheduled, not to be excused from it." },
          ],
        },
        transfer: {
          prompt: "What do you actually need to know to put an accommodation in place, and what have you been asking for out of habit?",
          options: ["Rewrite three diagnostic questions you have heard as access-focused questions", "Ask your human resources partner or ADA coordinator what documentation they request and when, so you can explain the route accurately", "Look at one position description and mark the essential functions against the tasks that are really marginal"],
        },
        blocks: [
          { type: "text", heading: "The job, the barrier and the fix", body: "<p>Every accommodation conversation has three subjects: what the person is trying to do, what is getting in the way and what would remove it. The first subject is where essential functions come in. Essential functions are the fundamental duties of a position, the reasons the job exists, the things that cannot be handed to someone else without changing what the job is. Marginal functions are the rest: tasks that are done in the position but could be reassigned or dropped. Accommodation is expected to change how essential functions are performed, when and where they are done and with what tools, and to reassign marginal functions when that helps. It is not expected to remove an essential function. Knowing which is which, from the position description and from how the job is actually done, keeps the conversation honest in both directions.</p><p>The second and third subjects are where diagnosis tries to sneak in. Staff ask what the condition is because it feels like the responsible question. It is not. The condition does not tell you the barrier; the person does. Two people with the same diagnosis can need opposite things, and one person's needs can change over time. Questions about diagnosis, history, treatment and prognosis also collect information protected under disability and data privacy law, information a supervisor is not the designated holder of and cannot un-know once heard. Keep to the task: which part fails, when, what has worked, what would work now.</p><p>There are times documentation is legitimately needed: when the disability or the need for the accommodation is not obvious and the organization needs to confirm them. Even then, the request is limited to what is needed to establish the disability and the need, it is made by the office designated to hold medical information, and it is kept apart from personnel files. A supervisor who says “I will need a doctor's note first” has taken a step that is not theirs to take, and has delayed access for a request that may need no documentation at all.</p>" },
          { type: "tabs", heading: "Ask this, not that", tabs: [
            { label: "About the task", body: "<p><strong>Ask:</strong> “Which parts of the job are affected? Walk me through a day where it goes badly.”</p><p><strong>Not:</strong> “What is your diagnosis?”</p>" },
            { label: "About the barrier", body: "<p><strong>Ask:</strong> “What about the current setup gets in the way: the timing, the tool, the format, the location, the noise?”</p><p><strong>Not:</strong> “How bad is it? Is it going to get worse?”</p>" },
            { label: "About options", body: "<p><strong>Ask:</strong> “What has worked before? What would you want if you could design it? Here is what I can think of; what am I missing?”</p><p><strong>Not:</strong> “Have you tried medication or therapy?”</p>" },
            { label: "About the fit", body: "<p><strong>Ask:</strong> “Would this fully remove the problem, or is there more? What should we do on a day it is not enough?”</p><p><strong>Not:</strong> “Are you sure you can still do this job?”</p>" },
            { label: "About documentation", body: "<p><strong>Say:</strong> “If documentation is needed, human resources or the ADA coordinator will ask for it directly, and they will only ask for what the decision requires. I will not be collecting it.”</p><p><strong>Not:</strong> “Bring me a doctor's note and we will go from there.”</p>" },
          ] },
          { type: "leaderMove", heading: "Strike the diagnostic questions", control: "You control which questions you ask, and every question about the condition is a question you did not ask about the task.", failure: "Do not open with “what do you have.” Do not make documentation a precondition for talking. Do not ask whether the person can still do the job when they have asked for a change in how it is scheduled or done.", next: "Write your questions down before your next accommodation conversation. Strike any that ask what the person has instead of what the person needs." },
          { type: "sorting", id: "accommodations-and-interactive-process-3-sort", heading: "Access-focused or diagnostic?", categories: ["Access-focused", "Diagnostic"], items: [
            { text: "“Which part of the intake script is hardest when it changes without notice?”", category: "Access-focused" },
            { text: "“When were you diagnosed, and by whom?”", category: "Diagnostic" },
            { text: "“Would written changes posted after the huddle remove the problem?”", category: "Access-focused" },
            { text: "“Are you taking anything for it?”", category: "Diagnostic" },
            { text: "“What should we plan for on a day the arrangement is not enough?”", category: "Access-focused" },
            { text: "“Is this the kind of thing that gets worse over time?”", category: "Diagnostic" },
          ] },
          { type: "flashcards", heading: "Keeping the focus", cards: [
            { front: "Essential function", back: "<p>A fundamental duty of the position, the reason it exists. Read the position description, then check it against how the job is really done; the two are not always the same.</p>" },
            { front: "Marginal function", back: "<p>A task done in the position that could be reassigned or dropped without changing the job. Reassigning marginal functions is a common and reasonable accommodation.</p>" },
            { front: "Changing how, not whether", back: "<p>Accommodation changes when, where, how and with what tools an essential function is done. It does not remove the function. Keep both halves of that sentence.</p>" },
            { front: "Who may ask for documentation", back: "<p>The office designated to hold medical information, usually human resources or the ADA coordinator, and only when the disability or need is not obvious, and only to the extent needed.</p>" },
            { front: "When the person offers the diagnosis", back: "<p>Thank them and return to the task. Do not write it into your record. What you record is the barrier and the plan.</p>" },
            { front: "The fluctuating condition", back: "<p>Plan for the variable, not the average. Ask what a hard day needs and build that in, rather than designing for the good days and calling the hard ones a performance problem.</p>" },
          ] },
          { type: "knowledgeCheck", id: "accommodations-and-interactive-process-3-check", question: "A supervisor tells an employee who requested a standing desk and periodic breaks, “Before I can approve anything I need a note from your doctor explaining your condition.” Which statement is accurate?", options: [
            { text: "This is correct procedure; documentation always comes first.", correct: false },
            { text: "The supervisor has taken a step that belongs to human resources or the ADA coordinator, made it a precondition for a conversation, and asked for more than the decision needs. The task-and-barrier conversation and interim relief should have come first.", correct: true },
            { text: "The supervisor should have approved the request and asked for the note afterward for the file.", correct: false },
          ], feedbackCorrect: "Yes. Documentation, when needed at all, is requested by the designated office, limited to establishing the disability and the need, and never held in a supervisor's file. The conversation comes first.", feedbackIncorrect: "A supervisor is not the office that requests or holds medical documentation, and a request for a standing desk and breaks may need none. Start with the task and the barrier, arrange what you can now, and route the formal part correctly." },
          { type: "quote", text: "The best manager I had never knew what I was diagnosed with. She knew I needed the schedule a week out and that some days I would need to move a visit. That was the whole conversation, and it worked for four years.", cite: "Composite staff perspective, illustrative" },
        ],
      },
      {
        id: "accommodations-and-interactive-process-4",
        number: 4,
        title: "Document, follow up and fix the system",
        summary: "Keep an appropriate record, check that the accommodation is working, know exactly who to involve, and turn repeated requests into a changed default.",
        minutes: 11,
        learning: {
          objective: "Document an accommodation conversation appropriately, keep medical information separate and limited, follow up to confirm the accommodation is working, and identify when to involve human resources, the ADA coordinator, legal counsel, disability resource staff or accessibility specialists.",
          takeaways: [
            "A good record shows the request, the barrier, the options, the decision, who did what and the follow-up date. It contains no diagnosis and lives apart from performance files.",
            "An accommodation that was never checked is an assumption. Follow up at the agreed date and whenever the job, the tools or the person's needs change.",
            "Repeated requests for the same thing are data about a default, not about the people who asked. Change the default.",
          ],
          evidence: "A scenario decision about an accommodation that has stopped working, a knowledge check and your unit's accommodation route written on one card.",
          appliedNextStep: "Write your unit's accommodation route on one card: who receives a request, who handles the formal process and documentation, who to call about digital or physical accessibility, where the record lives and when follow-up happens. Share it with your team.",
        },
        scenario: {
          context: "Six months ago, an employee received screen-magnification software as an accommodation, and it worked. The unit has since moved to a new case-management system. The employee has been quietly taking work home to keep up, because the new system does not work well with the magnifier, and has started missing deadlines. The supervisor notices the deadlines first.",
          prompt: "What should the supervisor do?",
          options: [
            { label: "Address the missed deadlines through the performance process. The accommodation was provided; the rest is up to the employee.", response: "The accommodation stopped being effective when the system changed, and no one checked. Treating the result as a performance problem punishes the employee for a barrier the organization created and never followed up on." },
            { label: "Ask the employee what changed, recognize that the new system has reopened the barrier, arrange interim relief now, bring in the accessibility specialists and the ADA coordinator about the system's compatibility, and set a new follow-up date. Raise the system's accessibility with its owner so it is fixed for everyone.", response: "Follow-up, interim access, the right offices and a system-level fix. The missed deadlines are a symptom; the conversation goes to the cause.", recommended: true },
            { label: "Tell the employee to submit a new accommodation request and wait for the formal process before changing anything.", response: "A changed accommodation need does not restart the clock from zero. The interactive process continues, and interim relief should not wait for paperwork." },
          ],
        },
        transfer: {
          prompt: "Which accommodations in your unit have never been checked since they were put in place, and what has changed around them?",
          options: ["List the accommodations you know about and the date each was last confirmed to be working", "Add a follow-up check to every accommodation record, and a trigger for any change in systems, tools or duties", "Identify one request your unit has received three or more times and propose the default change"],
        },
        blocks: [
          { type: "text", heading: "The record, the check and the pattern", body: "<p>Documentation in the accommodation process has two jobs: to make sure the accommodation actually happens and keeps happening, and to show, if anyone asks later, that the organization responded promptly and in good faith. A good record is short. It shows the date of the request and what was asked, the barrier as the person described it, the options considered and why each was chosen or set aside, the arrangement put in place and who owns it, the date of the hand-off to human resources or the ADA coordinator, and the follow-up date. It does not contain a diagnosis, a medical history or the supervisor's theory of the condition. Medical information, when the designated office has collected it, is kept in a separate confidential file, not in the personnel file and not in the supervisor's drawer.</p><p>Follow-up is the step most often dropped, and its absence is why accommodations quietly fail. Jobs change, systems change, teams move buildings, a person's needs shift. An accommodation that was effective in March may be useless in October. Check at the agreed date, and check again whenever the job, the tools or the person's circumstances change. Ask a plain question: “Is this still working? What has changed?” If the answer is no, you are back in the interactive process, not at the start of a new one, and interim access should not wait.</p><p>Finally, look at the pattern. When three people have asked for written instructions, a quieter workstation or a longer appointment, the organization has learned something about its defaults. Changing the default, posting all changes in writing, adding a quiet area, making the longer appointment the standard, removes the barrier for the fourth person before they have to ask, and often improves the work for everyone. This is the difference between an accommodation process and an accessible organization, and it is the sixth step of the sequence for a reason.</p>" },
          { type: "list", heading: "What a good record contains", items: ["The date the request was received and what was asked, in the person's words where possible.", "The task or service affected and the barrier as the person described it.", "The options considered, including the person's suggestions, and why each was chosen or set aside.", "The interim arrangement and the longer-term arrangement, with a named owner for each.", "The date of the hand-off to human resources or the ADA coordinator and what was shared.", "The follow-up date, and after it, what was found and what changed.", "Nothing about diagnosis, history, treatment or prognosis."] },
          { type: "accordion", heading: "Who to involve, and for what", items: [
            { title: "Human resources or the ADA coordinator", body: "<p>Every formal request. Any request that involves documentation, leave, reassignment, a change to essential functions or a possible undue hardship question. Any time you are unsure. They own the official decision and the confidential record.</p>" },
            { title: "Accessibility specialists or the digital accessibility team", body: "<p>Any barrier involving software, systems, documents, forms, websites or assistive technology compatibility. They can test, advise on fixes and raise the problem with the system owner.</p>" },
            { title: "Disability resource staff or the accessibility and language access office", body: "<p>Interpreters, captioning, alternative formats, physical access to buildings and rooms, and accommodations for participants and the public in programs and services.</p>" },
            { title: "Legal counsel", body: "<p>Through human resources or the ADA coordinator, not directly from a supervisor. Questions about legal obligations, disputes, complaints or an undue hardship determination.</p>" },
            { title: "Civil rights or equal opportunity office", body: "<p>If a person believes a request was denied or delayed because of disability, or reports retaliation for asking. Tell people this route exists; do not wait for them to find it.</p>" },
            { title: "Facilities", body: "<p>Physical changes: doors, desks, lighting, parking, restrooms, routes and signage. Loop them in through the responsible office so the fix is recorded and lasting.</p>" },
          ] },
          { type: "leaderMove", heading: "Check before the deadline slips", control: "You control whether an accommodation has a follow-up date and whether anyone asks “is this still working” when the job or the system changes.", failure: "Do not discover that an accommodation stopped working from a performance report. Do not treat a new barrier as a brand-new request that must start from zero.", next: "Put a follow-up date on every accommodation you know about, and add a note to your change-management checklist: when systems, tools or duties change, check every accommodation they touch." },
          { type: "flashcards", heading: "Closing the loop", cards: [
            { front: "Separate files", back: "<p>Medical information lives in a confidential file held by the designated office. The supervisor's record holds the barrier and the plan. The performance file holds neither.</p>" },
            { front: "The follow-up question", back: "<p>“Is this still working? What has changed?” Asked at the agreed date and whenever the job, the tools or the team changes.</p>" },
            { front: "A changed need", back: "<p>Continues the interactive process. Interim relief now, the responsible offices involved, a new follow-up date. Not a restart.</p>" },
            { front: "Three requests, one default", back: "<p>If the same request keeps arriving, the default is the barrier. Change it and note that you did.</p>" },
            { front: "Who owns the system fix", back: "<p>The owner of the system, form, building or policy. Your part is to name the barrier specifically, route it, and follow up until it is fixed or formally declined with a reason.</p>" },
            { front: "Tell people the routes", back: "<p>Employees and participants should know how to ask, who decides, how long it takes and where to go if they believe they were treated unfairly. If they have to guess, the process is not accessible.</p>" },
          ] },
          { type: "knowledgeCheck", id: "accommodations-and-interactive-process-4-check", question: "A supervisor keeps a folder with each team member's accommodation records, including the doctor's letters an employee handed her directly, in the same drawer as the annual performance reviews. Which statement is accurate?", options: [
            { text: "This is fine as long as the drawer is locked.", correct: false },
            { text: "Medical documentation belongs in a confidential file held by the designated office, not with the supervisor and not with performance records. The supervisor should route the letters to human resources or the ADA coordinator and keep only the barrier-and-plan record.", correct: true },
            { text: "The supervisor should shred the doctor's letters so no record exists.", correct: false },
          ], feedbackCorrect: "Yes. Separation is the safeguard: medical information with the designated office, the plan with the supervisor, performance apart from both. Route the letters; do not destroy them.", feedbackIncorrect: "A lock does not fix the wrong holder or the wrong file, and destroying records is not the answer either. Medical documentation goes to the designated office, separate from performance files." },
          { type: "statement", body: "An accommodation you never checked is an assumption. A request you have heard three times is a default waiting to change." },
          { type: "text", heading: "Take it to your work", body: "<p>A supervisor’s part is to receive, bridge and hand off. If you are unsure who holds the formal process in your unit, <a href=\"/support/right-person\">find the right person</a>. When a request shows you a default worth changing for everyone, the <a href=\"/practice/gp-4\">team climate path</a> helps you plan the change and who owns it.</p>" },
        ],
      },
    ],
  },
  jobAid: {
    title: "Accommodations and the interactive process",
    subtitle: "A one-page reminder for the moment a request arrives",
    quote: "Hear the request. Ask about the task. Bridge with interim access. Hand off the formal part. Follow up. Fix the default.",
    use: {
      purpose: "Keep the sequence, the boundaries and the routes in reach when an employee or participant asks for a change.",
      remember: ["A request needs no form, no magic words and no diagnosis to start the process.", "The conversation is about the task, the barrier and the options, never the condition.", "The supervisor receives, bridges and hands off; human resources or the ADA coordinator decides, documents and holds medical information.", "An accommodation without a follow-up date is an assumption; a request heard three times is a default to change."],
      doNext: "Write your unit's accommodation route on one card and share it with your team before the next request arrives.",
    },
    sections: [
      { heading: "The six steps, in order", items: ["Receive the request with respect; say what happens next and when.", "Clarify the task, the barrier and what has worked before; do not ask for a diagnosis.", "Identify options with the person; start with theirs.", "Weigh feasibility and effectiveness; put an interim arrangement in place now.", "Implement, record the barrier and the plan, hand off the formal part, set a follow-up date.", "If the same barrier keeps producing requests, change the default."] },
      { heading: "Questions to ask, questions to strike", items: ["Ask: which part of the job is affected, and when does it break down?", "Ask: what would fully remove the problem, and what do we do on a day it is not enough?", "Strike: what is your diagnosis, how bad is it, are you on medication, will it get worse.", "Say: if documentation is needed, human resources or the ADA coordinator will ask for only what the decision requires."] },
      { heading: "Who to involve", items: ["Human resources or the ADA coordinator: every formal request, all documentation, leave, reassignment, undue hardship, anything you are unsure about.", "Accessibility specialists: software, systems, documents and assistive technology compatibility.", "Accessibility or language access office: interpreters, captioning, alternative formats, physical access, participant and public accommodations.", "Civil rights or equal opportunity office: a person who believes a request was denied, delayed or punished because of disability."] },
      { heading: "What an accessible process looks like", items: ["Several ways in: a word to a supervisor, a message to the coordinator, a phone call, a union representative, or a health provider writing on the person’s behalf. No form and no special wording is required to begin.", "A prompt acknowledgment that says what happens next and when, and a conversation about the task and the barrier before any paperwork is discussed.", "Documentation only when it is needed to confirm a condition or shape an option, requested specifically, and held by the office responsible for it, never by the supervisor.", "An interim arrangement the same week when the permanent one takes time; the person keeps working while it is arranged.", "A check a month later: is it working, does it need adjusting, has the job changed. An accommodation is a relationship, not a transaction."] },
    ],
  },
  sources: [
    { title: "U.S. Equal Employment Opportunity Commission, Enforcement Guidance on Reasonable Accommodation and Undue Hardship", href: "https://www.eeoc.gov/laws/guidance/enforcement-guidance-reasonable-accommodation-and-undue-hardship-under-ada", note: "How requests are made, the interactive process, limits on medical inquiries and documentation, and the undue hardship standard in employment." },
    { title: "Job Accommodation Network", href: "https://askjan.org/", note: "Free, practical guidance on the interactive process, accommodation ideas by limitation and task, and the low typical cost of accommodations." },
    { title: "ADA.gov", href: "https://www.ada.gov/", note: "Reasonable modifications, effective communication and program access obligations for state and local government services, and employment provisions." },
    { title: "ADA National Network", href: "https://adata.org/", note: "Training and technical assistance on employment accommodations and public program access under the ADA." },
    { title: "U.S. Department of Labor, Office of Disability Employment Policy", href: "https://www.dol.gov/agencies/odep", note: "Employer-focused guidance on inclusive workplace practices and accommodation." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota technical assistance on disability access and rights in employment and services." },
  ],
};

export default pack;
