import type { CoursePack } from "../../source-types";

// Disability Inclusion · Practitioner, Module 2: Accessibility Auditing and Barrier Analysis.
// Program-authored course for accessibility coordinators, program managers, supervisors, policy analysts and inclusion champions.
const pack: CoursePack = {
  course: {
    id: "di-accessibility-auditing-and-barrier-analysis",
    indexNumber: 1113,
    seriesLabel: "Disability Inclusion · Practitioner",
    title: "Accessibility Auditing and Barrier Analysis",
    subtitle: "Walk a real journey, name every kind of barrier you find, decide what to fix first, and separate the fix you can make this week from the redesign that ends the problem.",
    scope: "For accessibility coordinators, equity professionals, learning leaders, human resources partners, program managers, supervisors, policy analysts, internal trainers and inclusion champions. Four lessons that teach a basic audit method for a service journey, a digital process, a meeting or an employee lifecycle, and that end with a completed barrier analysis canvas. Participation in this program is voluntary and does not replace required training.",
    treatment: "Four short lessons with scenarios, a sorting activity, flashcards, the barrier analysis canvas and knowledge checks",
    duration: "45–55 minutes",
    author: "One DHS — People, Access and Culture",
    coverImage: "/images/covers/language-access-design.jpg",
    coverAlt: "People wait in a human-services public lobby.",
    introTranscript: "An accessibility audit is not a checklist you complete at a desk. It is a walk through a journey the way a person actually takes it, from the first notice to the last confirmation, looking for the point where someone is stopped. This course teaches a basic audit you can run on a service, a digital process, a meeting or an employee lifecycle. You will learn to recognize eight kinds of barrier, to prioritize honestly by impact, urgency, reach and feasibility, and to write an immediate fix and a systemic fix side by side on a barrier analysis canvas.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Conduct a basic accessibility audit of a service journey, digital process, meeting process or employee lifecycle by walking it as a participant and recording each touchpoint.",
        "Classify the barriers you find as physical, communication, digital, attitudinal, policy, financial, transportation or procedural, and explain why the category shapes the owner and the fix.",
        "Prioritize barriers using impact, urgency, reach and feasibility, and defend the order in writing without letting feasibility hide a duty.",
        "Complete a barrier analysis canvas that separates the immediate fix from the systemic fix, names the owner of each, and states how success will be measured.",
        "Write an improvement proposal a decision maker can act on, with the evidence, the cost of doing nothing and a test that will show the fix worked.",
      ],
      evidence: [
        "Four knowledge checks that explain why a finding, category or priority is sound.",
        "A sorting activity that places twelve real findings into the eight barrier categories.",
        "One completed barrier analysis canvas for a journey in your own unit, with an immediate fix and a systemic fix.",
      ],
      appliedNextStep: "Choose one journey your unit owns. Walk it as a participant with at least one access lens, complete the canvas for the first barrier that stops someone, and put it in front of the person who owns the fix.",
    },
    governance: {
      contentOwner: "One DHS — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: ["Change in ADA, Section 504 or Section 508 guidance", "Change in the state accessibility standard or DHS audit and remediation procedures", "Feedback from disabled staff or participants that a scenario reads as unrealistic or stigmatizing"],
      relatedDoor: "An audit finding that involves a legal duty, an accommodation decision or a complaint goes to the ADA coordinator, human resources, civil rights or the accessibility team; this course helps you find and describe the barrier, it does not decide the case.",
      toolkitQuestion: "Who is trying to take part, where exactly are they stopped, what is the fix we can make now, and what is the fix that means nobody is stopped there again?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "accessibility-auditing-and-barrier-analysis-1",
        number: 1,
        title: "Choose a journey and walk it",
        summary: "Pick the right unit of analysis, map its touchpoints, and walk it with access lenses instead of reviewing it from a desk.",
        minutes: 12,
        learning: {
          objective: "Define the scope of an audit as a journey with a start, an end and touchpoints, and walk it with at least three access lenses to find where a person is stopped.",
          takeaways: [
            "The unit of an audit is a journey, not a building, a website or a policy: from the moment a person learns something exists to the moment they have what they came for.",
            "An audit is done with access lenses: keyboard only, screen reader, captions, magnification, plain reading, no car, no phone minutes, limited energy, a support person present.",
            "Record each touchpoint with what a person must do, what they must have, and what stops them, before you judge or fix anything.",
          ],
          evidence: "A journey map of one process with touchpoints and lenses; a knowledge check about scoping.",
          appliedNextStep: "Map one journey your unit owns on a single page: touchpoints in order, what the person needs at each, and which lenses you will walk it with.",
        },
        scenario: {
          context: "A DHS program manager asks you to “audit our website for accessibility.” The program’s real problem, she mentions in passing, is that people who start an application for a waiver service often stop after the first interview and never come back.",
          prompt: "How should you scope the audit?",
          options: [
            { label: "Audit the website as requested; that is what she asked for.", response: "A website scan will find defects, and they may matter. But the drop-off happens after the interview, which is not on the website. You would audit the wrong thing well." },
            { label: "Reframe the scope as the applicant journey from first contact through the interview to the next step, with the website as one touchpoint, and walk it with several access lenses.", response: "This puts the audit where the loss is happening and keeps the website in view without letting it define the whole problem.", recommended: true },
            { label: "Suggest a survey of people who dropped out before doing any audit.", response: "Hearing from people who left is valuable and belongs in the work, but a survey of people who have already disengaged is slow and often unanswered. Walk the journey now; ask people alongside it." },
          ],
        },
        transfer: {
          prompt: "Which journey in your unit loses people, and where do you suspect they are stopped?",
          options: ["Write the journey’s first and last touchpoint", "List the touchpoints between them in the order a person meets them", "Choose the three access lenses you will walk it with first"],
        },
        blocks: [
          { type: "text", heading: "The unit of analysis is a journey", body: "<p>Most accessibility reviews look at an object: a building, a website, a document. Objects are easy to scope and easy to certify. People, though, do not experience objects; they experience journeys. A person hears about a service, finds the information, decides whether to try, makes contact, waits, is interviewed, gets a decision, appeals or accepts, and then lives with the result. A barrier at any one of those points ends the journey, and it is often a point no object review would cover: the voicemail with no text alternative, the parking lot, the wait, the letter.</p><p>A basic audit therefore starts by naming the journey and its edges. Where does it begin for the person? Usually earlier than staff think, at the moment they learn the thing exists. Where does it end? Usually later, when they have what they came for and understand what happens next. Between the edges are <strong>touchpoints</strong>: each moment a person must do something, know something or have something. Write them in the order a person meets them, not the order your process chart shows.</p><p>Then walk the journey with <strong>access lenses</strong>. A lens is a deliberate constraint that shows you what a group of people already sees: keyboard only, a screen reader, captions on with sound off, screen magnified, plain-reading level, no car, no phone minutes, limited energy and pain, a support person present who is not allowed to answer for you. You cannot walk with every lens on the first pass; pick three that match the people your program serves and note the rest for later. And walk it, do not review it. Sit in the lobby. Call the number. Open the letter. Start the form at the point a person would, not from an internal link.</p>" },
          { type: "tabs", heading: "Four kinds of journey you can audit", tabs: [
            { label: "Service journey", body: "<p>Learning a service exists, finding information, contacting the office, waiting, being interviewed or assessed, receiving a decision, appealing, getting the service. Typical DHS examples: a county eligibility determination, a MnCHOICES assessment, a licensing application, a call to a help line.</p>" },
            { label: "Digital process", body: "<p>Any task completed on a screen: an online application, a renewal, a document upload, a training module, a scheduling tool. Walk it from the public entry point with a keyboard alone, then with a screen reader, then with magnification, and time how long each takes.</p>" },
            { label: "Meeting process", body: "<p>Invitation, registration, materials in advance, the route to the room or the link, the room itself, the format of the discussion, how people speak and are heard, notes afterward, and how decisions are reported back. Community advisory meetings and all-staff meetings both qualify.</p>" },
            { label: "Employee lifecycle", body: "<p>Posting, application, interview, offer, the first days on the job, equipment, training, performance review, accommodation, promotion, leave, exit. The lifecycle audit is where hiring panels, timed assessments and required training platforms show up as barriers.</p>" },
          ] },
          { type: "list", heading: "A first audit, step by step", ordered: true, items: ["Name the journey, its first touchpoint and its last, from the person’s point of view.", "List every touchpoint between them in the order a person meets it. Include waits, letters, phone trees and parking.", "For each touchpoint write three things: what the person must do, what they must have or know, and what could stop them.", "Choose three access lenses that match the people the program serves and walk the whole journey with each, taking notes as you go.", "Record every barrier with the exact place it occurs and what it prevents, without fixing or ranking yet.", "Ask at least two people with relevant lived experience to walk it or review your notes, and pay them for the time."] },
          { type: "leaderMove", heading: "Audit where the loss is", control: "You control whether the audit is scoped around the thing that is easy to review or the point where people actually disappear.", failure: "Do not accept “audit the website” or “check the room” as a finished scope. Ask where people stop, and put the audit there.", next: "Before your next audit begins, write one sentence that says whose journey it is and where you believe they are being stopped. Test that sentence first." },
          { type: "flashcards", heading: "Audit vocabulary", cards: [
            { front: "Journey", back: "<p>The path a person actually takes from learning a thing exists to having what they came for. The unit of an audit.</p>" },
            { front: "Touchpoint", back: "<p>Each moment in the journey where a person must do, know or have something. Waits, letters and parking lots are touchpoints.</p>" },
            { front: "Access lens", back: "<p>A deliberate constraint you walk the journey with: keyboard only, screen reader, captions, magnification, plain reading, no car, limited energy, support person present.</p>" },
            { front: "Stopping point", back: "<p>A touchpoint where a lens shows the person cannot continue independently in a reasonable time. Record it precisely before you think about the fix.</p>" },
          ] },
          { type: "knowledgeCheck", id: "accessibility-auditing-and-barrier-analysis-1-check", question: "You are auditing the journey for a county cash assistance interview. Which list of touchpoints is most complete?", options: [
            { text: "The interview itself and the decision letter.", correct: false },
            { text: "The notice that scheduled the interview, the phone tree or lobby, the wait, the identification and documents required, the interview, the decision letter, and the instructions for appeal.", correct: true },
            { text: "The county website and the online application form.", correct: false },
          ], feedbackCorrect: "Yes. A journey includes the notice, the way in, the wait, what the person must bring, the interview, the decision and the appeal. A barrier at any one of them ends the journey.", feedbackIncorrect: "Think from the person’s side. The journey started with the notice and does not end until they understand the decision and how to appeal it." },
        ],
      },
      {
        id: "accessibility-auditing-and-barrier-analysis-2",
        number: 2,
        title: "Eight kinds of barrier",
        summary: "Learn to name a barrier precisely, because the category tells you who owns it and what kind of fix will work.",
        minutes: 12,
        learning: {
          objective: "Classify audit findings as physical, communication, digital, attitudinal, policy, financial, transportation or procedural barriers, and explain how the category points to an owner and a fix.",
          takeaways: [
            "Eight categories cover most of what an audit finds; many findings belong to more than one, and the second category is often the one that gets missed.",
            "Attitudinal and procedural barriers are the most common and the least often written down, because they do not look like defects.",
            "Financial and transportation barriers are real access barriers even when the organization did not create them, and the organization can still reduce them.",
          ],
          evidence: "A completed sort of twelve findings; a knowledge check on a finding that belongs to two categories.",
          appliedNextStep: "Go back to the barriers you recorded in Lesson 1 and assign each a primary and, where it applies, a secondary category. Note who owns each.",
        },
        scenario: {
          context: "During a walk-through of a Disability Services Division community meeting, you note that the room is step-free, captions are on, and the slides were sent ahead. Then a participant who uses a communication device begins to type a response and the facilitator, trying to keep to schedule, says “Let’s come back to you” and moves on. The item is never revisited.",
          prompt: "What kind of barrier did you find, and what does that mean for the fix?",
          options: [
            { label: "None. The physical, communication and digital access were all in place.", response: "The room was accessible; the process was not. The participant was prevented from taking part as fully as everyone else. That is a barrier and it goes in the audit." },
            { label: "An attitudinal and procedural barrier: the facilitation practice assumes everyone responds at speaking speed, so the fix is in how the meeting is run, not in the room.", response: "Naming it this way points at the owner, whoever designs and runs the meeting, and at a fix that works: build wait time into the agenda, collect responses in more than one way, and always return.", recommended: true },
            { label: "A digital barrier: the communication device was too slow.", response: "The device did what it was built to do. Locating the barrier in the person’s equipment misplaces the problem and would lead you to a fix nobody needs." },
          ],
        },
        transfer: {
          prompt: "Which barrier category does your unit most often overlook?",
          options: ["Choose the category and write one example from your own journey map", "Name who owns that kind of fix in your organization", "Decide how you will make that category visible in your next report"],
        },
        blocks: [
          { type: "text", heading: "Why the category matters", body: "<p>“There is an accessibility problem” is a sentence that goes nowhere. “There is a procedural barrier at the document-upload step: the system accepts only one file format and rejects photographs taken on a phone” goes to a system owner with a fix attached. Naming the kind of barrier does three things at once: it locates the barrier in the design rather than in the person, it identifies who is responsible, and it suggests the kind of remedy that will work.</p><p>Eight categories cover most audit findings. <strong>Physical</strong>: the built environment, from door force to counter height to where the accessible parking actually is. <strong>Communication</strong>: how information is exchanged, including interpreters, captions, alternative formats, reading level and whether staff talk to the person or their companion. <strong>Digital</strong>: forms, documents, websites, platforms and kiosks. <strong>Attitudinal</strong>: assumptions, impatience, low expectations, treating a request as a favor. <strong>Policy</strong>: written rules that dictate a single method or add an unnecessary requirement. <strong>Financial</strong>: costs that fall on the person, including unpaid time off, printing, notarization, copays and the cost of a support person. <strong>Transportation</strong>: how a person gets there, including paratransit windows, rural distance and where the bus stops relative to the entrance. <strong>Procedural</strong>: the unwritten way things are done, such as timed sessions, the order of steps, who is allowed to help, and what happens when a step fails.</p><p>Many findings belong to two categories. A letter written at a college reading level in a small font is a communication barrier; the rule that only the letter counts as notice is a policy barrier. The second category is usually the one that keeps the problem alive after the first is fixed, so record both.</p>" },
          { type: "sorting", id: "accessibility-auditing-and-barrier-analysis-2-sort", heading: "Name the barrier", categories: ["Physical", "Communication", "Digital", "Attitudinal", "Policy", "Financial", "Transportation", "Procedural"], items: [
            { text: "The accessible entrance is at the back of the building and unmarked from the street.", category: "Physical" },
            { text: "The notice of interview is sent only as a printed letter in a small typeface.", category: "Communication" },
            { text: "The online renewal times out after fifteen minutes with no warning and no way to extend.", category: "Digital" },
            { text: "A worker says, “If she cannot handle the paperwork, maybe she should have someone manage her benefits.”", category: "Attitudinal" },
            { text: "The procedure says appeals must be submitted in writing and signed in ink.", category: "Policy" },
            { text: "Applicants must provide a notarized copy of a document, and the nearest notary charges a fee.", category: "Financial" },
            { text: "Paratransit can only guarantee a two-hour pickup window, and the appointment slot is thirty minutes.", category: "Transportation" },
            { text: "Staff are told not to help anyone fill in the form, even when asked, to avoid liability.", category: "Procedural" },
            { text: "Interpreters are booked only after the person arrives and asks.", category: "Procedural" },
            { text: "The video kiosk in the lobby has a touchscreen only and no audio output.", category: "Digital" },
            { text: "The interview room door requires a badge and there is no way to call staff from outside it.", category: "Physical" },
            { text: "A supervisor assumes a person with an intellectual disability cannot understand the choices and explains them to the support worker instead.", category: "Attitudinal" },
          ] },
          { type: "accordion", heading: "The two categories people forget to write down", items: [
            { title: "Attitudinal barriers", body: "<p>These are the hardest to record because they feel like opinions, not findings. Record them as behavior, not character: what was said, what was done, what it prevented. “Facilitator moved on while participant was still composing a response; item was not revisited” is a finding. “Facilitator was impatient” is a judgment. The behavior form is fair to the staff member and actionable for the owner.</p>" },
            { title: "Procedural barriers", body: "<p>These live in habit rather than policy, which is why nobody can point to a document. Ask staff, “What happens if this step fails?” and “Who is allowed to help here?” The answers reveal timed sessions, order-of-operations traps, and rules nobody wrote but everybody follows. A procedural barrier often has no owner until you name one, so name one in the audit.</p>" },
            { title: "Financial and transportation barriers", body: "<p>Organizations often exclude these because “we do not control the bus schedule.” You do not, but you control appointment lengths, whether phone and video are offered, whether a fee can be waived, whether a photograph of a document is accepted, and whether the accessible entrance is where the paratransit drop-off is. Record what the barrier prevents and the part of it you can move.</p>" },
          ] },
          { type: "quote", text: "The building passed its inspection. The problem was never the building. It was that nobody would let me finish a sentence, and nobody wrote that down.", cite: "Composite participant perspective, illustrative" },
          { type: "leaderMove", heading: "Write findings as behavior and location", control: "You control whether an audit finding is specific enough to hand to someone, or vague enough to be ignored.", failure: "Do not write “staff attitudes need improvement” or “the site has accessibility issues.” Write what happened, where, and what it prevented.", next: "Rewrite the three vaguest findings in your current notes as location, behavior or defect, and consequence." },
          { type: "flashcards", heading: "Eight categories, one line each", cards: [
            { front: "Physical", back: "<p>The built environment: routes, doors, counters, restrooms, signage, lighting, noise. Owner: facilities and whoever chose the room.</p>" },
            { front: "Communication", back: "<p>How information moves: interpreters, captions, formats, reading level, who is spoken to. Owner: language access, communications, and every staff member in the conversation.</p>" },
            { front: "Digital", back: "<p>Forms, documents, sites, platforms, kiosks. Owner: the system or document owner, with the accessibility team.</p>" },
            { front: "Attitudinal", back: "<p>Assumptions and behavior that limit participation. Owner: supervisors, through expectations, training and what they model.</p>" },
            { front: "Policy", back: "<p>Written rules that dictate a single method or add unnecessary requirements. Owner: the policy owner, with the ADA coordinator.</p>" },
            { front: "Financial, transportation, procedural", back: "<p>Costs on the person, ways of getting there, and unwritten habits. Owners are often unnamed; the audit names them.</p>" },
          ] },
          { type: "knowledgeCheck", id: "accessibility-auditing-and-barrier-analysis-2-check", question: "An audit finds that a decision letter is written at a college reading level and that the program counts only that letter as official notice of the appeal deadline. What is the most useful way to record this?", options: [
            { text: "One communication barrier: the letter is hard to read.", correct: false },
            { text: "Two findings: a communication barrier in the letter’s reading level and format, and a policy barrier in the rule that the letter is the only notice that counts. Each has its own owner.", correct: true },
            { text: "One digital barrier: the letter should be an email.", correct: false },
          ], feedbackCorrect: "Yes. Fixing the letter helps; fixing the rule is what stops people from losing appeal rights when any notice fails. Recording both keeps both owners accountable.", feedbackIncorrect: "The letter is a communication barrier, but the rule that only the letter counts is a policy barrier with a different owner. Record both, or the second one survives." },
        ],
      },
      {
        id: "accessibility-auditing-and-barrier-analysis-3",
        number: 3,
        title: "Prioritize by impact, urgency, reach and feasibility",
        summary: "Decide what to fix first in a way you can defend, without letting difficulty quietly demote a legal duty.",
        minutes: 12,
        learning: {
          objective: "Rank audit findings using impact, urgency, reach and feasibility, record the reasoning, and identify findings that must be acted on regardless of feasibility.",
          takeaways: [
            "Impact asks whether the barrier stops participation entirely or makes it harder; urgency asks what is lost while you wait; reach asks how many people and which people; feasibility asks what the fix costs in time, money and authority.",
            "Feasibility is the last question, not the first, and it never lowers a duty; a barrier that denies access has to be addressed even when the full fix is far off.",
            "Write the reasoning next to the rank so a decision maker can disagree with the judgment rather than the arithmetic.",
          ],
          evidence: "A priority table for at least six findings with reasoning; a knowledge check on a hard-but-urgent barrier.",
          appliedNextStep: "Rank the findings from your own journey map using the four questions, and mark any that involve a duty with a note that they are not optional regardless of feasibility.",
        },
        scenario: {
          context: "Your audit of a county eligibility journey produced nine findings. Two stand out: the interview notice arrives with too little time for someone to arrange paratransit, and the lobby signage uses low-contrast gray text. The paratransit fix means changing a statewide notice template; the signage can be replaced in a week.",
          prompt: "How do you prioritize?",
          options: [
            { label: "Fix the signage first because it is feasible, and list the notice timing as a long-term item.", response: "Feasibility is leading. The signage fix is fine to do this week, but calling the notice timing “long-term” lets a barrier that causes missed interviews and closed cases sit unaddressed." },
            { label: "Rank the notice timing highest on impact, urgency and reach, and pair it with an immediate local measure such as a phone call or text when the notice is sent, while the template change is pursued; do the signage as a quick win alongside.", response: "The hard fix gets the priority it deserves, the person gets relief now, and the easy fix still happens. Feasibility shaped the plan without shaping the ranking.", recommended: true },
            { label: "Send both to leadership and let them decide.", response: "Leadership should decide the systemic fix, but a practitioner who ranks nothing and recommends nothing has not done the analysis they were asked to do." },
          ],
        },
        transfer: {
          prompt: "Which finding in your unit is high impact but keeps getting demoted because it is hard?",
          options: ["Name the finding and what is lost while it waits", "Write an immediate local measure that reduces the harm now", "Identify whose authority the systemic fix needs"],
        },
        blocks: [
          { type: "text", heading: "Four questions in the right order", body: "<p>Every audit produces more findings than anyone can fix at once, so prioritizing is part of the method. The trap is letting feasibility go first. When the easiest fixes are done first because they are easy, the audit quietly becomes a list of cosmetic improvements while the barriers that actually stop people wait for a budget cycle. The order of the four questions is the safeguard.</p><p><strong>Impact</strong> comes first: does this barrier stop participation entirely, make it significantly harder, or make it less pleasant? A person who cannot submit an appeal because the only route is inaccessible has been stopped. A person who can submit it but takes twice as long has been burdened. Both matter; the first matters more. <strong>Urgency</strong> asks what is lost while you wait: benefits, jobs, appeal rights, safety, health. <strong>Reach</strong> asks how many people meet this barrier and which people; a barrier that affects a small number of people who have no other route can outrank one that inconveniences many. <strong>Feasibility</strong> comes last and asks what the fix costs in time, money and authority. It shapes the plan and the sequence. It does not change the rank, and it never lowers a duty. A barrier that denies access must be addressed now by some interim means even when the complete fix is far away.</p><p>Write the reasoning beside the rank. A simple scale, such as one to three on each question, is fine, but the sentences are what a decision maker can actually engage with. “Ranked first because it closes cases for people who cannot arrange transport in the time given; the template change requires a statewide owner; interim measure available locally” invites a decision. A number alone invites a shrug.</p>" },
          { type: "list", heading: "Signals for each question", items: ["Impact: can the person continue independently at all? If not, this is a stop, and stops rank above burdens.", "Urgency: is a benefit, job, appeal window, safety or health at stake during the wait? Deadlines raise urgency.", "Reach: how many people meet this touchpoint, and do the people affected have any other route? No other route raises reach even for small numbers.", "Feasibility: who has the authority, what does it cost, how long will it take, and what interim measure is available while the full fix is pursued?", "Duty check: does this finding involve effective communication, program access, a reasonable modification or a digital accessibility standard? If so, mark it as required, not optional, whatever the feasibility score."] },
          { type: "tabs", heading: "The same finding, four ways", tabs: [
            { label: "Impact", body: "<p>Finding: the online document upload rejects photographs from phones. For people without a scanner, this stops the application entirely; they cannot continue independently. Impact is high.</p>" },
            { label: "Urgency", body: "<p>An application that cannot be completed by the deadline is denied or delayed, and benefits depend on it. Urgency is high.</p>" },
            { label: "Reach", body: "<p>Most applicants use phones. People with the least equipment, the least income and the most disabilities are the most affected, and many have no other route. Reach is high.</p>" },
            { label: "Feasibility", body: "<p>The system owner can accept common image formats with a configuration change, and an interim route exists: accept documents by mail, in person or by email while the change is made. Feasibility is good, and the interim measure starts this week.</p>" },
          ] },
          { type: "leaderMove", heading: "Feasibility shapes the plan, not the rank", control: "You control whether hard-but-critical barriers stay at the top of the list with an interim measure, or slide to the bottom because they are hard.", failure: "Do not let a priority list become a list of easy wins. If every item at the top is cheap and quick, the ranking was done backwards.", next: "Look at your top three findings. If none of them is hard, re-rank with impact first and write the interim measure for the hard one." },
          { type: "flashcards", heading: "Prioritizing without self-deception", cards: [
            { front: "Stop versus burden", back: "<p>A stop means the person cannot continue independently in a reasonable time. A burden means they can, at a cost. Stops rank first.</p>" },
            { front: "Urgency", back: "<p>What is lost while the barrier waits: benefits, jobs, appeal rights, safety, health. A deadline in the journey raises urgency for everything before it.</p>" },
            { front: "Reach", back: "<p>How many people, and which people. Small numbers with no alternative route can outrank large numbers with an easy alternative.</p>" },
            { front: "Feasibility", back: "<p>Time, money and authority. Asked last. It decides the sequence and the interim measure; it does not decide whether a duty applies.</p>" },
            { front: "Interim measure", back: "<p>What you do this week for the person while the full fix is pursued. Every high-impact finding should have one written next to it.</p>" },
          ] },
          { type: "knowledgeCheck", id: "accessibility-auditing-and-barrier-analysis-3-check", question: "An audit finds that a required staff training platform cannot be completed with a screen reader. Fixing the platform depends on a vendor contract that will not renew for many months. What is the right way to prioritize this finding?", options: [
            { text: "Rank it low, because the fix is not feasible until the contract renews.", correct: false },
            { text: "Rank it high on impact, urgency and reach; provide an equivalent accessible way to complete the training now; and put the platform requirement into the renewal.", correct: true },
            { text: "Exempt affected staff from the training so the platform is not an issue.", correct: false },
          ], feedbackCorrect: "Yes. A stop for employees on required training is high on every question that matters. Feasibility shapes the sequence and the interim measure; it does not lower the priority.", feedbackIncorrect: "Feasibility comes last and does not lower a duty. Employees are stopped from required training; provide an equivalent route now and fix the platform through the contract." },
        ],
      },
      {
        id: "accessibility-auditing-and-barrier-analysis-4",
        number: 4,
        title: "Immediate fix, systemic fix, and the canvas",
        summary: "Complete the barrier analysis canvas, separate what you can do this week from the redesign that ends the problem, and write a proposal a decision maker can act on.",
        minutes: 12,
        learning: {
          objective: "Complete a barrier analysis canvas for one finding, with an immediate fix and a systemic fix, a named owner for each and a measure of success, and turn it into a short improvement proposal.",
          takeaways: [
            "The immediate fix restores access for the person now; the systemic fix changes the design so nobody is stopped there again. Both are required; neither substitutes for the other.",
            "A fix has an owner with authority and a date, or it is a wish.",
            "Success is measured by a test a person can pass, not by the fix being installed.",
          ],
          evidence: "One completed canvas for a real finding; a knowledge check about an improvement proposal.",
          appliedNextStep: "Complete the canvas for the highest-ranked finding in your audit and send it, with a one-page proposal, to the owner of the systemic fix. Ask for a decision date.",
        },
        scenario: {
          context: "A job applicant who uses a screen reader tells human resources that the state application form has unlabeled fields and a timed session she could not extend, so she could not finish. Human resources offers to take her application by phone and asks you to “close the loop.”",
          prompt: "What does closing the loop mean here?",
          options: [
            { label: "Confirm the phone application was taken and mark the issue resolved.", response: "The immediate fix served one applicant. The form is still stopping every other screen-reader user, and the next one may not call." },
            { label: "Record the phone application as the immediate fix, complete the canvas with the systemic fix, remediation or replacement of the form with keyboard and screen-reader testing before release, name the owners in human resources, technology and procurement, and set a success test.", response: "This is the full loop: the person served, the design changed, owners named, and a test that shows it worked.", recommended: true },
            { label: "Ask the applicant to document the defects in detail so the vendor can fix them.", response: "The organization owns the audit, not the applicant. Ask her permission to use her experience, pay her if she agrees to test the fix, and do the documentation yourself." },
          ],
        },
        transfer: {
          prompt: "Which finding in your audit is ready for a canvas today?",
          options: ["Complete the eight canvas questions for it in one sitting", "Name the owner of the systemic fix and the authority they need", "Write the test a person will pass when the fix has worked"],
        },
        blocks: [
          { type: "text", heading: "Two fixes, always", body: "<p>An audit that produces only immediate fixes is a help desk. An audit that produces only systemic fixes is a report that people wait on. The method requires both, side by side, for every finding that matters. The <strong>immediate fix</strong> restores access for the person in front of you now: an alternative route, a staff member who completes the form with them, an interpreter booked today, an extension granted, a document sent in the format they asked for. It is not a favor and it is not a workaround to be quietly repeated; it is the organization meeting its duty while the design is corrected. The <strong>systemic fix</strong> changes the design so nobody is stopped at that touchpoint again: the form is remediated or replaced, the template is rewritten, the procedure is changed, the room is moved, the contract includes accessibility acceptance testing.</p><p>Both fixes need an <strong>owner</strong>, meaning a person or office with the authority to make the change, and a date. “IT” is not an owner; the named system owner in technology is. “Procurement should require accessibility” is not a fix; the named contract manager adding acceptance criteria to a specific renewal is. Where the systemic fix needs authority you do not have, the canvas says whose authority it needs, and your proposal asks for it.</p><p>Finally, <strong>success is a test, not an installation</strong>. A form is fixed when a person using a keyboard alone and a person using a screen reader can complete it without help in a reasonable time. A notice template is fixed when people who rely on paratransit make their interviews at the same rate as everyone else. Write the test before the fix begins, and have the people the barrier affected run it, paid, when the fix is done.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical artifact", title: "Barrier analysis canvas", summary: "Eight questions on one page. Complete it for each finding that stops or seriously burdens a person. The example entries describe a job applicant who uses a screen reader and could not complete an online application.", fields: [
            { label: "Who is trying to participate?", value: "Name the person or group by what they are doing and how, not by diagnosis. Example: a job applicant who uses a screen reader and keyboard navigation." },
            { label: "What are they trying to do?", value: "The task in the person’s terms. Example: complete and submit the online application for a posted position before the closing date." },
            { label: "What barrier occurs?", value: "The exact defect, rule or behavior, and where in the journey. Example: form fields are unlabeled, so the screen reader does not announce them, and the session times out with no warning and no way to extend." },
            { label: "What is the impact?", value: "Stop or burden, and what is at stake. Example: the applicant cannot complete the application independently and risks missing the closing date; other screen-reader users are likely stopped the same way and may not report it." },
            { label: "What is the immediate fix?", value: "How access is restored now, by whom, by when. Example: human resources takes the application by phone or accessible document today, confirms receipt in writing, and extends the deadline for anyone affected by the defect." },
            { label: "What is the systemic fix?", value: "The design change that ends the barrier. Example: remediate the form’s labels and timing behavior or replace the platform, with keyboard and screen-reader acceptance testing required before release and written into the next contract." },
            { label: "Who owns the fix?", value: "A named person or office with authority, for each fix, with a date. Example: immediate fix, the human resources recruiter, today; systemic fix, the application system owner in technology and the contract manager in procurement, with the accessibility lead advising, decision date within 30 days." },
            { label: "How will success be measured?", value: "A test a person can pass. Example: applicants using a keyboard alone and a screen reader complete a live application without assistance in comparable time; the test is run by paid disabled testers before release and after each major change." },
          ], action: "Complete the canvas for your highest-ranked finding and attach it to a one-page proposal to the owner of the systemic fix." },
          { type: "accordion", heading: "From canvas to proposal", items: [
            { title: "One page, five parts", body: "<p><strong>The finding</strong> in one sentence, with location and impact. <strong>The evidence</strong>: what you observed, who walked the journey, what lenses were used, what people with lived experience said. <strong>The two fixes</strong>, each with owner, date and cost in time and money as far as you know. <strong>The cost of doing nothing</strong>: what is lost each month the barrier stands, in people stopped, cases closed, complaints, staff time spent on workarounds and duty unmet. <strong>The decision requested</strong>: exactly what you are asking the reader to approve, by when.</p>" },
            { title: "Write for the person who can say yes", body: "<p>Lead with impact and the decision requested, not with the method. A director does not need the eight categories; they need to know who is being stopped, what it costs, what you propose and what you need from them. Put the canvas behind the page as the detail.</p>" },
            { title: "Keep the record", body: "<p>Date the audit, the proposal and the decision. When the fix is made, run the success test and record the result next to the canvas. An audit trail that shows a barrier found, a fix made and a test passed is what turns individual effort into organizational memory.</p>" },
          ] },
          { type: "leaderMove", heading: "No fix without an owner and a test", control: "You control whether every fix in your report has a named owner with authority, a date and a test a person can pass.", failure: "Do not let “IT will look into it” or “procurement should require accessibility” stand as a fix. Name the person, the date and the test, or the finding will still be there next year.", next: "Review your last three recommendations. For each, write the owner’s name, the decision date and the test. If you cannot, the recommendation is not finished." },
          { type: "flashcards", heading: "Finishing the audit", cards: [
            { front: "Immediate fix", back: "<p>Restores access for the person now, by a named person, today or this week. It is the duty being met while the design is corrected, not a permanent workaround.</p>" },
            { front: "Systemic fix", back: "<p>Changes the design, rule, template, room or contract so nobody is stopped at that touchpoint again. Needs an owner with authority and a date.</p>" },
            { front: "Owner", back: "<p>A named person or office with the authority to make the change. Not a department name, not a hope.</p>" },
            { front: "Success measure", back: "<p>A test a person can pass, run by the people the barrier affected, paid, before release and after each major change.</p>" },
            { front: "Cost of doing nothing", back: "<p>People stopped, cases closed, appeal rights lost, staff time on workarounds, complaints and unmet duty, per month. The number that makes a proposal real.</p>" },
          ] },
          { type: "knowledgeCheck", id: "accessibility-auditing-and-barrier-analysis-4-check", question: "Which improvement proposal is most likely to produce a real change?", options: [
            { text: "“The lobby kiosk is inaccessible and should be fixed. IT has been notified.”", correct: false },
            { text: "“The lobby kiosk has no audio output or keyboard access, so people who are blind cannot check in independently and wait longer. Interim: staff greet and check in on request, starting today, owner the lobby lead. Systemic: replace the kiosk with one that meets the state standard, owner the facilities system manager, decision requested within 30 days. Success: a blind tester checks in independently.”", correct: true },
            { text: "“Kiosk accessibility should be considered in future procurement.”", correct: false },
          ], feedbackCorrect: "Yes. Finding, impact, two fixes with owners and dates, a decision requested and a test a person can pass. That is a proposal someone can approve.", feedbackIncorrect: "Look for the parts that make a fix real: who is stopped, an immediate measure with an owner, a systemic fix with an owner and date, and a test. Notifications and future considerations are not fixes." },
          { type: "statement", body: "An audit is finished when a person who was stopped can now get through, and when the design has changed so the next person is never stopped there at all. Anything less is a report." },
        ],
      },
    ],
  },
  jobAid: {
    title: "The basic audit",
    subtitle: "A one-page method for walking a journey and writing a barrier you can hand to someone",
    quote: "Walk it as a person would. Name the barrier precisely. Rank by impact first. Fix it twice: now, and for good.",
    use: {
      purpose: "Run a basic accessibility audit of a service, a digital process, a meeting or an employee lifecycle, and turn what you find into fixes with owners.",
      remember: ["The unit is a journey with touchpoints, not a building or a website.", "Eight categories: physical, communication, digital, attitudinal, policy, financial, transportation, procedural. Record the second one too.", "Impact, urgency, reach, then feasibility. Feasibility never lowers a duty.", "Every finding that matters gets an immediate fix and a systemic fix, each with an owner, a date and a test."],
      doNext: "Complete one barrier analysis canvas this month and put it in front of the person who owns the systemic fix.",
    },
    sections: [
      { heading: "Walking the journey", items: ["Name the first and last touchpoint from the person’s side; list everything between, including waits, letters and parking.", "Walk it with three access lenses that match the people served: keyboard only, screen reader, captions, magnification, plain reading, no car, limited energy, support person present.", "Record each stopping point as location, defect or behavior, and what it prevented. Do not rank or fix yet.", "Have at least two people with relevant lived experience walk it or review it, and pay them."] },
      { heading: "Ranking honestly", items: ["Stop outranks burden. Deadlines raise urgency. No alternative route raises reach.", "Feasibility shapes the sequence and the interim measure, not the rank.", "Mark any finding that touches effective communication, program access, reasonable modification or a digital standard as required.", "Write the reasoning beside every rank."] },
      { heading: "The canvas and the proposal", items: ["Who is trying to participate, what are they trying to do, what barrier occurs, what is the impact.", "Immediate fix and systemic fix, each with a named owner and a date.", "Success is a test a person can pass, run by paid disabled testers before release and after changes.", "One page for the decision maker: finding, evidence, two fixes, cost of doing nothing, decision requested."] },
    ],
  },
  sources: [
    { title: "ADA National Network", href: "https://adata.org/", note: "ADA information, guidance and training, including materials on program access and self-evaluation for state and local governments." },
    { title: "ADA.gov, Topics", href: "https://www.ada.gov/topics/", note: "Plain-language explanations of effective communication, program access and other Title II duties that audit findings often touch." },
    { title: "U.S. Access Board", href: "https://www.access-board.gov/", note: "Federal accessibility standards for buildings, facilities and information and communication technology used when classifying physical and digital barriers." },
    { title: "Section508.gov, Test for Accessibility", href: "https://www.section508.gov/test/", note: "Federal guidance on testing digital content and applications, including manual keyboard and screen-reader testing." },
    { title: "W3C Web Accessibility Initiative, Accessibility Fundamentals", href: "https://www.w3.org/WAI/fundamentals/", note: "Foundational explanations of how people with disabilities use digital content, useful for choosing access lenses." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota resources on accessibility, disability law and access in state programs and facilities." },
  ],
};

export default pack;
