import type { CoursePack } from "../../source-types";

// Disability Inclusion · Practitioner, Module 4: Co-design and Lived-Experience Partnership.
// Program-authored course for program managers, equity professionals, learning leaders, policy analysts, supervisors and inclusion champions who work with disabled advisors.
const pack: CoursePack = {
  course: {
    id: "di-co-design-and-lived-experience",
    indexNumber: 1115,
    seriesLabel: "Disability Inclusion · Practitioner",
    title: "Co-design and Lived-Experience Partnership",
    subtitle: "Work with disabled people and disability-led organizations as paid partners whose expertise changes decisions, and build the loop that shows them it did.",
    scope: "For accessibility coordinators, equity professionals, learning leaders, human resources partners, program managers, supervisors, policy analysts, internal trainers and inclusion champions. Four lessons on ethical partnership, fair compensation, recognizing tokenism and extraction, and building a paid advisory panel with real feedback loops. Participation in this program is voluntary and does not replace required training.",
    treatment: "Four short lessons with scenarios, a sorting activity, flashcards, a paid advisory panel charter and knowledge checks",
    duration: "45–55 minutes",
    author: "One DHS — People, Access and Culture",
    coverImage: "/images/covers/cultural-broker-role.jpg",
    coverAlt: "Two colleagues sit at a government table.",
    introTranscript: "The disability rights movement has a phrase for how decisions should be made: nothing about us without us. Inside a public agency, living up to it takes more than an invitation. It takes partnership that begins before the design is fixed, payment that treats lived experience as expertise, protection against the quiet habits of tokenism and extraction, and a loop that carries recommendations back to the people who made them with an honest account of what happened. This course teaches those four things and ends with a charter for a paid advisory panel you can adapt for your own program.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Describe the difference between informing, consulting, involving, collaborating and sharing authority with disabled people, and choose the right level for a given decision.",
        "Explain why lived experience is expertise, set a fair compensation approach, and address the practical barriers to paying people, including benefits interactions and procurement delays.",
        "Recognize tokenism, extractive consultation and last-minute review in your own program’s practices and propose the change that corrects each.",
        "Design a feedback loop in which advisors can see what was recommended, what was decided, why, and what changed as a result.",
        "Draft a paid advisory panel charter that covers purpose, decision authority, recruitment and representation, compensation, confidentiality, meeting access and how recommendations are communicated back.",
      ],
      evidence: [
        "Four knowledge checks that explain why a practice builds partnership or undermines it.",
        "A sorting activity that separates partnership from tokenism and extraction in twelve real situations.",
        "A draft advisory panel charter for one program, with compensation and feedback loop sections completed.",
      ],
      appliedNextStep: "Identify one decision your program will make in the next quarter that affects disabled people. Decide the level of partnership it warrants, budget for paid advisors, and draft the charter sections that decision needs.",
    },
    governance: {
      contentOwner: "One DHS — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: ["Change in state contracting, stipend or vendor payment procedures affecting advisor compensation", "Change in DHS community engagement or advisory committee policy", "Feedback from disabled advisors or disability-led organizations that a scenario or practice reads as unrealistic or disrespectful"],
      relatedDoor: "Contracts, stipends, data practices and formal advisory committee appointments go through procurement, finance, data practices and the responsible program office; this course helps you design the partnership, it does not authorize a payment or an appointment.",
      toolkitQuestion: "Who with lived experience is shaping this decision, are they paid, did they join before the design was fixed, and how will they learn what happened to their advice?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "co-design-and-lived-experience-1",
        number: 1,
        title: "From consultation to partnership",
        summary: "Understand the levels of participation, why timing decides whether advice can matter, and what disability-led organizations bring that individual advisors cannot.",
        minutes: 12,
        learning: {
          objective: "Distinguish informing, consulting, involving, collaborating and sharing authority, and match the level of partnership to the weight of a decision and the point in the process where advice can still change it.",
          takeaways: [
            "Participation runs from being told, to being asked, to shaping options, to deciding together, to holding authority; each level makes a different promise and each promise has to be kept.",
            "Timing is the decisive variable: advice invited after the design, budget or contract is fixed cannot change it, whatever the level is called.",
            "Disability-led organizations bring collective knowledge, accountability to a community and the ability to reach people the agency cannot; they should be partners, not sources of free referrals.",
          ],
          evidence: "A knowledge check on choosing the level; one upcoming decision in your program placed on the ladder with the point at which advisors will join.",
          appliedNextStep: "For the next decision your program makes that affects disabled people, write which level of participation you are offering, when advisors join, and what they can still change at that point.",
        },
        scenario: {
          context: "A DHS division is redesigning how people apply for a home and community-based waiver. The project plan schedules a “community listening session” in the final month, after the new form and the vendor contract are complete, so leadership can “hear from people with disabilities before launch.”",
          prompt: "What is the honest description of this plan, and what would you change?",
          options: [
            { label: "It is co-design; people with disabilities will be heard before launch.", response: "By the final month there is nothing left to design. People will be heard, and nothing they say can change the form or the contract. Calling that co-design promises something the plan cannot deliver." },
            { label: "It is informing dressed as consulting. Move paid advisors to the start, before the requirements and the contract are set, and keep them through testing; if the schedule cannot move, say plainly that the session is to explain the new process and gather issues for the first revision.", response: "Either fix is honest. The first makes real partnership possible; the second stops the agency from claiming a level of participation it did not offer.", recommended: true },
            { label: "Cancel the session, since it cannot change anything.", response: "People still deserve to know what is coming and to have a place to report problems. Keep the session and describe it truthfully, while fixing the timing for the next decision." },
          ],
        },
        transfer: {
          prompt: "Which decision in your program is currently labeled a level of participation it does not actually offer?",
          options: ["Name the decision and the label it carries", "Write what advisors can still change at the point they are invited", "Decide whether to move the invitation earlier or correct the label"],
        },
        blocks: [
          { type: "text", heading: "Five levels, one honest question", body: "<p>Public agencies use the word “engagement” for very different things. It helps to name the levels. <strong>Informing</strong> tells people what has been decided. <strong>Consulting</strong> asks for reactions to options the agency has already drafted. <strong>Involving</strong> brings people in to shape the options themselves. <strong>Collaborating</strong> means deciding together, with advisors at the table when trade-offs are made. <strong>Sharing authority</strong> gives a community body a real vote or a veto on defined decisions. None of these is wrong in itself. Informing is the right level for telling people about a decision already made by law. The failure is calling one level by the name of another, because each level makes a promise, and people can tell when it is broken.</p><p>The variable that decides whether a level is real is timing. Advice can only change what is still open. If the requirements are written, the budget approved and the vendor chosen, a listening session is informing no matter how carefully it is facilitated, because the answer to “what can we still change?” is “the training materials.” Co-design means disabled people are present when the problem is framed, when options are generated, when trade-offs are made and when the result is tested. That is earlier, longer and more expensive than a session in the final month, and it is the only version that deserves the name.</p><p>Individual advisors and <strong>disability-led organizations</strong> both matter, and they bring different things. An individual brings their own experience, which is real and specific and not representative of anyone else. An organization led by disabled people, such as a center for independent living, a self-advocacy group or a cross-disability coalition, brings collective knowledge, accountability to a community, the capacity to reach people the agency cannot, and the standing to tell you when a plan is wrong. Treat them as partners with a scope, a budget and a contract, not as a mailing list for recruiting volunteers.</p>" },
          { type: "tabs", heading: "The levels, with the promise each one makes", tabs: [
            { label: "Inform", body: "<p><strong>Promise:</strong> we will tell you what was decided, why, and how it affects you, in formats you can use. <strong>Right for:</strong> decisions already made by law or higher authority. <strong>Fails when:</strong> it is described as consultation.</p>" },
            { label: "Consult", body: "<p><strong>Promise:</strong> we will ask for your reactions to options we drafted, and tell you how your input influenced the result. <strong>Right for:</strong> choices among options the agency must own. <strong>Fails when:</strong> the options are already chosen or the feedback is never reported back.</p>" },
            { label: "Involve", body: "<p><strong>Promise:</strong> you will help shape the options before we choose, and your concerns will be visible in the alternatives considered. <strong>Right for:</strong> service design, forms, communication, meeting formats. <strong>Fails when:</strong> people join after the options are fixed.</p>" },
            { label: "Collaborate", body: "<p><strong>Promise:</strong> we will decide together; you will be at the table when trade-offs are made and your recommendations will be adopted to the greatest extent possible, with reasons given when they are not. <strong>Right for:</strong> program redesign, policy affecting participation, procurement of systems people must use. <strong>Fails when:</strong> the table is real but the decision is made elsewhere.</p>" },
            { label: "Share authority", body: "<p><strong>Promise:</strong> a defined body holds a vote or a veto on defined decisions. <strong>Right for:</strong> governance of programs that exist for the community. <strong>Fails when:</strong> the authority exists on paper but decisions route around it.</p>" },
          ] },
          { type: "leaderMove", heading: "Name the level truthfully", control: "You control whether your project plan calls a listening session in the final month “co-design,” or says what it is and moves partnership to the start of the next one.", failure: "Do not schedule community input after the contract is signed and describe it as partnership. People notice, and the next invitation will go unanswered.", next: "On your current project plan, write beside each engagement activity the level it actually offers and what can still change at that point. Move one of them earlier." },
          { type: "flashcards", heading: "Partnership vocabulary", cards: [
            { front: "Co-design", back: "<p>Disabled people present when the problem is framed, when options are generated, when trade-offs are made and when the result is tested. Not a session at the end.</p>" },
            { front: "Timing test", back: "<p>Ask, “What can advisors still change at the point they join?” If the answer is only the training materials, the level is informing.</p>" },
            { front: "Disability-led organization", back: "<p>An organization governed and staffed mainly by disabled people, accountable to a community. A partner with scope, budget and contract; not a free recruiting channel.</p>" },
            { front: "Representation", back: "<p>No individual represents all disabled people. Seek a range across disability types, ages, races, languages, geography and experience with the program, and say plainly whose voices are still missing.</p>" },
          ] },
          { type: "quote", text: "They asked what we thought of the new form. I said the questions were wrong. They said the questions came from the contract. So what exactly were they asking?", cite: "Composite advisor perspective, illustrative" },
          { type: "knowledgeCheck", id: "co-design-and-lived-experience-1-check", question: "A program is choosing a new online scheduling system that every participant will use. Which level of partnership fits, and when should advisors join?", options: [
            { text: "Inform participants after the system is chosen, with clear instructions.", correct: false },
            { text: "Collaborate: paid disabled advisors help define the requirements before procurement, sit in on demonstrations, and test the finalists before the contract is awarded.", correct: true },
            { text: "Consult after the contract is awarded so advisors can help design the training.", correct: false },
          ], feedbackCorrect: "Yes. A system everyone must use is a decision with heavy consequences and real trade-offs. Advisors need to shape requirements and test candidates while the choice is still open.", feedbackIncorrect: "Once the contract is awarded, advisors can only shape training. For a system every participant must use, bring paid advisors in before requirements are set and have them test the finalists." },
        ],
      },
      {
        id: "co-design-and-lived-experience-2",
        number: 2,
        title: "Pay people for their expertise",
        summary: "Treat lived experience as expertise with a rate, and solve the practical barriers that keep public agencies from paying disabled advisors on time and safely.",
        minutes: 12,
        learning: {
          objective: "Set a fair compensation approach for disabled advisors and address benefits interactions, payment timing, procurement paperwork and access costs before the first meeting.",
          takeaways: [
            "Lived experience is expertise the agency does not have; the people who provide it are paid the way other experts are paid, at a rate set before recruitment and stated in the invitation.",
            "Payments can affect public benefits some advisors rely on; offer choices in how people are compensated, point to benefits planning help, and never decide for someone that they should go unpaid.",
            "Access costs, transportation, interpreters, support persons, materials in alternative formats and unpaid preparation time are part of the real cost of participation and are the agency’s to cover.",
          ],
          evidence: "A knowledge check on compensation choices; a compensation section drafted for your charter with rate, method, timing and access costs.",
          appliedNextStep: "Before recruiting anyone, confirm with finance and procurement how advisors can be paid, how long it takes, and what paperwork is required, and write the answer into the invitation.",
        },
        scenario: {
          context: "A DHS program wants six disabled advisors for a year-long redesign. The budget has money for a facilitator and refreshments but not for advisors. A manager suggests offering volunteer certificates and lunch, and notes that “some of them are on benefits anyway, so they probably cannot accept money.”",
          prompt: "How do you respond?",
          options: [
            { label: "Agree; volunteer recognition avoids the benefits problem and the paperwork.", response: "This asks disabled people to give a year of expertise for lunch while the facilitator is paid, and it decides for them that they cannot accept money. Both are the agency’s problems to solve, not the advisors’." },
            { label: "Move budget to pay advisors at a stated rate, offer more than one form of compensation so each person can choose what works with their situation, connect people with benefits planning help, and cover access costs separately.", response: "This treats advisors as the experts they are, respects that each person knows their own benefits situation best, and puts the administrative work where it belongs.", recommended: true },
            { label: "Recruit only advisors who do not receive benefits, to keep it simple.", response: "That excludes exactly the people whose experience of the program is deepest and skews the panel toward those with the most resources. Solve the payment problem instead." },
          ],
        },
        transfer: {
          prompt: "What does your program currently pay a disabled advisor for a two-hour meeting, and what does it pay a consultant?",
          options: ["Write both numbers, or write that you do not know", "Find out how advisors can be paid and how long payment takes", "Draft the compensation section of your charter with rate, choices, timing and access costs"],
        },
        blocks: [
          { type: "text", heading: "Expertise has a rate", body: "<p>When an agency hires a consultant to explain how a system works, nobody suggests paying in lunch. Lived experience of disability, of the program, of the waiting room and the appeal process is expertise the agency does not have and cannot get another way. Paying for it is not generosity; it is what makes the relationship professional, keeps participation open to people who cannot afford unpaid time, and signals that the advice is expected to matter. Set the rate before recruiting, state it in the invitation, and pay for preparation and review time, not only the hours in the room. Many organizations benchmark advisor pay to what they pay other outside experts or to a professional hourly rate; whatever the benchmark, it should be defensible when an advisor asks how it was set.</p><p>The hardest practical question is <strong>benefits interaction</strong>. Some advisors receive income-tested benefits, such as Supplemental Security Income, Medical Assistance or housing assistance, where earnings can reduce a benefit or trigger reporting. This is a real concern; it is not a reason to pay nothing. Offer choices: taxable payment as a contractor or stipend, gift cards where policy allows, payment to a disability-led organization that then compensates its members, or an honorarium schedule that stays under reporting thresholds the advisor identifies. Connect people with benefits planning resources so they can decide with good information, and accept the choice they make. Never decide on someone’s behalf that they are better off unpaid.</p><p>Then there is the machinery. State payment often requires vendor registration, tax forms and weeks of processing. An advisor who gives a Tuesday evening and is paid in ten weeks has, in effect, made the agency a loan. Fix this before the first meeting: find out from finance and procurement exactly how advisors can be paid, how long it takes and what paperwork is needed; help people complete it; consider paying through a partner organization if that is faster; and tell advisors the real timeline. <strong>Access costs</strong> are separate from compensation and always covered: transportation or paratransit, interpreters and captioning, a paid support person, materials in the person’s format, and a meeting time and place that work for people with pain, fatigue and care responsibilities.</p>" },
          { type: "accordion", heading: "Compensation questions to settle before you recruit", items: [
            { title: "What is the rate, and how was it set?", body: "<p>State an hourly or per-meeting rate and a benchmark you can defend: what the agency pays other outside experts, or a professional rate for comparable advisory work. Pay for preparation, review of documents and follow-up, not only meeting hours.</p>" },
            { title: "What forms of payment can people choose from?", body: "<p>Offer more than one: contractor or stipend payment, gift cards where policy allows, payment through a disability-led organization, or an honorarium schedule. Let each advisor choose privately; do not require anyone to explain their benefits situation to the group.</p>" },
            { title: "How will benefits interactions be handled?", body: "<p>Say in the invitation that compensation may affect some public benefits, that the advisor decides what to accept, and where to get benefits planning help. Provide written documentation of payments on request so people can report accurately.</p>" },
            { title: "How long will payment take, and who helps with paperwork?", body: "<p>Confirm the real timeline with finance and procurement and tell people. Name a staff member who helps with vendor registration and tax forms. If the state route is slow, consider a partner organization that can pay faster.</p>" },
            { title: "What access costs are covered, and how?", body: "<p>Transportation and paratransit, interpreters and captioning, a paid support person, materials in the person’s format, child or dependent care where policy allows. Covered directly by the agency, not reimbursed from the advisor’s pocket weeks later.</p>" },
            { title: "What do advisors get besides money?", body: "<p>A named contact, documents in advance, a real account of what happened to their advice, and credit in the final product if they want it. These are in addition to payment, never a substitute for it.</p>" },
          ] },
          { type: "list", heading: "What the invitation says about money", items: ["The rate and what it covers: meeting time, preparation and review.", "The choices of payment form, and that the choice is private.", "That payment may affect some benefits, that the advisor decides, and where to get planning help.", "The real payment timeline and the name of the person who helps with paperwork.", "That access costs are covered directly and how to request them."] },
          { type: "leaderMove", heading: "Budget the advisors before the facilitator", control: "You control whether the project budget has a line for paying disabled advisors before it has a line for consultants, catering or design.", failure: "Do not launch a redesign whose only unpaid experts are the disabled people it is for. If the budget cannot pay advisors, it cannot pay for co-design, and the plan should say so.", next: "Open your project budget. If advisor compensation is not a line, add it now and move money from elsewhere to fund it." },
          { type: "flashcards", heading: "Paying people well", cards: [
            { front: "Rate", back: "<p>Set before recruitment, stated in the invitation, benchmarked to what other experts are paid, covering preparation and review as well as meetings.</p>" },
            { front: "Choice of payment form", back: "<p>Contractor or stipend, gift card where allowed, payment through a partner organization, or an honorarium schedule. Chosen privately by each advisor.</p>" },
            { front: "Benefits interaction", back: "<p>Earnings can affect income-tested benefits. Disclose it, offer choices, point to benefits planning help, and accept the advisor’s decision. Never decide for them.</p>" },
            { front: "Payment timeline", back: "<p>Confirmed with finance and procurement, told to advisors in advance, with a named helper for paperwork. A ten-week wait is a loan the advisor did not agree to make.</p>" },
            { front: "Access costs", back: "<p>Transportation, interpreters, captioning, support persons, formats, care. Covered directly by the agency, separate from compensation.</p>" },
          ] },
          { type: "knowledgeCheck", id: "co-design-and-lived-experience-2-check", question: "An advisor tells you privately that a cash stipend might put her over an income limit for a benefit she relies on. What is the right response?", options: [
            { text: "Thank her for volunteering and note that she has chosen not to be paid.", correct: false },
            { text: "Offer the other forms of compensation the program set up, share benefits planning resources, give her time to decide, and pay her in whatever form she chooses.", correct: true },
            { text: "Ask her to bring documentation of her benefits so the program can decide what is safe to pay.", correct: false },
          ], feedbackCorrect: "Yes. She keeps the decision and the information she needs to make it, and the program keeps its commitment to pay.", feedbackIncorrect: "The advisor decides, with good information and real choices. The program does not treat her concern as a decision to go unpaid, and it does not ask for private benefits records to decide for her." },
        ],
      },
      {
        id: "co-design-and-lived-experience-3",
        number: 3,
        title: "Recognizing tokenism and extraction",
        summary: "Learn the specific habits that turn partnership into performance, and the change that corrects each one.",
        minutes: 12,
        learning: {
          objective: "Identify tokenism, extractive consultation and last-minute review in program practice and propose the concrete change that corrects each.",
          takeaways: [
            "Tokenism is presence without influence: one person, invited to stand for everyone, in a room where the decision is made elsewhere.",
            "Extraction is taking people’s stories, time and ideas without payment, credit or any account of what happened to them.",
            "Last-minute review invites people to approve what they could not shape, and makes them responsible for outcomes they did not choose.",
          ],
          evidence: "A completed sort of twelve practices; a knowledge check on one practice from your own program with the correction written.",
          appliedNextStep: "Review the last three times your program asked disabled people for input. For each, write which pattern it matched, if any, and the specific change you will make next time.",
        },
        scenario: {
          context: "A county partner proudly reports that its new accessibility plan was “developed with the disability community.” On inquiry, the process was one unpaid focus group whose participants signed a photo release, a quotation from one participant on the report cover, and a request that the same participant “represent the community” at the county board presentation.",
          prompt: "What is happening here, and what would partnership have looked like?",
          options: [
            { label: "This is reasonable community engagement for a small county.", response: "Size does not change the pattern. Unpaid stories, a photograph on a cover and one person asked to stand for everyone are tokenism and extraction with a friendly face." },
            { label: "Tokenism and extraction: pay the participants, report back what changed because of what they said, bring several advisors into the plan’s revision with real influence, and stop asking one person to represent a community.", response: "Each correction removes a specific harm, and together they turn a photograph into a partnership.", recommended: true },
            { label: "Ask the county to remove the quotation and photograph so no one is exploited.", response: "Removing the visible signs does not fix the process. The focus group still went unpaid and unanswered. Fix the practice; then the credit, given with consent, is fine." },
          ],
        },
        transfer: {
          prompt: "Which of the three patterns is your program most at risk of right now?",
          options: ["Name the pattern and the practice that matches it", "Write the correction in one sentence", "Decide who has to agree to the change and ask them this week"],
        },
        blocks: [
          { type: "text", heading: "Three patterns with friendly faces", body: "<p>Almost nobody sets out to tokenize people. The patterns grow from schedules, budgets and good intentions. Naming them precisely makes them easier to see in a project plan before they harm anyone.</p><p><strong>Tokenism</strong> is presence without influence. Its signs: one disabled person on a committee of fifteen, invited to “represent the disability community”; a seat at a table where the decision is actually made in a smaller meeting; a request for a quotation or a photograph for the report; a person asked to speak for people whose disabilities, races, languages and lives are nothing like their own. The token pays twice, once by carrying the weight of everyone’s expectations and once by being blamed when the result does not work for people they never claimed to represent. The correction is plural, paid advisors with real scope, and an honest statement of whose voices are still missing.</p><p><strong>Extraction</strong> is taking without return. Its signs: unpaid focus groups; asking people to retell painful experiences for a report; collecting ideas that appear later without credit; never telling participants what happened to their input. Many disabled people have been consulted many times and seen nothing change, which is why a new invitation is met with fatigue rather than interest. The correction is payment, consent for how stories are used, credit offered and controlled by the person, and a report back every time. <strong>Last-minute review</strong> is the request to approve what people could not shape. It arrives as “can you take a quick look before this goes out Friday.” It makes advisors responsible for outcomes they did not choose and gives them the choice of rubber-stamping or being the obstacle. The correction is timing: bring people in when the questions are still open, and when you genuinely only need a check, say so and pay for it as a review, not a partnership.</p>" },
          { type: "sorting", id: "co-design-and-lived-experience-3-sort", heading: "Partnership, tokenism or extraction?", categories: ["Partnership", "Tokenism", "Extraction"], items: [
            { text: "Five paid advisors with a range of disabilities help write the requirements before the vendor search begins.", category: "Partnership" },
            { text: "One disabled employee is asked to join every committee so the agency can say people with disabilities were included.", category: "Tokenism" },
            { text: "A focus group of participants is asked to describe their worst experiences with the program; they are thanked and never contacted again.", category: "Extraction" },
            { text: "The advisory panel receives a written response to each recommendation saying what was adopted, what was not, and why.", category: "Partnership" },
            { text: "An advisor’s photograph and a quotation appear on the report cover, but her main recommendation is not mentioned in the report.", category: "Tokenism" },
            { text: "Ideas from a community meeting appear in the strategic plan as the agency’s own, with no credit and no report back.", category: "Extraction" },
            { text: "A disability-led organization is contracted to co-facilitate the design sessions and paid at its professional rate.", category: "Partnership" },
            { text: "A single advisor is asked to speak for autistic people, wheelchair users and people who are Deaf at a board presentation.", category: "Tokenism" },
            { text: "Advisors are sent a finished draft on Thursday and asked to sign off by Friday.", category: "Extraction" },
            { text: "The charter names the decisions the panel influences and the ones it does not, and the panel agreed to both.", category: "Partnership" },
            { text: "A committee seat is reserved for “a person with a disability,” but the real decisions are made in a staff meeting the seat holder is not invited to.", category: "Tokenism" },
            { text: "A researcher records participants’ stories for a report and does not tell them how the stories will be used or who will see them.", category: "Extraction" },
          ] },
          { type: "quote", text: "I have been in seven focus groups for this agency. I can tell you what I said in each one. I cannot tell you a single thing that changed.", cite: "Composite advisor perspective, illustrative" },
          { type: "leaderMove", heading: "Never ask one person to be a community", control: "You control whether your program invites one disabled person to represent everyone, or several paid advisors with different lives and names the gaps that remain.", failure: "Do not put a single seat labeled “person with a disability” on a committee and call it inclusion. One person cannot carry that, and the decision usually happens somewhere else anyway.", next: "Count the disabled advisors in your current process. If the answer is one, or zero, or “our colleague who uses a wheelchair,” change the plan before the next meeting." },
          { type: "flashcards", heading: "Three patterns, three corrections", cards: [
            { front: "Tokenism", back: "<p>Presence without influence: one person for everyone, a seat away from the real decision, a photograph instead of a change. Correction: several paid advisors with scope, and honesty about who is missing.</p>" },
            { front: "Extraction", back: "<p>Taking stories, time and ideas without payment, consent, credit or report back. Correction: pay, ask consent for use, offer credit the person controls, and always report what happened.</p>" },
            { front: "Last-minute review", back: "<p>Approve what you could not shape, by Friday. Correction: bring people in while questions are open; when you truly need only a check, say so and pay for a review.</p>" },
            { front: "Consultation fatigue", back: "<p>The reasonable response of people consulted many times who saw nothing change. Overcome only by demonstrated follow-through, not by better invitations.</p>" },
          ] },
          { type: "knowledgeCheck", id: "co-design-and-lived-experience-3-check", question: "A manager asks a disabled colleague to “take a quick look” at a finished accessibility policy the day before it is published, unpaid and outside her job duties. Which description and correction are right?", options: [
            { text: "Reasonable collegial review; no change needed.", correct: false },
            { text: "Last-minute review layered on extraction. Next time, include paid advisors while the policy is being drafted, and if a final check is all that is needed, ask for it with time, as recognized work.", correct: true },
            { text: "Tokenism; the fix is to ask two colleagues instead of one.", correct: false },
          ], feedbackCorrect: "Yes. Timing makes it last-minute review, and unpaid work outside her duties makes it extraction. The fix is earlier involvement and treating review as real work.", feedbackIncorrect: "Look at when she was asked and what she was given for it. A finished policy the day before publication, unpaid, is last-minute review and extraction. Bring people in earlier and pay for review." },
        ],
      },
      {
        id: "co-design-and-lived-experience-4",
        number: 4,
        title: "The charter and the feedback loop",
        summary: "Write down how the partnership works before it starts, and build the loop that shows advisors what happened to their advice.",
        minutes: 12,
        learning: {
          objective: "Draft a paid advisory panel charter that defines purpose, decision authority, recruitment and representation, compensation, confidentiality, meeting access and how recommendations are communicated back, and design a feedback loop that visibly influences decisions.",
          takeaways: [
            "A charter is a set of promises the agency makes in writing before recruitment, so advisors can decide whether to join and hold the agency to them.",
            "Decision authority must be stated exactly: which decisions the panel influences, which it decides, which it does not touch, and who answers when a recommendation is not adopted.",
            "A feedback loop has a fixed cycle: recommendation recorded, decision made, reasons given in writing, change visible, and the record shared with the panel and, where appropriate, the public.",
          ],
          evidence: "A draft charter for one program with all seven sections; a knowledge check on responding to a rejected recommendation.",
          appliedNextStep: "Draft the charter for your program using the artifact, share it with two disabled advisors or a disability-led organization for paid review before you recruit, and revise it with them.",
        },
        scenario: {
          context: "Your program’s advisory panel recommended that the new intake form be available by phone with a staff member, not only online. Leadership decided not to fund phone intake this year, citing staffing. The panel meets again in two weeks and has not been told.",
          prompt: "What does an honest feedback loop require now?",
          options: [
            { label: "Leave it off the agenda; the decision is final and raising it will only frustrate people.", response: "Silence is how consultation fatigue is made. The panel gave advice in good faith and is entitled to know the decision and the reason, even when the answer is no." },
            { label: "Before the meeting, send the panel a written response: the recommendation as they made it, the decision, the reason, what will be done instead in the meantime, and when the question will be revisited; then put it on the agenda with the decision maker present.", response: "A no with reasons, an interim measure and a return date keeps the partnership honest and keeps the recommendation alive.", recommended: true },
            { label: "Tell the panel the recommendation is “still under consideration” to keep morale up.", response: "That is not true, and advisors will find out. The loop only works when the account of what happened is accurate." },
          ],
        },
        transfer: {
          prompt: "Which recommendation from disabled advisors is your program currently sitting on without a response?",
          options: ["Write the recommendation as the advisors made it", "Write the decision, the reason, the interim measure and the revisit date", "Send it, and put it on the next agenda with the decision maker present"],
        },
        blocks: [
          { type: "text", heading: "Promises in writing, kept in public", body: "<p>A charter is the difference between a panel that hopes to matter and one that knows exactly how it will. It is written before recruitment, because people deserve to know what they are joining, and it is written with disabled advisors or a disability-led organization, paid, because a charter drafted entirely by staff tends to protect staff. Seven sections do most of the work: purpose and scope; decision authority; recruitment and representation; compensation; confidentiality; meeting access; and how recommendations are communicated back. The artifact below gives each section a starting text.</p><p>The section that most often goes wrong is <strong>decision authority</strong>. Vague language such as “the panel will advise leadership” satisfies nobody. Say which decisions the panel influences, which it decides outright, which are out of scope and why, and who is obliged to respond when a recommendation is not adopted. Advisors can accept a narrow scope that is honest; they cannot accept a broad one that turns out to be empty.</p><p>The <strong>feedback loop</strong> is what makes influence visible. It runs on a fixed cycle. Every recommendation is recorded in the advisors’ own words with a date. Every recommendation receives a written decision within a stated period: adopted, adopted in part, deferred with a revisit date, or not adopted, with reasons. Where a recommendation is adopted, the change is shown, not just announced: the new form, the revised letter, the changed procedure. The record of recommendations and responses is shared with the panel and, where the topic is public, published, so the community can see the pattern. When the answer is no, the decision maker, not a staff liaison, explains it to the panel in person. A loop like this does not guarantee that every recommendation is adopted. It guarantees that none disappears, which is what advisors have most often experienced and most reasonably fear.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical artifact", title: "Paid advisory panel charter", summary: "Starting text for the seven sections. Adapt it with paid disabled advisors or a disability-led organization before recruiting, and keep the agreed version where the panel can see it.", fields: [
            { label: "Purpose and scope", value: "The panel exists to shape [the program or decision] so it works for disabled people who use it. It joins at the start, when questions are open, and stays through testing and the first revision. The program names the decisions in scope and the ones outside it, with reasons." },
            { label: "Decision authority", value: "The panel influences: requirements, design options, communication, testing criteria and evaluation. The panel decides: accessibility acceptance criteria and the format of its own meetings. Out of scope: [named decisions fixed by statute, budget or contract], stated plainly. Every recommendation receives a written decision from the responsible decision maker within [a stated number of] days, with reasons. When a recommendation is not adopted, the decision maker explains it to the panel in person." },
            { label: "Recruitment and representation", value: "Six to ten paid advisors recruited through disability-led organizations, program participants and open application, across a range of disability types, ages, races, languages, geography and experience with the program. No advisor is asked to represent all disabled people. The charter states whose perspectives are still missing and how the program will seek them." },
            { label: "Compensation", value: "A stated rate for meeting, preparation and review time, benchmarked to what the program pays other outside experts. Choice of payment form, chosen privately. Disclosure that payment may affect some benefits, with benefits planning resources named. Confirmed payment timeline and a named staff helper for paperwork. Access costs covered directly: transportation, interpreters, captioning, support persons, formats and care where policy allows." },
            { label: "Confidentiality", value: "What advisors share about their own lives stays in the room unless they choose otherwise. Advisors are told before any session how notes, recordings, stories and quotations will be used, who will see them, and how to withdraw consent. Program information shared with advisors in confidence is identified as such in advance. Advisors are never asked for benefits records or medical documentation." },
            { label: "Meeting access", value: "Meetings offered in person and remotely; step-free location near accessible transit; interpreters, captioning and quiet space arranged by default; materials in accessible formats at least three working days ahead; agendas with time for people who communicate at different speeds; a named contact for access needs; meeting length and timing set with advisors." },
            { label: "How recommendations are communicated back", value: "Each recommendation recorded in the advisors’ words with a date. A written response within the stated period: adopted, adopted in part, deferred with a revisit date, or not adopted with reasons. Adopted changes shown to the panel in their final form. A running log of recommendations and responses shared with the panel and published where the topic is public. An annual review of the charter with the panel, paid." },
          ], action: "Draft your program’s version, pay two disabled advisors or a disability-led organization to review it, and adopt it before you recruit the panel." },
          { type: "list", heading: "The feedback loop, in order", ordered: true, items: ["Record the recommendation in the advisors’ own words, with the date and who made it.", "Route it to the named decision maker with a response date the charter sets.", "Decide, and write the response: adopted, adopted in part, deferred with a revisit date, or not adopted with reasons.", "Send the response to the panel before the next meeting; the decision maker attends to explain any no.", "Show the change in its final form when a recommendation is adopted.", "Add the recommendation and response to the running log the panel can see, and publish it where the topic is public.", "At the annual review, look at the log together: what share was adopted, what patterns appear in the reasons for no, and what the charter should change."] },
          { type: "accordion", heading: "Writing the response to a recommendation", items: [
            { title: "Adopted", body: "<p>State the recommendation, say it is adopted, name what will change, who owns it and by when, and how the panel will see the result. Credit the panel in the change itself if the panel wants that.</p>" },
            { title: "Adopted in part", body: "<p>Say exactly which part is adopted and which is not, and give the reason for the part that is not. Partial adoption presented as full adoption is the fastest way to lose trust.</p>" },
            { title: "Deferred", body: "<p>Give the reason, the interim measure that reduces the harm in the meantime, the date it will be revisited and who will bring it back. A deferral without a date is a no.</p>" },
            { title: "Not adopted", body: "<p>Give the real reason, in plain language, from the decision maker. If the reason is money, say how much. If the reason is law or contract, name it. Say what the program will do instead and whether the panel can help change the constraint.</p>" },
          ] },
          { type: "leaderMove", heading: "Deliver the no yourself", control: "You control whether a decision not to adopt a recommendation reaches the panel from the person who made it, with reasons, or leaks out through silence.", failure: "Do not let a staff liaison carry bad news the decision maker would not say in person, and never report a recommendation as “under consideration” when it has been declined.", next: "Look at your program’s outstanding recommendations. Any older than the charter’s response period gets a written response this week, and any no gets you or the decision maker in the room to explain it." },
          { type: "flashcards", heading: "Charter and loop", cards: [
            { front: "Charter", back: "<p>Written promises made before recruitment, drafted with paid disabled advisors: purpose, decision authority, recruitment and representation, compensation, confidentiality, meeting access, and how recommendations come back.</p>" },
            { front: "Decision authority", back: "<p>Which decisions the panel influences, which it decides, which are out of scope and why, and who must respond to a recommendation. Narrow and honest beats broad and empty.</p>" },
            { front: "Written response", back: "<p>Adopted, adopted in part, deferred with a date, or not adopted with reasons, within the period the charter sets. A deferral without a date is a no.</p>" },
            { front: "Running log", back: "<p>Every recommendation and response, visible to the panel and published where the topic is public. Reviewed together each year to see the pattern.</p>" },
            { front: "Show the change", back: "<p>An adopted recommendation is demonstrated in its final form, not announced. Advisors see the form, the letter, the procedure that changed because of them.</p>" },
          ] },
          { type: "knowledgeCheck", id: "co-design-and-lived-experience-4-check", question: "A panel recommended extending appointment slots for people who use interpreters. The program cannot change slot lengths until the scheduling system is replaced next budget cycle. Which response keeps the feedback loop honest?", options: [
            { text: "Tell the panel the recommendation is under consideration.", correct: false },
            { text: "Respond in writing that the recommendation is deferred, give the reason, describe the interim measure such as booking two consecutive slots when an interpreter is scheduled, name the revisit date and the owner, and have the decision maker present at the next meeting.", correct: true },
            { text: "Remove the recommendation from the log since it cannot be done now.", correct: false },
          ], feedbackCorrect: "Yes. A deferral with a reason, an interim measure, a date and an owner keeps the recommendation alive and the record honest.", feedbackIncorrect: "A recommendation that cannot be adopted now is deferred with a reason, an interim measure, a revisit date and an owner, and stays in the log. It is not softened into “under consideration” or quietly removed." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Partnership, not performance",
    subtitle: "A one-page check before your program asks disabled people for their expertise",
    quote: "Bring people in while the questions are open. Pay them. Tell them what happened. Show them the change.",
    use: {
      purpose: "Check a planned engagement with disabled people or disability-led organizations before it starts, and keep the promises a partnership makes.",
      remember: ["Name the level truthfully: inform, consult, involve, collaborate, share authority. Timing decides whether it is real.", "Lived experience is expertise with a rate. Offer choices in payment, respect benefits decisions, cover access costs.", "One person is not a community. Several paid advisors, and honesty about who is missing.", "Every recommendation gets a written response with reasons, and adopted changes are shown, not announced."],
      doNext: "Draft the charter with paid disabled advisors before you recruit the panel.",
    },
    sections: [
      { heading: "Before you invite anyone", items: ["What can advisors still change at the point they join? If only the training, move the invitation earlier or call it informing.", "Is there a budget line for advisor compensation, set before recruitment and stated in the invitation?", "Has finance confirmed how advisors are paid, how long it takes, and who helps with paperwork?", "Are you recruiting several people across disabilities, races, languages and experience, through disability-led organizations?"] },
      { heading: "During the partnership", items: ["Meetings accessible by default: formats three working days ahead, interpreters and captioning arranged, time for different communication speeds.", "Consent asked before stories, notes or quotations are used; credit offered and controlled by the person.", "No one asked to represent everyone; no one asked for benefits or medical records.", "Recommendations recorded in advisors’ words with dates."] },
      { heading: "Closing the loop", items: ["Written response within the charter’s period: adopted, in part, deferred with a date, or not adopted with reasons.", "The decision maker delivers any no in person.", "Adopted changes shown in final form; the running log shared with the panel and published where public.", "Charter reviewed with the panel each year, paid."] },
    ],
  },
  sources: [
    { title: "U.S. Department of Labor, Office of Disability Employment Policy", href: "https://www.dol.gov/agencies/odep", note: "Federal policy office promoting disability inclusion in employment, including guidance that centers disabled people’s participation in policy and program design." },
    { title: "W3C Web Accessibility Initiative, Involving Users in Web Projects for Better, Easier Accessibility", href: "https://www.w3.org/WAI/planning/involving-users/", note: "Guidance on involving people with disabilities early and throughout design and evaluation, applicable beyond web projects." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "State council on disability policy and access, and a starting point for identifying Minnesota disability organizations and advisory practices." },
    { title: "Minnesota Department of Human Services, Olmstead Plan", href: "https://mn.gov/dhs/general-public/about-dhs/olmstead/", note: "Minnesota’s commitments to integration and person-centered practice, which depend on the participation of people with disabilities in planning." },
    { title: "Centers for Disease Control and Prevention, Disability Inclusion", href: "https://www.cdc.gov/disability-inclusion/about/index.html", note: "Public health framing of disability inclusion as participation supported by policies and practices, including involving disabled people in program design." },
    { title: "ADA National Network", href: "https://adata.org/", note: "ADA information and training resources, including material on effective communication and accessible meetings that advisory panels rely on." },
  ],
};

export default pack;
