import type { CoursePack } from "../../source-types";

// Disability Inclusion curriculum, Level 2 module 6: Inclusive Meetings, Events and Learning.
// Program-authored for supervisors, program staff, direct-support professionals, care coordinators and intake teams.
const pack: CoursePack = {
  course: {
    id: "di-inclusive-meetings-events-learning",
    indexNumber: 1111,
    seriesLabel: "Disability Inclusion · Applied inclusion",
    title: "Inclusive Meetings, Events and Learning",
    subtitle: "Plan in-person, hybrid and virtual gatherings that people can actually attend, follow and shape, and recover well when something fails on the day.",
    scope: "For supervisors, program staff, direct-support professionals, care coordinators, intake teams and anyone who convenes a meeting, event, training or community session. Five short lessons with a planning checklist, format-specific practice and a plan for last-minute access problems. Participation in this program is voluntary and does not replace required training.",
    treatment: "Five short lessons with scenarios, a planning checklist, a sorting exercise, flashcards and knowledge checks",
    duration: "48–54 minutes",
    author: "One DHS — People, Access and Culture",
    coverImage: "/images/covers/facilitators-guide.jpg",
    coverAlt: "A man facilitates a small training room at a whiteboard.",
    introTranscript: "Most of the access failures at a meeting were decided weeks earlier, when the invitation went out without a question about access, the room was booked without checking the route, or the platform was chosen without turning on captions. This course moves the work to where it belongs: before the invitation. You will plan in-person, hybrid and virtual gatherings with a checklist, make materials and participation methods accessible, and handle the interpreter who does not arrive or the captions that fail without making the person with the access need carry the problem.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Use an accessibility planning checklist before an invitation is sent, and explain why each item belongs before the invitation rather than after.",
        "Plan an in-person gathering with accessible routes, seating, restrooms, transportation, emergency procedures and sensory considerations.",
        "Configure and run a hybrid or virtual session so that captions, interpretation, chat, polls, shared documents and breakout rooms work for everyone.",
        "Prepare materials in advance in accessible formats, offer more than one way to participate, and make follow-up usable.",
        "Respond to a last-minute access failure in a way that keeps the person included, decides with them how to proceed and fixes the process afterward.",
      ],
      evidence: [
        "Five scenario decisions and five knowledge checks with explanations.",
        "A completed sort of planning items into the stage where they belong.",
        "One real upcoming meeting, event or training planned against the checklist, with the changes you made recorded.",
      ],
      appliedNextStep: "Take the next meeting, event or training you convene through the checklist in lesson one before the invitation goes out. Keep the changes in your team’s template so they happen by default.",
    },
    governance: {
      contentOwner: "One DHS — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: ["Change in ADA, Section 504 or Section 508 guidance", "Change in DHS accessibility or language access standards", "Feedback from disabled staff or participants that a scenario reads as unrealistic or stigmatizing"],
      relatedDoor: "Interpreter and captioning requests, facility access questions and digital accessibility standards each have a responsible office, including the accessibility team, language access and facilities; this course prepares you to plan, it does not replace those services.",
      toolkitQuestion: "Who could not attend, follow or shape this gathering as it is currently planned, and what will change before the invitation goes out?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "inclusive-meetings-events-learning-1",
        number: 1,
        title: "Plan access before the invitation",
        summary: "Move accessibility from a late request to the first planning step, using a checklist that decides the room, the platform and the invitation together.",
        minutes: 11,
        learning: {
          objective: "Apply an accessibility planning checklist to an upcoming gathering and identify which decisions must be made before the invitation is written.",
          takeaways: [
            "The invitation is the last step of planning, not the first; the room, the platform, the materials and the interpreter timeline are decided before it.",
            "Ask about access needs in registration, with a named contact and a real date, and plan for common needs whether or not anyone asks.",
            "Interpreters and captioners are booked people, not settings; lead times of one to two weeks are ordinary.",
          ],
          evidence: "A completed sort of checklist items into planning stages and a knowledge check.",
          appliedNextStep: "Run your next gathering through the checklist and record which items were already habits and which were new.",
        },
        scenario: {
          context: "A program supervisor is asked to convene a half-day, in-person and virtual session with the people and organizations affected on a waiver service change in three weeks. She has a room held, a platform link, and a draft invitation ready to send today.",
          prompt: "What should she do first?",
          options: [
            { label: "Send the invitation now so people can hold the date, and sort out access once registrations come in.", response: "Once the invitation is out, the room, the date and the platform are fixed, and every access need becomes a retrofit. Three weeks is enough time to plan properly if the planning starts now." },
            { label: "Run the checklist first: confirm the room’s route and restrooms, turn on the platform’s captions, request interpreters and captioning now, add an access question and a named contact to registration, and set the materials deadline. Then send the invitation.", response: "An hour of planning today prevents a week of scrambling later and produces an invitation people can actually accept.", recommended: true },
            { label: "Add “accommodations available on request” to the invitation and send it.", response: "The line puts the burden on the person to ask, and the room and platform are still unchecked. It is better than silence and far short of planning." },
          ],
        },
        transfer: {
          prompt: "Which checklist item does your team most often leave until after the invitation, and what does that cost?",
          options: ["Move the access question and named contact into your registration template today", "Find out your interpreter and captioning request process and its lead time", "Put the checklist at the top of your team’s meeting planning template"],
        },
        blocks: [
          { type: "text", heading: "The invitation is the last step", body: "<p>Level 1 introduced the four lines of an accessible invitation. This course is about everything those four lines depend on. Captions are on only if the platform was chosen and configured. A step-free route is offered only if someone walked it. Interpreters are available only if they were requested with enough lead time. Materials arrive three working days ahead only if the deadline was set backward from the date. By the time you write the invitation, those decisions have already been made or missed.</p><p>Planning access first also changes what you ask people to disclose. When the room, the route, the captions and the accessible materials are already in place, the registration question can be brief and welcoming: “Tell us what you need to take part fully, and we will arrange it.” People are more willing to answer when the answer will clearly be acted on, and many common needs are met before anyone has to ask.</p><p>Lead time is the part people underestimate. Sign language interpreters and real-time captioners are skilled professionals with schedules. A week is a short notice; two is ordinary; for a large or specialized event, longer. Your organization has a process for requesting them, usually through the accessibility or language access team. Find it before you need it.</p>" },
          { type: "list", heading: "Planning in order", ordered: true, items: ["Decide purpose, format (in-person, hybrid or virtual) and length, including breaks.", "Choose and check the room or platform against the access criteria in lessons two and three.", "Request interpreters and captioning through the responsible office, with the date, length, format and subject.", "Set the materials deadline backward from the date so accessible versions can be prepared and sent ahead.", "Write registration with an access question, a named contact, and the date by which requests are needed.", "Write the invitation with route, platform, captions, interpretation, materials and contact lines.", "Assign roles for the day: host, chat and captions monitor, room and route contact, note taker.", "Plan follow-up: accessible notes, recording with captions and transcript, decisions and next steps."] },
          { type: "artifact", kind: "invitation", label: "Practical artifact", title: "Accessible meeting planning checklist", summary: "Work through every line before the invitation goes out, whatever the format. Each line has an owner.", fields: [
            { label: "Before invitations go out", value: "Format decided; room or platform checked; interpreters and captioning requested with lead time; materials deadline set; roles for the day assigned; access question, named contact and request date written into registration." },
            { label: "Registration and materials", value: "Registration works with a keyboard and a screen reader; the access question is open and welcoming; agenda, slides and pre-reading go out at least three working days ahead as accessible documents; alternative formats and languages are ready on request." },
            { label: "Room, route and platform", value: "In person: step-free route from transit and accessible parking to the seat, accessible restrooms on the same floor, seating that people can choose, microphones for every speaker, a quiet room, lighting and noise checked, emergency procedures that work for everyone. Virtual and hybrid: captions on by default, interpreter view that can be pinned, chat and polls with an accessible alternative, shared documents accessible, camera optional." },
            { label: "During and after", value: "Breaks built into the agenda; more than one way to contribute; facilitators name themselves and describe visuals; someone monitors chat and captions; follow-up includes accessible notes, a captioned recording with transcript, and decisions in plain language." },
          ], action: "Copy this into your team’s planning template and assign an owner to each line for your next meeting, event or training." },
          { type: "sorting", id: "inclusive-meetings-events-learning-1-sort", heading: "Which planning stage does each item belong to?", categories: ["Before the invitation", "Registration and materials", "On the day", "Follow-up"], items: [
            { text: "Request sign language interpreters through the language access process.", category: "Before the invitation" },
            { text: "Send the slides as an accessible document three working days ahead.", category: "Registration and materials" },
            { text: "Assign a colleague to read chat questions aloud and watch the captions.", category: "On the day" },
            { text: "Post the captioned recording with a transcript and the decisions made.", category: "Follow-up" },
            { text: "Walk the route from the accessible parking to the room.", category: "Before the invitation" },
            { text: "Include an open access question and a named contact in the sign-up form.", category: "Registration and materials" },
          ] },
          { type: "leaderMove", heading: "Hold the invitation until the checklist is done", control: "You control whether the invitation goes out as a placeholder that fixes every later decision, or as the last step of a plan that already works.", failure: "Do not send a save-the-date with a room and a platform you have not checked. Do not treat “accommodations available on request” as planning.", next: "For your next gathering, complete the checklist before you write a word of the invitation, and note how long it actually took." },
          { type: "flashcards", heading: "Planning terms", cards: [
            { front: "Lead time", back: "<p>The notice interpreters, captioners and accessible-format producers need. One to two weeks is ordinary; more for large or specialized events. Request early through the responsible office.</p>" },
            { front: "The access question", back: "<p>An open, welcoming line in registration: “Tell us what you need to take part fully.” Paired with a named contact and a date, and asked after the basics are already planned.</p>" },
            { front: "Three working days", back: "<p>A practical minimum for sending materials ahead. Screen-reader users, people who use interpreters, and people who process written information slowly all need time with the content before the room.</p>" },
            { front: "Roles for the day", back: "<p>Host, chat and captions monitor, room and route contact, note taker. A facilitator cannot do all four and facilitate.</p>" },
            { front: "Default, not exception", back: "<p>Captions on, accessible documents, a quiet room and a step-free route are planned every time, whether or not anyone has asked. Requests then cover what is individual.</p>" },
          ] },
          { type: "knowledgeCheck", id: "inclusive-meetings-events-learning-1-check", question: "Which of these must happen before the invitation is sent?", options: [
            { text: "Reading the chat questions aloud so remote and in-room participants hear them.", correct: false },
            { text: "Checking the room’s route and restrooms, configuring the platform’s captions, and requesting interpreters with lead time.", correct: true },
            { text: "Posting the captioned recording and the decisions made.", correct: false },
          ], feedbackCorrect: "Yes. Room, platform and interpreter decisions are fixed by the invitation, so they have to be made first.", feedbackIncorrect: "Two of these belong on the day or afterward. The decisions that the invitation locks in are the ones that must come before it." },
        ],
      },
      {
        id: "inclusive-meetings-events-learning-2",
        number: 2,
        title: "In person: the route, the room and the day",
        summary: "Check the path from the street to the seat, the seating, the restrooms, the sound, the light, the food and the emergency plan, so the room itself does not exclude anyone.",
        minutes: 11,
        learning: {
          objective: "Evaluate an in-person venue against at least eight access criteria and name the corrective action or alternative for each failure.",
          takeaways: [
            "Walk the route yourself, from accessible parking and the nearest transit stop to the seat, the restroom and the exit; a floor plan does not tell you about the heavy door or the step at the threshold.",
            "Microphones are for the listeners, not the speaker; use them every time, for every voice, including questions.",
            "An emergency plan that assumes everyone can hear an alarm and take the stairs is not a plan.",
          ],
          evidence: "A scenario decision, a knowledge check and a venue walkthrough for one real event with failures and fixes listed.",
          appliedNextStep: "Walk your most-used meeting room from the street to the seat and write down every point where a person could be stopped.",
        },
        scenario: {
          context: "A community meeting about a new county service is planned for a church hall a colleague recommends because it is free and central. The photos show a bright room with round tables. The colleague has not visited.",
          prompt: "What do you need to know before you confirm the hall?",
          options: [
            { label: "Whether it is available on the date and how many it seats.", response: "Necessary, but it tells you nothing about whether people can get in, move around, use a restroom or leave safely." },
            { label: "Walk it: the route from parking and transit, the entrance, door weight and thresholds, the restroom, aisle widths between the round tables, lighting, sound, a quiet space, and what happens in an alarm. Then decide.", response: "A free, central hall that some people cannot enter is not free for them. The walkthrough decides whether the room works or whether you need another one.", recommended: true },
            { label: "Ask the church whether the hall is accessible.", response: "“Accessible” means different things to different people. A yes from the venue is a starting point; the walkthrough is the evidence." },
          ],
        },
        transfer: {
          prompt: "Which of your regular venues have you never actually walked as a person with an access need?",
          options: ["Walk one venue this month from the street to the seat and back out in an alarm", "Add microphone use for every speaker to your facilitation norms", "Find out who owns the emergency plan for your most-used room and whether it names disabled attendees"],
        },
        blocks: [
          { type: "text", heading: "From the street to the seat", body: "<p>A room is accessible only if a person can get to it. Start where people start: at the accessible parking space, the paratransit drop-off and the nearest transit stop. Follow the route to the entrance. Is it step-free the whole way, including the curb, the threshold and any interior level change? Does the door open with light force or a button? Is the route signed? Inside, is there an accessible restroom on the same floor, and is the path to it clear? Can a person using a wheelchair or a walker reach a seat of their choosing, not just one spot by the door, and get to the front to speak? These questions cannot be answered from a photograph or a venue’s assurance. Walk them.</p><p>Then consider the room as a sensory environment. Fluorescent flicker, echo, a loud ventilation unit, strong smells from a kitchen, and a crowded layout make a room hard for many people, including people with brain injuries, autistic people, people with migraine and people with anxiety. A quiet room nearby, where a person can step out and still hear the session, is inexpensive and often decisive. Seating people can choose, including near the front for lip reading and near the door for leaving briefly, matters more than round tables.</p><p>Sound is the most common failure. A speaker who says “I will just project” is choosing to exclude hard-of-hearing people, people at the back, and everyone relying on captions or an interpreter who cannot hear the question. Use a microphone for every voice, pass it for every question, and repeat anything said without it. If the room has a hearing loop or assistive listening system, learn how it works before the day.</p>" },
          { type: "accordion", heading: "The venue walkthrough", items: [
            { title: "Arrival and route", body: "<p>Accessible parking close to a step-free entrance; a safe paratransit drop-off; a transit stop within a reasonable, step-free distance; clear signage; doors that open easily; no thresholds, steps or steep ramps on the route.</p>" },
            { title: "Room layout and seating", body: "<p>Aisles wide enough for wheelchairs and walkers; seating people can choose, including integrated wheelchair spaces beside companions; a clear path to the front; a table height a wheelchair user can use; space for a service animal beside its handler.</p>" },
            { title: "Restrooms and quiet space", body: "<p>An accessible restroom on the same floor with a clear path; an all-gender option where possible; a quiet room nearby with the session audio available; a place for a service animal to relieve itself.</p>" },
            { title: "Sound, light and sensory load", body: "<p>Microphones for every speaker and a plan to pass them; an assistive listening system where available; lighting that does not flicker and can be adjusted; noise from ventilation, kitchens and corridors checked; no strong fragrances.</p>" },
            { title: "Food and breaks", body: "<p>Breaks at least every ninety minutes; food that people can serve themselves from a reachable height or that is served on request; ingredients labeled; straws and adaptive options available.</p>" },
            { title: "Emergency procedures", body: "<p>A visual as well as audible alarm; a step-free evacuation route or an area of refuge with a communication link; staff who know how to assist, and a plan agreed in advance with anyone who has told you they will need help to evacuate.</p>" },
          ] },
          { type: "leaderMove", heading: "Pass the microphone every time", control: "You control whether every voice in the room, including every question, reaches the people relying on hearing aids, captions, an interpreter or the back row.", failure: "Do not accept “I will just speak up.” Do not let a question be answered before it has been repeated into the microphone.", next: "At your next in-person session, appoint someone to carry the microphone to questioners, and repeat the first question yourself to set the norm." },
          { type: "flashcards", heading: "Details that decide the day", cards: [
            { front: "Door force and thresholds", back: "<p>A heavy door or a two-inch lip stops a wheelchair user as surely as a staircase. Check both on the actual route, not on the plan.</p>" },
            { front: "Integrated seating", back: "<p>Wheelchair spaces beside ordinary seats, so a person sits with the people they came with, in the part of the room they choose.</p>" },
            { front: "Assistive listening", back: "<p>A hearing loop or a system with receivers sends the microphone signal directly to hearing aids or headsets. Ask the venue, test it, and tell people it exists.</p>" },
            { front: "The quiet room", back: "<p>A nearby space with lower light and noise where a person can step out and still follow the session. It should never feel like being sent out.</p>" },
            { front: "Area of refuge", back: "<p>A fire-protected space with a way to communicate, for people who cannot use stairs in an evacuation. Know where it is and who checks it.</p>" },
          ] },
          { type: "statement", body: "A free, central, beautiful room that some people cannot enter, hear in or leave safely is not a venue. It is a barrier with good lighting. Walk it before you book it." },
          { type: "knowledgeCheck", id: "inclusive-meetings-events-learning-2-check", question: "A venue says it is accessible. What is the strongest evidence that it is?", options: [
            { text: "The venue’s website lists an accessibility statement.", correct: false },
            { text: "You have walked the route from accessible parking and transit to a seat, the restroom and the emergency exit, and each is step-free, reachable and usable.", correct: true },
            { text: "A colleague used the venue last year without hearing any complaints.", correct: false },
          ], feedbackCorrect: "Yes. The walkthrough is the evidence. A statement and an absence of complaints are not.", feedbackIncorrect: "People who expect barriers often do not attend, so silence proves nothing, and a statement is a claim. Walk the route yourself." },
        ],
      },
      {
        id: "inclusive-meetings-events-learning-3",
        number: 3,
        title: "Hybrid and virtual: platforms, captions, chat and polls",
        summary: "Configure the platform, run interpretation and captions properly, make chat, polls, shared documents and breakout rooms usable, and keep remote participants equal in a hybrid room.",
        minutes: 12,
        learning: {
          objective: "Configure a virtual or hybrid session so that captions, interpretation, chat, polls, shared documents and breakout rooms are accessible, and describe the facilitation habits that keep remote participants equal.",
          takeaways: [
            "Automatic captions are a floor, not a ceiling; when accuracy matters or someone has asked, book a live captioner and check the platform supports it.",
            "An interpreter must be visible to the people who need them the whole time, including during screen sharing and in breakout rooms.",
            "In a hybrid room, remote participants lose first: give them a dedicated host, a microphone for every in-room voice, and the same materials at the same moment.",
          ],
          evidence: "A scenario decision, a knowledge check and a platform settings check for your next virtual or hybrid session.",
          appliedNextStep: "Open your platform’s settings before your next virtual session and confirm captions, interpreter view, chat accessibility, and how polls and shared documents will be offered to people who cannot use them.",
        },
        scenario: {
          context: "A hybrid team training is under way. Eight people are in a conference room with one laptop; six are remote, including a staff member who uses an ASL interpreter joined remotely and a staff member who relies on captions. The in-room group talks among themselves without the microphone, the facilitator shares slides that hide the interpreter, and a poll is launched that one remote participant cannot complete with a screen reader.",
          prompt: "What should the facilitator do now?",
          options: [
            { label: "Continue; the recording will be shared afterward and remote participants can catch up.", response: "A recording of a session in which the interpreter was hidden and the poll was inaccessible reproduces every barrier. The remote participants are being excluded now." },
            { label: "Pause, move the in-room microphone into use for every speaker, pin the interpreter so they stay visible during screen sharing, and take the poll again by voice and chat with an accessible alternative. Assign a colleague to host the remote side.", response: "Three fixes in two minutes restore equal participation. The remote host prevents the next slide from causing the same problem.", recommended: true },
            { label: "Ask the remote staff members to say if they are having trouble following.", response: "They are already having trouble, and the question asks them to interrupt a training to explain what the facilitator should have set up. Fix the setup." },
          ],
        },
        transfer: {
          prompt: "What does a remote participant in your hybrid meetings experience that the in-room group does not notice?",
          options: ["Join your own next hybrid meeting remotely for ten minutes and note what you cannot hear or see", "Assign a remote host for every hybrid meeting your team runs", "Turn captions on by default in your platform settings today"],
        },
        blocks: [
          { type: "text", heading: "The platform is the room", body: "<p>Virtual and hybrid sessions have the same access requirements as a room, delivered through settings and habits. Captions come first. Most platforms offer automatic captions; turn them on by default so no one has to ask. Automatic captions make errors with names, technical terms and accents, and they are not a substitute when someone has requested captioning or when accuracy matters, such as a training, a decision meeting or a public session. For those, request a live captioner through the responsible office and confirm your platform can display their text.</p><p>Interpretation needs the interpreter to be visible at all times to the people who use them. Learn how your platform lets participants pin or spotlight a video, and how interpreter video behaves when someone shares a screen or when breakout rooms open. Plan for two interpreters for sessions longer than about an hour, since they work in turns. Tell the interpreter the agenda, the names and the vocabulary ahead of time, and send them the materials.</p><p>Chat, polls, reactions and shared documents are where access quietly fails. Chat moves fast and is hard for screen-reader users and people who process text slowly; have someone read questions aloud and summarize decisions verbally. Polls and whiteboards are often not usable with a keyboard or a screen reader; offer a voice or chat alternative every time and treat the poll as a convenience. Shared documents must be accessible documents, sent ahead rather than only shown on screen, and anything shown on screen should be described aloud.</p>" },
          { type: "tabs", heading: "Format by format", tabs: [
            { label: "Virtual", body: "<p>Captions on by default; live captioning when requested or when accuracy matters. Interpreter pinned and visible during screen share and breakouts. Camera optional, stated aloud. Chat read aloud by a monitor. Polls with a voice or chat alternative. Materials sent ahead as accessible documents. Recording with captions and a transcript afterward. Breaks every hour.</p>" },
            { label: "Hybrid", body: "<p>Everything in Virtual, plus: a dedicated remote host whose only job is the remote side; a microphone for every in-room voice, passed for every question; a camera that shows the room, not the back of heads; the same materials at the same moment for both groups; remote participants called on first for questions; no in-room side conversations. If the room cannot deliver this, run the session fully virtual instead.</p>" },
            { label: "In the room, when hybrid", body: "<p>In-room participants follow the microphone rule without exception, keep the shared screen identical to what remote participants see, and avoid pointing at things remote people cannot see. Someone in the room watches the remote host’s signals for a remote question.</p>" },
            { label: "Learning sessions", body: "<p>Interactive activities must have a version that does not require a mouse, drag-and-drop, color alone or speed. Reading aloud is optional, never assigned. Timed quizzes are extended or untimed. Breakout groups are assigned deliberately so an interpreter or captioner follows the person who needs them.</p>" },
          ] },
          { type: "leaderMove", heading: "Give the remote side a host", control: "You control whether a hybrid session has one person whose whole job is the experience of the people who are not in the room.", failure: "Do not run a hybrid session from one laptop on a conference table with the facilitator also watching chat. Do not let a poll or whiteboard be the only way to contribute.", next: "For your next hybrid meeting, name the remote host in the invitation, and give them authority to pause the room." },
          { type: "quote", text: "Hybrid usually means the room has a meeting and I watch it. The one time it worked, someone in the room was on my side, and the facilitator asked us first.", cite: "Composite staff perspective, illustrative" },
          { type: "flashcards", heading: "Settings and habits", cards: [
            { front: "Automatic versus live captions", back: "<p>Automatic captions are a default floor. A live captioner is needed when someone has requested captioning, when the vocabulary is specialized, or when the record matters.</p>" },
            { front: "Pin or spotlight", back: "<p>The platform feature that keeps an interpreter visible. Learn it, test it during screen share and in breakouts, and tell participants how to use it.</p>" },
            { front: "Chat monitor", back: "<p>A named person who reads questions aloud, summarizes chat decisions verbally and posts spoken decisions in chat, so both channels carry the same content.</p>" },
            { front: "Accessible alternative", back: "<p>Every poll, whiteboard, reaction or breakout activity has a voice or chat way to take part, offered every time without anyone asking.</p>" },
            { front: "Describe what is on screen", back: "<p>“The slide shows three columns: barrier, owner, fix.” Say it for the people who cannot see it, and send the slides ahead so they already have it.</p>" },
            { front: "Camera optional", back: "<p>Say it aloud at the start. Camera requirements exclude people with sensory, bandwidth, home, health and privacy reasons that are none of the meeting’s business.</p>" },
          ] },
          { type: "knowledgeCheck", id: "inclusive-meetings-events-learning-3-check", question: "A staff member has requested captioning for a two-hour virtual policy training with many program-specific terms. Which plan meets the request?", options: [
            { text: "Turn on the platform’s automatic captions.", correct: false },
            { text: "Request a live captioner through the responsible office, confirm the platform displays their text, send them the materials and terms ahead, and keep automatic captions on as a backup.", correct: true },
            { text: "Record the session and send the transcript afterward.", correct: false },
          ], feedbackCorrect: "Yes. A specific request for captioning in a long, term-heavy session calls for a live captioner, with automatic captions as a backup only.", feedbackIncorrect: "Automatic captions will misrender the terms, and a transcript afterward is not participation. The request was for captioning during the session." },
        ],
      },
      {
        id: "inclusive-meetings-events-learning-4",
        number: 4,
        title: "Materials, participation and follow-up",
        summary: "Send materials people can use before the session, offer more than one way to contribute during it, and make what comes afterward as accessible as what came before.",
        minutes: 10,
        learning: {
          objective: "Prepare accessible advance materials, plan at least three participation methods, and produce follow-up that a person who could not attend or could not follow live can still use.",
          takeaways: [
            "Materials sent ahead as accessible documents are how screen-reader users, interpreter users and slow processors arrive prepared; a slide shown once on screen is not a material.",
            "Participation methods should include speaking, writing during, writing afterward and anonymous input, so that no one method decides who is heard.",
            "Follow-up is part of the meeting: accessible notes, a captioned recording with a transcript, and decisions in plain language with owners.",
          ],
          evidence: "A scenario decision, a knowledge check and a review of one recent meeting’s materials and follow-up against the checklist.",
          appliedNextStep: "Take the materials and notes from your last meeting and check each item: real text, headings, alt text, descriptive links, sent ahead, decisions and owners clear.",
        },
        scenario: {
          context: "A care coordination team holds a monthly case-planning meeting. The lead shares slides on screen only, discussion is fast and verbal, decisions are captured in the lead’s personal notes, and a team member with a processing disability has told her supervisor she leaves each meeting unsure what was decided or what she is expected to do.",
          prompt: "What should change?",
          options: [
            { label: "Ask the team member to stay after each meeting so the lead can recap for her.", response: "This makes her responsible for an inaccessible meeting and adds a private, unpaid recap to her week. The meeting should work for her in the first place." },
            { label: "Send the agenda and slides ahead as accessible documents, use a visible shared notes document during the meeting, slow the pace at decision points, and send plain-language decisions with owners and dates afterward.", response: "Every change here helps the whole team, and the team member no longer has to ask. This is design, not accommodation.", recommended: true },
            { label: "Record the meeting so anyone can replay it.", response: "A replay of a fast, verbal meeting with screen-only slides has the same barriers, and it doubles the time cost for the person it is meant to help." },
          ],
        },
        transfer: {
          prompt: "How would a person who could not attend your last meeting, or could not follow it live, find out what was decided?",
          options: ["Add a shared, visible notes document to your recurring meetings", "Send plain-language decisions with owners and dates within two working days", "Offer written input before and after every meeting, and read it into the record"],
        },
        blocks: [
          { type: "text", heading: "Before, during, after", body: "<p><strong>Before.</strong> Send the agenda, slides and any pre-reading at least three working days ahead as accessible documents: real text rather than images, real headings, alt text on meaningful images, descriptive link text, sufficient contrast, and tables that read in order. State what decisions will be made so people can prepare. Offer alternative formats and languages through the named contact. If a document cannot be made accessible in time, say so and provide the substance another way rather than sending it anyway.</p><p><strong>During.</strong> Open by naming yourself and describing who is present; ask speakers to say their names before speaking, which helps blind participants, interpreters, captioners and the transcript. Describe visuals aloud. Keep a shared notes document visible so that decisions are captured in words everyone can see and correct. Offer more than one way to contribute: speaking, writing in chat or on cards, sending input after the meeting, and an anonymous option for sensitive topics. Slow down at decision points and restate the decision before moving on. Build breaks in, and keep them.</p><p><strong>After.</strong> Send notes as an accessible document within a couple of working days, with decisions, owners and dates in plain language at the top. If the session was recorded, post it with accurate captions and a transcript, not with automatic captions left uncorrected. Read late written input into the record and tell the sender what happened to it. For learning sessions, provide the content in a form that can be revisited: the slides, the transcript, the job aid.</p>" },
          { type: "list", heading: "Accessible materials, the short check", items: ["Real text: select it, search it, have it read aloud. A scanned image or a picture of a table fails.", "Headings that are actual headings, so a screen-reader user can move through the document.", "Alt text on images that carry meaning; decorative images marked as such.", "Link text that says where it goes, not “click here.”", "Contrast strong enough to read in a bright room and on a dim screen; color never the only signal.", "Tables with header rows, reading in a sensible order; no merged cells for layout.", "Sent ahead, as attachments or links people can open without a special account, with formats and languages offered."] },
          { type: "accordion", heading: "More than one way to be heard", items: [
            { title: "Speaking", body: "<p>With a microphone, called on by name, with time to finish. Do not go around the room forcing everyone to speak; invite instead.</p>" },
            { title: "Writing during", body: "<p>Chat, cards, a shared document. A monitor reads written contributions aloud so they count as much as spoken ones.</p>" },
            { title: "Writing before or after", body: "<p>Input sent to the named contact before the meeting or within a set period after. Read into the record and answered.</p>" },
            { title: "Anonymous input", body: "<p>A form or box for sensitive topics, especially where power differences are in the room. Report back what was received and what changed.</p>" },
            { title: "Through a supporter", body: "<p>A person may contribute through an interpreter, a communication device, a support person or an advocate. Address the person, and give the extra seconds it takes.</p>" },
          ] },
          { type: "leaderMove", heading: "Restate the decision before you move on", control: "You control whether a decision is made in a fast verbal exchange that half the room follows, or stated plainly, written where everyone can see it, and confirmed.", failure: "Do not let “so we are agreed” stand in for a decision. Do not capture decisions in a personal notebook that no one else can see.", next: "At your next meeting, keep a shared notes document visible and read each decision aloud from it before moving to the next item." },
          { type: "flashcards", heading: "Small habits with large effects", cards: [
            { front: "Say your name before you speak", back: "<p>Helps blind participants, interpreters, captioners and the transcript. Costs one second.</p>" },
            { front: "Describe the visual", back: "<p>“This chart shows requests rising in the spring and falling in the fall.” Say what the picture says.</p>" },
            { front: "Invite, do not go around", back: "<p>Forcing everyone to speak in turn punishes people with speech, anxiety or processing differences. Invite, and offer written routes.</p>" },
            { front: "Decisions at the top", back: "<p>Notes open with decisions, owners and dates in plain language. The discussion follows for those who want it.</p>" },
            { front: "Corrected captions", back: "<p>A recording posted with uncorrected automatic captions is not accessible. Fix names, terms and errors, and add a transcript.</p>" },
          ] },
          { type: "knowledgeCheck", id: "inclusive-meetings-events-learning-4-check", question: "Which follow-up makes a meeting usable for someone who could not follow it live?", options: [
            { text: "The recording, posted the same day with automatic captions.", correct: false },
            { text: "Accessible notes with decisions, owners and dates at the top in plain language, plus a recording with corrected captions and a transcript.", correct: true },
            { text: "An email saying that anyone with questions can contact the lead.", correct: false },
          ], feedbackCorrect: "Yes. The decisions are findable and usable, and the recording is actually accessible.", feedbackIncorrect: "Uncorrected automatic captions and an invitation to ask both leave the work with the person. Notes with decisions and a corrected transcript do the work for them." },
        ],
      },
      {
        id: "inclusive-meetings-events-learning-5",
        number: 5,
        title: "When access fails on the day",
        summary: "Handle the interpreter who does not arrive, the captions that stop, the room that changed or the elevator that is out, without making the person with the access need carry the problem.",
        minutes: 10,
        learning: {
          objective: "Respond to a last-minute access failure by naming it, offering real options, deciding with the affected person how to proceed, and fixing the process afterward.",
          takeaways: [
            "The person with the access need decides, with you, whether the session proceeds, pauses or is rescheduled; the group’s convenience does not override their participation.",
            "Have a backup for each critical access element before the day: a second interpreter agency contact, automatic captions as a fallback, a second room, a virtual link.",
            "Every failure gets a short written record and one process change, so the same failure does not happen twice.",
          ],
          evidence: "A scenario decision, a knowledge check and a written backup plan for your next gathering’s critical access elements.",
          appliedNextStep: "For your next gathering, write down the backup for each critical access element and who activates it.",
        },
        scenario: {
          context: "Ten minutes before a public listening session on service changes, the ASL interpreters have not arrived and are not answering. Two Deaf community members are seated at the front. Forty other people are in the room, and a director is ready to begin.",
          prompt: "What should the organizer do?",
          options: [
            { label: "Start on time and ask the Deaf attendees to follow along with the printed slides until the interpreters arrive.", response: "Printed slides are not interpretation, and starting excludes the two people who came specifically to be heard. The forty can wait ten minutes; the two cannot get the session back." },
            { label: "Go to the two attendees first, tell them plainly what has happened and what options exist, call the agency’s emergency line and the backup contact, and decide with them whether to delay, run a short accessible portion, or reschedule their part with a commitment.", response: "Transparency to the people affected, real options, and a decision made with them. Afterward, the process gets a backup and a confirmation step.", recommended: true },
            { label: "Ask whether anyone in the audience knows sign language and could help.", response: "An untrained volunteer is not an interpreter, and asking the room turns a professional access failure into a public spectacle around the two attendees." },
          ],
        },
        transfer: {
          prompt: "What is your backup for the one access element that, if it failed, would exclude someone from your next gathering?",
          options: ["Write the backup and the person who activates it into your planning notes", "Confirm interpreters and captioners the working day before, and again the morning of, with a direct number", "After any failure, write three lines: what failed, what you did, what changes"],
        },
        blocks: [
          { type: "text", heading: "Failures happen; exclusion is a choice", body: "<p>Even well-planned gatherings have failures: an interpreter is ill, the captioning link breaks, the room is reassigned to one with steps, the elevator is out of service, the accessible document was overwritten by an image version. What distinguishes an inclusive organization is not that these never happen but what happens next. The decisive question is who carries the problem. If the person with the access need is left to sit through a session they cannot follow, or asked to make do, or asked to explain in front of others what they need, the failure has become exclusion.</p><p>The response has four parts. <strong>Name it</strong> to the affected people first, privately and plainly: what has failed, what you are doing about it, and how long that will take. <strong>Offer real options</strong>: delay, a virtual link with captions, a change of room, a shortened accessible session, or rescheduling with a firm commitment. <strong>Decide with them</strong>, not for them, and do not put the decision to the whole room. <strong>Fix the process</strong> afterward: a backup contact, a confirmation step the day before, a room check on the morning, and a short written record.</p><p>Backups are planned in advance, not improvised. For each critical access element, know the fallback and who activates it: a second interpreter agency or the language access team’s emergency contact; automatic captions on and a captioning link tested; a second accessible room or a virtual link ready; the accessible document saved in two places. A ten-minute conversation before the day is worth an hour of scrambling on it.</p>" },
          { type: "accordion", heading: "Common failures and the response", items: [
            { title: "Interpreters do not arrive", body: "<p>Tell the Deaf attendees first. Call the agency’s emergency line and the language access team. Offer a delay, a remote interpreter by video if one can be secured, or a rescheduled session with a commitment. Do not start without them unless they choose that. Do not ask the audience for a volunteer.</p>" },
            { title: "Captions stop or are unusable", body: "<p>Switch to the platform’s automatic captions as a stopgap, tell the participants who rely on captions what has happened, slow the pace, and have the chat monitor post key points. Post a corrected transcript afterward. Confirm the captioner’s link works the day before next time.</p>" },
            { title: "The room changed or the elevator is out", body: "<p>Find out before anyone arrives by checking the morning of. If a step-free route no longer exists, move the session, run it virtually, or postpone; do not ask a wheelchair user to wait in the lobby while the group meets upstairs.</p>" },
            { title: "The accessible materials were not sent", body: "<p>Send them now, describe every visual aloud, slow down at each slide, and offer a follow-up session or written input period for anyone who needed the materials in advance. Add a check to the planning template.</p>" },
            { title: "A sensory environment is worse than expected", body: "<p>Turn off what you can, open the quiet room, allow movement and breaks, and tell people it is fine to step out and return. Note the venue problem for the next booking.</p>" },
            { title: "Someone arrives with a need no one anticipated", body: "<p>Welcome them, ask what would work today, do what you can immediately, and be honest about what will take longer. Then add the need to the default plan.</p>" },
          ] },
          { type: "leaderMove", heading: "Decide with the person, not for the room", control: "You control whether the decision about proceeding is made with the person whose participation is at stake, or by the convenience of the majority.", failure: "Do not say “we will start and catch you up.” Do not turn to the room and ask whether everyone minds waiting; that makes the affected person the reason for the delay in front of forty people.", next: "Agree with your team, before your next event, that a critical access failure pauses the session until the affected person has been consulted." },
          { type: "flashcards", heading: "The recovery sequence", cards: [
            { front: "Name it, privately, first", back: "<p>Go to the affected people before you address the room. Say what failed, what you are doing and how long it will take.</p>" },
            { front: "Real options", back: "<p>Delay, a virtual link with captions, a different room, a shortened accessible portion, rescheduling with a commitment. Not “make do.”</p>" },
            { front: "Their decision", back: "<p>Ask what they want to do, and do that. Do not put it to the room.</p>" },
            { front: "Backups are planned", back: "<p>Second interpreter contact, automatic captions and a tested link, a second room or virtual option, documents saved twice, and a named person who activates each.</p>" },
            { front: "Three lines afterward", back: "<p>What failed, what you did, what changes. Send it to the owner of the process and the team that books the next one.</p>" },
          ] },
          { type: "statement", body: "A person who came to be heard and could not be is owed more than an apology. They are owed the session, in a form that works, and a process that will not fail them the same way again." },
          { type: "knowledgeCheck", id: "inclusive-meetings-events-learning-5-check", question: "Twenty minutes into a virtual training, the live captioner’s connection drops and the participant who requested captioning can no longer follow. What is the right response?", options: [
            { text: "Continue and send the recording with a transcript afterward.", correct: false },
            { text: "Pause, tell the participant what has happened, turn on automatic captions as a stopgap while the captioner reconnects, slow the pace, have the chat monitor post key points, and post a corrected transcript afterward.", correct: true },
            { text: "Ask the participant whether they would prefer to leave and take the training another time.", correct: false },
          ], feedbackCorrect: "Yes. Name it, use the backup, adjust the pace, and repair the record afterward.", feedbackIncorrect: "Continuing excludes the person now, and offering them the exit makes them carry the failure. Use the backup and keep them in the session." },
          { type: "text", heading: "Take it to your work", body: "<p>Before the next invitation goes out, run it through the <a href=\"/practice/gp-12\">Equity Pause</a>. For the whole gathering, the <a href=\"/practice/gp-8\">inclusive meeting path</a> walks through access from the invitation to the notes.</p>" },
        ],
      },
    ],
  },
  jobAid: {
    title: "Inclusive meetings, events and learning",
    subtitle: "A one-page reminder for anyone who convenes people",
    quote: "Plan access before the invitation. Walk the route. Captions on. A host for the remote side. Decide with the person when something fails.",
    use: {
      purpose: "Keep the planning checklist, the format-specific essentials and the recovery sequence in view for every gathering you convene.",
      remember: ["The invitation is the last step; room, platform, interpreters and materials come first.", "Walk the route from the street to the seat; a venue’s assurance is not evidence.", "Remote participants lose first in hybrid rooms; give them a host and a microphone for every in-room voice.", "A failure becomes exclusion only if the person with the access need is left to carry it."],
      doNext: "Run your next gathering through the checklist before the invitation goes out and keep the changes in your template.",
    },
    sections: [
      { heading: "Before the invitation", items: ["Format, length and breaks decided; room or platform checked against the criteria.", "Interpreters and captioning requested with lead time through the responsible office.", "Materials deadline set backward from the date; access question, named contact and request date in registration.", "Roles assigned: host, chat and captions monitor, room and route contact, note taker."] },
      { heading: "On the day", items: ["In person: microphone for every voice, seating people choose, quiet room open, emergency plan known.", "Virtual and hybrid: captions on, interpreter pinned, chat read aloud, accessible alternative to every poll, camera optional.", "Name yourself, describe visuals, restate each decision from a shared notes document."] },
      { heading: "Afterward and when things fail", items: ["Notes with decisions, owners and dates at the top; recording with corrected captions and a transcript.", "When access fails: tell the affected person first, offer real options, decide with them, use the backup.", "Write three lines: what failed, what you did, what changes."] },
      { heading: "Standing arrangements and requests", items: ["Seating at the table for people who use wheelchairs and a clear path to the front for any presenter, never a place at the edge of the room.", "A microphone in every hand that speaks, lighting that shows faces for lip reading, and a room without background noise that fights hearing aids.", "Materials at least two working days ahead in accessible formats; slides in high contrast with large type and alternative text for every image.", "Speakers give their name before speaking, one person at a time, and say aloud what is on the screen for people listening remotely or without sight.", "Requests treated as routine: two interpreters for anything over an hour, booked well ahead and sent the materials; live captioning; assistive listening devices; braille or large print through the responsible office."] },
    ],
  },
  sources: [
    { title: "Section508.gov, Create Accessible Meetings", href: "https://www.section508.gov/create/accessible-meetings/", note: "Federal guidance on planning and running meetings that are accessible in person and online." },
    { title: "W3C Web Accessibility Initiative, How to Make Your Presentations and Meetings Accessible to All", href: "https://www.w3.org/WAI/teach-advocate/accessible-presentations/", note: "Practical guidance for organizers, speakers and participants on accessible presentations and meetings." },
    { title: "ADA National Network", href: "https://adata.org/", note: "Information on accessible events, effective communication and auxiliary aids and services under the ADA." },
    { title: "U.S. Department of Justice, ADA.gov, Effective Communication", href: "https://www.ada.gov/topics/effective-communication/", note: "Requirements for public entities to provide auxiliary aids and services such as interpreters and captioning." },
    { title: "U.S. Access Board", href: "https://www.access-board.gov/", note: "Accessibility standards for buildings, facilities and information technology, including the ADA Standards for Accessible Design." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "State resources on accessible events and public participation in Minnesota." },
  ],
};

export default pack;
