import { intermediatePack } from "./build";
export default intermediatePack({
 id: "div-i01-microinterventions", number: 1, title: "Responding to Microaggressions: Microintervention Practice",
 subtitle: "Choose a useful response to subtle exclusion, support the affected person, and follow through without taking over.",
 sources: [
 { title: "Sue and colleagues (2019): Disarming racial microaggressions", href: "https://pubmed.ncbi.nlm.nih.gov/30652905/", note: "The authors propose a microintervention framework. It is a practice framework, not proof that every response works in every setting." },
 { title: "Xie and Galliher (2023): Social cost of bystander intervention strategies", href: "https://www.apa.org/education-career/ce/microaggressions-bystander-intervention.pdf", note: "Research on how observers evaluate intervention strategies; effects and costs depend on context." }],
 lessons: [
 { title: "Notice the message and choose the immediate purpose", objectives: ["Separate the words heard from an interpretation of their impact.", "Choose an immediate purpose for intervening.", "Identify a response that does not require the affected person to explain."],
 teaching: [
 "A microintervention is a small, purposeful response to an exclusionary message or action. Small describes the scale of the response, not the importance of the harm. An effective opening might restore a colleague's turn, question an assumption, or make a work standard explicit. It need not settle the speaker's character or explain the history of racism. The first decision is what this moment needs. A person being repeatedly interrupted may need the floor restored before the group needs a discussion about interruption patterns. A misleading generalization may need correction before it becomes the premise of a decision.",
 "Distinguish observation, possible message, and response. The observation is what was said or done. The possible message is the assumption a listener might reasonably receive. The response is an action within your responsibility. Keeping these separate prevents both minimization and mind-reading. You can say that assigning a colleague to translation based on appearance is an unsupported assumption without claiming to know the assigner's intention. Sue and colleagues offer ways of making hidden messages visible and interrupting them; their framework does not make a single script universally effective.",
 "Before speaking, consider who holds authority, whether the immediate setting is safe, and whether a response could expose someone to more attention. Uncertainty about the perfect words does not require silence. A narrow statement such as 'We have not asked who wants that assignment' can interrupt a pattern without demanding personal testimony. If you misheard, make room for correction. If the words are clear, do not require the affected person to certify that they were harmful before you uphold a respectful process. The purpose is to improve what happens next, not to demonstrate how much the intervener knows."],
 case: "In a fictional project meeting, a coordinator sees Mei join and says she can handle a Mandarin-speaking community partner. Mei's assigned role is budget analysis. No one has asked about her languages or interest in interpreting. The meeting chair has only a minute before the agenda moves on. Mei looks at her notes; that expression does not tell the chair what Mei wants. The chair can correct the assignment process without interpreting Mei's feelings.",
 question: "What should the chair do first?", options: ["Ask Mei to explain why the comment was offensive.", "Say assignments require confirmed skills and interest, and return to the staffing criteria.", "Announce that the coordinator intended to exclude Mei."], reasons: ["This makes Mei responsible for teaching and disclosing a reaction.", "This corrects the unsupported assumption while preserving Mei's choice about any further conversation.", "The intent is unknown; an accusation can replace the specific correction with a dispute about character."],
 check: "Which statement distinguishes observation from interpretation?", answer: "The assignment was made without checking language skills; its impact should not be assumed from facial expression.", distractors: ["Mei looked down, so she definitely wanted a public apology.", "The coordinator meant well, so no correction is needed."], explanation: "You can act on the unverified assignment while leaving another person's internal response and the speaker's motive open.", reflection: "Privately consider a time you noticed a questionable assumption. What did you know directly, and what did you add? You may use the fictional case instead.", practice: "Write a one-sentence interruption that names the assignment process, not Mei's identity or feelings." },
 { title: "Rehearse three response routes", objectives: ["Write a clarifying question that does not disguise an accusation.", "Draft a direct boundary about a behavior.", "Select a redirect that preserves the personâ€™s contribution."],
 teaching: ["Three useful response routes are clarification, a direct boundary, and redirection. Clarification asks the speaker to make an assumption inspectable: 'What information are we using to make that assignment?' It works best when you are willing to listen to the answer. A question delivered as a trap can increase defensiveness without clarifying anything. Directness is appropriate when the behavior is already clear: 'Please let Amina finish her recommendation.' Redirection restores the task: 'Amina proposed the outreach sequence; let us consider that sequence before moving on.' Each route serves a different immediate purpose.",
 "Practice a short version before an explanation. Long lectures can consume the affected person's time, repeat the offensive phrase, and make the intervener the center of attention. The short version should name a behavior and request a change that can happen now. It should also be credible for your role. A meeting participant can ask to hear a colleague finish; the chair has additional responsibility to manage speaking turns. Someone with less authority may prefer a private follow-up or a request that another responsible person intervene. None of these choices establishes a person's courage or commitment.",
 "Response research examines both potential benefits and social costs. An intervention that an observer praises is not automatically the one that best supports the target. Conversely, an uncomfortable response is not automatically a failure. Evaluate what it accomplished: was inaccurate information corrected, was the interruption stopped, and did the person retain choices? Do not require gratitude. If a speaker says 'I was joking,' bring attention back to the shared practice rather than debating humor. You might say, 'We can keep the conversation informal and still avoid assigning motives to an entire community.' This maintains a concrete standard while allowing the discussion to continue."],
 case: "At a fictional planning session, Amina introduces a change to the registration process. Two people talk over her, and a third repeats her suggestion as a new idea. Jordan, another participant, wants to respond but is not the chair. The group has five minutes left to choose a plan. Jordan can restore attribution and the speaking turn without making Amina explain whether this has happened before or asking everyone to confess bias.", question: "Which response most directly restores the contribution?", options: ["Deliver a five-minute speech about workplace exclusion.", "Say 'That builds on Amina's proposal. Amina, would you like to finish your explanation?'", "Tell Amina afterward that the group probably did not mean it."], reasons: ["The speech can consume the time needed to hear the proposal.", "This restores credit and offers the floor without requiring acceptance.", "A private reassurance does not correct the lost contribution and assumes intent."], check: "What makes a redirect useful?", answer: "It restores a contribution or fair process that was displaced.", distractors: ["It makes the intervener appear knowledgeable.", "It guarantees nobody feels discomfort."], explanation: "Assess the response by the action it enables, not by applause or the absence of tension.", reflection: "Which route feels easiest to you: clarifying, setting a boundary, or redirecting? What might your default miss?", practice: "Rehearse all three routes for the case. Keep each opening under two sentences and choose the route that best restores the contribution." },
 { title: "Offer support without taking control", objectives: ["Offer support that leaves disclosure optional.", "Distinguish informal support from a formal reporting responsibility.", "Prepare a follow-up that avoids circulating another personâ€™s experience."],
 teaching: ["After a public moment, private support can be more useful than another public statement. Start with what you observed and offer a choice. 'I noticed the assignment was made without checking your skills. Would a follow-up from me be useful?' This wording does not require the person to agree with your interpretation. They may want action, space, a witness, or no conversation. The choice can change later. An offer is not consent to share the incident with friends, a team chat, or a training group.",
 "Keep the boundaries of your role clear. If you hold a responsibility that requires responding through a workplace process, do not promise absolute confidentiality or offer silence you cannot maintain. Explain the relevant limit before asking for details, and use the established channel. This course is informal learning, not a replacement for a complaint process or an investigation. An affected colleague should not have to complete this learning, educate you, or participate in mediation to receive appropriate support. Likewise, a bystander should not independently investigate motives or interview coworkers under the banner of being helpful.",
 "Support includes practical repair. Correct an inaccurate assignment, restore credit in meeting notes, or ask the chair to change how turns are managed. Check the proposed repair with the person when it specifically identifies them, while retaining your own responsibility to improve a generally unfair process. Avoid making one person the permanent spokesperson for the problem. A colleague can decline a conversation and still benefit from a better meeting process. Follow-through also includes protecting against informal retaliation: do not describe someone as difficult because they spoke or because they chose not to. Record only what a legitimate process requires, using factual and proportionate language."],
 case: "Following a fictional meeting, Luis tells a coworker he does not want another discussion of the comment made about his accent. The coworker wants to send a team-wide message defending him. The coworker is not a supervisor and has no assigned investigative role. The message would identify Luis and reproduce the comment. A quieter option is to respect his boundary and address general turn-taking and evidence standards without recounting his experience.", question: "What response respects Luis's agency?", options: ["Send the message because defending someone always takes priority over their preference.", "Respect the boundary, offer future support, and improve general practices without retelling his experience.", "Promise to conceal any future concern regardless of formal responsibilities."], reasons: ["The message takes control of Luis's story and can increase unwanted attention.", "This supports choice while allowing responsible action on a general process.", "An absolute promise may conflict with actual role obligations."], check: "A private offer of support gives permission to do what?", answer: "Offer choices; it does not itself authorize disclosure to others.", distractors: ["Publish the account without names because everyone will understand.", "Assume responsibility for deciding the person's preferred outcome."], explanation: "Consent to one conversation is not blanket consent for retelling or intervention.", reflection: "When has helping become deciding for someone else? Consider how you could offer two real choices instead.", practice: "Write a private support offer and a separate process improvement that does not identify the affected person." },
 { title: "Turn an isolated response into a better practice", objectives: ["Identify a repeatable condition that made exclusion easier.", "Design a proportionate process change.", "Evaluate follow-through without collecting personal stories."],
 teaching: ["A successful interruption is a beginning, not an entire response to a recurring pattern. If the same person is repeatedly interrupted, the chair can examine turn-taking. If expertise is repeatedly assigned from appearance, the coordinator can use a skills-and-interest process. This shift does not erase individual responsibility. It gives that responsibility a repeatable structure. The question becomes 'What will make the respectful action easier next time?' rather than 'Who can deliver the strongest correction every time this happens?'",
 "Choose a change small enough to observe. For a meeting, that might be crediting the originator when an idea enters the notes and returning to unfinished comments before moving on. For assignments, it might be recording the task requirement before identifying candidates. Decide who can implement the change and what ordinary evidence would show it happened. A revised agenda proves a change in preparation; it does not prove that participants felt included. If feedback is sought, make it optional and ask about the process rather than asking staff to disclose experiences of bias. Never interpret nonresponse as satisfaction.",
 "Review unintended effects. A rigid speaking order may improve participation for some and make others feel put on the spot. Provide a pass option and a written contribution route when feasible. A generic reminder about respect may avoid embarrassment but leave a concrete harmful assignment intact. Combine the specific repair with an appropriate general improvement. Keep the evidence modest: 'The chair restored two interrupted turns' is a useful observation; 'The team no longer has microaggressions' is an unsupported conclusion. The job aid helps choose and review an action, not score colleagues or certify a bias-free workplace. Learning remains available without an assessment or a required disclosure."],
 case: "A fictional project team agrees to acknowledge idea authors in its meeting notes. In the next two meetings, the notes name proposals accurately, but one member says the fast pace still prevents questions. The chair could declare success because the original complaint was about attribution. A more useful review separates the improved record from the remaining participation barrier and tests a pause for questions before each decision, with a written follow-up option.", question: "What does the available evidence support?", options: ["The team has eliminated exclusion.", "Attribution in the notes improved; participation still needs a separate response.", "The change failed completely because another issue remains."], reasons: ["Improved attribution in two meetings does not establish that every form of exclusion has ended.", "This recognizes a real improvement without treating it as proof of a broader outcome.", "One unresolved condition does not erase a demonstrated improvement."], check: "Which review measure fits the change?", answer: "Check whether contributions are credited and ask optionally whether the process supports participation.", distractors: ["Rank employees by how often they intervene.", "Require affected staff to recount incidents each month."], explanation: "Process evidence can support learning without turning personal experiences into monitoring data.", reflection: "What would count as a useful improvement even if nobody praised your intervention?", practice: "Use the job aid to select one response and one process change. Identify an owner within the work process, a reasonable review point, and an observation that could lead you to revise the approach." }
 ],
 aid: { title: "Microintervention response and follow-through card", sections: [
 { heading: "Observe", items: ["Write the words or action without assigning motive.", "Separate a possible message from what you know about another person's feelings."] },
 { heading: "Choose a purpose", items: ["Restore a turn, correct an assumption, set a boundary, or offer support.", "Choose clarification, directness, redirection, or a later response based on role and context."] },
 { heading: "Preserve choice", items: ["Offer support without requiring disclosure or gratitude.", "Explain any actual role-based limits on confidentiality before asking for details."] },
 { heading: "Review the practice", items: ["Name the process change, responsible role, review point, and observable evidence.", "Distinguish a repaired moment from a claim that the broader problem has ended."] }
 ] }
});
