// @vitest-environment jsdom
import { afterEach,describe,expect,it,vi } from "vitest";
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { ResourceReleaseClient } from "@/components/resource-release-client";
import { ResourceInlineEditor } from "@/components/resource-inline-editor";
import { draftInput,draftId,fixtureResource,releaseFixture } from "./contributor-resource-fixtures";
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe("contributor resource controls",()=>{
 it("keeps owner endpoints as the default",async()=>{const fetcher=vi.fn().mockResolvedValue({ok:true,json:async()=>({release:releaseFixture()})});vi.stubGlobal("fetch",fetcher);render(<ResourceReleaseClient initial={releaseFixture()}/>);fireEvent.click(screen.getByRole("button",{name:"Save this review"}));await waitFor(()=>expect(fetcher).toHaveBeenCalled());expect(fetcher.mock.calls[0][0]).toBe(`/api/consultant/resources/${fixtureResource.id}/release`);});
 it("hides publication controls and disables review for a drafting-only contributor",()=>{render(<ResourceReleaseClient initial={releaseFixture()} endpoint="/api/contribute/resources/R-1/release" canReview={false} canPublish={false} canWithdraw={false} editHref="/contribute/resources/R-1/edit"/>);expect(screen.getByRole("button",{name:"Save this review"}).closest("fieldset")?.disabled).toBe(true);expect(screen.queryByRole("button",{name:"Publish this reviewed resource"})).toBeNull();expect(screen.queryByRole("button",{name:"Withdraw this resource"})).toBeNull();expect(screen.getByRole("link",{name:"Prepare a resource draft"}).getAttribute("href")).toBe("/contribute/resources/R-1/edit");});
 it("retains an unsaved draft after a conflict and posts only to the contributor endpoint",async()=>{const fetcher=vi.fn().mockResolvedValue({ok:false,json:async()=>({error:"The draft changed. Keep your wording."})});vi.stubGlobal("fetch",fetcher);render(<ResourceInlineEditor initial={{contentItemId:fixtureResource.id,expectedRevisionId:draftId,publishedRevisionId:null,hasUnpublishedChanges:true,fields:draftInput.fields}} pathOptions={[]} endpoint="/api/contribute/resources/R-1/draft" reviewHref="/contribute/resources/R-1" workspaceLabel="Contribute"/>);fireEvent.click(screen.getByRole("button",{name:"Open editing fields"}));fireEvent.change(screen.getByLabelText("Title"),{target:{value:"My unsaved contribution"}});fireEvent.click(screen.getByRole("button",{name:"Save draft for review"}));await screen.findByRole("alert");expect((screen.getByLabelText("Title") as HTMLInputElement).value).toBe("My unsaved contribution");expect(fetcher.mock.calls[0][0]).toBe("/api/contribute/resources/R-1/draft");});
});
