import { existsSync,mkdtempSync,readFileSync,readdirSync,rmSync} from "node:fs";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import postgres from "postgres";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { writeEvidenceReceipt } from "@/tests/helpers/evidence-receipts";
import { localPostgresServerOptions } from "@/tests/helpers/local-postgres";
import { fixtureResource } from "./contributor-resource-fixtures";
import { ContributorResourceStore } from "@/lib/content/contributor-resources";
import type { ResourceReleaseState } from "@/lib/content/resource-release-contract";
const ROOT=path.resolve(import.meta.dirname,"..");
const REVIEW_DIMENSIONS=["language_alignment","factual_currentness","accessibility","scope","placement","rights_and_consent","community_representation","legal_policy"];
type DB=ReturnType<typeof postgres>;
type Identity={account_id:string;session_id:string;digest:string;grants:Record<string,string>};
const E={identity:"resource-identity-test",identityHash:"a".repeat(64),contribution:"resource-contribution-test",contributionHash:"b".repeat(64)};
const RESOURCE={...fixtureResource,id:"contributor-resource-test",title:"Practical access guidance",summary:"A practical resource for colleagues.",body:["Use these steps to prepare an accessible meeting."],whyItMatters:"Clear preparation makes participation easier.",owner:"Program resources",tags:["access"],scope:"agencywide" as const,status:"approved" as const,accessibility:"reviewed" as const};
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const digest=(label:string)=>hash("disposable-resource-test:"+label);
const credential="$pac-scrypt$v=1$ln=17$r=8$p=1$"+"A".repeat(22)+"$"+"B".repeat(43);
function pgBinary(name:string){const executable=name+(process.platform==="win32"?".exe":"");return [process.env.PAC_TEST_POSTGRES_BIN?path.join(process.env.PAC_TEST_POSTGRES_BIN,executable):"",path.join(process.env.ProgramFiles??"C:/Program Files","PostgreSQL","16","bin",executable),"/usr/lib/postgresql/16/bin/"+executable].find(p=>p&&existsSync(p));}
function run(executable:string,args:string[]){const r=spawnSync(executable,args,{stdio:"ignore",windowsHide:true,timeout:60000});if(r.status!==0)throw new Error(path.basename(executable)+" failed");}
async function unusedPort():Promise<number>{return new Promise((resolve,reject)=>{const server=createServer();server.once("error",reject);server.listen(0,"127.0.0.1",()=>{const address=server.address();if(!address||typeof address==="string"){server.close();reject(new Error("Missing local port"));return;}server.close(e=>e?reject(e):resolve(address.port));});});}
describe("named contributor resource PostgreSQL lifecycle",()=>{
 let temporaryRoot="",dataDirectory="",adminUrl="",contributorUrl="";let admin:DB,contributor:DB,ownerRuntime:DB;
 let owner:Identity,drafter:Identity,reviewer:Identity,publisher:Identity;let beforePreservation:unknown,afterPreservation:unknown;
 const identityParams=(p:Identity)=>[p.digest,"local",E.identity,E.identityHash];
 const readParams=(p:Identity,scope="one-dhs")=>[...identityParams(p),E.contribution,E.contributionHash,scope];
 async function activate(feature:string,state="active"){await admin.unsafe("select pac.record_protected_feature_activation($1,$2,$3,$4,$5,$6)",["local",feature,state,feature==="protected_identity"?E.identity:E.contribution,feature==="protected_identity"?E.identityHash:E.contributionHash,"Disposable local verification only."]);}
 async function person(name:string,roles:string[]=[],scope="one-dhs"):Promise<Identity>{
  const invite=digest(name+"-invite"),session=digest(name+"-session");
  await contributor.unsafe("select * from pac.create_program_account_invitation($1,$2,$3,$4,$5,$6,$7,$8::timestamptz)",[...identityParams(owner),name,"Test "+name,invite,new Date(Date.now()+3600000).toISOString()]);
  const [record]=await contributor.unsafe<{account_id:string;session_id:string}[]>("select * from pac.accept_program_account_invitation($1,$2,$3,$4,$5,$6)",[invite,credential,session,"local",E.identity,E.identityHash]);
  const result:Identity={...record,digest:session,grants:{}};
  for(const role of roles){const [grant]=await contributor.unsafe<{grant_id:string}[]>("select * from pac.issue_program_access_grant($1,$2,$3,$4,$5::uuid,$6,$7,$8::timestamptz,$9)",[...identityParams(owner),record.account_id,scope,role,null,"Isolated role test."]);result.grants[role]=grant.grant_id;}return result;
 }
 async function read(p:Identity,scope="one-dhs",db=contributor):Promise<ResourceReleaseState>{const [r]=await db.unsafe<{state:ResourceReleaseState}[]>("select pac.read_contributor_resource_release_state($1,$2,$3,$4,$5,$6,$7,$8) as state",[...readParams(p,scope),RESOURCE.id]);return r.state;}
 async function editing(p:Identity,scope="one-dhs"){const [r]=await contributor.unsafe<{base_revision_id:string;editable_fields:Record<string,unknown>}[]>("select * from pac.read_contributor_resource_editing_state($1,$2,$3,$4,$5,$6,$7,$8)",[...readParams(p,scope),RESOURCE.id]);return r;}
 async function mutate(p:Identity,operation:string,payload:unknown,scope="one-dhs",db=contributor){const [r]=await db.unsafe<{result:unknown}[]>("select pac.run_protected_content_mutation($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::text::jsonb) as result",[...readParams(p,scope),operation,RESOURCE.id,JSON.stringify(payload)]);return r.result;}
 async function preservation(){
  const functions=await admin.unsafe("select p.oid::regprocedure::text signature,pg_get_functiondef(p.oid) definition,p.proacl::text privileges from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='pac' and p.proname in ('read_resource_editing_state','create_resource_draft','read_resource_release_state','list_resource_release_queue','record_resource_review','publish_resource_draft','withdraw_resource_publication','republish_resource_revision','enforce_publication_gate','save_page_block_copy','save_editable_surface') order by signature");
  const source=await admin.unsafe("select source_item_id,normalized_payload,normalized_item_sha256,owner_approval_status from pac.source_items order by source_item_id");
  const revisions=await admin.unsafe("select revision_id,payload_sha256,canonical_payload,created_by from pac.content_revisions order by revision_id");
  const ownerApprovals=await admin.unsafe("select 'resource' kind,coalesce(jsonb_agg(to_jsonb(r) order by r.revision_id),'[]'::jsonb) records from pac.resource_owner_approvals r union all select 'page',coalesce(jsonb_agg(to_jsonb(r) order by r.revision_id),'[]'::jsonb) from pac.page_block_owner_approvals r union all select 'surface',coalesce(jsonb_agg(to_jsonb(r) order by r.revision_id),'[]'::jsonb) from pac.surface_owner_approvals r");
  return {functions:hash(functions),sources:hash(source),revisions:hash(revisions),ownerApprovals:hash(ownerApprovals),functionCount:functions.length,sourceCount:source.length,revisionCount:revisions.length};
 }
 async function seed(){
  const [carrier]=await admin.unsafe<{carrier_id:string}[]>("insert into pac.source_carriers(logical_key,media_type,original_name,captured_by) values('contributor-resource-fixture','application/json','resource-fixture.json','fixture-owner') returning carrier_id");
  await admin.unsafe("insert into pac.source_items(source_item_id,source_business_id,carrier_id,title,normalized_payload,normalized_item_sha256,hash_algorithm,hash_algorithm_version,owner_approval_status,accounting_status,access_scope,sensitivity_class,deidentification_status,ordinary_indexing_allowed,model_context_allowed) values('contributor-resource-source','contributor-resource-source',$1::uuid,'Approved fixture source',$2::text::jsonb,$3,'sha256','1','owner_approved_for_ingestion','accounted','internal_source','S1','not_needed',true,false)",[carrier.carrier_id,JSON.stringify(RESOURCE),hash(RESOURCE)]);
  await admin.unsafe("insert into pac.content_items(content_item_id,content_kind,default_scope_id,staff_label,created_by,sensitivity_class,restricted) values($1,'resource','one-dhs',$2,'fixture-owner','S1',false)",[RESOURCE.id,RESOURCE.title]);
  const [rev]=await admin.unsafe<{revision_id:string}[]>("insert into pac.content_revisions(content_item_id,revision_number,canonical_payload,change_summary,created_by,sensitivity_class,ordinary_indexing_allowed,model_context_allowed,required_review_dimensions) values($1,1,$2::text::jsonb,'Approved fixture original','fixture-owner','S1',true,false,$3::text[]) returning revision_id",[RESOURCE.id,JSON.stringify(RESOURCE),REVIEW_DIMENSIONS]);
  await admin.unsafe("insert into pac.revision_sources(revision_id,source_item_id,relationship) values($1::uuid,'contributor-resource-source','primary')",[rev.revision_id]);
  await admin.unsafe("insert into pac.review_records(revision_id,dimension,status,reviewer_role,reviewer_id) select $1::uuid,dimension,'pass','program_steward','fixture-original-reviewer' from unnest($2::text[]) dimension",[rev.revision_id,REVIEW_DIMENSIONS]);
  await admin.unsafe("insert into pac.publication_decisions(content_item_id,revision_id,scope_id,decision,gate_snapshot,decided_by,reason,sensitivity_class,unauthenticated_exposure_permitted,exposure_reason) values($1,$2::uuid,'one-dhs','publish','{}'::jsonb,'fixture-owner','Approved fixture original','S1',true,'Publicly suitable practice guidance.')",[RESOURCE.id,rev.revision_id]);
 }
 beforeAll(async()=>{
  const initdb=pgBinary("initdb"),pgctl=pgBinary("pg_ctl");if(!initdb||!pgctl)throw new Error("Local PostgreSQL is required; verification must not silently skip.");
  temporaryRoot=mkdtempSync(path.join(tmpdir(),"pac-contributor-resource-"));dataDirectory=path.join(temporaryRoot,"data");const port=await unusedPort();
  run(initdb,["-D",dataDirectory,"--username=pac_test","--auth=trust","--encoding=UTF8","--no-locale"]);
  run(pgctl,["-D",dataDirectory,"-l",path.join(temporaryRoot,"postgres.log"),"-o",localPostgresServerOptions(port,temporaryRoot),"-w","start"]);
  adminUrl="postgresql://pac_test@127.0.0.1:"+port+"/postgres";contributorUrl=adminUrl.replace("pac_test@","pac_contributor_runtime@");admin=postgres(adminUrl,{ssl:false,max:1,prepare:false,onnotice:()=>undefined});
  const migrations=readdirSync(path.join(ROOT,"db/migrations")).filter(name=>/^\d{4}_.+\.sql$/.test(name)).sort();
  expect(migrations).toContain("0045_pac_contributor_resource_workflow.sql");
  for(const name of migrations){if(name.startsWith("0042_")){await seed();beforePreservation=await preservation();}try{await admin.unsafe(readFileSync(path.join(ROOT,"db/migrations",name),"utf8"));}catch(error){const failure=error as {message?:string;code?:string;position?:string};throw new Error("Fresh contributor migration failed at "+name+": "+failure.code+" position "+failure.position+" "+failure.message);}}
  afterPreservation=await preservation();
  const diagnostic=await admin.unsafe("select i.content_item_id,i.restricted,i.default_scope_id,i.retired_at,r.canonical_payload->>'id' payload_id,r.canonical_payload->>'status' status,s.active,pac.resource_management_allowed('one-dhs',i.content_item_id) allowed from pac.content_items i join pac.content_revisions r using(content_item_id) join pac.program_scopes s on s.scope_id=i.default_scope_id where i.content_item_id=$1",[RESOURCE.id]);
  expect(diagnostic).toHaveLength(1);expect(diagnostic[0]).toMatchObject({payload_id:RESOURCE.id,status:'approved',allowed:true});
  contributor=postgres(contributorUrl,{ssl:false,max:4,prepare:false,onnotice:()=>undefined});ownerRuntime=postgres(adminUrl.replace("pac_test@","pac_app_runtime@"),{ssl:false,max:1,prepare:false,onnotice:()=>undefined});
  await activate("protected_identity");await activate("protected_contribution");
  const invite=digest("bootstrap-invite"),session=digest("bootstrap-session");
  await admin.unsafe("select * from pac.bootstrap_program_owner_invitation($1,$2,$3,$4,$5::timestamptz,$6,$7)",["local","test.owner","Disposable Test Owner",invite,new Date(Date.now()+3600000).toISOString(),E.identity,E.identityHash]);
  const [identity]=await contributor.unsafe<{account_id:string;session_id:string}[]>("select * from pac.accept_program_account_invitation($1,$2,$3,$4,$5,$6)",[invite,credential,session,"local",E.identity,E.identityHash]);
  owner={...identity,digest:session,grants:{}};drafter=await person("test.drafter",["content_contributor"]);reviewer=await person("test.reviewer",["program_steward"]);publisher=await person("test.publisher",["publishing_approver"]);
 },120000);
 afterAll(async()=>{await contributor?.end({timeout:5}).catch(()=>undefined);await ownerRuntime?.end({timeout:5}).catch(()=>undefined);await admin?.end({timeout:5}).catch(()=>undefined);const pgctl=pgBinary("pg_ctl");if(pgctl&&dataDirectory&&existsSync(dataDirectory))spawnSync(pgctl,["-D",dataDirectory,"-m","immediate","-w","stop"],{stdio:"ignore",windowsHide:true,timeout:30000});if(temporaryRoot&&path.dirname(temporaryRoot)===path.resolve(tmpdir())&&path.basename(temporaryRoot).startsWith("pac-contributor-resource-"))rmSync(temporaryRoot,{recursive:true,force:true});},45000);
 it("preserves owner functions, approvals and original content through installation",()=>{expect(afterPreservation).toEqual(beforePreservation);writeEvidenceReceipt(path.join(ROOT,"evidence/functional-completion-2026-09-08/contributor-resource-preservation.json"),{verifiedAt:new Date().toISOString(),scope:"Fresh local database only",before:beforePreservation,after:afterPreservation,preserved:true});});
 it("denies direct owner resource and authorizer functions while preserving owner reads",async()=>{
  for(const sql of ["select * from pac.read_resource_editing_state('one-dhs','contributor-resource-test')","select pac.read_resource_release_state('one-dhs','contributor-resource-test')","select * from pac.content_revisions","select * from pac.program_account_credential_secrets","select pac.authorize_protected_action(null,null,null,null,null,null,null,null,null,null)","select pac.consume_protected_action(null,null,null)"])await expect(contributor.unsafe(sql)).rejects.toMatchObject({code:"42501"});
  expect(await ownerRuntime.unsafe("select * from pac.read_resource_editing_state('one-dhs','contributor-resource-test')")).toHaveLength(1);
  expect((await contributor.unsafe("select has_function_privilege(current_user,'pac.create_resource_draft(text,text,uuid,jsonb,text)','EXECUTE') allowed"))[0].allowed).toBe(false);
 });
 it("completes all five named actions with original reviewer attribution and durable receipts",async()=>{
  const base=await editing(drafter);const draft=await mutate(drafter,"resource_draft_save",{expectedRevisionId:base.base_revision_id,fields:{...base.editable_fields,title:"Reviewed access guidance"},changeNote:"A useful clarification."}) as {base_revision_id:string};
  let state=await read(reviewer);expect(state.published?.revisionId).toBe(base.base_revision_id);expect(state.draft?.reviews.every(r=>r.status==="pending")).toBe(true);
  const exposure={reason:"Publish reviewed guidance.",sensitivityClass:"S1",unauthenticatedExposurePermitted:true,exposureReason:"Publicly suitable practice guidance."};
  await expect(mutate(publisher,"resource_publish",{revisionId:draft.base_revision_id,expectedScopeDecisionId:state.scopeDecisionId,...exposure})).rejects.toMatchObject({code:"55000"});
  for(const dimension of REVIEW_DIMENSIONS){const review=state.draft!.reviews.find(r=>r.dimension===dimension)!;state=await mutate(reviewer,"resource_review_record",{revisionId:draft.base_revision_id,dimension,expectedPriorReviewId:review.reviewId,decision:"pass",note:"Checked practical guidance."}) as ResourceReleaseState;}
  expect(state.draft?.readyToPublish).toBe(true);state=await mutate(publisher,"resource_publish",{revisionId:draft.base_revision_id,expectedScopeDecisionId:state.scopeDecisionId,...exposure}) as ResourceReleaseState;const releaseId=state.published!.revisionId;
  state=await mutate(publisher,"resource_withdraw",{revisionId:releaseId,expectedScopeDecisionId:state.scopeDecisionId,reason:"Check the latest wording."}) as ResourceReleaseState;expect(state.withdrawn).toBe(true);
  state=await mutate(publisher,"resource_republish",{revisionId:releaseId,expectedScopeDecisionId:state.scopeDecisionId,...exposure}) as ResourceReleaseState;expect(state.published?.revisionId).toBe(releaseId);
  const reopened=postgres(contributorUrl,{ssl:false,max:1,prepare:false});try{expect((await read(publisher,"one-dhs",reopened)).scopeDecisionId).toBe(state.scopeDecisionId);}finally{await reopened.end({timeout:5});}
  const [created]=await admin.unsafe("select created_by,protected_authorization_id from pac.content_revisions where revision_id=$1::uuid",[draft.base_revision_id]);expect(created).toMatchObject({created_by:drafter.account_id,protected_authorization_id:expect.any(String)});
  const reviews=await admin.unsafe("select reviewer_id,reviewer_role,findings from pac.review_records where revision_id=$1::uuid",[releaseId]);expect(reviews).toHaveLength(8);for(const r of reviews){expect(r.reviewer_id).toBe(reviewer.account_id);expect(r.findings.carried_forward_by).toBe(publisher.account_id);}
  const receipts=await admin.unsafe("select a.authorization_id,a.action_kind,a.account_id,c.result_record_type,c.action_record_id from pac.protected_action_authorizations a join pac.protected_action_consumptions c using(authorization_id) where a.target_id=$1 order by a.authorized_at,a.authorization_id",[RESOURCE.id]);expect(receipts).toHaveLength(12);expect(receipts.every(r=>[drafter.account_id,reviewer.account_id,publisher.account_id].includes(String(r.account_id)))).toBe(true);
  await expect(admin.unsafe("select pac.consume_protected_action($1::uuid,'content_revision',$2)",[receipts[0].authorization_id,draft.base_revision_id])).rejects.toBeDefined();
  expect((await admin.unsafe("select count(*)::int count from pac.resource_owner_approvals"))[0].count).toBe(0);
  writeEvidenceReceipt(path.join(ROOT,"evidence/functional-completion-2026-09-08/contributor-resource-task-receipts.json"),{verifiedAt:new Date().toISOString(),scope:"Disposable local test identities only",operations:receipts,reopened:true,carriedReviewAttributionPreserved:true});
 });
 it("round-trips resource drafts through the actual contributor service and PostgreSQL adapter",async()=>{
  const store=new ContributorResourceStore({query:async(statement,parameters=[])=>contributor.unsafe(statement,parameters as never[]),close:async()=>undefined});
  const context={sessionTokenDigest:drafter.digest,environment:"local" as const,identityEvidenceId:E.identity,identityBundleSha256:E.identityHash,contributionEvidenceId:E.contribution,contributionBundleSha256:E.contributionHash};
  expect((await store.queue(context,"one-dhs")).some(item=>item.contentItemId===RESOURCE.id)).toBe(true);
  const base=await store.editing(context,"one-dhs",RESOURCE.id);expect(base).toBeDefined();
  const saved=await store.save(context,"one-dhs",RESOURCE.id,{expectedRevisionId:base!.expectedRevisionId,fields:{...base!.fields,title:"Clear guidance for an accessible meeting"},changeNote:"Confirmed through the actual named contributor service."});
  expect(saved.fields.title).toBe("Clear guidance for an accessible meeting");expect(saved.expectedRevisionId).not.toBe(base!.expectedRevisionId);
  const state=await store.read(context,"one-dhs",RESOURCE.id);expect(state?.draft?.revisionId).toBe(saved.expectedRevisionId);
  await expect(store.save(context,"one-dhs",RESOURCE.id,{expectedRevisionId:base!.expectedRevisionId,fields:base!.fields,changeNote:null})).rejects.toMatchObject({status:409});
 });
 it("rejects stale draft CAS, fabricated actors and cross-scope fields",async()=>{const base=await editing(drafter);const payload={expectedRevisionId:base.base_revision_id,fields:{...base.editable_fields,title:"Another useful revision"},changeNote:null};await mutate(drafter,"resource_draft_save",payload);await expect(mutate(drafter,"resource_draft_save",payload)).rejects.toMatchObject({code:"40001"});const current=await editing(drafter);await expect(mutate(drafter,"resource_draft_save",{...payload,expectedRevisionId:current.base_revision_id,actorId:publisher.account_id})).rejects.toMatchObject({code:"22023"});await expect(mutate(drafter,"resource_draft_save",{...payload,expectedRevisionId:current.base_revision_id,fields:{...payload.fields,scope:"dsd"}})).rejects.toMatchObject({code:"22023"});});
 it("does not let a DSD grant read or change agencywide working content",async()=>{const dsd=await person("test.dsd",["content_contributor"],"dsd");await expect(read(dsd)).rejects.toMatchObject({code:"PAA01"});const base=await editing(drafter);await expect(mutate(dsd,"resource_draft_save",{expectedRevisionId:base.base_revision_id,fields:base.editable_fields,changeNote:null})).rejects.toMatchObject({code:"PAA01"});expect((await editing(dsd,"dsd")).editable_fields.scope).toBe("dsd");});
 it("rejects stale reviews and publishing without the required role",async()=>{const state=await read(reviewer),review=state.draft!.reviews[0],payload={revisionId:state.draft!.revisionId,dimension:review.dimension,expectedPriorReviewId:review.reviewId,decision:"pass",note:"Checked this version."};await mutate(reviewer,"resource_review_record",payload);await expect(mutate(reviewer,"resource_review_record",payload)).rejects.toMatchObject({code:"40001"});await expect(mutate(drafter,"resource_withdraw",{revisionId:state.published!.revisionId,expectedScopeDecisionId:state.scopeDecisionId,reason:"No publishing grant."})).rejects.toMatchObject({code:"PAA01"});});
 it("honors revoked grants, revoked sessions and expired sessions on the next SQL call",async()=>{for(const kind of ["grant","session","expired"]){const p=await person("test."+kind,["content_contributor"]);expect((await read(p)).contentItemId).toBe(RESOURCE.id);if(kind==="grant")await contributor.unsafe("select pac.revoke_program_access_grant($1,$2,$3,$4,$5::uuid,$6)",[...identityParams(owner),p.grants.content_contributor,"End disposable test access."]);else if(kind==="session")await contributor.unsafe("select pac.end_program_account_session($1,$2)",[p.digest,"local"]);else await admin.unsafe("update pac.program_account_sessions set issued_at=clock_timestamp()-interval '9 hours',expires_at=clock_timestamp()-interval '1 hour' where session_id=$1::uuid",[p.session_id]);await expect(read(p)).rejects.toMatchObject({code:kind==="grant"?"PAA01":"PAI01"});}});
 it("reads graph neighbors only from current visible published revisions in the requested scope",async()=>{
  const state=await read(publisher);const sourceRevision=state.published!.revisionId;
  async function graphVersion(id:string,scope:string,number=1,publish=true){
    if(number===1)await admin.unsafe("insert into pac.content_items(content_item_id,content_kind,default_scope_id,staff_label,created_by,sensitivity_class,restricted) values($1,'resource',$2,'Related guidance','fixture-owner','S1',false)",[id,scope]);
    const payload={...RESOURCE,id,scope:scope==="dsd"?"dsd":"agencywide",title:"Related guidance "+id+" version "+number};
    const [revision]=await admin.unsafe<{revision_id:string}[]>("insert into pac.content_revisions(content_item_id,revision_number,canonical_payload,change_summary,created_by,sensitivity_class,ordinary_indexing_allowed,model_context_allowed,required_review_dimensions) values($1,$2,$3::text::jsonb,'Graph fixture','fixture-owner','S1',true,false,$4::text[]) returning revision_id",[id,number,JSON.stringify(payload),REVIEW_DIMENSIONS]);
    await admin.unsafe("insert into pac.revision_sources(revision_id,source_item_id,relationship) values($1::uuid,'contributor-resource-source','primary')",[revision.revision_id]);
    await admin.unsafe("insert into pac.review_records(revision_id,dimension,status,reviewer_role,reviewer_id) select $1::uuid,dimension,'pass','program_steward','fixture-original-reviewer' from unnest($2::text[]) dimension",[revision.revision_id,REVIEW_DIMENSIONS]);
    if(publish)await admin.unsafe("insert into pac.publication_decisions(content_item_id,revision_id,scope_id,decision,gate_snapshot,decided_by,reason,sensitivity_class,unauthenticated_exposure_permitted,exposure_reason) values($1,$2::uuid,$3,'publish','{}'::jsonb,'fixture-owner','Graph fixture','S1',true,'Publicly suitable practice guidance.')",[id,revision.revision_id,scope]);
    return revision.revision_id;
  }
  const graphRows=[{id:RESOURCE.id,revision:sourceRevision}];
  for(const id of ["graph-current","graph-stale","graph-withdrawn","graph-dsd","graph-unpublished"]){const scope=id==="graph-dsd"?"dsd":"one-dhs";graphRows.push({id,revision:await graphVersion(id,scope,1,id!=="graph-unpublished")});}
  await graphVersion("graph-stale","one-dhs",2);
  const withdrawn=graphRows.find(row=>row.id==="graph-withdrawn")!;
  await admin.unsafe("insert into pac.publication_decisions(content_item_id,revision_id,scope_id,decision,gate_snapshot,decided_by,reason) values($1,$2::uuid,'one-dhs','withdraw','{}'::jsonb,'fixture-owner','Graph withdrawal fixture')",[withdrawn.id,withdrawn.revision]);
  await admin.unsafe("insert into pac.knowledge_nodes(node_id,node_type,label,review_status,created_by) values('graph-test-topic','topic','Accessible participation','reviewed','fixture-owner')");
  for(const row of graphRows){const node="graph-node-"+row.id;await admin.unsafe("insert into pac.knowledge_nodes(node_id,node_type,label,content_item_id,properties,review_status,created_by) values($1,'revision','Published resource',$2,jsonb_build_object('revisionId',$3::text),'reviewed','fixture-owner')",[node,row.id,row.revision]);await admin.unsafe("insert into pac.knowledge_edges(edge_id,from_node_id,to_node_id,edge_type,review_status,created_by) values($1,$2,'graph-test-topic','applies_to','reviewed','fixture-owner')",["graph-edge-"+row.id,node]);}
  const agency=await ownerRuntime.unsafe("select * from pac.read_staff_graph_neighbors('one-dhs',$1,12)",[RESOURCE.id]);expect(agency.map(row=>row.content_item_id)).toEqual(["graph-current"]);
  const dsd=await ownerRuntime.unsafe("select * from pac.read_staff_graph_neighbors('dsd',$1,12)",[RESOURCE.id]);expect(dsd.map(row=>row.content_item_id).sort()).toEqual(["graph-current","graph-dsd"]);
  expect(await ownerRuntime.unsafe("select * from pac.read_staff_graph_neighbors('one-dhs','graph-withdrawn',12)")).toHaveLength(0);
  writeEvidenceReceipt(path.join(ROOT,"evidence/functional-completion-2026-09-08/staff-graph-postgres.json"),{verifiedAt:new Date().toISOString(),scope:"Fresh disposable local database",agency,dsd,withdrawnExcluded:true,unpublishedExcluded:true,staleRevisionEdgesExcluded:true,wrongScopeExcluded:true});
 });
 it("allows only withdrawal during a contribution pause and stops named work when identity pauses",async()=>{const state=await read(publisher);await activate("protected_contribution","inactive");await expect(read(drafter)).rejects.toMatchObject({code:"PAA01"});expect((await read(publisher)).scopeDecisionId).toBe(state.scopeDecisionId);await expect(mutate(publisher,"resource_republish",{revisionId:state.published!.revisionId,expectedScopeDecisionId:state.scopeDecisionId,reason:"Cannot widen while paused.",sensitivityClass:"S1",unauthenticatedExposurePermitted:true,exposureReason:"Public guidance."})).rejects.toMatchObject({code:"PAF01"});const withdrawn=await mutate(publisher,"resource_withdraw",{revisionId:state.published!.revisionId,expectedScopeDecisionId:state.scopeDecisionId,reason:"Contain the current publication."}) as ResourceReleaseState;expect(withdrawn.withdrawn).toBe(true);await activate("protected_identity","inactive");await expect(read(publisher)).rejects.toMatchObject({code:"PAF01"});await expect(mutate(publisher,"resource_withdraw",{revisionId:state.published!.revisionId,expectedScopeDecisionId:withdrawn.scopeDecisionId,reason:"Named identity is paused."})).rejects.toMatchObject({code:"42501"});});
});
