import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
const mocks=vi.hoisted(()=>({ identity:vi.fn(),principal:vi.fn(),context:vi.fn(),factory:vi.fn() }));
vi.mock("@/lib/auth/program-request",()=>({programIdentityFromRequest:mocks.identity,programMutationPrincipalFromRequest:mocks.principal}));
vi.mock("@/lib/auth/protected-mutation",()=>({ protectedMutationContextFromSessionToken:mocks.context, ProtectedMutationFeatureUnavailableError:class extends Error {} }));
vi.mock("@/lib/content/contributor-resources",async importOriginal=>({...await importOriginal<typeof import("@/lib/content/contributor-resources")>(),contributorResourceStore:mocks.factory}));
import { handleContributorResourceGet,handleContributorResourceDraft,handleContributorResourceAction } from "@/app/api/contribute/resources/handlers";
import { ContributorResourceError } from "@/lib/content/contributor-resources";
import { draftInput, editingRow, fixtureResource, fixtureContext, releaseFixture, revisionId } from "./contributor-resource-fixtures";
function request(method:string,body?:unknown,crossSite=false){return new NextRequest("https://program.example/api/contribute/resources/R-1/release",{method,headers:{origin:crossSite?"https://other.example":"https://program.example","content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});}
beforeEach(()=>{vi.clearAllMocks();mocks.identity.mockResolvedValue({accountId:"named-account"});mocks.principal.mockResolvedValue({identity:{accountId:"named-account"},sessionToken:"test-session"});mocks.context.mockReturnValue(fixtureContext);mocks.factory.mockReturnValue({read:vi.fn().mockResolvedValue(releaseFixture()),queue:vi.fn().mockResolvedValue([]),editing:vi.fn().mockResolvedValue(editingRow),save:vi.fn().mockResolvedValue(editingRow),act:vi.fn().mockResolvedValue(releaseFixture()),close:vi.fn()});});
describe("contributor resource request boundary",()=>{
 it("rejects unsigned requests without touching the resource store",async()=>{mocks.identity.mockResolvedValue(null);const r=await handleContributorResourceGet(request("GET"),fixtureResource.id);expect(r.status).toBe(401);expect(r.headers.get("cache-control")).toBe("no-store");expect(mocks.factory).not.toHaveBeenCalled();});
 it("rejects cross-origin edits and unexpected actor/activation fields",async()=>{expect((await handleContributorResourceDraft(request("PATCH",draftInput,true),fixtureResource.id)).status).toBe(403);expect((await handleContributorResourceDraft(request("PATCH",{...draftInput,actorId:"owner"}),fixtureResource.id)).status).toBe(400);expect(mocks.factory).not.toHaveBeenCalled();});
 it("requires a current drafting grant and builds evidence on the server",async()=>{const r=await handleContributorResourceDraft(request("PATCH",draftInput),fixtureResource.id);expect(r.status).toBe(200);expect(mocks.principal).toHaveBeenCalledWith(expect.anything(),"one-dhs","content_contributor");expect(mocks.context).toHaveBeenCalledWith("test-session","resource_draft_save");const json=await r.json();expect(JSON.stringify(json)).not.toContain("test-session");});
 it("rejects a revoked grant before opening the store",async()=>{mocks.principal.mockResolvedValue(null);const r=await handleContributorResourceDraft(request("PATCH",draftInput),fixtureResource.id);expect(r.status).toBe(403);expect(mocks.factory).not.toHaveBeenCalled();});
 it("requires publishing authority for withdrawal and preserves containment operation",async()=>{const r=await handleContributorResourceAction(request("POST",{action:"withdraw",revisionId,expectedScopeDecisionId:"1",reason:"A correction is needed."}),fixtureResource.id);expect(r.status).toBe(200);expect(mocks.principal).toHaveBeenCalledWith(expect.anything(),"one-dhs","publishing_approver");expect(mocks.context).toHaveBeenCalledWith("test-session","resource_withdraw");});
 it("reports stale revisions and preserves an explicit failure status",async()=>{mocks.factory().save.mockRejectedValue(new ContributorResourceError(409,"Reopen the latest draft."));const r=await handleContributorResourceDraft(request("PATCH",draftInput),fixtureResource.id);expect(r.status).toBe(409);expect(await r.json()).toMatchObject({error:"Reopen the latest draft."});});
});
