import { createHash, randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createFileStoreForTests, resetStoreForTests } from "@/lib/intelligence/memory/store";
import { ProgramTaskSchema, type ProgramEvent } from "@/lib/program/work-schema";
import { programState } from "@/lib/program/work-state";
const directories:string[]=[];
afterEach(async()=>{for(const directory of directories.splice(0))await rm(directory,{recursive:true,force:true});});
const task=()=>ProgramTaskSchema.parse({recordType:"program_task",id:"task-"+randomUUID().replaceAll("-",""),createdAt:new Date().toISOString(),functionId:"resources",outcomeIds:["organizational_memory"],kind:"resource_review",title:"Review resource availability",objective:"Review currently published resource metadata.",agentId:"librarian",dueAt:new Date().toISOString(),eligible:true,source:"owner",evidenceMode:"verification"});
function event(id:string,phase:ProgramEvent["phase"],attempt=1,at=Date.now()):ProgramEvent{
  const body="A concrete saved resource inventory with actual findings.";
  return {recordType:"program_event",id:randomUUID(),taskId:id,at:new Date(at).toISOString(),phase,attempt,actor:["started","completed","failed"].includes(phase)?"agent":"owner",note:"Synthetic lifecycle check.",...(phase==="completed"?{receipt:{title:"Resource review",body,evidenceLevel:"delivery" as const,method:"program_record_review" as const,references:[],contentHash:createHash("sha256").update(body).digest("hex")}}:{})};
}
for(const backend of ["memory","file"] as const)describe(backend+" program ledger",()=>{
 async function setup(){const directory=await mkdtemp(path.join(tmpdir(),"pac-program-ledger-"));directories.push(directory);const a=backend==="memory"?resetStoreForTests():createFileStoreForTests(directory),b=backend==="memory"?a:createFileStoreForTests(directory),record=task();await a.put("decision","program_task:"+record.id,record);return {a,b,record};}
 it("admits one concurrent start across independent callers",async()=>{const {a,b,record}=await setup(),at=Date.now();const results=await Promise.all(Array.from({length:12},(_,i)=>(i%2?a:b).appendProgramEvent(record.id,null,event(record.id,"started",1,at+i))));expect(results.filter(r=>r.applied)).toHaveLength(1);expect((await a.list<ProgramEvent>("decision")).filter(e=>e.recordType==="program_event")).toHaveLength(1);});
 it("keeps cancellation authoritative over late completion and permits an explicit retry",async()=>{const {a,b,record}=await setup(),at=Date.now(),start=event(record.id,"started",1,at);expect((await a.appendProgramEvent(record.id,null,start)).applied).toBe(true);const stop=event(record.id,"cancelled",1,at+1);expect((await b.appendProgramEvent(record.id,start.id,stop)).applied).toBe(true);expect((await a.appendProgramEvent(record.id,start.id,event(record.id,"completed",1,at+2))).applied).toBe(false);expect((await a.appendProgramEvent(record.id,stop.id,event(record.id,"completed",1,at+2))).applied).toBe(false);const retry=event(record.id,"retry_requested",1,at+3);expect((await a.appendProgramEvent(record.id,stop.id,retry)).applied).toBe(true);expect((await a.appendProgramEvent(record.id,retry.id,event(record.id,"started",2,at+4))).applied).toBe(true);});
 it("replays the same immutable event but rejects changed content and direct rewrite",async()=>{const {a,record}=await setup(),start=event(record.id,"started");expect((await a.appendProgramEvent(record.id,null,start)).applied).toBe(true);expect((await a.appendProgramEvent(record.id,null,start)).applied).toBe(true);expect((await a.appendProgramEvent(record.id,null,{...start,note:"Changed duplicate"})).applied).toBe(false);await expect(a.put("decision","program_event:"+start.id,{...start,note:"Rewrite"})).rejects.toThrow();await expect(a.put("decision","program_task:"+record.id,{...record,title:"Changed task"})).rejects.toThrow();});
 it("rejects receipt corruption and does not attach an old result to a new attempt",async()=>{const {a,record}=await setup(),at=Date.now(),start=event(record.id,"started",1,at);await a.appendProgramEvent(record.id,null,start);const bad=event(record.id,"completed",1,at+1);bad.receipt!.contentHash="0".repeat(64);expect((await a.appendProgramEvent(record.id,start.id,bad)).applied).toBe(false);const done=event(record.id,"completed",1,at+2);expect((await a.appendProgramEvent(record.id,start.id,done)).applied).toBe(true);const retry=event(record.id,"retry_requested",1,at+3);await a.appendProgramEvent(record.id,done.id,retry);const records=await a.list<ProgramEvent>("decision");const state=programState(record,records.filter(e=>e.recordType==="program_event"));expect(state.status).toBe("retry_requested");expect(state.receipt).toBeUndefined();expect(state.events.find(e=>e.id===done.id)?.receipt).toEqual(done.receipt);});
 it("will not duplicate a running attempt or skip its attempt number",async()=>{const {a,record}=await setup(),at=Date.now(),start=event(record.id,"started",1,at);await a.appendProgramEvent(record.id,null,start);expect((await a.appendProgramEvent(record.id,start.id,event(record.id,"started",2,at+1))).applied).toBe(false);const recovery=event(record.id,"started",2,at+600001);expect((await a.appendProgramEvent(record.id,start.id,recovery)).applied).toBe(true);expect((await a.appendProgramEvent(record.id,recovery.id,event(record.id,"completed",1,at+600002))).applied).toBe(false);});
});
