import { createHash, randomUUID } from "node:crypto";
import { mkdtemp, rm, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import * as stores from "@/lib/intelligence/memory/store";
import * as providers from "@/lib/intelligence/providers";
import { getModel } from "@/lib/intelligence/registry/models";
import { invalidatePolicyCache, setPolicy } from "@/lib/intelligence/policy";
import { createProgramTask, listProgramWork, prepareProgramFollowups, recordProgramDecision, runProgramWork, summarizeProgramWork } from "@/lib/program/work";
import { programFunctions } from "@/lib/program/model";
const directories:string[]=[];
beforeEach(async()=>{stores.resetStoreForTests();invalidatePolicyCache();await setPolicy({max_autonomy:"A5",flags:{"agent.content_sentinel":true}});});
afterEach(async()=>{vi.restoreAllMocks();for(const directory of directories.splice(0))await rm(directory,{recursive:true,force:true});});
function input(functionId="resources",kind:"work_preparation"|"resource_review"="work_preparation"){return {functionId,kind,title:"Prepare an accessible meeting",objective:"Prepare a useful agenda and evidence check for an accessible meeting.",dueAt:new Date().toISOString(),eligible:true,source:"owner" as const,evidenceMode:"verification" as const};}
function connected(complete:()=>Promise<unknown>){vi.spyOn(providers,"resolveBinding").mockReturnValue({model:getModel("mdl_claude_staff_primary")!,generative:true,reason:"synthetic provider control",adapter:{id:"anthropic",generative:true,health:async()=>({ok:true,latency_ms:0}),complete:async()=>({parsed:await complete(),model_id:"mdl_claude_staff_primary"})}});}
it("records provider unavailability as unfinished, with no invented artifact",async()=>{await createProgramTask(input());const result=await runProgramWork();expect(result.completed).toHaveLength(0);expect(result.failed).toHaveLength(1);const [work]=await listProgramWork();expect(work.status).toBe("failed");expect(work.receipt).toBeUndefined();expect(work.events.at(-1)?.note).toContain("provider is unavailable");});
it("does not allow a late provider result to overwrite an owner stop",async()=>{let finish!:(value:unknown)=>void;let entered!:()=>void;const started=new Promise<void>(r=>{entered=r;});connected(()=>{entered();return new Promise(r=>{finish=r;});});await createProgramTask(input());const running=runProgramWork();await started;const [active]=await listProgramWork();await recordProgramDecision(active.id,{phase:"cancelled",note:"Stop this preparation while the situation is reconsidered.",expectedEventId:active.lastEventId});finish({title:"Prepared meeting",body:"An accessible meeting agenda with clear purpose, participant access needs, preparation, an evidence check, and a practical follow-up."});expect((await running).completed).toHaveLength(0);const [stopped]=await listProgramWork();expect(stopped.status).toBe("cancelled");expect(stopped.receipt).toBeUndefined();expect(stopped.events.filter(e=>e.phase==="completed")).toHaveLength(0);});
it("honors a specialist pause before recording a generated completion",async()=>{connected(async()=>{await setPolicy({agents:{librarian:{enabled:false}}});return {title:"Prepared meeting",body:"An accessible meeting agenda with clear purpose, participant access needs, preparation, an evidence check, and a practical follow-up."};});await createProgramTask(input());expect((await runProgramWork()).completed).toHaveLength(0);expect((await listProgramWork())[0].status).toBe("failed");});
it("does not persist arbitrary provider exception details",async()=>{connected(async()=>{throw new Error("provider secret-value-and-request-text");});await createProgramTask(input());await runProgramWork();expect(JSON.stringify(await listProgramWork())).not.toContain("secret-value");});
it("creates one follow-up from an explicit observation without preparing a portfolio",async()=>{const task=await createProgramTask(input("resources","resource_review"));expect((await runProgramWork()).completed).toContain(task.id);const [work]=await listProgramWork();await recordProgramDecision(task.id,{phase:"reviewed",note:"Review the resource findings and return to the access gaps.",followUpAt:new Date(Date.now()-1000).toISOString(),disposition:"revise",expectedEventId:work.lastEventId});await prepareProgramFollowups();await prepareProgramFollowups();const all=await listProgramWork();expect(all).toHaveLength(2);expect(all.filter(t=>t.sourceId===task.id)).toHaveLength(1);});
it("excludes later events from a historical summary and excludes verification work",async()=>{await createProgramTask({...input("resources","resource_review"),evidenceMode:"operational"});const cutoff=new Date().toISOString();await new Promise(r=>setTimeout(r,5));await runProgramWork();const all=await listProgramWork();expect(summarizeProgramWork(all,undefined,cutoff).completed).toBe(0);expect(summarizeProgramWork(all).completed).toBe(1);expect(summarizeProgramWork(all.map(t=>({...t,evidenceMode:"verification"}))).eligible).toBe(0);});
it("executes and reopens actual published-resource review receipts for all 13 areas through local persistent storage",async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),"pac-program-actual-reviews-"));directories.push(directory);const store=stores.createFileStoreForTests(directory);vi.spyOn(stores,"getStore").mockReturnValue(store);invalidatePolicyCache();await setPolicy({max_autonomy:"A5",flags:{"agent.content_sentinel":true}});
 for(const fn of programFunctions)await createProgramTask({...input(fn.id,"resource_review"),title:fn.title+": published resource review",objective:"Inspect the actual scoped published resources in this area and record concrete findings."},randomUUID());
 for(let i=0;i<4;i++)expect((await runProgramWork({limit:4})).failed).toEqual([]);
 const reopened=stores.createFileStoreForTests(directory);vi.mocked(stores.getStore).mockReturnValue(reopened);
 const work=await listProgramWork();expect(work).toHaveLength(13);expect(work.every(t=>t.status==="completed"&&t.receipt?.method==="program_record_review")).toBe(true);
 for(const task of work){expect(task.receipt!.body).toContain("published resources matched");expect(createHash("sha256").update(task.receipt!.body).digest("hex")).toBe(task.receipt!.contentHash);}
 expect(summarizeProgramWork(work).eligible).toBe(0);
 await mkdir("evidence/functional-completion-2026-09-08",{recursive:true});
 await writeFile("evidence/functional-completion-2026-09-08/program-area-task-receipts.json",JSON.stringify({checkedAt:new Date().toISOString(),environment:"isolated local file store, reopened through a second instance",execution:"Actual published-resource metadata/reading inventory computation; no model requests, staff submissions or institutional outcomes",evidenceMode:"verification; excluded from operational autonomy metrics",areas:work.length,records:work},null,2));
},20000);
