import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Complex systems · Module 24: Religion, spirituality, and cultural practice.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-24-religion-spirituality-practice",
    indexNumber: 1166,
    seriesLabel: "Intercultural Practice and Equity · Complex systems",
    title: "Religion, Spirituality, and Cultural Practice",
    subtitle: "A date, a room, a tray of sandwiches and a line on a form all carry assumptions about belief and practice. Four lessons on where those assumptions quietly decide who can take part, ending with an inclusion check you add to your own event and engagement planning.",
    scope: "For internal DHS and DSD staff who schedule, host, write, design or evaluate anything other people are expected to attend or answer: communications, training and learning-design staff, policy and program staff, operations, quality, community engagement, data, contracts and grants staff, administrative and support staff, supervisors and managers. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. This module never asks you to describe, defend or disclose your own beliefs, practice or background. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota examples, scenarios, sorting and flashcard practice, private reflection prompts, and an inclusion check you can copy straight into your own event and engagement planning",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/facilitators-guide.jpg",
    coverAlt: "A man facilitates a small training room at a whiteboard.",
    introTranscript: "Most of the decisions that determine who can take part in a public process are made before anyone is invited. Someone picks a date because it fits an internal sign-off. Someone books a room because it was available. Someone orders sandwiches because that is what the last event had. Someone keeps a line on a form because it has always been there. None of those choices feels like a decision about religion, spirituality or cultural practice, and every one of them is. This module looks at the calendar, the room, the table and the form in turn, then gives you a six-line inclusion check you can run on the next thing you host, in about twenty minutes, before the invitation goes out.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Identify the scheduling decisions in your own work that decide who can take part, before anyone is invited.",
        "Plan food, rooms and hospitality so that taking part does not require a person to explain, decline or go without.",
        "Tell erasure and intrusion apart in a form, script or service plan, and write a participation question in place of both.",
        "Explain why an identical process can produce unequal participation, and name who absorbs the difference.",
        "Complete an inclusion check for one real event or engagement, change what is inside your own control, and take what is not to its named owner with a specific ask.",
      ],
      evidence: [
        "Four worked scenarios drawn from a public comment period, a community engagement event, an assessment form and a regional session, each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates a fact you can check from a decision the division owns, and erasure from intrusion from a useful question.",
        "A completed inclusion check for one real event or engagement, kept with the event plan rather than in a personal file.",
      ],
      appliedNextStep: "Take the next thing you are scheduling or hosting, run the six-line inclusion check before the invitation goes out, make the changes inside your own control, and take anything that is not yours to its named owner with one specific ask.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in the Minnesota Human Rights Act, or in Minnesota Department of Human Rights guidance, affecting religion and creed as protected classes in public services and public accommodations",
        "A change in federal civil rights guidance from the U.S. Department of Justice or the U.S. Department of Health and Human Services affecting national origin, language access or religious exercise in federally assisted programs",
        "A change in DHS or DSD public engagement, meeting, notice or procurement practice that alters how sessions are scheduled, hosted or catered",
        "Feedback from paid community advisors, disabled Minnesotans or culturally specific organizations that an example here does not match how a gathering or a process actually goes",
      ],
      relatedDoor: "Formal decisions about civil rights complaints, religious accommodation in employment, contract and grant terms with community and congregational partners, official public notice requirements, and what may be recorded in a service record belong to the responsible DHS human resources, civil rights, contracting, communications and legal offices; this module prepares the plan and the ask, it does not decide a request or set a record rule.",
      toolkitQuestion: "Before the invitation goes out, who has already been ruled out by the date, the room, the table or the form, and what would it take to find that out from them rather than about them?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-24-1",
        number: 1,
        title: "What the calendar already decided",
        summary: "A date and a time are the first access decision in any public process, and they are usually made for internal reasons by someone who never thought of them that way.",
        minutes: 11,
        learning: {
          objective: "Identify the scheduling decisions in your own work — the date, the hour, the deadline and the recurrence — that decide who can take part before a single invitation goes out.",
          takeaways: [
            "A working calendar is not neutral. The standard week, the meeting hour, the comment window and the recurring monthly slot all carry assumptions about when people are free, and those assumptions came from somewhere specific.",
            "Some observances move through the year because they follow a lunar calendar, so a date that was clear last time sits inside a month of daily fasting the next time. A recurring annual slot cannot be checked once and then left alone.",
            "The cost of a poor date is not spread evenly. A person who can attend the alternate session, submit in writing and follow up by phone loses very little. A person for whom that session was the only accessible way in loses the whole thing.",
            "Adding a second real way to take part is almost always cheaper than moving an event, and it reaches far more people than the ones you had in mind — disabled Minnesotans, shift workers, people without evening transportation and family caregivers among them.",
          ],
          evidence: "A scenario about a public comment window and a session schedule, sorting practice that separates a fact you can check from a decision the division owns, and a knowledge check on what to do when the date genuinely cannot move.",
          appliedNextStep: "Take the next thing you are scheduling — a session, a comment deadline, a survey window, a recurring workgroup — and before the date is announced, check it against a published multi-faith calendar and add one other way to take part that carries the same weight as the room.",
        },
        scenario: {
          context: "A DSD policy unit is opening a public comment period on a change to a service definition. The engagement plan sets a four-week window built backwards from an internal sign-off date, with three evening listening sessions, all on the same weekday, and one web form that closes at midnight on the final day. A colleague in community engagement points out two things: the window falls almost entirely inside a month-long period of daily fasting observed by a large number of Minnesotans, and the chosen weekday evening is when several communities hold weekly worship.",
          prompt: "The internal sign-off date is genuinely difficult to move. What is the strongest response?",
          options: [
            { label: "Keep the plan as it stands. The window is open to everyone on the same terms, the sessions are in the evening, and anyone who cannot attend can use the web form.", response: "Identical access is the argument, and it is Minimization in its most ordinary public-administration form: the route is the same for everyone, so the effects are assumed to be the same. They are not. The people this window works worst for are the ones with the least slack to absorb it, and the comment file will later be read as though it represented everyone." },
            { label: "Hold the window, and change what sits inside it: move one session to a different weekday and hour, give a phone route and a written route the same weight as the sessions, extend the close for written comment by a week, and ask two community organizations, paid for their time, which dates actually work before the next round.", response: "This treats the date as one variable among several rather than as the whole plan. The sign-off holds, the ways in multiply, and the next cycle starts from what communities actually said instead of from the internal calendar again. It also produces a comment file you can describe honestly.", recommended: true },
            { label: "Cancel the live sessions and run the comment period entirely in writing, so that no date can exclude anyone.", response: "Removing the sessions removes a barrier for some people and builds one for others: people who think out loud, people who do not write in English, people who use an interpreter, and people who will not fill in a government form but will come to a room and say what they think. Fewer ways in is rarely the fix." },
          ],
        },
        transfer: {
          prompt: "What is the next thing you will put on a calendar that other people have to show up for?",
          options: [
            "Name the date, and the two calendars you will check before it is announced",
            "Name the second way to take part that will carry the same weight as the room",
            "Name who you will ask about dates next time, and how their time will be paid",
          ],
        },
        blocks: [
          { type: "text", heading: "The working week is a design decision", body: "<p>Almost nobody sets a date thinking about religion. A session lands on a Friday afternoon because the room was free. A comment window closes on the last day of the month because that is when the report is due. A workgroup meets the third Wednesday at noon because it always has. Each of those is a reasonable operational choice, and together they form a calendar that treats one pattern of life as the default and everything else as a conflict to be reported.</p><p>The patterns that pull against that default are ordinary and widespread. A weekly day of rest or worship that begins at sundown the evening before. A daily prayer schedule that includes the middle of the afternoon. A month of fasting from dawn to sunset that changes people's energy, mealtimes and evenings. Dietary practices that require particular preparation. Mourning practices that keep a family at home for a set number of days. Pilgrimage that takes someone out of the state for two weeks. Minnesota has substantial Muslim, Christian, Jewish, Hindu, Buddhist and Sikh communities, along with many people who hold no religion at all and many for whom spirituality is a private practice with no congregation attached.</p><p>The practical problem is not that any of this is complicated. It is that the check happens too late. By the time a date reaches an invitation it has a room, a sign-off, a printed agenda and a line in someone else's calendar, and moving it becomes a favor rather than a design decision. Checking a date takes about four minutes. Almost every accessible-date problem in public engagement is a sequencing problem, not a values problem.</p>" },
          { type: "tabs", heading: "Four scheduling decisions, and what each one assumes", tabs: [
            { label: "The date", body: "<p>A single date assumes that everyone's obligations fall on the same days, and that anyone with a conflict will say so. Most people will not tell a government agency why they cannot come. Published multi-faith calendars solve most of this in minutes, and they are the reason a date should be checked while it is still a draft.</p>" },
            { label: "The hour", body: "<p>Late afternoon and early evening are the two hours that collide most often: with daily prayer, with the start of a day of rest at sundown, with breaking a fast, with the end of a school day and with the last accessible bus. An hour is usually easier to move than a date, and moving it costs almost nothing.</p>" },
            { label: "The deadline", body: "<p>A deadline is a schedule too. A comment period, an application window, a renewal date or a survey close that lands inside a fasting month, a mourning period or a major observance quietly reduces who is represented in the result — and the result is then used as evidence of what the public thinks.</p>" },
            { label: "The recurrence", body: "<p>A standing meeting or an annual event inherits the first decision forever. Observances that follow a lunar calendar move about eleven days each year, so a recurring slot that was clear one year sits in the middle of an observance a few years later. Recurring dates need a check on a cycle, not once at the start.</p>" },
          ] },
          { type: "list", heading: "What to check before a date becomes an announcement", items: [
            "The date and the two days around it, against a published multi-faith calendar and a school calendar.",
            "The hour, against late-afternoon prayer, sundown, the end of the school day and the last accessible transit run.",
            "Whether the period covers a month of daily fasting, and if it does, what that means for an evening event with food.",
            "Whether the deadline, not only the event, falls inside an observance — the deadline is the part people cannot negotiate.",
            "Whether a recurring slot has drifted into an observance since the last time anyone looked.",
            "Whether there is a second real way to take part for anyone the date still excludes, with the same weight as the room.",
          ] },
          { type: "sorting", id: "ipe-24-1-sort", heading: "Fact you can check, decision you own, or assumption to drop?", categories: ["A fact you can check", "A decision the division owns", "An assumption worth dropping"], items: [
            { text: "Several widely observed periods of fasting and celebration move through the calendar year because they follow a lunar calendar.", category: "A fact you can check" },
            { text: "The listening sessions are all on the same weekday at the same hour.", category: "A decision the division owns" },
            { text: "If the date were a problem for anyone, someone would have told us during registration.", category: "An assumption worth dropping" },
            { text: "The comment window closes at midnight on a fixed day, with no written extension available.", category: "A decision the division owns" },
            { text: "A weekly day of rest observed by some Minnesotans begins at sundown on the preceding evening rather than at midnight.", category: "A fact you can check" },
            { text: "People who really care about the change will find a way to attend whatever the date.", category: "An assumption worth dropping" },
          ] },
          { type: "leaderMove", heading: "Add a way in before you defend a date", control: "You control the order in which a date is decided and checked, the hour, the length of a written window, and whether a phone or written route carries the same weight as the room.", failure: "Do not answer a date objection by explaining why the date cannot move. The objection is not really about the date; it is about whether there is any way in for the people the date rules out.", next: "On the next thing you schedule, check the date while it is still a draft, and write the second way to take part into the plan before the first invitation is drafted." },
          { type: "quote", text: "I told them I could not come to the Friday sessions. They were very apologetic and said the dates were already set. What I wanted was not an apology. I wanted the same half hour with the same people, on a different day, and for my comments to land in the same file as everyone else's.", cite: "Composite community advisor perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-24-1-check", question: "A required public comment window is fixed by a statutory timeline and cannot be moved. It overlaps a month of daily fasting for a large group of Minnesotans. Which response is best supported?", options: [
            { text: "Note the overlap in the engagement record and proceed as planned; the timeline is set in law and nothing else can change.", correct: false },
            { text: "Hold the window as required, and change what is inside it: add a session at a different hour, give written and phone routes the same weight, keep written comment open to the last permitted moment, and say plainly in the notice that all three routes count the same.", correct: true },
            { text: "Ask community organizations to encourage their members to comment early, before the fasting period begins.", correct: false },
            { text: "Run the sessions as scheduled and follow up afterward with anyone who says they were unable to attend.", correct: false },
          ], feedbackCorrect: "Yes. A fixed outer window still leaves the hour, the formats, the weight given to each route and the wording of the notice entirely inside the division's control.", feedbackIncorrect: "A statutory window fixes the dates, not the design. Ask what is still yours to change inside it — the hour, the number of routes in, and whether written and phone comment are treated as equal to the room." },
          { type: "statement", body: "Private reflection, for you only: think of a date you set recently that other people had to work around. Who could have been helped, burdened, excluded or misunderstood by that timing, and how would you have found out? Nothing you write here is collected, stored or seen by anyone." },
        ],
      },
      {
        id: "ipe-24-2",
        number: 2,
        title: "Food, rooms and what hospitality says",
        summary: "The table is the most visible statement an event makes about who was expected. So is the room, the reception and whether there is anywhere to step out to.",
        minutes: 10,
        learning: {
          objective: "Plan the food, the room and the hospitality of a gathering so that taking part does not require anyone to explain a practice, decline a meal or go without.",
          takeaways: [
            "Food is not a detail of an event. It is the point where dietary practice, disability, health, allergy and household budget all meet the same table, and it tells everyone in the room who the host was picturing.",
            "A single default plus a request line moves the burden onto the person: they must name a practice or a condition to a government agency, in advance, in writing, to receive what everyone else is getting without asking. A plan with real choices built in asks nothing of anyone.",
            "The room carries the same message as the table. Whether there is a quiet space to step out to, whether that space can actually be reached by someone using a wheelchair, whether seating can be rearranged, whether alcohol is present and whether the air is heavy with scent all decide who can stay for the whole thing.",
            "Labeling is access. An unlabeled tray is equally unusable for a person keeping a dietary practice, a person with a severe allergy and a person counting carbohydrates. One clear card in front of each dish serves all three without a single conversation.",
          ],
          evidence: "A scenario about catering and room setup for a community engagement event, flashcards you can use while planning, and a knowledge check on building a choice in rather than processing a request.",
          appliedNextStep: "For the next gathering you help host, label every dish by ingredient, add clearly marked options that meet common dietary practices and common allergy needs, confirm a quiet room that can actually be reached, and replace the dietary-restriction question with an open line about what would help a person take part fully.",
        },
        scenario: {
          context: "You are helping plan a half-day community engagement event about how a DSD program is working. About sixty people are expected: disabled Minnesotans, family members, paid community advisors, provider staff and division staff. The event runs from late morning into mid-afternoon, so lunch is included. The draft plan orders sandwich trays and a coffee service, uses one large room with round tables set for eight, and adds a line to the registration form reading, “Please tell us about any dietary restrictions.”",
          prompt: "Which change would do the most for the most people?",
          options: [
            { label: "Keep the plan and make sure someone personally follows up on every dietary restriction listed on the registration form.", response: "This is conscientious, and it leaves the burden exactly where it started. A person has to name a practice or a health condition to a government agency, in advance, in writing, in order to have lunch. Anyone who registers late, arrives with a support person, or simply does not want to explain gets nothing — and the follow-up depends on one staff member remembering." },
            { label: "Build the choice into the default: label every dish by ingredient, include clearly marked options that meet common dietary practices and common allergy needs, keep the food simple, confirm a quiet room that can genuinely be reached and used for prayer, rest or stepping out, and replace the restriction question with an open line about what would help you take part fully.", response: "This removes the disclosure, serves several groups with the same decision, and treats a labeled tray and a quiet room as ordinary parts of hosting rather than as accommodations granted on request. It is also less work on the day, because nothing depends on a list.", recommended: true },
            { label: "Drop the catering, shorten the event to two hours, and avoid the question entirely.", response: "This solves the food problem by removing the hospitality, and it usually cuts the part of the day where people actually talk to one another. It also pushes out anyone who traveled a long way. For many communities a shared meal is part of what makes a gathering real rather than a hearing." },
          ],
        },
        transfer: {
          prompt: "Think about the last gathering you helped host.",
          options: [
            "Name what was on the table, and who could eat from it without asking anyone a question",
            "Name where a person could have gone to pray, rest, take medication, nurse a child or use a communication device away from the noise",
            "Name the one line on your registration form you would rewrite before the next one",
          ],
        },
        blocks: [
          { type: "text", heading: "What the table says before anyone speaks", body: "<p>Hospitality is read instantly. A person walks into a room, looks at the table, and knows within a few seconds whether the people who planned this had anyone like them in mind. That reading happens before the welcome, before the agenda and long before the part of the day where you ask for their honest view of a program.</p><p>The most common arrangement in public-sector events is one default plus a request line: sandwiches for everyone, and a box on the form for restrictions. It feels fair and it is not. It asks some people to disclose a practice, a health condition or a religious obligation in writing, to a government agency, weeks ahead, to receive what everyone else receives by walking in. It fails anyone who registers late. It fails anyone who brings a support person. It depends entirely on whoever collected the forms passing them to whoever ordered the food. And it turns an ordinary part of hosting into a favor.</p><p>The alternative is not more expensive and it is usually less work. Label everything by ingredient. Include several clearly marked options that meet common dietary practices and the common allergy needs at the same time. Keep the food simple enough that the labels are honest. Then ask one open question instead of a restriction question, and give it a named person and a reply date. The move from “tell us your restriction so we can make an exception” to “here is a table you can use” is the difference between Minimization and Adaptation in a form anyone can see.</p>" },
          { type: "accordion", heading: "Five parts of hosting that quietly decide who can stay", items: [
            { title: "The food itself", body: "<p>Several clearly marked options, chosen so that one plate works for more than one practice and more than one allergy, beat a single default with exceptions attached. Vegetarian and plant-based dishes, prepared and served separately from meat, cover a great deal of ground at once. Ask a caterer how items are prepared and kept apart, not only what is in them.</p>" },
            { title: "The labeling", body: "<p>A card in front of each dish naming the main ingredients is the single highest-value thing you can do, and it costs nothing. It works for dietary practice, for allergy, for diabetes and for anyone who simply wants to know. Print it large, in plain words, with good contrast, so it can be read from a seated position.</p>" },
            { title: "The timing of the meal", body: "<p>During a month of daily fasting, a midday lunch is not neutral and an evening event may sit right across the moment a fast is broken. Options that hold up as a takeaway plate, a meal break at a time people can actually eat, or a session that simply does not center on food all work better than an apology later.</p>" },
            { title: "The quiet room", body: "<p>One clean, private, reachable room with a chair and a door serves prayer, rest, medication, a panic attack, a nursing parent, a person recovering from a migraine and someone who needs ten minutes away from noise. Confirm that it can be reached without stairs, name it on the agenda, and do not require anyone to ask for the key.</p>" },
            { title: "The reception and the room shape", body: "<p>Alcohol at a reception changes who feels welcome and who leaves early. So does a room of standing-height tables, heavy scent, background music under conversation, or fixed seating that cannot be rearranged for a wheelchair, an interpreter or a person who needs to sit with their back to a wall. Ask what the room requires of a body before you book it.</p>" },
          ] },
          { type: "flashcards", heading: "Keep these in reach while you plan", cards: [
            { front: "Default plus request line", back: "<p>One standard option with a box for exceptions. Puts the burden on the person to disclose in advance, fails late registrations, and depends on one staff member's memory. Replace it.</p>" },
            { front: "Choice built into the default", back: "<p>Several clearly marked options that work for several practices and allergies at once. Nobody has to explain anything, and nothing depends on a list.</p>" },
            { front: "Labeling", back: "<p>A large, plain, high-contrast card naming the main ingredients in front of every dish. The cheapest access improvement available at any event.</p>" },
            { front: "The quiet room", back: "<p>Private, clean, reachable without stairs, named on the agenda, no key request required. Serves prayer, rest, medication, sensory overload and nursing parents with one decision.</p>" },
            { front: "The open line", back: "<p>“Tell us what would help you take part fully,” with a named person and a date they will reply by. Replaces the restriction question and catches needs you never thought to list.</p>" },
          ] },
          { type: "leaderMove", heading: "Build the choice in; do not process the request", control: "You control the menu, the labels, the room, the agenda and the wording of the registration form. All four are decided before anyone is asked to disclose anything.", failure: "Do not build a plan that works only if the right person reads the right box on the right form in time. That design fails quietly, and it fails the people who were least able to ask in the first place.", next: "On the next event you touch, replace the dietary-restriction question with an open participation question, and make the change to the menu and the room before that form goes out." },
          { type: "quote", text: "I stopped writing anything in the dietary box years ago. It is a small thing to go without lunch, and it is a smaller thing than explaining my religion to a state agency so that someone can decide whether to order me a separate plate. The day they just put cards in front of the food, I ate with everyone else and nobody knew anything about me.", cite: "Composite community advisor perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-24-2-check", question: "A regional session includes a working lunch. The planner wants to make it work for everyone without asking people to disclose anything. Which plan does that best?", options: [
            { text: "Order one standard meal and add a prominent dietary-restriction field to the registration form, with a reminder email two weeks out.", correct: false },
            { text: "Order several clearly labeled options chosen to meet common dietary practices and common allergy needs together, label every dish by ingredient, confirm a reachable quiet room, and replace the restriction field with an open line about what would help a person take part fully.", correct: true },
            { text: "Ask attendees to bring their own lunch so that everyone is certain of what they are eating.", correct: false },
            { text: "Order a vegetarian meal for everyone, since that avoids the largest number of restrictions at once.", correct: false },
          ], feedbackCorrect: "Yes. Labeled choices remove the disclosure entirely, cover several practices and several allergy needs with one decision, and do not depend on anyone having read a form.", feedbackIncorrect: "Ask which plan requires a person to tell a government agency something private in order to have lunch. A single default — even a thoughtful one — still leaves people explaining themselves, and a bring-your-own instruction quietly excludes anyone who traveled or cannot afford it." },
          { type: "statement", body: "Private reflection, for you only: at a gathering you hosted or attended, what did the room and the table assume about the people coming? Whose expertise about hospitality was missing from that planning conversation? Nothing you write here is collected, stored or seen by anyone." },
        ],
      },
      {
        id: "ipe-24-3",
        number: 3,
        title: "What the form and the service plan assume",
        summary: "Two opposite failures produce the same result: never asking, so a practice that organizes someone's week never reaches the plan, and asking with no purpose, so a person explains their belief to an agency that will do nothing with it.",
        minutes: 10,
        learning: {
          objective: "Tell erasure and intrusion apart in a form, script, communication plan or service plan, and write a participation question that replaces both, with a stated purpose, use and record rule.",
          takeaways: [
            "Erasure is never asking, so a weekly obligation, a dietary practice or a mourning period never reaches a plan that could have supported it. Intrusion is asking with no purpose, no use and no record rule, so a person explains a belief to a government agency that will do nothing with it and may share it widely.",
            "Between them sits the useful question, and it is about participation rather than belief: what regular practices, observances or needs matter to you here, and what would it take for this plan to support them?",
            "Any question you keep needs three sentences behind it: why it is asked, what will change because of the answer, and who will see it. A question that fails any of the three should be cut, not reworded.",
            "Program design carries quiet assumptions worth checking: that natural supports means family, that community means secular community, that a week holds no fixed obligations, that a person in a congregate setting has no way to keep a practice, and that a disabled adult has no spiritual life of their own to be consulted about.",
          ],
          evidence: "A scenario about revising an assessment question, sorting practice separating erasure from intrusion from a useful question, and a knowledge check on purpose, use and record rule.",
          appliedNextStep: "Take one form, script, template or plan you work with, find the question that asks about identity but changes nothing, and rewrite it as a participation question with a stated purpose, a stated use and one plain line about who will see the answer.",
        },
        scenario: {
          context: "A DSD program unit is revising an assessment form used in person-centered planning. The current form carries one line: “Religious preference: ______.” It is filled in about a third of the time, nothing downstream uses it, and it sits in a record shared with several parties. A workgroup proposes deleting the line. A staff member objects: a person she supported missed her weekly service for two years because nobody ever asked how she got there, and a dietary practice was left out of a residential plan for the same reason.",
          prompt: "What should the revised form do?",
          options: [
            { label: "Delete the line. Belief is private, the field is not used by anything, and a public agency should not be collecting it.", response: "The privacy instinct is right about that field and wrong about the need. Deleting the label protects the record and leaves the person who missed two years of weekly service exactly where she was. The problem was never the label; it was that nobody asked a question the plan could act on." },
            { label: "Keep the line and add guidance telling staff to ask about religion during the planning conversation.", response: "This keeps a category label that nothing uses and adds a general instruction to ask about belief. It raises the intrusion without producing anything a plan can carry out, and it puts staff in the position of asking a question they cannot explain the purpose of." },
            { label: "Replace the label with a participation question — what regular practices, observances, gatherings or dietary needs matter to you, and what would it take for this plan to support them — record only what the plan will act on, and say on the form who sees the answer and why.", response: "This is the usable version. It asks about participation rather than belief, it produces something a plan can actually do, it limits what enters the record to what will be acted on, and it tells the person up front where the answer goes. It also serves people with no religion at all, whose weekly commitments are just as real.", recommended: true },
          ],
        },
        transfer: {
          prompt: "Take one form, assessment, script or template you work with.",
          options: [
            "Name the question that asks about identity and changes nothing downstream",
            "Rewrite one question so it asks about participation instead, and name exactly what the answer will change",
            "Write the one plain line that tells a person who will see the answer and why",
          ],
        },
        blocks: [
          { type: "text", heading: "Erasure and intrusion are the same failure wearing different clothes", body: "<p>Public systems tend to swing between two errors. The first is erasure: the subject never comes up, so a weekly obligation, a dietary practice, a mourning period or a spiritual community that is the person's main source of support never reaches the plan. Nobody made a decision to leave it out. The form had no place for it and the conversation had no time for it, and a person's week was organized around something the plan could not see.</p><p>The second is intrusion: a field labeled with a category, asked of everyone, used by nothing, and stored somewhere a person cannot see. Asking a Minnesotan to write their religion on a state form in order to receive a service carries real weight — more for people whose communities have been surveilled, questioned at borders or asked to account for themselves in public. The answer is not made safer by the fact that the field is optional or that the intentions behind it were good.</p><p>The way between them is to change the subject of the question from belief to participation. A plan does not need to know what a person believes. It needs to know what regularly happens in their week, what they want to keep doing, and what would have to change for that to be possible. That question is answerable by a person with a deep religious practice, by a person whose spirituality has no congregation attached, and by a person with no religion at all whose Thursday evening is nonetheless spoken for. And it produces something a plan can carry out, which is the only reason to ask a question in the first place.</p>" },
          { type: "tabs", heading: "The same subject, four ways", tabs: [
            { label: "Erasure", body: "<p>Nothing on the form, nothing in the conversation, nothing in the plan. A person stops attending a weekly gathering that was the main thing holding her week together, and the record shows only that transportation was arranged for medical appointments. No one decided this. That is what makes it hard to find.</p>" },
            { label: "Intrusion", body: "<p>“Religious preference: ______,” asked of everyone, used by nothing, shared with several parties. The person cannot tell what the answer will do, cannot see where it goes, and has no way to decline without wondering whether declining is itself noted.</p>" },
            { label: "A useful question", body: "<p>“Are there regular practices, observances, gatherings or dietary needs that matter to you, and what would it take for this plan to support them?” Answerable by anyone, including people with no religion. Produces specific, actionable items: a ride at a fixed time, a meal prepared a particular way, a day left clear.</p>" },
            { label: "What travels with the answer", body: "<p>Only what the plan will act on: the ride, the meal, the clear day, the name of a place. Not the belief behind it. Say on the form who sees the record and why, and keep the reason a person gave out of it unless they asked for it to be written down.</p>" },
          ] },
          { type: "sorting", id: "ipe-24-3-sort", heading: "Erasure, intrusion, or a useful question?", categories: ["Erasure", "Intrusion", "A useful question"], items: [
            { text: "A residential service plan lists meal preferences by likes and dislikes only, with no field for a dietary practice.", category: "Erasure" },
            { text: "A registration form asks every attendee to state their religion, and nothing in the event plan uses the answer.", category: "Intrusion" },
            { text: "A planning conversation asks which regular commitments a person wants the schedule to protect, and the answer changes the transport arrangement.", category: "A useful question" },
            { text: "An intake script asks a person to explain why they observe a dietary practice before a request is passed to the kitchen.", category: "Intrusion" },
            { text: "An engagement plan lists faith and cultural organizations only as places to leave flyers, with no line for their questions or their fee.", category: "Erasure" },
            { text: "A survey asks what would make it easier for you to attend, with a named contact and a reply date, and the answers change the next schedule.", category: "A useful question" },
          ] },
          { type: "list", heading: "Assumptions worth checking in a program design", items: [
            "That natural supports means family. For many people the steadiest support is a congregation, a cultural organization or a neighbor from one, and none of them appear in the plan.",
            "That community means secular community. A community partner list built only from providers and advocacy organizations misses where people actually get information and help.",
            "That a week holds no fixed obligations. Appointment scheduling, day-program hours, transport windows and staff rotas are all built as though every hour is equally available.",
            "That a person living in a congregate setting has no practice to keep. Getting to a weekly service, keeping a dietary practice or having a private half hour depends entirely on whether someone wrote it into the plan.",
            "That an adult with a disability has no spiritual life of their own to be consulted about — one of the oldest and most persistent assumptions in this field, and one that substitute decision-making can quietly entrench.",
            "That a congregation will help for free. Organizations that carry information, transport and trust into communities are partners with costs, and should be paid the way any other partner is paid.",
          ] },
          { type: "leaderMove", heading: "State the purpose, the use and the record rule", control: "You control whether a question survives into the next version of a form, and whether anyone can explain what it is for.", failure: "Do not keep a field because it has always been there, and do not delete a need because the field that was standing in for it was badly written. Those are two different decisions.", next: "Take the next form or script you revise, and for every identity question write three sentences: why it is asked, what changes because of the answer, and who sees it. Cut anything that fails one of the three." },
          { type: "knowledgeCheck", id: "ipe-24-3-check", question: "A program wants to know whether people can attend weekday appointments. Which question is most defensible on a public form?", options: [
            { text: "“What is your religion?” — so staff can look up relevant observances and avoid scheduling conflicts.", correct: false },
            { text: "“Do you have any religious restrictions on your availability?” — phrased neutrally and marked optional.", correct: false },
            { text: "“Which days and times are difficult for you, and is there anything we should know to make an appointment work?” — with a line stating who sees the answer and what it will change.", correct: true },
            { text: "No question at all; scheduling conflicts can be handled individually when they come up.", correct: false },
          ], feedbackCorrect: "Yes. It asks about participation rather than belief, it is answerable by everyone, it produces something the scheduler can act on, and it tells the person what happens to the answer.", feedbackIncorrect: "Check each option against purpose, use and record rule. Asking about religion — even optionally, even kindly — collects a belief the schedule does not need, while asking nothing leaves the conflict for the person to absorb." },
          { type: "statement", body: "Private reflection, for you only: in a form, script or plan you work with, does what you ask make sense to someone who does not already know how DHS works — and would they understand what happens to the answer? Nothing you write here is collected, stored or seen by anyone." },
        ],
      },
      {
        id: "ipe-24-4",
        number: 4,
        title: "Your inclusion check for events and engagement",
        summary: "Six lines you fill in before the invitation goes out, plus what to do with the parts of the plan that are not yours to change.",
        minutes: 11,
        learning: {
          objective: "Complete an inclusion check for one real event or engagement you are planning, naming the date check, the hosting decisions, the ways in, who shaped the plan, how they were paid and what happens afterward.",
          takeaways: [
            "Nearly all of the check has to happen before the invitation goes out. After that the date is public, the room is booked and the food is ordered, and every change becomes an exception someone has to request.",
            "Run the check with someone who does not share your blind spots, and pay community advisors for that time the same way you would pay any other reviewer. Reviewing a plan is work.",
            "Two lines matter more than the rest: an open participation line with a named person and a real reply date, and a message afterward telling everyone who came what happened to what they said.",
            "Fix what is inside your own control first, then take each remaining item to its named owner with one specific ask. A venue standard or a template line, changed once, works for every event after this one.",
            "The check belongs with the event plan, not in a personal file, so that whoever runs this event next inherits what you learned instead of starting from nothing.",
          ],
          evidence: "A completed inclusion check for a real event, a scenario about the parts of a plan you do not own, and a private reflection on accountability and repair.",
          appliedNextStep: "Fill the check in for the next thing you host or convene, make the changes inside your own control before the invitation goes out, take the items that are not yours to their named owners with a specific ask each, and keep the finished check with the event plan.",
        },
        scenario: {
          context: "You have filled in the check for a regional engagement session five weeks out. Most of it is yours to change. Two things are not. The venue was booked months ago by another unit: it has no quiet space and its only reachable restroom is on the far side of the building. And the statewide invitation template is owned by a central communications group; it has no access-and-participation line in it at all.",
          prompt: "What do you do with the two items that are not yours?",
          options: [
            { label: "Record both as constraints in the event plan and run the session as booked. You cannot fix another unit's decisions five weeks out.", response: "Recording a constraint is not the same as working it. Five weeks is enough to find and confirm a usable quiet space elsewhere in the same building, and enough to add one line to your own confirmation message. Neither of those needs anyone else's template or booking." },
            { label: "Work around both inside your own control now — confirm a quiet, reachable space in the same building and name it on the agenda, and put the access-and-participation line, with a named person and a reply date, into your own confirmation and reminder messages — then take each item to its named owner with one specific ask: a quiet-space and restroom standard for the next booking cycle, and one added line in the template.", response: "This gets the session right for the people coming, and it gives two owners something small, specific and inside their own authority. A booking standard and a template line, once changed, keep working for every event after this one.", recommended: true },
            { label: "Postpone the session until the venue standard and the template have been sorted out properly.", response: "Postponing costs the people who already arranged the day, and it makes an access improvement look like the reason an engagement was canceled. Fix what you control, hold the session, and carry both asks forward with the evidence the session gives you." },
          ],
        },
        transfer: {
          prompt: "Which of these will you actually do this month?",
          options: [
            "Name the event, and the date you will run the check by — before the invitation goes out",
            "Name the person outside your unit whose eyes you want on the plan, and how their time will be paid",
            "Name the item that is not yours, its owner, and the one specific ask you will make",
            "Name what you will send afterward, to whom, about what actually changed",
          ],
        },
        blocks: [
          { type: "text", heading: "Run it early, and run it with someone else", body: "<p>The check below takes about twenty minutes for an event you already know. It is worth almost nothing after the invitation goes out and almost everything before. Once a date is announced, a room is booked and food is ordered, every improvement turns into an exception that somebody has to request, and the people most likely to need one are the least likely to ask.</p><p>Run it with one other person, ideally someone whose working life is not much like yours. You will not catch the thing you have never had to think about, and neither will the colleague who sits next to you. Where the event is about a community, ask an advisor from that community to read the plan, and pay them for the time exactly as you would pay any other reviewer. Reviewing a plan is work, and asking for it free is one of the quieter ways public agencies push cost onto the people they are trying to reach.</p><p>Then keep the finished page with the event plan rather than in your own files. Most of what you learn running one session is reusable — the venue with the unreachable restroom, the caterer who labels properly, the community organization that asked for three weeks of notice rather than ten days. Left in a personal folder, all of it has to be discovered again by the next person.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A planning check for one event or engagement", summary: "Six lines, filled in before the invitation goes out, kept with the event plan so the next person to run this inherits what you learned.", fields: [
            { label: "Purpose, and who must be able to take part", value: "A regional session on how a waiver service is working. The people who must be able to take part: disabled Minnesotans using the service, family members, paid community advisors, provider staff. If any of those groups cannot be there, the session does not do its job." },
            { label: "Date, time and the calendars you checked", value: "Checked while the date was still a draft, against a published multi-faith calendar, the school calendar and the last accessible transit run. Avoided the fasting month and the sundown hour. Second session at a different hour on a different weekday. Written and phone routes open for two weeks after." },
            { label: "Place, room and hospitality", value: "Step-free entry, a reachable restroom on the same floor, a named quiet room with a chair and a door, movable seating for interpreters and wheelchair users, no scent-heavy cleaning before the session. Food labeled by ingredient, several marked options covering common dietary practices and common allergy needs, no alcohol." },
            { label: "Invitation, and the ways in that carry equal weight", value: "Plain-language invitation four weeks out, in the languages the communities invited actually read, with the agenda attached as real text. One open line: what would help you take part fully, with a named person and a reply-by date. Room, phone and written comment described as equally weighted, because they are." },
            { label: "Who shaped the plan, and how they were paid", value: "Two community advisors and one disabled Minnesotan who uses the service read the draft plan and the invitation, three weeks out, and were paid at the standard reviewer rate. Their changes: the date, the second session time, and the removal of the dietary-restriction box." },
            { label: "Afterward: what people are told, and by whom", value: "Within two weeks, one plain-language message to everyone who came or sent comment: what was heard, what is changing, what is not changing and why, and what happens next. Sent by the named session lead. The finished check filed with the event plan for the next round." },
          ], action: "Copy these six lines into your own event plan, fill them in before the invitation goes out, make every change that is inside your own control, and take anything that is not yours to its named owner with one specific ask." },
          { type: "list", heading: "First fixes that need nobody's permission", items: [
            "Check the date against a published multi-faith calendar while it is still a draft, not after it is announced.",
            "Put one open line in every invitation — what would help you take part fully — with a named person and a date they will reply by.",
            "Label every dish by ingredient, in large plain type, and stop asking people to declare restrictions in advance.",
            "Name a quiet room on the agenda, confirm it can be reached without stairs, and require no one to ask for a key.",
            "Send the agenda and materials as real text at least two working days ahead, in the languages the people invited actually read.",
            "Give written and phone routes the same weight as the room in the notice, and mean it when the comments are counted.",
            "Send one message afterward to everyone who took part, saying what happened to what they said.",
          ] },
          { type: "accordion", heading: "When part of the plan is not yours to change", items: [
            { title: "Bring one item, not the whole check", body: "<p>A full page invites a conversation about the page. One item, with the effect named and a specific ask attached, invites a decision. Keep the rest for the owners it belongs to, one at a time.</p>" },
            { title: "Bring the effect, not the frustration", body: "<p>“This venue is terrible” is a complaint. “Eleven of sixty attendees could not reach a restroom without crossing the building, and four left early” is a finding. The second version can be acted on, and it does not require anyone to accept blame before they can help.</p>" },
            { title: "Ask for something inside their authority", body: "<p>A quiet-space and reachable-restroom line in the venue booking standard. One added line in the invitation template. A three-week notice minimum for community partners. If the change needs approval further up, ask who to approach and whether they will come with you.</p>" },
            { title: "Know which door a question belongs to", body: "<p>Religious accommodation in employment, civil rights complaints, contract terms with community partners and official public notice requirements each belong to a specific DHS office. Anything involving Tribal Nations or tribal human services goes first to the Department of Human Services offices that handle tribal matters and to the Minnesota Office of Indian Affairs, rather than being decided inside a program team.</p>" },
          ] },
          { type: "leaderMove", heading: "Change the default, not the exception", control: "You control the order of your own planning: date checked as a draft, room and food decided before the form goes out, advisors paid and consulted while the plan can still change.", failure: "Do not build an event that works for everyone only if the right people ask in time. That design puts the cost on the people least able to carry it, and it fails invisibly — you find out by who did not come back.", next: "Run the six-line check on the next event you touch before the invitation is drafted, fix what is yours, and take one item to its owner with a specific ask." },
          { type: "knowledgeCheck", id: "ipe-24-4-check", question: "Your finished check shows five items. Three are inside your control; two belong to other units. The most serious one — an unreachable restroom at a booked venue — is not yours. The session is five weeks away. What is the most effective first move?", options: [
            { text: "Send the whole check to leadership in both other units and ask for the items to be assigned to the right owners.", correct: false },
            { text: "Fix the three items inside your control now, arrange the best workaround you can for the venue this time, and take each of the two remaining items to its named owner with the effect measured and one specific ask.", correct: true },
            { text: "Note the venue problem as a constraint in the event record and proceed, since the booking cannot be undone at this point.", correct: false },
            { text: "Postpone the session until the venue standard and the invitation template have been revised.", correct: false },
          ], feedbackCorrect: "Yes. The people coming in five weeks need a workaround now, and the two owners need one specific, grantable ask each — which is what turns a single session into a standard.", feedbackIncorrect: "Ask which version actually helps the people attending in five weeks and also changes the next event. Sending the whole page upward assigns nothing, recording a constraint fixes nothing, and postponing makes access look like the reason an engagement was canceled." },
          { type: "statement", body: "Private reflection, for you only: if someone was quietly left out of something you hosted — by a date, a room, a tray or a line on a form — what would accountability and repair actually require: of you, of the process, and toward the people who did not come back? And how could the people most affected have shaped that plan earlier? Nothing you write here is collected, stored or seen by anyone." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Religion, spirituality and cultural practice",
    subtitle: "One page for anyone who schedules, hosts, writes or designs something other people have to take part in",
    quote: "The date, the room and the tray decide who is in the conversation, long before anyone speaks.",
    use: {
      purpose: "Keep the calendar, the table, the room and the form in view while you plan a session, open a comment period, host an event, revise a form or write an invitation.",
      remember: [
        "A working calendar is not neutral. Check a date against a published multi-faith calendar while it is still a draft, and check recurring dates on a cycle, because lunar observances move each year.",
        "Adding a second real way to take part is almost always cheaper than moving an event, and it helps far more people than the ones you had in mind.",
        "Build the choice into the default. A single option plus a request line makes people disclose a practice to a government agency in order to receive what everyone else gets by walking in.",
        "Labeling is access. One plain card in front of each dish serves dietary practice, allergy and health conditions at the same time.",
        "Erasure and intrusion are the same failure. Ask about participation, not belief, and say what the answer will change and who will see it.",
        "Identical is a fact about a process. Equal participation is a claim about its effects, and it has to be checked — treating everyone the same is Minimization, not fairness.",
      ],
      doNext: "Run the six-line check on the next thing you host, before the invitation goes out, with one person who does not share your blind spots.",
    },
    sections: [
      {
        heading: "The planning check, in short",
        items: [
          "Purpose, and who must be able to take part: if this group cannot be there, the event does not do its job.",
          "Date, time and the calendars you checked: multi-faith, school, transit, and the sundown hour.",
          "Place, room and hospitality: step-free entry, reachable restroom, named quiet room, movable seating, labeled food.",
          "Invitation, and the ways in that carry equal weight: plain language, real text, the languages people read, one open participation line.",
          "Who shaped the plan, and how they were paid: named reviewers, paid at a standard rate, consulted while the plan could still change.",
          "Afterward: what people are told, by whom, and by when — and the finished check filed with the event plan.",
        ],
      },
      {
        heading: "Before a date becomes an announcement",
        items: [
          "Check the date and the two days around it against a published multi-faith calendar and a school calendar.",
          "Check the hour against late-afternoon prayer, sundown, the end of the school day and the last accessible transit run.",
          "Check the deadline, not only the event; a deadline is the part nobody can negotiate.",
          "Check whether a recurring slot has drifted into an observance since anyone last looked.",
          "Write the second way to take part into the plan before the first invitation is drafted.",
        ],
      },
      {
        heading: "Hosting: food, rooms and hospitality",
        items: [
          "Several clearly marked options, chosen so one plate works for more than one practice and more than one allergy.",
          "A card in front of every dish naming the main ingredients, in large plain type with good contrast.",
          "A meal time that works during a fasting period, or a session that does not center on food.",
          "A private, clean, reachable quiet room with a chair and a door, named on the agenda, no key request needed.",
          "Seating that can be moved for interpreters, wheelchair users and anyone who needs a particular place in the room.",
          "An open line in place of a restriction box: what would help you take part fully, with a named person and a reply date.",
        ],
      },
      {
        heading: "In a form, a script or a service plan",
        items: [
          "Ask about participation, not belief: what regular practices, observances or needs matter here, and what would support them?",
          "For every question you keep, write three sentences: why it is asked, what changes because of the answer, who sees it.",
          "Record only what the plan will act on — the ride, the meal, the clear day — not the reason behind it.",
          "Check the quiet assumptions: that natural supports means family, that community means secular community, that a week holds no fixed obligations.",
          "Never ask a colleague to describe or defend their own beliefs, practice or background as part of this work.",
        ],
      },
      {
        heading: "Working with congregations and culturally specific organizations",
        items: [
          "They are partners with costs, not free distribution channels. Pay for review, facilitation, translation, storytelling and advice.",
          "Give real notice. Ten days is a flyer request; three weeks is an invitation to shape something.",
          "Making participation possible is not endorsing a belief, and asking what someone needs is not a religious test.",
          "For anything involving Tribal Nations or tribal human services, go first to the Department of Human Services offices that handle tribal matters and to the Minnesota Office of Indian Affairs.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Communications, training and learning-design staff, who pick the dates, write the invitations, book the rooms and set the format — this module goes deepest here, and it is the best place to start.",
          "Policy and program staff, whose comment windows, deadlines and assessment questions decide who is represented in the record.",
          "Community engagement staff, who carry the relationship when a date, a room or a table gets it wrong.",
          "Operations, administrative and support staff, who book the venue, order the food and answer the person who asks what is in the sandwiches.",
          "Quality, data and evaluation staff, who report participation numbers that a scheduling decision quietly shaped weeks earlier.",
          "Contracts, grants and fiscal staff, who decide whether community and congregational partners are paid for the work they are asked to do.",
          "Supervisors and managers, who can make a date check and a quiet room part of the standard rather than a favor.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "History, disability, and public institutions",
          "Immigration, resettlement, and state-system navigation",
          "LGBTQIA2S+ inclusion and privacy",
          "Power, conflict, and repair",
          "Ethical decision-making",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Department of Human Rights, Your rights", href: "https://mn.gov/mdhr/yourrights/", note: "The Minnesota Human Rights Act protections, including religion and creed alongside disability, and how they apply in public services and public accommodations." },
    { title: "U.S. Department of Justice, Civil Rights Division", href: "https://www.justice.gov/crt", note: "Federal civil rights enforcement, including national-origin discrimination in federally assisted programs, which often overlaps with religious identity." },
    { title: "U.S. Department of Justice, Federal Coordination and Compliance Section", href: "https://www.justice.gov/crt/fcs", note: "Guidance on Title VI of the Civil Rights Act and language access obligations for recipients of federal financial assistance, including notice and meaningful-participation requirements." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the governance, workforce, communication and community partnership standards used throughout this module." },
    { title: "ADA.gov, Title II primer for state and local governments", href: "https://www.ada.gov/resources/title-ii-primer/", note: "U.S. Department of Justice explanation of what Title II requires of state and local government programs, meetings and public events, including physical access and effective communication." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's advisory council on disability policy, access and rights, including guidance for state agencies on accessible meetings, venues, notices and public processes." },
    { title: "plainlanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Practical guidance for writing invitations, notices and forms people can act on, including how to ask a question that produces a usable answer." },
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials, and accessible instruction that does not require disclosure." },
  ],
};

export default pack;
