import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Complex systems · Module 27: Ethical decision-making.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-27-ethical-decision-making",
    indexNumber: 1169,
    seriesLabel: "Intercultural Practice and Equity · Complex systems",
    title: "Ethical Decision-Making",
    subtitle: "Autonomy, safety, cost, legal requirement, quality oversight and equity rarely point the same way. Four lessons on naming the trade, seeing the decision from somewhere other than your own desk, testing a reason before it hardens into a rule, and leaving a record the person affected could read.",
    scope: "For internal DHS and DSD staff who make or shape decisions that reach other people’s lives: policy, program and operations staff, for whom this is a useful place to start in this area; quality, compliance and performance staff, who will find the deeper material here; leaders, supervisors and managers; contracts, grants and procurement staff; data, research, evaluation and analytics staff; communications, training and learning-design staff; community engagement staff; administrative and support staff. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no badge, no completion requirement, and nothing you write in a reflection is collected or seen. You are never asked to disclose your own identity, beliefs or personal experiences. This is not direct-service or provider training, and completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota examples, worked scenarios, sorting and flashcard practice, private reflection prompts, and a seven-line multi-perspective decision review you can copy into your own work",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/equity-centered-leadership.jpg",
    coverAlt: "A woman sits at the head of a conference table with a notebook.",
    introTranscript: "Some decisions in this work cannot be settled by looking up the rule, because more than one thing the division is genuinely obliged to protect is in play at the same time: a person’s authority over their own life, their safety, what the law requires, what the money allows, what quality oversight can actually verify, and whether the result lands the same way on everyone. It never does. This module is about that kind of decision. It gives you a way to name the obligations pulling against each other, to see the decision from standpoints other than your own, to test a reason before it hardens into a rule for everyone, and to write down seven lines that let a decision be explained, challenged and revisited later. There is no score here, and nothing you write in a reflection is collected.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Name the obligations in tension in a real division decision — a person’s authority over their own life, safety, legal requirement, available resources, what quality oversight can verify, and whether the result lands fairly — and say which one the current design quietly favors.",
        "Describe one decision from at least five standpoints, and mark who was at the table, who was spoken for by somebody else, and who was missing.",
        "Apply six tests to the reasoning behind a decision, and separate genuine obligations from defensible preferences and unexamined habits.",
        "Explain why scarcity is a constraint while the distribution of its cost is a choice, and finish the sentence that usually stops at “we do not have the resources.”",
        "Complete a multi-perspective decision review for one real decision, including what it costs whom, how people can challenge it, when it will be revisited and what repair would require.",
      ],
      evidence: [
        "Four worked scenarios drawn from policy drafting after an incident, service design, quality review and a grant program, each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates who was actually at the table from who was spoken for, and obligations from preferences and habits.",
        "A completed seven-line decision review kept with the decision itself rather than in a personal file.",
      ],
      appliedNextStep: "Choose one decision you can genuinely shape this month. Name the obligations in tension, find one standpoint that is missing and bring it in properly, run the publicity and burden tests over the reason you would give, and write the seven lines into the record before the decision is final.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in Minnesota’s home and community-based services licensing standards, in the rule on positive support strategies and restrictive interventions, or in maltreatment reporting requirements",
        "A change in the code of ethics for executive branch employees, in conflict-of-interest requirements, or in department direction on how decisions affecting people receiving services are documented, explained and appealed",
        "Feedback from paid community advisors, disabled Minnesotans, county or lead agency staff, or division staff that a scenario here misstates how a decision is actually made or what it costs",
      ],
      relatedDoor: "Formal decisions — whether a licensing standard is met, whether something must be reported as maltreatment, how a rule is legally interpreted, how data about a person is classified, and the outcome of any appeal — belong to the responsible DHS program, licensing, legal, data practices and human resources offices, with independent review of the care and treatment of people receiving services available through the Minnesota Office of Ombudsman for Mental Health and Developmental Disabilities; this module prepares the reasoning and the ask, it does not decide a case.",
      toolkitQuestion: "If the person most affected by this decision read the reasons we wrote down, would they recognize the decision — and would they be able to see how to challenge it?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-27-1",
        number: 1,
        title: "Two right answers, one decision",
        summary: "The decisions that stay hard are the ones where more than one legitimate obligation is in play. This lesson names the six that pull against each other in division work, and the trade every design has already made.",
        minutes: 11,
        learning: {
          objective: "Name the obligations pulling on a real division decision, and state which one the current design quietly treats as the default.",
          takeaways: [
            "An ethical decision in public work is rarely a choice between right and wrong. It is usually a choice among things the division is genuinely obliged to protect: a person’s authority over their own life, their safety, what the law requires, what the money allows, what oversight can verify, and whether the result lands fairly.",
            "Every design has already resolved the tension. A form, a deadline, a rate, a standard: each has already decided whose interest gives way. The only question left is whether anybody chose it on purpose.",
            "Safety and autonomy are the pair that comes up most, and Minnesota law holds both at once. The licensing standards for home and community-based services set out service recipient rights on one side and protection standards on the other, and the rule on positive support strategies keeps restrictive interventions narrow.",
            "Scarcity is real; who absorbs it is not arithmetic. “We do not have the resources” describes a constraint. It does not say whose service gets thinner or whose wait gets longer, and that part is still a choice somebody makes.",
            "“We apply the same rule to everyone” feels like fairness and is often Minimization. The same rule costs different people different amounts, and the difference is nearly invisible from the middle of an organization.",
          ],
          evidence: "A scenario about guidance drafted under pressure after a serious incident, and a knowledge check on what a blanket requirement actually decides.",
          appliedNextStep: "Take one rule, deadline or standard your unit owns. Write down the obligation it protects and the one it quietly gives up, then find out whether anyone ever chose that on purpose.",
        },
        scenario: {
          context: "A serious incident in a community setting reaches a DSD program area. Nothing in current policy was broken. A draft response would add one requirement across every program in that service category: a documented risk review before any person may spend unsupervised time away from home. The drafting group has a week, and the pressure to show a response is real.",
          prompt: "What does this decision owe the people it will reach?",
          options: [
            { label: "Issue the requirement now. A response is expected, it applies to everyone equally, and it can be narrowed later if it turns out to be too broad.", response: "Speed here buys something specific: several hundred people lose unsupervised time in their own lives because of an event none of them were part of. A rule written under pressure is also the hardest kind to take back, because withdrawing it later reads as deciding that safety no longer matters." },
            { label: "Name the obligations in tension, work out who carries the cost of each option, ask the people the requirement would apply to and the staff who would run it, and bring a narrower version with a stated review point.", response: "This is the work, and most of it fits inside a week. Naming the tension stops the decision being framed as safety against nothing. Costing the options shows that a blanket review transfers the burden onto people who did nothing. A narrower, reviewable version almost always survives longer than the broad one.", recommended: true },
            { label: "Refer the whole question to licensing and legal, and wait for their determination before proposing anything.", response: "Those offices decide what the standards require, and the group should certainly ask them. But the choice here is not only a legal one. An office asked “is this permitted” will answer that question, not the question about who pays for it." },
          ],
        },
        transfer: {
          prompt: "Where in your own work has a rule already settled a tension that nobody named?",
          options: [
            "Name one rule, deadline or standard your unit owns",
            "Write down the obligation it protects and the one it gives up",
            "Find out who decided that, and whether the trade was ever written down anywhere",
          ],
        },
        blocks: [
          { type: "text", heading: "Why these decisions feel different", body: "<p>Most decisions in division work have an answer somebody can look up. The ones that stay difficult do not, and that is not a failure of preparation. They are hard because two things the division is genuinely obliged to protect are pointing in opposite directions at the same moment.</p><p>A person has authority over their own life, including the authority to make choices other people would not make. The division also has a duty to protect people from harm. A statute sets a requirement; the money does not stretch to doing it well everywhere. Quality oversight can only verify what somebody wrote down, which quietly rewards whatever is easy to document. And under all of it sits the question of whether the result lands the same way on everyone, which it almost never does.</p><p>Calling this an ethical decision is not a claim that anyone is behaving badly. It means the choice cannot be settled by finding the rule, because more than one legitimate obligation is live and the design is going to give somewhere. The skill worth building is not moral certainty. It is being able to say out loud which obligations are pulling, which one the current design favors, what that costs and who pays it.</p><p>Here is the part that catches people. The tension is always already resolved. By the time you see a form, a deadline or a standard, somebody has decided whose interest gives way — often nobody in particular, often years ago, often as a side effect of something else. Finding the trade that is already in the design is usually more useful than arguing about the one you are about to make.</p>" },
          { type: "flashcards", heading: "Six obligations, pulling at once", cards: [
            { front: "A person’s authority over their own life", back: "<p>The authority to decide where to live, who to spend time with, what risk to accept and what help to refuse. Minnesota’s licensing standards for home and community-based services set out service recipient rights directly. They are not a courtesy the division extends when it is convenient.</p>" },
            { front: "Safety", back: "<p>A real duty with a legal shape: protection standards, reporting requirements, and narrow limits on when a restrictive intervention may be used at all. Safety is not a veto over everything else, and it is not satisfied by removing a person’s choices.</p>" },
            { front: "What the law actually requires", back: "<p>A statute, a rule, a court decision or a federal condition of funding. Worth separating carefully from what a form has always said, what a supervisor prefers, and what somebody believes the rule probably means.</p>" },
            { front: "What the money allows", back: "<p>Appropriations, staffing and time are finite, and pretending otherwise produces decisions that fail quietly. Scarcity is a fact. Who absorbs it is a choice somebody makes, on purpose or by default.</p>" },
            { front: "What oversight can verify", back: "<p>Licensing, audit and quality review can only check what is recorded. That pulls design toward whatever documents well, which is not reliably the same as whatever works for a person.</p>" },
            { front: "Whether the result lands fairly", back: "<p>The same rule applied identically produces different results for people who start in different places. This obligation is to notice that before the rule is final, rather than after somebody manages to complain.</p>" },
          ] },
          { type: "accordion", heading: "What each obligation is protecting, and where it comes from", items: [
            { title: "Autonomy is not a preference", body: "<p>Under Minnesota’s licensing standards for home and community-based services, a person receiving services has stated rights: to make their own choices, to take part in decisions about their services, to privacy, to associate with the people they choose. These are not aspirations to be set aside when a situation becomes uncomfortable. Dignity of risk is the part that gets forgotten. An adult who cannot make a choice other people would call unwise has not really been given a choice at all.</p>" },
            { title: "Safety has a statutory shape, and a narrow one", body: "<p>The same standards set protection requirements, and Minnesota’s rule on positive support strategies limits restrictive interventions sharply, with the emergency use of manual restraint hedged about by conditions, reporting and review. The shape matters. The law does not say “keep people safe by whatever means are available.” It says safety is pursued through positive support, and that taking away a person’s control is the rarest of exceptions.</p>" },
            { title: "A requirement and a habit are not the same thing", body: "<p>A surprising share of what staff experience as “the rule” turns out to be a local practice, a form design, or a cautious reading that hardened long ago and was never revisited. Before you trade a person’s autonomy against a legal requirement, find the requirement and read the sentence. If nobody can point to it, you are not balancing law against autonomy. You are balancing a habit against a person.</p>" },
            { title: "Money is a constraint; who absorbs it is a decision", body: "<p>“We do not have the resources” is often true and almost never a complete sentence. It describes the constraint. It does not say whose service gets thinner, whose wait gets longer, whose paperwork gets heavier, or which county gets the slower answer. Those are choices. Made deliberately, they can be explained and revisited. Made by default, the cost lands on whoever has the least ability to push back.</p>" },
            { title: "Oversight can only verify what it can see", body: "<p>A quality system checks documents, timeliness and whether a required step happened. That is legitimate work, and it has a gravitational pull: over time, programs optimize for whatever gets checked. If the thing that matters most to a person cannot be recorded, it will slowly stop being the thing the program protects. Worth saying out loud in the room where a measure is designed.</p>" },
          ] },
          { type: "leaderMove", heading: "Name the trade before you make it", control: "You control whether the obligations in tension get named in the room, in plain words, before the decision is framed as a single question with one obvious answer.", failure: "Do not let the decision arrive as “are we willing to risk somebody getting hurt.” Framed that way it has exactly one answer, and everything it costs stays invisible.", next: "In the next decision meeting you are part of, say both obligations out loud — “this protects safety and it costs people their own choices” — and ask what the second one is worth." },
          { type: "quote", text: "Nobody asked me anything. They wrote a rule about my life because of something that happened to a person I have never met, three hundred miles away.", cite: "Composite perspective from a person receiving services, illustrative" },
          { type: "statement", body: "A private reflection, for you alone. How might my role, authority or assumptions shape which of these obligations I treat as obvious and which I treat as negotiable? Who could be helped, burdened, excluded or misunderstood by the decision in front of me? Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-27-1-check", question: "A draft response to one serious incident would require a documented risk review before anyone in a service category may spend unsupervised time away from home. What does that requirement actually decide?", options: [
            { text: "That safety is the division’s first duty, which is the correct order whenever there is a risk of harm.", correct: false },
            { text: "That everyone in the category gives up unsupervised time until a document exists, and that the cost of one event is carried by people who were not part of it. It may still be the right call, but it has to be chosen with that cost named.", correct: true },
            { text: "Nothing yet, because programs can always seek an exception for an individual whose circumstances are different.", correct: false },
          ], feedbackCorrect: "Yes. A blanket requirement is a transfer of cost as well as a safety measure, and the transfer is the part that usually goes unnamed.", feedbackIncorrect: "Look past the stated purpose to the effect. Who loses something on the day this takes effect, and were they any part of what happened?" },
        ],
      },
      {
        id: "ipe-27-2",
        number: 2,
        title: "The same decision, seen from five places",
        summary: "A decision looks different depending on where you stand, and the standpoints missing from the room produce the expensive mistakes. This lesson is about holding more than one view without collapsing them into your own.",
        minutes: 11,
        learning: {
          objective: "Describe one division decision from at least five standpoints, and identify which shaped the current design, which were spoken for by somebody else, and which were missing.",
          takeaways: [
            "A standpoint is not an opinion. It is what a person can actually see from where they stand and what the decision costs them, and you cannot reason your way into it from the middle of the organization.",
            "Five turn up in almost every division decision: the person whose life it reaches; the people who support them, including chosen family; the staff who have to run it; the county or lead agency that carries it out; and the reviewer who will later ask whether it was followed.",
            "Being spoken for is not being represented. A summary of what people would probably want, written by staff or by an association, is a careful guess with an official signature on it.",
            "History changes what a rule means. A community with generations of reason to expect a public system to work against them reads a new requirement differently, and that reading is information about the requirement rather than a problem with the reader.",
            "Holding several standpoints at once, without flattening them into your own, is the movement from Minimization toward Acceptance and Adaptation. It is a practice rather than a personality, and it is not the same thing as agreeing.",
          ],
          evidence: "A scenario about a service authorization change reviewed only by people already inside the system, sorting practice on who was actually at the table, and a knowledge check on what a comment period can and cannot catch.",
          appliedNextStep: "Take a decision your unit is working on now. List everyone it reaches, then mark each one: at the table, spoken for by somebody else, or missing. Bring the list to the next meeting about it.",
        },
        scenario: {
          context: "A DSD program area is changing how a service is authorized: a new online request, a shorter turnaround and a standard set of documents. The draft went to an internal workgroup, to a statewide association of service providers, and to the division’s legal contact. It did not go to anyone who uses the service, to the county workers who will enter the requests, or to the staff who answer the phone when a request is denied.",
          prompt: "Where does this review go wrong?",
          options: [
            { label: "It does not. The association represents the people who deliver the service and legal represents the requirements, so the ground is covered. Adding more voices now would delay a change that is already overdue.", response: "An association represents its members’ interests, which are real and are not the same as the interests of the people receiving the service or the workers entering the requests. “Already overdue” is also how most decisions come to be made with the smallest number of standpoints in the room." },
            { label: "Three standpoints are missing and each sees something the others cannot: people who use the service, county workers who will run the new request, and the staff who handle denials. Bring them in before the design is fixed, pay community advisors for their time, and say what changed because of them.", response: "This is the move. Each of the three sees a different failure: the person sees what happens in the gap, the county worker knows within a week which document is impossible to obtain, and the staff who handle denials hear the consequence first. Paying advisors and reporting back is what separates consultation from decoration.", recommended: true },
            { label: "Send the draft out for a public comment period at the end, so that anyone affected has the opportunity to respond.", response: "Comment at the end tests a finished design. It catches wording, not structure, and it asks people to argue against something that already looks decided. The expensive choices were made before the draft existed." },
          ],
        },
        transfer: {
          prompt: "Whose standpoint is missing from a decision you are part of right now?",
          options: [
            "List everyone the decision reaches, including the staff who will have to run it",
            "Mark who was at the table, who was spoken for, and who was missing entirely",
            "Name one group you could bring in before the design is fixed, and what it would take to do that properly",
          ],
        },
        blocks: [
          { type: "text", heading: "What a standpoint is, and why you cannot reason your way into one", body: "<p>A standpoint is not a point of view in the sense of an opinion you could talk somebody out of. It is the set of things a person can see from where they actually stand, plus what this decision costs them. Two people looking at the same change can both be completely accurate and completely at odds, because they are seeing different parts of it.</p><p>This is why careful thinking inside a division is not a substitute for asking. A policy analyst can imagine what a shorter turnaround might mean for someone whose service lapses. What they cannot see is what that person does on the third day, who they call, what it costs them, and which part of the process they will never trust again. That is not a failure of empathy. It is a limit on the position.</p><p>The practical form of this is simple and slightly uncomfortable: name the standpoints, find out which are represented, and treat “missing” as a real and reportable finding rather than a gap to be filled with a reasonable guess. Community members, disabled Minnesotans, families and culturally specific organizations who take part in that work are co-designers and advisors doing professional work. They are paid for it, they see what changed because of them, and they are free to say no.</p>" },
          { type: "tabs", heading: "One change, five views", tabs: [
            { label: "The person whose life it reaches", body: "<p>A shorter turnaround sounds like an improvement until you are the person whose service lapses because the new request needs a document your clinic takes three weeks to produce. From here the change is not faster; it is a new way to lose something. This standpoint also sees the part nobody inside the system sees, which is what happens in the gap.</p>" },
            { label: "The people who support them", body: "<p>Family, partners, friends, chosen family and paid support staff absorb whatever the system does not do. A new form means somebody sits at a kitchen table and fills it in. A denial means somebody makes the phone calls and rearranges a week. From here the question is never only whether the rule is right; it is who does the extra work the rule creates.</p>" },
            { label: "The staff who have to run it", body: "<p>The worker entering requests knows within a week which fields people get wrong, which document is effectively impossible to obtain, and which step everyone quietly works around. That knowledge is rarely asked for and is usually accurate. Leaving it out does not make the workaround disappear; it moves it somewhere nobody can see it.</p>" },
            { label: "The county or lead agency", body: "<p>They carry out what the division designs, with staffing the division does not control and caseloads it may not see. A change that costs the division nothing can cost a small county a position it does not have. From here, timing and notice matter as much as content, and a change announced late is a change that will be done badly.</p>" },
            { label: "The reviewer who comes later", body: "<p>Licensing, audit and quality staff will be asked whether the rule was followed, using the record. From here, what is not written did not happen. This standpoint is legitimate and it has a pull of its own: it rewards the design that documents well, which is not automatically the design that works.</p>" },
          ] },
          { type: "sorting", id: "ipe-27-2-sort", heading: "At the table, spoken for, or missing?", categories: ["At the table", "Spoken for by somebody else", "Missing entirely"], items: [
            { text: "A statewide association of service providers gave detailed comments on the draft.", category: "At the table" },
            { text: "Staff summarized what people receiving the service would probably prefer, based on past complaints.", category: "Spoken for by somebody else" },
            { text: "Nobody asked the county workers who will enter the new requests.", category: "Missing entirely" },
            { text: "Paid community advisors reviewed the design early, were told what changed because of them, and could decline.", category: "At the table" },
            { text: "A family member’s view was taken from a note written into a case record for a different purpose.", category: "Spoken for by somebody else" },
            { text: "The division’s legal contact confirmed that the change is permitted.", category: "At the table" },
            { text: "Nobody asked the staff who answer the phone when a request is denied.", category: "Missing entirely" },
          ] },
          { type: "accordion", heading: "Why the same rule reads differently to different people", items: [
            { title: "History is evidence, not attitude", body: "<p>Public institutions in Minnesota have a long documented record with disabled people that includes large state institutions, segregated schooling and decades of waiting for an ordinary life. People whose families lived through that read a new state requirement with that record in mind. That is not cynicism to be managed around. Treating it as an obstacle is how the next generation learns the same lesson.</p>" },
            { title: "Trust is a record, not a feeling", body: "<p>If a community has been consulted before and nothing changed, low turnout at your meeting is data about the last meeting rather than about whether people care. Trust here is the accumulated record of whether taking part ever produced a different outcome. It can only be rebuilt the same way it was lost, by showing what changed.</p>" },
            { title: "Intersection is not addition", body: "<p>A person is not a disability plus a language plus a county. Someone who is Deaf, works with an interpreter, lives in a small town and has a supported decision-making arrangement does not face four separate barriers. They face one situation in which each of those changes what the others mean. A design that handles each factor separately misses the person entirely.</p>" },
            { title: "Where the continuum fits, and where it stops", body: "<p>This program uses the intercultural development continuum — Denial, Polarization, Minimization, Acceptance, Adaptation, Integration — as its theory of change. It describes how an organization’s default way of handling difference tends to develop, and “we treat everyone exactly the same” is the classic Minimization move: it sounds fair and it hides the unequal cost. The continuum is a way of understanding the work. It is never a label, a score or a record about any individual, and nothing here is assessing you.</p>" },
          ] },
          { type: "quote", text: "We were invited to comment at the end. By then the only thing left to change was the wording. They seemed surprised that we did not have much to say.", cite: "Composite perspective from a paid community advisor, illustrative" },
          { type: "leaderMove", heading: "Find the missing standpoint before the design sets", control: "You control when people are brought in. Early, they can change the structure. Late, they can change the wording.", failure: "Do not treat an association, a summary of past complaints or a staff member’s best guess as the standpoint of the people affected. Each is useful, and none of them is the same thing.", next: "For the decision in front of you, name one standpoint that is missing, and find out what it would take to bring it in properly: time, notice, materials people can actually use, and payment for anyone who is not an employee." },
          { type: "statement", body: "A private reflection, for you alone. Whose expertise is missing from this decision, and what would it take to have it here early rather than at the end? How could the people most affected shape this work sooner? Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-27-2-check", question: "A program change goes out for public comment after the design is complete. What can that comment period reliably catch?", options: [
            { text: "Whether the design works for the people it affects, since anyone at all can respond to it.", correct: false },
            { text: "Problems with wording, clarity and specific details — and very little about structure, because the shape of the change is already settled and responding means arguing against something that looks decided.", correct: true },
            { text: "Nothing useful. Comment periods are a formality, and the effort is better spent elsewhere.", correct: false },
          ], feedbackCorrect: "Yes. Comment at the end is a real check on wording and detail. The structural choices were made before the draft existed, which is where the standpoints needed to be.", feedbackIncorrect: "Ask what a person can actually change at that point in the process, and how it feels to object to something that already looks final." },
        ],
      },
      {
        id: "ipe-27-3",
        number: 3,
        title: "Reasons that hold up",
        summary: "Six tests you can run on the reasoning behind a decision in about ten minutes, and five sentences that sound like reasons but are usually something else wearing a reason’s clothes.",
        minutes: 10,
        learning: {
          objective: "Apply six tests to the reasoning behind a real decision, and sort the stated reasons into obligations, defensible preferences and habits that still need a reason.",
          takeaways: [
            "Publicity: say the real reason out loud to the person it lands on, in plain words. If it only holds together in internal shorthand, it is not a reason yet.",
            "The rule: you are never deciding one case. Whatever you decide here is the rule for every case that looks like it. State that rule aloud and see whether you would sign it.",
            "Burden: name who carries the cost of each option — in money, and also in time, travel, waiting, paperwork, uncertainty, risk and dignity.",
            "Power: ask whether the decision would be the same if the people affected had more staff, better representation, or an easier route to someone with authority.",
            "Evidence: “nobody has complained” describes how complaining works. It is not evidence that nothing is wrong, least of all where complaining puts a service at risk.",
            "Reversal: if this were decided about you, on this evidence, by people who had never met you, what would you need in order to accept it?",
          ],
          evidence: "A scenario about two counties held to the same review standard with unequal capacity, sorting practice separating obligations from preferences and habits, and a knowledge check on what an absence of complaints actually tells you.",
          appliedNextStep: "Take the last decision your unit made that affected people outside it. Write down the reason exactly as it was given, then run the publicity test and the rule test over that sentence.",
        },
        scenario: {
          context: "A DSD quality unit finds a pattern in corrective action plans. One county’s plans are accepted on first submission; another county’s are returned two or three times. Reviewers are using the same checklist. The returned plans are harder to read, and that county has fewer staff, heavy turnover and nobody whose job includes writing. A reviewer proposes a written standard for plan quality so that everyone is held to the same bar.",
          prompt: "Which reading of this survives testing?",
          options: [
            { label: "The written standard is the fair answer. The same bar for everyone, in writing, removes the inconsistency the unit found.", response: "It removes inconsistency between reviewers, which is worth doing on its own. It does not touch the pattern. The same bar applied to units with unequal capacity produces the same result more defensibly, and the county with three staff still fails it." },
            { label: "Write the standard, and pair it with something the smaller county can actually use: a template, an example of an accepted plan, and an offer of a working session before submission. Then look again next cycle at whether the gap moved.", response: "This holds up under all six tests. The standard answers the reviewer consistency problem. The template and the working session answer the capacity problem, which is the one actually producing the pattern. Checking next cycle is what makes it a decision rather than a gesture.", recommended: true },
            { label: "Leave the standard out, and instruct reviewers to take county capacity into account when they review.", response: "This asks individual reviewers to make an unwritten allowance, which is neither consistent nor reviewable, and it rests the whole thing on discretion. It also cannot be explained to the county that happens to get the stricter read." },
          ],
        },
        transfer: {
          prompt: "Which reason given in your unit recently would not survive being said out loud to the person it affected?",
          options: [
            "Write down the reason exactly as it was given, in its original words",
            "Rewrite it as you would say it to the person, then see whether it still sounds like a reason",
            "Name who carries the cost of the decision, in something other than money",
          ],
        },
        blocks: [
          { type: "text", heading: "Test the reason, not the outcome", body: "<p>Two people can reach the same decision for completely different reasons, and it is the reasons that decide the next hundred cases. This is why testing the reasoning matters more than arguing about the outcome. An outcome settles today. A reason quietly becomes a rule.</p><p>The six tests below are not a formula that produces an answer. They are a way of finding out whether the reason you are about to write down will survive contact with the person it affects, with the next case that looks like this one, and with somebody reading the file later who was not in the room. Most of them take a minute.</p><p>Two do most of the work. The publicity test — can you say the real reason, in plain words, to the person it lands on — catches reasoning that only holds together in internal shorthand. The burden test — who pays, and in what currency — catches the decision that looks cost-free from inside the division because the cost lands somewhere the division does not have to look.</p>" },
          { type: "list", heading: "Six tests, about ten minutes", ordered: true, items: [
            "Publicity. Say the real reason to the person it affects, in words they use. Would it still sound like a reason?",
            "The rule. State what you are deciding for every case that looks like this one, then check whether you would put your name to it.",
            "Burden. Name who pays for each option in money, time, travel, waiting, paperwork, uncertainty and dignity.",
            "Power. Ask whether the decision would be the same if the people affected had more staff, better representation, or a shorter route to someone with authority.",
            "Evidence. Separate what you know from what you assume, and check whether an absence of complaints is evidence of anything here.",
            "Reversal. Put yourself on the other side of the decision with the same information available, and name what you would need in order to accept it.",
          ] },
          { type: "accordion", heading: "Five sentences that sound like reasons", items: [
            { title: "“The rule requires it”", body: "<p>Sometimes true. Find the rule and read the sentence. A large share of what feels mandatory turns out to be a form design, a local practice or a cautious reading nobody has revisited. And if it is genuinely required and the requirement is causing harm, that is not the end of the conversation either. It is the beginning of a different one, with the office that owns the requirement.</p>" },
            { title: "“Nobody has complained”", body: "<p>People who depend on a service have strong reasons not to complain about it, and the people a barrier stops are often the least able to work a complaint process. Silence measures the route, not the harm. If you want to know, ask in a way that costs the person nothing to answer.</p>" },
            { title: "“We do not have the resources”", body: "<p>Usually true, and incomplete. Finish the sentence: so this group waits longer, or this county gets the slower answer, or this step moves onto a family. Written out, it becomes a decision somebody can own and revisit. Left unfinished, it becomes a permanent state with no author.</p>" },
            { title: "“It would set a precedent”", body: "<p>A real consideration and a frequent cover. Ask what precedent, for whom, and whether it would actually be a bad one. Often the feared precedent is “we would have to do this for everybody,” which is sometimes exactly the right answer and is at minimum an honest statement of the cost.</p>" },
            { title: "“That sits with somebody else”", body: "<p>Boundaries are real, and this sentence ends more conversations than it should. The usable version names who does own it, says what you will do inside your own step, and hands the rest over with the specifics attached. The unusable version leaves the person to go and find the right door on their own.</p>" },
          ] },
          { type: "sorting", id: "ipe-27-3-sort", heading: "Obligation, defensible preference, or habit?", categories: ["An obligation", "A preference we can defend", "A habit that still needs a reason"], items: [
            { text: "A person receiving services has the right to take part in decisions about their own services.", category: "An obligation" },
            { text: "Requests are reviewed in the order they arrive, so that nobody can move ahead of the queue.", category: "A preference we can defend" },
            { text: "Applications have to come in on the form, because that is how it has always been done here.", category: "A habit that still needs a reason" },
            { text: "When the state asks a person for private information about themselves, it has to say why, how it will be used and who else may see it.", category: "An obligation" },
            { text: "Meeting materials go out two working days ahead, so people have time to read them.", category: "A preference we can defend" },
            { text: "Plans are returned when they are hard to read, without an example of an accepted one.", category: "A habit that still needs a reason" },
            { text: "Restrictive interventions are limited to the narrow circumstances set out in rule.", category: "An obligation" },
          ] },
          { type: "leaderMove", heading: "Write the reason you would give the person", control: "You control which reason goes into the record: the one that will satisfy a reviewer, or the one you would actually give the person affected.", failure: "Do not record “does not meet requirements” when the real reason is that the requirement asks for something the person cannot produce. The second sentence is the only one that lets anybody fix it.", next: "In the next decision you document, write the reason in the words you would use if the person were sitting across the table, and then check whether it still holds." },
          { type: "statement", body: "A private reflection, for you alone. Does this decision make sense to somebody who does not already know how the division works? If harm or exclusion came out of it, what would accountability and repair require of me? Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-27-3-check", question: "A unit reports that a requirement causes no problems, because it has received no complaints about it in three years. What is the strongest reading of that evidence?", options: [
            { text: "Reasonable evidence that the requirement works as intended, since people affected by a bad requirement usually say so.", correct: false },
            { text: "It tells you about the complaint route rather than the requirement. People who depend on a service often have good reasons not to complain, and the people a requirement stops are frequently the least able to use a complaint process.", correct: true },
            { text: "Meaningless, because complaint counts never tell you anything useful about a program.", correct: false },
          ], feedbackCorrect: "Yes. Silence measures the route. If you want to know whether the requirement causes harm, ask in a way that costs the person nothing to answer.", feedbackIncorrect: "Ask who would have to complain, what it would cost them to do it, and whether the route is one they could realistically use." },
        ],
      },
      {
        id: "ipe-27-4",
        number: 4,
        title: "Writing the decision down",
        summary: "A decision that exists only as an outcome cannot be explained, challenged, applied consistently or revisited. This lesson builds the seven-line review that holds the reasoning, and hands you the tool to copy into your own work.",
        minutes: 11,
        learning: {
          objective: "Complete a multi-perspective decision review for one real decision, naming the tension, the standpoints, the tests, what it costs whom, how people can challenge it, the revisit point and what repair would require.",
          takeaways: [
            "A decision record is only paperwork if it holds nothing but the outcome. With the reasoning in it, it is what lets a decision be explained, challenged, applied consistently and changed.",
            "Seven lines carry almost all of it: the decision, the obligations in tension, who is affected and who was in the room, the tests applied, what was chosen and what it costs whom, how people will be told and how they can challenge it, and what would make you look again.",
            "Write it for the person it affects, not for the auditor. A record a person could read and recognize is also a record a reviewer can follow.",
            "Put repair in before anything goes wrong. Deciding in advance what you would owe somebody if this caused harm is what separates a commitment from a sentiment.",
            "A decision with no revisit point is not a decision. It is a permanent state that nobody owns and nobody can reopen without appearing to start a fight.",
          ],
          evidence: "A scenario about a sound decision that was never written down, a completed seven-line decision review you can copy, and a knowledge check on what makes a record usable to the next person.",
          appliedNextStep: "Choose one decision you can actually shape this month. Fill in the seven lines before it is final, put the page where the decision lives rather than in your own notes, and name the point at which you will look again.",
        },
        scenario: {
          context: "A DSD grant program accepted a community organization’s application two cycles ago even though it lacked one required financial document, because the requirement asked for something the organization could not produce and the gap did not affect the work. The discussion was careful. None of it was written down. A new staff member now has two similar applications and no record of why the first was accepted. One is approved and one is denied. A third organization asks what the standard is.",
          prompt: "What actually failed here?",
          options: [
            { label: "Nothing failed at the time. The original decision was sound, and the problem is the new staff member’s inconsistency, which a reminder about applying requirements consistently will fix.", response: "The original decision may well have been sound, and nobody can now show that it was. Without the reasoning, the new staff member had nothing to apply consistently, and the third organization has no way to find out what standard it was held to." },
            { label: "The reasoning was never recorded, so a good decision became an unexplainable one. Reconstruct and write down the rule that was actually made, apply it to all three applications, tell the organizations plainly what the standard is, and keep the review with the program’s requirements so the next person inherits it.", response: "This is the repair and the prevention in one move. Writing the rule down is what makes consistency possible at all, and telling the organizations converts an internal correction into something they can rely on and challenge.", recommended: true },
            { label: "Deny all three and refer the documentation requirement upward to the office that owns it for a formal change.", response: "Consistent, and it takes the cost of the division’s own record-keeping out on three organizations that did nothing wrong. Referring the requirement upward is right. Denying people in the meantime is not." },
          ],
        },
        transfer: {
          prompt: "Which decision in front of you could you write down in seven lines this week?",
          options: [
            "Name the decision, and where the record will live so the next person finds it",
            "Write the line about what it costs and whom, before anybody asks you",
            "Name the revisit point and the colleague who will ask you about it",
          ],
        },
        blocks: [
          { type: "text", heading: "Why the record is the decision", body: "<p>Most decisions in a division are recorded as outcomes. Approved. Denied. Required. Effective from this date. The outcome is the only part that travels, and within a couple of cycles the people who made the decision have moved on and the reason has gone with them. What is left is a rule nobody can explain, applied by people who were not there, to people who cannot find out what standard they were held to.</p><p>Recording the reasoning fixes several problems at once. It lets the next person apply the same rule to the next similar case, which is what consistency actually is. It gives the people affected something specific to challenge, which is what accountability actually is. And it lets a decision be revisited when the facts change, instead of hardening into a permanent state because reopening it would look like criticism of whoever made it.</p><p>None of this needs a new process or a form somebody has to approve. Seven lines, in the document where the decision already lives — the memo, the change request, the meeting record, the note in the file — will carry it. The discipline is writing them before the decision is final, rather than reconstructing them afterwards, once the reasoning has quietly smoothed itself out.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A multi-perspective decision review", summary: "Seven lines that hold the reasoning behind a decision, so it can be explained, challenged, applied to the next case and revisited. The example below continues the grant scenario.", fields: [
            { label: "The decision in one sentence", value: "We will accept an equivalent financial record in place of the audited statement that some community organizations cannot produce, and we will say so in writing to every applicant." },
            { label: "Obligations in tension", value: "Careful stewardship of public money and a verifiable record, against equal access for smaller and culturally specific organizations that have never had an audit and cannot afford one. The current design favors the first, and nobody chose that; it arrived with the form." },
            { label: "Who is affected, and who was in the room", value: "Applicants, the communities they serve, grant staff, and the reviewer who will audit this cycle. In the room: grant staff and the program manager. Spoken for: applicants, through questions they asked in past cycles. Missing: the smaller organizations themselves, and the office that owns the requirement." },
            { label: "Tests applied, and what they changed", value: "Publicity: the original reason — “they did not meet the requirement” — could not be said to an applicant without embarrassment. Burden: the requirement costs a small organization money and months it does not have, and costs a large one a phone call. The rule: said aloud, we were writing “organizations without audits do not receive grants,” which nobody would sign." },
            { label: "What we chose, and what it costs whom", value: "Accept an equivalent record, listed in the application itself with examples. Cost: grant staff spend longer reviewing unfamiliar records, and the unit takes on the work of explaining the change to the office that owns the requirement." },
            { label: "How people will be told, and how they can challenge it", value: "The change goes into the application and into a plain-language note to every organization that applied in the last cycle, with a named contact and a route for proposing a different equivalent record." },
            { label: "Revisit point, and what repair would require", value: "Look again after two cycles at the approval pattern by organization size. If anyone was denied under the old reading for this reason alone, tell them, explain what changed, and invite a new application without making them ask first." },
          ], action: "Copy the seven lines into the document where your decision already lives — the memo, the change request, the meeting record — and fill them in before the decision is final." },
          { type: "list", heading: "What makes a line usable rather than decorative", items: [
            "A decision sentence somebody outside the division could read once and understand.",
            "Obligations named in pairs, so the trade is visible: this protects one thing and it costs another.",
            "Standpoints marked honestly as at the table, spoken for, or missing. Writing “missing” is a legitimate and useful entry.",
            "A cost line that names who pays, not only how much.",
            "A challenge route with a person attached, not a general address and a hope.",
            "A revisit point with a date and an owner, plus what would make you look sooner.",
          ] },
          { type: "flashcards", heading: "The seven lines", cards: [
            { front: "The decision", back: "<p>One sentence, in words the person affected would use. If it takes a paragraph of internal shorthand, the decision is not clear yet, even to you.</p>" },
            { front: "Obligations in tension", back: "<p>Name at least two, and say which one this design favors. “This protects safety and it costs people their own choices” is a complete entry.</p>" },
            { front: "Who is affected, and who was in the room", back: "<p>Three marks: at the table, spoken for by somebody else, missing. Writing “missing” is far more useful than leaving the line blank.</p>" },
            { front: "Tests applied", back: "<p>Which of the six you ran, and what changed because of them. If nothing changed, say that; it is information about the decision too.</p>" },
            { front: "What we chose, and what it costs whom", back: "<p>The line people skip, and the one that makes the record worth keeping. Money, time, travel, waiting, paperwork, risk, dignity.</p>" },
            { front: "How people will be told, and how they can challenge it", back: "<p>Plain language, the channels people actually use, a named contact, and a route that does not require knowing how the division is organized.</p>" },
            { front: "Revisit point, and repair", back: "<p>When you will look again, what would make you look sooner, and what you would owe somebody if this turns out to have caused harm.</p>" },
          ] },
          { type: "leaderMove", heading: "Put the reasoning where the next person will find it", control: "You control whether the reasoning goes into the document that travels with the decision, or stays in your own notes.", failure: "Do not leave the reasoning in a meeting recollection, an email thread or your memory. All three leave when you do, and what remains is an unexplainable rule with your unit’s name on it.", next: "Before your next decision is final, put the seven lines into the record that will outlive you in this role, and tell the person who inherits the work where to find them." },
          { type: "statement", body: "A private reflection, for you alone, and a commitment you can actually keep. The decision I will write down this month is… The obligation it quietly gives up is… The standpoint I am missing is… And the point at which I will look at it again is… Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-27-4-check", question: "Which decision record can the next staff member actually apply to a similar case?", options: [
            { text: "“Request denied. Does not meet program requirements. Applicant notified.”", correct: false },
            { text: "“Request denied because the required document asks for something this applicant’s clinic will not produce. We are treating an equivalent record as sufficient from now on, have told all current applicants, and will review the pattern after two cycles. Contact: the program lead.”", correct: true },
            { text: "“Request denied after discussion. The team considered several factors and reached consensus.”", correct: false },
          ], feedbackCorrect: "Yes. It gives the real reason, the rule it creates, who was told, when it will be revisited and who to ask. The next person can apply it, and the applicant can challenge it.", feedbackIncorrect: "Ask what the next staff member would do with this record, and what the applicant could do with it. If neither can act on it, the reasoning did not survive." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Ethical decision-making",
    subtitle: "One page for a decision that pulls in more than one direction",
    quote: "Name the tension. Find the standpoint you are missing. Test the reason. Write down what it costs, and when you will look again.",
    use: {
      purpose: "Keep this beside you when a decision cannot be settled by looking up the rule: a policy change, an exception, a new standard, a denial, a contract term, a measure.",
      remember: [
        "These decisions are hard because more than one legitimate obligation is live: a person’s authority over their own life, safety, what the law requires, what the money allows, what oversight can verify, and whether the result lands fairly.",
        "The design has already resolved the tension. Your job is to find which obligation it quietly favors, and whether anybody chose that on purpose.",
        "Scarcity is a fact; who absorbs it is a choice. Always finish the sentence that begins “we do not have the resources.”",
        "Being spoken for is not being represented, and a comment period at the end tests wording rather than structure.",
        "A decision with no written reason and no revisit point becomes a rule nobody can explain and nobody can change.",
      ],
      doNext: "Take one decision you can shape this month, fill in the seven lines before it is final, and put the page where the decision lives.",
    },
    sections: [
      {
        heading: "The six obligations to name out loud",
        items: [
          "A person’s authority over their own life, including the authority to accept risk and to refuse help.",
          "Safety, in the narrow statutory shape it actually has: protection standards, reporting, and tight limits on restrictive interventions.",
          "What the law truly requires, separated from what a form has always said.",
          "What the money allows, finished with the sentence about who therefore goes without.",
          "What quality oversight can verify, and the pull that exerts toward whatever documents well.",
          "Whether the result lands the same way on everyone, checked before the rule is final.",
        ],
      },
      {
        heading: "The six tests, about ten minutes",
        items: [
          "Publicity: say the real reason to the person it affects, in their words.",
          "The rule: state what you are deciding for every case like this one, and see if you would sign it.",
          "Burden: name who pays, in money, time, travel, waiting, paperwork, uncertainty and dignity.",
          "Power: would this be the same decision if the people affected had more staff or better representation?",
          "Evidence: separate what you know from what you assume, and check what silence is actually measuring.",
          "Reversal: on this evidence, decided about you by people who never met you — what would you need to accept it?",
        ],
      },
      {
        heading: "The seven-line decision review",
        items: [
          "The decision, in one sentence a person outside the division could read.",
          "Obligations in tension, and which one this design favors.",
          "Who is affected, and who was at the table, spoken for, or missing.",
          "Tests applied, and what changed because of them.",
          "What we chose, and what it costs whom.",
          "How people will be told, and how they can challenge it.",
          "Revisit point, and what repair would require if this causes harm.",
        ],
      },
      {
        heading: "Formal decisions, and the offices that make them",
        items: [
          "Whether a licensing standard or rule is met, and how a practice must change: the responsible DHS licensing and program offices.",
          "Whether something must be reported as maltreatment, and what happens next: the reporting route set out in statute, not a workgroup or a supervisor’s reading.",
          "Legal interpretation, including whether a requirement can be read differently: the department’s legal office.",
          "Data classification, and what the state must tell a person when it asks for private information about them: the responsible authority and the department’s data practices office.",
          "Independent review of the care and treatment of people receiving services: the Minnesota Office of Ombudsman for Mental Health and Developmental Disabilities.",
          "Anything involving Tribal Nations or tribal human services: the Department of Human Services offices that handle tribal matters and the Office of Indian Affairs, first and always.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Policy and program staff, whose drafts turn a tension into a rule for everybody — a useful place to start in this area.",
          "Quality, compliance and performance staff, who decide what gets checked, what a finding means and what a unit is asked to fix — the deeper material here is for you.",
          "Leaders, supervisors and managers, who can make naming the trade a normal part of how a decision meeting runs.",
          "Contracts, grants and procurement staff, whose requirements decide which organizations can compete at all.",
          "Data, research and evaluation staff, whose measures quietly tell programs which things matter.",
          "Communications and administrative staff, who write the sentence a person actually reads when a decision reaches them.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "History, disability, and public institutions",
          "Race, disability, and unequal outcomes",
          "Trauma-responsive public administration",
          "Power, conflict, and repair",
          "Complex issue inquiry",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Statutes, chapter 245D, Home and Community-Based Services Standards", href: "https://www.revisor.mn.gov/statutes/cite/245D", note: "Minnesota's licensing standards for home and community-based services, including service recipient rights (245D.04), protection standards (245D.06) and the narrow conditions on emergency use of manual restraints (245D.061)." },
    { title: "Minnesota Rules, chapter 9544, Positive Support Strategies and Restrictive Interventions", href: "https://www.revisor.mn.gov/rules/9544/", note: "The state rule on positive support strategies and the tightly limited circumstances in which restrictive interventions may be used in licensed services." },
    { title: "Minnesota Statutes, section 43A.38, Code of Ethics for Employees in the Executive Branch", href: "https://www.revisor.mn.gov/statutes/cite/43A.38", note: "The ethics requirements that apply to executive branch state employees, covering acceptance of gifts and favors, use of confidential information, use of state property and conflicts of interest." },
    { title: "Minnesota Office of Ombudsman for Mental Health and Developmental Disabilities", href: "https://mn.gov/omhdd/", note: "The independent state office that reviews the quality of services and the treatment of people receiving services for mental illness, developmental disabilities and substance use disorder." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's advisory council on disability policy, access and rights, including guidance for state agencies on accessible public processes and materials." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the governance, leadership, community partnership and accountability standards used in this module." },
    { title: "plainlanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Practical guidance for writing a decision, a reason or a notice that a person can read once and act on." },
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials and accessible instruction." },
  ],
};

export default pack;
