import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Internal leadership · Module 30: Equitable policy and procedure governance.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-30-policy-procedure-governance",
    indexNumber: 1172,
    seriesLabel: "Intercultural Practice and Equity · Internal leadership",
    title: "Equitable Policy and Procedure Governance",
    subtitle: "Accessibility, plain language, cultural responsiveness and stakeholder impact are cheap to fix while a draft is still a draft. Four lessons on building the review stage that looks at them before the requirements lock.",
    scope: "For internal DHS and DSD staff who set up, run, clear or live with review steps: policy and program staff; quality, compliance and performance staff; contracts, fiscal, grants and procurement staff; executive and senior leaders; and the communications, data and operations staff whose work begins the moment a document is released. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota DSD examples, scenarios, sorting and flashcard practice, private reflection prompts, and a one-page review stage you can copy into a workflow you own",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/accessibility-leadership.jpg",
    coverAlt: "A mixed-race team meets around a sunlit conference table in a Minnesota office.",
    introTranscript: "Almost everything a division decides reaches people as writing: a bulletin, a manual section, a form, a letter template, a contract clause, a work instruction. By the time most of that writing is reviewed for accessibility, plain language or cultural fit, the requirements inside it are already settled, and the only thing left to do is repair. This module is about the step before that. It covers what a review stage actually decides, four checks that find genuinely different problems, where the stage has to sit and what authority it needs, and how to keep it from turning into either a rubber stamp or a wall. It ends with a one-page review stage you can fill in for one workflow and take to the person who owns it.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Describe what an equity and access review stage decides, and find the point in your own workflow after which a requirement can no longer be changed without an amendment.",
        "Turn accessibility, cultural responsiveness, stakeholder impact and plain language into four questions a reviewer can answer with evidence rather than with an impression.",
        "Place the review where requirements are still open, and state in writing whether it advises, conditions or holds.",
        "Set a service timeline and an emergency route with a named approver and a required back-check, so urgency does not quietly become the ordinary path.",
        "Draft a one-page equity and access review stage for one real workflow, including what is recorded, who sees it, and how the stage itself will be examined.",
      ],
      evidence: [
        "Four worked scenarios drawn from bulletin publishing, form redesign, a review that has become a bottleneck, and a trial that produced no findings at all.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that assigns real findings to the check that would catch them, and separates what the review decides from what other offices and affected people decide.",
        "A completed one-page review stage for one workflow, with a trigger, a placement, decision rights, a timeline and a way out.",
      ],
      appliedNextStep: "Choose one document type your team produces regularly. Draw its path from first draft to the day it reaches people, mark the last point at which a requirement could still change, and write the review stage that would sit immediately before that point.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in ADA Title II, Section 504 or Section 508 requirements, or in the state's digital accessibility standard, that changes what a document or procedure must provide before release",
        "A change in how DHS or DSD drafts, clears, publishes or amends bulletins, manual sections, forms and work instructions",
        "Feedback from compensated community reviewers or from division drafting staff that the review stage described here does not match how drafts actually move",
      ],
      relatedDoor: "Formal decisions about legal sufficiency, rulemaking, clearance and publication belong to the responsible DHS policy, legal and communications offices; this module helps you design the review that happens before those decisions, not replace them.",
      toolkitQuestion: "Who could be helped, burdened, excluded or misunderstood by what this draft requires, and at what point in our own workflow could that still have been changed?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-30-1",
        number: 1,
        title: "What a review stage decides, and when it is too late to add one",
        summary: "Governance is not a meeting. It is a written answer to what triggers a review, what gets examined, who decides, and what happens when the answer is not yet.",
        minutes: 11,
        learning: {
          objective: "Describe what an equity and access review stage decides, and identify the point in your own division's workflow after which a requirement becomes expensive to change.",
          takeaways: [
            "Governance is the set of rules about which drafts get reviewed, at what point, against what criteria, by whom, and with what authority to say not yet. Most divisions already have some of it; the question is where accessibility and equity sit inside it.",
            "Accessibility, translation, plain language and outside input usually arrive after the requirements are settled. At that point they can only be repair work, and repair work is the first thing a publication calendar defers.",
            "A policy that reads the same for everyone can still cost different people very different amounts of time, travel, money and proof. Uniform wording is not the same as an even effect.",
            "Placement decides what a review is able to reach. A reviewer handed a cleared document and a release date can improve the document and almost never the requirement inside it.",
          ],
          evidence: "A scenario about a bulletin already cleared for release, a walk through the same revision as four different desks see it, and a knowledge check on what a final-step review can actually accomplish.",
          appliedNextStep: "Draw your own division's path for one kind of document, from first draft to the day it reaches people, and mark the last point at which a requirement could still be changed without a formal amendment.",
        },
        scenario: {
          context: "A DSD program analyst has finished a revised procedure for a waiver service change. Legal and communications clearance are done and the bulletin posts Friday. Alternate formats and translations are queued for after posting. A quality analyst reads the draft and notices two things: the new step requires a document most people have to request in person from a county office, and the response window is ten days counted from the date printed on the letter.",
          prompt: "What is the most useful thing to do with that observation?",
          options: [
            { label: "Post on schedule and open a follow-up item covering the alternate formats, the translations and the ten-day window.", response: "This is the usual outcome, and it is how access work becomes a permanent queue. Once the bulletin is out, the ten-day window is not a draft decision any more; it is a requirement people are living under, and changing it becomes an amendment and a correction notice rather than an edit." },
            { label: "Post on schedule, and add a line inviting anyone who needs the bulletin in another format or language to contact the division.", response: "The line is worth having and should be there anyway. But it moves the work onto the reader and onto whoever answers that phone, and it leaves the requirement untouched. The people least able to make that call are usually the ones the requirement already costs the most." },
            { label: "Ask the owner of the bulletin to hold it one cycle and route it through a named review that examines accessibility, plain language, cultural responsiveness and stakeholder impact, with the decision recorded either way.", response: "This treats the problem as what it is: a governance problem. A one-cycle hold is a decision a named person makes and records, not a personal veto, and it puts the real question in front of someone who can answer it. Was the in-person document intended, and what does the ten-day clock cost a person whose mail arrives late or goes to a former address? If a legal deadline means the timing cannot move, that goes through the exception route and is recorded with a name on it.", recommended: true },
          ],
        },
        transfer: {
          prompt: "Where does the last real chance to change a requirement sit in your own work?",
          options: [
            "Name one kind of document your team produces regularly: a bulletin, a manual section, a form, a letter template, a contract clause or a work instruction.",
            "Write down each step it passes through and who has to agree at each one.",
            "Mark the step after which a change stops being an edit and becomes an amendment, a reissue or a correction notice.",
            "Note where accessibility, translation, plain language and outside review currently sit relative to that mark.",
          ],
        },
        blocks: [
          {
            type: "text",
            heading: "Governance is the part nobody sees",
            body: "<p>Almost everything the Disability Services Division decides reaches people as writing. A manual section, a bulletin, a form, a letter template, a web page, a contract clause, a work instruction a lead agency follows. None of it is neutral. Every requirement inside it quietly decides who will find the process straightforward and who will spend a month on it.</p><p>Governance is the set of rules about what happens to that writing before it goes out: which drafts get reviewed, at what point, against what criteria, by whom, and with what authority to say not yet. Divisions almost always have some of this already. Legal review, communications review, a clearance step, an accessibility fix near the end, translation for the documents someone flagged as vital. The question this module asks is narrower and more useful. Are accessibility, plain language, cultural responsiveness and stakeholder impact examined while the requirements are still open, or only after they are settled?</p><p>The difference is not a matter of how much anyone cares. Reviewers who arrive after clearance are handed a finished document and a release date. They can catch a missing heading structure, an unlabeled table, an image with no text alternative. They cannot ask why the process requires an in-person visit, because that question is no longer in front of them. Late review turns design questions into repair work, and repair work is what a busy calendar defers first.</p>",
          },
          {
            type: "accordion",
            heading: "Where access work usually sits, and what that placement costs",
            items: [
              { title: "Accessibility arrives as remediation", body: "<p>A document is written, cleared, and then sent for an accessibility fix. Headings get tagged, contrast gets corrected, a text alternative is added. All of that is real work and worth doing. None of it touches the procedure: the ten-day clock, the in-person signature, the phone line open only on weekday mornings. Those are access questions too, and by the time the remediation step sees the file, they are decisions rather than options.</p>" },
              { title: "Translation is scheduled after the decision", body: "<p>Translation placed at the end has two effects. The first is timing: people who read in another language receive the requirement later than everyone else, and the clock usually started for them on the same day. The second is harder to see. A sentence written without translation in mind is often built out of idioms, program shorthand and long conditional clauses, and the translator inherits all of it. Writing with the translated version in view changes the original sentence, and that only happens if translation is present while the sentence is still being written.</p>" },
              { title: "Outside input is collected after the choice is made", body: "<p>Asking people what they think of a finished draft is a different activity from asking them what the requirement should be. The first produces reactions the division can acknowledge; the second produces design. When people with disabilities, families, interpreters and culturally specific organizations are brought in as compensated advisors and co-designers, the value comes almost entirely from the timing. After clearance, the only honest thing to offer them is a chance to comment on something that is not going to change.</p>" },
              { title: "Plain language is treated as copy editing", body: "<p>Plain language is often handled as a final pass over the wording: shorter sentences, simpler words, fewer acronyms. Useful, and not the same thing. The plain language question that matters in governance is what the reader has to do, find, prove or wait for, stated in one sentence. Answering that question frequently reveals that the requirement itself is unclear, not just the sentence describing it, and that discovery is worth much more before clearance than after.</p>" },
            ],
          },
          {
            type: "tabs",
            heading: "One revision, four desks",
            tabs: [
              { label: "Program analyst", body: "<p>She has a policy change to implement, an effective date she did not choose, and three other assignments. The draft is technically correct and cleared. The access items are real and she has queued them; the bulletin has to go out on Friday because the change takes effect the following month.</p>" },
              { label: "Lead-agency worker", body: "<p>He gets the bulletin the same day the public does. He will spend the next month explaining the ten-day clock to people who called on day eleven, and telling them that the date on the letter, not the day it arrived, is what counts. Nobody asked him what the last version of this process produced in phone calls.</p>" },
              { label: "The person who receives the letter", body: "<p>She reads at a different pace than the person who wrote it, works a shift that ends after the county office closes, and does not hold the utility account at the address the letter was sent to. She is not confused. She is being asked for something the process assumed she already had.</p>" },
              { label: "Quality and performance analyst", body: "<p>She has last year's completion figures for this step and knows which parts of the state fall behind on it. Nobody asked her before the draft was written, and the figures will show the effect of this revision about nine months from now, long after the decision that produced it has been forgotten.</p>" },
            ],
          },
          {
            type: "leaderMove",
            heading: "Put the stage before the lock, not after it",
            control: "You control where a review sits in a workflow you own, and whether its criteria are written down anywhere a drafter can read them.",
            failure: "Do not add reviewers to the end of a process and call it governance. A reviewer who receives a cleared document and a release date can only recommend repairs, and will be blamed for the delay when they do.",
            next: "Find the last point in one of your workflows where a requirement can still change, and move the access and equity questions to the step before it.",
          },
          {
            type: "quote",
            text: "We did everything right on that bulletin. Legal cleared it, communications cleared it, the format fix went in two weeks later. And then a county worker told me she had spent the whole month explaining that the ten-day clock started on the date printed on the letter, not the day it landed in the mailbox. She could have told us that in five minutes. Nobody asked her, because by the time anyone thought to, the letter was already out.",
            cite: "Composite DSD staff perspective, illustrative",
          },
          {
            type: "knowledgeCheck",
            id: "ipe-30-1-check",
            question: "A division adds an accessibility reviewer to the final step of its publishing workflow, immediately before a document is released. What is the most accurate description of what that change accomplishes?",
            options: [
              { text: "It closes the gap, because every document now receives an accessibility review before it reaches the public.", correct: false },
              { text: "It will catch document-level problems such as heading structure, contrast and text alternatives, and it will rarely change a requirement, because by the final step the requirements are already settled.", correct: true },
              { text: "It adds delay without benefit, since accessibility work is handled more efficiently as a correction after release.", correct: false },
            ],
            feedbackCorrect: "Yes. Placement decides what a review can reach. A final-step reviewer sees a finished document, so document findings are the only findings available to them.",
            feedbackIncorrect: "Think about what is still changeable at that point in the workflow. A reviewer at the final step can improve the document; the requirement inside it has already been decided, cleared and scheduled.",
          },
        ],
      },
      {
        id: "ipe-30-2",
        number: 2,
        title: "Four checks that find different things",
        summary: "Accessibility, plain language, cultural responsiveness and stakeholder impact overlap, and none of them substitutes for the others. Each becomes useful only when it is a question someone can answer with evidence.",
        minutes: 11,
        learning: {
          objective: "Turn accessibility, plain language, cultural responsiveness and stakeholder impact into four questions a reviewer can answer with evidence, and identify which check would find a given problem in a draft.",
          takeaways: [
            "A document can be tagged, readable and plainly written and still assume a household, a schedule, an account or a document the reader does not have. That is the check the first two cannot perform.",
            "A check is usable only if it can be answered yes, no or not yet, with something a reviewer can point at. Is this culturally responsive is not answerable. What does this draft assume the reader already has is.",
            "Accessibility applies to the procedure, not only to the document. A ten-day window, a weekday-morning phone line and an in-person signature are access questions even when the wording is perfectly clear.",
            "Stakeholder impact is the check skipped most often, because it is the one that asks what the division already knows about who completes this process and who does not, and who read the draft from outside the drafting team.",
          ],
          evidence: "A sorting exercise that assigns real findings to the check that would catch them, flashcards with the question behind each check, and a scenario about a form that passes three checks cleanly and fails the fourth.",
          appliedNextStep: "Take one page of something your team wrote and answer all four questions against it in writing. Note which question you could not answer without asking someone else, and name that someone.",
        },
        scenario: {
          context: "A DSD workgroup is finishing a redesigned request form for a support service. The document is tagged and works with a screen reader. The headings are descriptive, every deadline is stated in days with a start date, and no sentence carries more than one requirement. The form has one signature block, labeled for a parent, spouse or legal guardian, and asks the applicant to attach a recent utility bill in their own name as proof of address.",
          prompt: "Which finding is this review most likely to miss, and why does it matter?",
          options: [
            { label: "Nothing significant. The form is accessible and plainly written, and between them those two checks cover the substance of a document review.", response: "Accessibility and plain language are both strong here, and they are the two checks most teams are equipped to run well. That is exactly why the other two get skipped. A form can be easy to read and easy to navigate and still ask for something a large number of people cannot produce." },
            { label: "The signature block and the proof of address. The form assumes a household shape and an account in the applicant's own name, and both assumptions exclude people supported by someone other than a parent or spouse, people living with extended family, and people who do not hold the utility account.", response: "Yes. This is the cultural responsiveness check doing work the other three cannot do. The next question belongs to stakeholder impact: how many people, in which parts of the state, and does the division already have a way to know? A second signature line and a wider list of acceptable proof are small changes while this is still a draft, and an amendment afterward.", recommended: true },
            { label: "The reading level. A form like this should be written for the widest possible audience, and that is the central equity question in any document review.", response: "Reading level matters and this draft has handled it. But a plain sentence asking for a document the reader cannot obtain is still a barrier. Clear wording can make an exclusion easier to read without making it any easier to meet." },
          ],
        },
        transfer: {
          prompt: "Which of the four questions can your team currently answer without leaving the room?",
          options: [
            "Ask each of the four questions against one draft you are working on now.",
            "Mark which ones your team can answer from what it already has in front of it.",
            "Mark which ones need someone outside the drafting team, and name who that is.",
            "Write down what a drafter would have to bring so each question could be answered at the review rather than weeks after it.",
          ],
        },
        blocks: [
          {
            type: "text",
            heading: "Four checks, because they see different things",
            body: "<p>It is tempting to collapse these into one question about fairness and trust people to apply it. In practice that produces reviews where everyone agrees the draft seems fine, and the findings depend entirely on who happened to be in the room. Four separate checks work better because each one has a different instrument and finds a different class of problem.</p><p>Accessibility asks whether a person using a screen reader, magnification, captions, a keyboard alone or a slower processing pace can get through the document and the procedure. Plain language asks whether the requirement can be understood on a first read: what the reader must do, find, prove or wait for, and by when, counted from what. Cultural responsiveness asks what the draft assumes the reader already has — a household shape, a schedule, an account, a document, a language, a level of trust in a state agency. Stakeholder impact asks who is helped, burdened, excluded or misunderstood by the requirement, in what numbers, and what the division already knows about that.</p><p>The last of the four is the one most likely to be dropped, and it is often the only one that needs anything the drafting team does not already hold. It requires a look at completion figures, a conversation with the people who answer the phone afterward, and a draft read by someone the requirement will land on, invited and paid for that work. That is more effort than the other three. It is also where the surprises are.</p>",
          },
          {
            type: "flashcards",
            heading: "The question behind each check",
            cards: [
              { front: "Accessibility", back: "<p>Can a person get through this document and this procedure using a screen reader, magnification, captions, a keyboard alone, or at a slower pace? The procedure counts: hours, channels, windows, signatures and formats are all part of the answer.</p>" },
              { front: "Plain language", back: "<p>State the requirement in one sentence: what the reader must do, find, prove or wait for, by when, counted from what. If you cannot do that, the problem is usually the requirement rather than the wording.</p>" },
              { front: "Cultural responsiveness", back: "<p>What does this draft assume the reader already has? A parent or spouse, a stable address, an account in their own name, an email inbox, a weekday morning, a reason to trust the return address on the envelope.</p>" },
              { front: "Stakeholder impact", back: "<p>Who is helped, burdened, excluded or misunderstood by this requirement, in what numbers, and what does the division already know? Who read the draft from outside the drafting team, and were they paid for that time?</p>" },
              { front: "Why four and not one", back: "<p>Because a draft can pass three and fail the fourth without anyone noticing. Tagged, readable and clear is not the same as possible. Four questions give four different chances to catch it.</p>" },
            ],
          },
          {
            type: "accordion",
            heading: "What each check actually looks at",
            items: [
              { title: "Accessibility: the document and the procedure", body: "<p>In the document: heading structure that matches the reading order, real text rather than a scan, tables with row and column labels, links that say where they go, text alternatives that carry the information the image carries, captions on anything recorded, and color that is never the only way a deadline or a status is shown. In the procedure: whether the response window allows for mail delay, whether the only correction channel is a phone line with narrow hours, whether an in-person signature is genuinely necessary or simply traditional, and whether the format someone needs exists on the day the document is released rather than weeks later.</p>" },
              { title: "Plain language: one sentence, no hiding places", body: "<p>Write the requirement in one sentence and see what breaks. Promptly, appropriate documentation, as needed, may be required and in a timely manner are all places where a decision was not made. Each of them will be settled later by whoever answers the phone, which means the same requirement will be applied differently across the state. Name the days, name the start date, name who decides, and say what counts as proof.</p>" },
              { title: "Cultural responsiveness: what is assumed, not what is stated", body: "<p>This check reads for the unstated. A signature line that assumes a nuclear household. A comparison to a private insurance plan the reader may never have held. A schedule that assumes daytime availability. An instruction to bring the person who makes decisions for you, in a division whose own commitments are built around supported decision-making. A request for documents that people who have moved between countries, shelters or care settings frequently do not hold. The national standards for culturally and linguistically appropriate services are a useful reference here, and their governance and written-communication standards are aimed at precisely this step.</p>" },
              { title: "Stakeholder impact: who, how many, and how would we know", body: "<p>Start with what the division already has: completion and denial figures for this step, appeals, complaints, the questions that reach the help line, the patterns lead agencies report. Then ask the question the figures cannot answer, which is why. That part requires people who have met the process, invited as compensated advisors and reviewers rather than as an audience, and told afterward what happened to what they said.</p>" },
            ],
          },
          {
            type: "sorting",
            id: "ipe-30-2-sort",
            heading: "Which check would find this?",
            categories: ["Accessibility check", "Plain language check", "Cultural responsiveness check", "Stakeholder impact check"],
            items: [
              { text: "The published procedure is a scanned image, so a screen reader finds no text on the page.", category: "Accessibility check" },
              { text: "The deadline appears only inside a color-coded table, and nowhere in the text.", category: "Accessibility check" },
              { text: "The notice says documentation must be submitted promptly, without saying how many days or counted from what.", category: "Plain language check" },
              { text: "One sentence carries three separate requirements and two exceptions.", category: "Plain language check" },
              { text: "The form has a signature line for a parent or spouse and no line for anyone else who supports the person.", category: "Cultural responsiveness check" },
              { text: "The letter explains a benefit by comparing it to a private insurance plan the reader may never have held.", category: "Cultural responsiveness check" },
              { text: "Division figures show that one group of applicants completes this step far less often than others, and nobody has asked why.", category: "Stakeholder impact check" },
              { text: "Nobody who has actually been through this process has read the draft.", category: "Stakeholder impact check" },
            ],
          },
          {
            type: "leaderMove",
            heading: "Make every check answerable",
            control: "You control the wording of the criteria. A criterion is a question with an answer and a piece of evidence behind it, not a value the reviewer is asked to affirm.",
            failure: "Do not write criteria like considers cultural context or is accessible to all users. Nobody can fail them, which means nobody can pass them either, and the record will show a stage that never found anything.",
            next: "Rewrite one of your current review criteria so it can be answered yes, no or not yet, and name the single piece of evidence that settles it.",
          },
          {
            type: "knowledgeCheck",
            id: "ipe-30-2-check",
            question: "A draft procedure is tagged for screen readers, written at a low reading level, and states every deadline in days with a start date. It also requires an original document that is issued only by an office open on weekday mornings. Which statement is best supported?",
            options: [
              { text: "The draft is ready. Accessibility and plain language are the two checks that carry the substance, and both are satisfied.", correct: false },
              { text: "The draft passes the accessibility and plain language checks and has an unresolved finding that belongs to the cultural responsiveness and stakeholder impact checks, because a clearly written requirement can still be one many people cannot meet.", correct: true },
              { text: "The finding belongs to the accessibility check, because anything a person cannot do is by definition an accessibility barrier.", correct: false },
            ],
            feedbackCorrect: "Yes. The four checks are separate instruments. Clear and navigable is not the same as possible, and naming which check owns the finding is what tells you who has to be in the room to resolve it.",
            feedbackIncorrect: "Ask what each check is actually looking at. Two of them examine whether the document can be read and understood. The other two examine what the requirement assumes the reader has, and what it costs the people who have to meet it.",
          },
          {
            type: "statement",
            body: "A private reflection, for you only and never collected: think of a requirement you helped write, review or enforce. What did it assume the reader already had — a document, a stable address, an account in their own name, a family member, a weekday morning, an email inbox? Who inside your own division would have known that before it went out, and what stopped them from being asked?",
          },
        ],
      },
      {
        id: "ipe-30-3",
        number: 3,
        title: "Placement, authority, and the answer not yet",
        summary: "A stage with undefined authority becomes a comment box or a wall. Deciding in writing whether it advises, conditions or holds is most of the design.",
        minutes: 11,
        learning: {
          objective: "Place an equity and access review at the point where requirements are still open, and state in writing what authority it carries, how long it takes, and what happens when a finding cannot be resolved before release.",
          takeaways: [
            "An undefined authority resolves itself badly in both directions: into a comment box everyone learns to ignore, or into an unpredictable wall that people route around. Saying plainly whether the review advises, conditions or holds is kinder than either.",
            "Two touch points work better than one. An early look while the requirements are open, then a short confirmation before release that the findings were resolved or knowingly accepted.",
            "An emergency route with a named approver and a required back-check is what keeps urgent from becoming the ordinary path. Without one, the first genuine deadline teaches everyone that the stage is optional.",
            "Some questions do not belong to the review. Legal sufficiency, rulemaking and clearance belong to the responsible DHS offices, and what a requirement costs in practice belongs partly to the people who have to meet it, invited and paid for that work.",
          ],
          evidence: "A scenario about a review that both drafters and reviewers call broken for opposite reasons, a sorting exercise separating what the stage decides from what other offices and affected people decide, and a knowledge check on decision rights.",
          appliedNextStep: "Write one paragraph that states, for a workflow you own or influence, what the review examines, when it happens, what authority it carries, how many working days it takes, and who can approve an exception.",
        },
        scenario: {
          context: "A DSD senior leader hears two complaints in the same week. Drafting staff say the equity and access review has become a bottleneck that produces findings after clearance, when nothing can be changed without restarting. Reviewers say drafts reach them finished, with a release date already attached, and that their findings are written down and then overtaken by the schedule. The leader asks for a proposal.",
          prompt: "Which proposal addresses what both groups are actually describing?",
          options: [
            { label: "Move the review to the end of the workflow so reviewers see only final drafts, and limit findings to the document itself.", response: "This makes the calendar more predictable and guarantees the complaint the reviewers are making. It formalizes repair work as the only available outcome. It will also look like an improvement in the record, because the number of late findings will fall." },
            { label: "Keep the placement and make the review advisory only, so a finding never delays a release date.", response: "Predictable, and hollow. An advisory-only stage in a division under schedule pressure produces a careful record of things that were noticed and not changed. If that is genuinely the intent, it is better to say so plainly than to let staff and partners believe the review is protecting something." },
            { label: "Move the review earlier, to the point where requirements are still open; state in writing what authority it carries; give it a service timeline in working days; and add an emergency route with a named approver and a required back-check.", response: "This answers both complaints, because both are describing the same defect from opposite sides. Early placement gives reviewers something they can affect. A written authority and a published timeline let drafting staff plan instead of guess. The emergency route keeps real deadlines from breaking the stage, and the back-check keeps the emergency route from quietly becoming the normal one.", recommended: true },
          ],
        },
        transfer: {
          prompt: "What authority does your review actually carry today?",
          options: [
            "Ask three people who use the workflow what they believe happens when a reviewer objects.",
            "Compare their answers with what is written down anywhere.",
            "Write the sentence that would settle it: this review advises, conditions or holds.",
            "Name the person who can approve an exception, and what they have to record when they do.",
          ],
        },
        blocks: [
          {
            type: "text",
            heading: "Placement first, because placement decides everything else",
            body: "<p>Ask where the requirements stop being open. In most workflows there is a clear point: the draft goes for clearance, or the effective date is published, or the form goes to print, or the contract language goes out with the solicitation. Before that point, a finding is an edit. After it, the same finding is an amendment, a correction notice, or a note for the next revision cycle.</p><p>The review belongs immediately before that point, and it works better as two touch points than one. The first is an early look, while the requirement is still a proposal and the drafting team still has options. The second is short: a confirmation before release that the findings from the first look were resolved, or accepted in writing by a person with a name. The second touch point takes very little time when the first one happened, and it is the only thing that stops findings from evaporating between review and release.</p><p>Everything else in the design follows from placement. Authority matters because an early reviewer is asking for changes that cost the drafting team real work. A timeline matters because an early review that takes an unknown number of days will be skipped by anyone with an effective date. An exception route matters because some deadlines are set in statute and will not move for anyone's review.</p>",
          },
          {
            type: "tabs",
            heading: "Three honest ways to set decision rights",
            tabs: [
              { label: "Advisory", body: "<p>The review records findings; the document owner decides what to do with them. Low friction, fast, and appropriate for low-risk material and for a stage in its first weeks. Its failure mode is predictable: under schedule pressure the findings accumulate and nothing changes, and staff learn that participating is optional. If you choose advisory, pair it with a record that shows what was found and what was done, and look at that record on a set date.</p>" },
              { label: "Conditional", body: "<p>Findings on the four questions must be resolved before release, or accepted in writing by the named owner of the document. The reviewer does not decide; they make the decision visible and attach a name to it. This is the setting that works for most bulletin, form and manual workflows, because it respects the owner's authority while making silent deferral impossible. Its failure mode is paperwork, which you avoid by keeping the accepted-finding record to one line.</p>" },
              { label: "Hold", body: "<p>Release waits until specified findings are resolved. Appropriate for a narrow, named class of findings: a document that cannot be read by the people it is addressed to, a requirement with no lawful way to comply, a translation that has not happened for a document the division treats as vital. Use it sparingly and write the list down. A hold authority that is broad and undefined will be routed around within a month, and you will not hear about it.</p>" },
            ],
          },
          {
            type: "list",
            heading: "What the drafter brings, so the review is not a guessing game",
            ordered: false,
            items: [
              "The draft in a working format, not a flattened image, so reviewers can read structure as well as words.",
              "The requirement stated in one sentence: what a person must do, find, prove or wait for, by when, counted from what.",
              "What already exists in other formats and languages, and what would have to be produced before release.",
              "What the division already knows about who completes this step and who does not, if anyone has looked.",
              "Who read the draft from outside the drafting team, whether they were paid, and what they said.",
              "The effective date and where it comes from: statute, a federal requirement, a system change, or a decision that could move.",
            ],
          },
          {
            type: "sorting",
            id: "ipe-30-3-sort",
            heading: "Who decides this?",
            categories: ["Decided by the review stage", "Decided by the responsible DHS office", "Decided with the people affected"],
            items: [
              { text: "Whether the requirement is legally sufficient and whether the change has to go through rulemaking.", category: "Decided by the responsible DHS office" },
              { text: "Whether the draft is cleared and published, and on what date.", category: "Decided by the responsible DHS office" },
              { text: "Whether the requirement can be understood on a first read, and whether it states days and a start date.", category: "Decided by the review stage" },
              { text: "Whether the findings from the early look were resolved before release or accepted in writing, and by whom.", category: "Decided by the review stage" },
              { text: "Whether the draft is ready to release before the formats and translations people need exist.", category: "Decided by the review stage" },
              { text: "Which part of this process is hardest, and what it actually costs in time, travel and proof.", category: "Decided with the people affected" },
              { text: "What a workable notice period looks like for people who move often or share a mailing address.", category: "Decided with the people affected" },
            ],
          },
          {
            type: "leaderMove",
            heading: "Say out loud what happens when the answer is not yet",
            control: "You control whether not yet is a defined outcome with a named owner and a date, or an awkward pause that the release calendar resolves on its own.",
            failure: "Do not leave an unresolved finding in a record with no owner. An accepted risk with nobody's name on it is not an accepted risk; it is a finding that was quietly dropped.",
            next: "Write the not yet path for one workflow: what the reviewer records, who accepts the open finding, what date the back-check happens, and who is told.",
          },
          {
            type: "text",
            heading: "Where the continuum shows up in a review stage",
            body: "<p>This program uses the intercultural development continuum — denial, polarization, minimization, acceptance, adaptation and integration — as its theory of change. It describes how an organization's default way of seeing difference tends to move over time. It is never a label, a score, or a record about any individual, and nothing in this module asks anyone to place themselves or a colleague on it.</p><p>A review stage is one of the places where an organization's habitual position shows most plainly, because it is where difference becomes a decision. Minimization sounds reasonable and is easy to say out loud: the policy applies to everyone the same way, so it is already fair. In a review, it shows up as a preference for uniform wording, and as discomfort with a finding that says the same requirement costs different people very different amounts.</p><p>Acceptance sounds like a genuine question asked without defensiveness: what does this requirement cost someone whose week does not look like mine, and how would we find out? Adaptation is what happens next, when the draft actually changes — a second signature line, a wider list of acceptable proof, a window counted from receipt rather than from the date printed on the letter. A review stage is worth building mostly because it gives acceptance somewhere to go. Without it, the question gets asked in a hallway and the draft goes out unchanged.</p>",
          },
          {
            type: "knowledgeCheck",
            id: "ipe-30-3-check",
            question: "A division sets up an equity and access review but never states what authority it carries. Six months later, what is the most likely result?",
            options: [
              { text: "Staff will settle into a shared understanding through practice, which is usually more durable than a written rule.", correct: false },
              { text: "It will resolve into one of two things: a record of findings that changed nothing, or an unpredictable obstacle that drafting teams learn to route around, and leadership will hear about whichever one is more annoying.", correct: true },
              { text: "Nothing much, because decision rights matter far less than having capable reviewers and clear criteria.", correct: false },
            ],
            feedbackCorrect: "Yes. Undefined authority does not stay undefined; it gets settled by schedule pressure, in whichever direction the pressure runs. Writing it down is what lets both drafters and reviewers plan.",
            feedbackIncorrect: "Consider what happens the first time a finding meets a firm release date with nothing written down about who decides. That single outcome becomes the precedent everyone works from afterward.",
          },
          {
            type: "statement",
            body: "A private reflection, for you only and never collected: think of a time your own objection to a draft was overtaken by a deadline. What would have had to be written down beforehand for that conversation to go differently — a timeline, a named decider, an exception route, or simply a place to record that the finding was accepted and by whom?",
          },
        ],
      },
      {
        id: "ipe-30-4",
        number: 4,
        title: "Standing it up, and keeping it honest",
        summary: "One page, one document type, one workflow. Then the three ways this kind of stage fails, and the small number of things worth keeping track of.",
        minutes: 11,
        learning: {
          objective: "Draft a one-page equity and access review stage for one real workflow, and name the three ways such a stage fails along with the check that would catch each one.",
          takeaways: [
            "Start with one document type and one workflow. A stage that covers everything on paper and nothing in practice teaches people that the stage is decorative, and that lesson is hard to unteach.",
            "Three failure modes account for most of it: the rubber stamp, where nothing is ever found; the wall, where there is no timeline and no way out; and the parallel record, where findings are written down carefully and the document goes out unchanged.",
            "Keep track of the work, not the people. Drafts reviewed, findings by question, findings resolved before release, findings accepted and by whom, and days in the stage will tell you whether the stage is real. Ranking teams will only tell you who stopped sending drafts.",
            "Community reviewers are compensated advisors and co-designers, told what happened to their input. They are partners in this work and never learners in it.",
          ],
          evidence: "A one-page review stage you can copy and fill in, a scenario about a trial that produced no findings at all, and a knowledge check on what a clean record actually tells you.",
          appliedNextStep: "Fill in the review stage for one workflow, take it to the person who owns the step it would sit before, and agree on a start date, a service timeline in working days, and the point at which you will look at how the stage is working.",
        },
        scenario: {
          context: "A DSD leadership team approved a limited trial: every revision to one manual section goes through the new equity and access review before clearance. Three months in, the record shows twelve drafts reviewed and no findings on any of them. The trial is now up for a decision about whether to extend it to other document types.",
          prompt: "What should the leadership team make of a completely clean record?",
          options: [
            { label: "Treat it as evidence that the division's drafting practice is already sound, and extend the stage to other document types on that basis.", response: "It could be true, and twelve clean drafts in a row is not how this usually looks. Reporting it as a success without testing it risks expanding a stage that is not examining anything, and an expanded stage is much harder to correct than a small one." },
            { label: "Conclude that the stage is not finding enough to justify the time it takes, and retire it.", response: "This reads a measurement problem as a value problem. A stage that produces nothing may be badly designed, badly supplied, or run by people with no time to run it. None of those tell you whether the four questions were worth asking." },
            { label: "Treat the clean record as the first thing to examine: whether reviewers received enough to answer the four questions, whether anyone outside the drafting team read the drafts, whether findings were handled in conversation and never recorded, and whether the criteria can produce a finding at all.", response: "Yes. A clean record is a result about the stage as much as about the drafts. Ask the reviewers what they had to work with, ask two drafters what changed after a review, and read one of the twelve released documents yourself against the four questions. If the stage is sound and the drafts were genuinely clean, that will hold up in about fifteen minutes.", recommended: true },
          ],
        },
        transfer: {
          prompt: "What is the smallest version of this stage you could actually start?",
          options: [
            "Pick one document type your team produces regularly, and only that one.",
            "Name the step it would sit before, and the person who owns that step.",
            "Write the four questions and the single piece of evidence each one needs.",
            "Set a service timeline in working days, an exception route, and a date to look at how the stage is working.",
          ],
        },
        blocks: [
          {
            type: "text",
            heading: "Start narrow, and write it down",
            body: "<p>The most common way this work fails is not resistance. It is scope. A division decides that every public-facing document will go through an equity and access review, announces it, and then discovers that nobody has the hours, the criteria are unanswerable, and the release calendar does not move. Within two months the stage exists on paper and drafts go around it, and the next attempt has to overcome the memory of the first.</p><p>One document type. One workflow. One named owner for the step, one service timeline, one exception route. A page that a drafter can read in three minutes and a reviewer can work from. Once it runs for a season and produces findings that actually changed documents, extending it is an easy conversation, because you will have examples rather than a principle.</p><p>Write it down because unwritten stages drift. Everything below is the minimum that has to be on the page: what triggers it, where it sits, what gets examined and with what evidence, what authority it carries, how long it takes, how an exception works, what is recorded, and how the stage itself gets looked at.</p>",
          },
          {
            type: "artifact",
            kind: "tagged-document",
            label: "Practical tool",
            title: "A one-page equity and access review stage",
            summary: "Six lines that turn four questions into a step someone owns, with a timeline and a way out.",
            fields: [
              { label: "Trigger and scope", value: "Every revision to the provider bulletin series and to the manual sections those bulletins reference. Not internal scheduling notices, which continue through the standard communications review." },
              { label: "Where it sits in the workflow", value: "Early look: after the drafting team has a working draft and before legal and communications clearance, while the requirements can still change. Confirmation: a short check before release that the early findings were resolved or accepted in writing." },
              { label: "The four questions and the evidence each needs", value: "Accessibility: the draft in a working format, plus what a person must do, find, prove or wait for. Plain language: the requirement in one sentence, with days and a start date. Cultural responsiveness: what the draft assumes the reader already has. Stakeholder impact: what the division knows about who completes this step, and who read the draft from outside the drafting team." },
              { label: "Authority, timeline and exception route", value: "Conditional. Findings must be resolved before release or accepted in writing by the named document owner. Five working days from receipt of a complete draft. Exception: the division director may release with findings open, recorded with a name and a date for the back-check." },
              { label: "What is recorded and who sees it", value: "Drafts reviewed, findings by question, findings resolved before release, findings accepted and by whom, days in the stage, and what changed after outside review. Recorded about documents and steps, never as a rating of a person or a team." },
              { label: "How the stage itself is examined", value: "At the agreed point: ask reviewers what they lacked, ask two drafters what changed, read one released document against the four questions, and ask the compensated outside reviewers whether they were told what happened to their input." },
            ],
            action: "Copy these six lines, fill them in for one workflow you own or influence, and take the page to the person who owns the step you named in line two.",
          },
          {
            type: "accordion",
            heading: "Three ways this stage fails, and what catches each one",
            items: [
              { title: "The rubber stamp", body: "<p>Everything passes. The record is clean, the stage costs almost nothing, and it reports beautifully. Usually the cause is one of three things: criteria that cannot produce a finding, reviewers who receive a document and nothing else, or findings handled in a hallway conversation and never written down. What catches it: read one released document yourself against the four questions, and ask a drafter what actually changed after their last review. If the answer is nothing, you have the stage's real result.</p>" },
              { title: "The wall", body: "<p>No service timeline, no exception route, broad and undefined authority. Drafting staff cannot plan around it, so they stop trying. Work moves to document types the stage does not cover, effective dates get described as immovable when they are not, and the stage hears about drafts late or not at all. What catches it: compare the number of drafts the stage sees with the number the division actually released in the same period. A gap is the whole finding.</p>" },
              { title: "The parallel record", body: "<p>Findings are careful, well written, filed, and unconnected to what goes out the door. This is the most demoralizing of the three, because everyone involved is working hard. It is almost always an authority problem rather than an effort problem. What catches it: for each finding, record resolved before release, accepted in writing by a named person, or open. If the third category is large, the authority line on your page is not being used.</p>" },
            ],
          },
          {
            type: "list",
            heading: "Worth keeping track of, and worth leaving alone",
            ordered: false,
            items: [
              "Keep track of: drafts reviewed, and how that compares with drafts released.",
              "Keep track of: findings by question, so you can see which check is doing the work and which one is never used.",
              "Keep track of: findings resolved before release, findings accepted in writing and by whom, and findings still open.",
              "Keep track of: working days in the stage, so the timeline you published stays honest.",
              "Keep track of: what compensated outside reviewers said, what changed because of it, and whether they were told.",
              "Leave alone: any count that becomes a rating of a person, a supervisor or a unit. It will not improve drafts; it will reduce the number of drafts the stage is shown.",
              "Leave alone: anything a staff member wrote in a private reflection. Reflections in this program are not collected and are nobody else's business.",
            ],
          },
          {
            type: "leaderMove",
            heading: "Protect the stage from your own calendar",
            control: "You control whether the exception route is used for genuine statutory deadlines or for ordinary schedule pressure, and you control whether the back-check actually happens.",
            failure: "Do not approve the first few exceptions quietly. The first three uses of an exception route set its meaning for everyone watching, and a back-check that is skipped once is a back-check that has been retired.",
            next: "Before the next exception is requested, write down what counts as one and who approves it, and put the back-check on a date rather than on a good intention.",
          },
          {
            type: "knowledgeCheck",
            id: "ipe-30-4-check",
            question: "Which record tells you the most about whether an equity and access review stage is real?",
            options: [
              { text: "The number of drafts that passed the review with no findings, since a high number shows the drafting practice is strong.", correct: false },
              { text: "The number of drafts reviewed compared with the number released, together with how many findings were resolved before release, accepted in writing by a named person, or left open.", correct: true },
              { text: "The average time a draft spends in the stage, since a short average shows the stage is not creating delay.", correct: false },
            ],
            feedbackCorrect: "Yes. Those two comparisons catch the wall and the parallel record at once: whether drafts are reaching the stage at all, and whether findings are changing documents or only being filed.",
            feedbackIncorrect: "Ask what each record would look like if the stage were failing. A clean pass rate and a short average time both look excellent when drafts are going around the stage or findings are never recorded.",
          },
          {
            type: "statement",
            body: "A private reflection and a commitment, for you only and never collected: one workflow I could put this page in front of is... the person who owns the step it would sit before is... and the first document type I would start with is... Write it down where you will see it. If the person who owns that step says no, the useful next question is which of the four questions they would be willing to answer, and where.",
          },
        ],
      },
    ],
  },
  jobAid: {
    title: "Equitable policy and procedure governance",
    subtitle: "One page for adding an equity and access review to a policy workflow",
    quote: "A review that cannot hold anything is a comment box. A review nobody can plan around is a wall. Write down which one yours is.",
    use: {
      purpose: "Keep the four questions and the shape of the stage in view while you set up, run, defend or repair a review step in a bulletin, manual, form, letter or contract workflow.",
      remember: [
        "Placement decides what a review can reach. Put it before the point where a change stops being an edit.",
        "Four checks, because they find different things: accessibility, plain language, cultural responsiveness, stakeholder impact.",
        "A criterion is a question with an answer and a piece of evidence, not a value the reviewer is asked to affirm.",
        "Say in writing whether the review advises, conditions or holds, and name who can approve an exception.",
        "Keep track of the work, not the people. Reflections are private and are never collected.",
      ],
      doNext: "Write the review stage for one document type on one page, and take it to the person who owns the step it would sit before.",
    },
    sections: [
      {
        heading: "Place it before the lock",
        items: [
          "Draw the path from first draft to the day it reaches people, and mark where a change becomes an amendment.",
          "Put the early look before clearance, while the requirements are still open.",
          "Add a short confirmation before release: were the early findings resolved, or accepted in writing by a named person?",
          "If the only available placement is after clearance, say plainly that the stage can improve documents and not requirements.",
        ],
      },
      {
        heading: "The four questions",
        items: [
          "Accessibility: can a person get through this document and this procedure, including the hours, channels, windows and formats?",
          "Plain language: state the requirement in one sentence — do, find, prove or wait for, by when, counted from what.",
          "Cultural responsiveness: what does this draft assume the reader already has?",
          "Stakeholder impact: who is helped, burdened, excluded or misunderstood, in what numbers, and who read the draft from outside the drafting team?",
        ],
      },
      {
        heading: "Authority, timeline and the way out",
        items: [
          "Choose deliberately: advises, conditions, or holds. Write the sentence down where drafters can read it.",
          "Publish a service timeline in working days, counted from receipt of a complete draft.",
          "Name the exception approver, what they record, and the date of the back-check.",
          "Define not yet as a real outcome: the finding, the owner, the date, and who is told.",
        ],
      },
      {
        heading: "Keep it honest",
        items: [
          "Compare drafts reviewed with drafts released; a gap is the finding.",
          "Sort every finding into resolved before release, accepted in writing by a named person, or open.",
          "Read one released document yourself against the four questions, at the agreed review point.",
          "Pay outside reviewers, tell them what changed, and keep them as advisors and co-designers rather than an audience.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Policy and program staff, who decide what a requirement says and where it lives, and who carry most of the cost of a late finding.",
          "Quality, compliance and performance staff, who already hold much of the evidence the stakeholder impact question needs.",
          "Contracts, fiscal, grants and procurement staff, whose requirements decide who is able to apply at all, and whose clauses are hardest to change after release.",
          "Executive and senior leaders, who decide the stage's authority, its timeline and whether the exception route stays exceptional — a useful place to start.",
          "Communications, data and operations staff, whose work begins the moment a document is released and who see the consequences first.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "Leading a reflective DSD team",
          "Quality, complaints, and incident learning",
          "Responsible data and evaluation",
          "Co-design and compensated partnership",
          "Resource allocation and equity",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Department of Human Services, Content and writing guidelines", href: "https://mn.gov/dhs/digital-showcase/content-guidelines/", note: "The department's own editorial guidance on first-read understanding, descriptive headings, familiar terms and writing suited to the reader — the standard a draft is reviewed against." },
    { title: "PlainLanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Detailed guidance on audience, organization, useful headings and the vague words that leave a requirement undecided until someone answers the phone." },
    { title: "Minnesota IT Services, Accessibility standard", href: "https://mn.gov/mnit/about-mnit/accessibility/policy/", note: "The state's accessibility standard for digital documents, web content and procurement — the baseline the accessibility check is run against." },
    { title: "Section508.gov, Create accessible documents and content", href: "https://www.section508.gov/", note: "Federal guidance and practical instruction on accessible documents, forms and digital content, including how accessibility is built in rather than repaired." },
    { title: "W3C Web Accessibility Initiative, Developing organizational policies on accessibility", href: "https://www.w3.org/WAI/planning/org-policies/", note: "How organizations write and maintain an accessibility policy, including scope, responsibility, timelines and review — directly relevant to designing a review stage." },
    { title: "ADA.gov, State and local governments (Title II)", href: "https://www.ada.gov/topics/title-ii/", note: "U.S. Department of Justice guidance on what a state or local government program must provide, including effective communication and accessible programs, services and activities." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the governance, leadership, workforce and written-communication standards used in this module." },
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials and accessible instruction." },
  ],
};

export default pack;
