import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Complex systems · Module 22: Immigration, resettlement and state-system navigation.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-22-immigration-system-navigation",
    indexNumber: 1164,
    seriesLabel: "Intercultural Practice and Equity · Complex systems",
    title: "Immigration, Resettlement and State-System Navigation",
    subtitle: "Almost every public process was written by people who already knew how the system works. Four lessons on what that assumption costs the people who do not, ending with an assumed-knowledge review you fill in for one real process you touch.",
    scope: "For internal DHS and DSD staff who write, oversee, measure, fund or explain a public process: policy and program staff, data, research and evaluation staff, communications and language access staff, quality and performance staff, fiscal, contracts and grants staff, community engagement staff, administrative and support staff, supervisors and managers. This is not direct-service or provider training and it does not interpret an eligibility rule. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota examples, scenarios, sorting and flashcard practice, private reflection prompts, and an assumed-knowledge review you can copy into your own work",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/language-access-design.jpg",
    coverAlt: "People wait in a human-services public lobby.",
    introTranscript: "Minnesota has resettled people from many countries over several decades, and the households that arrived are now part of the public every division of this department serves. A share of those households include a person with a disability, which means this division's notices, forms, timelines and data arrive at kitchen tables where nobody has ever met a state human services agency before, or where the last government a family dealt with was not one you could safely ask a question of. This module is not about interpreting immigration law; that belongs to the offices that hold it. It is about a property of our own work that is almost invisible from the inside: how much prior knowledge a public process quietly requires before a person can use it at all. Four lessons, a set of things to check on any form, and a one-page review you can fill in for a process you already touch.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Identify the five kinds of prior knowledge a public process assumes — vocabulary, sequence, proof, channel and authority — in a notice, form or web page you touch.",
        "Distinguish the access obligations a program already carries from the demands a form has added by habit, and check what each added demand costs.",
        "Explain why caution toward a public system is usually a record of experience rather than a disposition, and describe what a process can change in response.",
        "Describe trauma-responsive public administration as a property of a process — predictability, stated purpose, real choice and no repeated retelling — rather than a clinical role for staff.",
        "Complete an assumed-knowledge review for one real process, make the fix inside your own step, and take each remaining line to its named owner with one specific ask.",
      ],
      evidence: [
        "Four worked scenarios drawn from a notice revision, a take-up review, a public-input session and a completed review, each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates an obligation the program already carries from a choice it made and an assumption worth checking.",
        "A completed assumed-knowledge review for one real process, kept with the process rather than in a personal file.",
      ],
      appliedNextStep: "Choose one process you touch. Walk it from the first moment a person meets it, write down every point where it assumes prior knowledge, fix the wording inside your own step, and take each remaining line to its named owner with one specific ask.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in federal or state language access guidance under Title VI of the Civil Rights Act, including what counts as meaningful access and which documents a program is expected to translate",
        "A change in the department's refugee resettlement programs, in eligibility rules tied to immigration status, or in what a program is required to collect, verify, retain or report",
        "Feedback from paid community reviewers, interpreters or recently arrived Minnesotans that a process described here does not match how it actually goes",
      ],
      relatedDoor: "Eligibility rules tied to immigration status, verification and documentation requirements, data sharing, retention and required public notices are decided by the responsible DHS program administration, civil rights, legal and data governance offices; this module prepares the review and the ask, it does not interpret an eligibility rule or authorize a change to what a program collects.",
      toolkitQuestion: "What does this process assume a person already knows about how the department works, and who is left standing outside because of that assumption?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-22-1",
        number: 1,
        title: "The process as a stranger meets it",
        summary: "Every public process carries prior knowledge inside it — words, order, proof, channel and authority. From inside, that knowledge is invisible. From outside, it is the first barrier.",
        minutes: 11,
        learning: {
          objective: "Name the five kinds of prior knowledge a public process assumes, and find at least three of them in a notice, form or web page you touch.",
          takeaways: [
            "A process assumes prior knowledge in five places: the words it uses, the order it expects, the proof it demands, the channel it works through, and who it assumes you know to ask. Each one is a place a person can stop entirely.",
            "Unfamiliarity is a fact about where the process starts, not a deficit in the person. The people most likely to be stopped by it are people meeting a state human services system for the first time, and people helping a relative through one.",
            "Sending everyone the same notice is a fact about the route, not a claim about the result. Treating identical delivery as proof of fairness is Minimization in its most ordinary administrative form.",
            "The staff member who wrote the page is the worst possible reader of it. Prior knowledge cannot be unlearned, which is why the check has to come from someone who has recently been outside it, and why that person's time is worth paying for.",
          ],
          evidence: "A scenario about revising a public notice, a knowledge check on where a process assumes knowledge, and four readings of the same paragraph.",
          appliedNextStep: "Take the last notice, web page or form your unit sent out. Mark every word, step and proof that only makes sense if you already know how the department works, and count how many there are on the first screen alone.",
        },
        scenario: {
          context: "A policy and communications team is revising the public page and the first notice for a disability services process. Staff who answer the phone report the same three calls over and over: people applied to the wrong office first, people brought a document the process does not use, and people who were told to wait did not know what they were waiting for or who had it.",
          prompt: "What is the most useful first move?",
          options: [
            { label: "Add a frequently asked questions section at the bottom of the page, built from the three calls staff hear most.", response: "This helps people who can already name their question. The three calls describe people who could not tell where the process starts, which means they never reach the bottom of the page. A list of answers below the fold does not repair a first screen that assumed too much." },
            { label: "Rewrite the first screen to say, in order: what this is, who decides, what to do first, what proof is accepted and what to do without it, and who to reach when stuck — then have it read by paid reviewers who recently went through the process, including someone who used an interpreter.", response: "This is the move. The three calls are not three separate confusions; they are the first screen failing to answer the five questions a person meeting the process has. Paying people who have recently been outside the process is the only reliable way to find what your own knowledge hides from you.", recommended: true },
            { label: "Translate the existing page into the languages most common among callers, so more people can read it.", response: "Translation is necessary and it is not sufficient here. A page that assumes you already know the order, the proof and the office produces an accurate translation of a page that assumes all three. Fix the logic first, then translate the version that works." },
          ],
        },
        transfer: {
          prompt: "Where does a process you touch actually start — for you, and for someone meeting it for the first time?",
          options: [
            "Write down the first moment your unit sees a case, and then the first moment the person did something about it",
            "Count the words on your first screen that a person would have to look up",
            "Name one person who has recently been outside this process and could be paid to read it",
          ],
        },
        blocks: [
          { type: "text", heading: "Where a process actually starts", body: "<p>Ask a program unit when a process begins and you will usually hear the date a request arrives. Ask the household and you hear something weeks earlier: a letter that mentioned a service, a neighbor who said to call the county, an appointment that turned out to be the wrong appointment. Between those two starting points sits everything this module is about. The department measures from the file. The person lives in the part before the file exists.</p><p>What fills that gap is prior knowledge. Public processes are built by people who know the field, and that knowledge gets written into the work so quietly that nobody notices it is a requirement. The notice says renewal, and assumes you know there was an original. It says contact your lead agency, and assumes you know you have one and which one it is. It gives you fourteen days, and assumes you know what happens on the fifteenth. None of that is careless writing. It is the ordinary residue of expertise, and it is a barrier with the same effect as a step in front of a door.</p><p>Someone who arrived in Minnesota recently meets all of it at once, often in a second or third language, sometimes while helping a parent or a child rather than themselves, and sometimes carrying an entirely reasonable caution about what a government office does with what you tell it. The point is not that these households need more help than others. The point is that the process was never asked whether it could be entered from outside, and nobody who works inside it can answer that question alone.</p>" },
          { type: "list", heading: "Five kinds of prior knowledge a process assumes", items: [
            "Vocabulary: waiver, assessment, lead agency, county of financial responsibility, appeal, renewal, redetermination. Words that are exact inside the field and opaque one step outside it.",
            "Sequence: that this step comes after that one, that an application follows an assessment, that a denial is not the end. The order is usually in someone's head and rarely on the page.",
            "Proof: which documents count, in what form, how recent, and — the part almost never stated — what the process accepts when a person cannot get the usual one.",
            "Channel: whether to call, mail, walk in or use a web form, which of those actually reaches a decision, and what the phone menu expects you to already know in order to choose an option.",
            "Authority: who decides, what this office can and cannot change, and who to go to when the answer is no. Without it, a person cannot tell a delay from a refusal.",
          ] },
          { type: "tabs", heading: "The same paragraph, read four ways", tabs: [
            { label: "A staff member", body: "<p><em>If your circumstances change, report the change to your lead agency within ten days to avoid an overpayment.</em></p><p>Clear, complete, and correct. It names the duty, the timeline and the consequence. It took three minutes to write and it has been in the notice for years.</p>" },
            { label: "Someone new to the system", body: "<p>Which agency is mine? I have talked to four offices. Is the county the lead agency, or is the one that called me? What counts as a change — a new address, a job that lasted two weeks, my mother moving in? Ten days from when: from the change, from this letter, from when I opened it?</p>" },
            { label: "Someone reading in a second language", body: "<p>Lead and agency are both common words and the phrase is not. Overpayment has no equivalent in many languages and is often translated into something closer to debt or fine, which changes what the sentence feels like. Report is the word used for reporting a person to the authorities. A correct translation can still land as a warning.</p>" },
            { label: "Someone helping a parent", body: "<p>I work two shifts. I can reach an office between two and four on a Thursday if I trade with someone. My mother has the letter and will not tell me she is worried about it. The ten days started before I saw it.</p>" },
          ] },
          { type: "leaderMove", heading: "Write the first screen for someone who has never been here", control: "You control the first screen: the order of the sentences, the words you use, what you say about proof, and whether the page names a person to reach.", failure: "Do not put the explanation in a later paragraph, a second document or a list of common questions. A person who cannot get past the first screen never reaches any of them, and you will only see it as an unexplained drop in applications.", next: "Before your next notice or page goes out, answer five questions in the first screen: what this is, who decides, what to do first, what proof is accepted and what to do without it, and who to reach when stuck." },
          { type: "flashcards", heading: "Words that sound plain from inside", cards: [
            { front: "Lead agency", back: "<p>Exact inside the field, and it does not tell a new reader which of the four offices they have spoken to is theirs. Say the name of the office, or say how to find out, in the same sentence.</p>" },
            { front: "Renewal or redetermination", back: "<p>Assumes the person knows there was a first determination, that it expires, and that nothing arrives to remind them if the address on file is old. Say what happens if the date passes, and whether there is a way back.</p>" },
            { front: "Within ten days", back: "<p>Ten days from what, counted how, and what happens on the eleventh? A deadline without a start date, a counting rule and a consequence is a source of fear rather than a source of action.</p>" },
            { front: "Verification", back: "<p>Reads inside as a routine step and outside as being doubted. Name the specific documents, say why each one is needed, and say what the process accepts when the usual document cannot be obtained.</p>" },
            { front: "You may appeal", back: "<p>Assumes the reader knows appeal means a real second look by someone else, not a complaint that annoys the person deciding. Say who hears it, that it costs nothing, and that using it does not affect current services.</p>" },
          ] },
          { type: "quote", text: "I had been in the country four years and I still could not tell the difference between an office that decides and an office that helps you fill in the form. Everyone I met was kind. Nobody ever drew me the map.", cite: "Composite participant perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-22-1-check", question: "A unit reports that its public page is clear, because staff reviewed it and no one has complained about it. What is the most accurate reading of that evidence?", options: [
            { text: "The page is clear; staff know the process well and complaints would surface a real problem.", correct: false },
            { text: "Staff cannot test for prior knowledge they already hold, and people stopped at the first screen usually leave rather than complain, so neither piece of evidence tells you whether the page can be entered from outside.", correct: true },
            { text: "The page is probably clear for most readers and needs a translated version for the rest.", correct: false },
            { text: "The absence of complaints is weak evidence, so the page should be rewritten in shorter sentences.", correct: false },
          ], feedbackCorrect: "Yes. Expertise cannot be switched off for a reading, and silence from people who could not get started looks exactly like satisfaction. Both gaps are closed the same way: pay someone who has recently been outside the process to read it.", feedbackIncorrect: "Ask what each piece of evidence could actually detect. A reviewer who knows the field cannot see the knowledge they are supplying, and a person stopped on the first screen rarely writes to say so." },
        ],
      },
      {
        id: "ipe-22-2",
        number: 2,
        title: "Language, documents and what a process demands as proof",
        summary: "Meaningful access is more than a translated page, and most forms ask for more than the rule requires. Every extra demand has a price, and the people who pay it disappear from the numbers first.",
        minutes: 11,
        learning: {
          objective: "Compare what a rule requires with what a form actually collects, and identify at least one demand the process added, one alternative it should accept, and one reason it never states.",
          takeaways: [
            "Meaningful access has four parts a program has to carry: telling people interpreting is available at no cost to them, providing qualified interpreters rather than relatives or children, translating the documents a person must understand to take part, and writing text whose logic survives translation.",
            "Forms accumulate. Fields get added for a study, a worry or a past problem and are almost never removed. Comparing the rule to the form field by field is an afternoon's work and it is the fastest equity review available to most units.",
            "A document demand fails in predictable ways: records left behind or held abroad, names transliterated differently on different papers, dates recorded under another calendar, and no stated alternative when the usual proof cannot be obtained.",
            "A question asked without a stated reason costs more than it looks. People with any reason to be careful about records decline the service instead of answering, and the division never sees them — not in the caseload and not in the data.",
          ],
          evidence: "A scenario about low take-up in a support program, sorting practice on obligations, choices and assumptions, and a knowledge check on unexplained questions.",
          appliedNextStep: "Take one form your unit uses. Put the rule beside it and mark every field the rule does not require. For each one, either remove it or write the sentence that says why it is needed and what happens to the answer.",
        },
        scenario: {
          context: "A data and evaluation unit is reviewing a support program with steady take-up in most of the state and very low take-up in several communities with many recently arrived households. The application asks for two proofs of address, a document that is difficult to obtain from outside the country, and a question about household composition that the governing rule does not require. The program is available in several translated versions.",
          prompt: "What should the unit recommend first?",
          options: [
            { label: "Fund additional outreach in the languages spoken in those communities, so that more people know the program exists and apply.", response: "Outreach against an application that asks more than it needs raises the number of people who start and not the number who finish. You will spend the money, watch the drop-off happen at the same fields, and have taught those communities that this program is not worth the trip." },
            { label: "Compare the rule to the form field by field, remove or justify every difference, state on the form why each remaining item is needed and what happens to the answer, name an alternative for the hard-to-obtain document, and then re-measure both applications started and applications completed by step.", response: "This is the recommendation. It treats low take-up as a question about the process rather than about the community, it is inside the unit's own reach, and measuring drop-off by step turns the next review from a guess into a finding.", recommended: true },
            { label: "Report the disparity in take-up, note that further study is needed to understand community-level factors, and recommend the topic for the next research cycle.", response: "The reporting is accurate and the conclusion is premature. A field-by-field comparison would take an afternoon and would very likely name the cause. Deferring to a research cycle keeps the process unexamined for another year while attributing the gap to the community." },
          ],
        },
        transfer: {
          prompt: "Which form in your area asks for something the rule does not require?",
          options: [
            "Name the field and the reason someone once had for adding it",
            "Write the one sentence that would tell a person why it is needed and what happens to the answer",
            "Name the alternative your process should accept when the usual document cannot be obtained",
          ],
        },
        blocks: [
          { type: "text", heading: "Meaningful access is more than a translated page", body: "<p>Language access has a settled shape in federal civil rights guidance under Title VI of the Civil Rights Act, and most staff can name the first part of it: a program that receives federal funds takes reasonable steps to give people with limited English proficiency meaningful access to what it does. In practice that becomes four obligations. Tell people, in a language they read, that interpreting is available at no cost to them. Provide a qualified interpreter rather than leaning on a relative, a neighbor or a child. Translate the documents a person must be able to understand in order to take part. And — the part that gets missed — write text whose meaning survives being carried into another language.</p><p>That last one is where a great deal of well-funded translation quietly fails. Ambiguity does not translate away. A sentence that could mean two things in English gives the translator a choice, and the reader receives whichever one the translator picked, with no sign that a choice was made. Terms of art that have no equivalent — overpayment, waiver, redetermination, spenddown — come out as the nearest ordinary word, and the nearest ordinary word often carries a threat the original did not. When a division writes plainly before it translates, it is not simplifying for someone. It is removing the choices that would otherwise be made on its behalf.</p><p>Leaning on family members to interpret deserves its own sentence, because it feels helpful and it is a shift of risk. It puts a private matter in a relative's hands, it makes a child responsible for a parent's medical or financial information, and it produces a record nobody can stand behind later. A qualified interpreter is not a courtesy extended to some participants. It is how the program makes its own record reliable.</p>" },
          { type: "accordion", heading: "Four ways a document demand fails, and what to write instead", items: [
            { title: "The record is somewhere the person cannot reach", body: "<p>Birth records, school records, marriage records and employment histories may be in a country a person left quickly, in an office that no longer functions, or in a family home they cannot contact. Asking again does not produce the document. Write the alternative into the form: what the process accepts instead, who can attest, and what the person should do first.</p>" },
            { title: "The name does not match itself", body: "<p>Transliteration from another writing system produces different spellings on different papers, and naming conventions differ: a family name may sit first, a patronymic may not be a surname at all, and a person may have been registered under a name the family does not use. A mismatch flagged once follows someone through every record the state holds. Say plainly that spelling differences are expected and name the step that resolves them, rather than treating the mismatch as a discrepancy.</p>" },
            { title: "The date is right in another calendar", body: "<p>Dates of birth recorded under a different calendar, or assigned on arrival when no record existed, are common and entirely ordinary. When a process treats a date difference as a red flag, it converts an artifact of paperwork into a suspicion about a person.</p>" },
            { title: "The demand costs money and time nobody mentioned", body: "<p>A certified copy, a notarized statement, a clinic letter, a trip to an office during working hours: each has a price paid in wages, transport, childcare or a favor owed. Add them up before you add a field. If the process cannot say why it needs the document, the household is paying for a habit.</p>" },
          ] },
          { type: "sorting", id: "ipe-22-2-sort", heading: "Obligation, choice, or assumption?", categories: ["An access obligation the program already carries", "A choice the program made and can change", "An assumption worth checking"], items: [
            { text: "Telling people, in a language they read, that an interpreter is available at no cost to them.", category: "An access obligation the program already carries" },
            { text: "Providing a qualified interpreter instead of asking the person's daughter to translate the appointment.", category: "An access obligation the program already carries" },
            { text: "Asking for two proofs of address when the governing rule asks for one.", category: "A choice the program made and can change" },
            { text: "Accepting only one kind of document, with no stated alternative for a person who cannot obtain it.", category: "A choice the program made and can change" },
            { text: "Low application numbers in a community mean there is less need there.", category: "An assumption worth checking" },
            { text: "The form is understood, because nobody has written to say it is not.", category: "An assumption worth checking" },
          ] },
          { type: "leaderMove", heading: "Ask what the rule requires before you ask the person", control: "You control which fields survive the next revision of your form, whether each one carries a stated reason, and whether the process names an alternative when the usual document cannot be produced.", failure: "Do not add a field because it would be useful to know, and do not keep one because it has always been there. Every unexplained question is a reason for a careful household to stop, and the stopping is invisible to you.", next: "Put the rule beside the form this month. Mark every field the rule does not require, and for each one either remove it or write the single sentence that says why it is needed and what happens to the answer." },
          { type: "list", heading: "Questions to put to any form before it goes out", items: [
            "Does the governing rule require this field, or did we add it? If we added it, what is it for and who uses it?",
            "Does the form say why each item is asked, who will see the answer, and what is done with it afterward?",
            "Is there an alternative for every document, and is the alternative on the form rather than in a staff manual?",
            "Can a person answer honestly and still be served, when a field is genuinely optional? If declining costs them the service, it is not optional.",
            "Would a correct translation of this sentence carry the same meaning, or does the sentence contain a choice we are handing to the translator?",
            "Does anything here ask a person to explain a hard experience in order to get a routine service?",
            "Where does a person go if the answer is no, and does the form say so in the same place it says no?",
          ] },
          { type: "knowledgeCheck", id: "ipe-22-2-check", question: "A program adds an optional question about household members' places of birth, marked for planning purposes only, with no further explanation. Applications from several communities fall in the following months. What is the most useful reading?", options: [
            { text: "The drop is unrelated; the question is optional and cannot affect eligibility.", correct: false },
            { text: "A question with no stated purpose reads as a question with an unstated purpose, so households with any reason to be careful about records decline the whole service — and because they never apply, the effect shows up nowhere except in a caseload nobody can explain.", correct: true },
            { text: "The question should be made mandatory so the planning data is complete and the pattern can be measured properly.", correct: false },
            { text: "The drop probably reflects seasonal variation and should be reviewed again after a full cycle.", correct: false },
          ], feedbackCorrect: "Yes. Optional is a description of the form, not of how the question lands. The cost falls on people who never enter the process, which is exactly the group no internal measure can see.", feedbackIncorrect: "Follow who bears the risk. A question without a reason is answered by people with nothing to weigh and avoided by people with something to weigh, and the second group leaves no trace in the numbers." },
          { type: "statement", body: "Private reflection, for you only: think of one field on a form your area owns. What might it mean to the person filling it in, as opposed to the person who added it — and whose expertise is missing from the group that decided it should be there? Nothing you write here is collected, stored or seen by anyone." },
        ],
      },
      {
        id: "ipe-22-3",
        number: 3,
        title: "Trust, memory and the cost of being asked",
        summary: "Caution toward a public system is usually a record of experience, not a disposition. What a process can change is its own predictability, its stated purpose and the number of times it makes someone tell a hard story.",
        minutes: 11,
        learning: {
          objective: "Explain why caution toward a public system is a record rather than a disposition, and name three properties of a process that raise or lower the cost of taking part.",
          takeaways: [
            "Trauma-responsive public administration is a property of a process, not a clinical role for staff. The four properties you control are predictability, a stated purpose for every question, a real choice that still gets the person served, and never requiring a hard account to be retold for a routine step.",
            "Distrust is usually specific and sourced: an earlier program that ended without notice, information that turned out to travel further than expected, or an encounter in another country with a state you could not question safely. Treating it as an attitude to be overcome misreads the evidence and insults the person holding it.",
            "Disability, recent arrival, language, and low income do not meet a division as four separate problems. They arrive together in one person, and a fix to one of them can be canceled out entirely by the others — an interpreter does not help if the window is fourteen days and the household works two shifts.",
            "Community organizations, interpreters and cultural brokers belong in this work as compensated co-designers, reviewers and advisors. They are not free translators, they are not a substitute for the division doing its own job, and the obligation does not transfer with the invitation.",
          ],
          evidence: "A scenario about a public-input session, sorting practice on what earns and what costs trust, and a knowledge check on reading low turnout.",
          appliedNextStep: "Take one letter, survey or meeting invitation your area sends. Add a plain sentence saying what will be collected, what will not be collected and who reads it — then check whether anything in it asks a person to explain a hard experience for a routine purpose.",
        },
        scenario: {
          context: "A division is planning a public-input session on a proposed change to a disability service. A community organization that works with recently arrived households tells the engagement lead that few people will come: an earlier state process collected information and families later heard it had been shared more widely than they expected, and this session is set for a weekday afternoon at a building reachable by car.",
          prompt: "What is the most effective response?",
          options: [
            { label: "Hold the session as planned, keep a careful record that outreach was conducted in the affected communities, and note the low turnout in the engagement summary.", response: "This converts a design problem into a finding about the community. Six months later the low turnout will be cited as evidence that these households are hard to reach or not interested, and the actual causes — an unaddressed data concern, a weekday afternoon and a building that needs a car — will not appear anywhere in the record." },
            { label: "Ask the organization what would make participation possible and pay for that advice and for facilitation; move the time and place accordingly; open by saying plainly what is collected, who sees it and what is not collected; offer a way to contribute without attending; and report back afterward what changed because of what people said.", response: "This is the response that works. It treats the organization as a paid advisor rather than a free channel, it answers the specific concern rather than talking around it, and reporting back is what makes the next invitation credible.", recommended: true },
            { label: "Replace the session with a translated survey, so people can take part privately without traveling or speaking in a room full of strangers.", response: "A private channel is a genuinely useful option and should be one of several. On its own it does not help here: the same sender is asking the same households for information, with the same unanswered question about where the answers go. The data concern has to be answered whatever the channel." },
          ],
        },
        transfer: {
          prompt: "What does a person risk by taking part in something your area runs, and what do they get told about it?",
          options: [
            "Write the sentence your invitation should carry about what is collected and who reads it",
            "Name one thing in the timing, place or format that assumes a car, a daytime schedule or a fixed address",
            "Name the organization or advisor whose review you would pay for, and what you would ask them to look at",
          ],
        },
        blocks: [
          { type: "text", heading: "Caution is a record, not a temperament", body: "<p>When a division notices that a community does not engage, the explanation reached for first is usually cultural: people are private, people rely on family, people do not use formal services. Sometimes there is something in that. Far more often the caution is specific and has a source, and the source is a thing that happened. A program that ended without notice. A question at an office that turned into a problem months later. Information that traveled further than anyone said it would. Or, before Minnesota, a state where the safe answer to an official question was no answer at all.</p><p>Read that way, caution is not a barrier inside the person for the division to overcome. It is an accurate summary of prior experience, and the only thing that changes it is a different experience. This matters practically, because the two readings lead to opposite work. If caution is a trait, the response is more persuasion: more outreach, more messaging, more explaining. If caution is a record, the response is to change what the process actually does — to say where answers go, to keep the commitment made last time, and to be the kind of counterparty a careful person can afford to deal with.</p><p>There is a second belief worth naming plainly, because staff meet it constantly and cannot resolve it. Many households believe that using a public program could affect an immigration case. The rules on that point have shifted more than once, and each shift has been followed by families withdrawing from programs they were plainly entitled to use. Whether the belief is accurate in a given situation is a legal question that belongs to the responsible offices, not to a program unit and not to this module. The administrative fact staff can act on is simpler: fear outlives the rule that caused it, it travels faster than a correction, and a notice that does not anticipate it will be read through it.</p>" },
          { type: "text", heading: "Identical is a fact about the route, not a claim about the result", body: "<p>The most common form of exclusion in a well-run public agency is not hostility. It is the conviction that sending everyone the same letter, on the same day, with the same window, is what fairness looks like. That belief is what the program's continuum calls Minimization: real differences are visible but treated as secondary to a shared sameness, and the division's own defaults quietly become the neutral standard everyone is measured against. It is comfortable, it is usually well meant, and it is where most of the unequal results in public administration are manufactured.</p><p>Acceptance is the point at which the difference stops being a footnote: a fourteen-day window is not the same fourteen days for a household with one car and two shifts as it is for a salaried reader with a home printer, and the process produced that difference. Adaptation is the point at which the work changes shape — the notice is written so it can be entered from outside, the review is built with people who have recently been outside it, and the division checks afterward whether the change actually reached anyone. Naming the stages is useful here because it describes what a unit is doing, not what any individual is. No result, orientation or movement along that continuum belongs in anyone's personnel record, and nothing in this module produces one.</p><p>The other thing Minimization hides is that people arrive whole. A division that fixes language access and leaves the deadline, or fixes the deadline and keeps a document nobody can obtain, has moved a barrier rather than removed one. Disability, recent arrival, language, income and distance meet the process at the same moment in the same person, and the fix has to hold for all of them at once or it does not hold.</p>" },
          { type: "sorting", id: "ipe-22-3-sort", heading: "Earns trust, costs trust, or worth checking?", categories: ["Something the process does that earns trust", "Something the process does that costs trust", "An assumption worth checking"], items: [
            { text: "A letter asks for information with no explanation of why it is needed or who will see it.", category: "Something the process does that costs trust" },
            { text: "The first page states what will be collected, what will not be collected, and who reads it.", category: "Something the process does that earns trust" },
            { text: "A person is asked to describe how they were injured in order to complete a routine renewal.", category: "Something the process does that costs trust" },
            { text: "A community organization is paid for the time it spends reviewing a draft notice, and the division reports back what changed.", category: "Something the process does that earns trust" },
            { text: "Low turnout at a public session means the community is not interested in the change.", category: "An assumption worth checking" },
            { text: "People who skipped the optional question had nothing they wanted to tell us.", category: "An assumption worth checking" },
          ] },
          { type: "accordion", heading: "Trauma-responsive, at the level of a process", items: [
            { title: "Predictability", body: "<p>Say what happens next, who will contact the person, roughly when, and by which channel. Then do that. Most of what a process can offer a wary household is the ordinary reliability of knowing what is coming, and most of what it costs them is the surprise letter, the unannounced call and the silence in between.</p>" },
            { title: "A stated purpose for every question", body: "<p>Ask, say why, say who sees it, say what happens to it afterward. A question with a reason attached is a transaction. A question without one is an unknown risk, and people price unknown risk high.</p>" },
            { title: "A real choice that still gets you served", body: "<p>Optional has to mean optional. If declining a field slows the case, costs a service or triggers a second look, the field is mandatory and the form is misleading. Where a choice is genuine, say what happens either way.</p>" },
            { title: "No repeated retelling", body: "<p>Nobody should have to narrate a hard experience again to satisfy a routine step. If an account is genuinely required once, record it properly so it is not required twice, say who will read it, and do not ask for detail the decision does not use. Staff are not counselors and should not try to be; the professional response here is a process that does not keep reopening the subject.</p>" },
          ] },
          { type: "leaderMove", heading: "Say what happens to the answer before you ask the question", control: "You control the sentence that accompanies a question: why it is asked, who reads the answer, what is done with it, and what is not collected at all.", failure: "Do not rely on a privacy notice further down the page, and do not answer a specific concern about where information went with a general reassurance that data is handled carefully. A careful reader hears the difference immediately.", next: "Add the sentence to one letter, survey or invitation this month, and check with a paid community reviewer whether it answers the question people are actually asking." },
          { type: "quote", text: "We are glad to help you fix the letter. What we cannot do is be the reason a family trusts it. That part is yours, and it is built out of what happened the last three times.", cite: "Composite community advisor perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-22-3-check", question: "An engagement summary records that a session was held in three communities with translated invitations and interpreters available, and that attendance was very low in two of them. Which conclusion is best supported?", options: [
            { text: "Interest in the proposed change is low in those two communities, and engagement effort should be directed where turnout is higher.", correct: false },
            { text: "Turnout measures the design as much as the interest, so the useful next step is to ask paid community advisors what the time, place, format and data practice cost people, and to treat the low attendance as an unanswered question rather than an answer.", correct: true },
            { text: "The invitations were probably poorly translated, and the translation vendor should be reviewed before the next session.", correct: false },
            { text: "Access was provided, so the division met its obligation and the record is complete.", correct: false },
          ], feedbackCorrect: "Yes. Translated invitations and interpreters remove two barriers and say nothing about the other four. Low turnout is a finding about the invitation until someone has asked.", feedbackIncorrect: "Ask what the number can actually tell you. Attendance reflects timing, travel, format, childcare, working hours and whether people trust where their information goes — none of which the summary measured." },
        ],
      },
      {
        id: "ipe-22-4",
        number: 4,
        title: "Your assumed-knowledge review",
        summary: "Walk one process from the first moment a person meets it, write down everywhere it assumes prior knowledge, fix the wording you own, and take the rest to their named owners with one specific ask each.",
        minutes: 11,
        learning: {
          objective: "Complete an assumed-knowledge review for one real process, naming the words and steps that only make sense from inside, the proof demanded, what is missing in language and format, where a person can stop with no way forward, and the first fix with an owner.",
          takeaways: [
            "Reviewing a process means reading the policy. Walking it means following what a person actually does, in order, starting weeks before your unit has a file — and the difference between the two is where almost everything in this module lives.",
            "Fix the wording inside your own step before the review goes anywhere. It usually needs nobody's permission, and a completed fix is what makes the rest of the page read as working document rather than criticism.",
            "A line you do not own needs a named person, the effect written plainly, and one ask inside that person's authority — a sentence added, a field removed, an alternative document named — not a copy of the whole review and a general concern.",
            "Have the draft read by people who were recently outside the process, pay them for it, and keep the finished review with the process rather than in a personal file so the next person to hold the work inherits it.",
          ],
          evidence: "A completed assumed-knowledge review, a scenario about what to do with the lines you do not own, and a private reflection on accountability and repair.",
          appliedNextStep: "Fill the review in for one process this month, make the fix inside your own step, tell the units on either side of you what changed, and take one other line to its named owner with a specific ask.",
        },
        scenario: {
          context: "You have walked a process you support and filled in the review. It shows six points where the process assumes prior knowledge. Two are in wording you write yourself. Three belong to the form owner and the notices team in another area. One is a requirement set in federal and state law that no one in the department can change.",
          prompt: "What is the most effective first move?",
          options: [
            { label: "Send the completed review to leadership across all three areas, with the six points listed, and ask for the changes to be assigned to the right owners.", response: "Three areas receive a document about other people's work, nobody has been asked for anything specific, and the two points you could have fixed yourself this week are still there. A review that starts by going upward is read as a complaint, and it is usually read once." },
            { label: "Rewrite the two points in your own wording now; take each of the three external points to its named owner separately, with the effect written plainly and one specific change attached; and for the requirement set in law, ask the responsible office how it is currently explained to the public and whether a plain-language explanation can travel with it.", response: "This is the sequence that produces change. Your own completed fix makes the review credible, one point with one ask is something a named owner can act on this month, and the item nobody can change still has an accessible explanation that can be improved.", recommended: true },
            { label: "Hold the review until the process is next redesigned, so the six points can be addressed together in a single coordinated change rather than piecemeal.", response: "Coordinated redesign is a good thing and it is not a reason to leave a sentence unfixed for two years. The points in your own wording cost nothing to repair now, and a review held for the perfect moment is usually a review nobody ever reads." },
          ],
        },
        transfer: {
          prompt: "Which line will you fix yourself, and who will ask you about it?",
          options: [
            "Name the sentence in your own wording that you will change, and the date it goes out",
            "Name the person in another area you will take one line to, and the exact ask",
            "Name the colleague who will ask you in a month what actually changed for the people using the process",
          ],
        },
        blocks: [
          { type: "text", heading: "Walk it from outside, not from your desk", body: "<p>Reviewing a process means reading the policy, opening the form and confirming that the steps match. It is useful and it cannot find what this module is about, because the person doing it supplies the missing knowledge without noticing. Walking a process means starting where the person starts — usually weeks before your unit has anything — and following what they actually do: the search, the phone menu, the first wrong office, the letter, the document they cannot find, the fourteen days, the silence.</p><p>Two rules make the walk worth the hour. Start from the first moment a person could hear the program exists, not from the moment a request reaches your queue. And write down the words as they are, not as you would explain them in a meeting; the whole point is to catch the sentence that works because you finished it in your head. Where you cannot do the walk yourself, pay someone who was recently outside the process to do it with you, including someone who used an interpreter. That is not a consultation exercise. It is the only reliable instrument available for this particular defect.</p><p>Then fill in the six lines below, one set for each point where the process assumes something. Fix the wording you own first. Take the rest to the people who own them, one at a time, with the effect written plainly and one specific ask attached. Keep the finished review with the process rather than in your own files, so that whoever holds this work next does not start from nothing.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "An assumed-knowledge review for one public process", summary: "Six lines for each point where a process expects a person to already know how the department works. One page, written in the order a person meets it, ready to send to the owners you name.", fields: [
            { label: "Process, and the first moment a person could meet it", value: "Request for a disability service. The first moment is a mention in an unrelated letter, three weeks before anything reaches our queue. Between those two points the person has called two offices and been transferred once." },
            { label: "Words and steps that only make sense from inside", value: "Lead agency, assessment, redetermination, and the unstated rule that the assessment comes before the application. None of the three words is defined anywhere on the page, and the order appears nowhere at all." },
            { label: "Proof the process demands, and what it accepts instead", value: "Two proofs of address and a dated record many households cannot obtain from outside the country. No alternative is stated on the form; staff know one exists and applicants do not." },
            { label: "Language and format: what exists, what is missing, what survives translation", value: "The form is translated; the web page that explains the order is not. Overpayment and verification translate into words that read as debt and doubt. Nothing says an interpreter is free." },
            { label: "Where a person can stop with no way forward, and what they hear", value: "After a denial for a missing document: the letter names the missing item but not the alternative, no person to call, and no statement that appealing is free and does not affect current services. Most people stop here and are recorded as not responding." },
            { label: "First fix, owner, and the next review point", value: "Add a first screen with the five questions answered and the order stated; put the document alternative and a named contact on the denial letter. Owners: our own unit for the page, the notices team for the letter. Review both together at the agreed point." },
          ], action: "Copy the six lines, fill one set for each point where the process assumes prior knowledge, fix the wording inside your own step first, and send the review to the owners you named with one specific ask for each line you do not own." },
          { type: "list", heading: "First fixes that need nobody's permission", items: [
            "Answer five questions on the first screen: what this is, who decides, what to do first, what proof is accepted and what to do without it, who to reach when stuck.",
            "Define a term the first time you use it, in the same sentence, rather than in a glossary somewhere else.",
            "Put the order of steps on the page, including which step has to happen before the one people usually try first.",
            "Write the document alternative where the document is requested, not in a staff manual.",
            "Say when a deadline starts, how it is counted and what happens if it passes — including whether there is a way back.",
            "Add the sentence that says why each question is asked, who reads the answer and what is done with it.",
            "Name a person to reach on anything that says no, in the same place it says no.",
            "State that interpreting is free, in the languages your program actually meets, on the first screen rather than the last.",
          ] },
          { type: "accordion", heading: "Who should read the draft before it goes out", items: [
            { title: "People who were recently outside the process", body: "<p>The only readers who can see the knowledge you are supplying. Pay them for the time, ask them to try to do the thing rather than to comment on the page, and watch where they stop rather than asking whether it was clear.</p>" },
            { title: "Someone who used an interpreter to get through it", body: "<p>They will find the sentences that split in two on the way across, and the places where a correct translation carries a threat the original did not.</p>" },
            { title: "A community organization, as a paid reviewer", body: "<p>Compensated for advice and review, with a clear scope and a report back on what changed. Not a free translation service, not a way to reach people without building your own reason to be trusted, and not a transfer of the obligation, which stays with the division.</p>" },
            { title: "The staff who answer the phone", body: "<p>They already know the three calls this page generates. They are rarely asked before the page is written and they can usually name the fix in a sentence.</p>" },
          ] },
          { type: "leaderMove", heading: "Fix the wording you own before the review goes anywhere", control: "You control your own sentences: the first screen, the definitions, the stated order, the reason attached to a question, and the name of a person to reach.", failure: "Do not send the review upward and wait. A page of other people's assumptions with nothing repaired on your own side reads as criticism, and it will be received that way.", next: "Make one fix inside your own step this month, tell the units on either side of you what changed, and then take the next line to its named owner with a specific ask." },
          { type: "knowledgeCheck", id: "ipe-22-4-check", question: "Which line from a completed assumed-knowledge review can actually be acted on?", options: [
            { text: "The denial letter is confusing for people new to the system and should be made clearer.", correct: false },
            { text: "The denial letter names the missing document but not the alternative the process accepts, gives no person to contact and does not say that appealing is free and does not affect current services; people stop here and are recorded as not responding. Owner: notices team. First fix: add the alternative, a named contact and the two sentences about appealing. Review at the agreed point.", correct: true },
            { text: "People who receive a denial do not respond, so a follow-up reminder should be added to the process.", correct: false },
            { text: "Translation of the denial letter should be reviewed, since most of the affected households read another language at home.", correct: false },
          ], feedbackCorrect: "Yes. It names what the letter does, who it stops, what that costs, one owner, a specific change and a review point. Everything on that line is something a named person can do.", feedbackIncorrect: "A usable line names the specific thing the process does, the people it stops, an owner, a change inside that owner's authority and when it will be looked at again. Clearer and a reminder are neither of those." },
          { type: "statement", body: "Private reflection, for you only: if a process you are part of has excluded someone because it assumed knowledge they had no way to have, what would accountability and repair actually require — of your own wording, of the process, and toward the households that stopped and were recorded as not responding? Nothing you write here is collected, stored or seen by anyone." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Immigration, resettlement and state-system navigation",
    subtitle: "One page for anyone who writes, oversees, measures, funds or explains a public process",
    quote: "Unfamiliarity is a fact about where the process starts, not a deficit in the person.",
    use: {
      purpose: "Keep the five kinds of assumed knowledge, the language access obligations and the six review lines in view while you draft a notice, revise a form, plan an engagement session or explain a gap in take-up.",
      remember: [
        "Five kinds of prior knowledge: vocabulary, sequence, proof, channel and authority. Each one is a place a person can stop entirely.",
        "Meaningful access is four things, not one: notice that interpreting is free, a qualified interpreter, translated documents, and text whose logic survives translation.",
        "Compare the rule to the form field by field. Whatever the rule does not require, either remove it or write the sentence that says why it is needed.",
        "Every document demand needs a stated alternative on the form, because records get left behind, names transliterate differently and dates come from other calendars.",
        "A question with no stated reason reads as a question with an unstated purpose, and the people who decline it never appear in the data at all.",
        "Caution toward a public system is usually a record of something that happened. The only thing that changes it is a different experience.",
        "Identical delivery is a fact about the route. Equal effect is a claim, and it has to be checked.",
        "The person who wrote the page cannot test it. Pay someone who was recently outside the process to try to use it.",
      ],
      doNext: "Walk one process from the first moment a person could meet it, fill in the six review lines, and fix the wording inside your own step before the review goes anywhere.",
    },
    sections: [
      {
        heading: "The assumed-knowledge review, in short",
        items: [
          "Process, and the first moment a person could meet it — not the moment it reaches your queue.",
          "Words and steps that only make sense from inside, including the order nobody wrote down.",
          "Proof the process demands, and what it accepts instead when the usual document cannot be obtained.",
          "Language and format: what exists, what is missing, and which sentences do not survive translation.",
          "Where a person can stop with no way forward, and what they hear when they do.",
          "First fix, owner, next review point: one change, one name, one date already on a calendar.",
        ],
      },
      {
        heading: "Five kinds of prior knowledge a process assumes",
        items: [
          "Vocabulary: terms that are exact inside the field and opaque one step outside it.",
          "Sequence: which step comes first, usually held in staff memory and absent from the page.",
          "Proof: what counts, in what form, and what the process accepts when it cannot be produced.",
          "Channel: which of call, mail, walk in or web form actually reaches a decision.",
          "Authority: who decides, what this office cannot change, and where to go when the answer is no.",
        ],
      },
      {
        heading: "Before a question goes on a form",
        items: [
          "Does the governing rule require this, or did we add it, and who uses the answer?",
          "Does the form say why it is asked, who sees it, and what happens to it afterward?",
          "Is there an alternative document, written where the document is requested?",
          "If the field is optional, can a person decline and still be served without delay?",
          "Would a correct translation carry the same meaning, or are we handing the translator a choice?",
          "Does anything here require a hard experience to be retold for a routine step?",
        ],
      },
      {
        heading: "When trust is the obstacle",
        items: [
          "Answer the specific concern. A general reassurance that information is handled carefully does not address a particular thing that happened.",
          "Say what is collected, what is not collected, who reads it, and what is done with it — before you ask, not in a notice further down.",
          "Keep last time's commitment, and report back what changed because of what people said. That is what makes the next invitation credible.",
          "Pay community organizations, interpreters and advisors for review and facilitation. The obligation stays with the division.",
          "Legal questions about immigration status and eligibility go to the responsible offices; a program unit does not interpret them and should not try.",
          "Treat low turnout and low take-up as findings about the design until someone has actually asked.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Policy and program staff, whose notices, forms and sequences carry most of the assumed knowledge in the department — the best place in this module to go deeper.",
          "Data, research and evaluation staff, who can see a gap in take-up and are usually the first people able to show that it belongs to the process rather than the community — also worth a deeper pass.",
          "Communications and language access staff, who inherit the ambiguity that plain writing would have removed before translation.",
          "Quality and performance staff, who decide what counts as a complete case and whose measures currently cannot see the people who stopped before applying.",
          "Fiscal, contracts and grants staff, who set the terms under which community organizations are paid for review, advice and facilitation.",
          "Community engagement, administrative and support staff, who answer the phone, hear the same three questions, and usually already know the fix.",
          "Supervisors and managers, who can authorize an afternoon spent comparing a rule to a form, which is the fastest equity review most units have available.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "History, disability, and public institutions",
          "Race, disability, and unequal outcomes",
          "Trauma-responsive public administration",
          "Power, conflict, and repair",
          "Ethical decision-making",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Department of Human Services, Refugee resettlement programs", href: "https://mn.gov/dhs/people-we-serve/adults/economic-assistance/refugee-resettlement/", note: "The department's information on refugee resettlement programs and services in Minnesota, including how the programs are administered with resettlement agencies and counties." },
    { title: "LEP.gov, Federal interagency limited English proficiency resources", href: "https://www.lep.gov/", note: "The federal government's central source on meaningful access for people with limited English proficiency, including the four-factor analysis, language access planning and guidance on the use of qualified interpreters rather than family members." },
    { title: "U.S. Department of Justice, Civil Rights Division, Federal Coordination and Compliance Section", href: "https://www.justice.gov/crt/fcs", note: "Federal enforcement and technical assistance on Title VI of the Civil Rights Act, including national origin discrimination and language access obligations for recipients of federal financial assistance." },
    { title: "U.S. Department of Health and Human Services, Think Cultural Health: National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "The National Standards for Culturally and Linguistically Appropriate Services, covering governance, communication, language assistance, community engagement and accountability in health and human services." },
    { title: "PlainLanguage.gov", href: "https://www.plainlanguage.gov/", note: "Federal plain-language guidelines and examples for public writing, including the structural advice this module applies to a first screen: lead with what the reader must do, define terms in place and state the sequence." },
    { title: "ADA.gov, Title II primer for state and local governments", href: "https://www.ada.gov/resources/title-ii-primer/", note: "U.S. Department of Justice explanation of what Title II requires of state and local government programs, including effective communication and access to programs however they are delivered." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's advisory council on disability policy, access and rights, and a route to disability-led review of state processes and public materials." },
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage with content, cultural relevance, and instruction that does not assume a single set of prior experiences." },
  ],
};

export default pack;
