import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Public-service practice · Module 18: Cross-division coordination.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-18-cross-division-coordination",
    indexNumber: 1160,
    seriesLabel: "Intercultural Practice and Equity · Public-service practice",
    title: "Cross-Division Coordination",
    subtitle: "Most public-service work fails between two units rather than inside one. Four lessons on the seams where work changes hands, ending with a handoff map you fill in for one real process you touch.",
    scope: "For internal DHS and DSD staff whose work arrives from another unit and leaves for one: contracts, fiscal, grants and procurement staff, administrative and support staff, policy and program staff, operations, quality, communications, data and engagement staff, supervisors and managers. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota examples, scenarios, sorting and flashcard practice, private reflection prompts, and a handoff and exclusion map you can copy into your own work",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/stock-people-01.jpg",
    coverAlt: "Four colleagues standing together, reviewing a document one of them is holding.",
    introTranscript: "Very little that a division produces is finished by one unit. A change to a service definition passes through policy, operations, communications, language access, fiscal, contracting, data and county partners before it reaches one person's kitchen table. Every one of those units has an owner and a standard for its own step. The points where the work moves between them usually have neither, and that is where the delay, the repeat question and the lost access arrangement collect. This module gives you a name for those points, five things that have to travel across each one, a six-column map you can draw in about an hour, and a way to take a seam you do not own to the person who does.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Identify every point where a piece of work you touch changes hands, inside the division and beyond it.",
        "Name the five things that have to travel across a handoff, and check which of them actually do.",
        "Draw a one-page handoff map for a real process, in the order a person meets it, with the waits and the repeat asks written in.",
        "Explain why an identical route can produce unequal effects, and name who absorbs the wait.",
        "Complete a handoff and exclusion map, repair the seam inside your own step, and take one other seam to its named owner with a specific ask.",
      ],
      evidence: [
        "Four worked scenarios drawn from a policy change, a process map, a grant payment route and a cross-unit repair, each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates a handoff the division owns from a wait the person absorbs and an assumption worth checking.",
        "A completed handoff and exclusion map for one real process, kept with the process rather than in a personal file.",
      ],
      appliedNextStep: "Choose one process you touch. Walk it in the order a person meets it, fill the map in for every seam, repair the one inside your own step, and take one other seam to its named owner with a specific ask.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in Minnesota Office of Grants Management policy or Office of State Procurement requirements that alters how grants, contracts, invoices and payments move between units",
        "A change in DHS or DSD program administration, delegated authority, or the division of responsibilities between the department, counties and partner agencies",
        "Feedback from grantees, paid community advisors or disabled Minnesotans that a handoff described here does not match how the work actually goes",
      ],
      relatedDoor: "Formal decisions about delegated authority, contract and grant terms, payment timelines, county and partner agreements, and required public notices belong to the responsible DHS program administration, contracting, fiscal, communications and legal offices; this module prepares the map and the ask, it does not change an agreement or authorize a payment.",
      toolkitQuestion: "Between the unit that finishes a step and the unit that starts the next one, who is carrying the person's time, information and access arrangements, and who owes them an update?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-18-1",
        number: 1,
        title: "Where the work changes hands",
        summary: "Almost nothing a division produces is finished by one unit. This lesson locates the seams where work moves, and names the five things that have to travel across each one.",
        minutes: 11,
        learning: {
          objective: "Identify every point where a piece of work you touch changes hands, and name the five things that must travel with it for the next unit to finish the job.",
          takeaways: [
            "A handoff is any point where the work, the decision or the responsibility for it moves to a different person, unit, agency or partner. Most processes have more of them than anyone has counted.",
            "Five things have to travel across a handoff: the decision and the reason for it, what the person has already told us, the access and language arrangements already in place, the clock that is running for the person, and the name of whoever owns the next step and the next message.",
            "Steps have owners, queues and standards. Seams usually have none of the three, which is why a process can be fully staffed at every step and still fail between them.",
            "Counting the seams is the fastest way to find the delay, the repeat question and the missing notice before anyone is stopped by them.",
          ],
          evidence: "A scenario about a service change that reached the people affected after it took effect, and a knowledge check on what does and does not cross a seam.",
          appliedNextStep: "Take one process you touch and count the handoffs from a person's first contact to the final answer. Write the number down, then mark the ones you had not counted before.",
        },
        scenario: {
          context: "A DSD policy change adjusts what a service must document, effective at the start of the next quarter. Policy drafts it. Operations updates the manual. Communications writes the notice. Counties relay it locally. Language access is asked for translated versions once the text is final. The change takes effect, and the notice reaches most affected households two weeks later. The plain-language version never appears at all, because it was written from a draft and the final legal edit went out without going back.",
          prompt: "Which description of what went wrong is most useful to the people who have to fix it?",
          options: [
            { label: "Communications was late. Add a firm deadline for the notice to the policy change checklist.", response: "A real improvement to one step, and it would not have saved the plain-language version or told the counties any earlier. The notice was late because it was last in a chain nobody was holding, not because the writer missed a date." },
            { label: "The change crossed five sets of hands with no one holding three things: the effective date, the access versions and the message to the people affected. Name those three as a single owned item that travels with the change from the first draft.", response: "This is the accurate reading. Each unit did its own step correctly. What failed was the seam, and the fix is to give the three things that kept falling through a named owner who carries them the whole way.", recommended: true },
            { label: "Ask counties to explain the change locally, since they have direct contact with families and can reach them faster than a mailed notice.", response: "This moves the seam outward rather than closing it, and it adds unfunded work to county offices that also received the change late. Counties can help, but only once the change, the reason and the usable versions reach them in time." },
          ],
        },
        transfer: {
          prompt: "Pick one thing you sent to another unit in the last month. What traveled with it, and what did the next person have to go looking for?",
          options: [
            "List what you sent, and what you assumed the next person already had",
            "Name the one thing they had to ask you for, or ask the person again for",
            "Decide what you will attach by default next time, so nobody has to chase it",
          ],
        },
        blocks: [
          { type: "text", heading: "Steps have owners; seams usually do not", body: "<p>Almost nothing a division produces is finished by one unit. A change to a service definition passes through policy, operations, communications, language access, fiscal, contracting, data and county partners before it reaches one person's kitchen table. Each of those units has a lead, a queue and a standard for its own step. The places where the work moves between them usually have none of those things.</p><p>Those places are worth a name: <strong>seams</strong>. A seam is any point where the work, the decision or the responsibility for it changes hands — between two units in the division, between the division and a central service, between the department and a county that administers the program locally, between the division and a provider, grantee or community organization. Seams are where the delay lives, where the same question gets asked a second time, and where an access arrangement somebody carefully set up quietly disappears.</p><p>The useful move is not to ask each unit whether it did its part. Most of the time, every unit did. The useful move is to count the seams, and then ask what is supposed to travel across each one. Five things usually have to. It is rare for all five to make it.</p>" },
          { type: "list", heading: "The five things that should travel", ordered: true, items: [
            "The decision and the reason for it, not only the document it produced. The next unit cannot apply a rule well when it has to work backward to the problem the rule was meant to solve.",
            "What the person has already told us, so nobody asks them for the same information a second or third time.",
            "The access and language arrangements already in place: the format a person reads, the interpreter already booked, the contact method that works, the extra time already agreed.",
            "The clock. Which deadline is running for the person, how much of it is left, and who is holding it while the work is internal.",
            "The name of the person who owns the next step, and the name of whoever owes the person on the other end an update.",
          ] },
          { type: "tabs", heading: "Six kinds of seam, and what usually falls through", tabs: [
            { label: "Inside the division", body: "<p>Policy writes it, operations applies it, communications explains it, quality watches how it lands. The most common loss here is the reason. Operations receives a rule without the problem behind it, and applies it literally in the cases nobody anticipated.</p>" },
            { label: "To a central service", body: "<p>Fiscal, contracting, legal, communications, language access and technology support every division at once and see only their slice of any one request. What falls through here is the deadline and the person behind it. A routine position in a queue can be a hard date for someone waiting.</p>" },
            { label: "To another state agency", body: "<p>Housing, employment, education and health work reaches the same Minnesotans through different doors, different eligibility language and different records. What falls through here is the person's own account of their situation, which they end up giving again at every door.</p>" },
            { label: "To counties", body: "<p>Minnesota delivers much of its human services work through counties under state supervision. What falls through here is the practical burden. A change that costs the state a paragraph can cost a county office a new routine, retraining and a month of confused calls — and the notice often arrives after the effective date.</p>" },
            { label: "With Tribal Nations", body: "<p>Coordination with Tribal Nations rests on a government-to-government relationship and on consultation requirements that this module does not interpret and does not substitute for. For anything involving Tribal Nations, Native American communities or tribal human services, the responsible offices are the Department of Human Services offices that handle tribal matters and the Office of Indian Affairs. Bring the question to them early rather than reading a general coordination practice across.</p>" },
            { label: "To providers and community partners", body: "<p>Contracts, grants, payments, reporting and program guidance all cross this seam. What falls through here is cost and timing. The same requirement and the same wait land very differently on a large organization and on a small, community-based one.</p>" },
          ] },
          { type: "leaderMove", heading: "Name the seam you already own", control: "You control what leaves your step: what you attach, what you write down, who you name as the next contact, and whether the person on the other end hears anything while they wait.", failure: "Do not treat a handoff as finished when the work leaves your queue. Sent is not received, and received is not usable.", next: "Before your next handoff leaves your desk, attach the five things and name the next owner by name, not by unit." },
          { type: "flashcards", heading: "Language for the map", cards: [
            { front: "Step", back: "<p>A piece of work with an owner, a queue and a standard. Steps are usually well managed and well measured.</p>" },
            { front: "Seam", back: "<p>The point where work, a decision or responsibility changes hands. Rarely owned by anyone, which is exactly why problems collect there.</p>" },
            { front: "The wait", back: "<p>The time between one unit finishing and the next one starting. Nearly invisible inside the organization, completely visible to the person waiting.</p>" },
            { front: "The repeat ask", back: "<p>Any moment a person is asked for information they have already given. A reliable sign that something did not travel across a seam.</p>" },
            { front: "Diffused accountability", back: "<p>Every unit did its part correctly and the result still failed the person. The steps were owned; the seam was not.</p>" },
          ] },
          { type: "quote", text: "I did not really mind that it took time. I minded that for six weeks nobody could tell me who had it.", cite: "Composite perspective of a person waiting on a decision, illustrative" },
          { type: "knowledgeCheck", id: "ipe-18-1-check", question: "A program unit sends a complete, correctly filled request to a central service. Three weeks later the person who is waiting calls to ask where it stands, and no one she reaches can tell her. What does this most clearly show?", options: [
            { text: "A staffing problem in the central service; the queue is simply too long right now.", correct: false },
            { text: "A seam with no owner: the request crossed, but the clock she is under and the name of whoever owes her an update did not cross with it.", correct: true },
            { text: "A communication problem with the person; she should have been told at the start to expect a long wait.", correct: false },
          ], feedbackCorrect: "Yes. The document arrived. What did not arrive was the deadline running for her and the name of the person who owes her an answer, which is why the question has no answer inside the organization.", feedbackIncorrect: "Look at what actually crossed the seam. The form did. Her clock and the name of whoever owes her an update did not, and that is why nobody can tell her anything." },
        ],
      },
      {
        id: "ipe-18-2",
        number: 2,
        title: "Drawing the handoff map",
        summary: "Six columns, one page, and the path the person travels rather than the chart of who reports to whom. How to draw it, and why the first draft should go out before it is right.",
        minutes: 11,
        learning: {
          objective: "Draw a six-column handoff map for one real process, showing each change of hands, what moves, what the person is asked for again, how long the wait is and what the person hears during it.",
          takeaways: [
            "Map the path the person travels, not the organization chart. The two pictures rarely look alike, and only one of them shows where work stalls.",
            "Six columns are enough: the step and its named owner, what moves and in what form, what the person has to supply again, the wait and what they hear during it, who could be excluded here, and the first fix with a name and a date on it.",
            "Step times reported unit by unit hide the seams, because each unit measures from the moment work reaches its own queue. The days between queues belong to no one and appear in no report.",
            "A map is a draft until the other owners correct it. A map that arrives as a question gets corrected; a map that arrives as a finding gets defended.",
          ],
          evidence: "A scenario about shortening the time to a decision, a sorting exercise that separates a handoff the division owns from a wait the person absorbs, and a knowledge check on what unit-by-unit reporting cannot show.",
          appliedNextStep: "Draw the path for one process on a single page, in the order a person meets it, and send it to the other named owners with one sentence asking them to correct your version of their step.",
        },
        scenario: {
          context: "You are asked to shorten the time between a request and a decision in a program you support. Each of the four units involved can report its own average completion time, and each is under three days. The people who apply routinely wait six to eight weeks, and a noticeable share stop responding partway through.",
          prompt: "Where should the mapping work start?",
          options: [
            { label: "With the slowest of the four internal steps, since that is where the biggest time saving is available.", response: "The slowest step is not necessarily where people fall out, and four steps under three days each do not add up to six weeks. Starting here would optimize a part of the process that is not the problem." },
            { label: "Draw the whole path from the person's first contact to the final answer, mark every change of hands, every point where they are asked for something again and every wait between units, then check where people actually stop responding.", response: "This is the map. It puts the internal steps and the invisible gaps on the same page, in the order a person meets them, and it looks for the drop-off points rather than assuming where they are.", recommended: true },
            { label: "Ask each of the four units to report its own completion time in a standard format, then add them together for a total.", response: "Adding the parts gives you eight days and hides six weeks. Unit reporting starts the clock when work reaches that unit's queue, so the time between queues — which is most of the elapsed time — never appears anywhere." },
          ],
        },
        transfer: {
          prompt: "Whose step in your process do you understand least?",
          options: [
            "Name the unit whose step you have never actually watched anyone do",
            "Ask them what arrives from you, and what they usually have to chase",
            "Write their step into your map in their words rather than your own",
          ],
        },
        blocks: [
          { type: "text", heading: "Map the path, not the organization chart", body: "<p>A coordination problem looks entirely different depending on which picture you draw. Draw the organization chart and you see units, leads and reporting lines. All of it is accurate, and none of it tells you where the work stalls. Draw the path the person travels, from their first contact to the answer they finally receive, and the picture changes: a short chain of steps separated by long, undocumented waits.</p><p>Keep the map to one page and six columns. It should be readable by someone who does not work in your unit, and it should be written in the order a person meets the process rather than in the order the units appear on a chart. An hour is usually enough for a process you already know well, and considerably longer for one you only thought you knew.</p><p>Two cautions. First, completion times reported unit by unit will not reveal the seams, because each unit starts its clock when the work reaches its own queue; the days between queues belong to nobody. Second, your first draft of another unit's step will be wrong in some detail that matters to them. Send it to them anyway, early, and ask them to correct it. The point of the draft is to be corrected.</p>" },
          { type: "accordion", heading: "The six columns, and what belongs in each", items: [
            { title: "Step and named owner", body: "<p>Name the person, not only the unit. Contracting is not an owner; a named contracting officer is. If nobody can name the owner of a step, you have already found something worth writing down.</p>" },
            { title: "What moves, and in what form", body: "<p>The request, the decision, the file, the approval, the money. Note the form it arrives in, because the form decides whether the next unit can use it or has to rebuild it from scratch.</p>" },
            { title: "What the person supplies again", body: "<p>Every piece of information the person has to provide a second time. Each repeat request marks a seam where something did not travel, and repeat requests are where people quietly drop out.</p>" },
            { title: "The wait, and what the person hears", body: "<p>How long the work sits between units, in days, and what the person on the other end is told during that time. In most processes the honest answer to the second half is nothing at all.</p>" },
            { title: "Who could be excluded here", body: "<p>Name people and situations, not categories. Someone who reads in another language. Someone who cannot call during business hours. Someone whose rent is due. An organization with no cash reserve. Categories are easy to agree with and hard to act on.</p>" },
            { title: "First fix, owner, next review point", body: "<p>One change, one name, one date already on somebody's calendar. A line with no owner is an observation, not a fix.</p>" },
          ] },
          { type: "sorting", id: "ipe-18-2-sort", heading: "Whose burden is this, and is it even true?", categories: ["A handoff the division owns", "A wait the person absorbs", "An assumption worth checking"], items: [
            { text: "The request sits in a shared queue for eleven days between the program unit and contracting.", category: "A handoff the division owns" },
            { text: "A grantee delays payroll for a month while an invoice is corrected and resubmitted.", category: "A wait the person absorbs" },
            { text: "Counties will pass the change along to families, so a separate notice is probably not needed.", category: "An assumption worth checking" },
            { text: "The plain-language version is written from a draft, and the final legal edit is never sent back for a new one.", category: "A handoff the division owns" },
            { text: "People who do not answer the second notice are most likely no longer interested.", category: "An assumption worth checking" },
            { text: "A family loses an unpaid day of work for an appointment rescheduled twice while two units settle who approves it.", category: "A wait the person absorbs" },
          ] },
          { type: "leaderMove", heading: "Send the draft before it is right", control: "You control whether your map arrives as a question or as a verdict about somebody else's work.", failure: "Do not present another unit's step as a finding in a meeting they are not in. The map will be argued rather than corrected, and you will lose the people whose help you need.", next: "Send your draft to each named owner with one line: this is my understanding of your step, tell me what I have wrong." },
          { type: "statement", body: "Private reflection, for you only: think of a handoff you are part of every week. How might your role, your authority or the words you choose decide what the next unit assumes? Nothing you write here is collected, stored or seen by anyone." },
          { type: "knowledgeCheck", id: "ipe-18-2-check", question: "Four units each report that their average time to complete their own step is two days. The person applying waits seven weeks for an answer. What does the map need to show that the unit reports do not?", options: [
            { text: "A more precise measure of each unit's two days, so the total is accurate.", correct: false },
            { text: "The waits between the units and what the person hears during them; eight days of work inside seven weeks of elapsed time means the answer is in the gaps.", correct: true },
            { text: "Which of the four units is understating the time its step actually takes.", correct: false },
          ], feedbackCorrect: "Yes. Add the reported step times, compare them with the person's experience, and the difference is the part nobody is measuring.", feedbackIncorrect: "Compare eight days of reported work with seven weeks of waiting. The gap is not inside any unit's step, so no unit's report will ever show it." },
        ],
      },
      {
        id: "ipe-18-3",
        number: 3,
        title: "Where exclusion collects",
        summary: "A handoff can be perfectly neutral in writing and still sort people. The five failure points that gather at a seam, and why an identical route does not produce an equal effect.",
        minutes: 11,
        learning: {
          objective: "Name the five failure points that concentrate at a handoff, and explain why an identical route can produce very different burdens for different people and organizations.",
          takeaways: [
            "Access arrangements are the first thing to fall off at a seam. A plain-language version, a translation, a preferred contact method or an agreed allowance of extra time usually lives with one unit and does not travel with the work.",
            "The same wait is not the same burden. A payment delay that a large organization absorbs can stop a small, community-based one from operating, and repeated delays quietly narrow who is willing to contract with the state at all.",
            "At a seam, treating everyone the same way is the most common form of Minimization. The route really is identical and the effect really is not, and only the first of those is easy to check.",
            "Every unit can be correct at its own step while the process fails the person. That is what diffused accountability looks like from the outside, and it is the honest reason coordination work matters.",
          ],
          evidence: "A scenario about a grant payment route that is applied consistently and still harms the smallest partner, a sorting exercise on the failure points, and a knowledge check on identical routes with unequal effects.",
          appliedNextStep: "Take one handoff you are part of and ask who absorbs the wait. Write down what it costs them in money, time or trust, and name who could change it.",
        },
        scenario: {
          context: "A DSD grant supports a small, community-based organization serving disabled adults in a specific cultural community. Invoices route from the program unit to fiscal to central processing. A missing field returns the invoice with a standard letter, no named contact, and a review period that restarts. Payment averages 10 weeks. Larger grantees absorb it. This organization pauses services for a month, and its director says she is unlikely to apply in the next cycle.",
          prompt: "What is the most accurate reading of this situation?",
          options: [
            { label: "The organization needs to submit complete invoices. Offer training on the invoice requirements and monitor whether errors drop.", response: "Training may help and it puts the whole burden on the grantee. It leaves untouched the letter with no named contact, the restarted clock and the absence of anyone who owes the organization an update — which is where most of the 10 weeks actually comes from." },
            { label: "The route is neutral on paper and unequal in effect. Name the three seam problems — a rejection letter with no named contact, a review period that restarts, and nobody who owns telling the grantee where it stands — fix those, and treat payment timeliness as part of what the division is accountable for.", response: "This is the accurate reading. It keeps the requirements intact, fixes the parts of the route that the division controls, and recognizes that a delay the division treats as routine is doing different work to different organizations.", recommended: true },
            { label: "Advance this organization's payment as a one-time exception so services can resume immediately.", response: "Understandable, and it may not be within anyone's authority here. Even where it is, a single exception helps once and changes nothing for the next cycle or the next grantee. The route produced this, and the route is what can be repaired." },
          ],
        },
        transfer: {
          prompt: "Which of the five failure points shows up most often in your own work?",
          options: [
            "Name the one you see most, and the process where you see it",
            "Write down what it costs the person or the organization on the other end",
            "Name the one change inside your own step that would reduce it",
          ],
        },
        blocks: [
          { type: "text", heading: "Identical routes, unequal effects", body: "<p>A handoff can be entirely neutral in writing and still sort people. The route is the same for everyone; the capacity to absorb it is not. A payment that arrives 10 weeks late is an accounting inconvenience for an organization with reserves and a payroll emergency for a small one without them. A notice that requires a phone call during business hours is a minor task for a salaried employee and a lost shift for someone paid by the hour. Nobody designed either result, and the process produces both.</p><p>Five failure points account for most of what goes wrong at a seam. <strong>Access arrangements do not travel</strong>, so the interpreter, the format and the extra time have to be requested again. <strong>The person is asked again</strong> for information they already gave. <strong>Silence during the wait</strong>, because internal time is invisible from the inside. <strong>Identical route, unequal effect</strong>, where the same delay costs different people very different amounts. <strong>Nobody owns the seam</strong>, so each unit can truthfully report that it did its part.</p><p>The fourth one deserves its name. The program uses the intercultural development continuum — Denial, Polarization, Minimization, Acceptance, Adaptation and Integration — as its theory of change, and a handoff is where Minimization shows most plainly: difference is acknowledged in principle and set aside in practice, because the route is genuinely the same for everyone. Acceptance begins when a division can say out loud that the same wait costs different people different amounts. Adaptation is when the handoff is redesigned around that fact rather than explained away. Integration is when the people the process affects help design the coordination itself. These stages describe how the program examines and builds its own processes. They are never a label, a rating or a record about any individual.</p>" },
          { type: "flashcards", heading: "The five failure points", cards: [
            { front: "Access arrangements do not travel", back: "<p>The format, the interpreter, the contact method and the agreed extra time live with one unit. At the seam the person starts over, usually by asking again for something they already arranged.</p>" },
            { front: "The person is asked again", back: "<p>Information already given is requested a second or third time. Every repeat request is both a sign that something did not cross and a point where people stop responding.</p>" },
            { front: "Silence during the wait", back: "<p>The work moves between queues and the person hears nothing. Waiting without information is a different experience from waiting with it, and the difference is entirely within the division's control.</p>" },
            { front: "Identical route, unequal effect", back: "<p>The same steps and the same delay land differently depending on what a person or organization can absorb. Consistency of the route is a fact; equality of the effect is a claim that has to be checked.</p>" },
            { front: "Nobody owns the seam", back: "<p>Each unit reports success and the result still fails. Until a named person carries the work across the gap, the gap will keep producing the same outcome.</p>" },
          ] },
          { type: "tabs", heading: "The same 10-week payment route, four different costs", tabs: [
            { label: "A large provider organization", body: "<p>Absorbs it. Reserves cover payroll, an accounts team follows the invoice, and the delay never reaches the people served. From inside the division, this organization's experience is the one that makes the route look fine.</p>" },
            { label: "A small community-based organization", body: "<p>Cannot absorb it. Payroll is delayed or a line of credit is drawn at real cost, services pause, and the organization thinks hard before applying again. Across several cycles this quietly narrows the range of organizations willing to work with the state.</p>" },
            { label: "The people that organization serves", body: "<p>See a service stop with no explanation they can act on, and often conclude that the organization is unreliable rather than that a payment route is slow. Trust is lost at the point closest to them.</p>" },
            { label: "The staff member holding the seam", body: "<p>Takes calls about a queue they do not control, has nothing to offer but sympathy, and learns over time to stop answering. Nobody designed this job, and somebody is doing it in every division.</p>" },
          ] },
          { type: "sorting", id: "ipe-18-3-sort", heading: "Which failure point is this?", categories: ["Access arrangements did not travel", "The clock kept running for the person", "Nobody owned the seam"], items: [
            { text: "The interpreter booked for the first appointment is not booked for the second, because a different unit arranges the second.", category: "Access arrangements did not travel" },
            { text: "A request for a correction restarts the review period, and the deadline the person was given does not move.", category: "The clock kept running for the person" },
            { text: "Three units confirm the request left their queue, and none can say where it is now.", category: "Nobody owned the seam" },
            { text: "The translated version is produced from a draft, and the final version is issued in English only.", category: "Access arrangements did not travel" },
            { text: "An appeal window keeps running while the file waits for one signature.", category: "The clock kept running for the person" },
            { text: "Everyone agrees the notice should have gone out, and no one's step included sending it.", category: "Nobody owned the seam" },
          ] },
          { type: "quote", text: "We can carry a late payment once. Twice in a year and I am choosing between making payroll and applying for the next grant. Nobody has ever asked me which one I chose.", cite: "Composite community organization perspective, illustrative" },
          { type: "leaderMove", heading: "Ask who absorbs the wait", control: "You control whether the question how long does this take us is followed by the question who is carrying that time.", failure: "Do not accept that a route is fair because it is identical. Identical is a fact about the process; fair is a claim about its effects, and only one of the two is easy to verify.", next: "At the next review of a process you are part of, ask out loud who absorbs the wait and what it costs them, and write the answer into the record." },
          { type: "knowledgeCheck", id: "ipe-18-3-check", question: "A division applies the same review timeline and the same correction process to every grantee. Two small, community-based organizations withdraw from the program in the same cycle; the larger organizations do not. What is the most useful reading?", options: [
            { text: "The route was applied equally, so the withdrawals reflect those organizations' own capacity rather than anything about the process.", correct: false },
            { text: "An identical route can still sort organizations, because the capacity to absorb delay is not evenly distributed. The process needs to be examined for who it costs most, not only for whether it was applied consistently.", correct: true },
            { text: "The division should reduce its documentation requirements for smaller organizations so they can keep up.", correct: false },
          ], feedbackCorrect: "Yes. Consistency of the route and equality of the effect are two different claims, and the second one has to be checked rather than assumed.", feedbackIncorrect: "Consistency was never in question here. Ask instead what the same delay costs an organization with reserves and one without, and what the pattern of withdrawals is telling you about the route." },
        ],
      },
      {
        id: "ipe-18-4",
        number: 4,
        title: "Your handoff and exclusion map",
        summary: "Walk one process in the order a person meets it, fill the map in for every seam, repair the one inside your own step, and take the others to their named owners with a specific ask.",
        minutes: 11,
        learning: {
          objective: "Complete a handoff and exclusion map for one real process, naming each seam, the people it could exclude, the owner and the first fix, and decide which seam you will repair yourself.",
          takeaways: [
            "Repair the seam inside your own step before the map goes anywhere. It is the only part that needs nobody's permission, and a completed fix is what makes the rest of the map credible.",
            "A seam you do not own still needs a named person, a measured wait and one specific ask, rather than a copy of the whole map and a general concern.",
            "Ask for something inside the other owner's authority: a named contact on a rejection letter, an issue date in an acknowledgment, one field removed. Save the larger redesign for the people who can authorize it.",
            "Keep the map with the process rather than in a personal file, so the next person to hold the work inherits what you learned.",
          ],
          evidence: "A completed handoff and exclusion map, a scenario about what to do with the seams you do not own, and a private reflection on accountability and repair.",
          appliedNextStep: "Fill the map in for one process this month, repair the seam inside your own step, tell the units on either side of you what changed, and take one other seam to its named owner with a specific ask.",
        },
        scenario: {
          context: "You have walked a process you support and filled in the map. It shows four seams. One sits inside your own step. Two belong to units in other parts of the department, and one belongs to a central service you rarely deal with. The longest wait on the page is at a seam you do not own.",
          prompt: "What is the most effective first move?",
          options: [
            { label: "Send the completed map to leadership in all four areas and ask for the fixes to be assigned to the right owners.", response: "This hands the map back to the same diffusion it documents. Four areas receive a document about other people's steps, nobody has been asked for anything specific, and the longest wait stays exactly where it is." },
            { label: "Repair the seam inside your own step first, then take one other seam at a time to its named owner, with the wait measured, the effect named and one specific ask they can actually grant.", response: "This is the sequence that produces change. Your own completed fix shows the map is a working document rather than a complaint, and a single seam with a single ask is something a named owner can act on this month.", recommended: true },
            { label: "Hold the map until you have verified every step with every unit involved, so the version you circulate is beyond dispute.", response: "Accuracy matters, and a perfect map in a personal file changes nothing. Verification happens faster when the draft goes out for correction than when you try to close every question yourself." },
          ],
        },
        transfer: {
          prompt: "Which seam will you repair yourself, and who will ask you about it?",
          options: [
            "Name the seam inside your own step and the exact change you will make",
            "Name the person in another unit you will take one seam to, and the specific ask",
            "Name the colleague who will ask you in a month what actually changed",
          ],
        },
        blocks: [
          { type: "text", heading: "Walk it in the order a person meets it", body: "<p>Reviewing a process means reading the policy and looking at the form. Walking it means following one real request from the first moment a person touches the process to the moment they hear an answer, crossing every seam in the order the seams occur, and writing down what happens in the gaps. It takes about an hour for a process you already know, and a good deal longer for one you only thought you knew.</p><p>Two rules make the walk worth the hour. Start where the person starts, not where your unit starts; a process that begins for you when the file arrives began for them weeks earlier, often with a phone call nobody logged. And write the wait as the person experiences it, in days, with what they were told during it. Internal time is nearly invisible from the inside and it is most of what is visible from outside.</p><p>Then fill the map in, one set of six lines for each seam. Repair the seam inside your own step first. Take the seams you do not own to the people who do, one at a time, with the wait measured and a specific ask attached. Keep the finished map with the process, not in your own files, so that whoever holds this work next does not start from nothing.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A handoff and exclusion map for one process", summary: "Six lines for each seam in a process you touch. One page, written in the order a person meets it, ready to send to the owners you name.", fields: [
            { label: "Process, and the point where a person first meets it", value: "Mid-year grant amendment that changes a service level. The first point a person meets it is the day the organization tells them the service is changing, which is also the first they hear of it." },
            { label: "Handoff, and the two owners on either side of it", value: "Seam two of four: program unit to contracting. Owners: the named program lead who approves the change, and the named contracting officer who issues the amendment." },
            { label: "What moves, and what does not move with it", value: "The amendment request and the approval move. The reason for the change, the notice date the organization was promised, and the name of whoever will tell participants do not move." },
            { label: "The wait, and what the person hears during it", value: "Eighteen days between approval and an issued amendment. Participants hear nothing. The organization is told to wait for paperwork, with no date and no contact." },
            { label: "Who could be excluded here, and what it costs them", value: "Participants who need the current service level until the new one starts, and those who read in a language other than English. The organization, which cannot plan staffing. Cost: a gap in service and a month of uncertainty." },
            { label: "First fix, owner, and the next review point", value: "Attach a named participant-notice owner and a plain-language summary to every amendment request, and add the expected issue date to the contracting acknowledgment. Owners: the program lead and the contracting officer. Review together at the agreed point." },
          ], action: "Copy the six lines, fill one set for each seam in a process you touch, repair the seam inside your own step, and send the map to the owners you named with one specific ask for each seam you do not own." },
          { type: "list", heading: "First fixes that need nobody's permission", items: [
            "Name a person, not a unit, as the next owner on everything that leaves your step.",
            "Keep the plain-language and translated versions attached to the same record as the final text, so a last edit cannot leave them behind.",
            "Send one line to the person waiting whenever the work moves: where it is, who has it, and roughly how long.",
            "Carry the access record forward: the format, the interpreter, the contact method and any extra time already agreed.",
            "Put the deadline the person is under at the top of what you hand over, not buried in the body.",
            "When you return something for correction, say exactly what is missing, name a contact, and say whether the clock restarted.",
            "Ask the unit you hand off to most often what they always have to chase you for, and then stop making them chase it.",
          ] },
          { type: "accordion", heading: "Taking a seam you do not own to the person who does", items: [
            { title: "Bring one seam, not the whole map", body: "<p>A full map invites a discussion about the map. One seam, with the wait measured and the effect named, invites a decision. Keep the rest of the page for later conversations with other owners.</p>" },
            { title: "Bring the effect, not the frustration", body: "<p>This takes too long is a complaint. Eighteen days here, and the organization holds payroll through it, is a finding. The second version can be acted on, and it does not require anyone to accept blame before they can help.</p>" },
            { title: "Bring an ask they can actually grant", body: "<p>Ask for something inside their authority: a named contact on the rejection letter, an expected date in the acknowledgment, one field removed from a form. If the fix needs approval further up, ask them who to approach and whether they will come with you.</p>" },
          ] },
          { type: "leaderMove", heading: "Repair your own seam first", control: "You control the seam on your own side: what you attach, who you name, what you tell the person waiting, and whether the access record travels with the work.", failure: "Do not send the map upward and wait. A map with nothing fixed on your own side reads as a complaint about other people's steps, and it will be received that way.", next: "Make one fix inside your own step this month, tell the units on either side of you what changed, and then take the next seam to its named owner." },
          { type: "knowledgeCheck", id: "ipe-18-4-check", question: "Your finished map shows four seams. One is inside your own step; three belong to other units. Which first move is most likely to produce an actual repair?", options: [
            { text: "Send the full map to leadership in all four areas and ask for the fixes to be assigned.", correct: false },
            { text: "Repair the seam inside your own step, then take one other seam at a time to its named owner with the wait measured and a specific ask.", correct: true },
            { text: "Hold the map until every step has been verified with every unit, so the version you send is beyond dispute.", correct: false },
            { text: "Circulate the map to the three other units at once and ask each to reply with a plan.", correct: false },
          ], feedbackCorrect: "Yes. A completed fix on your own side makes the map credible, and one seam with one specific ask is something a named owner can act on this month.", feedbackIncorrect: "Ask which version of this actually gets something changed. A map with nothing repaired on your own side reads as a complaint, and four requests at once tend to produce four replies and no repairs." },
          { type: "statement", body: "Private reflection, for you only: if a handoff you are part of has excluded someone, what would accountability and repair actually require — of your own step, of the process, and toward the people who were left waiting? Nothing you write here is collected, stored or seen by anyone." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Cross-division coordination",
    subtitle: "One page for anyone whose work arrives from somewhere else and leaves for somewhere else",
    quote: "Nothing fails at a step as often as it fails between two.",
    use: {
      purpose: "Keep the seams, the five things that travel and the six map lines in view while you move work between units, issue a change, route an invoice or answer someone who is waiting.",
      remember: [
        "Steps have owners, queues and standards. Seams usually have none of the three, which is why problems collect there.",
        "Five things have to travel: the decision and its reason, what the person already told us, the access and language arrangements, the clock, and the name of the next owner.",
        "Map the path the person travels, not the organization chart. Unit-by-unit reporting cannot show the waits between queues.",
        "The same wait is not the same burden. Ask who absorbs it and what it costs them.",
        "Identical is a fact about the route. Fair is a claim about its effects, and it has to be checked.",
        "Repair the seam inside your own step first. It is the only one that needs nobody's permission.",
      ],
      doNext: "Walk one process in the order a person meets it, fill the map in for every seam, and repair the one you own before the map goes anywhere.",
    },
    sections: [
      {
        heading: "The handoff map, in short",
        items: [
          "Step and named owner: a person, not a unit. If nobody can name the owner, write that down.",
          "What moves, and in what form: whether the next unit can use it or has to rebuild it.",
          "What the person supplies again: every repeat request marks something that did not travel.",
          "The wait, and what the person hears: in days, with the honest answer about what they were told.",
          "Who could be excluded here: named people and situations, not categories.",
          "First fix, owner, next review point: one change, one name, one date already on a calendar.",
        ],
      },
      {
        heading: "The five things that should travel",
        items: [
          "The decision and the reason for it, not only the document it produced.",
          "What the person has already told us, so nobody asks a second time.",
          "The access and language arrangements already in place: format, interpreter, contact method, extra time.",
          "The clock: which deadline is running for the person, how much is left, and who holds it.",
          "The name of the next owner, and of whoever owes the person an update.",
        ],
      },
      {
        heading: "Where exclusion collects at a seam",
        items: [
          "Access arrangements do not travel, so the person arranges them again.",
          "The person is asked for information they already gave.",
          "Silence during the wait, because internal time is invisible from the inside.",
          "An identical route with unequal effects, which is Minimization in its most ordinary form.",
          "Nobody owns the seam, so every unit can report success while the result fails.",
        ],
      },
      {
        heading: "When the seam is not yours",
        items: [
          "Bring one seam, not the whole map.",
          "Bring the measured wait and the named effect, not the frustration.",
          "Bring an ask inside that person's authority, and ask who else has to agree.",
          "For anything involving Tribal Nations or tribal human services, go first to the Department of Human Services offices that handle tribal matters and the Office of Indian Affairs.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Contracts, fiscal, grants and procurement staff, who sit at more seams than anyone else and see every invoice, amendment and payment that stalls between two units — a useful place to start.",
          "Administrative and support staff, who route the requests, book the arrangements, answer the person who is waiting and watch commitments quietly disappear — a good module to go deeper with.",
          "Policy, program and operations staff, whose changes cross five sets of hands before they reach a household.",
          "Communications, language access, quality, data and engagement staff, who usually receive work last and carry what earlier steps left behind.",
          "Supervisors and managers, who can give a seam an owner, which is the one fix most of these problems need.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "Accessible public communications",
          "Language access in state programs",
          "Program and service design",
          "Equitable stakeholder partnership",
          "Responding to concerns and feedback",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Department of Human Services, Partners and providers", href: "https://mn.gov/dhs/partners-and-providers/", note: "The department's information for counties, tribes, providers, grantees and partner agencies, including program administration guidance and the notices that cross between them." },
    { title: "Minnesota Office of Grants Management", href: "https://mn.gov/admin/government/grants/", note: "Statewide grants policies covering solicitation, agreements, monitoring, payment and closeout — the rules that govern most handoffs between a division and its grantees." },
    { title: "Minnesota Office of State Procurement", href: "https://mn.gov/admin/osp/", note: "Statewide contracting and purchasing requirements, including the approval routes that contract and amendment work passes through." },
    { title: "ADA.gov, Title II primer for state and local governments", href: "https://www.ada.gov/resources/title-ii-primer/", note: "U.S. Department of Justice explanation of what Title II requires of state and local government programs, including access to programs delivered through other agencies or contractors." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's advisory council on disability policy, access and rights, including guidance for state agencies on accessible programs, notices and public processes." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the governance, partnership and accountability standards that apply across organizational units." },
    { title: "plainlanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Practical guidance for writing notices, letters and instructions people can act on, including the correction and next-step wording that decides whether a returned request gets resolved." },
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials and accessible instruction." },
  ],
};

export default pack;
