import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Complex systems · Module 21: Race, disability and unequal outcomes.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-21-race-disability-outcomes",
    indexNumber: 1163,
    seriesLabel: "Intercultural Practice and Equity · Complex systems",
    title: "Race, Disability and Unequal Outcomes",
    subtitle: "Ableism and racism rarely arrive one at a time. Four lessons on where two patterns meet inside a public system, how to read a difference in results without jumping to a cause, and how to build the questions that make an examination worth doing.",
    scope: "For internal DHS and DSD staff whose work shapes who gets access and what happens next: policy and program staff; quality, compliance and performance staff; data, research and evaluation staff; contracts, fiscal and procurement staff; and executive and senior leaders. Communications, training, engagement, administrative and support colleagues will recognize their own steps in it too. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota public-administration examples, scenarios, sorting and flashcard practice, private reflection prompts, and a disparity inquiry guide you can copy into your own work",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/equity-inclusion-leadership-systems.jpg",
    coverAlt: "A mixed leadership table reviews printed charts.",
    introTranscript: "Most of the unequal results a public system produces were never designed by anyone. They come out of ordinary decisions: a requirement everyone must meet the same way, an assessment administered in a language that was almost right, a survey mailed to the people still receiving a service. This module looks at what happens when the patterns we call ableism and racism meet inside one of those decisions, because people do not encounter them one at a time. It then does the harder part: how to read a difference in results without either explaining it away or attaching a cause to it that arrived before the evidence did. It ends with a one-page inquiry guide you can fill in for a real outcome in your own work. Nothing here is scored, ranked or collected, the reflection prompts are yours alone, and nothing in this module is a label or a record about any individual.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Explain how ableism and racism can operate at the same time inside one public process, and describe the combined effect in terms of results rather than intentions.",
        "Locate where in a service path an outcome difference could have been produced, from access and eligibility through assessment, navigation, crisis response, housing, work and quality reporting.",
        "Read a reported difference well enough to name its denominator, the categories it collapses and the people missing from it before naming a cause.",
        "Keep a group-level pattern strictly separate from any claim about an individual person or about anyone's motive.",
        "Complete a disparity inquiry guide for one outcome you are responsible for, naming who should shape the inquiry, how they are paid, and what the division will do if the answer points at its own decisions.",
      ],
      evidence: [
        "Four worked scenarios drawn from policy drafting, quality reporting, evaluation and contract renewal, each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that places a difference at the step where it was produced, and separates what a number shows from what it only suggests.",
        "A completed disparity inquiry guide kept with the program file rather than in a personal folder.",
      ],
      appliedNextStep: "Choose one outcome you are responsible for where a difference has been mentioned but never examined. Fill in the inquiry guide, start with the line on who is missing from the number, confirm the advisor payment route with a fiscal colleague, and write down what the division will do if the answer points at a step we own.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in DHS or DSD direction on equity reporting, quality measurement, or how race, ethnicity, language and disability information is collected and published",
        "A change in federal or state civil rights guidance affecting Title VI, ADA Title II or Section 504 obligations for state human services programs",
        "Feedback from paid community advisors, self-advocates or disability-led organizations that the examples or the inquiry guide do not match how these questions actually go inside the division",
      ],
      relatedDoor: "Formal determinations about a civil rights complaint, a disparate-impact finding, a contract action, or the publication of disparity data belong to the responsible DHS civil rights, legal, data governance and contracting offices; this module prepares the inquiry, it does not make the finding.",
      toolkitQuestion: "Who could be helped, burdened, excluded or misunderstood by this process, and whose expertise is missing from the decision about it?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-21-1",
        number: 1,
        title: "Two patterns, one process",
        summary: "Ableism and racism operate through defaults and designs, not only through attitudes. People meet them together, and the combination behaves differently from either one alone.",
        minutes: 11,
        learning: {
          objective: "Explain how ableism and racism can operate at the same time inside one public process, and describe the combined effect in terms of what the process produced rather than what anyone intended.",
          takeaways: [
            "Both patterns are carried in ordinary things: the form that assumes a stable address, the assessment that assumes a person speaks for themselves in English, the appointment offered only on a weekday morning. Neither needs a person with bad intentions to operate.",
            "People do not meet these patterns one at a time. The combination often produces a result that neither pattern alone would have predicted, which is why a fix aimed at one of them can leave the other completely untouched.",
            "Every process carries an unspoken picture of the person it was built for. Writing that picture down in one sentence is usually the fastest way to see who the process works less well for.",
            "“The rule is the same for everyone” describes the rule. It does not describe the result, and the result is what a public agency is answerable for.",
          ],
          evidence: "A scenario about a documentation requirement described as neutral, tabbed examples of what each pattern does inside a process, flashcards that keep the working words apart, and a knowledge check on identical rules and unequal results.",
          appliedNextStep: "Take one process you touch. Write, in a single sentence, the person it appears to have been built for: their language, their transportation, their paperwork, their schedule, and who is available to help them. Then name one group that sentence leaves out.",
        },
        scenario: {
          context: "A DSD policy team is updating what a person must submit to keep receiving a waiver service. The draft asks for a signed form from a treating professional dated within the past ninety days. A manager reviewing it says the change is neutral: the requirement is identical for everyone who receives the service, so it cannot favor anyone.",
          prompt: "What is the most useful thing to say next?",
          options: [
            {
              label: "Agree. A requirement that applies to everyone in the same way cannot produce unequal results; any differences that appear later come from outside the program.",
              response: "The requirement is identical. The ability to meet it is not. Getting a treating professional to sign something inside ninety days depends on insurance, transportation, clinic wait times, interpreter availability, and whether a professional already knows the person well enough to sign. An identical rule meeting unequal conditions is one of the most common ways a public process produces an unequal result.",
            },
            {
              label: "Ask what it actually takes to meet the requirement — distance to a clinic that will see the person, appointment waits, interpreter availability, whether someone already knows them — and then ask which parts of the state and which communities have the least of those.",
              response: "This keeps the attention on what the requirement will produce, without accusing anyone of intent. It also produces something the team can act on: a second route to meet the requirement, a longer window, or help arranging the appointment.",
              recommended: true,
            },
            {
              label: "Suggest collecting race and disability information after the change takes effect, and revisiting the requirement if a difference shows up in reporting.",
              response: "Measuring afterward is worth doing, and it is not a substitute for asking the question now. By the time a difference appears in a report, people have already lost a service, and the burden of demonstrating harm has quietly moved onto them.",
            },
          ],
        },
        transfer: {
          prompt: "Where in your own work does a single requirement do most of the sorting?",
          options: [
            "Name one requirement in a process you touch that everyone must meet in the same way.",
            "List what a person needs in order to meet it: a document, a professional, a device, a ride, a translated form, someone free during business hours.",
            "Name which of those a person is least likely to have, and say why that is not randomly distributed.",
            "Write one alternative route to meeting the same requirement, and name who would have to approve it.",
          ],
        },
        blocks: [
          {
            type: "text",
            heading: "Two patterns, one process",
            body: "<p>Ableism is the set of assumptions and designs that treat one way of moving, thinking, communicating and working as ordinary, and everything else as an exception to be requested, documented and approved. At the level of a public system, racism works through the same mechanism: rules, defaults and habits shaped around one set of conditions, applied to people whose conditions are different, producing results that follow the difference rather than the rule.</p><p>Neither needs a person with bad intentions to operate. Both are carried in ordinary working material: the form that assumes a stable address, the assessment that assumes the person speaks for themselves in English, the appointment slot that assumes a weekday off, the standard that reads family involvement as support or as interference depending on how the family behaves in a meeting. Most of what a division does is built out of that material, and most of it was built by people trying hard to be fair.</p><p>What makes this module harder than either topic alone is that people do not meet these patterns one at a time. A man with a brain injury who speaks Somali at home, a grandmother caring for a grandchild with a developmental disability in a household where three languages are spoken, a Black teenager whose behavior is recorded as a conduct problem in one setting and as a disability need in another, and a farmer forty miles from the nearest assessor are not four versions of the same problem. Each meets a specific combination of design decisions, and the combination can produce something neither pattern, taken alone, would have predicted.</p><p>This program uses the intercultural development continuum to describe movement: Denial, Polarization, Minimization, Acceptance, Adaptation and Integration. Minimization is the most comfortable place for a public agency to sit, because it sounds exactly like fairness — the rules are the same for everyone, so the results must be fair enough. Moving toward Acceptance means letting a difference in results be real and worth understanding. Moving toward Adaptation means changing the design once you understand it. None of that is a label about you, and nothing in this program is recorded about any individual.</p>",
          },
          {
            type: "tabs",
            heading: "What each pattern does inside a process",
            tabs: [
              { label: "Ableism in a process", body: "<p>It sets a default body, pace and way of communicating, and then treats every other way as a request. The person has to notice that an adjustment exists, know to ask, have the words for it, and be believed. Each of those steps is a filter. It also shows up as expectation: what a worker believes this person will be able to do shapes what is offered long before anyone writes it down.</p>" },
              { label: "Racism in a process", body: "<p>It works through where services were built, which languages the forms exist in, whose family arrangements are recognized, whose account of their own life is taken at face value, and which behavior is read as cooperation. It also works through history: communities with reason not to trust a public system engage with it later, less often, and with more at stake when they do.</p>" },
              { label: "Both at once", body: "<p>The combination is not addition. A person who needs an interpreter and an accommodation may fall between two processes that each assume the other handled it. Reserve in a meeting can be read as low need by an assessor and as difficulty by a program. An adjustment offered in English to a family that does not use English is not an adjustment. A fix aimed at one pattern routinely leaves the other exactly where it was.</p>" },
              { label: "Why intent is the wrong place to start", body: "<p>Asking whether anyone meant it turns a design question into a question about people's character, and once that happens the room defends itself instead of reading the evidence. Ask instead what the process produced, which step produced it, and who controls that step. Those questions can be answered, and answering them changes something.</p>" },
            ],
          },
          {
            type: "flashcards",
            heading: "Words worth keeping apart",
            cards: [
              { front: "Difference", back: "<p>Any variation between groups in a measured result. Some differences are small, expected, or driven by something the program does not control. A difference becomes worth examining when it is consistent, large enough to matter to the people inside it, and attached to a step the division controls.</p>" },
              { front: "Disparity", back: "<p>A difference in outcome that follows a line we have said we do not want results to follow: race, disability, language, income, geography. Calling something a disparity is a claim about the pattern. It is not yet a claim about the cause.</p>" },
              { front: "Ableism", back: "<p>Designs, rules and expectations built around one way of moving, thinking, communicating and working, which then treat everything else as an exception to be requested. It operates through defaults, not only through attitudes.</p>" },
              { front: "Racism, at the level of a system", back: "<p>The same mechanism operating along racial lines: defaults, rules and habits shaped by one set of conditions and applied to people whose conditions differ, producing results that follow the difference. This module examines designs and results, not anyone's motives.</p>" },
              { front: "Intersectionality", back: "<p>A way of looking, not a category to put someone in. It asks what happens where two or more patterns meet in one person's path through a system, because the combination often behaves differently from either pattern alone.</p>" },
              { front: "Minimization", back: "<p>A stage on the intercultural development continuum where sameness is emphasized and difference is treated as minor. In a public agency it sounds like fairness: identical rules, therefore fair results. It is a stage to move through, not a fault in a person, and it is never scored or recorded about anyone here.</p>" },
            ],
          },
          {
            type: "leaderMove",
            heading: "Name the person the process was built for",
            control: "You control whether the picture of the default participant stays unspoken. Writing it down takes one sentence, and it is usually the fastest way to see who a process works less well for.",
            failure: "Do not answer a question about results with a description of the rule. “The requirement is the same for everyone” is true, and it tells you nothing about what the requirement produced.",
            next: "Before your next process change is finalized, write the sentence: this step assumes a person who has… Then name one group the sentence leaves out, and what it would cost to include them.",
          },
          {
            type: "quote",
            text: "They kept telling me the rule was the same for everybody. It was. I still could not get the paper signed, because the only clinic that would see me was two counties away and the next opening was in March. The rule was fair. My year was not.",
            cite: "Composite participant perspective, illustrative",
          },
          {
            type: "knowledgeCheck",
            id: "ipe-21-1-check",
            question: "A program change requires a document that everyone must obtain the same way, within the same timeframe. Six months later, approval rates differ by race and by disability type. Which reading is best supported?",
            options: [
              { text: "The difference must come from outside the program, because the requirement itself treated everyone identically.", correct: false },
              { text: "An identical requirement can still produce different results, because what it takes to meet it is not evenly available. The requirement is one of the places the difference could have been produced, and it sits inside the division's own design.", correct: true },
              { text: "The difference shows that some groups needed the requirement explained to them more clearly.", correct: false },
            ],
            feedbackCorrect: "Yes. Identical rules meeting unequal conditions is one of the most common ways a public process produces an unequal result, and it is a place the division controls.",
            feedbackIncorrect: "Look at what a person needs in order to meet the requirement — a professional, a document, a ride, an appointment, time away from work — and ask whether those are evenly available. The rule can be identical and the result still uneven.",
          },
          {
            type: "statement",
            body: "A private reflection, for you alone: think of one process you touch. How might your role, your authority, your language or your assumptions shape what that process asks of people? Nothing you write here is collected, scored, or seen by anyone else.",
          },
        ],
      },
      {
        id: "ipe-21-2",
        number: 2,
        title: "Where the difference was produced",
        summary: "A difference visible at the end of a service path was usually created several steps earlier. Seven places to look, and how to find the one your own work controls.",
        minutes: 11,
        learning: {
          objective: "Locate where in a service path an outcome difference could have been produced — access and eligibility, assessment, navigation, crisis response, housing, work or quality reporting — and name which of those steps your own role controls.",
          takeaways: [
            "A difference reported at the end of a path was almost always produced earlier, by something ordinary: who heard about the service, what document was required, who administered the assessment and in what language, who was walked through the next step and who was handed a phone number.",
            "Assessment looks like measurement and is not. The instrument, the person administering it, the language, the interpreter, who else is in the room, and whether something is written down as a behavior, a symptom or a cultural practice all shape the result.",
            "Crisis response looks like a reaction to an emergency and is also a set of prior choices: which number is publicized, which service is funded to answer, who is dispatched, and whether an unfamiliar response to fear and pain is read as a symptom or as a threat.",
            "Quality measures reach people who are still receiving the service, still at the recorded address, and able to answer in a language the survey is printed in. A quality figure describes the people it reached; its silence is not the same as satisfaction.",
            "Most staff fully control one or two steps and influence a few more. That is enough to matter, and it is far more useful than holding an opinion about the whole system.",
          ],
          evidence: "A scenario about a steady satisfaction figure that reaches only part of a population, an accordion covering the seven places a difference can be produced, a sorting exercise that places examples at the step where they occur, and a knowledge check on what a survey figure establishes.",
          appliedNextStep: "Draw the path a person takes through one service your role touches, from first hearing it exists to the last measured outcome. Mark the single step your work actually controls, and write what you would need to know to tell whether that step works the same way for everyone.",
        },
        scenario: {
          context: "A DSD quality report carries an overall satisfaction figure for a service. It has held steady for three reporting cycles. The survey is mailed, in English and Spanish, to people currently receiving the service, and about a third of it comes back. A supervisor asks the quality team whether anything in this measure needs attention.",
          prompt: "What is the most useful answer?",
          options: [
            {
              label: "Report that satisfaction is steady and nothing needs attention, since three cycles without movement is a good sign.",
              response: "Steadiness in a figure that reaches only part of a population is not reassurance. The people most likely to have been pushed out of a service are the least likely to be in the number that measures it.",
            },
            {
              label: "Report the figure together with who it reached and who it could not — people who left the service, people whose address changed, people who read neither of the two languages, people who cannot complete a mailed form — and propose one affordable change to reach one of those groups next cycle.",
              response: "This reports the number honestly and turns its limits into a specific next step rather than a general complaint about the instrument. It also gives the supervisor something to decide.",
              recommended: true,
            },
            {
              label: "Withhold the figure until the survey has been redesigned to reach everyone.",
              response: "Waiting for an instrument that reaches everyone means reporting nothing for a long time, and silence is not more honest than a bounded number. The figure needs its boundaries stated, not its publication delayed.",
            },
          ],
        },
        transfer: {
          prompt: "Map one service path you touch.",
          options: [
            "List the steps a person passes through, from first hearing the service exists to the last measured outcome.",
            "Mark the one step your role controls completely.",
            "Name what you would need to know to tell whether that step works the same way for everyone.",
            "Name the colleague who holds the step immediately before yours, and the one who holds the step after.",
          ],
        },
        blocks: [
          {
            type: "text",
            heading: "A difference has a location",
            body: "<p>When a difference shows up at the end of a service path, the instinct is to look at the end. That is almost always the wrong place. By the time a number is reported, the difference has usually been produced several steps earlier by something entirely ordinary: who heard the service existed, which document was required, who administered the assessment and in what language, who was walked through the next step and who was handed a phone number.</p><p>It helps to treat the path as a sequence of places where a difference can be created, and then to ask which of them your own work touches. Most people control one or two steps completely and influence a few more. Knowing which is yours converts a large, discouraging topic into a small, workable one.</p><p>Two of these places deserve particular care, because the decisions inside them are rarely described as decisions at all. Assessment is one. Crisis response is the other. Both feel like responses to facts, and both are shaped by choices made well before anyone walked into the room.</p>",
          },
          {
            type: "accordion",
            heading: "Seven places a difference can be produced",
            items: [
              { title: "Access and eligibility", body: "<p>Who hears the service exists, in which language, and from a source they trust. What the application asks for, how long the window is, whether it can be finished by phone, and whether a person needs someone free during business hours to complete it. Every requirement is a filter; the only question is who it filters.</p>" },
              { title: "Assessment", body: "<p>Which instrument is used, who administers it, in what language, with which interpreter, and with whom else present. Whether a person's reserve is read as low need. Whether a family's involvement is read as support or as interference. Whether something is recorded as a behavior, a symptom or a cultural practice. A great deal of a person's future service is settled here.</p>" },
              { title: "Service navigation", body: "<p>Help is rarely distributed evenly. Some people are walked through the next step by someone who knows the system; others are given a number and a website. Who gets which often depends on who asks in a way staff recognize, who has a family member with free time, and who already knows the vocabulary.</p>" },
              { title: "Crisis response", body: "<p>What happens at nine on a Friday night is decided long before Friday: which number is publicized, which service is funded to answer it, who is dispatched, and whether an unfamiliar response to fear and pain is read as a symptom or as a threat. This is where differences in outcome become most severe and hardest to reverse.</p>" },
              { title: "Housing", body: "<p>Which settings are offered, which are described as realistic, whose family is assumed to be available, and which parts of the state have anything available at all. Offers are shaped by what a worker believes is possible for this particular person, and those beliefs are not evenly distributed.</p>" },
              { title: "Work", body: "<p>Who is offered competitive integrated employment, who is offered something smaller, and who is told to wait. Expectations about capability are one of the most consistent places where the two patterns combine, because both carry assumptions about what a person will turn out to be able to do.</p>" },
              { title: "Quality outcomes", body: "<p>Surveys and quality measures reach people who are still receiving the service, still at the recorded address, and able to answer in a language the survey is printed in. People who never entered, who left early, or who cannot answer in the form offered are simply not in the number. Report who it reached alongside what it said.</p>" },
            ],
          },
          {
            type: "sorting",
            id: "ipe-21-2-sort",
            heading: "Where was this difference produced?",
            categories: ["Access and eligibility", "Assessment and decision", "Navigation and continuity", "Outcome and quality"],
            items: [
              { text: "The application window is ten working days, and the only way to request more time is a phone line open during business hours.", category: "Access and eligibility" },
              { text: "Outreach for a new service went out through two large provider networks, neither of which operates in the northern half of the region.", category: "Access and eligibility" },
              { text: "An interpreter was arranged for the intake meeting but not for the assessment that decided the service level.", category: "Assessment and decision" },
              { text: "A person's short answers were recorded as limited need; the family later explained that he had been raised to be brief and polite with officials.", category: "Assessment and decision" },
              { text: "Two people with similar assessed needs left with noticeably different plans, and the difference tracks which worker they were assigned.", category: "Assessment and decision" },
              { text: "One family was called twice to make sure the renewal was completed; another received the same mailed notice and nothing else.", category: "Navigation and continuity" },
              { text: "People who miss a second appointment are closed out automatically, with a letter sent to the last recorded address.", category: "Navigation and continuity" },
              { text: "The satisfaction survey is mailed in two languages to people currently receiving the service.", category: "Outcome and quality" },
              { text: "The employment measure counts people who reached a job, and the region with the fewest job developers is also the region with the fewest people counted.", category: "Outcome and quality" },
            ],
          },
          {
            type: "text",
            heading: "What this module does not cover",
            body: "<p>Questions that involve Tribal Nations and American Indian communities are not settled inside this module, and this program does not author that content on its own. They belong with the Office of Indian Affairs and with the Department of Human Services offices that handle tribal matters. That is a standing deference, not a gap waiting to be filled here. The module on tribal sovereignty and state responsibilities, in this same area, describes the relationship and where those questions go.</p><p>This module also stays inside DHS and DSD public administration. It is not provider training, not a county or managed-care curriculum, and it does not describe how to deliver a service. Minnesota supports disability-services provider learning separately. What is examined here is our own side of the arrangement: the policies, requirements, contracts, reports and decisions the division makes.</p>",
          },
          {
            type: "leaderMove",
            heading: "Work the step you control",
            control: "You control the step your role owns completely: the wording of a requirement, the length of a window, the language of a notice, the instruction given to whoever administers an assessment, the question printed on a survey.",
            failure: "Do not send the whole path upward and wait for a systemwide answer. A difference produced across seven steps is repaired one step at a time, and the first step is the one you own.",
            next: "Name your step. Write what you would need to know to tell whether it works the same way for everyone. Then ask for that one piece of information.",
          },
          {
            type: "knowledgeCheck",
            id: "ipe-21-2-check",
            question: "A service's satisfaction figure has been steady for three reporting cycles. The survey is mailed, in two languages, to people currently receiving the service, and about a third is returned. What does the figure establish?",
            options: [
              { text: "That satisfaction with the service is stable across the people it serves.", correct: false },
              { text: "That among people still receiving the service, still reachable at the recorded address, able to read one of two languages and willing to return a mailed form, reported satisfaction is stable. It says nothing about people who left, never entered, or could not answer.", correct: true },
              { text: "That the survey is reliable and the service needs no further review.", correct: false },
            ],
            feedbackCorrect: "Yes. A quality figure describes the people it reached. Naming who sits outside it is part of reporting it honestly.",
            feedbackIncorrect: "Ask who could answer this survey at all. The people most likely to have been pushed out of a service are the least likely to appear in the number that measures it.",
          },
          {
            type: "statement",
            body: "A private reflection, for you alone: look at the path you just mapped. Who could be helped, burdened, excluded or misunderstood at the step your work controls? Nothing you write here is collected or seen by anyone else.",
          },
        ],
      },
      {
        id: "ipe-21-3",
        number: 3,
        title: "Reading a difference without jumping to a cause",
        summary: "A gap is a question, not an answer. Denominators, collapsed categories, uneven records, and the difference between explaining a pattern and hiding it.",
        minutes: 11,
        learning: {
          objective: "Examine a reported outcome difference well enough to say what it does and does not establish, naming at least three ways the reading could be wrong before naming any cause.",
          takeaways: [
            "The denominator decides the story. Share of the state's population, share of people likely eligible, share of people who applied, and share of applicants approved are four different questions with four different answers.",
            "Broad categories hide the communities inside them. A single figure can sit flat while two communities inside the same category move in opposite directions.",
            "Small numbers are a reason to look more carefully, across more cycles, and with more care for privacy. They are not a reason to stop asking.",
            "Adjusting for county, income or referral source can be useful and can also remove the pattern from view, because those are often results of the same history. Report both figures and say what the adjustment took out of sight.",
            "A pattern across a group is never evidence about an individual, and it is never evidence of anyone's motive. Holding that line is what makes an honest reading possible, because it removes the accusation that makes a room defend a number instead of reading it.",
          ],
          evidence: "A scenario about a request to adjust a difference away before it reaches leadership, an accordion on six ways a reading goes wrong, sorting practice separating what a number shows from what it only suggests, flashcards on denominators, and a knowledge check on adjustment.",
          appliedNextStep: "Take one number in a report you use. Write down the denominator it actually uses, one group it collapses, and one group of people who are not in it at all because they never reached the step being counted.",
        },
        scenario: {
          context: "An evaluation analyst is preparing a routine update for a DSD service measure: the share of applicants approved within the standard timeframe. It differs by about ten percentage points between two recorded groups, and has for three cycles. A program director asks the analyst to adjust the figure for county before it goes to leadership, because rural counties have fewer assessors and longer waits.",
          prompt: "What should the analyst do?",
          options: [
            {
              label: "Adjust for county as asked and report the adjusted figure, since the county effect is real and the unadjusted number would mislead leadership.",
              response: "The county effect is real, and reporting only the adjusted figure removes the pattern from view. Where people live is itself the result of decisions about where services were built and who could afford to live where. An adjustment that absorbs that history has not explained it.",
            },
            {
              label: "Report both figures, with one plain sentence saying how much county accounts for, a note that where people live is itself shaped by earlier decisions, and a short list of the steps that could produce the remaining difference.",
              response: "This keeps the difference visible, credits the real effect the director identified, and hands leadership something they can act on rather than a single number to accept or reject.",
              recommended: true,
            },
            {
              label: "Report only the unadjusted difference, on the grounds that adjusting it is a way of explaining away a disparity.",
              response: "Refusing the adjustment discards information the director correctly identified, and it invites an argument about the number instead of a conversation about the steps. The answer is both figures, clearly labeled, not one of them.",
            },
          ],
        },
        transfer: {
          prompt: "Take one measure you report or rely on regularly.",
          options: [
            "Write down the denominator it actually uses, in one sentence.",
            "Name one group the categories collapse, and say what you can and cannot see inside it.",
            "Name one group of people who are not in the number because they never reached the step being counted.",
            "Write the one question you would need answered before you would be willing to name a cause.",
          ],
        },
        blocks: [
          {
            type: "text",
            heading: "A gap is a question, not an answer",
            body: "<p>A reported difference tells you that something is happening. It does not tell you what. The distance between those two sentences is where most examinations of a disparity go wrong, and they go wrong in one of two directions: the number is treated as proof of a cause somebody already believed, or it is adjusted, qualified and explained until there is nothing left to act on.</p><p>Both moves feel rigorous. Only one of them is a reading. A reading names what the number covers, what it collapses, who is missing from it, and which of the possible explanations the division can actually check. It ends with a question sharp enough to answer, not with a verdict.</p><p>There is also a line this work does not cross. A pattern across a group is never evidence about an individual, and it is never evidence of anyone's motive. A difference in approval rates does not tell you that a particular assessor is biased, and it tells you nothing at all about the person sitting in front of you. Keeping that line visible is not a softening. It is what makes the examination possible, because it removes the accusation that makes people defend a number instead of reading it.</p>",
          },
          {
            type: "accordion",
            heading: "Six ways a reading goes wrong",
            items: [
              { title: "The denominator answers a different question", body: "<p>Share of the state's population, share of people likely eligible, share of people who applied, and share of applicants approved are four separate measures. A group can be over-represented in one and under-represented in the next. Write the denominator down before interpreting anything.</p>" },
              { title: "The categories collapse the communities inside them", body: "<p>Broad race and ethnicity categories hold communities with very different histories, languages, arrival stories and relationships with public systems. A single figure for a broad category can look flat while two communities inside it move in opposite directions. Where the numbers allow, look inside the category. Where they do not, say so in the report.</p>" },
              { title: "The numbers are too small to carry the weight", body: "<p>Small counts move a great deal on one or two cases. That is a reason to look across several cycles, to be careful about publishing anything that could identify a person, and to ask more precisely. It is not a reason to stop asking.</p>" },
              { title: "The information itself is uneven", body: "<p>Race and language are sometimes self-reported, sometimes recorded by staff observation, sometimes left blank. Disability type is often recorded to fit the program rather than the person. A difference can be produced by how a field was filled in rather than by anything that happened to anybody.</p>" },
              { title: "Adjusting removes the thing you were looking for", body: "<p>Controlling for county, income, prior contact or referral source can be genuinely useful. It can also hide the pattern, because those are frequently results of the same history. If you adjust, report both figures and say plainly what the adjustment took out of view.</p>" },
              { title: "The reading arrives with its cause already attached", body: "<p>Everyone in the room has a theory before the meeting starts. Write the competing explanations down first — including the ones that point at the division's own steps — and only then ask which of them can be checked with something you are able to obtain.</p>" },
            ],
          },
          {
            type: "sorting",
            id: "ipe-21-3-sort",
            heading: "A measure shows the approved-within-timeframe share by recorded group, across three cycles. What does it carry?",
            categories: ["What the number shows", "What the number only suggests", "What the number cannot show"],
            items: [
              { text: "That the approved share differs between two recorded groups, consistently, across all three cycles.", category: "What the number shows" },
              { text: "That the difference is wider now than in the earliest cycle available.", category: "What the number shows" },
              { text: "That having fewer assessors in a region is the reason for the difference.", category: "What the number only suggests" },
              { text: "That the assessment step is worth examining before the outreach step.", category: "What the number only suggests" },
              { text: "That the requirement for a recently signed form is part of what produced it.", category: "What the number only suggests" },
              { text: "Whether any individual assessor treated any individual applicant unfairly.", category: "What the number cannot show" },
              { text: "What a particular applicant experienced at the counter.", category: "What the number cannot show" },
              { text: "What anyone involved intended.", category: "What the number cannot show" },
              { text: "How many people never applied because someone told them informally that they would not qualify.", category: "What the number cannot show" },
            ],
          },
          {
            type: "flashcards",
            heading: "Five denominators, five different questions",
            cards: [
              { front: "Out of everyone in Minnesota", back: "<p>Compares the service's population with the state's. Useful for asking whether a service reaches the communities it is meant to reach. Poor at explaining anything about how the service treats the people already in it.</p>" },
              { front: "Out of everyone likely eligible", back: "<p>Compares who is served with who could be served. Harder to estimate, and far more informative about reach, outreach and the front door.</p>" },
              { front: "Out of everyone who applied", back: "<p>Isolates what happened after the door. Differences here point at requirements, assessment and processing rather than at outreach.</p>" },
              { front: "Out of everyone approved", back: "<p>Asks what happened next: level of service, setting, waiting time, continuity. Differences here point at decisions made after eligibility was settled.</p>" },
              { front: "Out of everyone who answered", back: "<p>The quiet denominator behind every survey figure. Report it every time, and always say who could not answer at all.</p>" },
            ],
          },
          {
            type: "leaderMove",
            heading: "Ask for the reading, not the verdict",
            control: "You control what you ask for when a difference appears: a reading with denominators, categories and missing people named, or a one-line answer about whether the number is a problem.",
            failure: "Do not ask an analyst to make a difference go away, and do not ask them to prove it is somebody's fault. Both requests produce a worse answer than the question deserved.",
            next: "The next time a difference reaches you, ask three things: what is the denominator, who is not in this number, and which of the possible explanations sits inside a step we control.",
          },
          {
            type: "knowledgeCheck",
            id: "ipe-21-3-check",
            question: "A difference in on-time approvals narrows considerably once the figures are adjusted for county. What should the report say?",
            options: [
              { text: "That the difference is explained by geography and requires no further attention.", correct: false },
              { text: "That county accounts for much of the difference, that where people live is itself shaped by earlier decisions about where services were built, and that both the adjusted and the unadjusted figures belong in the report.", correct: true },
              { text: "That the unadjusted figure was misleading and should be withdrawn.", correct: false },
            ],
            feedbackCorrect: "Yes. An adjustment that removes a pattern from view has not explained it. Reporting both figures keeps the question open and the report honest.",
            feedbackIncorrect: "Adjusting for something that is itself a result of the same history can hide exactly what you were trying to see. Report both figures, and say what the adjustment took out of view.",
          },
          {
            type: "statement",
            body: "A private reflection, for you alone: when you last saw a difference in a report, what did you assume had caused it before you read any further? Nothing you write here is collected, scored, or attached to your name.",
          },
        ],
      },
      {
        id: "ipe-21-4",
        number: 4,
        title: "Questions for examining an outcome difference",
        summary: "The practical tool: a one-page inquiry guide that turns an observed difference into an examination somebody owns, with the response agreed before the answer is known.",
        minutes: 11,
        learning: {
          objective: "Build a written inquiry guide for one real outcome difference in your own work, naming the question, the people who should shape it, the steps to examine, and what accountability would require if the answer points back at the division.",
          takeaways: [
            "Most outcome differences in a large public system are noticed long before they are examined. The missing piece is usually not willingness; it is that nobody wrote the questions down.",
            "Who is asked to help examine a difference decides what can be found. People with disabilities, families, interpreters and culturally specific organizations are co-designers and advisors in this work, paid for their time, not subjects of it.",
            "Arrange the payment route before the first invitation goes out. Setting it up takes longer than the meeting does, and an unpaid invitation is a request to subsidize the state.",
            "Write down what the division will do if the answer is inconvenient, while you still do not know the answer. A commitment made in advance survives a finding nobody wanted.",
            "Changing a requirement going forward does not reach the people already closed out under it. Accountability names them; repair reaches them.",
          ],
          evidence: "A scenario about a contract renewal where provider-level differences appear, a disparity inquiry guide you can copy into your own work, an ordered question set to take into the room, an accordion on what to do when the answer points back at us, and a knowledge check on what a finding obliges.",
          appliedNextStep: "Fill the inquiry guide in for one outcome you are responsible for. Start with the line naming who is missing from the inquiry, and ask a contracts or fiscal colleague about the payment route before the first invitation goes out.",
        },
        scenario: {
          context: "A contract manager is preparing a renewal for a large provider that supports people across several counties. Performance information attached to the renewal shows that among the people this provider supports, the share who reach competitive integrated employment differs sharply by recorded race. The provider is the only one of its size in part of the region, and the renewal is due in six weeks.",
          prompt: "What is the most responsible next step?",
          options: [
            {
              label: "Add a renewal condition requiring the provider to close the gap by the next contract period, with reporting against it.",
              response: "An obligation with no examination behind it pushes the problem down the chain. The provider can meet it by supporting people who are easier to place, which makes the reported figure improve while the actual difference gets worse. A condition may well belong in the contract; it belongs after somebody understands what produced the difference.",
            },
            {
              label: "Note the difference in the contract file and keep monitoring for another cycle, since the counts are small and there is no alternative provider in part of the region.",
              response: "Monitoring with no question attached is how a difference becomes a permanent feature. Small counts are a reason to look across more cycles and protect privacy, not a reason to wait. Having no alternative provider makes the examination more urgent, not less.",
            },
            {
              label: "Open a short joint inquiry with the provider and paid community advisors before the renewal, covering referral, assessment, expectations about capability and where job development staff are actually placed — and write down in advance what the division will do if the cause sits on our side.",
              response: "This treats the difference as a question about the whole arrangement, including the division's own referral and contracting decisions. It also settles the response before anyone knows the answer, which is what keeps a finding from being negotiated away afterward.",
              recommended: true,
            },
          ],
        },
        transfer: {
          prompt: "Which outcome in your own work would you be willing to examine this way?",
          options: [
            "Name one outcome you are responsible for where a difference has been mentioned but never examined.",
            "Write down the denominator it uses and one group its categories collapse.",
            "Name the people who should shape the inquiry, and the colleague who can confirm the payment route.",
            "Write the sentence that says what you will do if the answer points at a step you own.",
          ],
        },
        blocks: [
          {
            type: "text",
            heading: "From noticing to asking well",
            body: "<p>Most outcome differences inside a large public system are noticed long before they are examined. They appear in a quarterly report, somebody mentions them, and the conversation moves on because nobody has a way to turn an observation into work. The missing piece is rarely willingness. It is that nobody wrote the questions down.</p><p>An inquiry guide is a short document, no longer than a page, that turns one observed difference into something a group of people can actually examine. It names the outcome and the difference, the denominator and the categories, the steps where the difference could have been produced, the people who should shape the inquiry and how they are paid, what the division will do if the answer points at its own decisions, and who owns each part.</p><p>The last two lines are where inquiries usually fail. Community advisors, people with disabilities, families, interpreters and culturally specific organizations are co-designers and advisors here, not subjects, and their time is paid for. Arrange the payment route before the first invitation goes out, because it takes longer to set up than the meeting does. Then write down what happens if the answer is inconvenient, while you still do not know the answer. A commitment made in advance survives a finding nobody wanted.</p>",
          },
          {
            type: "artifact",
            kind: "tagged-document",
            label: "Practical tool",
            title: "A disparity inquiry guide for one outcome",
            summary: "One page that turns an observed difference into an examination somebody owns.",
            fields: [
              { label: "The outcome and the difference you can see", value: "On-time approvals for a waiver service. Across three cycles, the share approved within the standard timeframe for one recorded group runs roughly twelve points below the next largest group." },
              { label: "Denominator, categories and who is missing from the number", value: "Denominator is applicants, not the likely eligible population. Broad race categories; at this size we cannot look inside them. Not in the number at all: people discouraged before they applied, and people whose race field is blank." },
              { label: "The steps where the difference could have been produced", value: "The recently signed form requirement; interpreter availability at the assessment rather than at intake; which office processed the file; automatic closure after a missed appointment." },
              { label: "Who should shape the inquiry, and how they are paid", value: "Two people who went through the process, one family member, one culturally specific organization, one interpreter. Paid at the agreed advisor rate through the existing grant route; confirm with fiscal before any invitation goes out." },
              { label: "What we will do if the answer points back at us", value: "Record the finding in the program file in plain words, name an owner for the step, add a second route to meeting the requirement or change it, and contact the people whose applications were closed under it." },
              { label: "Owner, report-back date and next review point", value: "Named program manager owns the guide. Advisors and affected applicants hear what was found within one cycle of the last session. Reviewed again at the agreed point." },
            ],
            action: "Copy the six fields onto a single page, fill them in for one outcome you are responsible for, start with the line on who is missing, and settle the payment route before the first invitation goes out.",
          },
          {
            type: "list",
            heading: "Questions to take into the room",
            ordered: true,
            items: [
              "What exactly is the outcome, and for whom is it a good or a bad one? Say it in a sentence a person outside the division would understand.",
              "What is the denominator, and what would the picture look like with a different one?",
              "Which categories are we using, what do they collapse, and what are we prepared to say about the communities inside them?",
              "Who is not in this number at all, and at which step did they leave or never arrive?",
              "Which steps in the path could have produced this, and which of those does the division control?",
              "What would we expect to see if each competing explanation were true, and which of those can we actually check?",
              "Whose expertise is missing from this conversation, and what would it take for them to shape it rather than review it at the end?",
              "What does accessibility mean here beyond the legal minimum — in how the inquiry itself is run, not only in what it examines?",
              "Does the way we plan to describe this make sense to people who do not already know how DHS works?",
              "If the answer points at one of our own decisions, what will we do, and who has agreed to that in advance?",
              "If harm or exclusion has already occurred, what would accountability and repair require for the people it happened to, not only for the process going forward?",
              "Who hears what we found, in what language and format, and by when?",
            ],
          },
          {
            type: "accordion",
            heading: "If the answer points back at us",
            items: [
              { title: "Say it in the record", body: "<p>A finding that a division requirement produced a difference belongs in the program file in plain words, with a date and a named owner. Softening it there is how the same requirement survives the next review untouched.</p>" },
              { title: "Separate what is obligated from what is chosen", body: "<p>Some responses are legal obligations under civil rights and accessibility law, and they are decided by the responsible offices rather than by a program team. Others are choices a program can make immediately. Keeping the two apart prevents both paralysis and overreach.</p>" },
              { title: "Repair is about people, not only process", body: "<p>Changing a requirement going forward does not reach the people already closed out under it. Ask who they were, whether they can be contacted, and what could be offered: a reopened application, a waived step, a direct call rather than another letter.</p>" },
              { title: "Tell the advisors what happened", body: "<p>People who helped examine a difference are owed the finding and the decision, including the parts that did not go their way. A report-back that only arrives when the news is good teaches people not to take part next time.</p>" },
              { title: "Expect the defensive turn, and plan for it", body: "<p>When a finding lands, the first reaction in the room is often polarization: the number is attacked, or a person is blamed. Naming that possibility in advance, and returning to the design question rather than the motive question, is usually what keeps the work moving.</p>" },
            ],
          },
          {
            type: "leaderMove",
            heading: "Decide the response before you know the answer",
            control: "You control whether the commitment to act is written down while the finding is still unknown. Afterward, every commitment reads as a concession.",
            failure: "Do not open an inquiry you are not prepared to have answered, and do not invite paid advisors into a question whose answer you have already decided. Both cost trust you will need later.",
            next: "Before the first session, write one sentence: if this examination finds that our own step produced the difference, we will… Then have the person who can authorize it agree to that sentence.",
          },
          {
            type: "knowledgeCheck",
            id: "ipe-21-4-check",
            question: "A joint inquiry finds that a division requirement produced most of an outcome difference. The program changes the requirement for future applicants. What is still missing?",
            options: [
              { text: "Nothing further is required; the process has been corrected going forward.", correct: false },
              { text: "The people whose applications were closed under the old requirement, who are owed contact and a route back in, and the advisors who helped, who are owed the finding and the decision.", correct: true },
              { text: "A written statement of regret in the next public report.", correct: false },
            ],
            feedbackCorrect: "Yes. A forward-looking fix leaves the people already affected exactly where they were. Accountability names them, and repair reaches them.",
            feedbackIncorrect: "Ask who was already harmed by the requirement and what they are owed now, not only what the next applicant will experience.",
          },
          {
            type: "statement",
            body: "A private reflection, for you alone: take one outcome you are responsible for. How could the people most affected by it have shaped this work earlier, and what would have had to change for that to be possible? If harm or exclusion has already occurred, what would accountability and repair require? Nothing you write here is collected, scored, or seen by anyone else.",
          },
        ],
      },
    ],
  },
  jobAid: {
    title: "Race, disability and unequal outcomes",
    subtitle: "One page for examining a difference in results",
    quote: "A difference in outcomes is a question about our design before it is a fact about a group of people.",
    use: {
      purpose: "Keep the inquiry questions in view while you read a report, prepare a renewal, draft a requirement, or answer a question about a difference in results.",
      remember: [
        "Ableism and racism operate through defaults and designs, not only through attitudes. Neither needs anyone's intent to produce an unequal result.",
        "An identical rule meeting unequal conditions produces an unequal result. Describing the rule is not an answer about the result.",
        "A difference has a location: access and eligibility, assessment, navigation, crisis response, housing, work, or quality reporting.",
        "A pattern across a group is never evidence about an individual, and never evidence of anyone's motive.",
        "Name the denominator, the categories and the people missing from the number before you name a cause.",
        "Decide what you will do if the answer points at your own step, while you still do not know the answer.",
      ],
      doNext: "Fill the inquiry guide in for one outcome you are responsible for, start with the line on who is missing, and confirm the advisor payment route before the first invitation.",
    },
    sections: [
      {
        heading: "The inquiry guide, in short",
        items: [
          "The outcome in one sentence, and the difference you can actually see.",
          "The denominator, the categories it collapses, and who is not in the number at all.",
          "The steps where the difference could have been produced, and which of them we control.",
          "Who should shape the inquiry, how they are paid, and who confirms the payment route.",
          "What we will do if the answer points back at us, agreed before the answer is known.",
          "A named owner for every line, the date people hear what was found, and the next review point.",
        ],
      },
      {
        heading: "Before you name a cause",
        items: [
          "Write the denominator down first; four denominators give four different answers.",
          "Say what the categories collapse, and whether you can look inside them at this size.",
          "Check how the information was recorded: self-reported, observed by staff, or left blank.",
          "List the competing explanations, including the ones that point at our own steps.",
          "If you adjust the figure, report both versions and say what the adjustment took out of view.",
        ],
      },
      {
        heading: "Where to look first",
        items: [
          "Access and eligibility: who heard, what was required, how long the window was.",
          "Assessment: the instrument, the language, the interpreter, who else was in the room.",
          "Navigation: who was walked through the next step and who was handed a phone number.",
          "Crisis response: which number is publicized, who is dispatched, how distress is read.",
          "Housing and work: what was offered, what was called realistic, and by whom.",
          "Quality reporting: who could answer the survey, and who was never in it.",
        ],
      },
      {
        heading: "When the answer points back at us",
        items: [
          "Put the finding in the program file in plain words, with a date and a named owner.",
          "Keep legal obligations, which belong to the responsible offices, separate from choices a program can make now.",
          "Reach the people already closed out, not only the next applicant.",
          "Send the finding and the decision to the advisors who helped, including the parts that did not go their way.",
          "Expect the defensive reaction, and return the room to the design question rather than the motive question.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Policy and program staff, who write the requirements where an identical rule meets unequal conditions — a useful place to start.",
          "Quality, compliance and performance staff, who usually see a difference first and decide how it gets described — a useful place to start.",
          "Data, research and evaluation staff, who hold the denominators, the categories and the honest account of who is missing — a useful place to start.",
          "Contracts, fiscal and procurement staff, whose renewal terms and payment routes decide both what providers are asked to do and who can afford to advise us — a good place to go deeper.",
          "Executive and senior leaders, who decide whether a finding is acted on or absorbed — a useful place to start.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "History, disability, and public institutions",
          "Tribal sovereignty and state responsibilities",
          "Immigration, resettlement, and state-system navigation",
          "Trauma-responsive public administration",
          "Power, conflict, and repair",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Department of Human Services, People with disabilities", href: "https://mn.gov/dhs/people-we-serve/people-with-disabilities/", note: "The department's own description of the services, waivers and supports available to Minnesotans with disabilities, and the program structures this module refers to in general terms." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's council on disability policy, access and rights, including guidance for state agencies and a route to disability-led perspectives on how state processes actually work." },
    { title: "U.S. Department of Justice Civil Rights Division, Title VI overview", href: "https://www.justice.gov/crt/fcs/TitleVI-Overview", note: "Federal overview of Title VI, which prohibits discrimination on the basis of race, color and national origin in programs receiving federal financial assistance, including how disparate effects are treated." },
    { title: "ADA.gov, Title II of the Americans with Disabilities Act", href: "https://www.ada.gov/topics/title-ii/", note: "U.S. Department of Justice guidance on the obligations of state and local government programs, including effective communication, integration and reasonable modification of policies." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the standards on collecting population data, conducting community assessments and partnering with the communities a program serves." },
    { title: "Minnesota State Demographic Center", href: "https://mn.gov/admin/demography/", note: "Minnesota's official source for population, age, race, ethnicity, language and disability estimates, useful when checking a denominator or asking whether a group is large enough for a reported difference to carry weight." },
    { title: "Minnesota Management and Budget, impact evaluation", href: "https://mn.gov/mmb/impact-evaluation/", note: "Minnesota's state-government evaluation work, useful background on what an evaluation can and cannot establish about the effect of a program or a program change." },
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials and accessible instruction." },
  ],
};

export default pack;
