import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Internal leadership · Module 29: Leading a reflective DSD team.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-29-reflective-team",
    indexNumber: 1171,
    seriesLabel: "Intercultural Practice and Equity · Internal leadership",
    title: "Leading a Reflective DSD Team",
    subtitle: "Respectful inquiry, learning from mistakes, feedback that travels uphill and shared accountability are conditions a leader sets, not a culture that arrives. Four lessons on the small, visible moves that set them, ending with a team learning agreement you draft with your team rather than for them.",
    scope: "For internal DHS and DSD supervisors and managers, and for executive and senior leaders who want a closer look at how operating conditions get set. Useful to anyone who runs a recurring meeting, holds a supervision hour, reviews work, or signs off on a decision, including workgroup and project leads without a supervisory title. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. This module never asks you or anyone on your team to disclose a diagnosis, a belief, a background or a private experience. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota DSD examples, scenarios, sorting and flashcard practice, private reflection prompts, and a team learning agreement you can draft straight into your own team's routine",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/equity-centered-leadership.jpg",
    coverAlt: "A woman sits at the head of a conference table with a notebook.",
    introTranscript: "Most of what a team believes about whether it is safe to raise something is learned from small moments that nobody planned: who gets asked first, how long a silence lasts before someone fills it, what happens to a question that arrives four minutes before the end, and whether a mistake produces a name or a fix. Those moments are conditions, and a supervisor sets them, usually without noticing. This module looks at four of them in turn — how a question is received, how a mistake is reviewed, how feedback travels uphill, and how a team writes down the way it wants to work — and ends with a team learning agreement you can draft with your team in about thirty minutes of one meeting.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Name the conditions you already control in a recurring meeting, and change one so that raising a question costs less.",
        "Write a short account of something that went wrong that explains the conditions behind it instead of ending at a person.",
        "Build one route by which feedback about your own decisions reaches you without first passing through someone's estimate of what is safe to say.",
        "Tell an unenforceable ground rule apart from an observable routine, and rewrite one.",
        "Draft or rework a team learning agreement with your team, with access built in and a review point set before anyone leaves the room.",
      ],
      evidence: [
        "Four worked scenarios from internal division work — a notice redesign meeting, an amendment sent with the wrong effective date, a workload survey that reported success, and ground rules that no longer match how the team works — each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates a condition the division owns from a decision someone made from a judgment about a person.",
        "A team learning agreement drafted with the team and kept where the team can edit it, rather than in a supervisor's private file.",
      ],
      appliedNextStep: "Change one condition in the next meeting you run and say out loud what you changed. Then take thirty minutes of a team meeting to draft or rework your team's learning agreement together, and set the review point before anyone leaves.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in Minnesota Management and Budget statewide human resources policy affecting supervisory responsibility, respectful workplace expectations, or performance and feedback conversations",
        "A change in DHS or DSD supervision, quality review, incident review or staff engagement practice that alters how a unit is expected to examine its own work",
        "A change in federal guidance on culturally and linguistically appropriate services affecting the leadership, governance and workforce standards used in this module",
        "Feedback from supervisors, staff or paid community advisors that an example here does not match how a real unit meeting, review or feedback route actually goes",
      ],
      relatedDoor: "Formal decisions about discipline, grievances, complaints of discrimination or harassment, accommodation requests, performance ratings and personnel records belong to the responsible DHS human resources, labor relations, civil rights and legal offices; this module helps you set the conditions inside your own team, and it never decides or records a personnel matter.",
      toolkitQuestion: "What did my team learn from the way I answered the last inconvenient question, and what does that tell them about the price of the next one?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-29-1",
        number: 1,
        title: "What your first response teaches the team",
        summary: "Respectful inquiry is not a mood that settles over a unit. It is a short list of conditions a supervisor sets in every meeting, usually without noticing.",
        minutes: 10,
        learning: {
          objective: "Name the conditions you actually control in a routine meeting, and change one of them so that raising an inconvenient question costs less than staying quiet.",
          takeaways: [
            "Respectful inquiry is a set of conditions, not a climate: the order of speaking, the length of a silence, the price of a late objection, what happens to a question after it is asked, and what the notes record.",
            "Your first response to an inconvenient question sets the price of the next one. Staff read that price accurately and adjust what they bring you.",
            "Authority compresses information. The further a problem starts from your desk, the more it has been edited before it reaches you, and the more confident it has to sound to survive the trip.",
            "A team that insists everyone is treated the same is often practicing Minimization: real differences in how people experience the same process disappear from the conversation. Acceptance begins when those differences are allowed back in as information about the design.",
          ],
          evidence: "A scenario about a question that lands in the last five minutes of a unit meeting, flashcards on the five conditions, and a knowledge check on what a supervisor controls when there is no time.",
          appliedNextStep: "Pick one recurring meeting you run. Change one condition before the next one — the order of speaking, the silence you allow, or what happens to a question after it is asked — and tell the team what you changed and why.",
        },
        scenario: {
          context: "Your unit is finishing a redesign of a notice that goes to people who receive waiver services. In the last ten minutes of a staff meeting, a newer analyst says the reading level and the phone-only question line will not work for many of the people who get this notice, and that the plain-language review was dropped to hold the print date. Two senior staff glance at the clock. You are the supervisor.",
          prompt: "What do you do in the next sixty seconds?",
          options: [
            { label: "Thank her, say it is a fair point, and ask her to send you a note afterward so the group can finish the agenda.", response: "This is the most common move, and it quietly closes the door. The question leaves the room, the team learns that a late observation becomes homework for whoever raised it, and the print date still decides. If you genuinely need the time, at least say in the room what will happen to the question, by when, and with whom." },
            { label: "Stop the agenda, ask her to say more, ask the group what would have to be true for her to be wrong, and put a named owner and a date on it before anyone leaves.", response: "Two minutes buys three things. The question stays in the room. The group practices examining a claim rather than a person. And the analyst learns what raising something costs here, which decides whether she raises the next one.", recommended: true },
            { label: "Note that plain-language review belongs to communications rather than to the unit, and move on.", response: "The ownership may be accurate and the move is still wrong. Knowing who decides does not tell you whether to raise something. What the team hears is that a boundary is a good enough reason to stop thinking." },
          ],
        },
        transfer: {
          prompt: "Think of the last question that arrived in one of your meetings at an inconvenient moment. What did the room learn from what you did next?",
          options: [
            "Write down, in one sentence, what your team most likely concluded from your response",
            "Pick one condition — the order of speaking, the silence, the record — and change it before your next meeting",
            "Tell the team what you changed and why, so the change is visible rather than a private resolution",
            "Ask one person who was in that meeting what they would have needed in order to say more",
          ],
        },
        blocks: [
          { type: "text", heading: "Conditions, not climate", body: "<p>Teams are often told that psychological safety is a feeling to create. It is far more useful to treat it as a set of conditions you already control and are already setting, deliberately or by accident. Every recurring meeting has an order of speaking, a tolerance for silence, a way that a late objection gets handled, and a rule about what goes in the notes. None of those arrive from the department. A supervisor sets them.</p><p>The conditions matter most for the observations that are hardest to raise: that a notice will not work for the people who receive it, that a measure counts the wrong thing, that a decision was made before the meeting, that a process burdens one group of staff more than another. Those observations rarely arrive as finished arguments. They arrive as a half-formed sentence at the end of a long agenda, from the person with the least standing in the room.</p><p>What you do with that sentence is the whole lesson. If a question becomes homework for the person who raised it, questions stop. If it is treated as a challenge to the plan rather than information about the plan, only the confident keep speaking. If it disappears into “good point, let's take that offline,” the team learns that the meeting is for reporting and not for thinking. None of this requires anyone to be unkind. Warm, well-run meetings produce silence all the time.</p><p>This is also where a careful team settles into Minimization: the belief that because everyone is treated the same, everyone experiences the same thing. It sounds fair, and it removes exactly the differences that matter — who can read the agenda in the format it arrived in, who gets interrupted, whose files take longer, who is asked to explain themselves. Moving toward Acceptance means letting those differences back into the conversation and treating them as information about the design rather than as a complaint about the team.</p>" },
          { type: "list", heading: "What you actually control in a one-hour meeting", items: [
            "Who is asked first, and whether people are asked at all rather than left to volunteer.",
            "How long a silence is allowed to last before you fill it. Three seconds is a different meeting from one.",
            "Whether the agenda leaves room for something nobody planned, or is full by design.",
            "What happens to a question after it is asked: a named owner, a date, and one line in the notes the whole team can see.",
            "Whether materials arrive far enough ahead, as real text rather than images of text, for someone who reads slowly or uses a screen reader.",
            "Whether you state your own position first on a decision that is still open, which usually ends the discussion before it starts.",
            "What the record keeps: only the decision, or the decision plus the disagreement, the open question and the person following it.",
          ] },
          { type: "flashcards", heading: "Five conditions worth setting on purpose", cards: [
            { front: "The order of speaking", back: "<p>Volunteering favors confidence, seniority and fluency in the room's default style. Going around in order, with the item owner last, is the cheapest change available and it changes who is heard.</p>" },
            { front: "The length of a silence", back: "<p>Most people need a few seconds to turn a hunch into a sentence. A supervisor who fills every pause has decided, without meaning to, that only the fastest thinkers contribute.</p>" },
            { front: "The price of a late objection", back: "<p>Whatever you do with the question that arrives at minute fifty-six is the price list for every future question. Pay it visibly once and the next one arrives earlier, when it is cheaper to fix.</p>" },
            { front: "The fate of a question", back: "<p>A question with no owner and no date becomes a feeling that was heard. A question with both becomes work. The difference takes ten seconds to create.</p>" },
            { front: "The record", back: "<p>Notes that carry only decisions teach the team that disagreement is not real work. Notes that carry the open question, the person following it and the date teach the opposite.</p>" },
          ] },
          { type: "leaderMove", heading: "Say out loud what happens to the question", control: "You control whether a question that arrives inconveniently leaves the room with an owner and a date, or leaves the room as a private impression.", failure: "Do not say “good point, let's take that offline” and stop there. Offline has no owner, no date and no witnesses, and the team knows it.", next: "In your next meeting, take the first hard question and, before moving on, say who will look at it, by when, and where the team will see the answer." },
          { type: "quote", text: "I thought I had an open door. Then a colleague told me my team saves things for one-to-ones because the group meeting is where I defend the plan. She was right. It took someone outside my unit to say it out loud.", cite: "Composite supervisor perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-29-1-check", question: "A staff member raises a concern in the last five minutes of a meeting and you have four minutes left. Which response best protects the condition you want?", options: [
            { text: "Ask her to send it to you in writing afterward so the group can finish on time.", correct: false },
            { text: "Take ninety seconds to let her finish, say in the room who will look at it and by when, and open the next agenda with it.", correct: true },
            { text: "Note that the issue sits outside the unit's formal ownership and refer her to the responsible office.", correct: false },
          ], feedbackCorrect: "Yes. You cannot always give a question the time it deserves. You can always keep it in the room, give it an owner and a date, and let the team see that it went somewhere.", feedbackIncorrect: "Time pressure is real, but the condition at risk is not the four minutes. It is whether a late question becomes the asker's private burden or the group's shared work." },
        ],
      },
      {
        id: "ipe-29-2",
        number: 2,
        title: "Learning from a mistake without looking for someone to blame",
        summary: "A review that ends at a name makes the next problem arrive later and cost more. A review that ends at a condition changes something.",
        minutes: 11,
        learning: {
          objective: "Produce a short account of one thing that went wrong that explains the conditions that made the mistake reasonable at the time, and that names a change, an owner and a check rather than a culprit.",
          takeaways: [
            "People usually make sensible decisions inside the conditions they are given. The useful question is not why someone did it, but what made it the reasonable thing to do with the tools, information and time in front of them.",
            "Blame and accountability work against each other. Blame ends the inquiry at a name and leaves the condition in place. Accountability names the change, who owns it, and when someone will ask.",
            "A learning account has to survive being read by the person it is about. If it would not, you will not hear about the next problem early enough for it to be cheap.",
            "Near misses are the cheapest lessons available, and they only reach you if the last one did not cost somebody their standing.",
            "Speed is part of the condition. A unit that is always one deadline behind will reuse whatever is nearest, and no reminder changes that.",
          ],
          evidence: "A scenario about an amendment that went out with the wrong effective date, sorting practice that separates a condition from a decision from a judgment about a person, and a knowledge check on what belongs in a learning account.",
          appliedNextStep: "Take one thing that went wrong in the last month, including something that was caught in time, and write four lines: what happened, what made it reasonable at the time, what will change, and who will check it and when.",
        },
        scenario: {
          context: "A contract amendment went out to a set of grantees with the wrong effective date. A grantee caught it, not the division. The template had been changed two weeks earlier; the change was announced in the eleventh paragraph of a long all-staff email; the staff member who prepared the amendment started from a saved copy because the shared folder holds three files with nearly identical names and none is marked current. Your director wants to know who made the error.",
          prompt: "What do you bring back to the director?",
          options: [
            { label: "The name of the staff member, with a note that she has been reminded to use the current template.", response: "It answers the question that was asked, and it guarantees that the next error is found by someone outside the division. Three similarly named files and an announcement buried in a long email are still sitting there, waiting for the next person in a hurry." },
            { label: "A short account of the conditions — three nearly identical files, a change announced inside a long email, and no check of the effective date before an amendment leaves the division — with a named owner and a date for each fix.", response: "This is the account a director can act on. It explains why the old template was the easy one to reach, it names three changes rather than one reminder, and it gives each of them somebody who will report back.", recommended: true },
            { label: "A statement that the error was a one-off and that the team is being more careful.", response: "Careful is not a plan, and the grantee already demonstrated that the division's care was not the control that caught it. Nothing in this answer would prevent the same amendment going out again next month." },
          ],
        },
        transfer: {
          prompt: "Which recent mistake or near miss on your team was never reviewed, because it was small enough to absorb?",
          options: [
            "Write the four lines for it: what happened, what made it reasonable, what changes, who checks and when",
            "Name the condition that is still in place and would produce the same result again next month",
            "Ask the person closest to it to read your account before anyone else does, and change what they say is unfair",
            "Decide what you will do differently the next time someone tells you about a near miss",
          ],
        },
        blocks: [
          { type: "text", heading: "Two accounts of the same event", body: "<p>The first account says: an experienced staff member used an out-of-date template and an incorrect amendment reached fourteen grantees. It is accurate. It is also useless, because everything in it is finished. The person has been identified, the lesson is that people should be careful, and the only available follow-up is a reminder.</p><p>The second account says: the current template is one of three nearly identical files in a shared folder, none marked current; the change was announced in the eleventh paragraph of a long email sent during a busy week; the unit was four days from a deadline; and nothing in the sending process looks at the effective date. In those conditions, starting from a saved copy is not carelessness. It is the sensible shortcut almost anyone would take, and the error was waiting for whoever happened to be in a hurry that week.</p><p>The second account is harder to write because it declines the invitation to end at a name. It is the only one that produces work. Three similarly named files can be fixed in twenty minutes. A change announcement can be sent as its own short notice. A check of the effective date can be added to the send step. None of that requires anyone to be more careful, which is fortunate, because nobody can be reliably more careful for very long.</p><p>None of this removes accountability, and it is not a way of excusing people. Accountability moves from “who did it” to “what will be different, who owns that, and when will somebody ask.” A person's name still appears in the account. It appears as the owner of a fix, not as the cause of the problem.</p>" },
          { type: "sorting", id: "ipe-29-2-sort", heading: "Condition, decision, or judgment about a person?", categories: ["A condition the division owns", "A decision someone made", "A judgment about a person"], items: [
            { text: "Three versions of the amendment template sit in the shared folder with nearly identical names, and none is marked current.", category: "A condition the division owns" },
            { text: "The template change was announced in the eleventh paragraph of a long all-staff email.", category: "A condition the division owns" },
            { text: "Nothing in the sending process checks an effective date before an amendment leaves the division.", category: "A condition the division owns" },
            { text: "She started from a saved copy on her own drive rather than opening the shared folder.", category: "A decision someone made" },
            { text: "He sent the amendment without asking anyone for a second read.", category: "A decision someone made" },
            { text: "She is careless with detail.", category: "A judgment about a person" },
            { text: "He does not take deadlines seriously.", category: "A judgment about a person" },
          ] },
          { type: "accordion", heading: "Four questions that keep a review honest", items: [
            { title: "What made this reasonable at the time?", body: "<p>Ask it plainly and mean it. If the answer is “nothing, it was just sloppy,” you have almost certainly not found the condition yet. Look at what was nearest to hand, what the deadline was, what the last reminder competed with, and what the process made easy.</p>" },
            { title: "What did the person know, and when did they know it?", body: "<p>Hindsight makes every warning obvious. Reconstruct the information as it actually arrived: a long email, a hallway comment, a folder with three files. Judge the decision against what was visible then, not against what you know now.</p>" },
            { title: "Who else could have caught this, and what stopped them?", body: "<p>Most errors pass several people. If the second reader was optional, if the checker was the same person as the sender, or if raising a doubt would have delayed a deadline, those are conditions too, and they are usually easier to change than anything about an individual.</p>" },
            { title: "What will be different, who owns it, and when will somebody ask?", body: "<p>An account without these three is a story. With them it is work. Put the check on a real date, in a meeting that already exists, and let the team see it come back.</p>" },
          ] },
          { type: "leaderMove", heading: "Bring conditions upward, not a name", control: "You control what goes into the account that leaves your unit. When a director asks who, you can answer with what made it likely, and who owns the fix.", failure: "Do not deliver a name and a reminder. It closes the matter, it teaches the team to route the next problem around you, and it leaves the condition in place for the next person in a hurry.", next: "The next time something goes wrong, write the four lines before you write the email, and let the person closest to the work read them first." },
          { type: "statement", body: "A private reflection, kept by you and collected nowhere: think of the last mistake someone on your team told you about. Did you hear it from the person, from a colleague, or from outside the division? What does that answer tell you about what it currently costs to tell you early?" },
          { type: "knowledgeCheck", id: "ipe-29-2-check", question: "Which sentence belongs in a learning account of the amendment error?", options: [
            { text: "The staff member responsible has been reminded to check the template folder before sending.", correct: false },
            { text: "Three nearly identical templates and a change announced inside a long email made the old version the easy one to reach. The folder will be cleaned and marked, template changes will go out as their own short notice, and the effective date will be checked before an amendment leaves the division. The unit lead owns all three and reports at the next unit meeting.", correct: true },
            { text: "The error was unusual, and the team is being more careful with amendments.", correct: false },
          ], feedbackCorrect: "Yes. It explains the conditions, names three specific changes, gives them an owner, and sets a point where someone will ask.", feedbackIncorrect: "Read each option and ask what will actually be different next month. A reminder and a promise to be careful leave every condition exactly where it was." },
        ],
      },
      {
        id: "ipe-29-3",
        number: 3,
        title: "Feedback that has to travel uphill",
        summary: "What reaches a supervisor about her own decisions has already been edited. A route, a report-back and an honest measure are what make it accurate again.",
        minutes: 11,
        learning: {
          objective: "Build one route by which feedback about your own decisions reaches you without first passing through someone's estimate of what is safe to say, and report back what changed because of it.",
          takeaways: [
            "Feedback travels downhill on its own and uphill only by design. By the time an observation about your decision reaches you, it has usually been softened by the person's estimate of what saying it will cost them.",
            "Asking is not a route. A route has a moment, a form people can actually use, a named person who is not you, and a visible result.",
            "The report-back is what makes a second round possible: here is what you told me, here is what changed, here is what did not and why.",
            "An average hides whoever is carrying the uneven part of a change. If the measure cannot detect an uneven burden, a good result is not evidence that there is not one.",
            "Paid community advisors and partners are giving you feedback too. If it never reaches a decision, you have bought their time and spent their trust.",
          ],
          evidence: "A scenario about a workload survey that reported success while two staff absorbed the difference, four views of the same month, and a knowledge check on what a measure is capable of showing.",
          appliedNextStep: "Pick one decision you made in the last quarter. Build one route for feedback about it that does not run through you, use it once, and tell the team what changed and what did not.",
        },
        scenario: {
          context: "After you reorganized case-file review assignments, you sent a short survey. Twelve of fifteen staff said the change is working well. A month later, a peer mentions that the new pattern has roughly doubled the review load for the two staff who handle files that involve interpreters, because those reviews take longer and the assignment count treats every file as the same size.",
          prompt: "What does the survey result actually tell you?",
          options: [
            { label: "That the change is working for most of the team, and two people are finding it harder.", response: "This reads an averaged result as a fact about everyone. The survey was never able to show an uneven burden, because a general satisfaction question sits on top of a count that treats a two-hour review and a forty-minute review as equal. Two people are not finding it harder; the design handed them the difference." },
            { label: "That the question could not surface the problem: an overall satisfaction question over an equal-weight count will report success until someone stops coping. Change the question and change the count.", response: "This is the honest reading. It treats the measure as part of the design rather than as neutral evidence, and it fixes the thing that produced the uneven load rather than managing the reaction to it.", recommended: true },
            { label: "That you should follow up individually with the two staff so they feel heard.", response: "A private conversation is worth having, and on its own it converts a design problem into a morale problem and asks two people to absorb it quietly. Feeling heard is not the repair when the count is what is wrong." },
          ],
        },
        transfer: {
          prompt: "Which of your recent decisions has produced no critical feedback at all?",
          options: [
            "Write down who would be first to notice a problem with it, and whether they have a route to you",
            "Ask one person outside your reporting line what they are hearing about it",
            "Report back to the team on something they raised earlier, before you ask them for anything new",
            "Check whether your measure of that decision is capable of showing an uneven result",
          ],
        },
        blocks: [
          { type: "text", heading: "What has already happened to it before it reaches you", body: "<p>Information about how a decision is landing passes through people on its way up, and each of them makes a quick calculation: is this safe to say, is it worth the trouble, and will it change anything. Most observations fail at least one of those tests. What survives the trip is the version that sounds reasonable, arrives with evidence, and does not require anyone to contradict you directly. That is a small and unrepresentative sample of what is actually happening.</p><p>The effect is strongest for exactly the things this program is about: that a form assumes a household shape most families do not have, that a meeting time works for headquarters and not for anyone with a school run, that files needing an interpreter take longer and the count does not know it. These are noticed first by the people closest to the work and furthest from the decision, and they are the observations that cost the most to raise.</p><p>So a leader who wants accurate information cannot rely on being approachable. Approachability is a quality of the person; what is needed is a property of the process. A route has a moment in the calendar, a form that does not require someone to compose an argument, a named person who is not the supervisor, and a visible result. The result matters most. People give feedback a second time based on what happened to it the first time, and on nothing else.</p><p>Working with difference rather than around it is the practical form of Adaptation: you are not asking staff to agree with you, and you are not settling for a polite consensus. You are trying to see what somebody else can see from where they sit, and then to change the design accordingly.</p>" },
          { type: "tabs", heading: "One month, four seats", tabs: [
            { label: "From the supervisor's desk", body: "<p>The reassignment went smoothly. The survey came back positive, nobody has raised a concern in a unit meeting, and the backlog numbers are steady. There is no signal here that anything needs attention, which is precisely the problem: the absence of bad news is being read as good news.</p>" },
            { label: "From the analyst reviewing interpreter-supported files", body: "<p>Every one of her reviews now takes longer than the count assumes, and she has the same target as everyone else. She has said nothing, because the change was announced as a fairness improvement and objecting to it would sound like objecting to fairness. She is finishing on her own time.</p>" },
            { label: "From a paid community advisor", body: "<p>She told the division six months ago that reviews involving interpreters need more time, not the same time. The comment appears in a meeting summary and in no decision. She has begun declining meetings, and nobody in the division has connected the two.</p>" },
            { label: "From the record", body: "<p>The assignment count, the satisfaction question and the backlog report all say the change worked. All three measure at a level where the uneven part cancels out. The record is not lying; it was built without the ability to see this.</p>" },
          ] },
          { type: "list", heading: "What makes a route a route, rather than an invitation", items: [
            "A moment on the calendar, not a standing offer. “My door is open” has no moment, so it never happens.",
            "A form that fits what people can give: three written lines, a rotating note-taker, ten minutes with a peer, a question answered anonymously.",
            "A named person who is not you, for the feedback that is about you.",
            "A question narrow enough to answer honestly: not “how is it going,” but “what has this change made harder, and for whom?”",
            "A measure that can detect an uneven result, which usually means a count that reflects how long the work actually takes.",
            "A report-back with a date: what you told me, what changed, what did not and why.",
          ] },
          { type: "leaderMove", heading: "Report back before you ask again", control: "You control whether people find out what happened to what they said, and you control how long that takes.", failure: "Do not run a second round of asking when the first round produced no visible result. It teaches the team, accurately, that consultation here is a formality.", next: "Before your next request for input, spend five minutes of a meeting on the last one: what people said, what changed, what did not and the reason." },
          { type: "flashcards", heading: "Four ways feedback gets edited on the way up", cards: [
            { front: "Softening", back: "<p>“It has been a bit of an adjustment” is what “this is unworkable” becomes after two retellings. Ask for the sharper version directly, and thank the person who gives it.</p>" },
            { front: "Rounding", back: "<p>A strong objection from two people and mild approval from twelve becomes “generally positive.” Ask who disagreed and what they said, before you accept a summary.</p>" },
            { front: "Going around you", back: "<p>People take the problem to a peer, a union representative or another unit instead. If you learn things about your own decisions from outside your team, that is the finding, not the annoyance.</p>" },
            { front: "Silence read as agreement", back: "<p>No response is information about the route, not about the decision. Treat an unusually quiet round as a reason to check the route rather than as consent.</p>" },
          ] },
          { type: "quote", text: "We told them the same thing three times over a year. It turns up in every set of meeting notes and in none of the decisions. We are not short of opinions to give. We are short of reasons to keep giving them here.", cite: "Composite community advisor perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-29-3-check", question: "Your survey shows high overall satisfaction with a workload change, and a peer later reports that two staff are carrying most of the added time. What is the most accurate conclusion?", options: [
            { text: "Most of the team is satisfied, and two people need extra support.", correct: false },
            { text: "The measure could not surface an uneven burden, because a general satisfaction question sat on top of a count that treats every file as the same size. The question and the count both need to change.", correct: true },
            { text: "The peer report is second-hand and should be set aside until the two staff raise it themselves.", correct: false },
          ], feedbackCorrect: "Yes. A general question over an equal-weight count will report success right up to the point where somebody stops coping. Change what you measure, not only how you respond.", feedbackIncorrect: "Ask what the measure was capable of showing. If the design cannot detect an uneven burden, a good result is not evidence that there is not one." },
        ],
      },
      {
        id: "ipe-29-4",
        number: 4,
        title: "Writing the agreement with your team",
        summary: "A team learning agreement turns four conditions — questions, mistakes, feedback and disagreement — into routines anyone can see, use, point at and change.",
        minutes: 10,
        learning: {
          objective: "Draft or rework a team learning agreement with your team that states observable routines for questions, mistakes, feedback, disagreement and access, with a named holder and a review point.",
          takeaways: [
            "An agreement one person writes and announces is a policy. An agreement the team drafts, edits and can reopen is a tool they will actually use.",
            "Unenforceable rules quietly favor whoever is already comfortable. “Assume good intent” cannot be checked; “when something lands badly we say so in the moment, and the person who said it answers without defending” can be.",
            "Put access inside the agreement rather than beside it: materials ahead of time as real text, captions on by default, a pace that allows processing, and one open line about what a person needs to take part.",
            "Nobody has to disclose a diagnosis, a belief, a background or a private experience to be covered. An agreement that depends on disclosure has already excluded someone.",
            "An agreement with no review point becomes a poster. Put the review on the calendar in the same meeting that produces the draft.",
          ],
          evidence: "A scenario about ground rules that no longer match how a team works, a team learning agreement you can copy into your own team's routine, and a knowledge check on what makes a line usable six months later.",
          appliedNextStep: "Take thirty minutes of one team meeting to draft or rework the agreement together, name who holds the copy, and set the review point before anyone leaves the room.",
        },
        scenario: {
          context: "Your team's ground rules were written at an off-site three sessions ago and are pinned to the wall: assume good intent, be present, step up and step back, there are no bad ideas. In the last two months, two decisions were settled in side conversations before the meeting, one experienced staff member has stopped raising concerns, and a new colleague who uses a screen reader received the agenda as scanned images twice.",
          prompt: "Where do you start the rework?",
          options: [
            { label: "Re-read the rules at the next meeting and ask everyone to recommit to them.", response: "A recommitment to rules that cannot be checked changes nothing, and it puts the failure on people's sincerity. None of the four rules would have prevented a side conversation, a silence or an agenda sent as images." },
            { label: "Ask the team to rewrite each rule as something a person can observe, add how materials arrive and by when, and set a review point.", response: "This is the move. “Assume good intent” becomes what we do when something lands badly. “Step up and step back” becomes how the first ten minutes run. Access stops being an afterthought, and the review point keeps the agreement from becoming wallpaper again.", recommended: true },
            { label: "Drop the agreement, which clearly is not working, and handle expectations in individual supervision instead.", response: "This loses the shared part, which is the part that works. Supervision is private and one-directional; norms are public and apply to you as well. A team cannot point at a private conversation when the next side deal happens." },
          ],
        },
        transfer: {
          prompt: "What does your team currently have in place of an agreement?",
          options: [
            "Write down the three rules your team actually follows, including the unwritten ones",
            "Pick the one that costs someone the most, and bring it to the team as a question rather than as a change",
            "Name the date the draft will be reviewed, and put it on the calendar in the same meeting",
            "Decide which line you will hold yourself to first, and say so when you hand out the draft",
          ],
        },
        blocks: [
          { type: "text", heading: "From a poster to a working agreement", body: "<p>Most teams have something. Values on a wall, four rules from an off-site, or an unwritten understanding that everyone learned by watching. The written ones usually share a weakness: they describe attitudes rather than behaviors. “Be respectful,” “assume good intent,” “step up and step back” are impossible to check, impossible to point at without accusing a colleague of a bad character, and comfortable mainly for the people the meeting already suits.</p><p>A working agreement describes routines. It says what happens in the first ten minutes, how materials arrive and by when, what happens to a concern raised late, what gets written after a mistake, how feedback reaches the supervisor and what comes back, and who can reopen a decision. A new colleague can read it and know what to do. Anybody can say “we agreed the agenda goes out two days ahead” without implying that a colleague is careless.</p><p>How it is written matters as much as what it says. If you arrive with a finished agreement, you have written a policy and the team will treat it as one. Bring a draft, say plainly that it is a draft, and let the team rewrite it in their own words. Expect the first version to be too long; a short agreement that people follow beats a thorough one nobody remembers. Go first on the line that applies to you, and name what you are hardest to hold to.</p><p>Keep two things out of it permanently. It never requires anyone to disclose a diagnosis, a belief, a background or a private experience — what someone needs to take part is asked for openly and provided without an explanation. And it is never a record about a person. It is a description of how the team works, which the team can change whenever the work changes.</p>" },
          { type: "list", heading: "From a feeling to something you can see", items: [
            "Instead of “assume good intent”: when something lands badly we say so in the moment, and the person who said it listens first and answers without defending.",
            "Instead of “be respectful”: we argue with the decision, the evidence and the process, and we do not characterize each other's motives.",
            "Instead of “step up and step back”: the first ten minutes go around the table in order, and the person who owns the item speaks last.",
            "Instead of “be present”: the agenda and materials arrive two working days ahead as real text, and we do not read slides aloud in the meeting.",
            "Instead of “there are no bad ideas”: every question gets one line in the notes with an owner and a date before the topic closes.",
            "Instead of “we learn from our mistakes”: when something goes wrong we write four lines — what happened, what made it reasonable, what changes, who checks and when — and the person closest to it reads them first.",
          ] },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A team learning agreement", summary: "Seven lines a team can draft together in about thirty minutes, keep where everyone can edit them, and review on a date that is already on the calendar.", fields: [
            { label: "How a meeting opens and how materials arrive", value: "Agenda and materials two working days ahead as real text rather than images of text. Captions on by default. The first ten minutes go around the table in order, and the item owner speaks last." },
            { label: "What happens when someone raises a concern", value: "The concern stays in the room. Before the topic closes it gets one line in the notes, a named owner and a date. If there is no time, it opens the next agenda rather than becoming the asker's homework." },
            { label: "What happens after a mistake", value: "Four lines: what happened, what made it reasonable at the time, what changes, who checks and when. The person closest to it reads the account first. Names appear as owners of fixes, not as causes." },
            { label: "How feedback reaches the supervisor, and what comes back", value: "One route that does not run through the supervisor — a rotating note-taker, a peer, or a short written round — used at a set point. Within two weeks the team hears what changed, what did not and why." },
            { label: "How a decision is recorded and reopened", value: "The notes carry the decision, the disagreement and the open question. Anyone may ask once for a decision to be reopened, with what is new." },
            { label: "Access, and what nobody has to ask for", value: "What a person needs in order to take part is asked for openly and provided without explanation. Nobody describes a diagnosis, a belief, a background or a private experience to be covered by anything here." },
            { label: "Who wrote this, who holds it, and when it is reviewed", value: "Drafted by the whole team, held by a named person, open for anyone to edit, and reviewed at the agreed point and whenever the team changes size, membership or the kind of work it does." },
          ], action: "Copy the seven lines into a shared document, bring them to a team meeting as a draft rather than a decision, rewrite them in the team's own words, name who holds the copy, and put the review point on the calendar before anyone leaves." },
          { type: "accordion", heading: "Four conversations to have while you draft it", items: [
            { title: "Who writes it, and who can change it", body: "<p>Say at the start that the draft is disposable and the team's version is the real one. Then prove it by keeping a line you would not have written. An agreement only one person can amend is a policy with friendlier wording.</p>" },
            { title: "What we do when we disagree with a decision that is already made", body: "<p>Most teams have no answer, so disagreement goes into corridors. Write one: the decision stands, the disagreement goes in the notes, and anyone may ask once for it to be reopened if something new appears. That single line prevents a great deal of quiet resistance.</p>" },
            { title: "What access is built in, and what nobody has to ask for", body: "<p>Decide what arrives by default for everyone — materials ahead of time as real text, captions on, a pace that allows processing, a room people can reach — so that access does not depend on somebody being willing to request it in front of colleagues.</p>" },
            { title: "What happens when the agreement is broken, including by me", body: "<p>Name what anyone may say when a line is missed, in words that do not accuse: “we agreed the agenda goes out two days ahead.” Then say what you will do when it is aimed at you, and do that the first time it happens, because the first time sets the value of the whole document.</p>" },
          ] },
          { type: "leaderMove", heading: "Draft it with them, and go first", control: "You control whether the agreement arrives finished or unfinished, and whether the first line anyone tests is one that applies to you.", failure: "Do not hand out a polished agreement and ask for comments. A team reads a finished document as a decision, and you will get agreement rather than the version they would actually follow.", next: "Bring a draft with at least two lines you are unsure about, say which line you personally find hardest to hold to, and keep whatever the team rewrites." },
          { type: "knowledgeCheck", id: "ipe-29-4-check", question: "Which line in a team learning agreement can actually be used six months from now?", options: [
            { text: "We value curiosity and we assume the best of one another.", correct: false },
            { text: "When a concern is raised and there is no time for it, it goes into the notes with an owner and a date, and it opens the next agenda.", correct: true },
            { text: "Everyone is encouraged to speak up, and there are no bad questions.", correct: false },
          ], feedbackCorrect: "Yes. Someone can check whether it happened, and anyone can point at it without accusing a colleague of a bad attitude.", feedbackIncorrect: "Ask of each line: could a new colleague read it and know exactly what to do, and could anyone tell afterward whether it happened?" },
          { type: "text", heading: "A private reflection, for you alone", body: "<p>Nothing here is collected, scored or seen by anyone else. Take whichever question is useful and leave the rest.</p><p>How might my role, authority and language change what people are willing to say in a meeting I run? Who on my team is most likely to be helped by the way we work now, and who is most likely to be burdened by it? Whose expertise is missing from the way this team makes decisions, and what would it take to have it here earlier? If something on my team went wrong and somebody was harmed or excluded, what would accountability and repair actually require of me rather than of them?</p><p>One more, if it is useful: what did it cost the last person who disagreed with me in public, and how would I know?</p>" },
          { type: "statement", body: "A commitment worth writing down: “The one condition I will change before my next team meeting is… the line of the agreement I will hold myself to first is… and the person who will tell me honestly whether it stuck is…”" },
        ],
      },
    ],
  },
  jobAid: {
    title: "Leading a reflective team",
    subtitle: "One page for any supervisor, manager or senior leader who runs a meeting, holds a supervision hour or signs off on a decision",
    quote: "A team tells you the truth at the price you have set for it.",
    use: {
      purpose: "Keep the four conditions in view while you run a meeting, review something that went wrong, ask for feedback, or write down how your team intends to work.",
      remember: [
        "Respectful inquiry is a set of conditions, not a mood: the order of speaking, the length of a silence, the price of a late objection, what happens to a question, and what the notes record.",
        "Your first response to an inconvenient question sets the price of the next one, and your team prices it accurately.",
        "Blame ends an inquiry at a name and leaves the condition in place. Accountability names the change, the owner and the check.",
        "A learning account has to survive being read by the person it is about, or you will not hear about the next problem early.",
        "Feedback travels downhill on its own and uphill only by design. The report-back is what makes a second round possible.",
        "An average hides whoever is carrying the uneven part of a change. Ask about the unevenness directly, and check what your measure is able to see.",
        "Treating everyone identically is Minimization, not fairness. Acceptance begins when real differences in how people experience the same process are allowed back into the conversation.",
        "Nobody has to disclose a diagnosis, a belief, a background or a private experience to be covered by a team agreement.",
      ],
      doNext: "Change one condition in the next meeting you run, and take thirty minutes of a team meeting to draft or rework the agreement together with a review point set before anyone leaves.",
    },
    sections: [
      {
        heading: "The team learning agreement, in short",
        items: [
          "How a meeting opens and how materials arrive: two working days ahead as real text, captions on, first ten minutes in order, item owner last.",
          "What happens when someone raises a concern: it stays in the room and gets one line in the notes with an owner and a date, or it opens the next agenda.",
          "What happens after a mistake: four lines — what happened, what made it reasonable, what changes, who checks and when — read first by the person closest to it.",
          "How feedback reaches the supervisor: one route that does not run through the supervisor, used at a set point, with a report-back inside two weeks.",
          "How a decision is recorded and reopened: notes carry the decision, the disagreement and the open question; anyone may ask once to reopen it with something new.",
          "Access, and what nobody has to ask for: provided by default, requested without explanation, and never conditional on disclosing anything private.",
          "Who wrote it, who holds it, and when it is reviewed: drafted by the team, open to edit, and reviewed on a date already on the calendar.",
        ],
      },
      {
        heading: "Conditions to set on purpose",
        items: [
          "Ask people in order rather than waiting for volunteers, and speak last on any decision that is still open.",
          "Let a silence run three seconds longer than is comfortable.",
          "Give the first hard question of the meeting an owner and a date out loud, before moving on.",
          "Send materials early as real text, not as images of text, and say who to tell if something does not work.",
          "Put the disagreement and the open question in the notes, not only the decision.",
          "Say what you changed about how the meeting runs and why, so the change is visible rather than private.",
        ],
      },
      {
        heading: "After something goes wrong",
        items: [
          "Ask what made this the reasonable thing to do with the tools, information and time available.",
          "Reconstruct what the person knew and when, not what is obvious now.",
          "Ask who else could have caught it and what stopped them; that is usually a condition too.",
          "Write four lines and let the person closest to the work read them before anyone else.",
          "Send conditions and owners upward when a director asks who; a name plus a reminder closes the matter and changes nothing.",
        ],
      },
      {
        heading: "Making feedback reach you",
        items: [
          "Build a route with a moment, a usable form, a named person who is not you, and a visible result.",
          "Ask a narrow question: what has this change made harder, and for whom?",
          "Check whether your measure can detect an uneven result before you trust a good one.",
          "Report back within a set time: what you told me, what changed, what did not and why.",
          "Treat an unusually quiet round as information about the route rather than as consent.",
          "Make sure what paid advisors and partners tell you reaches an actual decision, and tell them what it changed.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Supervisors and managers, who set the conditions in every recurring meeting, supervision hour and review — this module goes deepest here, and it is a good place to start.",
          "Executive and senior leaders, who decide whether a unit's learning account reaches a director as a name or as a condition, and whether a review point survives a busy quarter.",
          "Policy, program and operations staff who lead a workgroup or a project team without a supervisory title.",
          "Quality and performance staff, whose complaint and incident reviews depend entirely on people telling them things early.",
          "Training, communications and learning-design staff, who are often the ones raising the late question in somebody else's meeting.",
          "Data, research and evaluation staff, who can show a supervisor what an average is hiding.",
          "Fiscal, contracts and grants staff, who see how a template, a deadline and a sign-off step shape the errors that follow.",
          "Administrative and support staff, who see who gets interrupted, who never receives the agenda in time, and who absorbs the rework.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "Equitable policy and procedure governance",
          "Inclusive workforce and team culture",
          "Quality, complaints, and incident learning",
          "Leading difficult dialogue",
          "Sustaining voluntary learning",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials, and instruction that does not require anyone to disclose personal experience in order to take part." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the governance and leadership standards, the workforce standards, and the standards on continuous improvement, conflict and grievance resolution used throughout this module." },
    { title: "Minnesota Management and Budget, statewide human resources policies", href: "https://mn.gov/mmb/employee-relations/laws-policies-rules/statewide-hr-policies/", note: "The statewide policies that frame a Minnesota supervisor's responsibilities, including respectful workplace expectations, performance and feedback conversations, and where formal personnel matters belong." },
    { title: "Minnesota Department of Human Rights, Your rights", href: "https://mn.gov/mdhr/yourrights/", note: "Minnesota Human Rights Act protections in employment and public services, and the boundary between team learning practice and a formal complaint of discrimination, harassment or retaliation." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's advisory council on disability policy and access, including practical guidance for state agencies on accessible meetings, materials and notices — the basis for the access lines built into the agreement." },
    { title: "ADA.gov, Title II primer for state and local governments", href: "https://www.ada.gov/resources/title-ii-primer/", note: "U.S. Department of Justice explanation of what Title II requires of state and local government programs and meetings, including effective communication, which separates a legal obligation from the optional practice in this module." },
    { title: "plainlanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Practical guidance for writing an agreement, a notice or a question people can act on, including how to write a rule that a new colleague can follow without interpretation." },
    { title: "Minnesota Department of Human Services, content and writing guidelines", href: "https://mn.gov/dhs/digital-showcase/content-guidelines/", note: "The department's own editorial guidance on first-read understanding, descriptive sentence-case headings and familiar terms, applied here to the wording of team agreements and meeting notes." },
  ],
};

export default pack;
