import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Internal leadership · Module 32: Quality, complaints, and incident learning.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-32-complaints-incident-learning",
    indexNumber: 1174,
    seriesLabel: "Intercultural Practice and Equity · Internal leadership",
    title: "Quality, Complaints and Incident Learning",
    subtitle: "Complaints, feedback, records and the stories behind them are the division’s cheapest early warning, and the easiest to waste. Four lessons on reading them as information about a system rather than a verdict on a person, ending with a short set of equity questions you can add to a review your unit already runs.",
    scope: "For internal DHS and DSD quality, compliance and performance staff, and for data, research and evaluation staff, contracts, fiscal and procurement staff, supervisors and managers, and executive and senior leaders who want a closer look. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. This module never asks you to disclose a diagnosis, a belief, a background or a private experience. It is not a reporting, investigation, licensing, appeal or discipline procedure; those belong to the responsible offices and run on their own authority. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota DSD examples, scenarios, sorting and flashcard practice, private reflection prompts, and a short set of equity questions you can add straight into a review your unit already holds",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/outcomes-not-intentions.jpg",
    coverAlt: "A woman reviews printed charts at a desk.",
    introTranscript: "A division learns about its own design in three ways: from what people complain about, from what goes wrong, and from what nobody says. The first two arrive as records and get reviewed. The third is usually invisible, and it is often the largest of the three. This module looks at what a complaint count actually measures, how to write a review that ends at a condition instead of at a person’s name, how to read records and narratives together without letting an average hide the uneven part, and how to add three or four equity questions to a review your unit already runs. It ends with the questions themselves, written so you can put them on an agenda that already exists.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Explain what a complaint or feedback count measures about the route people had to use, and treat a quiet channel as a finding rather than a result.",
        "Write a review account that ends at a condition the division can change, with an owner, a date and a check, instead of at the person closest to the error.",
        "Read counts and narratives together, name what the record cannot see, and disaggregate before trusting an overall rate.",
        "Tell an equity question that changes a review apart from one that only adds a paragraph to it.",
        "Add a short set of equity questions to a review your unit already runs, with the agenda item each one attaches to, who answers, and when the addition itself is checked.",
      ],
      evidence: [
        "Four worked scenarios from internal division work — a regional drop in complaint volume, a notice released with the wrong effective date, a year of records where resolution time splits by who filed, and a standing contract performance review with no spare meeting time — each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates what a count can show, what only a narrative can show, and what the record cannot see at all.",
        "A short set of equity questions attached to items on an existing agenda, with an owner for each answer and a date when the addition is reviewed.",
      ],
      appliedNextStep: "Take one review your unit already holds. Attach one question to each existing agenda item, name who answers it and where the answer is recorded, and set the date when you will check whether the questions changed a decision or only lengthened the minutes.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in Minnesota Department of Human Services complaint, grievance, appeal or incident review practice, or in the quality assurance expectations for the programs the division oversees",
        "A change in federal guidance on culturally and linguistically appropriate services affecting the standards on conflict and grievance resolution, community assessment and continuous improvement used in this module",
        "A change in state or federal language access or accessible communication requirements that alters how a person can make a complaint, or feedback from paid community advisors that a complaint route described here does not match the one people actually meet",
      ],
      relatedDoor: "Reports of maltreatment, licensing actions and investigations, appeals and fair hearings, complaints of discrimination, and personnel discipline belong to the responsible DHS offices for inspection and licensing, appeals, human resources, and civil rights and legal counsel; this module decides none of those matters and takes up only what the division should learn once each of those processes has done its own work.",
      toolkitQuestion: "Whose complaint never reached us, and what in our own process decided that?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-32-1",
        number: 1,
        title: "What a complaint count actually measures",
        summary: "Before a complaint is information about a service, it is information about the route a person had to get through to make it. Falling volume is not, by itself, good news.",
        minutes: 10,
        learning: {
          objective: "Explain what a complaint or feedback count measures about access to the route itself, and name at least two reasons a quiet channel in your program area may be a finding rather than a result.",
          takeaways: [
            "A complaint count is first a count of successful complaints. It measures who knew the route existed, in a language and format they could use, who believed it was safe to use, and who had the time and standing to finish it.",
            "Falling volume is ambiguous on its own. It can mean a repaired service, a closed route, an exhausted group of people, or a change in who is willing to put their name on something.",
            "Most of what a division needs to hear never arrives as a complaint. It arrives as a question to a county worker, a remark to a paid community advisor, a pattern in a call queue, a disenrollment, or silence.",
            "A unit that says “we treat every complaint exactly the same” is often working in Minimization: identical handling of unequal access produces an unequal result and calls it fairness. Acceptance begins when the differences in who can complain are allowed back in as information about the design.",
          ],
          evidence: "A scenario about a regional drop in complaint volume, flashcards on what a count can and cannot see, and a knowledge check on how to read a quiet channel.",
          appliedNextStep: "Take one feedback or complaint route your area depends on and write down the four things a person must have before their words reach you: knowing it exists, a usable language and format, a belief that using it is safe, and the time and standing to finish it. Mark the one you have never actually checked.",
        },
        scenario: {
          context: "You are in the division’s quarterly quality review. Complaints about a waiver program in one region are down by nearly half over two quarters, and the region’s manager presents that as evidence that a corrective plan worked. In the same period, three other things happened in that region: the question line was replaced by a web form, the county contact who used to walk people through the form retired and was not replaced, and the plain-language version of the complaint notice was dropped from the last mailing to hold a print date.",
          prompt: "What do you say next in the review?",
          options: [
            { label: "Accept the finding, record the corrective plan as effective, and move to the next agenda item; the numbers are the numbers.", response: "Three parts of the route changed in the same period as the volume. A count that depends on the route cannot tell you, on its own, anything about the service behind it. Recording this as a success also retires the corrective plan, which means nobody looks again." },
            { label: "Say plainly that the volume fell at the same time the route changed, and ask for one thing before the finding stands: a description of what a person now has to do to complain, and whether anyone has tried it end to end.", response: "This is the move. It does not accuse the region of anything, it does not require new data, and it separates two questions that had been merged: did the service improve, and did the route narrow. Walking the route yourself usually takes under an hour and answers the second one.", recommended: true },
            { label: "Ask the region to survey people who received services during the period to confirm that satisfaction improved.", response: "The instinct is right and the method inherits the problem. A survey reaches people through the same channels, in the same formats, that the complaint route just lost — and it asks people who already tried to tell you something to tell you again, this time on your schedule." },
          ],
        },
        transfer: {
          prompt: "Think of a feedback or complaint route your own work depends on. What would a person have to get past before their words reached you?",
          options: [
            "Write the route as a list of steps from the person’s side, not from the file’s side, and count the steps",
            "Name the format and the languages the route is actually available in, and check when that was last true",
            "Identify who in your program area would have to complain about a colleague, a county, or a provider they still depend on",
            "Ask one paid community advisor what people tell them that never reaches the division",
          ],
        },
        blocks: [
          { type: "text", heading: "A count of complaints is a count of successful complaints", body: "<p>Quality reviews treat complaint volume as a signal about a service. It is that, eventually. First it is a signal about a route. Every recorded complaint is the end of a short obstacle course: the person knew there was somewhere to complain, found it, could read or hear it in a language and format that worked, believed that using it would not cost them their services or their standing, had the time and energy left after everything else, and finished it. Anyone stopped at any point leaves no record at all.</p><p>This matters most for the people the division most needs to hear from. A person who uses a communication device and is given a phone number. A parent whose written Somali or Hmong is stronger than their written English, reading an English form. A person whose county worker is also the person they would be complaining about. A person who has complained twice already and watched nothing change. None of them appear in the count, and none of them appear as a zero either. They are simply absent, and absence reads on a chart exactly like satisfaction.</p><p>So when volume moves, ask about the route before you ask about the service. Did a phone line become a web form? Did a plain-language version get dropped to hold a deadline? Did a trusted person leave? Did an advocacy organization lose the grant that paid the staff member who used to help people file? Each of those moves the number without touching the thing you think you are measuring.</p><p>The same logic applies in reverse. A sudden rise in complaints is often a route that finally works — a new language line, a form that a screen reader can get through, a county that started telling people the route exists. Reading that rise as declining quality punishes the exact change you wanted.</p>" },
          { type: "list", heading: "What a person needs before a complaint ever reaches you", items: [
            "Knowledge that a route exists, from a source they already trust, not buried on page nine of a notice.",
            "A language and a format they can use: not only translation, but plain wording, a form that works with a screen reader, an option that is not a phone call, and an option that is not a web form.",
            "A belief that using it is safe: that services, hours, a placement or a relationship with a worker will not quietly get worse afterward.",
            "Somewhere to complain that is not the person or office being complained about, or at least a second route that is not.",
            "Time, energy and standing — which is why complaints cluster among people who have a paid advocate, a family member with flexible hours, or prior experience with government processes.",
            "A reason to believe it matters: a previous complaint that produced a visible answer, or someone who told them what happened last time.",
          ] },
          { type: "flashcards", heading: "What the number can and cannot see", cards: [
            { front: "Volume fell", back: "<p>Four ordinary explanations: the problem was fixed, the route narrowed, the people most affected gave up, or the people who used to help them file are gone. The number cannot tell you which. Something else has to.</p>" },
            { front: "Volume rose", back: "<p>Often the route improved. A new language line, an accessible form, a county that started naming the route out loud. Treating a rise as falling quality punishes the improvement.</p>" },
            { front: "Volume is flat", back: "<p>Flat is the least informative result of the three, and the easiest to report. Split it before you trust it: by region, program, language, how the complaint arrived and who filed it.</p>" },
            { front: "A channel with almost nothing in it", back: "<p>A finding, not a result. Either nothing is wrong in that area, or the channel does not work. You can tell the two apart in an afternoon by trying to use it.</p>" },
            { front: "Complaints filed by someone else", back: "<p>When most complaints in an area arrive through a family member, a provider or an advocate, the direct route is not reaching the person. That is worth a line in the report every time.</p>" },
          ] },
          { type: "leaderMove", heading: "Ask what changed in the route before you credit the result", control: "You control whether a movement in complaint volume is reported as a finding about a service, or as a finding about a service and a route together.", failure: "Do not close a corrective plan on falling volume alone. Once it is closed, the number becomes the record, and nobody looks at the route again until something serious arrives from somewhere else.", next: "In the next review where a count has moved, ask one question before the finding is recorded: what changed in how a person reaches us, and has anyone tried it since?" },
          { type: "quote", text: "We stopped telling families to use the complaint form. It went to the same office, it took eleven weeks, and the answer was always that the provider was in compliance. Now they tell us instead, and you never hear it.", cite: "Composite community advocate perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-32-1-check", question: "A program area records almost no complaints from people who use communication devices or interpreters. Which reading is best supported?", options: [
            { text: "Service in that area is working well for those groups, and the resources should go where complaints are higher.", correct: false },
            { text: "The near-absence is a finding about the route until someone checks it: the fastest test is to try to make a complaint the way those people would have to.", correct: true },
            { text: "The sample is too small to interpret, so the area should be left out of the summary until more records accumulate.", correct: false },
          ], feedbackCorrect: "Yes. A silent channel and a working service look identical on a chart. Only trying the route tells them apart, and it is usually a short piece of work.", feedbackIncorrect: "Ask what a person in that group would have to do to appear in this data at all. If you cannot describe the steps, the absence is about the route, not about the service." },
        ],
      },
      {
        id: "ipe-32-2",
        number: 2,
        title: "Reviewing what went wrong without ending at a name",
        summary: "A review that ends at the person closest to the error closes fast and changes nothing. A review that ends at a condition costs a little more attention and holds.",
        minutes: 11,
        learning: {
          objective: "Write a review account of something that went wrong that names the conditions behind it, the change, the owner and the check, rather than ending at the person closest to the error.",
          takeaways: [
            "The person closest to an error is usually the last condition in a long line, and by far the easiest one to name. Naming them ends the review and leaves every earlier condition exactly where it was.",
            "Blame and accountability are different products. Blame produces a name and a reminder to be careful. Accountability produces a change, an owner, a date, and a check that someone can look at afterward.",
            "The useful question is what made this the reasonable thing to do with the information, tools and time available at that moment. If the honest answer is “nothing,” you have not found the conditions yet.",
            "Formal processes — reports of maltreatment, licensing, appeals, complaints of discrimination, discipline — run on their own authority and their own schedule. A learning review neither replaces them nor waits for them to finish before repairing a condition it already understands.",
            "When a review turns into two camps, the region against the central office or the unit against the contractor, it has slipped into Polarization and the condition has stopped being examined. Bringing it back means asking both sides what they could see from where they were standing.",
          ],
          evidence: "A scenario about a notice released with the wrong effective date, tabs showing the same event written four ways, an accordion on where a learning review stops and a formal process begins, and a knowledge check on what makes a review line usable.",
          appliedNextStep: "Take the last thing that went wrong in your area and rewrite the account in four lines: what happened, what made it reasonable at the time, what changes, and who checks it and when. Let the person closest to the work read it before anyone above you does.",
        },
        scenario: {
          context: "A benefit notice for a group of people receiving disability services went out with an effective date three weeks earlier than intended. Roughly a hundred households called; a few had already canceled a service they thought was ending. The template carries a default date that must be overwritten by hand, the print deadline had moved up by two days, there is no second reader for date fields, and there is no way to test a notice against a small sample before the full run. A director asks the quality unit for a short account by the end of the week and wants to know who sent it.",
          prompt: "What does the quality unit send the director?",
          options: [
            { label: "The name of the analyst who released the mailing, with a note that coaching has been provided and the matter is closed.", response: "This is the fastest account to write and the most expensive one to have written. It answers the director’s question, it closes the file, and it leaves a default date field, a moved deadline, a missing second reader and an untestable print run all in place for the next notice." },
            { label: "Four lines: what happened, what made it reasonable at the moment, what changes with an owner and a date, and how the households affected are being told — with the name available if the director still wants it, and a note on where the formal processes sit.", response: "This gives the director more than was asked for and answers the original question too. Conditions are named, somebody owns each change, there is a date to check, and the people affected appear in the account rather than only in the count.", recommended: true },
            { label: "Hold the account until the formal review of the mailing has concluded, so that the two do not contradict each other.", response: "Understandable, and it costs the division weeks. A learning review and a formal process answer different questions and can run at the same time. Waiting also means the template still has a default date field during the next print run." },
          ],
        },
        transfer: {
          prompt: "Think about the last review in your area that ended with a person’s name. What was still true about the process the following week?",
          options: [
            "Write the same account again, ending at a condition rather than at a person, and see how much longer it takes",
            "Name one condition from that event that is still in place, and who could change it",
            "Check whether the people affected were ever told what happened, in a form they could use",
            "Ask who else could have caught it, and what stopped them — that answer is usually a condition too",
          ],
        },
        blocks: [
          { type: "text", heading: "Where a review stops is a choice, and it is made early", body: "<p>Every review of something that went wrong could stop at several different points. It could stop at the person who pressed the button. It could stop at the supervisor who approved the run. It could stop at the template, the deadline, the missing second reader, the absence of any way to test. Each of those is a true account of the same event. Only some of them change anything.</p><p>Reviews stop at a person for a reason that has nothing to do with anyone’s intent. A name is a complete answer. It fits in a sentence, it satisfies the request, it closes the file, and it is the cheapest possible finding. A condition is an incomplete answer that creates work: somebody has to own it, somebody has to change it, and somebody has to check whether the change held. Under time pressure, the cheap answer wins unless a unit has decided in advance that it will not.</p><p>The test that keeps a review honest is reconstruction. Ask what this person could see at the moment they acted — what the screen showed, what the deadline was, what they had been told, what had happened the last forty times they did the same thing. Then ask what made this the reasonable action given that. There is almost always an answer, and the answer is the condition. If you cannot find one, you are still reasoning from what is obvious now rather than from what was available then.</p><p>None of this makes anyone unaccountable. Accountability is the part that produces a change with a name attached to the change, a date, and a check. Blame produces a name attached to the mistake and a reminder to be careful. One of those is still true in six months.</p>" },
          { type: "tabs", heading: "The same notice, written four ways", tabs: [
            { label: "A blame account", body: "<p>“The analyst failed to update the effective date before releasing the mailing. Coaching has been provided.” True, complete, closed. Every condition survives it, and the next analyst inherits all of them plus the knowledge that the cost of an error here is personal.</p>" },
            { label: "A process account", body: "<p>“The notice release procedure was not followed.” Slightly better, and still a dead end. It names a rule rather than a design, and it invites a longer procedure as the fix — which is the most common way a division adds work without reducing error.</p>" },
            { label: "A condition account", body: "<p>“The template carries a default effective date that must be overwritten by hand; the print deadline moved up two days; there is no second reader for date fields; there is no way to test a run against a sample. Any one of these alone is survivable. Together they make this error likely rather than unlucky.” Now there are four things to change and four people who could own one.</p>" },
            { label: "A repair account", body: "<p>“About a hundred households were told their services were ending three weeks early. Some acted on it. Correction letters went out in plain language and in the languages of the original mailing; the call line has a script; the households that canceled a service are being contacted directly.” Conditions explain the error. This is the part that addresses the harm, and it is the part most often missing entirely.</p>" },
          ] },
          { type: "accordion", heading: "Where a learning review stops and a formal process begins", items: [
            { title: "Reports of maltreatment", body: "<p>If anything in a review suggests maltreatment of a vulnerable adult or a child, the reporting obligation is immediate, it belongs to the person who learned it, and it does not wait for a review to reach a conclusion. The responsible DHS office for investigation takes it from there. A learning review never substitutes for that report and never delays it.</p>" },
            { title: "Licensing and contract enforcement", body: "<p>Findings about a licensed program or a contracted provider belong to the offices that hold the license and the contract. Your review can identify a condition the division owns — a template, a deadline, a payment rule, an oversight gap — and it should. It cannot decide a licensing action, and it should not be written as though it might.</p>" },
            { title: "Appeals and fair hearings", body: "<p>A person disputing a decision about their own services has a formal route with legal timelines. That route is theirs and it runs independently. What a quality unit can learn from a pattern of appeals — which notices are disputed, in which regions, in which languages — is useful and is a different piece of work.</p>" },
            { title: "Complaints of discrimination and personnel matters", body: "<p>Complaints of discrimination, harassment or retaliation, and any question of discipline, belong to the responsible human resources, civil rights and legal offices. A learning review that starts drifting toward whether someone should be disciplined has left its lane; hand that part over and keep working on the conditions.</p>" },
          ] },
          { type: "leaderMove", heading: "Send conditions upward when a director asks who", control: "You control what the account says, and you can answer a narrow question with a fuller answer without refusing it.", failure: "Do not send only a name, and do not withhold one either. A name alone closes the matter. A refusal makes the review look like protection, and the next request comes with less patience.", next: "The next time a senior leader asks who, send four lines — what happened, what made it reasonable, what changes with an owner and a date, and what is being done for the people affected — and note that the name is available." },
          { type: "knowledgeCheck", id: "ipe-32-2-check", question: "Which finding from an incident review can still be acted on six months from now?", options: [
            { text: "Staff will take additional care when entering effective dates on outgoing notices.", correct: false },
            { text: "The notice template’s default date field is removed and date changes require a second reader; the communications lead owns both, and the quality unit checks the next two print runs.", correct: true },
            { text: "The unit will review its notice procedures and reinforce expectations with the team.", correct: false },
            { text: "The analyst responsible has received coaching and the matter is closed.", correct: false },
          ], feedbackCorrect: "Yes. There is a specific change, a named owner and a check somebody can actually perform later.", feedbackIncorrect: "Ask of each finding: what exactly is different afterward, who made it different, and how would anyone know in six months? Care, reinforcement and coaching leave nothing to check." },
          { type: "statement", body: "A review that ends at a name answers the question that was asked. A review that ends at a condition answers the question that matters. Both take the same afternoon." },
        ],
      },
      {
        id: "ipe-32-3",
        number: 3,
        title: "Reading the pattern: records and narratives together",
        summary: "Counts tell you how often. Narratives tell you how. Neither tells you who is carrying the uneven part unless you cut the data and ask what the fields never collected.",
        minutes: 11,
        learning: {
          objective: "Examine a set of complaint or incident records, name at least two things the record cannot see, and identify one group whose experience the current fields would never reveal.",
          takeaways: [
            "Counts tell you how often something happens. Narratives tell you how it happens and what it cost. An overall average tells you neither, and it hides whoever is carrying the uneven part by design.",
            "A record can only report what its fields ask. If nothing asks whether the complaint came through an interpreter, arrived from a family member, or was the person’s third attempt, those facts leave no trace and cannot appear in any pattern you build later.",
            "A small number is not the absence of a pattern. When a group is small in the records, two or three narratives plus what paid community advisors already report is often the best evidence available; the honest move is to say the number is small and act on the pattern, not to wait for it to grow.",
            "Cuts that usually cost nothing and often find the barrier: by region, by program, by language and communication method, by how the complaint arrived, by who filed it, and by whether it was a repeat.",
            "Narratives are evidence, not color. Two accounts that describe the same obstacle in different words are a finding; a well-chosen quotation added to an otherwise unchanged report is decoration.",
          ],
          evidence: "A scenario about resolution times that split by who filed the complaint, sorting practice separating counts, narratives and blind spots, and a knowledge check on reading a small group in the data.",
          appliedNextStep: "Pull one set of records your area already keeps and make three cuts you have never made: by language or communication method, by who filed, and by whether it was a repeat. Then list two things the fields could not have told you either way.",
        },
        scenario: {
          context: "Your evaluation team is asked to summarize a full cycle of complaint records for a home and community-based services program area. Overall resolution times look steady and unremarkable. When you split the records by how the complaint arrived, complaints filed by a family member or a paid advocate are resolved in roughly half the time of complaints filed by the person receiving services. There are fewer than twenty records in the second group. Nothing in the intake fields records whether an interpreter was involved. Your director wants one page by Monday.",
          prompt: "What goes on the page?",
          options: [
            { label: "The overall resolution time, with the split noted as an observation for a future review, since fewer than twenty records is too small a group to support a conclusion.", response: "This is the cautious-sounding choice and it is the one that loses the finding. “Noted for a future review” has no owner and no date. Meanwhile the difference you found is exactly the difference the overall average was built to hide." },
            { label: "The split, stated with the number of records shown plainly, what the fields could not see, what you would ask paid community advisors, and one change to the intake fields so the next cycle can answer the question properly.", response: "This is honest about the size of the group and still useful. It gives the director a finding, the limits of the finding, a way to test it with people who already know the answer, and a small fix that makes the next cycle better. It is also a page, not a project.", recommended: true },
            { label: "Run a test of statistical significance on the difference and report it only if the result clears the usual threshold.", response: "A reasonable instinct applied in the wrong place. With a group this small, a test will almost certainly fail to reach a threshold, and the failure will be read as evidence that there is no difference. That is not what it would mean, and the reading will stick." },
          ],
        },
        transfer: {
          prompt: "Think about a set of records your work relies on. What can it not see, and who disappears because of that?",
          options: [
            "List the fields the intake form actually collects, and then list three facts about a person’s experience that none of them capture",
            "Make one cut you have never made and see whether the overall rate survives it",
            "Find two narratives that describe the same obstacle in different words and write the obstacle down as a finding",
            "Ask a paid community advisor what they would expect this data to show, then compare",
            "Propose one new field, and be specific about the decision it would let someone make",
          ],
        },
        blocks: [
          { type: "text", heading: "An average is a decision about what you are willing not to see", body: "<p>An overall rate is a summary, and every summary is a choice about which differences stop mattering. A steady average resolution time can sit on top of two very different experiences: one group whose complaints are handled in a fortnight because a paid advocate follows them, and another whose complaints take two months because nobody is chasing them and the first letter went out in a language they do not read. The average is accurate. It is also the single number least likely to lead anyone to do anything.</p><p>This is where a quality unit most often settles into Minimization without noticing. Every complaint goes into the same queue, is handled by the same procedure, and is measured by the same clock. That sounds fair and it is the definition of identical treatment, which is not the same thing. Identical treatment of people with different access to the process produces different results, and then reports those results as one number. Moving toward Acceptance is not complicated here: cut the data and look.</p><p>The second half of the work is what the record cannot see. A complaint record reports only what its fields asked for. If nothing asks whether an interpreter was involved, whether this was the person’s second or third attempt, whether the complaint was about the same worker who would receive it, or whether the person had already stopped using the service by the time anyone called back, then those facts exist nowhere in the file. They are not zeros. They are invisible, and no amount of analysis recovers them.</p><p>Which is why narratives belong in the same piece of work as the counts, and why what paid advisors and community organizations tell you is evidence rather than anecdote. Two accounts describing the same obstacle in different words is a finding about a design. The count tells you how often. The narrative tells you what it was like and where it broke. You need both on the page.</p>" },
          { type: "sorting", id: "ipe-32-3-sort", heading: "What can this tell you?", categories: ["What the count can show", "What only a narrative can show", "What the record cannot see at all"], items: [
            { text: "Complaints in this program area rose by a third after the new notice went out.", category: "What the count can show" },
            { text: "Resolution takes twice as long when the person files for themselves rather than through an advocate.", category: "What the count can show" },
            { text: "The caller was asked to repeat the whole account three times to three different people before anything was written down.", category: "What only a narrative can show" },
            { text: "The person had already canceled the service by the time the first call back arrived, so the resolution meant nothing.", category: "What only a narrative can show" },
            { text: "Whether the complaint was made through an interpreter, when the form has no field for it.", category: "What the record cannot see at all" },
            { text: "The people who started the form, reached the section requiring a case number, and stopped.", category: "What the record cannot see at all" },
            { text: "Six of the nine complaints in one region name the same step in the renewal process.", category: "What the count can show" },
            { text: "The family decided not to complain again because the last answer arrived eleven weeks later in a letter they could not read.", category: "What only a narrative can show" },
          ] },
          { type: "flashcards", heading: "Cuts worth making before you trust a rate", cards: [
            { front: "By who filed it", back: "<p>Self, family member, paid advocate, provider, county staff. A large gap between self-filed and advocate-filed complaints is one of the clearest access findings available, and it takes one cut to see.</p>" },
            { front: "By language and communication method", back: "<p>Not only the language of the complaint but the method: phone, web form, paper, in person, through an interpreter, through a communication device. This is usually where a route turns out to be theoretical.</p>" },
            { front: "By region and by program", back: "<p>Two regions running the same program with very different volumes are telling you about two different routes, two different local relationships, or two different levels of trust — rarely about two different levels of quality.</p>" },
            { front: "By repeat", back: "<p>A second or third complaint about the same matter is a different event from a first one. If the records cannot tell them apart, every repeat is being counted as fresh evidence that people are being heard.</p>" },
            { front: "By what happened next", back: "<p>Resolved, withdrawn, no response, service ended before resolution. “Withdrawn” and “no contact” often hold the most important cases, and they are the two categories least likely to be read.</p>" },
          ] },
          { type: "list", heading: "Questions to ask of any set of records before you summarize it", items: [
            "What did the fields ask for, and what did they therefore make impossible to find?",
            "Who had to get through a route in order to appear here at all?",
            "Which categories are small, and what do the narratives in them say?",
            "What do the withdrawn, unanswered and abandoned records have in common?",
            "What did people who are not in this data tell paid advisors during the same period?",
            "What would have to be added to the form so that the next cycle can answer the question I could not answer this time?",
          ] },
          { type: "leaderMove", heading: "Say the number is small, and act on it anyway", control: "You control whether a finding from a small group is reported with its limits or dropped for lack of size.", failure: "Do not write “too few records to draw conclusions” and stop. That sentence reads as rigour and functions as a decision to ignore the group least able to reach you in the first place.", next: "Report the small finding with the count stated plainly, add what the narratives and paid advisors say, and propose one field change so the next cycle can answer it properly." },
          { type: "knowledgeCheck", id: "ipe-32-3-check", question: "A review finds that complaints from one program area are resolved much faster when filed by an advocate than when filed by the person themselves, across fewer than twenty self-filed records. What is the most useful next step?", options: [
            { text: "Set the finding aside until enough self-filed records accumulate to support a firm conclusion.", correct: false },
            { text: "Report the difference with the number of records stated, read the narratives in the smaller group, check it against what paid community advisors already report, and change the intake fields so the next cycle can answer it.", correct: true },
            { text: "Report the overall resolution time, which is the only figure the sample supports.", correct: false },
            { text: "Ask advocates to file on behalf of more people so that resolution times improve overall.", correct: false },
          ], feedbackCorrect: "Yes. State the limit, use the evidence you have, and fix the instrument so the next cycle is better. Waiting for the group to grow is a decision, not a neutral position.", feedbackIncorrect: "A small group is a reason to be careful about how strongly you state a finding. It is not a reason to drop the finding, and the smallest groups are usually the ones with the hardest route to you." },
        ],
      },
      {
        id: "ipe-32-4",
        number: 4,
        title: "Adding equity questions to a review you already run",
        summary: "A new equity process competes for time it will not get. Three or four questions attached to items already on the agenda change decisions that are already being made.",
        minutes: 12,
        learning: {
          objective: "Add a short set of equity questions to a review your unit already runs, naming the agenda item each question attaches to, who answers it, where the answer is recorded, and when the addition itself is checked.",
          takeaways: [
            "A question changes a review only if it has a place in the agenda, somebody who has to answer it, and a record of the answer. A question with none of those becomes a paragraph in a charter.",
            "Adding to a review that already happens beats building a new one. The meeting exists, the people attend, the decisions are already being made there, and nobody has to defend a new process to a leadership team.",
            "Three or four questions is the working limit. A list of twelve is read carefully once and skipped from then on.",
            "The most useful equity question in a review is usually about who is missing from the record rather than about who is in it.",
            "Changing how a review is run, rather than adding a statement about equity to its cover page, is what Adaptation looks like in ordinary operations. The review still does its original job; it just sees more while doing it.",
            "Build one answer into the questions: “we do not know” is a legitimate answer that must produce an owner and a date, or the question will quietly stop being asked.",
          ],
          evidence: "A scenario about a standing contract performance review with no spare meeting time, a practical set of four questions attached to existing agenda items, an accordion explaining why each question earns its place, and a knowledge check on what makes a question usable.",
          appliedNextStep: "Choose one review your unit already holds. Attach one question to each existing item, name who answers and where the answer is recorded, set the date you will check whether the questions changed a decision, and bring the draft to the next meeting rather than announcing it.",
        },
        scenario: {
          context: "Your unit runs a standing quarterly review of contracted service performance. The agenda has four fixed items: volume and activity, resolution and response times, corrective plans, and open licensing and compliance matters. A senior leader asks you to build equity into the review before the next quarter. There is no additional meeting time, no new staff, and the contract managers who attend are already at capacity.",
          prompt: "How do you build it in?",
          options: [
            { label: "Add a standing agenda item called “Equity” at the end of the meeting, with a rotating presenter each quarter.", response: "This is the most common design and it fails in a predictable way. The last item is the one cut when the meeting runs long, a rotating presenter means nobody owns it, and putting equity in its own item separates it from the four places where decisions are actually made." },
            { label: "Attach one question to each of the four items that are already on the agenda, name who answers it, and record the answer in the same minutes as the item itself.", response: "The questions arrive where the decisions are, they cost a few minutes rather than a new meeting, and the answers sit in the record next to the item they affected. This also survives a busy quarter, because there is no separate thing to cut.", recommended: true },
            { label: "Write an equity commitment into the review charter and ask each contract manager to keep it in mind when preparing their material.", response: "Nothing is wrong with the commitment and nothing will come of it. There is no point in the meeting where anyone must answer anything, no record of whether it happened, and no way to tell six months later whether the review changed at all." },
          ],
        },
        transfer: {
          prompt: "Which review will you add questions to, and what will you check three months from now?",
          options: [
            "Name the review, the four items already on its agenda, and the question you would attach to each",
            "Name who answers each question — a role, not the meeting as a whole",
            "Decide where the answer is recorded, and check that it is somewhere the next person will actually look",
            "Set the date you will ask whether any of the questions changed a decision, and what you will do if none did",
            "Bring the draft to the meeting unfinished, so the people who attend can rewrite it",
          ],
        },
        blocks: [
          { type: "text", heading: "Put the question where the decision is", body: "<p>The usual way an organization adds equity to a review is to add a section about it. The section goes at the end, because the existing items have owners and history and the new one does not. It is presented by whoever is available. It is the first thing dropped when the meeting runs twelve minutes late, which is most meetings. And because it sits apart from the items where decisions are made, even a good discussion in that section rarely changes a decision in the others.</p><p>The alternative costs less and works better. Leave the agenda alone and attach one question to each item that is already there. The volume item gets a question about who could not reach the route. The resolution time item gets a question about where the time is uneven. The corrective plan item gets a question about whether the plan changes a condition or relies on people being more careful. The open matters item gets a question about whether the people affected have been told what happened, in a form they can use. Nothing new is scheduled. Four questions get asked in the four places where they could change something.</p><p>Three things make the difference between a question that works and a question that decorates. It has to attach to a specific item, so there is a moment when it must be asked. Somebody by role has to answer it, so it is not addressed to the room. And the answer has to be recorded in the same minutes as the item, so that a decision made afterward has the answer sitting next to it. Without all three, the question survives about two quarters.</p><p>Plan for the answer “we do not know,” because at first it will be the honest answer to most of them. That is not a failure of the question; it is the first finding. Make the rule in advance: an unknown produces a named owner and a date, and comes back to the same item next quarter. Otherwise the question quietly stops being asked, because nobody enjoys the silence that follows it.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A short set of equity questions for a review you already run", summary: "Four questions attached to items already on an agenda, with an owner for each answer and a date to check whether any of it changed a decision. Copy the fields and fill them for your own review.", fields: [
            { label: "The review and the item each question attaches to", value: "Quarterly contracted service performance review. Item one: volume and activity. Item two: resolution and response times. Item three: corrective plans. Item four: open licensing and compliance matters. No new agenda item, no additional meeting time." },
            { label: "The four questions", value: "One — who could not reach this route, and what does this count therefore not include? Two — split by region, language, communication method and who filed: where is the time uneven, and for whom? Three — does this plan change a condition, or does it rely on the same people being more careful? Four — which of the people affected have been told what happened, in a language and format they can use?" },
            { label: "Who answers, and where the answer is recorded", value: "The item owner answers, by role rather than by volunteer: the reporting analyst for one and two, the contract manager for three, the communications lead for four. Each answer goes in the minutes beside its own item, not in a separate summary." },
            { label: "What happens when the answer is “we do not know”", value: "An unknown is recorded as an unknown, with a named owner and a date, and returns to the same item at the next review. Unknowns are expected in the first two rounds and are the first real finding; they are not a reason to drop the question." },
            { label: "The date the addition itself is reviewed", value: "At the agreed point after two full rounds: did any answer change a decision, which question produced only unknowns, and what should be reworded or replaced? Whoever proposed the questions brings that review, and the meeting may cut one." },
          ], action: "Copy the five fields, fill them for one review your unit already holds, take the draft to that meeting unfinished, and keep whatever the people who attend rewrite." },
          { type: "accordion", heading: "Why each question earns its place", items: [
            { title: "Who could not reach this route, and what does this count therefore not include?", body: "<p>Attached to any item built on a count. It reopens the difference between a service and the route to it, which a volume figure closes automatically. In the first rounds the answer is usually “we do not know,” and that answer is more useful than the count it sits beside.</p>" },
            { title: "Where is the time or the outcome uneven, and for whom?", body: "<p>Attached to any item reporting an average. It costs one cut of data the unit already holds. It is the fastest way to find a barrier, and it is the question an overall rate is structurally unable to raise on its own.</p>" },
            { title: "Does this plan change a condition, or rely on people being more careful?", body: "<p>Attached to corrective plans and improvement actions. Most plans that fail quietly are the second kind. Asking it out loud, in front of the people who wrote the plan, tends to improve the plan in the meeting rather than three quarters later.</p>" },
            { title: "Who affected by this has been told what happened, in a form they can use?", body: "<p>Attached to open matters and closures. Divisions are good at resolving and poor at telling. This question is the one most likely to produce visible work for the people who were actually harmed, and it is the one most often missing from a review entirely.</p>" },
          ] },
          { type: "leaderMove", heading: "Put an owner on the question, not on equity", control: "You control whether a question is addressed to a role that must answer it, or to the meeting in general.", failure: "Do not assign the questions to an equity lead, a committee or a rotating presenter. Once the questions belong to a specialist, the item owners stop treating them as part of their own item, which is the only place they do any work.", next: "Write the role beside each question before the draft goes anywhere, and check that no two questions land on the same person." },
          { type: "knowledgeCheck", id: "ipe-32-4-check", question: "Which addition to an existing review is most likely to still be working a year from now?", options: [
            { text: "A standing equity item at the end of the agenda, presented by a different attendee each quarter.", correct: false },
            { text: "One question attached to each existing agenda item, answered by that item’s owner, recorded in the same minutes, with a date set to review whether any answer changed a decision.", correct: true },
            { text: "An equity statement in the review charter that all attendees are asked to consider while preparing.", correct: false },
            { text: "A twelve-question equity checklist circulated before each review for attendees to complete in advance.", correct: false },
          ], feedbackCorrect: "Yes. It has a moment, an owner, a record and a check — and nothing separate that can be cut when the meeting runs long.", feedbackIncorrect: "Ask of each option: when exactly does someone have to answer, who is that person, where does the answer go, and how would anyone know later whether it happened?" },
          { type: "text", heading: "A private reflection, for you alone", body: "<p>Nothing here is collected, scored or seen by anyone else. Take whichever question is useful and leave the rest.</p><p>How might my role, authority or language shape which complaints are treated as credible in a review I take part in? Who could be helped, burdened, excluded or misunderstood by the complaint and review processes my area runs? Whose expertise is missing from the way we decide what a complaint means, and what would it take to have it here earlier? What might accessibility mean here beyond the legal minimum — in the route, the form, the answer and the time it takes?</p><p>And one more, if it is useful: when something in my area harmed or excluded someone, what would accountability and repair actually require of us, rather than of the person closest to the error?</p>" },
          { type: "statement", body: "A commitment worth writing down: “The review I will add questions to is… the item each one attaches to is… the person who answers is… and the date I will ask whether any of it changed a decision is…”" },
        ],
      },
    ],
  },
  jobAid: {
    title: "Quality, complaints and incident learning",
    subtitle: "One page for anyone who reviews complaints, incidents, performance or contracted service quality",
    quote: "A complaint count is a count of the people who got through. Everyone stopped on the way looks exactly like satisfaction.",
    use: {
      purpose: "Keep four things in view while you read complaint data, review something that went wrong, summarize a set of records, or add questions to a review your unit already holds.",
      remember: [
        "A complaint count measures the route before it measures the service. Ask what changed in the route before you credit a result.",
        "A quiet channel is a finding, not a result. The fastest test is to try to use it the way the people missing from your data would have to.",
        "Blame produces a name and a reminder. Accountability produces a change, an owner, a date and a check.",
        "Ask what made this the reasonable thing to do with the information, tools and time available. If the answer is nothing, keep looking.",
        "Reports of maltreatment, licensing actions, appeals, complaints of discrimination and discipline belong to the responsible offices; a learning review neither replaces them nor waits for them.",
        "An average hides whoever is carrying the uneven part. Cut by region, program, language and communication method, who filed, and whether it is a repeat.",
        "A record can only report what its fields asked. Name what yours cannot see before you summarize it.",
        "A small group is a reason to state a finding carefully, not a reason to drop it.",
        "Identical handling of unequal access is Minimization, not fairness. Acceptance begins when those differences come back into the analysis.",
        "Nobody has to disclose a diagnosis, a belief, a background or a private experience to take part in any of this.",
      ],
      doNext: "Attach one question to each item on a review you already hold, name who answers it and where the answer is recorded, and set the date you will check whether any answer changed a decision.",
    },
    sections: [
      {
        heading: "The equity questions, in short",
        items: [
          "Attach the questions to items already on the agenda. Do not create a separate equity item at the end; it is the first thing cut.",
          "On any count: who could not reach this route, and what does this count therefore not include?",
          "On any average: split by region, language, communication method and who filed — where is the time or the outcome uneven, and for whom?",
          "On any corrective plan: does this change a condition, or does it rely on the same people being more careful?",
          "On any open or closed matter: which of the people affected have been told what happened, in a language and format they can use?",
          "Name the role that answers each question, and record the answer in the same minutes as its own item.",
          "Treat “we do not know” as a real answer that produces an owner and a date, and expect it for the first two rounds.",
          "Set a date to review the questions themselves: which changed a decision, which produced only unknowns, and which should be reworded or dropped.",
        ],
      },
      {
        heading: "When you read a complaint count",
        items: [
          "Ask what changed in the route — channel, format, languages, the person who used to help people file — before crediting a movement in volume.",
          "Walk the route yourself the way the missing group would have to; it usually takes under an hour.",
          "Treat a rise as a possible sign the route improved, not as declining quality.",
          "Note when most complaints in an area arrive through a family member, provider or advocate rather than the person themselves.",
          "Ask one paid community advisor what people tell them that never reaches the division.",
        ],
      },
      {
        heading: "When you review something that went wrong",
        items: [
          "Reconstruct what the person could see at the moment, not what is obvious now.",
          "Write four lines: what happened, what made it reasonable, what changes with an owner and a date, and what is being done for the people affected.",
          "Let the person closest to the work read the account before anyone above you does.",
          "Ask who else could have caught it and what stopped them; that answer is usually a condition too.",
          "Answer a request for a name with conditions and a name, not with one or the other.",
          "Report maltreatment immediately and separately; never let a learning review delay it.",
        ],
      },
      {
        heading: "When you summarize a set of records",
        items: [
          "List what the fields asked for, and then what they made impossible to find.",
          "Make the cuts before you trust the overall rate, not after someone questions it.",
          "Read the withdrawn, unanswered and abandoned records; they usually hold the most.",
          "Put narratives and counts on the same page, and treat two accounts of the same obstacle as a finding.",
          "State a small number plainly and act on the pattern rather than waiting for the group to grow.",
          "Propose one field change so the next cycle can answer the question you could not.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Quality, compliance and performance staff, whose complaint, incident and corrective-plan reviews are the subject of this module — a good place to start, and the deepest fit.",
          "Data, research and evaluation staff, who decide which cuts get made, what a small group means, and whether narratives reach the same page as the counts.",
          "Contracts, fiscal and procurement staff, who run performance reviews where a question attached to an existing item can change what a contract actually requires.",
          "Supervisors and managers, whose first response to bad news sets whether the next problem arrives early or late.",
          "Executive and senior leaders, who decide whether an account reaches them as a name or as a condition, and whether a review point survives a busy quarter.",
          "Policy, program and operations staff, who own many of the conditions a good review finds.",
          "Communications and learning-design staff, who write the notices, forms and answers that decide whether a complaint route is usable at all.",
          "Administrative and support staff, who see which calls come back a third time and which letters are returned unopened.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "Leading a reflective DSD team",
          "Equitable policy and procedure governance",
          "Responsible data and evaluation",
          "Co-design and compensated partnership",
          "Resource allocation and equity",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials, and instruction that never requires anyone to disclose a personal experience in order to take part." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the standards on conflict and grievance resolution, community assessment, continuous improvement and accountability that frame this module's approach to complaints and reviews." },
    { title: "Minnesota Department of Human Services, appeals", href: "https://mn.gov/dhs/general-public/appeals/", note: "The department's own description of the formal appeal and fair hearing route available to a person disputing a decision about their services, which runs on its own authority and timelines separately from any quality or learning review." },
    { title: "Minnesota Ombudsman for Mental Health and Developmental Disabilities", href: "https://mn.gov/omhdd/", note: "An independent state office that receives complaints and reviews deaths and serious injuries for people receiving mental health, developmental disability and related services — an example of a route that exists outside the division and often hears what the division does not." },
    { title: "Minnesota Department of Human Services, adult protection", href: "https://mn.gov/dhs/people-we-serve/adults/services/adult-protection/", note: "Minnesota's adult maltreatment reporting system and the reporting obligations that apply immediately and independently of any internal review, used here to mark where a learning review must stop and a formal report begins." },
    { title: "ADA.gov, Title II primer for state and local governments", href: "https://www.ada.gov/resources/title-ii-primer/", note: "U.S. Department of Justice explanation of Title II obligations for state and local government programs, including effective communication and grievance procedures — the legal floor beneath the optional practice described in this module." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's advisory council on disability policy and access, including practical guidance for state agencies on accessible materials, notices and public processes, which shapes whether a complaint route is usable in the first place." },
    { title: "plainlanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Practical guidance for writing a notice, a complaint form or a review finding that a reader can act on without interpretation — applied here to complaint routes, correction letters and the wording of review findings." },
  ],
};

export default pack;
