import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Internal leadership · Module 38: Sustaining voluntary learning.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-38-sustaining-voluntary-learning",
    indexNumber: 1180,
    seriesLabel: "Intercultural Practice and Equity · Internal leadership",
    title: "Sustaining Voluntary Learning",
    subtitle: "Learning that nobody is required to do needs conditions, not enforcement. Four lessons on protecting time, making the work visible without watching people, and building team rhythms that survive a busy quarter.",
    scope: "For internal DHS and DSD supervisors, managers, executives and senior leaders who want equity and intercultural learning to keep going after the launch message — and for the policy, program, quality, communications, learning, data and administrative staff who end up holding the practice together. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota DSD leadership examples, scenarios, sorting and flashcard practice, private reflection prompts, and a one-page team learning rhythm and resource-sharing plan you can copy into your own work",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/intercultural-competence-no-score.jpg",
    coverAlt: "Four colleagues talk in a hallway with coffee.",
    introTranscript: "Almost every division has watched the same thing happen. A learning offering opens well, a few dozen people use it in the first weeks, and by the third month it has gone quiet. The usual reactions are to require it, to count it, or to let it fade. All three change what the learning is. This module is about the fourth option: finding out which condition actually went missing, protecting a small amount of time, connecting the material to decisions the team already has to make, and reporting what changed in the work rather than who opened what. It covers the difference between required-training records and voluntary learning, what a leader can honestly tell a director without building a file on anyone, the small rhythms that outlast enthusiasm, and how to make the word optional true in practice. It ends with a one-page plan your team can write together.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Name the five conditions voluntary learning depends on — time, permission, relevance, visibility and safety — and identify which one has gone missing on a specific team.",
        "Explain why requiring, counting and comparing voluntary learning change what it is, and keep required-training obligations clearly separate from optional learning.",
        "Report honestly on learning without collecting individual use, attendance or reflections, using changes in the work as the evidence.",
        "Design a team learning rhythm that survives workload spikes, rotates its host, and offers more than one way to take part.",
        "Write a one-page team learning rhythm and resource-sharing plan that states plainly what is not recorded and how declining is treated.",
      ],
      evidence: [
        "Four worked scenarios drawn from a learning offering that went quiet, a director's request for a quick read, a rhythm that depended on one person, and a private question about performance review.",
        "A knowledge check in every lesson with feedback that explains the workable answer.",
        "Sorting practice that separates what can be reported from what stays private, and what sustains a rhythm from what ends it.",
        "A completed one-page team learning rhythm and resource-sharing plan, with a host rotation, a second way to take part, and a stated season and check-in point.",
      ],
      appliedNextStep: "Pick the team you actually lead or support. Write down which of the five conditions is weakest for them right now, and change that one thing — not all five — before the next month is out.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in what DHS or DSD requires of staff as mandatory training, or in how training completion and performance information are recorded and used",
        "A change in state or federal accessibility requirements that affects how internal learning material and shared resources must be offered",
        "Feedback from supervisors, from staff who take part, or from compensated community reviewers that the practices described here read as optional on paper and mandatory in practice",
      ],
      relatedDoor: "Formal decisions about required training, training records, performance management and what appears in an employee's file belong to the responsible DHS human resources, learning and labor relations offices; this module helps you design voluntary learning alongside those obligations, not around them.",
      toolkitQuestion: "If someone on my team quietly chose not to take part, is there any place in our routines where that choice would show up?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-38-1",
        number: 1,
        title: "Why voluntary learning stops",
        summary: "It rarely stops because people lost interest. Five conditions hold it up, and the three usual rescues break the thing they are trying to save.",
        minutes: 10,
        learning: {
          objective: "Identify which of the five conditions — time, permission, relevance, visibility or safety — has gone missing on a specific team, using evidence the team already has.",
          takeaways: [
            "Voluntary learning depends on five conditions. Time that is actually protected, permission that people have heard out loud, relevance to a decision in front of them, visibility so the work is not invisible, and safety so that what a person does not yet know cannot be used against them.",
            "The three usual rescues change what learning is. Requiring it turns reflection into compliance, counting it turns curiosity into a file, and comparing teams turns colleagues into competitors and exposes the least confident person first.",
            "Required training and voluntary learning are different things with different rules. Keeping them plainly separate is what makes the voluntary part safe enough to be honest in.",
            "A single time slot for everyone feels like fairness and quietly selects for people whose week looks like the organizer's. Treating sameness as fairness is the habit the continuum calls Minimization, and it is the most common default in a large division.",
          ],
          evidence: "A scenario about a learning offering that went quiet by the third month, a knowledge check on what a drop in use actually tells you, and a condition-by-condition reading of one team.",
          appliedNextStep: "Name the last three staff members who told you they wanted to take something on and did not. For each, write which of the five conditions was missing, in one sentence, without naming anyone in anything you share.",
        },
        scenario: {
          context: "A DSD leadership team opened a voluntary set of equity and intercultural modules to a division of about a hundred and fifty staff. Use was strong for four weeks, thin by the eighth, and close to nothing by the twelfth. In the leadership meeting, a manager proposes adding participation to everyone's performance goals and pulling a monthly report of use by unit so leaders can see which teams are behind.",
          prompt: "What is the most useful first move?",
          options: [
            { label: "Add participation to performance goals and circulate the monthly report of use by unit.", response: "This converts something voluntary into something required, without the deliberation and bargaining a real requirement deserves. It also makes any honest reflection risky, and a report by unit invites comparison between supervisors, which moves everyone's attention to the number rather than the work." },
            { label: "Find out which of the five conditions went missing before changing anything: ask a handful of staff what stopped them, protect a small piece of time, attach one module to a decision the team already has to make, and report what the team learned rather than who took part.", response: "This treats the drop as information about conditions rather than about people. It is also the only option that leaves the learning voluntary, which is the thing that made honest reflection possible in the first place.", recommended: true },
            { label: "Let it rest and relaunch with better communication in a quieter season.", response: "This treats attention as the only variable. If the conditions that stopped it were unprotected time and unclear permission, a better announcement in a quieter season will meet exactly the same wall." },
          ],
        },
        transfer: {
          prompt: "Which of the five conditions is weakest on your team right now, and what is the smallest change that would strengthen it?",
          options: [
            "Name the condition and the evidence that tells you it is the weak one",
            "Write the smallest change you could make without anyone's approval",
            "Name the person or meeting that would have to change for it to hold for more than a month",
          ],
        },
        blocks: [
          { type: "text", heading: "Interest is almost never the problem", body: "<p>When a voluntary learning offering goes quiet, the first explanation offered in a leadership meeting is usually about motivation. People are busy, priorities shifted, the enthusiasm faded. That explanation is comfortable because it places the cause in staff rather than in the design, and it leads directly to the three interventions that damage voluntary learning most.</p><p>In a public agency, the more accurate explanation is nearly always structural. A staff member who wants to take a forty-minute module has to decide, in the middle of a caseload or a policy deadline, whether spending that time is allowed. If nobody has said out loud that it is, the safe answer is no. If the time is not on a calendar anywhere, the safe answer is no. If the module has no visible relationship to a decision the person will actually make, the safe answer is no. None of that is a motivation problem, and none of it is fixed by a reminder.</p><p>Five conditions hold voluntary learning up: time, permission, relevance, visibility and safety. They fail one at a time and they fail quietly. The useful question after a drop is not why people stopped caring. It is which of the five went missing, and when.</p>" },
          { type: "tabs", heading: "Five conditions, and how each one disappears", tabs: [
            { label: "Time", body: "<p><strong>What it looks like when it holds:</strong> a protected slot on a real calendar, or an explicit statement that this counts as work time and does not have to be made up.</p><p><strong>How it disappears:</strong> nobody says where the time comes from. Staff conclude, correctly, that it comes out of their own evening or their own backlog. The offering is not refused; it is postponed forever.</p>" },
            { label: "Permission", body: "<p><strong>What it looks like when it holds:</strong> a supervisor says, in a meeting and again in writing, that taking an hour for this is expected to be normal, and then is seen doing it.</p><p><strong>How it disappears:</strong> permission is assumed rather than stated. Newer staff, staff who are already worried about their standing, and staff whose work is closely measured all read silence as a warning.</p>" },
            { label: "Relevance", body: "<p><strong>What it looks like when it holds:</strong> a module is attached to something the team is about to do — a policy revision, a letter rewrite, a partnership meeting, a complaint pattern.</p><p><strong>How it disappears:</strong> the catalogue is offered as a catalogue. Everything is available and nothing is connected, so choosing becomes one more decision in a week that is already full of them.</p>" },
            { label: "Visibility", body: "<p><strong>What it looks like when it holds:</strong> people hear what colleagues found useful, in ordinary conversation, and see something in the work change because of it.</p><p><strong>How it disappears:</strong> learning becomes entirely private. Not private in the protective sense — private in the sense that nobody ever knows it happened, so it never becomes part of how the team talks about its work.</p>" },
            { label: "Safety", body: "<p><strong>What it looks like when it holds:</strong> it is clear what is and is not recorded, reflections stay with the person who wrote them, and not knowing something is treated as ordinary.</p><p><strong>How it disappears:</strong> a well-meant report, a roster, a stray comment in a performance conversation. It takes one instance for people to conclude that the honest answer is the expensive one.</p>" },
          ] },
          { type: "leaderMove", heading: "Say the permission out loud, then be seen using it", control: "You control whether the people you supervise have actually heard that spending work time on this is normal, and whether they have seen you do it.", failure: "Do not assume that opening a resource is the same as granting permission. Staff read the absence of a statement as a risk, and the people most likely to read it that way are the ones with the least standing to lose it.", next: "At your next team meeting, say plainly where the time comes from, then block the same amount on your own calendar where the team can see it." },
          { type: "flashcards", heading: "The three rescues, and what each one costs", cards: [
            { front: "Requiring it", back: "<p>Turns reflection into compliance. People produce the answer that is safe to have on record, which is exactly the answer that teaches nobody anything. A genuine requirement may sometimes be right — but it belongs in the required-training system, negotiated openly, not bolted onto something that was introduced as optional.</p>" },
            { front: "Counting it", back: "<p>Turns curiosity into a file. Once individual use is visible to anyone above a person, the rational move is to open the module and move on. You gain a number that measures page-opening and lose the thing the number was supposed to describe.</p>" },
            { front: "Comparing teams", back: "<p>Turns colleagues into competitors and makes supervisors manage the number rather than the practice. It also lands hardest on units with the least slack, which are usually the units carrying the heaviest and most exposed work.</p>" },
            { front: "Required training", back: "<p>A genuine obligation with a real basis, recorded in the department's own system, with consequences that are stated in advance. It should be named as such, plainly, and never blurred with optional learning.</p>" },
            { front: "Voluntary learning", back: "<p>Chosen by the person, not recorded against them, safe to be honest in, and free to decline. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.</p>" },
          ] },
          { type: "quote", text: "I wanted to take the module on language access because I write the letters. What I could not work out was whether an hour of it would look like an hour I was not doing my job. Nobody had said either way, so I did not risk it.", cite: "Composite DSD program staff perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-38-1-check", question: "Use of a voluntary learning offering drops sharply after the first month. Which reading is best supported?", options: [
            { text: "Interest has faded; the offering should be relaunched with stronger messaging.", correct: false },
            { text: "One or more of the conditions the learning depends on — protected time, stated permission, relevance to current work, visibility, or safety — has gone missing, and the first task is to find out which one.", correct: true },
            { text: "The content is too difficult, and shorter material would hold attention better.", correct: false },
            { text: "Participation should be added to performance goals so that it competes fairly with other priorities.", correct: false },
          ], feedbackCorrect: "Yes. A drop is information about conditions long before it is information about people, and each of the five conditions needs a different repair.", feedbackIncorrect: "Ask what a staff member has to decide before opening a module in the middle of a working day: is the time allowed, has anyone said so, does it connect to something in front of me, and is it safe to be honest in? The answer to one of those has usually changed." },
          { type: "statement", body: "Private reflection, for you alone and collected nowhere: think of a colleague who has never taken up any of this. What in the way you run the team might be telling them that it is not for them, or not worth the risk? Nothing you write here is recorded or shared." },
        ],
      },
      {
        id: "ipe-38-2",
        number: 2,
        title: "Visible without being watched",
        summary: "Leaders are asked whether learning is working. There is an honest answer that does not require a record of who read what.",
        minutes: 11,
        learning: {
          objective: "Answer a leadership question about whether voluntary learning is working, using changes in the work as evidence, without collecting individual use, attendance or reflections.",
          takeaways: [
            "Three different things get called tracking: required-training records, which have a real basis and belong in the department's own system; grouped signals about whether a resource is useful, which can be kept free of names; and individual records of voluntary learning and reflections, which are the ones to refuse.",
            "The most honest evidence is the work itself. A rewritten notice, a changed agenda, a question someone brought to a partnership meeting, a decision made differently — these tell a director more than a use count ever will, and they cost nobody their privacy.",
            "Visibility should be opt-in and about content, not people. What is shared is what a person chose to share, described by topic and by change, never by name and never by who did not take part.",
            "The continuum stages describe the direction the program is moving in. They are never a label, a rating or a note about a colleague, and no inferred position belongs in any record about a person.",
          ],
          evidence: "A scenario about a director asking for a quick read before a division update, a sorting exercise separating what can be reported from what stays private, and a knowledge check on grouped reporting.",
          appliedNextStep: "Write the three sentences you would actually say to your director about learning on your team this quarter. If any of them requires knowing who opened what, rewrite it around something that changed in the work.",
        },
        scenario: {
          context: "A DSD director asks a supervisor for a quick read on whether the equity and intercultural learning is landing, ahead of a division update. The supervisor has three things available: a list from the shared page showing which staff opened which modules, several private reflections that staff mentioned in one-to-one meetings, and a revised client notice the team rewrote after two people worked through the plain-language material.",
          prompt: "What should the supervisor bring to the director?",
          options: [
            { label: "The list of who opened which modules, because it is the most concrete thing available.", response: "It is the least meaningful and the most damaging of the three. Opening a page is not learning, and once a name-level list has circulated once, staff manage their behavior around it from then on. The supervisor would be trading the practice for a number that does not describe it." },
            { label: "The revised notice, the questions the team raised, and which topics drew enough interest to be worth scheduling a discussion — with a plain statement that individual use and reflections are not collected, and an offer of a better question the director could ask next quarter.", response: "This answers the real question with the strongest evidence available, protects the conditions the learning depends on, and gives the director something to act on. Naming what is deliberately not collected also prevents a reasonable request from turning into a roster later.", recommended: true },
            { label: "Ask each staff member to write a short summary of what they have learned, and pass the summaries up.", response: "This converts private reflection into an assignment that leadership will read. The predictable result is careful writing that reveals nothing, and staff correctly conclude that reflection is now a performance document." },
          ],
        },
        transfer: {
          prompt: "What could you honestly report about learning on your team without knowing what any individual did?",
          options: [
            "Name one thing in the work that changed, and what prompted it",
            "Name one question the team raised that it would not have raised a season ago",
            "Name one topic that drew enough interest to be worth a scheduled discussion",
            "Name the one thing you will say plainly is not collected",
          ],
        },
        blocks: [
          { type: "text", heading: "The question behind the question", body: "<p>A director who asks whether the learning is working is almost never asking for a use count. They are usually asking one of three things: can I say something credible about this in a meeting, is this worth the time it is taking, or is anything actually changing. A use count answers none of those. It answers a fourth question nobody asked, which is how many people clicked.</p><p>This matters more than it sounds. The measure you choose becomes the thing your team optimises for, and it does so within about a month. Choose a use count and you will get pages opened. Choose changed work and you will get conversations about notices, agendas, contracts and letters. The second is harder to put in a table and far more honest.</p><p>There is also a floor under all of this. A person's voluntary learning, and above all their reflections, are theirs. In a program whose subject matter includes bias, assumptions and the things a person does not yet understand, a record of who is working on what would be a record of who has admitted a gap. That record would be read differently depending on who the person is, and it would be read hardest by the people with the least standing in the organization.</p>" },
          { type: "accordion", heading: "Three different things people call tracking", items: [
            { title: "Required-training records", body: "<p>Mandatory training has a real basis, a stated consequence and a system of record kept by the department. That system exists for good reasons and this module does not argue with it. What matters here is that it stays clearly labeled as what it is, so that nobody has to guess which category a given offering falls into. When staff cannot tell the difference, they treat everything as mandatory and nothing as safe.</p>" },
            { title: "Grouped signals about a resource", body: "<p>It is legitimate to want to know whether a resource is useful. Grouped signals can answer that without names: how many people across a division used a topic area, which modules generated questions, what the shared resource space is actually being used for. Keep the groups large enough that nobody can be picked out of them, and resist any request to break them down by unit or supervisor, because a small unit is a person.</p>" },
            { title: "Individual records of voluntary learning", body: "<p>This is the category to refuse. Who opened what, who attended, who reflected on which prompt, how far along someone appears to be. None of it belongs in a supervisory record, a performance conversation or a division report, and none of it measures the thing it appears to measure. If a system produces it by default, ask what it would take to stop producing it.</p>" },
            { title: "What the continuum describes", body: "<p>Denial, Polarization, Minimization, Acceptance, Adaptation and Integration describe where a program's practice is heading and give a team shared language for patterns in how work gets done. They are not a rating, not a label for a colleague, and not something to note about anyone. Licensed assessment is a separate, professionally administered matter; this program does not stand in for it, score anyone, or attach a position to a person's name.</p>" },
          ] },
          { type: "sorting", id: "ipe-38-2-sort", heading: "Report it, group it, or leave it alone", categories: ["Report it as evidence", "Group it so no one is identifiable", "Leave it with the person"], items: [
            { text: "The team rewrote the appointment notice after working through the plain-language material.", category: "Report it as evidence" },
            { text: "What a staff member wrote in a private reflection prompt about her own assumptions.", category: "Leave it with the person" },
            { text: "Across the division, the language access and co-design topics drew the most interest this season.", category: "Group it so no one is identifiable" },
            { text: "A named list of who opened which module, arranged by unit.", category: "Leave it with the person" },
            { text: "The team started asking, in contract discussions, who is being paid for their expertise and who is not.", category: "Report it as evidence" },
            { text: "The number of questions the policy inbox received about accessible formats this quarter.", category: "Group it so no one is identifiable" },
            { text: "Whether a particular staff member has taken the IDI, and anything about their results.", category: "Leave it with the person" },
          ] },
          { type: "leaderMove", heading: "Offer the better question before someone asks for the roster", control: "You control which measure you put in front of leadership first, and a reasonable request usually takes the shape of whatever you have already made available.", failure: "Do not wait until someone asks for a list and then argue about privacy. By then you are refusing a request instead of having already answered the question.", next: "Before your next update, write down the three changes in the work you can point to, and lead with those. Say in the same breath what is deliberately not collected and why." },
          { type: "list", heading: "Things you can say that are both true and useful", items: [
            "Here is what changed in a document, a process or a meeting, and here is what prompted it.",
            "Here are the questions the team is asking now that it was not asking a season ago.",
            "Here are the topics that drew enough interest to be worth scheduling a discussion.",
            "Here is what we tried that did not work, and what we think the reason was.",
            "Here is what we do not collect: who took part, what anyone wrote, and how far along any individual is.",
            "Here is the better question I would like to be asked next quarter, and what I would need to answer it.",
          ] },
          { type: "knowledgeCheck", id: "ipe-38-2-check", question: "A division leader asks for learning participation broken out by unit so that supervisors can be supported where use is low. A division has several units of three to five people. What is the sound response?", options: [
            { text: "Provide it, since the intent is supportive rather than punitive.", correct: false },
            { text: "In a unit of three to five people, a unit-level figure identifies individuals, so offer a division-level picture instead, together with what has actually changed in the work and an explanation of what is not collected.", correct: true },
            { text: "Provide it, but ask supervisors not to discuss individual results with their staff.", correct: false },
            { text: "Refuse without explanation, since participation information is private.", correct: false },
          ], feedbackCorrect: "Yes. A small unit is a person, intent does not change what the number reveals, and a plain explanation with a better answer attached is far more useful than a flat refusal.", feedbackIncorrect: "Ask how many people sit behind each figure. When a unit has three staff, a unit-level count is an individual-level count with a different label on it — and a supportive intention today does not travel with the number to whoever reads it next." },
          { type: "statement", body: "Private reflection, for you alone and collected nowhere: is there anywhere in your own routines — a note, a spreadsheet, a memory you draw on in performance conversations — where you are holding information about who has and has not taken part? What would it take to stop holding it?" },
        ],
      },
      {
        id: "ipe-38-3",
        number: 3,
        title: "Rhythms that survive a busy quarter",
        summary: "Enthusiasm lasts about six weeks. A rhythm that is small, shared, connected to real work and open in more than one way lasts much longer.",
        minutes: 11,
        learning: {
          objective: "Design a team learning rhythm that survives a workload spike, using a rotating host, a connection to current work, and at least two ways to take part.",
          takeaways: [
            "Small and repeatable beats large and occasional. A standing twenty-five minutes attached to a meeting that already exists outlasts a quarterly half-day, because it survives the week when everything is on fire.",
            "A rhythm owned by one enthusiastic person ends when that person moves teams. Rotating the host, with a short shared outline, is what turns a personal practice into a team practice.",
            "One time slot for everyone quietly excludes part-time staff, people working early or late hours, staff with caregiving at midday, field staff and anyone who needs processing time. A second way to take part is a design decision, not a consolation prize.",
            "A rhythm with a named season and a check-in point survives better than an open-ended commitment, because people can say yes to something that has an end and an honest review.",
          ],
          evidence: "A scenario about a monthly learning half-hour that depended on one analyst and never reached part-time staff, a sorting exercise on what sustains and what ends a rhythm, and a knowledge check on scheduling.",
          appliedNextStep: "Look at a meeting your team already holds. Decide whether twenty-five minutes of it, once a month, could carry this — and who other than you would host the second one.",
        },
        scenario: {
          context: "A DSD unit has held a monthly learning half-hour for two seasons. It works because one analyst prepares everything, picks the material, writes a short note and runs the discussion. She is moving to another team next month. The slot has always been at noon, and the three part-time staff and the two staff who work early hours have never attended.",
          prompt: "What would keep this going, and make it better than it was?",
          options: [
            { label: "Ask the analyst to keep hosting from her new team until someone on the unit is ready to take it over.", response: "This keeps a rhythm alive on one person's goodwill and postpones the problem rather than solving it. Nobody else has hosted, so nobody else will feel ready, and the noon slot that has excluded five staff for two seasons is untouched." },
            { label: "Rotate the host using a short shared outline, alternate the slot so it is not always at noon, add a written way to take part for anyone who cannot be there, and name a season with a check-in point.", response: "Each part addresses a different failure. The rotation makes it a team practice rather than a personal one, alternating the slot stops one schedule from deciding who belongs, the written option makes participation real for part-time and early-hours staff, and a stated season with a check-in gives everyone an honest exit.", recommended: true },
            { label: "Stop the meeting and point people to the shared resource page instead, since the material is available any time.", response: "The page was always there. The half-hour was the thing that turned a page into a conversation and connected material to the unit's actual work. Removing the rhythm and keeping the page returns the unit to exactly the state it was in before the analyst started." },
          ],
        },
        transfer: {
          prompt: "Which existing meeting could carry twenty-five minutes of this, and who besides you would host?",
          options: [
            "Name the meeting and the amount of time you would take from it",
            "Name two people who could host, and what each would need to feel ready",
            "Name the second way to take part for anyone who cannot attend live",
            "Name the season this runs for and the date you will check in on it",
          ],
        },
        blocks: [
          { type: "text", heading: "Build for the bad month, not the good one", body: "<p>Most learning rhythms are designed during a good month. Someone is enthusiastic, the calendar has room, and the first session goes well. The design question that actually matters is different: what happens to this in the month when a legislative deadline lands, two people are out, and a complaint needs a response by Friday.</p><p>A ninety-minute quarterly session does not survive that month. It gets moved, then moved again, and the second move is usually the end. Twenty-five minutes attached to a meeting that already exists often does survive, because it is small enough to keep and it does not require anyone to find a new hour.</p><p>The second design question is who it belongs to. A rhythm carried by one enthusiastic person is a personal practice that other people attend. It ends when that person moves, goes on leave, or gets tired — and the team learns, incorrectly, that this kind of thing does not last here. Rotating the host, with a short outline anyone can follow, is the difference between a practice and a person.</p><p>The third question is who the schedule was built around. A single slot that suits full-time day staff reads as neutral and is not. Part-time colleagues, people on early or late hours, staff with caregiving at midday, staff in the field, and anyone who needs time to process before speaking are all filtered out by a choice nobody made deliberately. Offering one way to take part and calling it fair because it is the same for everybody is the Minimization pattern in its most ordinary form.</p>" },
          { type: "tabs", heading: "Four rhythms, what each costs, and what breaks it", tabs: [
            { label: "Standing slot", body: "<p><strong>What it is:</strong> twenty-five minutes on an existing monthly team meeting, with one short piece of material read in advance or skimmed together.</p><p><strong>What it costs:</strong> the time, and someone's preparation of a half-page note.</p><p><strong>What breaks it:</strong> letting it be the first thing cut when the agenda is full. Protect it by putting it first rather than last.</p>" },
            { label: "Rotating host", body: "<p><strong>What it is:</strong> a different person each time, following a shared one-page outline: what we are looking at, why it matters to our work, two questions, what we might do differently.</p><p><strong>What it costs:</strong> about thirty minutes of preparation per host, a few times a year.</p><p><strong>What breaks it:</strong> an outline that only the original host understands, and a rota that quietly returns to the most willing person.</p>" },
            { label: "Paired to a decision", body: "<p><strong>What it is:</strong> choosing the module that matches something the team is about to do — a notice being rewritten, a contract being renewed, a partnership meeting being planned.</p><p><strong>What it costs:</strong> a little planning ahead, and the discipline to choose relevance over novelty.</p><p><strong>What breaks it:</strong> drifting into whatever is newest in the catalogue, at which point the connection to the work is gone and so is the reason to come.</p>" },
            { label: "Shared finds", body: "<p><strong>What it is:</strong> a simple shared place where anyone can drop one thing they found, with one sentence about who it is for and why it is worth the time.</p><p><strong>What it costs:</strong> almost nothing, if the one-sentence rule holds.</p><p><strong>What breaks it:</strong> volume without judgment. Ten links a week with no explanation is the same as no links at all, and it buries the two that mattered.</p>" },
          ] },
          { type: "sorting", id: "ipe-38-3-sort", heading: "Sustains it, strains it, or ends it", categories: ["Sustains the rhythm", "Strains the rhythm", "Ends the rhythm"], items: [
            { text: "Twenty-five minutes at the start of a meeting the team already holds.", category: "Sustains the rhythm" },
            { text: "One person prepares every session because they are the one who cares most.", category: "Strains the rhythm" },
            { text: "Attendance is noted and mentioned in one-to-one meetings.", category: "Ends the rhythm" },
            { text: "The host rotates, using a shared one-page outline.", category: "Sustains the rhythm" },
            { text: "The session is always at noon, and three part-time staff can never attend.", category: "Strains the rhythm" },
            { text: "A written summary lets anyone take part who could not be there live.", category: "Sustains the rhythm" },
            { text: "The slot is the first thing cut whenever the agenda is full.", category: "Ends the rhythm" },
            { text: "The material is chosen to match a decision the team is about to make.", category: "Sustains the rhythm" },
          ] },
          { type: "flashcards", heading: "Design choices worth making on purpose", cards: [
            { front: "How long?", back: "<p>Twenty to thirty minutes, attached to something that already exists. Long enough for one idea and a real exchange, short enough to survive a bad month.</p>" },
            { front: "Who hosts?", back: "<p>Anyone, in rotation, with a shared outline. If only one person can host it, you have a personal practice rather than a team one.</p>" },
            { front: "When?", back: "<p>Not always the same hour. Alternate, or offer a second way in. A fixed slot decides who belongs without ever announcing that it is doing so.</p>" },
            { front: "What material?", back: "<p>Whatever matches a decision the team is about to make. Relevance is what carries a rhythm through a busy quarter; novelty is not.</p>" },
            { front: "For how long?", back: "<p>Name a season and a check-in point. People can commit to something that has an end, and an honest review is easier than an indefinite obligation nobody can close.</p>" },
            { front: "Who else might be there?", back: "<p>Community co-designers, disabled advisors, interpreters and culturally specific organizations may be invited to shape or lead a session. They are partners, they are compensated for it, and they are not learners in this program.</p>" },
          ] },
          { type: "leaderMove", heading: "Give it away in the second month", control: "You control whether the second session is hosted by someone other than you, and whether a workable outline exists before you need it.", failure: "Do not host it well for a year. A rhythm that depends on your preparation ends when your calendar changes, and the team will read that ending as proof that this kind of thing does not last here.", next: "Write the one-page host outline now, ask a colleague to run the next session, and be present as a participant rather than as the person in charge of it." },
          { type: "knowledgeCheck", id: "ipe-38-3-check", question: "A team's learning half-hour is always held at noon. Three part-time staff and two staff on early hours have never attended. Which response best fits the design reference this curriculum uses?", options: [
            { text: "Keep the slot, since it is the same for everyone and the majority can attend.", correct: false },
            { text: "Alternate the time and add a written way to take part, so that more than one route in exists by design rather than by request.", correct: true },
            { text: "Ask the five staff to let their supervisor know if they want the time changed.", correct: false },
            { text: "Record the session and make the recording available to anyone who asks for it.", correct: false },
          ], feedbackCorrect: "Yes. Multiple ways to engage, built in from the start rather than granted on request, is the core of the design reference — and it removes the need for anyone to explain their schedule.", feedbackIncorrect: "A single option that is identical for everyone is not the same as one that works for everyone. Asking excluded staff to request a change puts the cost on the people already carrying it, and access offered only on request is a backstop rather than a design." },
          { type: "statement", body: "Private reflection, for you alone and collected nowhere: whose week does your team's schedule assume? Think about start times, meeting hours, deadlines and the moments when decisions actually get made, and notice who would have to ask for an exception to be fully present." },
        ],
      },
      {
        id: "ipe-38-4",
        number: 4,
        title: "Your team learning rhythm and resource-sharing plan",
        summary: "One page the team can write together: what you will do, who hosts, how to take part another way, what gets shared, and what this plan will never record.",
        minutes: 11,
        learning: {
          objective: "Write a one-page team learning rhythm and resource-sharing plan that names the practice, the host rotation, a second way to take part, and what is deliberately not recorded.",
          takeaways: [
            "Optional in writing and observed in practice is coercion with better manners. What makes optional true is structural: no attendance record, no reflection collection, a real second route in, and no place anywhere that non-participation shows up.",
            "A plan that says what it will not do is more reassuring than a plan that promises good intentions, because the next supervisor inherits the structure rather than the promise.",
            "Resource sharing works on one rule: one sentence saying who it is for and why it is worth their time. Keep original sources intact and describe them accurately rather than replacing them with a summary.",
            "End a rhythm on purpose when it has done its work. A practice that is quietly allowed to die teaches the team that these things do not last; one that is closed with a short review teaches the opposite.",
          ],
          evidence: "A scenario about a staff member privately asking whether declining will be noticed, a completed one-page plan with a host rotation and a second route in, and a knowledge check on what makes optional true.",
          appliedNextStep: "Draft the one-page plan for your own team, then take it to them as a draft they can change — including the right to say that the whole thing is not worth doing right now.",
        },
        scenario: {
          context: "A DSD supervisor drafts a monthly team learning rhythm and shares it as optional. Two days later, a staff member stops by privately and asks whether choosing not to take part will be noticed in her performance review.",
          prompt: "How should the supervisor handle this?",
          options: [
            { label: "Reassure her that it will not be noticed, and thank her for asking.", response: "The reassurance is sincere and it is also unverifiable. She asked about the structure, not about this supervisor's intentions — and the next supervisor will inherit the structure, not the promise. Answering only her also leaves everyone else with the same unanswered question." },
            { label: "Treat the question as information about the design: put in writing what is and is not recorded, separate this plainly from required training and from performance review, remove any place where non-participation would be visible, and say the same thing to the whole team rather than only to her.", response: "This is the right response because it changes the structure rather than offering an assurance. It also answers the question for the people who did not feel safe enough to ask it, which is usually most of them.", recommended: true },
            { label: "Raise it at the next team meeting and ask whether anyone else shares the concern.", response: "This asks people to voice a worry about their supervisor's plan, in front of their supervisor and their colleagues. Silence will be read as agreement, and the one person who did speak up privately has now had her question made public without her agreeing to it." },
          ],
        },
        transfer: {
          prompt: "What in your current routines would show that someone had not taken part?",
          options: [
            "Check whether attendance appears in any note, list or summary you keep",
            "Check whether your one-to-one meetings ask about it, even informally",
            "Check whether the people who take part are the ones you think of first for opportunities",
            "Write the sentence you will say to the whole team about what is not recorded",
          ],
        },
        blocks: [
          { type: "text", heading: "Making optional true", body: "<p>Most teams have been told that something is optional and learned that it was not. The word has been worn thin, and a staff member who hears it applies a reasonable discount. The repair is not a more emphatic promise. It is structure: things that are true about the design whether or not the current supervisor is thoughtful, and that a new supervisor cannot quietly reverse.</p><p>That means writing down the negative space. A plan that says what will happen is ordinary. A plan that also says what will not happen — no attendance list, no collection of anything anyone writes, no mention of participation in performance conversations, no effect on assignments or opportunities — does something a promise cannot. It gives a staff member a sentence they can point to, and it gives the next person in your chair a standard to inherit.</p><p>The other half of the page is sharing. Most teams already share resources badly: a stream of links with no explanation, which buries the two that mattered. One rule fixes most of it. Anything shared carries one sentence saying who it is for and why it is worth their time. Keep the original source intact and describe it honestly rather than quietly replacing it with your own summary, and say plainly when something is required reading and when it is simply available.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A team learning rhythm and resource-sharing plan", summary: "One page a team writes together, naming the practice, who carries it, how else to take part, what gets shared, and what will never be recorded.", fields: [
            { label: "The practice and its frequency", value: "Twenty-five minutes at the start of our monthly team meeting, on material connected to something we are about to decide. Time is work time and does not have to be made up." },
            { label: "Hosting and rotation", value: "A different host each month from a volunteer rota, using the shared one-page outline: what we are looking at, why it matters to our work, two questions, what we might do differently. The supervisor hosts no more than twice a year." },
            { label: "Taking part another way", value: "The host posts a half-page note and the two questions within a day. Anyone can respond in writing, at any hour, or not at all. The slot alternates between morning and midday so it is not always built around one kind of schedule." },
            { label: "What gets shared, and where", value: "One shared space. Anything posted carries one sentence naming who it is for and why it is worth their time. Original sources stay intact and are described accurately. Required reading is labeled as required; everything else is simply available." },
            { label: "What this plan does not do", value: "No attendance is recorded. Nothing anyone writes in a reflection is collected, read or repeated. Participation is not mentioned in performance conversations, is not a factor in assignments or opportunities, and appears in no list anywhere. Completion counts toward no DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception." },
            { label: "Season, check-in point and how it ends", value: "Runs for one season. At the check-in we ask three questions: is it still connected to our work, is there more than one real way in, and is it still worth the time. If the answer is no, we close it on purpose and say what we learned." },
          ], action: "Copy the six fields, fill them in as a draft, and take the draft to your team as something they can change — including the option of deciding that now is not the time." },
          { type: "list", heading: "Five signals that make optional true", ordered: true, items: [
            "There is no list. Not a roster, not a note in a file, not a recollection you draw on later.",
            "Declining is met with nothing at all — no follow-up, no gentle check-in, no second invitation aimed at one person.",
            "The supervisor is sometimes absent, and the session runs perfectly well without them.",
            "A second, genuinely equivalent way to take part exists, and is used by enough people to be normal rather than exceptional.",
            "Nobody is named in any summary, upward or sideways, for taking part or for not taking part.",
          ] },
          { type: "accordion", heading: "Questions you will be asked, and answers that hold up", items: [
            { title: "Does this count toward my required training?", body: "<p>No. This is voluntary learning and it is separate from the department's required training. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception. Say this early and in writing, because a staff member who is unsure will treat everything as mandatory and nothing as safe.</p>" },
            { title: "Will anyone see what I wrote?", body: "<p>No. Reflection prompts are private and nothing written in them is collected, stored against a person or read by anyone. If a colleague chooses to share a thought in a session, that is their choice in that moment and it does not become a record.</p>" },
            { title: "What if my team is too busy this quarter?", body: "<p>Then say so plainly and pause it with a date to look again, rather than letting it fade. A stated pause keeps the practice credible. A slow disappearance teaches everyone that commitments here are decorative.</p>" },
            { title: "Can we bring in people from outside the division?", body: "<p>Yes, and this is often where the most useful sessions come from. Community co-designers, disabled advisors, families, interpreters and culturally specific organizations can shape or lead a session. Compensate them, be specific about what you are asking for, give them enough notice, and tell them afterwards what changed. They are partners in this work, not participants in staff training.</p>" },
            { title: "How do I know it is working?", body: "<p>Look at the work. A rewritten notice, a changed agenda, a question raised in a contract discussion that nobody was asking a season ago. If you cannot point to anything in the work after a full season, that is worth knowing — and it is a reason to change the design, not a reason to start counting people.</p>" },
          ] },
          { type: "leaderMove", heading: "Write down what you will not do", control: "You control whether the plan states its limits in writing, which is the only part of it that outlives your intentions.", failure: "Do not rely on the team trusting you. Trust is not transferable, and the person who reads this plan after you leave will follow what it says rather than what you meant.", next: "Add the paragraph naming what is not recorded to your draft, read it out to the team when you share it, and keep it in place when the plan is next revised." },
          { type: "knowledgeCheck", id: "ipe-38-4-check", question: "A supervisor wants a team learning rhythm that is genuinely optional. Which combination does the most to make that true?", options: [
            { text: "Saying clearly at each session that participation is voluntary, and thanking people who attend.", correct: false },
            { text: "No attendance record, nothing written collected, an equivalent second way to take part that people actually use, and no place in any routine where not taking part would show.", correct: true },
            { text: "Keeping a private list of who attends so that support can be offered to those who do not.", correct: false },
            { text: "Making the sessions short enough that attending costs almost nothing.", correct: false },
          ], feedbackCorrect: "Yes. Optional is a property of the structure, not of the announcement. Each of those four removes a place where a choice could be observed or held against someone.", feedbackIncorrect: "Ask what a cautious staff member would check. Not what was said at the session — whether a record exists, whether anything they wrote travels, whether there is a real alternative, and whether declining shows up anywhere at all." },
          { type: "statement", body: "Private reflection and one commitment, kept by you and collected nowhere: which single condition — time, permission, relevance, visibility or safety — is weakest on your team right now? Write the one change you will make before the next month is out, and the name of the colleague who will ask you whether you made it." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Sustaining voluntary learning",
    subtitle: "One page for supervisors and leaders keeping learning alive without counting people",
    quote: "Learning that nobody is required to do needs conditions, not enforcement.",
    use: {
      purpose: "Keep the conditions in view when you are deciding how to support learning on your team, what to report upward, and how to design a rhythm that will still be running at the end of a hard quarter.",
      remember: [
        "Five conditions hold voluntary learning up: protected time, stated permission, relevance to current work, visibility, and safety.",
        "Requiring it, counting it and comparing teams each change what the learning is. Required training belongs in its own system, named plainly as required.",
        "Report changes in the work, not who took part. A small unit is a person, and intention does not travel with a number.",
        "Small, rotating, connected to a real decision, with more than one way in, and a season with a check-in point.",
        "Optional is a property of the structure: no list, no collection, a real second route, and nowhere that declining shows up.",
      ],
      doNext: "Name the weakest of the five conditions on your team, change that one thing this month, and ask someone other than you to host the next session.",
    },
    sections: [
      {
        heading: "When learning has gone quiet",
        items: [
          "Ask which of the five conditions went missing before changing anything about the offering.",
          "Say out loud, and then in writing, where the time comes from and that using it is normal.",
          "Attach one module to a decision the team already has to make this month.",
          "Resist requiring, counting or comparing — each fixes the number and damages the practice.",
        ],
      },
      {
        heading: "When someone asks whether it is working",
        items: [
          "Lead with what changed in a document, a process or a meeting, and what prompted it.",
          "Offer grouped pictures large enough that nobody can be picked out; refuse breakdowns by small unit.",
          "Say plainly what is not collected: individual use, attendance, and anything written in a reflection.",
          "Offer the better question you would like to be asked next quarter, and what you would need to answer it.",
        ],
      },
      {
        heading: "When you design the rhythm",
        items: [
          "Twenty-five minutes on a meeting that already exists, placed first on the agenda rather than last.",
          "Rotate the host from the second session, using a shared one-page outline anyone can follow.",
          "Build a second way in — a short written note and open questions — rather than granting it on request.",
          "Name the season and the check-in point, and close the practice on purpose if it has done its work.",
        ],
      },
      {
        heading: "When you share resources",
        items: [
          "One sentence with everything you share: who it is for, and why it is worth their time.",
          "Keep original sources intact and describe them accurately instead of replacing them with a summary.",
          "Label what is required as required; say plainly when something is simply available.",
          "Invite community co-designers, disabled advisors and culturally specific organizations to shape or lead sessions, compensate them, and tell them afterwards what changed.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Supervisors and managers, who decide in practice whether learning time is permitted, who hosts, when the session is held, and whether taking part is ever noticed — a good place to start.",
          "Executive and senior leaders, who set what gets reported upward and therefore what every team below them will optimise for.",
          "Learning, communications and training staff, who build the material and the shared spaces the rhythms depend on.",
          "Quality, policy and program staff, who hold the real work a session can be attached to, and who see first when something in practice has changed.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "Leading a reflective DSD team",
          "Inclusive workforce and team culture",
          "Inclusive learning and knowledge design",
          "Leading difficult dialogue",
          "Quality, complaints, and incident learning",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage built in from the start, culturally responsive material, and learning that is accessible by construction rather than by later request." },
    { title: "CAST, Universal Design for Learning Guidelines", href: "https://udlguidelines.cast.org/", note: "The engagement, representation, and action and expression framework behind the second route into a session and the choice not to rely on a single time slot or format." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the standard on ongoing education and training for the workforce at every level — the obligation this module tries to meet without coercion." },
    { title: "Minnesota Department of Human Services, Content and writing guidelines", href: "https://mn.gov/dhs/digital-showcase/content-guidelines/", note: "The department's own editorial guidance on first-read understanding, descriptive sentence-case headings and familiar terms — applied here to the one-sentence rule for anything shared with colleagues." },
    { title: "PlainLanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Guidance on audience, organization and useful headings, used in this module for the host outline and the half-page note that carries a session to people who could not attend." },
    { title: "W3C Web Accessibility Initiative, Planning and managing web accessibility", href: "https://www.w3.org/WAI/planning/", note: "Practical guidance on sustaining accessibility as an ongoing organisational practice with named responsibility and review points, rather than a one-time project." },
    { title: "Section508.gov, Manage an accessible program", href: "https://www.section508.gov/manage/", note: "Federal guidance on running an accessibility program over time, including workforce training, shared responsibility and periodic review — the operational parallel to a learning rhythm that has to outlast its founder." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's advisory council on disability policy, access and rights, and a starting point for identifying disability-led organizations to invite and compensate as co-designers or session leaders." },
  ],
};

export default pack;
