import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Complex systems · Module 23: LGBTQIA2S+ inclusion and privacy.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-23-lgbtqia2s-inclusion-privacy",
    indexNumber: 1165,
    seriesLabel: "Intercultural Practice and Equity · Complex systems",
    title: "LGBTQIA2S+ Inclusion and Privacy",
    subtitle: "Identity information does not behave like the rest of an administrative record. Four lessons on what the division asks, what it keeps, who can see it, and how a form, a policy or a message can include people without exposing them.",
    scope: "For internal DHS and DSD staff whose work shapes what the division asks, keeps, publishes and shows: communications, training and learning-design staff; data, research, evaluation and analytics staff; policy, program and operations staff; quality and performance staff; contracts, grants and procurement staff; community engagement staff; administrative and support staff; supervisors and managers. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. You are never asked to disclose your own identity, relationships or experiences. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota examples, scenarios, sorting and flashcard practice, private reflection prompts, and an inclusion and privacy review sheet you can copy into your own work",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/equal-opportunity-employment.jpg",
    coverAlt: "A woman reviews an employment packet at a table.",
    introTranscript: "Most of what a public record holds is ordinary and correctable. A few fields are not. Information about a person’s identity, relationships or household can change how they are treated by a relative, a housemate, a support worker, a landlord or an employer, and it cannot be taken back once it has moved. This module is about the part of that risk the division controls: the questions we add to forms, the notices we mail, the fields a record can and cannot hold, the photographs and examples we publish, and the reports we release. It ends with a five-line review you can run over one real document in about an hour, and a fix you can make without anyone’s permission.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Explain why identity information carries risk that most administrative information does not, and name what a disclosure can set in motion for someone who relies on services.",
        "Apply five questions to any proposal to collect identity information, before a field is added to a form, a survey or a system.",
        "State what the Minnesota Government Data Practices Act requires when the state asks a person for private information about themselves, and name the offices that decide the formal questions.",
        "Distinguish representation, exposure and exclusion in a public communication, a photograph, a training example or a policy definition of family.",
        "Complete an inclusion and privacy review of one real form, policy or message, make the fix inside your own step, and route the rest to a named owner.",
      ],
      evidence: [
        "Four worked scenarios drawn from survey design, record design, public communications and a document review, each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates a question worth asking from one that needs a different route, and representation from exposure and exclusion.",
        "A completed five-line review sheet for one real document, kept with the document rather than in a personal file.",
      ],
      appliedNextStep: "Choose one form, policy or message you can actually change. Run the five review lines over it, fix what sits inside your own step, and take the rest to the named owner with a specific ask and a review point.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in the Minnesota Government Data Practices Act, in how the division’s data on individuals is classified, or in Minnesota Department of Administration data practices guidance",
        "A change in the Minnesota Human Rights Act or in federal civil rights guidance affecting protected characteristics, records or public communications",
        "Feedback from paid community advisors, disabled Minnesotans or staff that an example here misstates the risk a disclosure actually carries",
      ],
      relatedDoor: "Formal decisions about data classification, the notice given when the state collects private information, record and system design, personnel records, public data requests and discrimination complaints belong to the responsible DHS data practices, privacy, human resources, equal opportunity and legal offices, and to the Minnesota Department of Human Rights; this module prepares the review and the ask, it does not classify data or decide a complaint.",
      toolkitQuestion: "If the person this record describes read every field in it tomorrow, and so did someone they have not chosen to tell, what would this design have cost them?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-23-1",
        number: 1,
        title: "Why this information is different",
        summary: "Most of what a record holds is dull and correctable. A few fields are neither. This lesson is about what makes identity information behave differently, and what a disclosure sets in motion for someone who depends on a service.",
        minutes: 11,
        learning: {
          objective: "Explain why identity information carries risk that most administrative information does not, and name at least four consequences a disclosure can set in motion for someone who relies on disability services.",
          takeaways: [
            "Most administrative information is reversible. A wrong address gets corrected. A disclosure cannot be taken back, and the person, not the division, lives with wherever it travels.",
            "Disclosure is rarely one decision. It is a calculation a person repeats in every new room: a shift change, a new case manager, a team meeting, a family visit, a county office lobby.",
            "Chosen family is often the real support network. A policy that recognizes only legal relatives locks the people who actually show up out of a planning meeting, a notice or a decision.",
            "Intersection changes the stakes. Someone who needs daily support, shares a home with staff, and has a guardianship or supported decision-making arrangement has far less control over who knows what than the person designing the form usually imagines.",
            "“We treat everyone the same” is the most common form of Minimization in this work. It sounds fair, and it quietly assumes the risk of being known costs everyone the same.",
          ],
          evidence: "A scenario about a quality survey that would add identity questions, and a knowledge check on how a policy definition of family decides who gets into the room.",
          appliedNextStep: "Pick one record, form or routine message your unit touches. Write down every person who can see it in a normal week, including people outside the division. Most lists come out longer than expected.",
        },
        scenario: {
          context: "A DSD quality unit is redesigning the experience survey it sends to people receiving waiver services. A staff member proposes adding questions about sexual orientation and gender identity so the unit can finally show whether satisfaction differs. The survey is mailed to the home, returned by mail or completed by phone with the person’s own case manager, and results are reported by county.",
          prompt: "What has to be settled before those questions go in?",
          options: [
            { label: "Nothing further. The questions are standard on other surveys, and using the same wording lets the unit compare results.", response: "Borrowing a question does not bring its conditions with it. Here the answer travels through a household mailbox, sometimes through the person’s own case manager, and out into a county report where a small count can identify somebody. The conditions decide whether the question is safe, not the wording." },
            { label: "Why the unit is asking and what will change because of the answers; whether the survey can be completed privately rather than through the person’s own case manager; whether an answer is genuinely optional with no consequence; who can see it; and whether county-level reporting could identify a single respondent.", response: "This is the work, and each of the five is answerable. Any one left open is a reason to wait. Asking is not the problem. Asking without settling the route, the audience and the reporting is.", recommended: true },
            { label: "Drop the questions. Identity information is too sensitive for a survey that goes to people’s homes.", response: "Understandable, and it carries its own cost. With no information at all, the unit can only say it has not seen a difference, which is the very thing it set out to test. The usable answer is almost always a different route — a private channel, a stated purpose, real optionality, reporting at a level that protects people — rather than silence." },
          ],
        },
        transfer: {
          prompt: "Where in your own work does information about a person travel further than the person would expect?",
          options: [
            "Name one record, notice or report you touch, and list everyone who can see it in a normal week",
            "Mark the line on that list where the person would be surprised",
            "Write down who owns the step where the surprise starts",
          ],
        },
        blocks: [
          { type: "text", heading: "What makes this information behave differently", body: "<p>Most of what a public record holds is ordinary and fixable. A wrong address is corrected. A mistyped date is amended. The person is mildly annoyed, and the work moves on.</p><p>A few fields do not behave that way. Information about a person’s sexual orientation, gender identity, relationships or household can change how they are treated by a relative, a housemate, a support worker, a landlord, an employer or a neighbor. It cannot be corrected back. Once it has moved, the person carries the result, not the unit that collected it.</p><p>That asymmetry is the whole subject of this module. It is not an argument for collecting nothing, and it is not permission to collect freely. It is a reason to know precisely what you are asking, why, who will see it, how long it stays, and what happens to the person if it reaches someone they did not choose to tell. Those questions have answers. Most of the trouble in this area comes from adding a field before anybody worked them out.</p>" },
          { type: "text", heading: "Where this program stops", body: "<p>The 2S in the acronym stands for Two-Spirit, a term that belongs to Native American communities and carries meanings this program is not the right author for. Anything involving Two-Spirit people, tribal human services, or communication and consultation with Tribal Nations goes first to the Department of Human Services offices that handle tribal matters and to the Office of Indian Affairs. That is a standing deference, not a section waiting to be finished, and this program will not close it on its own.</p>" },
          { type: "accordion", heading: "Four things a disclosure can set in motion", items: [
            { title: "At home, and in shared settings", body: "<p>Many people who use disability services live with support staff, housemates or family. A notice on a kitchen table, a call taken on speaker, a schedule pinned to a fridge: each is a room where information can arrive ahead of the person’s decision to share it. Shift changes multiply it. The person told one worker, and the record told the rest.</p>" },
            { title: "Inside the service relationship itself", body: "<p>Someone who depends on daily support has a strong reason not to risk the relationship with the people who provide it. That is not timidity about a rule; it is a realistic reading of who helps them get out of bed. It is also why “nobody has ever raised this with us” is weak evidence of anything.</p>" },
            { title: "In a record that outlives the moment", body: "<p>A note travels. It moves to a new case manager, a new provider, a quality review, an audit file, a public data request. Whoever wrote it is usually gone by then, and the context went with them. Write anything about a person as though they will read it, because many of them eventually do.</p>" },
            { title: "In a small place", body: "<p>In a county where a program serves a few dozen people, a category with two people in it is a name. Greater Minnesota changes what counts as identifiable, and a report that protects people statewide can expose someone locally.</p>" },
          ] },
          { type: "flashcards", heading: "Words worth using carefully", cards: [
            { front: "Disclosure", back: "<p>A person choosing to tell someone about their identity or relationships. It belongs to the person. A record, a notice or a hallway conversation can take that choice away without anyone deciding to.</p>" },
            { front: "Outing", back: "<p>Identity information reaching someone the person did not choose to tell. It usually happens through ordinary routines: a mailed notice, a shared voicemail, a meeting roster, a photograph caption, a note read aloud.</p>" },
            { front: "Chosen family", back: "<p>The people who actually do the work of family: partners, friends, former partners, housemates, community elders. For many people they are the whole support network. For some, they are the only one.</p>" },
            { front: "The name a person uses", back: "<p>Not a nickname and not a preference. It is the name on the door, in the room and in the person’s own life. A record that holds only a legal name pushes it into a note field, where it gets missed.</p>" },
            { front: "No answers in a field", back: "<p>Tells you nothing about who is there. It usually tells you something about how safe the question felt.</p>" },
          ] },
          { type: "leaderMove", heading: "Design for the person who cannot afford to be known", control: "You control whether the default design assumes that being known is free, and treats everyone for whom it is not as an exception to sort out later.", failure: "Do not build the process for the person who is comfortable answering and then bolt on a workaround for everyone else. The workaround is usually where the exposure happens.", next: "Before the next form, notice or survey leaves your unit, name the person for whom that document is riskiest, and check what the design does to them." },
          { type: "quote", text: "People assume the risk is one big dramatic thing. It is not. It is somebody mentioning it at shift change, and then a worker I have never met knowing before we are introduced.", cite: "Composite perspective from a person receiving services, illustrative" },
          { type: "statement", body: "A private reflection, for you alone. How might my role, authority or assumptions shape what I think is safe to ask? Who could be helped, burdened, excluded or misunderstood by the way this information moves? Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-23-1-check", question: "A planning meeting invitation says a person may bring “a family member or legal representative.” The person’s main support is a partner of many years who is not a legal relative. What is the most accurate reading?", options: [
            { text: "The invitation is correct as written; the person can ask for an exception if they want someone else in the room.", correct: false },
            { text: "The definition, not the person, is the barrier. Recognizing only legal relationships excludes the people who actually provide the support, and it forces the person to explain a relationship in order to be heard.", correct: true },
            { text: "The person should first add the partner as an authorized contact in the record so the invitation applies to them.", correct: false },
          ], feedbackCorrect: "Yes. The wording belongs to the division and the fix costs nothing: say who the person chooses to bring.", feedbackIncorrect: "Ask what the person has to do to get their own support into the room, and who wrote the rule that makes them do it." },
        ],
      },
      {
        id: "ipe-23-2",
        number: 2,
        title: "What you ask, and what happens to the answer",
        summary: "A field on a form is a promise about what happens next. This lesson covers the five questions that have to be answered before the field exists, and what the state already owes a person when it asks.",
        minutes: 11,
        learning: {
          objective: "Apply five questions to a proposal to collect identity information, and state what the Minnesota Government Data Practices Act requires when the state asks a person for private information about themselves.",
          takeaways: [
            "Five questions decide whether a field belongs on a form: why we are asking, what changes because of the answers, whether the answer is genuinely optional, who will see it, and how long it stays.",
            "Under the Minnesota Government Data Practices Act, information the government keeps about individuals is classified by law, and when the state asks a person to supply private information about themselves it must tell them why it is being collected, how it will be used, whether they may refuse, what happens if they answer or refuse, and who else may receive it.",
            "Optional has to be optional in practice. A blank that stops the form, a phone script with no way past the question, or an answer that changes how a worker treats the person is not a choice.",
            "Collecting nothing is also a decision with effects. It leaves the division able to say only that it has not seen a difference, which is a statement about the questions asked rather than about the people served.",
            "Small counts identify people. One or two people in a category in a county report is a name to anyone who lives there, whatever the cover of the report says.",
          ],
          evidence: "A scenario about fields switched on because a system offered them, sorting practice on when to ask, and a knowledge check on what the state has to tell a person when it collects private information.",
          appliedNextStep: "Take one identity question already in use in your unit’s forms, surveys or systems and try to answer the five questions about it. If you cannot answer one of them, you have found the work.",
        },
        scenario: {
          context: "A new records screen in a DSD program area includes optional fields for gender identity and pronouns, because the system supports them. Staff begin filling them in from conversation, without asking. A supervisor notices that the fields appear in a routine report sent to contracted providers, and that nobody can say who decided the fields would be used or what for.",
          prompt: "What is the first move?",
          options: [
            { label: "Tell staff to stop filling in the fields, and switch them off until further notice.", response: "It stops the flow, and it also removes the one thing that might have let people be addressed correctly. Switching a field off answers a question nobody has asked yet: what were these fields for?" },
            { label: "Leave the fields in place and add a line to the report telling providers to treat the information as confidential.", response: "An instruction to a downstream reader does not undo a disclosure, and it leaves the larger problem untouched. The information was recorded from conversation rather than asked for, so nobody agreed to anything." },
            { label: "Stop the flow into the provider report now, then settle the five questions before the fields are used again: the purpose, what changes because of the answers, how the person is asked and told it is optional, who sees it, and how long it is kept.", response: "This is the order that works. Close the live exposure first, then do the design work that should have come before the fields were switched on. It also gives staff something to hear other than “stop.”", recommended: true },
          ],
        },
        transfer: {
          prompt: "Which question already on one of your unit’s forms could you not explain to the person answering it?",
          options: [
            "Find one field and write the plain-language reason it exists",
            "Trace where its answers go, including any report that leaves the division",
            "Bring the field you could not explain to the person who owns the form",
          ],
        },
        blocks: [
          { type: "text", heading: "A field is a promise, not a container", body: "<p>A field on a form is not neutral. It is a promise that somebody thought about what the answers are for, that the answers are safe where they are going, and that the person filling it in knows what they are agreeing to. When a field arrives because a new system offered it, none of those promises has been made.</p><p>The five questions below are the design work, not a compliance step at the end, and for most fields they take about twenty minutes. Any one of them left open is a reason to wait rather than a reason to stop forever. The usual result is not “do not ask.” It is “ask differently”: a private channel instead of a mailed form, a stated reason in plain words instead of a bare field, or reporting at a level where no single person can be picked out.</p><p>There is a genuine cost on the other side too. A division that collects nothing about who its programs reach can only report that it has not seen a difference. That will not hold the first time somebody asks whether a program works as well for everyone, and it leaves the people most likely to be missed invisible in exactly the places where decisions are made.</p>" },
          { type: "list", heading: "The five questions, in the order they matter", ordered: true, items: [
            "Why are we asking? Name the decision, report or change the answers make possible. “It would be good to know” is not a purpose.",
            "What changes because of the answers? If nothing in the program would be done differently, the question collects risk and returns nothing.",
            "Is the answer genuinely optional? A person must be able to skip it, in every channel, without the form stopping and without being treated differently.",
            "Who will see it? Name them: this unit, a contracted provider, a county, a public report, an audit file, anyone who makes a data request.",
            "How long does it stay, and where does it stop? A field with no end point turns one moment’s answer into a permanent disclosure.",
          ] },
          { type: "accordion", heading: "What is already required, and who decides it", items: [
            { title: "The notice the state owes a person", body: "<p>When a state agency asks a person to supply private or confidential information about themselves, the Minnesota Government Data Practices Act requires a notice: why the information is being collected, how it will be used, whether the person may refuse, what happens if they supply it or refuse it, and who else is authorized to receive it. That is an obligation, not a courtesy. It is also exactly what a person needs in order to decide.</p>" },
            { title: "Classification is not a matter of preference", body: "<p>Government information about individuals is classified by law as public, private or confidential. A unit does not choose the classification because a field feels sensitive, and it cannot promise secrecy it has no authority to give. The responsible authority and the department’s data practices office make that determination. Ask them before designing around an assumption.</p>" },
            { title: "Information about staff travels a different route", body: "<p>Information about employees sits under personnel data rules and the department’s own human resources policies, not the route that applies to people receiving services. A staff member’s identity is theirs. A manager who is told something in confidence is not holding a record, and should not create one. Questions about personnel records go to human resources.</p>" },
            { title: "Discrimination is a separate question with a separate door", body: "<p>The Minnesota Human Rights Act lists sexual orientation and gender identity among its protected characteristics. Whether something amounts to unlawful discrimination is decided by the Minnesota Department of Human Rights and by the department’s equal opportunity and legal offices. It is not decided by a learning module, a workgroup or a supervisor’s reading of a policy.</p>" },
          ] },
          { type: "sorting", id: "ipe-23-2-sort", heading: "Ask it, do not ask it, or change the design?", categories: ["Safe to ask", "Do not ask it yet", "Change the design, not the question"], items: [
            { text: "A voluntary statewide experience survey explains why it asks about sexual orientation, says an answer is optional, and publishes results only at a level where no one can be picked out.", category: "Safe to ask" },
            { text: "A new intake screen includes a gender identity field because the system offers one, and nobody can say what the answers will be used for.", category: "Do not ask it yet" },
            { text: "A person’s used name is typed into a free-text note because the record holds only a legal name, so every notice prints the other name.", category: "Change the design, not the question" },
            { text: "A county-level breakdown would show a single person in one category, identifying them to anyone who knows the county.", category: "Change the design, not the question" },
            { text: "A grant application asks community organizations to report the identities of the people they served, with no explanation of who will see the list.", category: "Do not ask it yet" },
            { text: "A voluntary, anonymous staff experience survey asks about identity, reports only for groups large enough to protect individuals, and is run by a unit that cannot link answers to employment records.", category: "Safe to ask" },
          ] },
          { type: "leaderMove", heading: "Answer the five before the field goes live", control: "You control whether a question reaches a form with its purpose, its optionality, its audience and its end point already written down.", failure: "Do not let a field arrive because a system offers it or because another survey has it. A borrowed question does not bring its conditions with it.", next: "Write the five answers into the same document that requests the change, so the next person can read them without asking you." },
          { type: "statement", body: "A private reflection, for you alone. Whose expertise is missing from the decision to add this question? What would safety and accessibility mean here beyond a legal minimum? Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-23-2-check", question: "A unit plans to ask people receiving services an optional question about gender identity. Which combination best matches what the state has to tell the person?", options: [
            { text: "That the question is optional, and nothing more; the rest is internal business.", correct: false },
            { text: "Why the information is being collected, how it will be used, whether they may refuse, what happens if they answer or refuse, and who else may receive it.", correct: true },
            { text: "That the information will be kept confidential and will never be shared with anyone.", correct: false },
          ], feedbackCorrect: "Yes. That is the notice the Minnesota Government Data Practices Act requires when the state asks a person for private information about themselves, and it is also what the person needs in order to decide.", feedbackIncorrect: "A person deciding whether to answer needs the purpose, the use, the consequence either way, and the list of who else may see it. A blanket promise of secrecy is usually one the unit has no authority to make." },
        ],
      },
      {
        id: "ipe-23-3",
        number: 3,
        title: "Communications, representation and safety",
        summary: "A notice can out someone. So can a caption, a voicemail or a sign-in sheet. This lesson separates representation from exposure, and works on the wording, images, examples and contact routines that decide which one a message does.",
        minutes: 11,
        learning: {
          objective: "Distinguish representation, exposure and exclusion in a public communication, a photograph, a training example or a policy definition, and name the change that fixes each one.",
          takeaways: [
            "Representation is being visible in a way the person chose. Exposure is being visible in a way they did not. The difference is consent and control, not tone.",
            "Ordinary routines do most of the outing: mailed notices, voicemails on shared phones, meeting rosters, sign-in sheets, captions under photographs, a note read aloud in a room.",
            "Asking how a person wants to be contacted, and storing the answer where the next staff member will see it, is one of the cheapest safety measures the division has.",
            "Examples teach. A training case, a sample letter or a household diagram that only ever shows one kind of family tells staff what the normal case is, and turns everything else into something a person has to argue for.",
            "People invited to tell their story are co-designers and advisors doing professional work. They are paid for it, they approve exactly what is published, and they can withdraw it afterwards.",
          ],
          evidence: "A scenario about a report photograph and its caption, sorting practice on representation, exposure and exclusion, and a knowledge check on contact routines and record design.",
          appliedNextStep: "Take the last public-facing thing your unit produced — a notice, a page, a report, a slide deck — and mark every place a named or identifiable person appears and every place a family is described. Check which of those the person actually approved.",
        },
        scenario: {
          context: "A DSD program report is nearly final. It includes a photograph of a person who agreed to be in it, with a caption giving their first name, their county and the program they receive services through. The communications lead also wants to quote one sentence from an advisory group member about their partner. Both people said yes in a meeting several months ago.",
          prompt: "What should happen before the report goes out?",
          options: [
            { label: "Publish as planned. Both people agreed, and the report is stronger with real voices in it.", response: "Agreement in a meeting months ago is not approval of this caption, in this report, beside this program name. The caption is the part that discloses, and neither person has seen it." },
            { label: "Remove the photograph and the quote to be safe.", response: "That removes the risk and the people at the same time. A report with nobody in it is not more respectful, only emptier — and the advisory group member did want to be heard." },
            { label: "Go back to both people with the exact image, caption and quote as they will appear, say plainly what a reader could work out from them, confirm how each person wants to be identified, and record that they can withdraw later.", response: "This is what consent means for a publication: specific, informed, current and revocable. It usually takes one phone call, and it often produces a better caption than the draft.", recommended: true },
          ],
        },
        transfer: {
          prompt: "Where does a routine in your unit tell somebody something about a person before the person has?",
          options: [
            "List the ways your unit reaches people: mail, voicemail, text, portal, in person",
            "Ask which of those arrive somewhere other people can see or hear",
            "Add one line at first contact: how the person wants to be reached, and where that answer is stored so the next staff member sees it",
          ],
        },
        blocks: [
          { type: "text", heading: "Representation, exposure, exclusion", body: "<p>Three different things get discussed as though they were one. <strong>Representation</strong> is a person being visible in a way they chose: a quote they approved, a photograph they saw before it ran, an example built with paid advisors. <strong>Exposure</strong> is a person being visible in a way they did not choose, which is usually accidental and almost always produced by a routine rather than a decision. <strong>Exclusion</strong> is a person not appearing at all, or appearing only as the exception to a definition somebody wrote without them.</p><p>The fix for each is different. Exposure is fixed by changing a routine: what the envelope says, what the voicemail names, what the caption gives away, who is on the roster. Exclusion is fixed by changing a definition or an example: who counts as family, who may come to the meeting, which household the sample letter describes. Representation is not fixed at all — it is earned, by asking, paying, showing people the exact wording and letting them change or withdraw it.</p><p>None of this requires a communications team to become cautious. It requires the person who writes the caption to have been in the conversation, and the person who designs the notice to know what arrives at the front door.</p>" },
          { type: "tabs", heading: "Four ordinary places a message discloses", tabs: [
            { label: "The mailed notice", body: "<p>A letter naming a clinic, a program or a service arrives at an address the person shares. Envelopes get opened by whoever is standing there. Look at what the outside of the envelope says and what the first visible line says, and offer a contact route the person chooses.</p>" },
            { label: "The returned call", body: "<p>A voicemail on a household phone, a message that names a program, a call back at a time the person is not alone. Ask when and how it is safe to call, record the answer where the next person will see it, and follow it.</p>" },
            { label: "The room", body: "<p>Sign-in sheets, name badges, a roster on a screen, a note read aloud at a team meeting, a schedule pinned where housemates walk past. The room tells people things before the person does.</p>" },
            { label: "The caption", body: "<p>A first name, a county and a program name under a photograph can identify a person to anyone who knows them. Captions disclose more than images do, and they are usually written last, by someone who was never in the conversation.</p>" },
          ] },
          { type: "sorting", id: "ipe-23-3-sort", heading: "Includes, exposes or leaves out?", categories: ["Includes people", "Exposes someone", "Leaves people out"], items: [
            { text: "A report uses a composite example, written with paid advisors and approved by them, to show how a policy change reaches a household.", category: "Includes people" },
            { text: "A photograph of a named participant runs with a caption giving their county and the program they receive services through.", category: "Exposes someone" },
            { text: "A policy says a person may bring “a family member” to a planning meeting, and staff read that as a legal relative.", category: "Leaves people out" },
            { text: "An appointment reminder is left as a voicemail on a shared household phone, naming the clinic.", category: "Exposes someone" },
            { text: "A public notice offers three ways to be contacted and asks the person which one is safe to use.", category: "Includes people" },
            { text: "Every household example in a training deck is a married different-sex couple with children.", category: "Leaves people out" },
          ] },
          { type: "list", heading: "Wording changes that cost nothing", items: [
            "Write “the people you choose to bring” instead of “family member or legal representative.”",
            "Ask “who should be part of this planning?” rather than “what is your relationship to the applicant?”",
            "Offer contact choices instead of assuming the address on file: how would you like us to reach you, and is there a time or a way that does not work?",
            "Put the name a person uses into a field the record can hold, and make that the name that prints on the notice.",
            "Say what a public report will and will not show about a person, in the same plain words you used to ask.",
            "Replace the single family example in a training deck with two or three that are all treated as ordinary.",
          ] },
          { type: "quote", text: "The report said they had my consent. What I said yes to was a conversation. Nobody ever showed me the sentence with my county printed under it.", cite: "Composite advisory group member perspective, illustrative" },
          { type: "leaderMove", heading: "Let the person hold the disclosure", control: "You control whether a person can choose how they are named, pictured, quoted and contacted, and whether that choice is written somewhere the next staff member will actually see it.", failure: "Do not treat a yes given months ago, in a different room, about a different draft, as approval of the thing you are about to publish.", next: "Before the next publication or first contact, confirm the exact wording with the person and record the contact route they chose." },
          { type: "statement", body: "A private reflection, for you alone. Does this message make sense to someone who does not already know how the department works? Who could be exposed, burdened or misread by the way it arrives? Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-23-3-check", question: "A person tells an intake worker that a letter to their home address is not safe for them and asks to be reached by text. The record has one address field and no place for contact preferences. What is the useful response?", options: [
            { text: "Note the request in a free-text comment and trust the next worker to read it.", correct: false },
            { text: "Follow the request now, and raise the missing field as a record design problem with the owner of the system, because a preference stored where it can be missed will be missed.", correct: true },
            { text: "Explain that mailed notices are the official channel and ask the person to watch their mail more closely.", correct: false },
          ], feedbackCorrect: "Yes. Do the right thing today, and fix the reason it was hard, because the next person will not have heard the conversation.", feedbackIncorrect: "Two things need doing: honor the request now, and name the design that made honoring it depend on one worker’s memory." },
        ],
      },
      {
        id: "ipe-23-4",
        number: 4,
        title: "Review a form, policy or message",
        summary: "The practical part. Five lines you can run over one real document in about an hour, ending with a fix you can make yourself and an ask you can take to somebody else.",
        minutes: 11,
        learning: {
          objective: "Complete an inclusion and privacy review of one real form, policy or message, naming what it asks, where it could expose or exclude someone, the first fix and its named owner.",
          takeaways: [
            "Review the document a person actually receives, in the channel they receive it, not the version in the style guide.",
            "Three defects account for most of what a review finds: a question with no stated reason, a record that cannot hold something true about the person, and a definition that recognizes only some relationships.",
            "A finding is only useful when it names an owner and a first fix. “This is a problem” goes nowhere. “This line, this change, this person, by this point” moves.",
            "Fix the part inside your own step before the review goes anywhere. It needs nobody’s permission, and it is what makes the rest of the review credible.",
          ],
          evidence: "A scenario about reviewing an inherited form, a completed five-line review sheet for one real document, and a knowledge check on what makes a finding actionable.",
          appliedNextStep: "Run the five lines over one document you can change. Make the fix in your own step this month, and send the rest to the owners you named with a specific ask and a review point.",
        },
        scenario: {
          context: "You inherit a three-page application form your unit sends out. It asks for legal name only, marital status, and “relationship to applicant” for anyone else listed. It requires a signature from the applicant or a legal representative, and the accompanying notice explains none of the questions. Nobody currently in the unit wrote it, and the system behind it is shared with two other program areas.",
          prompt: "Where does your review start?",
          options: [
            { label: "With the system owner, since most of the fields are shared and cannot be changed by your unit alone.", response: "That conversation will be needed, and starting there usually stalls. You do not yet know which fields matter, and a request to change a shared system with no specific finding behind it rarely moves." },
            { label: "With a full rewrite of the form in plain language, which fixes the wording problems in one pass.", response: "Plain language is a real improvement, and it is a different review. A perfectly clear question that nobody can explain the purpose of is still a question with no purpose." },
            { label: "With the document as a person receives it: list every question and the reason for each, mark where somebody could be exposed or left out, note what the record cannot hold, and separate what you can change from what the system owner must.", response: "This is the order that produces something usable. It gives you a short list of specific findings, a fix you can make yourself, and a request to the system owner that names a field, a reason and a date.", recommended: true },
          ],
        },
        transfer: {
          prompt: "Which document will you run this on, and who will ask you what you found?",
          options: [
            "Name the form, policy or message and the day you will review it",
            "Name the colleague or supervisor who will ask you about the result",
            "Write the fix you expect to find inside your own step, then check whether you were right",
          ],
        },
        blocks: [
          { type: "text", heading: "Review what the person receives", body: "<p>Review the thing a person actually gets. Not the template in the style guide, not the screen a staff member sees, and not the policy that describes the form. The envelope, the first paragraph, the questions in order, the signature line, the way it arrives and the way it has to be returned.</p><p>Five lines are enough. What you are reviewing and who receives it. Every question it asks, with the reason for each one written beside it. Where a person could be exposed, burdened or left out. What the record can hold, and what it forces staff to bury in a note. Then the first fix, a named owner, and a point at which somebody will check.</p><p>Most reviews come back with three or four findings, one of which sits inside your own step. Make that one. It turns the review from an opinion about somebody else’s work into a piece of work with a result already in it, and it is the part that needs nobody’s permission.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A review sheet for one form, policy or message", summary: "Five lines that turn a document you inherited into a short list somebody can act on.", fields: [
            { label: "What you are reviewing, and who receives it", value: "The three-page program application, mailed to the home address on file, returned by mail or in person, and read aloud by phone when a person asks." },
            { label: "Every question it asks, and the reason for each one", value: "Legal name — needed to establish eligibility. Marital status — no reason anyone in the unit can state. Relationship to applicant — used to decide who may be contacted, which is not what the wording asks." },
            { label: "Where a person could be exposed, burdened or left out", value: "Mailed to a shared address with the program name on the envelope. “Legal representative” excludes a partner who is the person’s actual support. No place for the name the person uses, so notices print the other one." },
            { label: "What the record can hold, and what it forces into a note", value: "One name field, one address field, no contact preference, no field for a supporter the person chooses. Staff currently write all three into a free-text comment the next worker rarely reads." },
            { label: "First fix, named owner, next review point", value: "Mine this month: take the program name off the envelope and add a contact-preference question to the cover letter. System owner: add a used-name field and a chosen-supporter field; ask by the agreed review point and record the answer." },
          ], action: "Copy the five lines, fill them in for one document you can actually change, make the fix inside your own step first, and send the rest to the owners you named with a date." },
          { type: "list", heading: "What a review usually finds", items: [
            "A question nobody can explain. It was inherited, and the reason left with whoever added it.",
            "A definition of family that recognizes legal relationships and nothing else.",
            "A record that holds a legal name and an address and nothing about how the person wants to be reached or who they want in the room.",
            "A channel with no alternative: mail only, phone only, portal only.",
            "A notice that names a program on the outside of the envelope.",
            "A report small enough that one person in a category can be recognized.",
            "A consent taken once, in general, and treated as permanent.",
          ] },
          { type: "accordion", heading: "When the fix is not yours", items: [
            { title: "Bring one finding, not the whole review", body: "<p>System and policy owners receive a great deal of general concern and very little they can act on. Bring the field, the wording, the effect on a person and the change you want. One specific ask travels further than a full report.</p>" },
            { title: "Bring the effect, not the frustration", body: "<p>“This form is bad” is a feeling. “This form has no field for the name a person uses, so every notice prints a name they do not use and staff are handling it in a comment field” is a defect with a cost attached.</p>" },
            { title: "Ask who else has to agree", body: "<p>Shared systems, legal review, data classification and public notices usually involve more than one office. Ask the owner who else signs off, and write that into the review so the next person does not start over.</p>" },
            { title: "Route the formal questions properly", body: "<p>Data classification and the wording of the notice given when the state collects private information go to the responsible authority and the department’s data practices office. Personnel questions go to human resources. Discrimination questions go to the department’s equal opportunity and legal offices and to the Minnesota Department of Human Rights. Anything involving Tribal Nations goes first to the Department of Human Services offices that handle tribal matters and to the Office of Indian Affairs.</p>" },
          ] },
          { type: "leaderMove", heading: "Fix your own line first", control: "You control the wording, the envelope, the contact question, the example and the reply inside your own step.", failure: "Do not send the whole review upward and wait. A review with no completed fix in it reads as a complaint.", next: "Make one change in your own step before the review leaves your desk, and say in the review what you already did." },
          { type: "statement", body: "A private reflection, for you alone. If harm or exclusion happened through a document like this one, what would accountability and repair actually require? How could the people most affected have shaped this document earlier, as paid co-designers rather than reviewers at the end? Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-23-4-check", question: "Which review finding is written so that somebody can act on it?", options: [
            { text: "The application form is not inclusive and should be updated.", correct: false },
            { text: "Question four asks marital status, and no one in the unit can state what the answer is used for. Owner: the program policy lead. First fix: remove the question or write the reason into the notice, by the agreed review point.", correct: true },
            { text: "Staff should be more aware of privacy when they handle this form.", correct: false },
          ], feedbackCorrect: "Yes. A line, a reason, an owner, a fix and a point at which somebody will check. That can move without you in the room.", feedbackIncorrect: "An actionable finding names the exact line, the effect, the person who owns it, the change and when it will be checked. Awareness is not a change to a document." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Inclusion and privacy in what we ask, keep and send",
    subtitle: "One page for anyone who writes a question, designs a record or sends a message",
    quote: "Ask what an answer costs the person before deciding the field is harmless.",
    use: {
      purpose: "Keep the five questions, the difference between representation and exposure, and the five review lines in view while you design a form, add a field, write a notice or prepare a report.",
      remember: [
        "Most administrative information is correctable. A disclosure is not, and the person carries the result rather than the unit that collected it.",
        "A field is a promise that somebody settled the purpose, the optionality, the audience and the end point. A borrowed question does not bring its conditions with it.",
        "When the state asks a person for private information about themselves, it owes them the reason, the use, whether they may refuse, what happens either way, and who else may see it.",
        "Chosen family is often the real support network. A definition that recognizes only legal relatives excludes the people who actually show up.",
        "Representation is visibility the person chose. Exposure is visibility they did not. The difference is consent and control, not tone.",
        "“We treat everyone the same” is Minimization in its most ordinary form: it assumes being known costs everyone the same.",
      ],
      doNext: "Run the five review lines over one document you can actually change, and make the fix inside your own step before the review goes anywhere.",
    },
    sections: [
      {
        heading: "The five questions before a field exists",
        items: [
          "Why are we asking? Name the decision, report or change the answers make possible.",
          "What changes because of the answers? If nothing would be done differently, the question collects risk and returns nothing.",
          "Is the answer genuinely optional, in every channel, with no consequence for skipping it?",
          "Who will see it? Name them, including providers, counties, public reports and audit files.",
          "How long does it stay, and where does it stop?",
        ],
      },
      {
        heading: "The review sheet, in short",
        items: [
          "What you are reviewing, and who receives it: the version the person gets, in the channel they get it.",
          "Every question it asks, and the reason for each one written beside it.",
          "Where a person could be exposed, burdened or left out: the envelope, the definition, the missing alternative.",
          "What the record can hold, and what it forces staff to bury in a note.",
          "First fix, named owner, next review point: one change, one name, one date already on a calendar.",
        ],
      },
      {
        heading: "Where a message discloses without meaning to",
        items: [
          "The envelope and the first visible line of a mailed notice.",
          "A voicemail on a shared phone that names a program or a clinic.",
          "Sign-in sheets, rosters, badges and schedules pinned where housemates pass.",
          "A caption under a photograph giving a first name, a county and a program.",
          "A county or program report small enough that one person in a category is recognizable.",
        ],
      },
      {
        heading: "Includes, exposes, leaves out",
        items: [
          "Includes: a quote the person approved as it will appear, with the option to withdraw it later.",
          "Exposes: anything published, mailed or spoken that a person did not see in its final form.",
          "Leaves out: a definition of family, representative or household written without the people it decides for.",
          "People invited to tell a story are paid co-designers and advisors, not learners in this curriculum and not illustrations.",
        ],
      },
      {
        heading: "Formal decisions, and the offices that make them",
        items: [
          "Data classification and the notice given when the state collects private information: the responsible authority and the department’s data practices office.",
          "Personnel records and a staff member’s own privacy at work: human resources.",
          "Discrimination questions: the department’s equal opportunity and legal offices, and the Minnesota Department of Human Rights.",
          "Anything involving Tribal Nations or tribal human services: the Department of Human Services offices that handle tribal matters and the Office of Indian Affairs, first and always.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Communications, training and learning-design staff, who decide what a notice says on the outside of an envelope, which example a training deck treats as ordinary, and whose photograph runs with which caption — a good module to go deeper with.",
          "Data, research, evaluation and analytics staff, who decide which fields exist, what a report can show without identifying somebody, and whether a question has a purpose it can actually serve — a good module to go deeper with.",
          "Policy and program staff, whose definitions of family, representative and household decide who gets into the room.",
          "Operations, quality and administrative staff, who run the contact routines where most disclosure actually happens.",
          "Supervisors and managers, who can give a shared field an owner and protect a staff member’s own privacy at work.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "History, disability, and public institutions",
          "Race, disability, and unequal outcomes",
          "Trauma-responsive public administration",
          "Power, conflict, and repair",
          "Ethical decision-making",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Statutes, chapter 13, Government Data Practices", href: "https://www.revisor.mn.gov/statutes/cite/13", note: "Minnesota’s law on government data, including how data on individuals is classified and the notice required when a state agency asks a person to supply private or confidential data about themselves." },
    { title: "Minnesota Department of Administration, Data Practices Office", href: "https://mn.gov/admin/data-practices/", note: "The state office that advises on data practices questions, classification and the responsibilities of a responsible authority." },
    { title: "Minnesota Department of Human Rights", href: "https://mn.gov/mdhr/", note: "The state agency that enforces the Minnesota Human Rights Act, which lists sexual orientation and gender identity among its protected characteristics." },
    { title: "National Academies of Sciences, Engineering, and Medicine, Measuring Sex, Gender Identity, and Sexual Orientation", href: "https://nap.nationalacademies.org/catalog/26424/measuring-sex-gender-identity-and-sexual-orientation", note: "Consensus guidance on when and how to ask identity questions in surveys and administrative records, including optionality, purpose and protecting respondents in small counts." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the governance, communication, data collection and community partnership standards used in this module." },
    { title: "plainlanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Practical guidance for writing questions, notices and letters people can act on, including how to explain why information is being requested." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota’s advisory council on disability policy, access and rights, including guidance for state agencies on accessible forms, notices and public processes." },
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials and accessible instruction." },
  ],
};

export default pack;
