import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Internal leadership · Module 35: Inclusive learning and knowledge design.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-35-inclusive-learning-design",
    indexNumber: 1177,
    seriesLabel: "Intercultural Practice and Equity · Internal leadership",
    title: "Inclusive Learning and Knowledge Design",
    subtitle: "Most internal guidance is written once and met a thousand times, by people in the middle of other work. Four lessons on building training, guidance, resource libraries and internal tools that are findable, readable and genuinely usable across roles.",
    scope: "For internal DHS and DSD staff who make the material other staff have to use: communications, training and learning design staff; policy and program staff who write guidance and work instructions; quality and performance staff; data, research and technology staff who document what they build; supervisors and leaders who ask for a resource and then decide whether it is finished; and administrative and support staff who keep the shared pages and templates alive. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota DSD examples, scenarios, sorting and flashcard practice, private reflection prompts, and a one-page review record you can fill in for a resource you already own",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/facilitators-guide.jpg",
    coverAlt: "A man facilitates a small training room at a whiteboard.",
    introTranscript: "A division produces an enormous amount of material for its own staff: guidance documents, work instructions, templates, short trainings, shared resource pages, onboarding packets. Almost all of it is written once, by someone who knows the subject well, and then met hundreds of times by people who do not, in the middle of something else. This module is about the distance between those two moments. It covers the three different ways internal material fails, what the design reference for this curriculum actually asks for, how a resource library stays findable and current instead of quietly filling with duplicates, and how to run a real review of something that already exists. It ends with a one-page review record you can copy into your own work.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Tell apart the three ways internal material fails — not found, not understood, not usable at the moment of need — and say which one a specific resource is failing.",
        "Apply the Minnesota Framework for Universal Multicultural Instructional Design and universal design for learning to a resource you are building, so more than one way of engaging works without anyone having to ask.",
        "Name the accessibility choices a communications, training or program person controls directly, and make them before a resource is released rather than after a complaint.",
        "Keep a resource library findable and current: one named owner, one current version, plain titles in the words people search, and a review point that actually arrives.",
        "Run an inclusive design review of one existing resource and record each finding with an owner, a first fix and a review point.",
      ],
      evidence: [
        "Four worked scenarios drawn from a guidance document nobody uses, a converted slide deck with a timed quiz, a resource page holding three versions of the same instruction, and a ninety-minute review.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates the design commitments a choice serves, and assigns real findings to the check that would catch them.",
        "A completed one-page review record for one existing resource, with findings, owners, first fixes and a next review point.",
      ],
      appliedNextStep: "Choose one resource your team already owns and other staff already use. Write down the last three questions people asked about it, find where each answer sits, and run the four checks in the review record on that one resource.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in ADA Title II, Section 504 or Section 508 requirements, or in the state's digital accessibility standard, that changes what an internal document, page or training must provide before it is released",
        "A change in how DHS or DSD writes, clears, publishes, stores or retires internal guidance, work instructions, templates and shared resource pages",
        "Feedback from compensated community reviewers, from disabled staff, or from the staff who use these resources daily that the checks described here miss the problems they actually run into",
      ],
      relatedDoor: "Formal decisions about accessibility conformance, required training, records retention and what is published on behalf of the department belong to the responsible DHS communications, accessibility, learning and records offices; this module helps you design and review the material before those decisions, not replace them.",
      toolkitQuestion: "Does this make sense to someone who does not already know how DHS works, and who would have to ask for help before they could use it at all?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-35-1",
        number: 1,
        title: "Published is not the same as usable",
        summary: "Internal material fails in three different ways that look identical from a distance. Naming which one you are looking at is most of the repair.",
        minutes: 11,
        learning: {
          objective: "Identify which of three failures a specific internal resource is experiencing — not found, not understood, or not usable at the moment of need — using evidence your team already has.",
          takeaways: [
            "Publishing is an event on one day. Usability is what happens for months afterward, to people who are in the middle of something else and have about a minute of patience.",
            "Repeat questions, private workarounds and out-of-date copies still in circulation are the most honest evidence you will ever get about where material fails. They are free, and most teams already have them.",
            "The three failures need different repairs. Not found is a naming and placement problem; not understood is a writing and structure problem; not usable at the moment of need is a format and length problem. Sending the announcement again repairs none of them.",
            "One version for everyone sounds like fairness and usually means one version shaped for readers most like the author. Treating sameness as fairness is the habit the continuum calls Minimization, and it is the most common design default in a large organization.",
          ],
          evidence: "A scenario about a guidance document that was published, announced and then re-announced; a knowledge check on what repeat questions actually tell you; and a role-by-role reading of the same page.",
          appliedNextStep: "Pick one resource your team owns. Write down the last three questions people asked about it, find where each answer sits in the material, and name which of the three failures is in play.",
        },
        scenario: {
          context: "A DSD program team finishes a new set of internal instructions for a changed service authorization step. It is a twenty-four page document with a table of contents, posted to the division's shared page and announced once in a division-wide message. Six weeks later the policy inbox is still answering the same three questions by hand, two teams are working from the old instructions, and one unit has built its own one-page cheat sheet that is almost right.",
          prompt: "What is the most useful first move?",
          options: [
            { label: "Send the announcement again and ask supervisors to confirm their teams have read it.", response: "This treats the problem as attention. Nothing about finding, understanding or using the document in the middle of a task has changed, so the same three questions will keep arriving — and the unit with its own cheat sheet already told you the document is the wrong shape for the moment of use." },
            { label: "Take the three repeat questions and the unit's cheat sheet as evidence, find where each answer sits in the document, and rebuild those parts as short direct answers placed where the work actually happens.", response: "This is the move. The repeat questions tell you what people cannot find or cannot understand; the homemade cheat sheet tells you what shape the answer needs to be. Both are evidence you already have, and both point at the material rather than at the reader.", recommended: true },
            { label: "Add a required acknowledgment so the division can confirm that everyone opened the document.", response: "Confirming that a file was opened measures traffic, not usability. It also converts a resource meant to help people work into a compliance step, which changes how staff relate to everything else the team publishes." },
          ],
        },
        transfer: {
          prompt: "Take one internal resource your team owns. Where would a person actually meet it, and what are they doing at that moment?",
          options: [
            "Name the resource and the exact task someone is in the middle of when they need it",
            "Write down the last three questions people asked about it, in their words",
            "Decide which of the three failures each question points at, and what the smallest repair would be",
          ],
        },
        blocks: [
          { type: "text", heading: "Three different failures that look the same from a distance", body: "<p>A division produces a large amount of material for its own staff. Guidance documents, work instructions, templates, short trainings, shared resource pages, onboarding packets, the note that explains the exception to the rule. Nearly all of it is written once, by someone who knows the subject extremely well, and then met many times over by people who do not, while they are in the middle of something else.</p><p>When that material is not working, the symptom is almost always the same. People ask anyway. They ask a colleague, they ask the inbox, they ask the person who wrote it, or they stop asking and build their own version. From a distance all of that looks like one problem, usually described as staff not reading what was sent. Up close it is three different problems, and they need three different repairs.</p><p><strong>Not found.</strong> The person never reached the material. The title uses the program's vocabulary rather than the words people search for, the page sits three levels down, nothing in the workflow points to it, or there are four similar files and no way to tell which is current. <strong>Not understood.</strong> The person reached it and could not follow it. The structure is legal or chronological rather than task-based, the answer is on page eleven of a document with no headings that name questions, or the language assumes a shared background the reader does not have. <strong>Not usable at the moment of need.</strong> The person found it, understood it, and still could not use it, because it is twenty-four pages and they had ninety seconds between a call and a deadline.</p><p>Sending the announcement again repairs none of these. It is worth saying plainly that this is not a staff attention problem. When several capable people fail at the same material in the same place, the material is the thing that has the defect.</p>" },
          { type: "tabs", heading: "Five people opening the same page", tabs: [
            { label: "Policy analyst", body: "<p>Reads the whole thing, needs the reasoning and the authority behind each requirement, and will notice if a citation is missing. This is usually the reader the document was written for, because it is usually the reader who wrote it.</p>" },
            { label: "Contract manager", body: "<p>Needs one clause-level answer and needs to be able to quote it to a party outside the division. Will not read twenty-four pages, and should not have to. Wants to know what changed since the last version and when it takes effect.</p>" },
            { label: "Administrative support specialist", body: "<p>Is the person most likely to be asked the question first, by phone, while doing three other things. Needs the answer as a short direct statement in ordinary words, reachable in under a minute, with a named person to send the hard cases to.</p>" },
            { label: "Data and research staff", body: "<p>Needs the definitions: which field, which population, which date rule, which exception. Will read carefully but only the part that defines something. Everything else in the document is noise for this reader.</p>" },
            { label: "New staff member in week two", body: "<p>Does not yet know which words are official terms and which are ordinary English, does not know what the abbreviations stand for, and cannot tell what is background and what is a requirement. This reader is the best test you have, and the easiest one to arrange.</p>" },
          ] },
          { type: "leaderMove", heading: "Write for the moment, not for the file", control: "You control what the reader meets first: the title, the first screen, the structure of the headings, and whether the first thing on the page is the answer or the history.", failure: "Do not build one long document and call the job finished because everything is in there somewhere. Completeness is a property of the file. Usability is a property of the encounter.", next: "Before you write anything new, write one sentence describing the moment a person will be in when they need it. Keep that sentence at the top of your draft until the draft is finished." },
          { type: "flashcards", heading: "Four questions to answer before you write anything new", cards: [
            { front: "Who exactly is this for?", back: "<p>Not everyone. Name the roles. If the honest answer is four different roles with four different needs, that is useful information: you are probably writing three things, not one.</p>" },
            { front: "What are they in the middle of?", back: "<p>The task, the pressure and the time available. A resource used during a phone call is a different object from one used while planning a quarter, even when the subject is identical.</p>" },
            { front: "What does the answer look like when it is short?", back: "<p>Write the shortest true answer first, in ordinary words. If it cannot be written short, the material is not ready. Everything else is support for that answer.</p>" },
            { front: "What does this replace?", back: "<p>Almost nothing is genuinely new. Name what this supersedes and arrange for the old version to be marked or removed, or you have added to the pile rather than fixed it.</p>" },
          ] },
          { type: "quote", text: "I made my own one-page version because I could not keep opening a twenty-four page file between calls. I know mine is not perfect. I also know three other people asked me for a copy of it.", cite: "Composite DSD staff perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-35-1-check", question: "A shared page holds a clear, well-written guide, and staff keep asking a colleague the same question instead. What does that most reliably tell you?", options: [
            { text: "Staff are not making the effort to read what has been provided.", correct: false },
            { text: "Something in the encounter is failing — the guide is not being found, not being understood, or not usable in the moment — and the repeat question tells you which one to look at first.", correct: true },
            { text: "The guide needs a stronger announcement and a reminder from supervisors.", correct: false },
            { text: "The question is too specific to be worth covering in general guidance.", correct: false },
          ], feedbackCorrect: "Yes. A repeat question is free evidence about the material, and it points at one of three different repairs. Well written is not the same as findable, and neither is the same as usable during a task.", feedbackIncorrect: "Consider what a repeated question actually measures. Several capable people failing at the same point is information about the design of the material, not about their effort." },
          { type: "text", heading: "A private reflection", body: "<p>These prompts are yours. Nothing here is collected, scored or seen by anyone else, and there is no right answer to reach.</p><p>Think about one resource you have written or commissioned. How might your own role, vocabulary or assumptions have shaped what you decided the reader already knew? Who could be burdened or excluded by that assumption — a new colleague, someone in a different part of the division, someone whose first language is not English, someone using a screen reader? Whose expertise was missing when the structure was decided?</p>" },
        ],
      },
      {
        id: "ipe-35-2",
        number: 2,
        title: "Design for the range, not the average",
        summary: "What the curriculum's design reference actually asks for, what accessibility you control directly, and why on-request access is a fallback rather than a design.",
        minutes: 11,
        learning: {
          objective: "Rebuild one learning or guidance product so that more than one way of engaging works by default, applying the design reference's three commitments without requiring anyone to ask for an alternative.",
          takeaways: [
            "The Minnesota Framework for Universal Multicultural Instructional Design and universal design for learning agree on the same practical point: build several ways in from the start, because the alternative is a single path plus a queue of exceptions.",
            "Multiple ways to engage means the same substance is available as readable text, as a short summary, as practice, and as something a person can return to — not one format with a note offering alternatives on request.",
            "Accessibility is mostly decided by a handful of choices a communications, training or program person makes directly: headings, alt text, link wording, contrast, reading order, table headers, captions, and whether anything moves or is timed.",
            "Scores, timers, rankings and public completion lists change what a resource is. They convert optional learning into performance, which suppresses exactly the questions the material exists to answer.",
          ],
          evidence: "A scenario about a converted slide deck with a timed quiz and a posted completion list, sorting practice that assigns design choices to the commitment they serve, and a knowledge check on what on-request access does and does not solve.",
          appliedNextStep: "Take one product you are building now and write down the three ways a person could get its substance without asking anyone for anything. If you can only name one, you have found the work.",
        },
        scenario: {
          context: "A DSD team needs staff across several units to understand a changed internal reporting requirement. What exists is a slide deck converted into a single file: a flowchart image with no description, a ten-question quiz with a four-minute timer, and a completion list posted to a shared page so managers can see who finished. Two staff have asked for an alternative format. One supervisor has asked why her team's names are on a list.",
          prompt: "Which redesign does the most for the most people?",
          options: [
            { label: "Remove the timer and extend the quiz window, so people who need more processing time are not cut off partway through.", response: "This is a real improvement and it is not enough. The flowchart is still unreadable to anyone using a screen reader, the substance is still locked in one format, and the completion list still turns optional learning into something managers watch." },
            { label: "Rebuild it so the same substance exists as a readable page with real headings, a described version of the flowchart, an optional practice activity with no score or timer, and a one-page summary people can keep — then retire the completion list.", response: "This is the redesign. Each piece removes a different barrier, and none of them requires a person to identify themselves or ask for an exception. Retiring the list matters as much as the rest: it returns the material to being a resource rather than a record of who complied.", recommended: true },
            { label: "Keep the module as it is and add a note at the top offering an alternative format on request.", response: "On-request access is a useful backstop and a poor design. It asks the person to notice the barrier, disclose that they meet it, wait, and receive something different from what everyone else got. Design the default so the request is rarely necessary, and keep the offer for the cases you did not anticipate." },
          ],
        },
        transfer: {
          prompt: "Look at the last learning or guidance product your team released. How many ways in does it actually have?",
          options: [
            "List every way a person could reach the substance without asking anyone for anything",
            "Open it and check the five choices you control directly: headings, alt text, link wording, contrast and reading order",
            "Find anything timed, scored or posted as a list of names, and decide whether it earns its place",
          ],
        },
        blocks: [
          { type: "text", heading: "What the design reference actually asks for", body: "<p>This curriculum uses the Minnesota Framework for Universal Multicultural Instructional Design as its design reference, and that framework lines up closely with universal design for learning. Stripped of the vocabulary, both say the same practical thing: decide up front that the people using this will vary, and build for that range, instead of building for an imagined average person and then handling everyone else as an exception.</p><p>Universal design for learning names three places variation shows up. <strong>Engagement</strong>: what makes this worth someone's attention, which differs by role, by pressure and by how the subject touches their work. <strong>Representation</strong>: how the substance is presented, so that reading, listening, seeing a structure and working through an example are all available rather than only one of them. <strong>Action and expression</strong>: how a person works with the material and shows themselves they have it, which in a voluntary program means optional practice and private reflection rather than a score.</p><p>The Minnesota framework adds the part that is easy to skip. Materials carry cultural assumptions in their examples, their names, their scenarios, their idioms and their picture of what a normal situation looks like. A case story set entirely in a suburban two-parent household with reliable transportation and a landline is not neutral; it is one context presented as the default. Designing across contexts is not decoration. It decides whether a reader recognizes the situation well enough to apply the guidance at all.</p><p>Both of these are ordinary craft, not ideology. They are also the difference between designing for sameness — one version, equally available, which the continuum calls Minimization — and designing for the actual range, which is what Adaptation looks like in this kind of work.</p>" },
          { type: "accordion", heading: "Four commitments that decide most of the design", items: [
            { title: "Several ways in, by default", body: "<p>The same substance available as readable text with real headings, as a short summary, as an example or practice activity, and as something a person can return to later. Not one path with a note offering alternatives to anyone willing to identify themselves and wait.</p>" },
            { title: "Accessible by construction, not by repair", body: "<p>Headings that carry the document structure, alt text on every meaningful image, link text that says where it goes, contrast that holds up on a laptop in a bright room, a reading order that makes sense without sight, table headers that a screen reader can announce, captions on anything with speech in it. Every one of these costs almost nothing while you are building and is expensive to retrofit.</p>" },
            { title: "Content that works across contexts", body: "<p>Examples drawn from more than one kind of household, community and region of the state. Names, situations and idioms that do not assume one background. Plain language that explains a specialized term the first time rather than assuming everyone arrived with it. Where a real community is involved, the people from that community are compensated co-designers and reviewers, not an afterthought and not the audience for this curriculum.</p>" },
            { title: "Voluntary, with nothing attached", body: "<p>No score, no timer, no ranking, no public list of who finished, no record of what a person wrote in a reflection. This is not softness. A resource that reports on the reader stops being a place where people admit what they do not know, which is the only condition under which learning material is useful.</p>" },
          ] },
          { type: "sorting", id: "ipe-35-2-sort", heading: "Which commitment does this choice serve?", categories: ["Several ways in", "Accessible by construction", "Content that works across contexts"], items: [
            { text: "A one-page summary of the same guidance, for people who will never open the full document.", category: "Several ways in" },
            { text: "Alt text describing what a flowchart shows, not the words image of flowchart.", category: "Accessible by construction" },
            { text: "Case examples set in a rural county, a suburban household and an urban apartment building.", category: "Content that works across contexts" },
            { text: "Link text that says which form it opens instead of the words click here.", category: "Accessible by construction" },
            { text: "An optional practice activity with no score, alongside the explanation.", category: "Several ways in" },
            { text: "Explaining a specialized term the first time it appears, in ordinary words.", category: "Content that works across contexts" },
            { text: "Heading levels that follow the real structure rather than being chosen for their size.", category: "Accessible by construction" },
            { text: "A short version and a full version, both current, with the difference stated.", category: "Several ways in" },
          ] },
          { type: "list", heading: "The accessibility a communications, training or program person controls directly", ordered: false, items: [
            "Headings that describe the section and follow a real order, so a screen reader user can move through the structure instead of reading everything.",
            "Alt text on every meaningful image, describing what it conveys; decorative images marked so they are skipped.",
            "Link wording that names the destination, so a list of links read aloud is still useful.",
            "Contrast strong enough to read on an ordinary screen in an ordinary room, and never color alone to carry meaning.",
            "Reading order and keyboard order that match the visible layout, with a focus indicator you can actually see.",
            "Real table headers on real tables, and no layout built out of a table.",
            "Captions on anything with speech in it, and a text version of anything essential that is only spoken.",
            "Nothing that moves, flashes or starts on its own; nothing timed unless the timing is the point.",
            "Plain language, short sentences, ordinary words, and the specialized term explained the first time it is used.",
          ] },
          { type: "leaderMove", heading: "Make the default the accessible version", control: "You control whether accessibility is a property of the thing you release or a service people request afterward.", failure: "Do not release the convenient format and add a line offering something else on request. That line moves the cost onto the person with the least power in the exchange and tells them the material was not built with them in mind.", next: "Before your next resource is released, run the nine choices above against it. Fix what you can in an hour, and write down what you could not fix and who owns it." },
          { type: "knowledgeCheck", id: "ipe-35-2-check", question: "A team publishes a training as a single converted file and adds a note: an accessible version is available on request. What is the most accurate assessment?", options: [
            { text: "This meets the need, since anyone who requires a different format can obtain one.", correct: false },
            { text: "The offer is a reasonable backstop, but it is not the design: it requires the person to notice the barrier, disclose that they meet it, wait, and receive something different from what colleagues got.", correct: true },
            { text: "The note is unnecessary, because most staff can use the converted file without difficulty.", correct: false },
            { text: "The team should survey staff about their access needs before deciding how to publish.", correct: false },
          ], feedbackCorrect: "Yes. Build the default so the request is rarely necessary, and keep the offer for the situations you could not anticipate. Nobody should have to identify themselves to receive the same substance everyone else received.", feedbackIncorrect: "Think about what the request costs the person making it: noticing, disclosing, waiting, and then working from something different from what the room is working from." },
          { type: "text", heading: "A private reflection", body: "<p>Private, as always. Nothing here is collected or seen.</p><p>Picture the examples in the last thing you built. Whose household, whose county, whose working conditions did they assume? What might accessibility mean in that product beyond the legal minimum — not the conformance line, but the point at which a person could use it as easily as anyone else? If you found out later that it had excluded someone, what would accountability and repair actually require of you?</p>" },
        ],
      },
      {
        id: "ipe-35-3",
        number: 3,
        title: "Findable, current and owned",
        summary: "A resource library is not a folder. Duplicates, orphaned files and titles in the division's private vocabulary quietly undo good material.",
        minutes: 10,
        learning: {
          objective: "Bring one shared resource page back to a trustworthy state by establishing a single current version, a named owner, a plain title and a review point for each item on it.",
          takeaways: [
            "Good material stops working for reasons that have nothing to do with its quality: the author changed roles, a newer version appeared under a different name, or the title uses a program term nobody searches for.",
            "Every internal resource needs five things attached to it — a plain title in the words people use, a one-sentence summary, the audience, a named owner, and when it was last looked at. Without the owner and the review date, everything else decays.",
            "Duplicates are worse than gaps. A gap sends someone to ask a person; three unlabeled versions send three people to three different answers and nobody notices for a year.",
            "Retiring material is a skill, not a failure. Mark what is replaced, say in one line what changed, and move it out of the main list rather than deleting the record of what people were told before.",
          ],
          evidence: "A scenario about a page holding three versions of the same form instruction, a knowledge check on what restores trust in a shared page, and flashcard practice on the four parts of findability.",
          appliedNextStep: "Open one shared page your team owns. For each item, write the owner and the last review date. Anything you cannot fill in is either someone's to claim in the next two weeks or ready to be retired.",
        },
        scenario: {
          context: "A DSD resource page holds three documents that all explain the same form: the original instruction sheet, a revision posted under a different name, and a slide deck from a training that covered the same ground with one step described differently. None of the three says which is current. Two are owned by staff who have since moved to other roles. A supervisor tells you her new hires have been using whichever one appears first in search.",
          prompt: "What restores trust in that page fastest?",
          options: [
            { label: "Add a note at the top of the page telling people to use the most recent file.", response: "This asks every reader to compare dates across three documents and guess, on a page that has already shown it cannot be trusted. It also leaves the differing step in place, so the people who guess wrong will still be wrong." },
            { label: "Choose one current version, name a living owner and a next review point, mark the other two as replaced and move them out of the main list, and add one line saying what changed.", response: "This is the repair. One current version removes the guessing, the named owner makes the page maintainable, the line about what changed protects the people who learned the old step, and moving rather than deleting keeps the record of what staff were previously told.", recommended: true },
            { label: "Leave all three available so people can choose whichever fits their situation.", response: "Choice among unlabeled duplicates is not choice. It moves the risk of being wrong onto the reader, who has the least information about which document is current and no way to find out." },
          ],
        },
        transfer: {
          prompt: "Which shared page or folder does your team send people to, and could a new colleague tell what is current on it?",
          options: [
            "Open it as a new colleague would and note the first thing that is ambiguous",
            "Count the items with no named owner and the items with no date of last review",
            "Pick one duplicate pair and decide, this week, which one is current",
          ],
        },
        blocks: [
          { type: "text", heading: "Why good material stops working", body: "<p>Almost none of the material that fails inside a division failed because it was badly written. It failed because of what happened to it afterward. The person who wrote it moved to another role and nobody inherited it. A revision went up under a different name and both stayed. A training covered the same ground and described one step slightly differently. A reorganization moved the page and the links that pointed to it were never updated. Two years of that, and a shared page becomes something staff scroll past on their way to asking a colleague.</p><p>The failure mode is specific and worth naming: not an empty library, but a crowded one. A gap is honest — a person finds nothing and asks someone. Three unlabeled versions of the same instruction are not honest. Three people find three different answers, all of them believe they followed the guidance, and nobody discovers the difference until a decision has already gone out.</p><p>Findability has four parts, and titles are where most of the damage happens. Material inside a division tends to be named in the division's own vocabulary — the project name, the committee, the form number, the abbreviation everyone in that room understood at the time. The people who need it search in ordinary words for the task they are doing. A title written for the author is a file that will not be found by the reader.</p>" },
          { type: "list", heading: "What every internal resource needs attached to it", ordered: true, items: [
            "A plain title in the words people would actually search for, naming the task rather than the project.",
            "One sentence saying what it is for, readable before anything is opened.",
            "The audience: which roles this is written for, and which roles it is not.",
            "A named living owner — a person or a position, not a former staff member and not a committee that no longer meets.",
            "When it was last looked at, and when it will be looked at next.",
            "What it replaces, or what has replaced it, stated in one line.",
          ] },
          { type: "flashcards", heading: "Findability, in four parts", cards: [
            { front: "The name", back: "<p>Does the title use the reader's words or the author's? Name the task and the audience. The project name, the committee and the form number belong in the summary, not in the title.</p>" },
            { front: "The words people search", back: "<p>Write down the five phrases someone would actually type, including the wrong ones and the old names. Put them in the summary so the search can find them.</p>" },
            { front: "Where it sits", back: "<p>Is it reachable from the place the work happens, or only from a page someone would have to already know about? A resource that requires prior knowledge to find is a resource for people who did not need it.</p>" },
            { front: "What points to it", back: "<p>Which workflow, message, template or page sends people here — and does any of those still point at a replaced version? Old links are how retired material stays in circulation.</p>" },
          ] },
          { type: "leaderMove", heading: "Retire something on purpose", control: "You control whether superseded material stays in the main list, and whether anyone is told what changed.", failure: "Do not leave a replaced document up because removing it feels risky. Ambiguity is the greater risk: the old version is still being followed by someone right now, and neither of you knows it.", next: "This month, pick one duplicate pair on a page you own. Declare one current, mark the other replaced, write the single line about what changed, and tell the people who were trained on the old one." },
          { type: "knowledgeCheck", id: "ipe-35-3-check", question: "A shared page has four documents on the same topic and no indication of which is current. Which action does the most to make the page trustworthy again?", options: [
            { text: "Sort the page so the most recently uploaded file appears at the top.", correct: false },
            { text: "Name one current version with a living owner and a next review point, mark the rest as replaced and move them out of the main list, and state in one line what changed.", correct: true },
            { text: "Keep all four so that staff can select whichever fits their circumstances.", correct: false },
            { text: "Delete the three older documents so only one remains.", correct: false },
          ], feedbackCorrect: "Yes. One current version, a living owner, a review point, and a line about what changed. Moving rather than deleting keeps the record of what staff were previously told, which matters if someone acted on it.", feedbackIncorrect: "Ask what the reader has to work out for themselves in each option. Upload dates and reader choice both leave the guessing in place; deleting removes the record of guidance people may have followed." },
          { type: "statement", body: "A private reflection, not collected and not seen: think of a resource you own or inherited. If you left your role next month, would anyone know it was theirs? What would the people who rely on it discover only after it had quietly gone out of date, and how could the people most affected have shaped it earlier?" },
        ],
      },
      {
        id: "ipe-35-4",
        number: 4,
        title: "Reviewing a resource you already have",
        summary: "Four checks, in order, on something that already exists — and a one-page record that turns what you find into work someone can own.",
        minutes: 11,
        learning: {
          objective: "Run a four-check inclusive design review of one existing resource and record each finding with the people it affects, an owner, a first fix and a review point.",
          takeaways: [
            "Review in a fixed order — found, read, understood, works for the range — because an unfindable document's wording problems do not matter yet, and a fix at the wrong level wastes the hour you have.",
            "A finding is only useful when it names what is wrong, who it stops, who owns the step and what the first fix is. Everything short of that is an observation that will be read once and lost.",
            "Some findings will be accepted as they are. That is legitimate when it is written down and signed by a named person, and corrosive when it happens silently.",
            "Do not hand a colleague who uses a screen reader your unchecked draft and call it a review. Run the basic checks first; when you do bring in outside reviewers or community co-designers, compensate them and tell them afterward what changed.",
          ],
          evidence: "A scenario about how to spend a ninety-minute review, sorting practice that assigns real findings to the check that would catch them, and a completed one-page review record for a single resource.",
          appliedNextStep: "Run the four checks on one resource you own, fill in the review record, and send it to the person who owns the first fix — with a date you will both look at it again.",
        },
        scenario: {
          context: "You have agreed to review one existing resource against inclusive design standards: a two-page instruction sheet your team sends to every new staff member in their first week. It has been in use for years, nobody has looked at it closely, and you have ninety minutes before your next meeting.",
          prompt: "How do you spend the ninety minutes?",
          options: [
            { label: "Read it closely and mark every sentence you would word differently, then send the marked-up copy to the owner.", response: "This is copyediting. It will improve the tone and miss the structural problems: whether a new staff member can find the sheet at all, whether the headings carry the structure, whether the table has real headers, whether the examples assume one kind of background. Wording is the last check, not the first." },
            { label: "Run four checks in order — can it be found, can it be read by the tools people use, can it be understood on a first read, does it work for the range of people who receive it — and write each finding with the people it stops, an owner and a first fix.", response: "This is the review. The order keeps you from polishing sentences in a document nobody can locate, and the finding format turns ninety minutes of reading into work someone can pick up. What you cannot fix becomes a line with an owner rather than a note that disappears.", recommended: true },
            { label: "Send it to a colleague who uses a screen reader and ask her to tell you what is wrong with it.", response: "One person's access experience is not a review, and asking a colleague to audit an unchecked document is unpaid work on top of her own job. Run the basic checks yourself first. When you do bring in disabled reviewers or community co-designers, arrange compensation, be specific about what you are asking, and tell them afterward what changed." },
          ],
        },
        transfer: {
          prompt: "Which resource will you review this month, and who will you send the record to?",
          options: [
            "Name the resource and the ninety minutes you will give it",
            "Name the person who owns the first fix and the date you will both look at it again",
            "Write the finding you expect to make before you start, then check whether you were right",
          ],
        },
        blocks: [
          { type: "text", heading: "Four checks, in this order", body: "<p>Reviewing something that already exists is different from building something new, and it is the more common task. The material is in use, people depend on it, and you usually have an hour or two rather than a project. The order of the checks is what makes that hour productive.</p><p><strong>Can it be found?</strong> Search for it the way a new colleague would, in ordinary words. Check whether the title names the task, whether anything in the workflow points to it, and whether a replaced version is still sitting next to it. If this check fails, stop here; the rest is polishing a document nobody reaches.</p><p><strong>Can it be read by the tools people use?</strong> Are the headings real headings that carry the structure? Does every meaningful image have alt text that says what it shows? Does link text name its destination? Is the reading and keyboard order the same as the visible order? Does the table have real headers? Is the contrast adequate, and does any meaning depend on color alone?</p><p><strong>Can it be understood on the first read?</strong> Does the structure follow the reader's task rather than the program's history? Is the answer near the top? Are specialized terms and abbreviations explained the first time? Would a person in their second week know which sentences are requirements and which are background?</p><p><strong>Does it work for the range of people who receive it?</strong> Whose household, county, schedule, language and working conditions do the examples assume? Is there more than one way in, or one path plus an offer of alternatives on request? Is anything timed, scored or posted as a list of names, and does it earn that?</p>" },
          { type: "sorting", id: "ipe-35-4-sort", heading: "Which check would catch this?", categories: ["Can it be found", "Can it be read", "Can it be understood", "Works for the range"], items: [
            { text: "The title is the project name and the form number, with nothing about the task.", category: "Can it be found" },
            { text: "The section breaks are bold text sized larger, not real headings.", category: "Can it be read" },
            { text: "The requirement appears on page two, after a page of history.", category: "Can it be understood" },
            { text: "Every example assumes reliable personal transportation and daytime availability.", category: "Works for the range" },
            { text: "A replaced version of the same sheet is still on the page, undated.", category: "Can it be found" },
            { text: "Four abbreviations are used before any of them is explained.", category: "Can it be understood" },
            { text: "The only summary of the process is a picture with no description.", category: "Can it be read" },
            { text: "The substance exists in one format, with a note offering alternatives on request.", category: "Works for the range" },
          ] },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A review record for one existing resource", summary: "One page that turns ninety minutes of reading into findings someone can act on.", fields: [
            { label: "Resource and audience", value: "New staff instruction sheet, two pages, sent by the unit lead in week one to every new hire including transfers from other divisions. Reviewed as a new colleague with no DSD background, using a screen reader." },
            { label: "Findings, check by check", value: "Found: title is the form number; nothing in the onboarding message links to it; a replaced version sits beside it undated. Read: section breaks are bold text rather than headings; the process picture has no description; two links read as here. Understood: the requirement appears after a page of background; four abbreviations are unexplained. Range: every example assumes a car and daytime availability; one format only." },
            { label: "Owner and first fix", value: "Unit lead: retitle by task, link it from the welcome message, mark the old version replaced. Training staff: convert the bold text to real headings, describe the picture, rewrite the two links — about one hour. Program staff: move the requirement to the top and explain the abbreviations at first use." },
            { label: "Accepted as is, and by whom", value: "The single-format limitation stays for now; a one-page summary is the agreed substitute until the page is rebuilt. Accepted in writing by the unit lead, with the reason recorded." },
            { label: "Next review point and triggers", value: "Look again at the agreed point, and sooner if the form changes, if the onboarding process changes, or if a new colleague tells us they could not find or use it." },
          ], action: "Copy the five fields, fill them in for one resource you already own, and send the record to the person who owns the first fix — with the date you will both look at it again." },
          { type: "list", heading: "First fixes that need nobody's permission", ordered: false, items: [
            "Retitle the resource by the task, in the words people search for.",
            "Convert sized bold text into real headings so the structure can be read aloud and navigated.",
            "Write alt text that says what an image shows, and mark decorative images to be skipped.",
            "Replace link text such as here and click here with the name of the destination.",
            "Move the answer to the top and the history to the bottom.",
            "Explain every abbreviation the first time it appears.",
            "Add a one-page summary next to the full version, and say which is which.",
            "Mark one version current, mark the rest replaced, and say in one line what changed.",
          ] },
          { type: "leaderMove", heading: "Write the finding so someone can pick it up", control: "You control the form of the finding: what is wrong, who it stops, who owns the step, what the first fix is, and when it will be looked at again.", failure: "Do not send a list of impressions and expect action. A finding without an owner and a first fix is an observation, and observations are read once.", next: "Write your next three findings in that form, send them to the named owners, and put the review date in your own calendar rather than hoping someone else keeps it." },
          { type: "knowledgeCheck", id: "ipe-35-4-check", question: "Your review of an internal instruction sheet finds that section breaks are bold text rather than real headings. Which entry is a complete finding?", options: [
            { text: "Headings need work throughout the document.", correct: false },
            { text: "Section breaks are sized bold text, not real headings, so screen reader users cannot navigate the structure and must read the whole sheet. Owner: training staff. First fix: convert to heading levels, about one hour. Look again at the agreed point.", correct: true },
            { text: "The formatting is inconsistent and should be brought into line with the division's template.", correct: false },
            { text: "Consider whether headings are necessary in a document of this length.", correct: false },
          ], feedbackCorrect: "Yes. What is wrong, who it stops, who owns it, the first fix and when it will be looked at again — that entry can be picked up and finished by someone who was not in the room.", feedbackIncorrect: "A complete finding names the defect, the people it stops, an owner, a specific first fix and a review point. Anything less is an impression that will be read once and lost." },
          { type: "statement", body: "A private reflection, yours alone and not collected: think about the resource you just decided to review. How could the people most affected by it have shaped it earlier — new colleagues, staff who use assistive technology, staff in units far from yours, and, where a community is involved, compensated co-designers from that community? Then write your own next line: the resource I will review is, the person who owns the first fix is, and the date we will look at it again is." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Inclusive learning and knowledge design",
    subtitle: "One page for anyone who writes, builds or maintains internal guidance",
    quote: "Published is not the same as usable. Design for the range, not the average.",
    use: {
      purpose: "Keep the four checks and the design commitments in view while you plan a training, write a work instruction, build a template, or clean up a shared resource page.",
      remember: [
        "Material fails in three different ways — not found, not understood, not usable at the moment of need — and each needs a different repair.",
        "Repeat questions, private workarounds and homemade cheat sheets are free evidence about your material, not evidence about staff effort.",
        "Build several ways in by default. On-request access is a backstop, not a design.",
        "One current version, one named living owner, a plain title in the reader's words, and a review point that actually arrives.",
        "A finding is only useful when it names who it stops, who owns it, what the first fix is and when it will be looked at again.",
      ],
      doNext: "Pick one resource you already own, run the four checks on it in order, and send the review record to the person who owns the first fix.",
    },
    sections: [
      {
        heading: "Before you write anything new",
        items: [
          "Write one sentence describing the moment a person will be in when they need this, and keep it at the top of the draft.",
          "Name the roles this is for, and the roles it is not for. Four very different roles usually means three documents, not one.",
          "Write the shortest true answer first, in ordinary words; everything else supports it.",
          "Name what this replaces, and arrange for the old version to be marked or moved.",
        ],
      },
      {
        heading: "The four checks for any resource",
        items: [
          "Can it be found? Search as a new colleague would. Title names the task, the workflow points to it, no undated duplicate beside it.",
          "Can it be read? Real headings, alt text that says what an image shows, link text that names the destination, adequate contrast, sensible reading and keyboard order, real table headers.",
          "Can it be understood on a first read? Answer near the top, structure follows the task, abbreviations explained at first use, requirements distinguishable from background.",
          "Does it work for the range? More than one way in, examples from more than one kind of household and county, nothing timed or scored without a reason.",
        ],
      },
      {
        heading: "Keeping it current",
        items: [
          "Attach five things to every item: plain title, one-sentence summary, audience, named living owner, last and next review.",
          "Declare one current version and mark the rest replaced; move them out of the main list rather than deleting the record.",
          "Say in one line what changed, and tell the people who were trained on the old version.",
          "Anything with no owner is either someone's to claim in the next two weeks or ready to retire.",
        ],
      },
      {
        heading: "Writing a finding people can act on",
        items: [
          "Name the defect, the people it stops, the owner of the step, the first fix and the review point.",
          "Record what is accepted as it is, by whom, and why — silence on that is how a gap becomes permanent.",
          "Run the basic checks yourself before asking anyone else to look; do not hand an unchecked draft to a colleague as an audit.",
          "When you bring in disabled reviewers or community co-designers, compensate them, be specific about the ask, and tell them afterward what changed.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Communications and training staff, who build most of this material and control most of the choices that decide whether it works — a useful place to start.",
          "Policy and program staff, who write the guidance and work instructions that carry the largest share of a division's internal knowledge.",
          "Quality and performance staff, who already hold the repeat questions and complaint patterns that show where material is failing.",
          "Data, research and technology staff, whose documentation of what they build is read by people outside their field.",
          "Supervisors, leaders and administrative staff, who ask for resources, decide when one is finished, and keep the shared pages and templates alive.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "Leading a reflective DSD team",
          "Inclusive workforce and team culture",
          "Co-design and compensated partnership",
          "Leading difficult dialogue",
          "Sustaining voluntary learning",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials, and instruction that is accessible by construction rather than by later accommodation." },
    { title: "CAST, Universal Design for Learning Guidelines", href: "https://udlguidelines.cast.org/", note: "The engagement, representation, and action and expression framework used in this module to explain what several ways in actually means in a learning product." },
    { title: "Minnesota Department of Human Services, Content and writing guidelines", href: "https://mn.gov/dhs/digital-showcase/content-guidelines/", note: "The department's own editorial guidance on first-read understanding, descriptive sentence-case headings, familiar terms and writing suited to the reader." },
    { title: "PlainLanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Detailed guidance on audience, organization, useful headings and the vague wording that leaves a reader unable to act on what they have just read." },
    { title: "W3C Web Accessibility Initiative, Writing for web accessibility", href: "https://www.w3.org/WAI/tips/writing/", note: "Practical guidance on link text, headings, plain wording and text alternatives — the writing-side choices named in the second and fourth lessons." },
    { title: "Section508.gov, Create accessible documents and content", href: "https://www.section508.gov/create/documents/", note: "Federal instruction on accessible documents, presentations, spreadsheets and forms, including heading structure, alt text and table headers." },
    { title: "Minnesota IT Services, Accessibility standard", href: "https://mn.gov/mnit/about-mnit/accessibility/policy/", note: "The state's accessibility standard for digital documents, web content and procurement — the baseline an internal resource is reviewed against." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the standards on easy-to-understand materials and on workforce education and training." },
  ],
};

export default pack;
