import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Internal leadership · Module 31: Inclusive workforce and team culture.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-31-inclusive-workforce-culture",
    indexNumber: 1173,
    seriesLabel: "Intercultural Practice and Equity · Internal leadership",
    title: "Inclusive Workforce and Team Culture",
    subtitle: "Team culture is not a values statement. It is the accumulated result of a handful of ordinary decisions: how a job is posted, who sits on the panel, what the first month feels like, who gets the interesting work, and what happens when somebody asks for something they need. Four lessons on finding those decisions and examining one of them properly.",
    scope: "For internal DHS and DSD staff who shape how people are hired, welcomed, supervised, developed and kept: supervisors and managers; executive and senior leaders; communications, training and learning-design staff; policy, program and operations staff; quality and performance staff; data, research and analytics staff; fiscal, contracts, grants and procurement staff; community engagement staff; administrative and support staff. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. You are never asked to disclose your own identity, health, experiences or beliefs. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota examples, scenarios, sorting and flashcard practice, private reflection prompts, and a workforce-process barrier review you can copy into your own work",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/equal-opportunity-employment.jpg",
    coverAlt: "A woman reviews an employment packet at a table.",
    introTranscript: "Most divisions describe their culture in the language of intention: we value different perspectives, we support each other, everyone belongs here. Staff read those statements against something else entirely. They read them against the posting that required a credential the work never needed, the panel of three people from the same unit, the first month where nobody said what good looked like, the stretch assignment that went to somebody else, and the accommodation request that disappeared for six weeks. This module treats team culture as the sum of those decisions rather than as a mood. It looks at how a job is posted and filled, what the first weeks teach people, how work and supervision time get handed out, and who is quietly asked to do unpaid work because of who they are. It ends with a barrier review you can run on one workforce process in about six hours, and a first fix that needs nobody's permission.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Locate the specific workforce decisions in your own area where belonging, access and fairness are settled in practice rather than in a statement, and name the person who owns each one.",
        "Distinguish requirements essential to a job from wording, credentials and process steps that screen out people whose experience is real but differently shaped.",
        "Identify the onboarding, assignment, supervision and development decisions that determine who stays and who advances in a DSD unit.",
        "Name the unpaid work that quietly falls on some staff because of who they are, and describe what a supervisor does instead.",
        "Complete a barrier review of one workforce process, naming each step, who it stops, the owner, the first fix inside your own authority, and the point at which somebody checks.",
      ],
      evidence: [
        "Four worked scenarios drawn from internal DSD work: a leadership group reading its own staff survey results, a draft posting and selection plan, two analysts hired in the same month, and a unit choosing which process to examine.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates essential requirements from convenient ones, and separates decisions a supervisor owns from decisions the division owns.",
        "A completed barrier review of one workforce process, kept with the work rather than in a personal file.",
      ],
      appliedNextStep: "Choose one workforce process you touch, walk it end to end as the person going through it, write the barrier review, make the first fix inside your own step this month, and give the check a name and a date.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in State of Minnesota hiring, classification, selection or accommodation practice issued by Minnesota Management and Budget, or a change in the department's own human resources procedures",
        "A change in federal employment guidance on disability, including guidance from the U.S. Equal Employment Opportunity Commission on reasonable accommodation, or a change in the Minnesota Human Rights Act",
        "Feedback from DSD staff, paid community advisors or disabled Minnesotans that a scenario here misstates what a supervisor actually controls, or understates what an accommodation request costs the person making it",
      ],
      relatedDoor: "Formal decisions about recruitment, selection, classification, compensation, accommodation requests, discipline, complaints and promotion belong to the responsible DHS human resources and equal opportunity offices and to Minnesota Management and Budget; this module prepares the examination, it does not decide a personnel matter.",
      toolkitQuestion: "If somebody who did not already know how this division works went through this process, what would it teach them about whether they belong here?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-31-1",
        number: 1,
        title: "Where team culture is actually decided",
        summary: "Culture is not what a division says about itself at an all-staff meeting. It is the accumulated result of a few repeatable decisions, nearly all of which belong to somebody with a name.",
        minutes: 11,
        learning: {
          objective: "Locate at least five workforce decisions in your own area where belonging, access and fairness are settled in practice, and name the person who owns each one.",
          takeaways: [
            "A values statement is read against experience. People compare it to the last posting they saw, the last panel they sat on, and the last one-on-one that was canceled.",
            "Belonging is settled in about seven places: how the work is described, how it is posted, who selects, what the first month contains, how work is assigned, how supervision time is spent, and how growth is offered.",
            "Every one of those places has an owner. That is the useful news: a process with an owner can be examined and changed without a campaign, a budget or a reorganization.",
            "“We treat everybody the same” describes an intention and hides an effect. The same posting, the same interview and the same onboarding land differently depending on what a person arrives with.",
            "Survey results tell you where to look. They do not tell you what is wrong. The process walk does that, and it is the part most divisions skip.",
          ],
          evidence: "A scenario about a leadership group deciding how to spend one hour on its staff survey results, sorting-free flashcard practice on five words that get used interchangeably, and a knowledge check on where culture change actually happens.",
          appliedNextStep: "List the workforce decisions your area made in the last month: a posting, a panel, a new hire's first week, an assignment, a promotion, a schedule change. Beside each one, write the name of the person who decided.",
        },
        scenario: {
          context: "A DSD division reviews its annual staff engagement results. Overall satisfaction is steady, but two items sit noticeably lower for staff who report a disability and for staff of color: “my ideas are valued” and “I can raise a concern without it costing me.” The leadership group has one hour on the agenda. A manager proposes a culture campaign: a values poster in the break rooms, a kickoff event, and a monthly note from the director.",
          prompt: "What is the most useful way this group could spend the hour?",
          options: [
            { label: "Approve the campaign. Staff need to hear that leadership takes belonging seriously, and visible commitment is where culture change starts.", response: "The campaign is cheap, quick and easy to agree to, which is most of its appeal. It also asks people to accept a statement about the division that contradicts what they told the survey. A poster is read against the last posting, the last panel and the last canceled meeting, and it loses that comparison every time." },
            { label: "Pick one workforce process the division actually controls — the posting, the panel, onboarding, how work is assigned, or the one-on-one — and walk it step by step for who it screens out, starting with the process closest to those two items.", response: "Yes. The survey said where to look; the walk finds what is wrong. One process examined properly produces a change somebody can own, which is worth more than six initiatives nobody is accountable for.", recommended: true },
            { label: "Add questions to next year's survey so the division understands the pattern before it acts.", response: "This produces a more precise description of the same problem twelve months later. Asking again without acting on the first answer also spends the willingness that produced it; the response rate for the group you most need to hear from is usually the first thing to fall." },
          ],
        },
        transfer: {
          prompt: "Which single workforce decision in your area has the most people passing through it?",
          options: [
            "Name the decision and roughly how many people it touched in the last year",
            "Name the person who owns it, by name rather than by unit",
            "Write down what you would expect to find if you walked it, then check whether you were right",
          ],
        },
        blocks: [
          { type: "text", heading: "Culture is a set of decisions, not a mood", body: "<p>Ask a division to describe its culture and you will usually get adjectives: collaborative, supportive, mission-driven. Ask a person who left after eleven months and you will get events. The posting asked for a credential the job never used. The interview questions arrived at the door. Nobody explained what good work looked like until the first review. The interesting project went to somebody who had been there longer, twice. A request for a change in schedule took six weeks and three explanations.</p><p>Those are not failures of warmth. Every one of them is a decision, made by a person, inside a process that has a name and an owner. That is what makes this workable. You cannot change a mood by deciding to. You can rewrite a posting, change who sits on a panel, protect a standing meeting, and publish what happens when somebody asks for what they need.</p><p>This is also where the phrase “we treat everybody the same” quietly does its damage. It describes an intention, and the intention is usually genuine. What it hides is effect. The same posting, the same interview and the same first month land differently depending on what a person arrives with: a degree or a decade of directly relevant work without one, a car or a bus route, predictable health or a condition that flares, a network inside the agency or nobody to ask. A division that stops at intention will keep producing the same result and keep being surprised by it.</p><p>The five stages named on the next screen describe how a leadership group reads its own team, not how any individual thinks. They are a way of noticing an institutional habit, and never a label, a score or a record about a person.</p>" },
          { type: "list", heading: "Where belonging is actually settled", items: [
            "How the work is described: the position description, the classification, and whether the duties match what the person will really do.",
            "How the job is posted: the requirements, the wording, where it is advertised, how long it stays open, and how hard the application is to complete.",
            "Who selects: the panel, the questions, when candidates see them, the format, and what counts as a good answer.",
            "The first month: who greets the person, what equipment and access arrive on day one, who explains the unwritten rules, and whether anyone says what good work looks like.",
            "How work is assigned: who gets the visible project, who gets the maintenance queue, and whether anybody tracks the pattern over a year.",
            "How supervision time is spent: whether the one-on-one is held, what it is used for, and whether feedback arrives in time to act on.",
            "How growth is offered: who is told about a training budget, a temporary assignment or a posting before it closes, and who finds out afterward.",
          ] },
          { type: "tabs", heading: "Five ways a leadership group reads its own team culture", tabs: [
            { label: "Denial", body: "<p>“We have a good culture here. People stay for years.” The people who left are not in the room, and exit records say pay. Nobody asks who stopped applying, who stopped volunteering for projects, or who stopped raising things in meetings.</p>" },
            { label: "Polarization", body: "<p>“Some people are never satisfied, whatever we do.” Or the mirror image: “this division is hopeless.” Both readings end the inquiry. One protects the process from examination, the other declares examination pointless, and neither produces a change anyone can name.</p>" },
            { label: "Minimization", body: "<p>“We treat everybody the same, and we hire the best person for the job.” Sincere, widely held, and the single most expensive sentence in this list. It converts a specific, checkable question about effect into a general statement about intent, which makes it nobody's to answer.</p>" },
            { label: "Acceptance", body: "<p>“Our process works well for people who arrive with certain things. Who does it work less well for, and where exactly?” The question is now answerable. Someone can walk the posting, the panel and the first month and come back with steps and owners.</p>" },
            { label: "Adaptation", body: "<p>The unit changes how it hires, welcomes, assigns and develops, because it can now see the process from the other side well enough to design differently: essential requirements only, questions in advance, a named first-week contact, assignment patterns reviewed once a year, and a check somebody's calendar actually holds.</p>" },
          ] },
          { type: "leaderMove", heading: "Give every step an owner's name", control: "You control whether a workforce process in your area is described as “the way we do it here” or as a numbered sequence of steps, each with a person's name beside it.", failure: "Do not accept “that is just how the hiring process works” as an answer. Somebody wrote the requirement, somebody chose the panel, somebody set the window. A process with no owner cannot be improved and cannot be defended.", next: "Before your next hire or onboarding, write the steps in order on one page and put a name beside each. Show it to the people who own those steps." },
          { type: "flashcards", heading: "Five words that get used interchangeably, and should not", cards: [
            { front: "Representation", back: "<p>Who is on the payroll. It is a count, it is worth knowing, and on its own it tells you nothing about whether those people can do their jobs, influence decisions, or want to stay.</p>" },
            { front: "Access", back: "<p>Whether the ordinary things of the job work for the person: the application system, the building, the meeting, the document, the schedule. Access is a property of the design, not a favor granted to an individual.</p>" },
            { front: "Accommodation", back: "<p>A specific adjustment for a specific person, decided through a formal route that human resources owns. Necessary, and a sign of where the design failed. A process that needs many of the same accommodation is a process that should change.</p>" },
            { front: "Belonging", back: "<p>Whether a person can contribute fully, be themselves at work without paying for it, influence what happens, and expect to still be here in three years. It is observable, and it is mostly produced by supervisors.</p>" },
            { front: "Retention", back: "<p>Who stays. A useful signal and a lagging one: by the time it moves, the decisions that produced it are a year or more old and the person is gone.</p>" },
          ] },
          { type: "statement", body: "A private reflection, for you alone. Think of one workforce decision you made or influenced in the last month. How did your role, your authority and your assumptions about what a good candidate or a good employee looks like shape it? Who could have been helped, burdened, excluded or misunderstood by it? Nothing you write here is collected, seen or kept." },
          { type: "knowledgeCheck", id: "ipe-31-1-check", question: "A unit's staff survey shows that staff with disabilities report lower agreement with “my ideas are valued.” Which follow-up is most likely to change the result?", options: [
            { text: "Run an all-staff session on inclusive communication, so everyone hears the same expectations about how ideas are received.", correct: false },
            { text: "Walk one process where ideas actually enter decisions — how the agenda is set, who is asked to present, who is on the project team — find where people are stopped, name the owner, and change one step.", correct: true },
            { text: "Ask supervisors to be more attentive to quieter team members in meetings and to follow up individually.", correct: false },
            { text: "Repeat the survey in six months with an additional open comment field to understand the concern in more detail.", correct: false },
          ], feedbackCorrect: "Yes. The survey located the problem; a walked process identifies the step, the owner and the fix. Everything else describes the problem more carefully or asks individuals to compensate for a design.", feedbackIncorrect: "Ask which option ends with a changed step and a named owner. Training, attentiveness and more survey questions can all be genuinely useful, and none of them alters the decision that produced the result." },
        ],
      },
      {
        id: "ipe-31-2",
        number: 2,
        title: "Who the posting is written for",
        summary: "A job posting is a filter. Most of what it filters out was never a requirement of the work, and the filtering happens before anyone in the division sees a name.",
        minutes: 11,
        learning: {
          objective: "Examine a job posting and selection process and distinguish requirements essential to the work from wording, credentials and steps that screen out people whose experience is real but differently shaped.",
          takeaways: [
            "A requirement is essential when the work genuinely cannot be done without it. Everything else is a convenience, and conveniences do the quiet work of narrowing a candidate pool.",
            "Degree requirements, years-of-experience floors and “experience in this specific program” each exclude people who can do the job, and none of them predicts performance on its own.",
            "Wording carries as much weight as requirements. A posting full of internal shorthand tells outsiders the job is not for them, and the people already inside read it without noticing.",
            "The steps are part of the filter: a short window over a holiday, an application that takes four hours, an inaccessible form, interview questions handed out at the door, and a panel drawn from one unit.",
            "The fixes are unglamorous and effective: test each requirement against the duties, name the equivalent experience that counts, send questions in advance, make every step usable, and put somebody from outside the unit on the panel.",
          ],
          evidence: "A scenario about a draft policy analyst posting, sorting practice separating essential requirements from convenient ones and accessibility barriers, and a knowledge check on what discretion late in a process can and cannot repair.",
          appliedNextStep: "Take the last posting your area wrote. Beside each requirement, write the duty it is there to protect. Delete or rewrite every requirement you cannot connect to a duty, and name the equivalent experience that will count instead.",
        },
        scenario: {
          context: "A DSD program area is filling a policy analyst position. The draft posting requires a master's degree, five years of experience in a DHS waiver program, “excellent verbal communication,” and a valid driver's license. The posting opens on a Friday afternoon and closes the following Wednesday. Interviews are held the same week, in person at the central office, with the questions handed to candidates at the door. The panel is the hiring supervisor and two analysts from the same unit.",
          prompt: "Which change does the most for the quality of this hire?",
          options: [
            { label: "Extend the posting window and add a line encouraging people from underrepresented groups to apply.", response: "The longer window is a genuine improvement and the invitation is well meant. Neither touches the filter. Encouraging somebody to enter a process that will screen them out for a credential the job does not need is an invitation into a closed door, and people who have been through it before recognize the shape of it." },
            { label: "Test each requirement against the actual duties, drop the ones that are not essential, name the equivalent experience that counts, send the questions in advance, offer a remote option for the interview, and put an analyst from another unit on the panel.", response: "Yes. Each of these is inside the hiring supervisor's reach and each one removes a filter that was never protecting the work. Questions in advance in particular tend to worry panels and then improve the answers, because preparation is a job skill and recall speed under pressure is not.", recommended: true },
            { label: "Keep the requirements as written and rely on the panel to look past them when a strong candidate comes through.", response: "Discretion applied late cannot recover people who never applied, and it is not applied evenly. An unwritten allowance is granted most often to candidates the panel already finds familiar, which is the opposite of what it is meant to correct." },
          ],
        },
        transfer: {
          prompt: "What is in your area's standard posting that nobody has questioned in years?",
          options: [
            "Find the requirement that has been copied forward through several postings without review",
            "Write the duty it is supposed to protect, in one sentence, or delete it",
            "Name one person outside your unit who will read the next draft before it posts",
          ],
        },
        blocks: [
          { type: "text", heading: "What a posting is actually doing", body: "<p>A posting looks like a description of a job. It behaves like a set of instructions to the public about who should not bother. Most of the narrowing in a hiring process happens here, before anyone in the division has seen a name, and it is invisible to the people doing the hiring because they only ever meet the people who got through.</p><p>Three requirements do most of the damage in public administration. A degree requirement on a role where the degree is not used excludes people who did the work without one, and it correlates with family money more closely than with capability. A years-of-experience floor set at five rather than three is almost always a guess, and it removes people who moved faster. “Experience in this specific program” is the narrowest of all: it guarantees that the unit hires people who already think the way the unit thinks, which is exactly the opposite of what a redesign or an equity review needs.</p><p>Then there is the wording. A posting written in internal shorthand, thick with program names and division abbreviations, reads as a private conversation. People inside the agency read it and see a job. People outside read it and see a room they are not in. That is not a small effect; for a division that says it wants perspectives it does not already have, it is the whole effect.</p>" },
          { type: "accordion", heading: "Five places a selection process quietly narrows", items: [
            { title: "The requirement list", body: "<p>Ask of each line: can the duties in this position description be performed without it? If yes, it is a preference, and preferences belong in a separate section or nowhere. Where a credential is genuinely needed, name the equivalent experience that will also count, and mean it — a list of equivalents nobody on the panel knows how to score is decoration.</p>" },
            { title: "The wording", body: "<p>Read the draft as somebody who has never worked in state government. Every program name, division abbreviation and internal phrase is a small signal about who this is for. Say what the person will actually do on a Tuesday, in plain words, and keep the sentences short enough to read on a phone.</p>" },
            { title: "The application itself", body: "<p>Time it. If completing it honestly takes four hours, you have set a price that people working two jobs or managing a health condition cannot pay. Check that every step works with a keyboard and a screen reader, that documents can be read by the tools people use, and that there is a named contact for anyone who needs the process to work differently.</p>" },
            { title: "The interview design", body: "<p>Questions handed out at the door test recall speed and comfort with improvisation, neither of which is in the position description. Send the questions in advance, say how long the interview will run, offer a remote option, and ask the same questions of everyone so the answers can actually be compared.</p>" },
            { title: "The panel", body: "<p>A panel drawn from one unit will recognize one kind of good. Add somebody from another area, somebody who will use what this role produces, and where the role touches services, consider a paid community advisor with the clarity to say what the unit cannot hear from inside.</p>" },
          ] },
          { type: "sorting", id: "ipe-31-2-sort", heading: "Essential to the job, screening people out, or an accessibility barrier?", categories: ["Essential to the job", "Screens people out without adding quality", "Accessibility barrier"], items: [
            { text: "A professional license the position is legally required to hold in order to sign the work it produces.", category: "Essential to the job" },
            { text: "A master's degree for an analyst role whose duties list no research design or supervision.", category: "Screens people out without adding quality" },
            { text: "An online application that cannot be completed with a keyboard alone.", category: "Accessibility barrier" },
            { text: "Five years of experience specifically inside one DHS program area, for a role that reviews that area's design.", category: "Screens people out without adding quality" },
            { text: "The ability to analyze program data and write findings that a non-specialist can act on, which is the core of the position description.", category: "Essential to the job" },
            { text: "Interview questions handed to candidates at the door, with no option to see them beforehand.", category: "Accessibility barrier" },
            { text: "A valid driver's license for a desk-based role with no required travel.", category: "Screens people out without adding quality" },
            { text: "An application window that opens Friday afternoon and closes the following Wednesday.", category: "Screens people out without adding quality" },
            { text: "An in-person interview at the central office with no remote option and no information about the building's entrance.", category: "Accessibility barrier" },
            { text: "Fluency in written English sufficient to draft public notices, which this role drafts every week.", category: "Essential to the job" },
          ] },
          { type: "leaderMove", heading: "Write only the requirements you can defend", control: "You control every line in the draft posting and every step in the selection plan, up to the point where the requisition leaves your desk.", failure: "Do not copy the last posting forward. Inherited requirements are the most common reason a division keeps hiring people who resemble the people it already has, and nobody in the room chose that outcome.", next: "On your next requisition, write the duty each requirement protects in the margin. Anything with an empty margin comes out before it posts, and the equivalent experience that counts goes in." },
          { type: "quote", text: "I did the work for eleven years at a nonprofit. The posting wanted the degree, so I did not apply. A colleague told me afterward that they would have counted my experience. Nobody told me that in the posting, and the posting was all I had.", cite: "Composite applicant perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-31-2-check", question: "A hiring supervisor keeps a degree requirement on a posting, planning to consider equivalent experience if a strong applicant without a degree comes through. What is the most accurate assessment?", options: [
            { text: "Reasonable. The requirement signals the level of the role, and the supervisor retains flexibility for exceptional candidates.", correct: false },
            { text: "The requirement is doing its filtering before the supervisor ever sees an application. People who read it and did not apply cannot be reconsidered, and unwritten flexibility is applied most readily to candidates who already seem familiar.", correct: true },
            { text: "It depends on the classification; if the class specification names a degree, the supervisor has no discretion and the question does not arise.", correct: false },
            { text: "Acceptable as long as the posting also includes a statement welcoming applicants from a range of backgrounds.", correct: false },
          ], feedbackCorrect: "Yes. A filter operates on the people who read it, not on the people who reach the panel. If equivalent experience counts, the posting has to say so, and the panel has to know how to weigh it.", feedbackIncorrect: "Ask who is affected by a requirement, and when. The people it removes are gone before any discretion can be exercised, and discretion that is never written down tends to favor the familiar." },
          { type: "statement", body: "A private reflection, for you alone. Picture the last person you hired or helped to select. What did they arrive with that made the process easy for them, and who would have found the same process expensive? Does this posting make sense to somebody who does not already know how this agency works? Nothing you write here is collected, seen or kept." },
        ],
      },
      {
        id: "ipe-31-3",
        number: 3,
        title: "Arriving, staying, and who gets grown",
        summary: "People form a working conclusion about their future in an organization during the first weeks, and revise it every time work is handed out. Both of those moments belong to a supervisor.",
        minutes: 11,
        learning: {
          objective: "Identify the onboarding, assignment, supervision and development decisions that determine who stays and who advances, and name the unpaid work that quietly falls on some staff.",
          takeaways: [
            "Onboarding teaches people what is true here. Equipment that arrives late, access that takes a month and nobody explaining what good work looks like all teach something specific.",
            "Assignment is the most consequential ordinary decision a supervisor makes. The visible project builds a career; the maintenance queue holds the unit together and is invisible at review time.",
            "A canceled one-on-one is a message, and it is received as one. Protecting the meeting costs thirty minutes and is the cheapest retention practice available to a supervisor.",
            "Some staff carry unpaid work nobody assigned: representing a community, translating informally, comforting colleagues, sitting on every committee that needs to look mixed. It is real work, it is uncompensated, and it competes with the work they are reviewed on.",
            "Development is usually offered through informal channels — a mention of a training budget, a heads-up about a posting, an introduction. Whoever is outside those channels is not developing, whatever the plan says.",
            "Accommodation requests are formal and they are also a test of the unit. How long it takes, how many times the person has to explain, and who else finds out are all things the unit can influence.",
          ],
          evidence: "A scenario about two analysts hired in the same month with different first years, sorting practice on who owns which retention decision, and a knowledge check on assignment patterns.",
          appliedNextStep: "List every substantial assignment your unit handed out over the past year and who received it. Look at the pattern rather than any single decision, and decide what the next three assignments will do about it.",
        },
        scenario: {
          context: "Two analysts join the same DSD unit in the same month. One is given the service redesign project, a standing weekly one-on-one and an introduction to the division director. The other is given the maintenance work queue, a one-on-one that is canceled more often than it is held, and a request to join the division's cultural awareness committee “because you would bring a perspective we do not have.” Eleven months later the second analyst resigns. The exit record reads: left for higher pay.",
          prompt: "What does that record miss?",
          options: [
            { label: "Nothing important. Pay is a real reason people leave state service, and the unit cannot compete with private employers on salary.", response: "Pay is real, and it is also the safest thing a departing employee can write. It closes the conversation, protects the reference and requires no one to be named. The record is accurate and almost empty; treating it as the explanation means the unit will repeat the year exactly." },
            { label: "The decisions that produced the resignation were ordinary supervision decisions: who got the visible project, whose one-on-one was protected, and who was asked to do identity work for free. Those belong to the supervisor, and they can be examined.", response: "Yes. None of it required ill intent and all of it was inside one person's control. Assignment, supervision time and unpaid representation are examinable, and a unit that looks at the pattern over a year will usually find it obvious.", recommended: true },
            { label: "The second analyst should have raised the imbalance with the supervisor, who could not have known it was a problem.", response: "This asks a new employee to negotiate their own development with the person who writes their review, using information they do not have about what everyone else received. The risk sits entirely with them, and the cost of getting it wrong is their reputation in a small division." },
          ],
        },
        transfer: {
          prompt: "Who in your unit has had the visible work in the last year, and who has held the queue?",
          options: [
            "List the substantial assignments of the past year and who received each one",
            "Name what the pattern would look like to somebody who was not chosen",
            "Decide what your next two assignments will be, and tell the person why they are getting it",
          ],
        },
        blocks: [
          { type: "text", heading: "The first month teaches people what is actually true", body: "<p>A new employee spends their first weeks doing two jobs. One is learning the work. The other is reading the place: what is said out loud, what is understood without being said, what happens to people who ask questions, and whether the description in the interview resembles the room.</p><p>Most of what they learn in that second job is taught by logistics. A laptop that arrives in week three teaches that the unit does not plan for new people. Building access that takes a month teaches the same thing more expensively. Software a screen reader cannot use teaches something sharper: that somebody chose this and did not think about you. A first month with no explanation of what good work looks like teaches people to guess, and the ones who guess best are the ones who have worked somewhere like this before.</p><p>Then the ordinary year starts, and the decisions that matter most are the ones that feel smallest. Who gets the redesign and who gets the queue. Whose one-on-one is protected when the calendar gets tight. Who hears about the temporary assignment before it posts. Who is introduced to the director and who is not. Each of these is defensible on its own. Over a year they compose a career, or fail to, and the supervisor who made every one of them can usually not recall making any of them.</p><p>There is one more thing to watch, because it is nearly invisible from above. Some staff carry work nobody assigned and nobody counts: explaining a community to colleagues, translating a document informally because they can, being asked onto every committee that needs to look mixed, and absorbing the distress of coworkers who want somewhere safe to ask. It is real labor. It is unpaid, it is not in the work plan, and it competes directly with the work the person is actually reviewed on. Asking a staff member to represent a community is asking an employee to do a second job for free, on top of a first job they are being judged on.</p>" },
          { type: "tabs", heading: "Four decisions that quietly set retention", tabs: [
            { label: "Assignment", body: "<p>The visible project builds a record: it produces something with the person's name on it, puts them in rooms with decision-makers and gives them something to point at in an interview. The maintenance queue holds the unit together and is invisible at review time. Both jobs need doing. Look at who has done which over a year, not over a week, and rotate the visible work deliberately.</p>" },
            { label: "Access to decision-makers", body: "<p>Careers in public administration move partly on who knows your work. An introduction costs a supervisor one sentence in a meeting. Being the person nobody introduces costs the employee years, and they will rarely know what it cost them.</p>" },
            { label: "Supervision time", body: "<p>A standing one-on-one that is actually held is worth more than any development plan. Canceling it repeatedly says the person is the flexible item on the calendar. When it must move, move it rather than dropping it, and say why.</p>" },
            { label: "How growth is offered", body: "<p>Training budgets, temporary assignments, conference travel and upcoming postings mostly travel informally: a mention in a corridor, a heads-up from somebody who already knows. Whoever is outside those channels is not developing. Write down what is available and tell everyone on the same day.</p>" },
          ] },
          { type: "sorting", id: "ipe-31-3-sort", heading: "Who owns this decision?", categories: ["The supervisor decides this", "The division decides this", "Not the staff member's to carry"], items: [
            { text: "Whether the weekly one-on-one is held or dropped when the calendar gets tight.", category: "The supervisor decides this" },
            { text: "Who is given the high-visibility redesign project this year.", category: "The supervisor decides this" },
            { text: "Whether a new hire's laptop, building access and software are ready on the first day.", category: "The division decides this" },
            { text: "Explaining a community's culture to colleagues who ask, on top of a full workload.", category: "Not the staff member's to carry" },
            { text: "Whether upcoming temporary assignments are announced to everyone or mentioned to a few.", category: "The supervisor decides this" },
            { text: "How long an accommodation request takes to move through the formal route, and how many times the person must explain it.", category: "The division decides this" },
            { text: "Serving on every committee that needs to look representative, without release from other duties.", category: "Not the staff member's to carry" },
            { text: "Whether the unit's onboarding includes somebody saying plainly what good work looks like here.", category: "The supervisor decides this" },
            { text: "Whether the tools the unit is required to use can be operated with a screen reader.", category: "The division decides this" },
            { text: "Negotiating your own development with the person who writes your review, using information about others you do not have.", category: "Not the staff member's to carry" },
          ] },
          { type: "flashcards", heading: "Unpaid work that appears in nobody's work plan", cards: [
            { front: "Representation work", back: "<p>Being asked to speak for a community because of who you are. It is a second job, performed for free, in front of an audience with power over your review. Pay community advisors for expertise; do not convert an employee into one.</p>" },
            { front: "Informal language work", back: "<p>Translating or interpreting for colleagues because you can. It carries real professional risk when the content is technical or legal, and the division has qualified routes for a reason. Use them, and pay for them.</p>" },
            { front: "Emotional labor", back: "<p>Becoming the person everyone brings their distress to. Usually falls on the people already carrying the most, and it is invisible until they leave.</p>" },
            { front: "Committee ballast", back: "<p>Being placed on a group so the group looks mixed, without release from other duties and without influence over the outcome. Presence used as evidence, which is a cost to the person and no benefit to the work.</p>" },
            { front: "Explaining the same barrier repeatedly", back: "<p>Having to re-request the same adjustment each time a system, a supervisor or a room changes. Fix the design once and the requests stop; leave it and the person pays a small tax forever.</p>" },
          ] },
          { type: "leaderMove", heading: "Protect the meeting you scheduled", control: "You control whether a standing one-on-one happens, what it is used for, and whether feedback arrives early enough for the person to act on it.", failure: "Do not let the one-on-one become the item that absorbs every calendar conflict. Reliability is the message; the agenda is secondary. And do not ask a staff member to represent a community on top of a full workload.", next: "This month, hold every one-on-one you have scheduled. When one genuinely must move, move it rather than canceling it, and say so in a sentence." },
          { type: "quote", text: "I was the one they brought to every community meeting. Nobody adjusted my other work, nobody paid me for it, and at review time it did not exist. I was not being valued. I was being used, warmly.", cite: "Composite staff perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-31-3-check", question: "A supervisor reviews a year of assignments and finds the visible projects have gone to the same two analysts, both of whom joined the unit earliest. What is the most useful response?", options: [
            { text: "No action is needed. Each assignment was made on readiness at the time, and experience is a legitimate basis for trusting somebody with visible work.", correct: false },
            { text: "Treat the pattern as the finding rather than defending each decision, name who has not had visible work, and assign the next two projects deliberately with the support that makes them succeed.", correct: true },
            { text: "Raise it at the next team meeting and invite anyone who wants a more visible project to say so.", correct: false },
            { text: "Alternate visible projects strictly by seniority from now on, so the decision is transparent and cannot be questioned.", correct: false },
          ], feedbackCorrect: "Yes. Each decision can be defensible while the pattern is not. Naming who was left out and assigning deliberately, with support, is what changes the next year.", feedbackIncorrect: "Look at what each option does to the pattern. Defending individual decisions preserves it, an open invitation rewards whoever is most comfortable asking, and a rigid rule replaces one automatic outcome with another." },
          { type: "statement", body: "A private reflection, for you alone. Who on your team is doing work that does not appear in their work plan, and what does it cost them? Whose expertise is missing from how your unit decides who gets grown? Nothing you write here is collected, seen or kept." },
        ],
      },
      {
        id: "ipe-31-4",
        number: 4,
        title: "Examine one workforce process",
        summary: "One process, walked end to end as the person going through it, with each step's barrier, the people it stops, the owner, the first fix and a date when somebody checks.",
        minutes: 11,
        learning: {
          objective: "Complete a barrier review of one workforce process you touch, naming each step, who it stops, the owner of the step, the first fix inside your own authority, and the point at which somebody checks.",
          takeaways: [
            "Walking a process is not the same as reviewing it. Reviewing means reading the procedure; walking means following what actually happens, in order, from the position of the person it happens to.",
            "Workforce barriers cluster at five points: finding out the opportunity exists, getting through the application, being selected, arriving and getting set up, and staying and growing.",
            "A complete line names the step, what it screens out, who it stops, the owner, the first fix and the check. A line without an owner and a date is an observation, not work.",
            "Most first fixes are small, free and inside somebody's existing authority. Processes stay broken mainly because nobody has ever walked them.",
            "Some of what you find belongs to a formal office: classification, compensation, accommodation decisions, discipline and complaints. Route those plainly, and keep doing your own step.",
            "The review is worth more than a report if it ends with one changed step. Publish what you changed to the people it affects, including the parts you could not change and why.",
          ],
          evidence: "A scenario about choosing which of four processes to examine, a completed barrier review you can copy, a list of first fixes that need nobody's permission, and a knowledge check on what makes a review line usable.",
          appliedNextStep: "Pick your process this week, block a half day, walk it in order, write the review, make the first fix in the step you own, and put the check on a named person's calendar.",
        },
        scenario: {
          context: "Your unit agrees to examine one workforce process. Four candidates are on the table: the posting and selection for the two positions the unit fills each year; onboarding for new staff; the way stretch assignments are handed out; and the route a staff member takes to request an adjustment they need in order to work, which nobody in the unit can describe from memory. You have about six hours of your own time and no budget.",
          prompt: "Which one do you take, and where do you start?",
          options: [
            { label: "Take the posting and selection, because hiring gets the most attention and any improvement there is visible across the division.", response: "Worth doing, and it runs twice a year, so a fix made now cannot be tested for months. Hiring also already carries oversight from human resources and Minnesota Management and Budget, which means it is the process most likely to have been looked at recently." },
            { label: "Take the request route nobody can describe. Start by writing what actually happens now, step by step, from a staff member's first mention of a need through to the decision and whoever tells them the answer.", response: "Yes. A process nobody can describe from memory is usually failing quietly, and it is failing people who are already paying a cost to use it. Writing the current route is free, takes an afternoon, and the gaps tend to announce themselves as soon as it is on paper.", recommended: true },
            { label: "Take all four at a high level, so the unit has a complete picture before committing to any change.", response: "Four shallow looks produce a summary and a sense of progress. One walked process produces a step, an owner and a fix somebody can make this month. Breadth is the more comfortable choice and the less useful one." },
          ],
        },
        transfer: {
          prompt: "Which workforce process will you walk, and who will ask you what you found?",
          options: [
            "Name the process and the half day you will block for it",
            "Name the colleague who will ask you about the result, and when",
            "Write the barrier you expect to find before you start, then check whether you were right",
          ],
        },
        blocks: [
          { type: "text", heading: "Walk it as the person going through it", body: "<p>Reviewing a process means reading the procedure and looking at the form. Walking it means following what actually happens, in order, from the position of the person it happens to: somebody outside the agency who has never seen a state job posting, a new employee who does not know anyone yet, a staff member who needs something in order to do the work and has to ask a supervisor for it.</p><p>Barriers in workforce processes cluster at five points. <strong>Finding out</strong>: does the opportunity reach people who are not already inside, in words they can read, with enough time to act? <strong>Getting through</strong>: can a person complete the application with the tools and hours they have? <strong>Being selected</strong>: does the process measure the work, or does it measure familiarity and recall speed? <strong>Arriving</strong>: is the person set up, told what good looks like, and introduced to people who matter? <strong>Staying and growing</strong>: is work assigned deliberately, is supervision time protected, and does what a person needs arrive without a month of explaining?</p><p>At each step, write five things: the step, what it screens out, who it stops, who owns it, and the first fix. Then add one line the whole review depends on — who checks, and by when. A review without that line becomes a document. A review with it becomes work.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A barrier review for one workforce process", summary: "One page that turns a walked process into a change somebody owns. Copy the five fields, repeat them for each step, and fill them from the walk rather than from the procedure.", fields: [
            { label: "Process and whose experience you are walking", value: "The route a staff member takes to request an adjustment they need in order to do the work, walked as somebody who has been in the unit four months, has no relationship with human resources, and would rather not tell their supervisor why." },
            { label: "Step and what it screens out", value: "Step two, the first conversation: the only documented way in is “talk to your supervisor.” This screens out anyone whose need is private, anyone whose supervisor is part of the difficulty, and anyone who does not yet know the request is legitimate." },
            { label: "People stopped and the owner of the step", value: "Staff with non-apparent conditions, staff early in a probationary period, and staff who have had a request go badly somewhere else. Owner: the unit manager for the local practice; the department's human resources office for the formal route." },
            { label: "First fix inside your own authority", value: "Write the route down in plain words — where to go, what is asked for, roughly how long it takes, who sees it — publish it where the unit actually looks, and name a second contact so the supervisor is not the only door. Costs an afternoon and no budget." },
            { label: "What belongs to a formal office, and who checks", value: "The decision itself, the medical information handled, and the overall timeline belong to human resources; send them the route as walked, including how long it took. Check: the unit manager reviews at the agreed point and reports what changed to the whole unit, including what did not change and why." },
          ], action: "Copy the five fields, repeat them for each step of your process, walk the process this month, and send the completed review to the owners you named." },
          { type: "list", heading: "First fixes that need nobody's permission", ordered: false, items: [
            "Write the duty each posting requirement protects; delete the ones with nothing beside them.",
            "Name the equivalent experience that counts, in the posting, in words a panel can apply.",
            "Send interview questions in advance and say how long the interview will run.",
            "Put one panel member from outside the hiring unit on every panel.",
            "Publish what a new employee gets in week one, and check the day before they start that it exists.",
            "Say plainly, in the first week, what good work looks like in this unit.",
            "Announce training budgets, temporary assignments and upcoming postings to everyone on the same day.",
            "Hold the one-on-one. Move it rather than canceling it, and say why.",
            "Write down the route for requesting an adjustment, with a second contact who is not the supervisor.",
            "Stop asking staff to represent a community on top of a full workload; pay community advisors instead.",
          ] },
          { type: "flashcards", heading: "Five points where a workforce process stops people", cards: [
            { front: "Finding out", back: "<p>Does the opportunity reach people who are not already inside the agency, in plain words, with enough time to prepare an application?</p>" },
            { front: "Getting through", back: "<p>Can the person complete every step with the tools, hours and support they have, including a keyboard, a screen reader, a phone and a shift that ends at six?</p>" },
            { front: "Being selected", back: "<p>Does the process measure the work described in the position description, or does it measure familiarity, recall speed and comfort in an unfamiliar room?</p>" },
            { front: "Arriving", back: "<p>Is the person set up on day one, told what good work looks like, introduced to people who matter, and given somebody to ask the obvious questions?</p>" },
            { front: "Staying and growing", back: "<p>Is work assigned deliberately across a year, is supervision time protected, does growth travel through channels everyone can reach, and does what a person needs arrive without a month of explaining?</p>" },
          ] },
          { type: "leaderMove", heading: "Fix your own step before you write the report", control: "You control the steps inside your own authority: the wording, the window, the panel, the first week, the assignment, the standing meeting, the second contact.", failure: "Do not send the whole review upward and wait. A review that travels up without a change attached reads as a request for permission, and it usually receives one at about the speed you expect.", next: "Make one first fix in a step you own before the agreed review point, tell the people it affects, and hand the rest to the owners you named with the review attached." },
          { type: "knowledgeCheck", id: "ipe-31-4-check", question: "A barrier review of onboarding finds that new staff often wait weeks for the software they need. Which entry is a complete review line?", options: [
            { text: "Barrier: equipment delays. Fix: improve coordination with the units involved.", correct: false },
            { text: "Barrier: at step four, software requests are submitted after the start date, so new staff wait weeks and some cannot use the standard tools at all. Stops: every new hire, and anyone whose tools must work with a screen reader. Owner: the hiring supervisor for the request, the service desk for fulfilment. First fix: submit requests when the offer is accepted and confirm the day before the start date. Check: the unit manager reviews the next three starts at the agreed point.", correct: true },
            { text: "Barrier: new staff are not proactive about requesting what they need. Fix: include a reminder in the welcome message.", correct: false },
            { text: "Barrier: onboarding is inconsistent across the division. Fix: propose a division-wide onboarding standard for leadership consideration.", correct: false },
          ], feedbackCorrect: "Yes. Step, what it screens out, who it stops, the owner, a specific first fix and a named check. The line can be acted on by somebody who was not in the room.", feedbackIncorrect: "A complete line names the step and the effect, says who is stopped, gives the fix an owner, and ends with who checks and when. Anything that makes the new employee responsible, or defers to a future standard, leaves the next start exactly where it was." },
          { type: "statement", body: "A private reflection, and then one line to keep. Privately: if exclusion happened in this process, what would accountability and repair actually require of your unit, beyond fixing the step? Then write the line you will keep with the work: “The process I will walk this month is… the first fix inside my own authority is… and the person who will ask me about it on… is…” Nothing you write in the reflection is collected, seen or kept." },
        ],
      },
    ],
  },
  jobAid: {
    title: "Inclusive workforce and team culture",
    subtitle: "One page for anyone who writes a posting, sits on a panel, runs an onboarding, hands out work or holds a one-on-one",
    quote: "A values statement is read against the last posting, the last panel and the last canceled one-on-one. The processes are the culture.",
    use: {
      purpose: "Keep the workforce decisions in view while you draft a posting, plan a selection, welcome a new employee, hand out a project, hold a one-on-one or examine a process for barriers.",
      remember: [
        "Culture is the accumulated result of ordinary decisions, and every one of those decisions has an owner with a name.",
        "“We treat everybody the same” describes an intention and hides an effect. Ask who a process works less well for, and where exactly.",
        "A requirement is essential only if the duties cannot be performed without it. Everything else narrows the pool without adding quality.",
        "Discretion applied late cannot recover the people a posting already removed, and it is not applied evenly.",
        "Assignment, access to decision-makers, supervision time and how growth is offered are the four decisions that set retention, and they all sit with a supervisor.",
        "Representation work, informal translating, emotional labor and committee ballast are real work. They are unpaid, uncounted, and they compete with the work the person is reviewed on.",
        "A review line without an owner and a check is an observation. Add both, or it is not work yet.",
      ],
      doNext: "Walk one workforce process end to end this month, write the five review fields for each step, make the first fix inside your own authority, and give the check a name and a date.",
    },
    sections: [
      {
        heading: "Where belonging is actually settled",
        items: [
          "How the work is described: the position description and whether the duties match the real job.",
          "How it is posted: requirements, wording, where it is advertised, how long it stays open, how long the application takes.",
          "Who selects: the panel, the questions, when candidates see them, the format, what counts as a good answer.",
          "The first month: equipment and access on day one, a named contact, and somebody saying what good work looks like.",
          "How work is assigned: who gets the visible project, who holds the queue, and whether anyone looks at the pattern over a year.",
          "How supervision time is spent and whether the one-on-one is actually held.",
          "How growth is offered: who hears about a budget, an assignment or a posting first.",
        ],
      },
      {
        heading: "Before you post a job",
        items: [
          "Write the duty each requirement protects. Delete every line with nothing beside it.",
          "Name the equivalent experience that counts, in the posting, in terms the panel can apply.",
          "Read the draft as somebody who has never worked in state government; remove the internal shorthand.",
          "Time the application. Four hours is a price some capable people cannot pay.",
          "Check that every step works with a keyboard and a screen reader, and name a contact for anyone who needs the process to work differently.",
          "Give the window enough working days to be usable, and avoid holiday weeks.",
        ],
      },
      {
        heading: "Before the panel meets",
        items: [
          "Send the questions in advance and say how long the interview will run.",
          "Offer a remote option, and say where the accessible entrance is for anyone coming in person.",
          "Ask the same questions of everyone so answers can be compared.",
          "Put at least one member from outside the hiring unit on the panel.",
          "Agree beforehand how equivalent experience will be weighed, so it is not decided in the room.",
          "Where the role touches services, consider a paid community advisor rather than an unpaid one.",
        ],
      },
      {
        heading: "The first month",
        items: [
          "Order equipment, access and software when the offer is accepted; confirm the day before the start date.",
          "Name a first-week contact for the obvious questions nobody wants to ask their supervisor.",
          "Say plainly what good work looks like here, in the first week rather than at the first review.",
          "Explain the unwritten rules, including how decisions are actually made and who to ask about what.",
          "Introduce the person to the people whose work touches theirs, by name.",
          "Tell them how to ask for what they need in order to work, and who else they can ask besides you.",
        ],
      },
      {
        heading: "Assignment, supervision and growth",
        items: [
          "Look at a year of assignments, not a week. Rotate the visible work deliberately and say why somebody is getting it.",
          "Hold the one-on-one; move it rather than canceling it.",
          "Announce training budgets, temporary assignments and upcoming postings to everyone on the same day.",
          "Make an introduction. It costs a sentence and the absence of it costs years.",
          "Do not ask a staff member to represent a community on top of a full workload. Pay community advisors for expertise.",
          "Give feedback early enough to act on, and separate coaching from the review record.",
        ],
      },
      {
        heading: "The barrier review, in short",
        items: [
          "Process and whose experience you are walking.",
          "Step and what it screens out.",
          "People stopped and the owner of the step.",
          "First fix inside your own authority.",
          "What belongs to a formal office, and who checks, by when.",
          "Publish what changed to the people it affects, including what did not change and why.",
        ],
      },
      {
        heading: "Formal decisions, and the offices that make them",
        items: [
          "Recruitment rules, classification, compensation and statewide hiring practice: the department's human resources office and Minnesota Management and Budget.",
          "Accommodation requests and the information that comes with them: the department's human resources office through its formal route, not the supervisor's desk drawer.",
          "Equal opportunity questions, affirmative action obligations and discrimination concerns: the department's equal opportunity and legal offices, and the Minnesota Department of Human Rights.",
          "Discipline, grievances and conduct matters about a named employee: human resources, separately from any process review.",
          "Accessibility of the systems and documents a unit is required to use: the offices that own the standard and the contract.",
          "Anything involving Tribal Nations or tribal human services: the Department of Human Services offices that handle tribal matters and the Office of Indian Affairs, first and always.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Supervisors and managers, who own most of the decisions in this module — a good place to start, and the shortest distance between reading it and changing something.",
          "Communications and training staff, who write the postings, the onboarding materials and the internal messages that teach people what is expected here — a good module to go deeper with.",
          "Executive and senior leaders, who decide whether culture work means a campaign or an examined process, and who own the systems, tools and timelines a unit cannot change alone — a good module to go deeper with.",
          "Policy, program and operations staff, whose position descriptions and duty statements set what a posting is allowed to require.",
          "Quality and performance staff, who can look at assignment and retention patterns across a year rather than one decision at a time.",
          "Fiscal, contracts, grants and procurement staff, who decide whether the tools a unit must use are usable, and whether community advisors are actually paid.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "Leading a reflective DSD team",
          "Equitable policy and procedure governance",
          "Quality, complaints, and incident learning",
          "Inclusive learning and knowledge design",
          "Resource allocation and equity",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Management and Budget, building a diverse state workforce", href: "https://mn.gov/mmb/careers/diverse-workforce/", note: "Minnesota Management and Budget administers statewide hiring practice for executive branch agencies; this section covers the state's approach to recruiting and hiring a workforce that reflects Minnesota, including information for job seekers with disabilities." },
    { title: "U.S. Equal Employment Opportunity Commission, disability discrimination", href: "https://www.eeoc.gov/disability-discrimination", note: "Federal guidance on disability discrimination in employment under the Americans with Disabilities Act, including what employers may ask, what qualifies as a reasonable accommodation, and the difference between essential functions and preferences." },
    { title: "Job Accommodation Network", href: "https://askjan.org/", note: "Free, practical guidance on workplace accommodations by condition and by job function, funded by the U.S. Department of Labor; useful when a unit wants to know what an adjustment typically involves before assuming it is complicated or expensive." },
    { title: "Minnesota Council on Disability, employment", href: "https://www.disability.state.mn.us/employment/", note: "Minnesota's advisory council on disability policy and rights, including employment information for Minnesota employers and workers with disabilities." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas/standards", note: "National standards for culturally and linguistically appropriate services, including the governance, leadership and workforce standards on recruiting, promoting and supporting a workforce responsive to the population served, and on educating that workforce." },
    { title: "Section508.gov", href: "https://www.section508.gov/", note: "Federal guidance on accessible information and communications technology and documents, used here for the requirement that application systems, onboarding materials and everyday work tools be usable with assistive technology." },
    { title: "plainlanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Practical guidance for writing documents people can act on, applied here to job postings, onboarding materials and the written route for requesting a workplace adjustment." },
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials and accessible instruction without timed or scored interactions." },
  ],
};

export default pack;
