import type { CoursePack } from "../../source-types";

// Intercultural Practice and Equity · Internal leadership · Module 36: Leading difficult dialogue.
// Program-authored for internal DHS and DSD staff. Voluntary, self-directed, no scores and no completion requirement.
const pack: CoursePack = {
  course: {
    id: "ipe-36-leading-difficult-dialogue",
    indexNumber: 1178,
    seriesLabel: "Intercultural Practice and Equity · Internal leadership",
    title: "Leading Difficult Dialogue",
    subtitle: "Conversations about disability, ableism, racism, identity, power and exclusion fail in predictable ways, and most of what decides them happens before anyone speaks. Four lessons on preparing and holding a conversation that examines the work without requiring anyone to agree or to disclose anything, ending with a discussion plan you can take into a real team meeting.",
    scope: "For internal DHS and DSD supervisors and managers, and for executive and senior leaders who set the conditions for these conversations across a division. Useful to anyone who runs a recurring meeting, leads a workgroup, holds a review after something went wrong, or has been handed the conversation nobody wants to lead. Four short lessons you can take in any order and return to. Voluntary and self-directed: no score, no ranking, no completion requirement, and nothing you write in a reflection is collected. This module never asks you, or anyone in a room you lead, to disclose an identity, a diagnosis, a belief, a political view or a private experience. Completion here does not count toward DHS-required training credits unless management, a director, or DHS leadership expressly approves an exception.",
    treatment: "Four short lessons with Minnesota DSD examples, scenarios, sorting and flashcard practice, private reflection prompts, and a discussion plan you can fill in for one real team issue",
    duration: "40–45 minutes",
    author: "One DSD — People, Access and Culture",
    coverImage: "/images/covers/stock-people-10.jpg",
    coverAlt: "Four colleagues talking together in a bright office space.",
    introTranscript: "Almost every hard conversation in public work is lost before anyone speaks. It is lost in an invitation that asked people to reveal something instead of examine something, in a note-taker whose summary goes somewhere nobody was told about, in a room where the person with the most at stake has the least protection, and in an opening that never said whether anything could still change. This module takes those conditions apart in order: what the hour is actually for, what you set before it starts, the five moments in the room that decide it, and how to write an eight-line discussion plan for one issue your team is really carrying. It never asks anyone to agree, and it never asks anyone to talk about themselves.",
    kind: "course",
    contentType: "practice",
    learning: {
      objectives: [
        "Name what a particular hard conversation is for before you open it, and say out loud what is already decided and what is genuinely open.",
        "Set the conditions that decide what people are willing to say: the invitation, who is in the room, the record, the opt-out, access, and who facilitates.",
        "Write ground rules that describe observable behavior rather than attitudes, and that nobody has to disclose anything in order to be covered by.",
        "Respond to the five moments that decide a hard conversation without shaming anyone, requiring agreement, or asking one person to speak for a group.",
        "Write and use a discussion plan for one real team issue, with an opening frame, three prepared moves, and a report-back that has an owner and a date.",
      ],
      evidence: [
        "Four worked scenarios from internal division work — a notice that a paid advisory group called accusatory, an all-staff session planned after a staff engagement round, a review that turns toward a step the supervisor approved, and a plan that is really a defense plan — each with a recommended response and the reasoning behind it.",
        "A knowledge check in every lesson with feedback that explains the usable answer.",
        "Sorting practice that separates a request to disclose from an invitation to examine the work, and that shows where a single sentence sends a conversation.",
        "A completed discussion plan for one real issue, with the opening frame written out in full and the report-back already on somebody's calendar.",
      ],
      appliedNextStep: "Choose one issue your team is actually carrying. Write the eight lines, read the opening frame aloud once before you use it, hold the conversation within the month, and give the report-back a name and a date before anyone leaves the room.",
    },
    governance: {
      contentOwner: "One DSD — People, Access and Culture",
      reviewers: ["Equity and Inclusion Operations Consultant"],
      evidenceDate: "Public sources checked at authoring",
      lastReviewed: "At authoring",
      nextReview: "At the agreed review point and whenever an update trigger occurs",
      updateTriggers: [
        "A change in Minnesota Management and Budget statewide human resources policy affecting respectful workplace expectations, supervisory responsibility, or where a formal personnel matter belongs",
        "A change in Minnesota Department of Human Rights guidance or in DHS civil rights practice that moves the boundary between a team conversation and a formal complaint of discrimination, harassment or retaliation",
        "Feedback from supervisors, staff or paid community advisors that a scenario here does not match how a real division review, staff session or partner conversation actually goes",
      ],
      relatedDoor: "Formal complaints of discrimination, harassment or retaliation, grievances, investigations, discipline, accommodation requests and personnel records belong to the responsible DHS human resources, labor relations, civil rights and legal offices; this module helps you prepare and hold a conversation inside your own area, and it never investigates, decides or records a personnel matter.",
      toolkitQuestion: "What did the last hard conversation I led cost the person who spoke first, and would they raise it again?",
      status: "reviewed",
    },
    lessons: [
      {
        id: "ipe-36-1",
        number: 1,
        title: "What the hour is actually for",
        summary: "Four different conversations arrive wearing the same clothes. An hour that tries to hold all of them settles into whichever one has a deadline behind it.",
        minutes: 10,
        learning: {
          objective: "Name what a particular hard conversation is for before you open it, separate the parts that belong in a different room, and say what is already decided in the first two minutes.",
          takeaways: [
            "Four conversations are usually asked to share one hour: settling a decision, accounting for what happened, examining the effect of the work on people, and repairing something the division cost somebody. Each needs different conditions, and run together they collapse into the one with a date attached.",
            "A dialogue asks people to examine evidence, decisions and effects. It does not ask them to agree, to declare a position, or to describe their own identity, health, politics or private life. An hour that cannot proceed without a disclosure has quietly become a request.",
            "Naming the purpose out loud in the first two minutes does more for a hard conversation than any technique used later in it.",
            "If the decision is already made, say so first. Staff can tell, and a consultation that turns out to be a notification spends trust you will need the next time you ask for something.",
            "The people most affected by a process are usually outside the division. If the hour is about them and they are not in it, say that plainly rather than letting a staff conversation stand in for their expertise.",
          ],
          evidence: "A scenario about a review of a services notice a paid advisory group called accusatory, four tabbed views of the same hour, and a knowledge check on what an opening has to settle.",
          appliedNextStep: "Take the next hard conversation on your calendar and write two sentences: what this hour is for, and what it is not for. Read both aloud when you open it.",
        },
        scenario: {
          context: "A paid community advisory group has told your division that a redesigned services notice reads as if the person receiving it is suspected of doing something wrong, and that the paragraph about services ending appears well before the paragraph about how to ask a question. The analyst who drafted it heard this second-hand and is upset. The notice is due at the printer in ten days, and the wording decision sits with the communications lead. You have one hour with the unit on Thursday.",
          prompt: "What do you set that hour up to do?",
          options: [
            { label: "Open with the advisory group's feedback and let the conversation go wherever the team needs it to go.", response: "It sounds respectful and the result is predictable. The analyst defends a draft, the print date pulls everything toward the decision, and careful feedback ends the hour as one more opinion in a busy week. When a purpose is not named, the strongest pressure in the room supplies one." },
            { label: "Say in the first two minutes that the hour is for understanding what the notice does to somebody reading it, that the wording decision sits with the communications lead and returns next week with a named owner, and that nobody is being asked to defend or apologize for a draft.", response: "This separates three things that were about to be fused: the effect, the decision and the person. It also tells the analyst, before she has to guess, that her draft is not on trial. The advisory group's finding gets the only hour in which it could still change anything.", recommended: true },
            { label: "Hold the conversation after the print date, when the team is not under deadline pressure.", response: "It protects the meeting and spends the only window in which anything could change. It also teaches a group you are paying that their findings arrive too late to matter, which is the most expensive lesson on this list." },
          ],
        },
        transfer: {
          prompt: "Think about the next hard conversation you are expected to lead. What is it actually for?",
          options: [
            "Write one sentence naming what the hour is for, and one naming what it is not for",
            "Decide which part belongs in a different room, and say out loud where it will go",
            "Check what in it is already decided, and plan to say that before anything else",
            "Name the person who will hear what changed, and the date they will hear it",
          ],
        },
        blocks: [
          { type: "text", heading: "Four conversations, one hour", body: "<p>Ask three people what a hard conversation is for and you will often get three answers that cannot be satisfied in the same hour. One wants a decision settled. One wants an account of what went wrong. One wants the effect of the work examined. And somebody in the room, often the person who has not spoken yet, wants something repaired. All four are legitimate. Held together, they collapse into whichever one has a deadline behind it, which is almost always the decision.</p><p>They are worth keeping apart because each needs different conditions. A decision needs to know who decides and by when. An account needs the conditions that made the result likely rather than the name of whoever was nearest. An examination needs evidence, disagreement and enough time for people who think before they speak. Repair needs acknowledgment before explanation, and it needs the people affected present, or represented by somebody they chose and who is paid for the time, rather than described in their absence.</p><p>Naming which one you are holding takes about twenty seconds and changes the whole hour. “This is not where the wording gets decided; that comes back next week with a named owner. This hour is for understanding what this notice does to somebody reading it at a kitchen table.” Now nobody is guessing at the terms, nobody is defending a draft, and the person who raised the problem can see that it did not evaporate on contact with a deadline.</p><p>There is one more thing to name, and it is the one most often left unsaid. A dialogue examines the work: decisions, evidence, effects, who is reached easily and who is burdened. It does not require agreement, and it does not require anybody to describe their own identity, health, politics or private life. If the hour cannot proceed unless somebody discloses something, it has stopped being a dialogue, and the person carrying the disclosure is paying for everyone else's learning.</p>" },
          { type: "tabs", heading: "The same hour, four purposes", tabs: [
            { label: "Settling a decision", body: "<p>Something has to be chosen: wording, a date, a threshold, a route. Say who decides, on what basis, and by when. If it is already decided, say that in your first breath. A consultation that turns out to have been a notification is remembered for a long time, and it makes the next invitation harder to fill.</p>" },
            { label: "Accounting for what happened", body: "<p>Something went wrong and the division needs to understand it. The useful question is what made that result the reasonable thing to do with the tools, information and time people actually had. An account that ends at a name closes the matter and leaves the condition in place for the next person in a hurry.</p>" },
            { label: "Examining the work", body: "<p>The process itself is on the table: who it reaches easily, who it burdens, who never appears in it at all. Evidence belongs here, including what paid reviewers and partners have already told you. Disagreement is the point of the hour rather than a sign it is going badly.</p>" },
            { label: "Repairing something", body: "<p>The division did something that cost somebody. Acknowledgment comes first and explanation second. The people affected are present or represented by somebody they chose and who is compensated, and the fix is specific enough that a person outside the division could check whether it happened.</p>" },
          ] },
          { type: "leaderMove", heading: "Say what the hour is for before anyone speaks", control: "You control the first two minutes: what this conversation is for, what it is not for, what is already decided, and what happens to whatever gets raised.", failure: "Do not open with “we just wanted to have an open discussion about this.” An unnamed purpose gets filled by whoever carries the most pressure or the most standing, and everyone else spends the hour working out the terms from clues.", next: "Before your next hard conversation, write the two sentences — what this hour is for, and what it is not for — and read both out loud at the start." },
          { type: "flashcards", heading: "Five things to settle before you open", cards: [
            { front: "Which of the four is this?", back: "<p>A decision, an account, an examination or a repair. Say it out loud. If two of them honestly belong in the same hour, say which one comes first and how much of the time it gets.</p>" },
            { front: "What is already decided?", back: "<p>Say it in the first two minutes. People find out either way, and finding out late converts a hard conversation into a lasting lesson about what consultation means here.</p>" },
            { front: "What is nobody being asked to do?", back: "<p>Nobody is being asked to agree, to declare a position, or to describe an identity, a diagnosis, a belief or a private experience. Saying this is not a formality. It changes who is willing to speak.</p>" },
            { front: "Who is missing?", back: "<p>If the hour is about what a process does to people outside the division, the expertise you need is outside the division. Bring it in early and pay for it, or say plainly that this is only the staff half of the question.</p>" },
            { front: "What happens afterward?", back: "<p>An owner, a date, and one sentence people will hear about what changed and what did not. Without those three, the hour was a release of pressure and everybody knows it.</p>" },
          ] },
          { type: "quote", text: "I sat through ninety minutes about a form I wrote. Nobody said at the start whether the form could still change. I spent the whole hour defending a draft that had already been replaced, and the person who raised the actual problem never got an answer.", cite: "Composite staff perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-36-1-check", question: "You are opening an hour on a notice that a paid advisory group says reads like an accusation. The printer deadline is ten days away and the wording decision sits with the communications lead. Which opening is most usable?", options: [
            { text: "“We want an open, honest conversation today. Everything is on the table.”", correct: false },
            { text: "“This hour is for understanding what this notice does to the person reading it. The wording decision sits with the communications lead and comes back next Thursday. Notes carry decisions and open questions, nobody is named, and nobody is being asked to defend a draft.”", correct: true },
            { text: "“Before we start, it would help if people shared their own experiences of receiving a notice like this one.”", correct: false },
          ], feedbackCorrect: "Yes. Purpose, who decides and when, what is written down, and what nobody is being asked to do — all of it in about twenty seconds, before anyone has to guess.", feedbackIncorrect: "Ask what each opening leaves people to work out for themselves: whether the notice can still change, who decides, what is recorded, and whether they are expected to talk about their own lives." },
        ],
      },
      {
        id: "ipe-36-2",
        number: 2,
        title: "Conditions, not courage",
        summary: "What people are willing to say is set by the invitation, the room, the record and the opt-out. A skilled facilitator cannot repair conditions in the room that were set badly outside it.",
        minutes: 11,
        learning: {
          objective: "Set the conditions for a hard conversation before it starts — invitation, room, record, opt-out and access — and rewrite two ground rules so they describe behavior anybody in the room could point at.",
          takeaways: [
            "Most of what will happen has been decided before anyone speaks: who was invited, what the invitation said the hour was for, who else is present, what gets written down, and whether declining costs anything.",
            "Power in the room is a fact, not a mood. A staff member cannot leave a bad conversation with a director the way a director can, and a colleague on a performance plan or with a pending accommodation request is carrying something nobody else can see. Saying “feel free to disagree with me” does not change the arithmetic.",
            "People decide what to say based on what they believe is being recorded. Say what the notes carry, who receives them, whether anybody is named, and what stays in the room. Unclear recording terms produce careful sentences, and careful sentences are not what the hour needs.",
            "Ground rules that describe attitudes — assume good intent, be brave — cannot be checked and quietly favor whoever is already comfortable. Rules that describe behavior can be used by anybody present, including on the person leading.",
            "Access is part of the design rather than an exception granted on request: materials ahead of time as real text, captions on by default, interpreters booked before the schedule hardens, a reachable room, a pace that allows people to think, and more than one way to take part.",
            "An invitation to “share your experience as a disabled employee” turns a colleague into an exhibit. Ask instead what the process does to the people it reaches, and let anyone who wants to bring their own experience do it on their own terms.",
          ],
          evidence: "A scenario about an all-staff session planned after a staff engagement round, sorting practice separating a request to disclose from an invitation to examine the work, and a knowledge check on ground rules.",
          appliedNextStep: "Rewrite the invitation for your next hard conversation so it names the purpose, what is already decided, how to take part, what is recorded, and what nobody will be asked to disclose.",
        },
        scenario: {
          context: "A division staff engagement round produced comments that disabled employees and employees who work through interpreters are routinely talked over in unit meetings and left out of decisions made in the last five minutes. An assistant commissioner asks you to run a ninety-minute all-staff session next week. The draft invitation calls it a safe space to share your lived experience. She plans to attend, and a note-taker will send a summary to the leadership team.",
          prompt: "What do you change before the invitation goes out?",
          options: [
            { label: "Keep the invitation warm and open as it is; rewriting it will make the session feel bureaucratic before anyone arrives.", response: "The invitation is already doing a great deal of work. It asks people to reveal something rather than examine something, it promises a safety the room cannot deliver, and it says nothing about where what they say will end up. Warmth is not the problem here; the unstated terms are." },
            { label: "Rewrite it: name the purpose and what leadership will do with what they hear, say what is recorded and who receives it, ask about the process rather than about people's lives, offer a written route and a small-group route, say that attending is optional and that declining costs nothing, and decide honestly whether the assistant commissioner's presence helps or compresses.", response: "Every one of these is a condition, and all of them are yours to set. The one that takes courage is the last: presence at the top of a division changes what can be said, and deciding it on the evidence rather than on protocol is the difference between a session and a performance.", recommended: true },
            { label: "Make attendance required, so that no group ends up under-represented, and leave the rest of the invitation as drafted.", response: "Required attendance at a conversation about exclusion produces compliance rather than information. It also puts the heaviest risk on the people with the most at stake, who now cannot quietly decline, while leaving every other term of the invitation unstated." },
          ],
        },
        transfer: {
          prompt: "Look at the invitation for a conversation you are planning, or the last one you sent.",
          options: [
            "Name what the hour is for and what will happen to what people say",
            "Replace any request for personal experience with a question about the process",
            "Say what is recorded, who receives it, and what stays in the room",
            "Offer at least two ways to take part, including one that is not speaking in a group",
            "Say plainly that taking part is optional and that declining costs nothing",
          ],
        },
        blocks: [
          { type: "text", heading: "Most of it happens before anyone speaks", body: "<p>By the time people are in the room, most of what is going to happen has already been settled. Who was invited and who was not. What the invitation said the hour was for. Whether a senior leader will be there. Whether notes go somewhere. Whether saying no costs anything. Whether the materials arrived in a form everybody can read, two days ahead rather than two minutes ahead. People read all of that accurately and adjust what they are prepared to say, usually without deciding to.</p><p>This is why technique inside the room is the smaller half of the job. No facilitator, however skilled, can undo an invitation that asked people to reveal something, a note-taker whose summary reaches leadership without anyone being told, a room that can only be entered by a staircase, or a session scheduled in the one hour the interpreter is not available. Those are conditions, and a leader sets them, deliberately or by accident.</p><p>Two of them are worth naming out loud rather than managing quietly. The first is power. A staff member cannot leave a bad conversation with a director in the way a director can leave it. A temporary employee, a person on a performance plan, and a person whose accommodation request is still pending are each carrying something into the room that nobody else can see. Warmth does not dissolve that, and neither does an invitation to speak freely. What helps is naming the asymmetry, providing a route that does not run through you, and then behaving well the first time somebody uses it.</p><p>The second is the record. People calibrate what they say to what they think is being written down, and in the absence of information they assume the worst version. So say it: what the notes will carry, who receives them, whether anyone is named, what stays in the room. If leadership needs a summary, say so, and say what will be in it. Honest recording terms cost you a sentence and buy you the only thing that makes the hour worth holding.</p>" },
          { type: "list", heading: "What you set before anyone speaks", items: [
            "The invitation: what the hour is for, what is already decided, and what nobody will be asked to disclose.",
            "Who is in the room, and whether a senior leader's presence adds weight to the outcome or compresses what people are willing to say.",
            "The record: what the notes carry, who receives them, whether anybody is named, and what stays in the room.",
            "The opt-out: that taking part is optional, that declining costs nothing, and that there is a written route for anyone who would rather not speak in a group.",
            "Access as a default rather than a request: materials ahead of time as real text, captions on, interpreters booked before the schedule hardens, a reachable room, and a pace that allows people to think.",
            "Time: enough of it that the hardest thing anyone has to say is not the thing said with four minutes left.",
            "Who facilitates, and whether it should be you at all when the conversation is partly about decisions you made.",
          ] },
          { type: "sorting", id: "ipe-36-2-sort", heading: "Disclosure, examination, or a condition you set?", categories: ["A request to disclose", "An invitation to examine the work", "A condition the leader sets"], items: [
            { text: "“Tell us what it has been like for you as a disabled employee in this division.”", category: "A request to disclose" },
            { text: "“Which step in this process would be hardest for somebody who cannot use the online form?”", category: "An invitation to examine the work" },
            { text: "“Notes carry decisions and open questions, nobody is named, and the leadership team receives the summary.”", category: "A condition the leader sets" },
            { text: "“Would anyone from an underrepresented group like to start us off?”", category: "A request to disclose" },
            { text: "“What has this change made harder, and for whom?”", category: "An invitation to examine the work" },
            { text: "“Materials go out two working days ahead as real text, and captions are on by default.”", category: "A condition the leader sets" },
            { text: "“If you would rather write than speak, here is where it goes and who reads it.”", category: "A condition the leader sets" },
            { text: "“It would really help if someone shared a personal story so the group understands why this matters.”", category: "A request to disclose" },
            { text: "“Here are the closure numbers broken out by how the notice was delivered. What do you see in them?”", category: "An invitation to examine the work" },
          ] },
          { type: "accordion", heading: "Four conditions to name out loud rather than manage quietly", items: [
            { title: "The power in the room", body: "<p>Say who is present and what that means. “I am the person who approved this step, and a director will read the summary” is more useful than any assurance that people should feel free to speak. Then give at least one route that does not run through you — a peer, a written line, a small group with somebody else in it — and treat what arrives that way as seriously as what is said to your face.</p>" },
            { title: "The record", body: "<p>What the notes carry, who receives them, whether anybody is named, and what stays in the room. If a summary goes upward, say what will be in it. If nothing is written, say that too. The most damaging version is the one where people find out afterward that the terms were different from what they assumed.</p>" },
            { title: "The opt-out, and what it costs", body: "<p>Attendance at a conversation about exclusion has to be genuinely optional, and declining has to cost nothing that anyone can observe. That means no roll call, no follow-up asking why somebody was not there, and a route that lets a person contribute without appearing. A group that feels compelled will supply agreement, which is the one thing the hour does not need.</p>" },
            { title: "Access, and what nobody has to ask for", body: "<p>Decide what arrives by default for everybody: materials ahead of time as real text rather than images of text, captions on, an interpreter booked around the person rather than the schedule, a room people can reach, a pace that allows processing, and one open line about what somebody needs in order to take part. Access that depends on a person requesting it in front of colleagues is access with a price attached.</p>" },
          ] },
          { type: "leaderMove", heading: "Write rules anybody could use on you", control: "You control whether the ground rules describe attitudes nobody can check or behavior anybody in the room can point at, including on the occasions when the person who missed them is you.", failure: "Do not open with “assume good intent” and “be brave.” The first hands the work of interpretation to whoever was hurt; the second asks the people with the least protection to take the most risk, and calls it a value.", next: "Replace two rules with observable ones before your next session: how the first ten minutes run, and what happens when something somebody says lands badly." },
          { type: "statement", body: "A private reflection, kept by you and collected nowhere: think of the last conversation you invited people into. Did the invitation ask them to examine something or to reveal something? And who in that room had the most to lose by answering it honestly?" },
          { type: "knowledgeCheck", id: "ipe-36-2-check", question: "Which ground rule could actually be used by anybody in the room six months from now?", options: [
            { text: "We assume good intent and give each other grace.", correct: false },
            { text: "When something lands badly we say so in the moment, and the person who said it listens first and answers without defending.", correct: true },
            { text: "This is a brave space, and we encourage everyone to be open and vulnerable.", correct: false },
          ], feedbackCorrect: "Yes. It describes what people do, it applies to the person leading exactly as much as to anyone else, and somebody can point at it without accusing a colleague of a bad character.", feedbackIncorrect: "Ask of each rule: could a new colleague read it and know what to do, could anyone tell afterward whether it happened, and does it quietly ask the person with the least protection to carry the most risk?" },
        ],
      },
      {
        id: "ipe-36-3",
        number: 3,
        title: "The five moments in the room",
        summary: "Hard conversations turn on the same handful of moments every time. Under pressure you will use whatever move is nearest, so choose the moves in advance.",
        minutes: 11,
        learning: {
          objective: "Respond to the five moments that decide a hard conversation — harm named, defensiveness, silence, one person asked to speak for a group, and pressure for agreement — without shaming anyone or requiring anybody to agree.",
          takeaways: [
            "Acknowledge before you explain. “That is a real effect and I want to understand it” concedes nothing about intent and costs nothing you need. The explanation is still owed; it lands very differently in second place.",
            "Defensiveness is usually a person protecting their standing rather than their argument. Return the standing — nobody's character is on the table — and move the subject back to the rule, the evidence and the effect.",
            "Silence is information about the conditions, not agreement. Ask a narrower question, offer the written route, or say what will happen to anything raised later, and let three seconds pass before you fill it yourself.",
            "Asking one person to speak for a group does two things at once: it burdens them and it excuses everyone else. A specific account is specific — it is evidence about a process, not a representative sample and not a complaint to be discounted.",
            "Agreement is not the goal. A useful hard conversation can end with people still disagreeing, as long as everyone knows what was decided, who decided it, what is still open, and where the disagreement was written down.",
            "Treating everyone identically is Minimization, not fairness. Acceptance begins when a real difference in how people meet the same process is allowed back into the room as information about the design, and then actually checked.",
          ],
          evidence: "A scenario in which a review turns toward a step the supervisor approved, flashcards giving the move for each of five moments, sorting practice on where a single sentence sends a conversation, and a knowledge check.",
          appliedNextStep: "Pick the one of the five moments you handle worst, write the sentence you will say next time, and say it out loud once before you need it.",
        },
        scenario: {
          context: "Midway through a review you are facilitating on why a renewal process closed a number of cases for non-response, a staff member says the real problem is a delivery rule: mail returned from certain addresses is treated as non-response, and the people it closes are people who move often and people who work through interpreters. The colleague who designed the step says he finds the implication insulting and that every case is treated identically. The room goes quiet and two people look at you. You approved the step.",
          prompt: "What do you say next?",
          options: [
            { label: "Say that both points are fair, that everyone is working hard under real constraints, and move to the next item so the meeting can recover.", response: "It ends the discomfort in about four seconds, and it teaches the room that naming an uneven effect costs more than staying quiet. Nothing about the delivery rule has been examined, and the next person who notices something will do the arithmetic you just showed them." },
            { label: "Say that identical treatment is precisely what is being examined and that nobody's character is on the table, ask her what pattern she has seen, say that you approved the step and want the numbers, and name who brings them back and when.", response: "Four things in one turn: the colleague's standing is returned, the subject goes back to the rule, your own part is named out loud, and the question leaves the room with an owner and a date instead of as an impression.", recommended: true },
            { label: "Ask the two of them to work it out between themselves and bring you a recommendation.", response: "It hands a difference in standing to two colleagues with no structure around it, protects you from hearing the part that concerns your own decision, and tells the room that you will not stay in a hard moment. The person with less standing will not press it a second time." },
          ],
        },
        transfer: {
          prompt: "Which of the five moments do you handle worst?",
          options: [
            "Write the sentence you will say the next time somebody names an uneven effect",
            "Practice one sentence that moves the subject from a person back to the decision",
            "Decide in advance what you will do when the conversation reaches your own decision",
            "Plan what you will say when a room goes quiet, instead of filling it",
          ],
        },
        blocks: [
          { type: "text", heading: "The same five moments, nearly every time", body: "<p>Most hard conversations turn on a handful of moments, and they are the same moments almost every time. Somebody names an effect the work is having on people. Somebody else hears it as an accusation. The room goes quiet. One person is asked, directly or by everyone turning to look at them, to speak for a whole group. And somebody presses for the thing that would end the discomfort fastest, which is agreement.</p><p>None of these calls for eloquence. What they call for is a decision you have already made, because under pressure you will use whatever move is nearest to hand, and what is nearest to hand is almost always the move that ends the discomfort: reassurance, a change of subject, or an offer to take it offline. Each is comfortable in the moment and expensive afterward, because the room is watching to learn the price of the next observation.</p><p>One principle sits underneath all five: the subject of the sentence is the work. An uneven effect is information about a design, not a claim about anyone's character. A staff member who says a delivery rule closes cases for people who move often is describing the rule. Keeping the conversation on the rule protects two people at once — the person who raised it, who is not asking anybody to confess anything, and the colleague who built it, who is not being accused of anything.</p><p>This is also where a careful, well-meaning room settles into Minimization: the belief that because everyone is treated identically, everyone experiences the same thing. It sounds like fairness, and it removes exactly the differences the hour exists to examine. Moving toward Acceptance does not mean agreeing that a criticism is correct. It means letting the difference back into the room as information about the design, and then going and finding out.</p>" },
          { type: "flashcards", heading: "Five moments and the move for each", cards: [
            { front: "Somebody names harm or an uneven effect", back: "<p>Acknowledge before you explain. “That is a real effect and I want to understand it” concedes nothing about intent and costs you nothing you need. The explanation is still owed, and it will be heard once the acknowledgment has been made.</p>" },
            { front: "A colleague becomes defensive", back: "<p>Say plainly that nobody's character is on the table, then move the subject back to the rule, the evidence and the effect. Defensiveness is usually somebody protecting their standing rather than their argument, and returning the standing is what frees them to look at the work.</p>" },
            { front: "The room goes quiet", back: "<p>Silence is information about the conditions, not agreement. Ask a narrower question, offer the written route, or say what will happen to anything raised later — and let three seconds pass before you fill it yourself.</p>" },
            { front: "One person is asked to speak for a group", back: "<p>Take it off them: “I do not want to put that on one person. Let us look at what the process does.” Then treat a specific account as specific — evidence about a step, neither a representative sample nor a complaint to be discounted.</p>" },
            { front: "Somebody presses for agreement", back: "<p>Say that agreement is not what this hour is for. People can leave still disagreeing as long as everyone knows what was decided, who decided it, what remains open, and where the disagreement was written down.</p>" },
          ] },
          { type: "sorting", id: "ipe-36-3-sort", heading: "Where does this sentence send the conversation?", categories: ["Back to the work", "Onto a person", "Quietly out of the room"], items: [
            { text: "“Which returned addresses are treated as non-response, and what happens to the case after that?”", category: "Back to the work" },
            { text: "“Can you show me the pattern you have seen, even roughly?”", category: "Back to the work" },
            { text: "“I approved that step, so I want the numbers on it.”", category: "Back to the work" },
            { text: "“What would have to be true for this not to be happening?”", category: "Back to the work" },
            { text: "“I am sure nobody meant anything by it.”", category: "Onto a person" },
            { text: "“Are you saying our staff are biased?”", category: "Onto a person" },
            { text: "“That is a fair point. Let us take it offline.”", category: "Quietly out of the room" },
            { text: "“We are all doing our best under real constraints.”", category: "Quietly out of the room" },
            { text: "“Let us not make this about race.”", category: "Quietly out of the room" },
          ] },
          { type: "accordion", heading: "Three harder cases", items: [
            { title: "When the conversation is about your own decision", body: "<p>The most useful things you can do are unglamorous: stay, ask one clarifying question, and say what you heard before you say why it happened. Naming your own part out loud — “I approved that step” — does more for the room's honesty than any assurance about openness, because it tells people the cost of saying it has already been paid. Then leave with an owner and a date, and come back with what you found even if what you found is that the concern was mistaken.</p>" },
            { title: "When somebody says more than they meant to", body: "<p>It happens, particularly when a conversation gets to something real. Protect the person rather than the moment: do not build on it, do not put it in the notes, and do not repeat it in a summary. Say that it stays here, move the conversation back to the process, and follow up privately afterward to ask what they would like done with it, if anything. A disclosure used well once is still a disclosure somebody did not plan to make.</p>" },
            { title: "When it ends without agreement", body: "<p>Say so cleanly instead of manufacturing consensus in the last four minutes. What the room needs on the way out is: here is what was decided, here is who decided it, here is what is still open and who owns it, and here is where the disagreement is recorded. Anybody may ask once for a decision to be reopened if something new appears. That sentence prevents a great deal of quiet resistance, and it costs nothing to say.</p>" },
          ] },
          { type: "leaderMove", heading: "Acknowledge first, explain second", control: "You control the order of your own two sentences. Acknowledgment first and explanation second is entirely within your gift, and it costs you nothing you actually need.", failure: "Do not lead with why it happened. An explanation offered before an acknowledgment reads as a defense whatever it contains, and the second half of it never gets heard.", next: "The next time somebody names an effect in a meeting you are leading, say what you heard and that you want to understand it, and hold the explanation for your second turn." },
          { type: "quote", text: "I said the renewal step was closing people who move a lot. My supervisor did not defend it and did not agree with me either. He asked what I had seen, said he had approved the step, and said he wanted the numbers before the next unit meeting. That was the first time raising something felt worth the trouble.", cite: "Composite staff perspective, illustrative" },
          { type: "knowledgeCheck", id: "ipe-36-3-check", question: "In a review you are leading, a staff member says a delivery rule is closing cases for people who move often and people who work through interpreters. The colleague who designed the rule says the implication is insulting. Which response keeps the conversation usable?", options: [
            { text: "“Nobody is accusing anyone here. Let us move on and I will look into it separately.”", correct: false },
            { text: "“Identical treatment is exactly what we are examining, and nobody's character is on the table. What pattern have you seen? I approved this step, so I want the numbers, and I want them before the next unit meeting.”", correct: true },
            { text: "“Can the two of you work this through and bring me a recommendation?”", correct: false },
          ], feedbackCorrect: "Yes. It returns the colleague's standing, keeps the subject on the rule, names your own part in it, and sends the question out of the room with an owner and a date.", feedbackIncorrect: "Ask what each answer teaches the room about the price of naming an uneven effect, and whether the delivery rule itself ever gets looked at." },
        ],
      },
      {
        id: "ipe-36-4",
        number: 4,
        title: "Your discussion plan",
        summary: "Eight lines for one issue your team is actually carrying: purpose, power, what is open, how people take part, the opening frame, three prepared moves, the record, and who hears what changed.",
        minutes: 10,
        learning: {
          objective: "Write a discussion plan for one real team issue that names the purpose, the power in the room, what is genuinely open, how people take part, the opening frame, three prepared moves, what is recorded, and the report-back with an owner and a date.",
          takeaways: [
            "A plan is not a script, and it is certainly not a set of prepared answers to the objections you expect. That is a defense plan wearing a discussion plan's clothes, and everybody in the room can tell.",
            "Two lines get written out in full rather than sketched: the opening frame, which is the ninety seconds that sets every term of the hour, and the three moves you will reach for when it goes sideways.",
            "Read the opening frame aloud once before you use it. The difference between saying it and improvising it while twelve people watch is larger than it looks on paper.",
            "A conversation with no report-back happened once. Name the owner, the date, and the sentence people will hear about what changed and what did not — and say that date out loud at the start.",
            "If the issue needs a facilitator who is not you, or expertise from people who are not staff, that is a design decision rather than a failure. Arrange compensation for external co-designers, reviewers and advisors before the invitation goes out, and tell them afterward what their time changed.",
          ],
          evidence: "A scenario about a plan that is really a defense plan, a discussion plan you can copy into your own work, a private reflection, and a knowledge check on what an opening frame has to carry.",
          appliedNextStep: "Fill in the eight lines for one issue your team is really carrying, hold the conversation within the month, and put the report-back on somebody's calendar before you send the invitation.",
        },
        scenario: {
          context: "You are preparing a ninety-minute conversation about why the division's contract and grant materials keep reaching partners in formats that people who are blind cannot use. Two units point at each other, the procurement lead says the template is fixed, and a paid community reviewer has raised it three times. Your draft plan is a minute-by-minute agenda with prepared talking points for each objection you expect.",
          prompt: "What is wrong with the plan, and what replaces it?",
          options: [
            { label: "Nothing is wrong with it. A tight agenda and prepared answers are what keep a hard conversation from drifting into grievance.", response: "Prepared answers to expected objections keep the hour inside what you already believe. The agenda will hold, the conversation will not happen, and the reviewer will raise it a fourth time — to somebody else." },
            { label: "Keep the timing and drop the prepared answers, then add the four things that actually decide the hour: who is in the room and what power is in it, what is already decided and what is open, how people take part and what nobody has to disclose, and what happens afterward.", response: "This is the swap that matters. You lose a script you were never going to follow and gain the conditions that let people tell you where the format is lost, including the parts that involve a template you approved.", recommended: true },
            { label: "Send the plan to the two unit leads beforehand and ask them to agree on an account of what happened before the meeting.", response: "Pre-agreement removes the disagreement the conversation exists to examine, and it settles the reviewer's finding in a room she is not in. The meeting will then ratify an account that was written to be comfortable." },
          ],
        },
        transfer: {
          prompt: "Which issue will you write the eight lines for?",
          options: [
            "Name the issue and the date the conversation will happen",
            "Write the opening frame out in full, and read it aloud once",
            "Choose the three moves you will make when it goes sideways",
            "Name who hears what changed, and the date they hear it",
            "Decide whether you should be facilitating it at all",
          ],
        },
        blocks: [
          { type: "text", heading: "A plan, not a script", body: "<p>A discussion plan is short. It is not an agenda with talking points, and it is certainly not a set of prepared answers to the objections you expect, which is a defense plan in better clothes. Its only job is to settle the handful of things that decide a hard conversation before anyone is in the room, so that the conversation itself can be genuinely open.</p><p>Eight lines will do it. What the issue is and what the hour is for. Who is in the room and what power is in it. What is already decided and what is genuinely open. How people take part, and what nobody has to disclose. The opening frame and the first question. Three moves for when it goes sideways. What is recorded and what stays in the room. And what happens afterward: an owner, a date, and the sentence people will hear about what changed.</p><p>Two of those get written out in full. The opening frame is the ninety seconds that sets every term of the hour, and reading it aloud once in advance is the difference between saying it and improvising it while twelve people watch you work out what you meant. The three moves are what you will reach for under pressure, and if you have not chosen them you will reach for reassurance, because reassurance is always within arm's length.</p><p>The last line is the one most often left off, and it decides whether anybody brings you anything next time. Give the report-back a name and a date in the same week you send the invitation, and say the date out loud when you open. Here is what you told us, here is what changed, here is what did not and why. If the answer is that nothing changed, say that too, with the reason. People can live with a no. They cannot live with silence, and they will draw the obvious conclusion from it.</p>" },
          { type: "artifact", kind: "tagged-document", label: "Practical tool", title: "A discussion plan for a team issue", summary: "Eight lines you can fill in for one real issue in about half an hour and take into the room exactly as they are. The example shown is a format-accessibility problem in contract and grant materials.", fields: [
            { label: "The issue in one sentence and what the conversation is for", value: "Contract and grant materials keep reaching partners in formats that people who are blind cannot use. This hour is for understanding where the usable format is lost and what each unit controls. It is not where the template gets redesigned; that decision sits with procurement and comes back at the agreed review point." },
            { label: "Who is in the room and what power is in it", value: "Two unit leads, the procurement lead, three staff who assemble the packets, and the paid community reviewer who first raised it. I approved the current template, and a director will read the summary. Both of those get said out loud in the first minute rather than discovered later." },
            { label: "What is already decided and what is genuinely open", value: "Decided: the materials have to be usable, which is an obligation rather than a preference, and the next round goes out this quarter. Open: which step loses the format, what each unit changes on its own authority, and whether the template goes back for redesign." },
            { label: "How people take part, and what nobody has to disclose", value: "Materials two working days ahead as real text, captions on, a reachable room, and a written route for anyone who would rather not speak in the group. Nobody is asked about their own disability, identity or private experience. Every question is about the process." },
            { label: "The opening frame and the first question", value: "Ninety seconds, written out: purpose, what is decided, what is open, what is recorded and who sees it, how to take part, and what nobody is being asked to do. First question: at which step does a usable file stop being usable, and who owns that step?" },
            { label: "Three moves for when it goes sideways", value: "If somebody names harm, acknowledge and then explain. If somebody becomes defensive, say nobody's character is on the table and return to the step. If the room goes quiet, ask a narrower question and let three seconds pass before I fill it." },
            { label: "What is recorded, and what stays in the room", value: "The notes carry decisions, open questions, owners and the disagreement. No individual is named as a cause. The summary goes to the director and to everyone who was in the room, including the reviewer." },
            { label: "What happens afterward: owner, date and report-back", value: "Each open question gets a named owner and a date, said aloud before anyone leaves. Within two weeks everyone in the room hears what changed, what did not and why — including the reviewer, whose time is paid." },
          ], action: "Copy the eight lines into a document, fill them in for one issue your team is actually carrying, write the opening frame out in full and read it aloud once, and put the report-back on somebody's calendar before you send the invitation." },
          { type: "list", heading: "Opening lines that do the work in ninety seconds", items: [
            "“This hour is for understanding what the renewal step does to people who move often. It is not where we decide the step.”",
            "“What is already decided: the notice goes out this quarter. What is open: everything about how it reads.”",
            "“Notes carry decisions, open questions and disagreements. Nobody is named. The summary goes to the director and to all of you.”",
            "“Nobody is being asked to agree with me, and nobody is being asked to talk about themselves. The questions are about the process.”",
            "“If you would rather write than speak, here is where it goes and who reads it. Either route counts the same.”",
            "“I approved the step we are about to examine. I would rather hear about it here than read about it in a complaint.”",
          ] },
          { type: "accordion", heading: "Three questions to settle before the invitation goes out", items: [
            { title: "Should you be the one facilitating?", body: "<p>If the conversation is substantially about decisions you made, your presence changes what can be said and your facilitation changes it further. Consider answering for the part that is yours and handing the facilitation to somebody with no stake in the outcome — a peer from another unit, or an external facilitator. Staying in the room while somebody else runs it is often the strongest available move, and it is almost never the comfortable one.</p>" },
            { title: "Who is in the room who is not staff, and are they paid?", body: "<p>People with disabilities, family members, interpreters and culturally specific organizations take part in this work as co-designers, reviewers, storytellers, facilitators and advisors. They are not learners in a staff module and they are not volunteers supplying free expertise. If the hour depends on what they know, arrange the compensation before the invitation goes out, agree how their contribution is described, and tell them afterward what it changed.</p>" },
            { title: "What will you do if it ends without agreement?", body: "<p>Decide now, because you will be asked at minute eighty-five. The usable answer: the decision stands or is deferred, the disagreement goes into the record with the reasoning, and anybody may ask once for it to be reopened if something new appears. Write that sentence into the plan and you will not have to invent it while everyone watches.</p>" },
          ] },
          { type: "leaderMove", heading: "Book the report-back before you hold the conversation", control: "You control whether the follow-up exists before the hour starts: a named owner, a date already on a calendar, and a sentence people will hear whether the answer turns out to be yes or no.", failure: "Do not close with “thank you, this was really valuable.” A conversation that produces gratitude and no owner teaches people that the hour itself was the point, and they will price the next invitation accordingly.", next: "Put the report-back on somebody's calendar in the same week you send the invitation, and say that date out loud when you open the conversation." },
          { type: "text", heading: "A private reflection, for you alone", body: "<p>Nothing here is collected, scored or seen by anyone else. Take whichever question is useful and leave the rest.</p><p>How might my role, authority and language change what people are willing to say in a conversation I lead? Who could be helped, burdened, excluded or misunderstood by the way I have designed this hour? Whose expertise is missing from the room, and what would it take to have it here earlier and properly paid? What might accessibility mean in this conversation beyond the legal minimum? If harm or exclusion happened in something my area decided, what would accountability and repair actually require of me, rather than of the people affected?</p><p>One more, if it is useful: what did it cost the last person who told me something I did not want to hear, and how would I know?</p>" },
          { type: "knowledgeCheck", id: "ipe-36-4-check", question: "Which opening frame gives people what they need in order to speak honestly?", options: [
            { text: "“Thanks for coming, everyone. This is a safe space and we genuinely want to hear whatever you have to say.”", correct: false },
            { text: "“This hour is for understanding where the usable format is lost. Procurement decides the template and reports back at the review point. Notes carry decisions and open questions with nobody named, and the summary goes to the director and to you. Nobody is being asked to agree or to talk about themselves.”", correct: true },
            { text: "“We have a lot to get through, so let us cover the background first and leave time for questions at the end.”", correct: false },
          ], feedbackCorrect: "Yes. Purpose, who decides, what is recorded and who sees it, and what nobody is being asked to do. Declaring a room safe does none of those things.", feedbackIncorrect: "Ask what each opening still leaves people to guess: whether anything can change, who decides, what is written down and where it goes, and whether they are expected to talk about their own lives." },
          { type: "statement", body: "A commitment worth writing down: “The issue I will write the eight lines for is… the conversation will happen on… the person who hears what changed is… and the move I most need to have ready is…”" },
        ],
      },
    ],
  },
  jobAid: {
    title: "Leading difficult dialogue",
    subtitle: "One page for any supervisor, manager or senior leader preparing a conversation nobody wants to lead",
    quote: "Declaring a room safe does not make it safe. Saying what the hour is for, what is already decided, what gets written down and what nobody has to disclose comes much closer.",
    use: {
      purpose: "Keep the four purposes, the conditions and the five moments in view while you plan a hard conversation, write an invitation, open a session, or decide what to do in the moment it turns.",
      remember: [
        "Four conversations arrive wearing the same clothes: settling a decision, accounting for what happened, examining the effect of the work, and repairing something. Say which one this hour is.",
        "Say what is already decided in the first two minutes. People find out anyway, and finding out late is what teaches them not to bother next time.",
        "A dialogue asks people to examine the work. It never requires agreement, and it never requires anyone to describe an identity, a diagnosis, a belief or a private experience.",
        "Power in the room is a fact, not a mood. Name the asymmetry, provide a route that does not run through you, and behave well the first time somebody uses it.",
        "Say what the notes carry, who receives them and what stays in the room. Unclear recording terms produce careful sentences, and careful sentences are not what you need.",
        "Ground rules that describe attitudes cannot be checked and favor whoever is already comfortable. Write ones anybody could point at, including on the days you are the one who missed them.",
        "Acknowledge before you explain. The explanation is still owed, and it is heard far better second.",
        "Treating everyone identically is Minimization, not fairness. Acceptance begins when a real difference in how people meet the same process is allowed back in as information about the design.",
        "A conversation with no report-back happened once. Owner, date, and one sentence about what changed and what did not.",
      ],
      doNext: "Write the eight discussion-plan lines for one issue your team is carrying, read the opening frame aloud once, and put the report-back on somebody's calendar before you send the invitation.",
    },
    sections: [
      {
        heading: "The discussion plan, in short",
        items: [
          "The issue in one sentence and what the conversation is for — including what it is not for.",
          "Who is in the room and what power is in it, said out loud rather than discovered later.",
          "What is already decided and what is genuinely open.",
          "How people take part, and what nobody has to disclose.",
          "The opening frame and the first question, written out in full.",
          "Three moves for when it goes sideways, chosen before you need them.",
          "What is recorded, who receives it, and what stays in the room.",
          "What happens afterward: owner, date, and the sentence people will hear about what changed.",
        ],
      },
      {
        heading: "Before the invitation goes out",
        items: [
          "Name the purpose and what is already decided; a consultation that turns out to be a notification is remembered for a long time.",
          "Ask about the process, not about people's lives. Replace any request for personal experience with a question about the work.",
          "Say what is recorded, who receives it, and whether anybody is named.",
          "Make taking part optional, make declining cost nothing observable, and offer a written route as well as the room.",
          "Build access in by default: materials ahead as real text, captions on, an interpreter booked before the schedule hardens, a reachable room, a pace that allows thinking.",
          "Decide whether you should facilitate at all, and arrange compensation for anyone taking part who is not staff.",
        ],
      },
      {
        heading: "The first ninety seconds",
        items: [
          "What this hour is for, and what it is not for.",
          "What is already decided, who decides the rest, and by when.",
          "What the notes carry, who sees the summary, and what stays in the room.",
          "How to take part, including the route that is not speaking in a group.",
          "That nobody is being asked to agree, and nobody is being asked to talk about themselves.",
          "Your own part in whatever is being examined, if you have one, and the date of the report-back.",
        ],
      },
      {
        heading: "Five moments in the room",
        items: [
          "Harm or an uneven effect is named: acknowledge, then explain. Never the other way round.",
          "A colleague becomes defensive: return their standing, then move the subject back to the rule and the evidence.",
          "The room goes quiet: ask a narrower question, offer the written route, and let three seconds pass before you fill it.",
          "One person is asked to speak for a group: take it off them, and treat a specific account as specific evidence about a step.",
          "Somebody presses for agreement: say what was decided, who decided it, what is open, and where the disagreement is written down.",
        ],
      },
      {
        heading: "When it is your decision on the table",
        items: [
          "Say your own part out loud early; it tells the room the cost has already been paid.",
          "Stay in the moment, ask one clarifying question, and say what you heard before you say why it happened.",
          "Hand the facilitation to somebody with no stake when the conversation is substantially about you.",
          "Come back with what you found, including when what you found is that the concern was mistaken.",
        ],
      },
      {
        heading: "Who this helps",
        items: [
          "Supervisors and managers, who hold most of these conversations and set the conditions for all of them — this module goes deepest here, and it is a good place to start.",
          "Executive and senior leaders, whose presence changes what can be said in a room and who decide whether a report-back survives a busy quarter.",
          "Policy, program and operations staff who lead a workgroup or a project team without a supervisory title.",
          "Quality, complaints and incident staff, whose reviews depend entirely on people being willing to say something early.",
          "Community engagement staff, who carry what partners and paid advisors say into rooms where it is inconvenient.",
          "Training, communications and learning-design staff, who are often asked to facilitate a conversation somebody else designed.",
          "Fiscal, contracts, grants and procurement staff, who hold conversations about templates, formats and requirements that decide who can take part.",
          "Data, research and evaluation staff, who can show a room what an average is hiding.",
          "Administrative and support staff, who see who gets interrupted, who never gets the materials in time, and who absorbs the rework.",
        ],
      },
      {
        heading: "Related modules",
        items: [
          "Leading a reflective DSD team",
          "Inclusive workforce and team culture",
          "Quality, complaints, and incident learning",
          "Co-design and compensated partnership",
          "Equitable policy and procedure governance",
        ],
      },
    ],
  },
  sources: [
    { title: "Minnesota Framework for Universal Multicultural Instructional Design", href: "https://mncpd.org/wp-content/uploads/2016/12/MN_Framework_for_Universal_Multicultural_Instructional_Design.pdf", note: "The design reference for this curriculum: multiple ways to engage, culturally responsive materials, and instruction that never requires a participant to disclose a personal experience in order to take part." },
    { title: "U.S. Department of Health and Human Services, National CLAS Standards", href: "https://thinkculturalhealth.hhs.gov/clas", note: "National standards for culturally and linguistically appropriate services, including the governance and leadership standards, the workforce standards, and the standards on community engagement, conflict and grievance resolution that frame these conversations." },
    { title: "Minnesota Management and Budget, statewide human resources policies", href: "https://mn.gov/mmb/employee-relations/laws-policies-rules/statewide-hr-policies/", note: "The statewide policies that frame a Minnesota supervisor's responsibilities, including respectful workplace expectations and where a formal personnel matter belongs rather than a team conversation." },
    { title: "Minnesota Department of Human Rights, Your rights", href: "https://mn.gov/mdhr/yourrights/", note: "Minnesota Human Rights Act protections in employment and public services, and the boundary between an internal learning conversation and a formal complaint of discrimination, harassment or retaliation." },
    { title: "Minnesota Council on Disability", href: "https://www.disability.state.mn.us/", note: "Minnesota's advisory council on disability policy and access, including practical guidance for state agencies on accessible meetings, materials and notices — the basis for the access conditions built into the discussion plan." },
    { title: "ADA.gov, Title II primer for state and local governments", href: "https://www.ada.gov/resources/title-ii-primer/", note: "U.S. Department of Justice explanation of what Title II requires of state and local government programs, meetings and communications, which keeps a legal obligation clearly distinct from the optional practice in this module." },
    { title: "Minnesota Governor's Council on Developmental Disabilities", href: "https://mn.gov/mnddc/", note: "Public Minnesota materials on disability history, self-advocacy and community participation, useful background for why people expect to be involved in decisions about them rather than described in their absence." },
    { title: "plainlanguage.gov, Federal plain language guidelines", href: "https://www.plainlanguage.gov/guidelines/", note: "Practical guidance for writing an invitation, an opening frame or a ground rule that a colleague can act on without interpreting it first." },
  ],
};

export default pack;
