exec((__import__('pathlib').Path(__file__).parent/'write-packs.py').read_text(encoding='utf-8-sig'))
publish(7,'networks-opportunity-hoarding','Social Networks, Homophily, and Opportunity Hoarding','Trace how information and advocacy move through relationships, and widen access to opportunities without policing personal friendships.',[
lesson('Separate personal affinity from opportunity structure',['Define homophily without assuming a motive.','Distinguish available relationships from preferences within them.','Identify an opportunity that depends on network access.'],'''Homophily describes a tendency for connections to form among people who are similar in some respect. Similarity may involve profession, location, education, race, age, interests, or organizational position. The concept does not mean that every friendship is an act of exclusion. It helps examine how the structure of relationships influences which information people receive and which opportunities they can reach. McPherson and colleagues’ review emphasizes both opportunities for contact and patterns within those opportunities.

Distinguish composition from choice. If a work unit is highly homogeneous, many relationships within it will also be homogeneous even without a strong preference for similarity. If a wider set of possible contacts exists but important connections remain concentrated in one circle, different questions arise. A careful analysis asks who can meet whom, under what conditions, and with what consequences. It does not infer a discriminatory intention simply from the identity of someone’s friends or ask employees to disclose private social lives.

Networks matter because information is not distributed evenly. An informal conversation may reveal that a temporary assignment will open before the official notice appears. A trusted colleague may explain what an application needs. A sponsor may interpret an ambiguous record favorably. None of these acts is inherently wrong, but access to them can become a hidden qualification. People outside the circle may appear less prepared when they actually had less information or less opportunity to demonstrate readiness.

Begin with the opportunity, not a map of everyone’s friendships. Trace how people learned about it, who could express interest, what preparation was available, and who influenced the decision. Use authorized organizational records and avoid unnecessary collection of personal network information. An observable concern might be that every nomination came through the same small group even though eligibility was broader. That is a reason to examine the route, not proof that the group conspired. The practical response is to make consequential information and participation routes more transparent while preserving ordinary supportive relationships. Fair access should not depend on already knowing the person who knows the opportunity exists.''','A fictional temporary assignment is announced publicly only after several people in one network have prepared applications with informal advice.','Publish the preparation information and provide a fair response period for everyone eligible.','The repair addresses unequal access to consequential information without treating friendship itself as wrongdoing.','Require employees to list their personal friends so managers can monitor similarity.','Private friendship monitoring is intrusive and unnecessary for examining the organizational opportunity route.','What information about advancement did you learn informally rather than through an open process?','Map one opportunity from first notice to final selection, including preparation and advocacy.'),
lesson('Understand bridging ties and their limits',['Distinguish bonding and bridging functions of relationships.','Explain why adding contacts does not guarantee opportunity.','Identify a structural barrier beyond a person’s network.'],'''Some relationships provide reliable support and repeated cooperation. Others connect a person to information outside their usual circle. These functions are often described as bonding and bridging. A close colleague can provide trust and practical help; a more distant connection may know about a role that nobody in the immediate team has heard of. Neither function is universally superior. The useful question is what a person can access through a relationship and what remains unavailable despite it.

Research on weak ties includes large-scale experiments involving professional-network recommendations and job mobility. Rajkumar and colleagues found evidence that the strength of ties can matter for movement between jobs in that setting. That does not establish that instructing every employee to network more will improve equity in a public agency. A digital platform, an internal assignment process, and a professional community have different rules and power relationships. The research supports examining information pathways, not promising a particular result from collecting more contacts.

Networking advice can misplace responsibility when the barrier is institutional. A person may make many connections yet still lack release time, accessible events, recognized credentials, or a sponsor with decision-making influence. Invitations held outside work hours may be easier for some people to accept than others. An expectation to build relationships through unpaid social activity can turn unequal resources into apparently different levels of commitment. Examine what the organization makes possible before treating a narrow network as an individual deficit.

Create bridges through the work where appropriate: open information sessions, cross-team problem solving, transparent expressions of interest, and access to preparation materials. These should supplement, not replace, reviewable decisions. A public event is not an equitable route if the consequential conversation still happens privately afterward. Clarify which opportunities are available and how people can pursue them without relying on personal familiarity. Evaluate whether the new route changes access to useful information and participation, not merely whether the contact list grew. This keeps the focus on organizational responsibility while recognizing that relationships can remain a valuable source of support, learning, and collaboration.''','A fictional manager tells staff excluded from assignments to attend more evening networking events, without examining how assignments are allocated.','Offer work-time information and a transparent expression-of-interest route, then review assignment decisions.','The response addresses organizational access rather than making private social participation the solution.','Count the number of new contacts as proof that opportunity has become equitable.','More contacts do not establish access to meaningful information, support, or decisions.','Which networking expectation assumes time or resources that not everyone has?','Design a work-based bridge to one opportunity and specify what useful access it provides.'),
lesson('Identify opportunity hoarding without assuming conspiracy',['Identify an exclusion mechanism in a recurring allocation pattern.','Distinguish trust-based cooperation from closed access to scarce resources.','Propose a transparent allocation rule.'],'''Opportunity hoarding occurs when access to valuable resources becomes concentrated within a bounded group and outsiders face difficulty entering. The boundary may be explicit, such as membership in a restricted circle, or informal, such as being known to the people who nominate candidates. The concept draws attention to resource allocation. It does not require assuming a secret agreement or claiming that every advantage was intentionally reserved. Repeated small decisions can create a durable pattern even when each decision seems convenient.

Trust is useful in work. A leader may reasonably value evidence that someone can deliver a difficult assignment. The problem arises when the only accepted evidence is having already received assignments from the same circle. That creates a loop: opportunity produces experience, experience justifies the next opportunity, and people outside the loop remain unproven. Examine whether a person can demonstrate relevant capability through another route and whether developmental opportunities are separated from roles that truly require established experience.

Scarcity makes the allocation rule important. If there are only two high-visibility assignments, an open invitation alone cannot give everyone the role. The organization still needs relevant criteria, a documented selection process, and feedback that helps others understand future routes. Rotation may be useful for some developmental tasks but unsuitable for others. Random selection among qualified candidates may fit a particular low-risk opportunity but should not be introduced without authority and careful consideration. No single allocation method is equitable in every setting.

Review the pattern over time. Who receives preparation, visibility, credit, and the chance to recover from a mistake? Are assignments repeatedly offered to those already known while eligibility remains broader? Use records appropriate to the purpose and avoid turning the exercise into a map of private loyalties. A good response widens legitimate routes into the work and makes reasons understandable. It does not punish existing relationships or assume that people who have benefited lack ability. The goal is to prevent familiarity from functioning as an unannounced prerequisite and to make the development of future capability part of the allocation decision.''','A fictional team always chooses people with prior stretch assignments, but only those same people have ever been offered a first stretch assignment.','Create a supported entry route with relevant criteria and distinguish developmental work from roles requiring prior experience.','The response breaks the circular qualification rule while preserving legitimate task requirements.','Assume that everyone previously selected is unqualified because the route was narrow.','A restricted route can exclude capable people without proving that its beneficiaries lack ability.','Where does prior opportunity become the only accepted evidence for receiving another opportunity?','Write an allocation rule that states eligibility, evidence, support, selection authority, and feedback.'),
lesson('Evaluate access while respecting privacy',['Select measures of opportunity access and quality.','Explain why demographic balance alone does not prove fairness.','Create a review plan that avoids private relationship surveillance.'],'''A network-informed improvement should be evaluated through the opportunity pathway. Begin with visibility: did eligible people learn about the opportunity in time? Then examine preparation, expression of interest, selection, support, and credit. These stages reveal different barriers. A broad announcement may improve visibility while the application still requires information available only through a sponsor. A diverse selection may be followed by unequal support. The final participant list cannot explain the whole process.

Choose measures that fit the question and the available authority. You might review announcement timing, access to information sessions, the use of selection criteria, or whether all participants receive necessary support. Where demographic analysis is authorized and useful, work with appropriate specialists and protect small groups. Do not create a personal relationship database simply because network theory makes relationships interesting. The course’s purpose is to improve organizational access, not to monitor employees’ friendships, social media, or private affiliations.

Interpret results carefully. More expressions of interest may indicate better access or a change in the opportunity’s attractiveness. A different participant mix may reflect the revised route, changes in eligibility, or ordinary variation. A small pilot may show that the new route is usable without proving a stable effect on advancement. Examine both opportunity quality and distribution. A nominal assignment with little influence or support is not equivalent to a meaningful developmental role, even if both appear in the same count.

Report what the review can support. Describe the changed route, evidence of use, remaining barriers, and the next decision. Invite feedback through an appropriate channel from people who considered participating but did not apply; their experience may reveal a barrier hidden by applicant-only data. Keep participation voluntary and do not penalize people for declining an opportunity. A fairer pathway offers understandable choices rather than requiring everyone to pursue the same career pattern. Continue to value relationships as sources of support while ensuring that essential information and legitimate opportunities do not remain available only through familiarity with the right person.''','A fictional review celebrates a wider participant mix but finds that newcomers received no preparation time and less project credit.','Review support and credit alongside selection and correct the unequal conditions.','Access includes the quality of participation, not only entry into the role.','Treat the participant count as conclusive evidence of equity.','A count can conceal unequal resources and recognition after selection.','What would make an opportunity meaningful rather than merely visible on a résumé?','Create a review covering notice, preparation, selection, support, credit, and feedback from nonparticipants.')],
[('Homophily','A pattern of connections among similar people; it does not by itself establish a motive.'),('Bridging tie','A relationship connecting someone to information or people outside their usual circle.'),('Opportunity hoarding','Concentration of valuable access within a bounded group, including through informal routes.'),('Circular qualification','Requiring prior opportunity as the only evidence for receiving a first opportunity.')],
[('Trace the route',['Choose a consequential opportunity.','Record notice, preparation, nomination, selection, support, and credit.','Identify where personal familiarity substitutes for an open route.']),('Design access',['Publish information early enough to act on it.','Create supported entry routes where development is the purpose.','Use relevant criteria and explain decisions.','Avoid requiring unpaid social activity to obtain essential information.']),('Review without surveillance',['Measure access and participation quality separately.','Use authorized organizational records rather than private friendship data.','Protect small groups in demographic analysis.','Review whether newcomers receive support and recognition after selection.'])],
[('McPherson, Smith-Lovin, and Cook (2001), Birds of a Feather: Homophily in Social Networks','https://sites.santafe.edu/~aaronc/courses/5352/readings/McPherson_Smith-Lovin_Cook_01_BirdsOfAFeature_HomophilyInSocialNetworks.pdf','University-hosted full research review distinguishing network composition and homophily. Workplace allocation exercises are original applications.'),('Rajkumar and colleagues (2022), A causal test of the strength of weak ties','https://pubmed.ncbi.nlm.nih.gov/36107999/','Primary experiment on a professional-network platform; its effects do not guarantee results from internal networking programmes.')])

publish(8,'bias-reduction-interventions','Designing and Testing Bias-Reduction Interventions','Move from an appealing training idea to a testable change, with behavioral outcomes, ethical safeguards, and honest limits on what a pilot can establish.',[
lesson('Turn an aspiration into a testable mechanism',['State a specific behavior an intervention is intended to change.','Distinguish an attitude measure from a work outcome.','Draft a mechanism linking an activity to a decision.'],'''Reduce bias is a purpose, not yet a testable intervention. A useful design states which decision or behavior should change, what activity might change it, and why. For example, a team may want reviewers to offer comparable clarification opportunities. A proposed intervention could introduce a standard clarification step before a decision is finalized. The mechanism is that the step reduces unequal treatment of missing information. That is more specific than assuming a general awareness workshop will improve every kind of decision.

Separate awareness, implicit association, stated attitude, behavior, and outcome. These may relate to one another, but a change in one does not establish change in the others. A participant can report learning something without changing a process. An implicit-association measure can change immediately after an activity without producing a durable behavioral effect. A process can become more consistent without a measurable change in a short-term attitude questionnaire. Select the measure that answers the actual question rather than the one easiest to collect.

Primary intervention research illustrates the need for that distinction. Devine and colleagues studied a prejudice habit-breaking approach, while Lai and colleagues compared interventions and examined persistence over time. Their findings should be read in relation to their samples, measures, and follow-up periods. They do not justify promising that a single course eliminates bias or that an individual score predicts a particular employment decision. In this programme, an IAT may be an optional private reflection resource, not a staff assessment, selection instrument, or required outcome measure.

Write the design as a chain: identified barrier, proposed activity, expected process change, and observable outcome. Then ask where the chain could fail. People may not use the new step, the step may not address the barrier, or another part of the process may override it. A strong design names those possibilities in advance. It also distinguishes a practical improvement within ordinary authority from research involving people that may require additional review. The goal is disciplined learning about a specific change, not an experiment conducted on staff without appropriate authorization or an ambitious claim supported only by participant satisfaction.''','A fictional team proposes an implicit-bias presentation and plans to declare success if attendees enjoy it.','Specify the decision behavior to change and choose a measure of that behavior alongside optional feedback.','Satisfaction can describe experience but cannot establish that the intended decision process changed.','Use attendance and satisfaction as proof that discrimination declined.','Those measures do not test discrimination or isolate a change in workplace behavior.','Which link between learning and action do you usually assume rather than examine?','Write a four-part mechanism: barrier, activity, process change, and outcome.'),
lesson('Choose a comparison that answers the question',['Explain a limitation of a before-and-after comparison.','Identify a feasible comparison for a fictional pilot.','Distinguish service improvement from human-subjects research.'],'''A comparison gives a result meaning. If a process improves after a new checklist is introduced, the checklist may have helped. But staffing, case mix, workload, season, or another policy may also have changed. A before-and-after design cannot automatically separate those explanations. This does not make ordinary improvement work useless. It means the report should distinguish evidence that a change was feasible from evidence that it caused a particular outcome.

Select a comparison appropriate to the question and the setting. A team might compare similar decision periods, review a sample of cases against the same standard, or use a phased implementation where authorized and appropriate. A randomized design can strengthen causal reasoning in some circumstances, but random assignment is not automatically ethical, practical, or authorized. Do not withhold a required access support, protection, or service for the sake of a learning exercise. Seek appropriate evaluation and ethics guidance when the activity goes beyond routine improvement.

Specify the unit being examined. Is it a person, a case, a team, or a decision? A change introduced at team level can affect many cases, and those cases are not necessarily independent observations. Small numbers and repeated decisions by the same people can make apparent differences unstable. A simple chart can still be useful for identifying implementation problems, but it should not imply statistical certainty that the design cannot provide. Consult qualified analysts for claims requiring more advanced methods.

Decide the outcome and review period before seeing the results when possible. Otherwise, it is easy to highlight whichever measure happened to improve and ignore the rest. Record practical constraints, expected benefits, possible harms, and a stopping rule. Explain what information will be collected and avoid private learning responses or unnecessary identity data. A credible pilot may conclude that the change is usable, needs revision, or warrants a more rigorous evaluation. Those are valuable results. They are more useful than a confident success story whose comparison cannot answer the question it claims to answer.''','A fictional checklist pilot improves completion rates during a month when staffing doubles.','Report the improvement and staffing change together and plan a more informative comparison.','The observed change is real, but the design does not isolate which factor produced it.','Attribute the entire improvement to the checklist because it was introduced first.','Temporal order alone does not remove competing explanations such as staffing and case mix.','What other change could explain a result you would like to credit to training?','Choose a feasible comparison and state one conclusion it could support and one it could not.'),
lesson('Measure benefits, burdens, and implementation',['Select an outcome, a process measure, and a balancing measure.','Identify a privacy risk in a proposed metric.','Create a stopping rule for unintended harm.'],'''An intervention can improve one measure while making another part of the work worse. A required second review might improve consistency but delay urgent decisions. A standard script might reduce omissions but make it harder to respond to a person’s actual question. A useful evaluation includes a balancing measure: an indicator of an important burden or unintended effect. This prevents a narrow definition of success from concealing costs transferred to staff or service users.

Use three complementary measures. The process measure asks whether the activity occurred as intended. The outcome measure asks whether the relevant result changed. The balancing measure asks what else became harder or riskier. For a clarification step, these might be the proportion of eligible cases offered clarification, the completeness of information at decision time, and the additional delay introduced. These are illustrative choices, not a required agency measurement framework. Adapt them to the actual purpose and authority of the work.

Protect privacy and avoid inappropriate personal assessment. Do not collect IAT scores, inferred IDI orientations, trauma narratives, or personal identity disclosures simply to make a course evaluation look comprehensive. If demographic analysis is authorized and relevant, use appropriate safeguards, especially for small groups. Explain who can see the information and what decisions it will inform. A voluntary learning programme should not quietly become a source of personnel ratings or a test of ideological agreement.

Define a stopping or revision rule before implementation. A rule might require review if the change introduces a serious access barrier, produces an unacceptable delay, or results in information being shared beyond its authorized purpose. Use qualified judgment about thresholds rather than inventing a number with no basis in the work. Invite feedback that can reveal problems outside the chosen metrics. An affected person’s account should not be dismissed merely because a dashboard is green. Good measurement supports responsible attention; it does not replace it. The aim is to learn whether the intervention improves the intended decision without imposing avoidable burdens or creating a new kind of exclusion.''','A fictional double-review process improves documentation but adds delays that prevent some people from meeting another deadline.','Review the delay as a balancing outcome and revise or pause the process where needed.','Improved documentation does not justify ignoring a new access barrier created by the intervention.','Continue unchanged because the primary quality score improved.','A single favorable metric can hide harm transferred elsewhere in the process.','Who could bear the cost of a change that looks successful on your preferred measure?','Define process, outcome, and balancing measures plus one condition that requires review or pause.'),
lesson('Interpret results and decide what happens next',['Distinguish observed results from a causal claim.','Explain why immediate change may not persist.','Write a transparent continue-revise-stop decision.'],'''The end of a pilot is a decision point, not an obligation to produce a success story. Begin by comparing the results with the question and measures specified beforehand. Did the activity occur? Did the intended behavior change? Were there unexpected burdens? What alternative explanations remain? A result that challenges the original idea is useful if it prevents the organization from expanding an ineffective or harmful practice. Treat revision as part of responsible learning rather than as an embarrassment to conceal.

Time matters. An immediate response after a workshop may differ from practice several weeks later. Attention, novelty, and the conditions of measurement can affect early results. Research comparing implicit-bias interventions has highlighted the difference between short-term changes and persistence. For a workplace process, examine whether the new behavior remains usable when workload rises or staff change. Do not assume that a single favorable follow-up establishes permanent change. Choose a review interval that fits the mechanism and practical risks.

Report uncertainty in plain language. Say that a small pilot showed improved use of a clarification step, for example, while acknowledging that the sample cannot establish a stable change in disparities. Avoid replacing honest limitations with vague claims that the programme transformed culture. Also avoid concluding that nothing matters because evidence is incomplete. A limited result can justify continuing a low-risk improvement with review, while a major expansion may require stronger evidence. The standard of evidence should match the consequence of the decision.

End with an explicit action: continue, revise, stop, or seek a more rigorous evaluation. Name the person responsible and the next review date. Preserve the original measures and record changes to the plan so later readers can understand the reasoning. Share an appropriate summary with people who contributed, including what did not work. Keep private learning responses separate from operational evaluation. This approach supports the programme’s movement toward responsive practice without turning staff into scored subjects. The strongest claim is the one the evidence can sustain, coupled with a concrete plan for what the organization will do next.''','A fictional pilot increases use of a fair clarification step but has too few cases to assess group outcomes.','Continue the usable process with review while describing the outcome evidence as insufficient.','A limited process finding can support a proportionate decision without an unsupported claim about disparities.','Call the pilot a failure because it did not prove a permanent reduction in bias.','The design may still establish feasibility and process improvement; it should be judged against the question it could answer.','What result would lead you to stop an intervention you initially favored?','Write a decision memo with results, limitations, unintended effects, next action, owner, and review date.')],
[('Mechanism','The proposed explanation of how an activity changes a specific process or behavior.'),('Outcome measure','Evidence about the result the change was intended to improve.'),('Balancing measure','Evidence about an important burden or unintended effect elsewhere in the work.'),('Causal claim','A claim that the intervention produced the change; it requires a design capable of addressing alternative explanations.')],
[('Define the test',['Name the barrier and decision behavior.','Link activity, process change, and intended outcome.','Distinguish private reflection from operational evaluation.']),('Plan ethically',['Choose a comparison suited to the question.','Use appropriate authorization and evaluation expertise.','Never withhold required access or protection for a test.','Specify process, outcome, balancing measures, and stopping conditions.']),('Interpret honestly',['Check implementation before interpreting outcomes.','Record sample, timing, competing explanations, and privacy limits.','Distinguish short-term response from persistence.','Decide to continue, revise, stop, or evaluate further and explain why.'])],
[('Devine and colleagues (2012), Long-term reduction in implicit race bias','https://pubmed.ncbi.nlm.nih.gov/23524616/','Primary habit-breaking intervention study; findings are specific to its design and measures, not a guarantee of workplace behavioral change.'),('Lai and colleagues (2016), Reducing implicit racial preferences: II. Intervention effectiveness across time','https://pubmed.ncbi.nlm.nih.gov/27454041/','Primary comparative intervention research emphasizes distinguishing immediate changes from persistence. It does not support employee scoring.'),('Devine and colleagues (2012), open full text','https://pmc.ncbi.nlm.nih.gov/articles/PMC3603687/','Open-access primary article for examining methods and limits directly; optional further reading.')])
