exec((__import__('pathlib').Path(__file__).parent/'write-packs.py').read_text(encoding='utf-8-sig'))
publish(9,'intergroup-contact','Intergroup Contact: Conditions, Power, and Unintended Effects','Design meaningful cooperation across difference while attending to power, voluntary participation, and the limits of contact as an equity strategy.',[
lesson('Distinguish proximity from meaningful contact',['Explain why sharing a room is not a complete contact intervention.','Identify conditions that support cooperative interaction.','Distinguish a research tendency from a guaranteed result.'],'''People can spend years in the same building without meaningful interaction across group boundaries. They may share a workspace while performing unequal roles, competing for scarce opportunities, or relying on stereotypes about one another. Intergroup contact theory asks when and how interaction can reduce prejudice. It does not say that proximity automatically produces understanding. The arrangement of the contact, the surrounding power relations, and what participants are asked to do all deserve attention.

Research associated with the contact hypothesis has emphasized equal status within the encounter, common goals, cooperation, and support from relevant authorities. Pettigrew and Tropp’s meta-analysis found a broad relationship between contact and reduced prejudice across studies. Later reviews, including Paluck and colleagues’ examination of randomized studies with delayed outcomes, highlight the importance of research design and gaps in what can be concluded for particular populations and settings. These findings support careful design, not a promise that one cross-group event will change enduring behavior.

Translate the conditions into practical questions. Equal status within an activity does not mean participants have equal institutional power outside it. A supervisor and an employee may both be invited to speak, but one still controls assignments. A common goal must be meaningful to the participants, not merely to the organizer. Cooperation requires interdependence rather than a contest in which one group wins recognition at the other’s expense. Authority support should include resources and protection for participation, not just a welcoming statement.

Use a fictional joint task to test the design. Can each participant contribute relevant expertise? Are materials accessible? Is there time to understand different approaches? Can someone decline personal disclosure without losing their place in the activity? What happens if an interaction causes harm? These questions make the design more concrete than a general instruction to get to know each other. They also preserve choice: nobody should be required to represent an identity group or become an educational resource for others. Meaningful contact can be one part of learning, while structural barriers still require direct attention beyond the encounter.''','A fictional division hosts a lunch where staff from different groups sit together, then calls it a proven prejudice-reduction intervention.','Describe it as an opportunity for interaction and design a separate cooperative task with clear conditions and review.','A social event may be valuable, but attendance alone does not establish meaningful contact or a measured effect.','Assume that shared seating guarantees improved intercultural competence.','Proximity does not establish cooperation, equal standing in the activity, or durable change.','Which condition is missing from a cross-group event you have attended or can imagine?','Review a fictional activity for equal standing, common goals, cooperation, authority support, and access.'),
lesson('Account for power inside and outside the encounter',['Map authority that remains outside a shared activity.','Identify a burden placed on a minority-status participant.','Propose a participation safeguard.'],'''An encounter can look equal while the surrounding relationship remains unequal. A manager and a staff member may receive the same speaking time, yet the staff member may reasonably consider how disagreement could affect future assignments. A community participant may sit beside agency leaders without controlling what happens to their recommendations. Equal treatment within the meeting is useful, but it does not erase unequal authority. A serious design names that difference instead of assuming that an icebreaker has removed it.

Research has examined differences in contact-prejudice relationships for minority- and majority-status groups. That distinction matters because the benefits and burdens of an encounter may not be distributed equally. One participant may gain new understanding while another spends the session correcting assumptions or explaining experiences. The programme should not treat the latter person’s effort as a free resource. Learning across difference is more credible when participation offers meaningful value and does not depend on someone performing an identity for the group.

Clarify what participation can influence. If a shared task concerns a process, identify which parts are open to change and who decides. Provide an independent route for concerns, explain how contributions will be recorded, and avoid requiring a person to disclose a private experience to establish the relevance of their view. A fictional case can allow participants to examine power and interpretation without making someone’s biography the lesson. Where participation is part of assigned work, distinguish that work responsibility from optional personal disclosure and optional learning activities.

Review who benefits from the design. Does the event create access to decision makers for participants, or only generate positive stories for the organization? Are concerns about inequity treated as disruptive to harmony? Can people disagree without being described as resistant to inclusion? A contact activity should not make comfort the overriding outcome. It can support cooperation while preserving the ability to name a structural problem. Sometimes the appropriate decision is to change the format, provide separate preparation, or choose another learning method. The aim is useful engagement with difference under credible conditions, not contact at any cost.''','A fictional community workshop invites candid feedback, but leaders describe criticism of a fixed policy as negative energy.','Clarify the decision limits and preserve a route for substantive criticism rather than making harmony the goal.','Cooperation does not require suppressing a concern about the conditions that shape the interaction.','Ask participants to share only positive experiences to protect the relationship.','That request privileges organizational comfort and restricts the knowledge the encounter can produce.','Who is doing the most explanatory work in the proposed activity, and what do they receive in return?','Map decision authority, participant benefit, explanatory burden, and a route for disagreement.'),
lesson('Build a cooperative task with meaningful differences',['Design a shared task requiring distinct contributions.','Distinguish perspective-taking from speaking for another group.','Plan a response to an uncomfortable interaction.'],'''A cooperative task should require participants to work with one another’s relevant knowledge. Simply dividing a worksheet into separate sections may create parallel activity rather than cooperation. A stronger task might ask a mixed-role team to redesign a fictional notice, where one person examines process requirements, another considers communication access, and another tests how a newcomer would understand the instructions. Roles should reflect relevant experience or chosen interests, not assumptions based on racial or cultural identity.

Make the shared goal concrete and attainable. Participants need to know what a useful product looks like and what decisions they can make. Provide the same background information in accessible formats and allow time to compare interpretations. Do not reward speed so heavily that the most confident speaker takes control. Structure the discussion so that different approaches can be considered before a final choice. This is not a claim that all perspectives are equally accurate; it is a method for making the reasoning and evidence visible.

Perspective-taking has limits. Imagining another person’s experience can reveal assumptions, but it does not establish what that person actually thinks or needs. Ask participants to distinguish what they know, what they are imagining, and what would need to be asked. Avoid simulations that claim to reproduce an identity or a lifetime of exclusion in a brief exercise. Use the fictional task to identify questions and design alternatives, then seek appropriate input where real decisions require it.

Prepare for difficulty without making discomfort the purpose. If someone is stereotyped or asked to represent a group, the facilitator should redirect responsibility to the task and address the conduct. Offer a pause or another participation route where appropriate. Do not require the affected person to explain the harm before the facilitator can act on an observable problem. End with a review of the product and the collaboration conditions: what information was useful, where authority shaped the discussion, and what should change next time. A cooperative task is successful when it produces useful work and a fairer interaction, not when everyone reports an identical emotional experience.''','A fictional notice-redesign group asks its only immigrant colleague to explain what all immigrants would understand.','Return to the specific notice, invite relevant expertise voluntarily, and identify questions requiring broader input.','The response preserves the colleague’s agency and prevents one person from being treated as a representative sample.','Accept the answer as definitive because lived experience removes the need for other evidence.','Individual experience is valuable but does not establish every person’s needs or interpretation.','When does perspective-taking become an assumption that you already understand someone else?','Design a shared task with complementary roles, accessible materials, a decision method, and a response to stereotyping.'),
lesson('Review effects beyond a pleasant encounter',['Separate participant experience from changes in practice.','Identify an unintended effect of emphasizing harmony.','Create a follow-up question tied to the shared task.'],'''A pleasant encounter can be worthwhile without demonstrating reduced prejudice or changed practice. Participants may enjoy meeting colleagues and still return to a process that excludes the same people. Others may find an encounter uncomfortable yet produce a useful change. Evaluate the purpose you actually set. If the goal was to improve a notice through shared expertise, examine the notice and whether people can use it. If the goal was to change collaboration, examine the relevant behavior over an appropriate period.

Contact can have unintended effects when harmony becomes more important than examining unequal conditions. Participants may feel pressure to avoid naming discrimination because doing so appears to threaten a newly positive relationship. A majority-status participant may conclude that a warm interaction proves the institution is fair. These are risks to examine, not predictions that every encounter will have those effects. Ask whether the design preserved room for criticism and whether any structural concern raised during the activity received a responsible response.

Use proportionate evidence. Optional feedback can describe whether the activity felt understandable, useful, and respectful. It cannot by itself establish durable behavior change. A follow-up review might examine whether the jointly designed process was adopted, whether participation broadened, or whether the original problem remains. Avoid collecting private identity narratives or treating enthusiasm as an assessment of a person’s intercultural orientation. No one should have to provide a favorable testimony to validate the activity.

Decide what to do next based on both the product and the participation conditions. Continue a useful format, revise a burden, or choose a different method where the power imbalance cannot be adequately addressed. Preserve the distinction between learning across difference and resolving a formal complaint. An encounter is not a substitute for correcting a documented access barrier or following required procedures. The programme’s emphasis on Acceptance and Adaptation is served when contact leads to more accurate questions and responsive action, while leaving individuals free to interpret their own experiences. Report a bounded result: what changed, what remains uncertain, and which responsibility now belongs to the organization.''','A fictional workshop receives positive ratings, but leaders use those ratings to dismiss an unresolved access concern raised during the session.','Treat the ratings and the access concern as different evidence and assign a response to the unresolved issue.','A positive experience does not cancel a substantive concern about the organization’s process.','Close the access concern because participants said the workshop was enjoyable.','Enjoyment does not establish that a barrier was corrected or that all relevant concerns were resolved.','Could a desire to preserve a good relationship make an important issue harder to raise?','Write a follow-up covering the shared product, participation conditions, unresolved concerns, and next responsibility.')],
[('Contact','Interaction across group boundaries; proximity alone does not establish its quality.'),('Equal standing in the task','A participation condition that must be designed; it does not erase outside authority.'),('Cooperation','Working toward a shared goal through meaningful contributions rather than competing for status.'),('Harmony risk','Pressure to preserve a positive relationship can discourage naming unequal conditions.')],
[('Set the purpose',['Name the shared task and what can change.','Identify meaningful contributions without assigning identity representatives.','Distinguish social connection from an evaluated intervention.']),('Design conditions',['Provide accessible materials and adequate time.','Map authority inside and outside the activity.','Preserve choice about personal disclosure and routes for disagreement.','Prepare a response to stereotyping or other harmful conduct.']),('Review responsibly',['Examine the product and participation conditions separately.','Do not equate enjoyment with durable change.','Assign ownership to unresolved structural concerns.','Continue, revise, or replace the format based on evidence and participant burden.'])],
[('Pettigrew and Tropp (2006), A meta-analytic test of intergroup contact theory','https://pubmed.ncbi.nlm.nih.gov/16737372/','Research synthesis supports attention to contact conditions; it does not guarantee the result of a particular workshop.'),('Paluck, Green, and Green (2019), The contact hypothesis re-evaluated','https://www.cambridge.org/core/journals/behavioural-public-policy/article/contact-hypothesis-reevaluated/142C913E7FA9E121277B29E994124EC5','Review of randomized studies with delayed outcomes, including important limits on generalization.'),('Tropp and Pettigrew (2005), Relationships between intergroup contact and prejudice among minority and majority status groups','https://pubmed.ncbi.nlm.nih.gov/16313659/','Research on differing relationships across group status; used to prompt examination of unequal benefits and burdens.'),('Pettigrew and Tropp (2006), full article','https://sparq.stanford.edu/sites/g/files/sbiybj19021/files/media/file/pettigrew_tropp_2006_-_intergroup_contact_theory.pdf','University-hosted full research article for optional methods and evidence reading.')])

publish(10,'moral-exclusion-dehumanization','Moral Exclusion, Dehumanization, and Rehumanization','Examine how language and procedures can narrow whose needs count, and practice restoring specificity, agency, and fair consideration without ignoring real constraints.',[
lesson('Recognize the boundary of moral concern',['Explain moral exclusion using a fictional decision.','Distinguish a legitimate eligibility rule from denying a person’s dignity.','Identify whose interests disappear from a justification.'],'''Moral exclusion concerns the boundary around people whose needs and treatment are regarded as deserving ordinary fairness. Susan Opotow’s work examines how people can be placed outside that boundary. In public service, the question is not whether every request must be granted. Resources, eligibility, safety, and authority create real limits. The question is whether a person remains entitled to an accurate explanation, respectful treatment, and a fair process even when the answer is no.

Exclusion can appear in a justification that makes a group’s inconvenience, error, or suffering irrelevant. A team may describe some people as not worth explaining things to, or assume that a category of service users cannot contribute useful information. The concern is the change in moral consideration, not merely an impolite word. A procedure can be written politely while treating some people’s need for clarification as unworthy of attention. Examine what the language permits people to overlook.

Distinguish moral concern from agreement or approval. A person can behave harmfully and still be entitled to proportionate procedures. A service request can be ineligible while the requester still deserves understandable information about the decision and available routes. Maintaining that distinction is especially important under workload pressure, when simplifying labels can make difficult decisions feel easier. The goal is not to eliminate boundaries, but to ensure that boundaries remain connected to legitimate purposes and do not erase the person’s standing.

Use a decision audit with three questions. Whose interests are included in the explanation? Whose interests are treated as irrelevant? What rule justifies that difference? A justified distinction should be explainable through the work, evidence, and authority involved. If the explanation rests on a broad assumption about a group’s worth, motivation, or humanity, the decision needs closer examination. Do not label a colleague morally excluded or inhuman in response. Redirect attention to the reasoning and its consequences. Rehumanizing practice begins by restoring the expectation that every person’s situation can be described accurately and considered within a fair, proportionate process.''','A fictional team rejects an ineligible request and says there is no point explaining the decision to people like that.','Maintain the eligibility decision if justified while providing an understandable explanation and appropriate next route.','A limit on service does not remove the person’s entitlement to respectful, accurate process.','Approve every request because any refusal is moral exclusion.','Legitimate boundaries can coexist with dignity; the issue is how people are considered and treated.','When does frustration make someone’s need for an explanation seem less important?','Review a fictional refusal for the rule, evidence, explanation, and person’s continuing procedural standing.'),
lesson('Distinguish dehumanizing language from useful categorization',['Identify language that erases agency or individuality.','Distinguish a necessary administrative category from a total description of a person.','Rewrite a note using specific observable information.'],'''Dehumanization involves denying or diminishing qualities associated with being fully human. Nick Haslam’s framework distinguishes forms that deny qualities such as civility or maturity from forms that treat people as objects, mechanisms, or interchangeable units. These distinctions help examine both overtly degrading language and ordinary impersonal practices. They do not mean that every shorthand term or administrative category is dehumanizing. The context and consequence of the description matter.

Organizations need categories to manage work. A case number, eligibility status, or service category can be useful and appropriate. The problem arises when the category becomes the whole account of the person or justifies ignoring their agency and circumstances. A record that identifies a missed appointment provides relevant information. A record that treats the person as inherently noncompliant may obscure whether the notice arrived, the location was accessible, or the person had a way to reschedule. Specificity improves both respect and decision quality.

Examine verbs as well as nouns. Does the note describe what happened, or assign a fixed character? Does it distinguish a person’s choice from a barrier in the process? Does it preserve the person’s own stated preference where relevant? Accurate documentation can include difficult behavior and safety concerns without degrading the person. Avoid replacing precise evidence with vague positivity. Rehumanization does not require pretending that a harmful event did not occur; it requires describing the event and responding proportionately rather than reducing the person to it.

Practice rewriting a fictional note. Replace a global label with the observed sequence, identify missing information, and state the next appropriate action. Keep the detail relevant and respect privacy. Do not add an imagined personal story to make the person seem sympathetic. Human standing should not depend on whether the writer can produce an emotionally appealing biography. The improvement is an account that supports a fair decision: what occurred, what is known, what the person communicated, and what needs clarification. Such writing can reduce the space in which contempt or indifference becomes an unexamined part of routine work.''','A fictional note says a person is impossible and does not care. The only documented event is a missed call after an inaccessible notice.','Record the missed call, the notice barrier, and the appropriate follow-up without assigning a fixed character.','Specific information supports a better decision and preserves the distinction between behavior and identity.','Delete all mention of the missed call because negative information is dehumanizing.','Accurate relevant events still belong in the record; the problem is an unsupported total judgment of the person.','Which label makes you feel that you already know the whole person?','Rewrite one fictional note into observed event, relevant context, uncertainty, and next action.'),
lesson('Restore agency without making empathy a requirement',['Distinguish agency from a story designed to evoke sympathy.','Identify a decision point where a person can make an informed choice.','Design a respectful response under a real constraint.'],'''Rehumanization should restore a person’s standing and agency rather than require them to become emotionally understandable to the decision maker. Personal stories can deepen understanding, but access to fair treatment should not depend on telling a compelling story. Some people do not want to disclose, cannot safely disclose, or communicate in ways an audience finds less familiar. A fair process must work for them too. Respect should not be conditional on the listener’s emotional response.

Agency means having meaningful ways to understand, express preferences, and act within the available choices. A form that offers two technically different options may provide little agency if neither is understandable or usable. A meeting that asks for input after the decision is fixed may create the appearance of participation. Examine where a person can actually affect the next step. Explain limits honestly, provide accessible information, and distinguish a choice that is real from one that cannot change anything.

Constraints do not excuse degrading treatment. A staff member may need to end an unsafe interaction, enforce an eligibility requirement, or decline an unauthorized request. The response can still name the specific reason, use proportionate action, and explain any appropriate next route. Do not ask staff to absorb abuse as proof of empathy. Preserve safety and formal procedures while avoiding language that casts an entire group as undeserving. A person’s behavior can require a boundary without erasing their humanity.

Test a proposed response by imagining that the person offers no personal story and does not express gratitude. Would the explanation, access support, and decision remain the same? If not, the process may depend too much on emotional approval. Use the job aid to identify the decision, the legitimate constraint, the available choices, and how the person can seek clarification or review. The aim is not limitless agreement. It is a relationship in which institutional power remains accountable and the person remains someone whose preferences, understanding, and rights matter. This makes rehumanization a practical feature of ordinary decisions rather than a temporary feeling produced by a moving narrative.''','A fictional worker offers a review route only after hearing a particularly moving personal account from one requester.','Make the appropriate review route understandable and available to everyone eligible for it.','Fair process should not depend on a person’s ability or willingness to evoke sympathy.','Require all requesters to share a personal hardship story so staff can empathize.','Compelled disclosure adds a burden and makes humane treatment depend on emotional performance.','Would your response remain respectful if the person did not explain their life or thank you?','Write a response naming the legitimate constraint, available choices, accessible explanation, and review route.'),
lesson('Examine routines that normalize indifference',['Identify a routine that distances decisions from their consequences.','Select a process improvement that preserves dignity.','Review effects without stigmatizing staff or service users.'],'''Indifference can become routine when people see only a small part of a process. One team sends a notice, another closes a case, and another receives the call from someone who never understood what happened. Each action may follow a local rule while nobody sees the accumulated burden. This does not establish that staff lack empathy. It suggests that the organization’s feedback structure may keep decision makers distant from the consequences of their work. Examining that structure is more useful than assigning a moral character to the team.

Reconnect decisions with relevant consequences through appropriate evidence. Review a de-identified fictional journey, examine authorized process records, or invite voluntary feedback through a suitable route. Do not expose personal information or require people to recount distress publicly. The question is which step produces avoidable confusion, delay, humiliation, or loss of agency. A process map can reveal that a standard notice assumes knowledge nobody has explained or that the route for correcting an error is much harder than the route for making it.

Choose a practical improvement. It might be a clearer explanation at the point of refusal, a correction route that does not require repeated retelling, or a review of labels used in case notes. Preserve accurate documentation and legitimate requirements. Replacing every administrative term with warmer language is not enough if the decision pathway stays inaccessible. Conversely, a concrete improvement can matter even when it does not transform every relationship. Evaluate the specific condition you changed rather than making a broad claim that the organization is now humane.

Include staff conditions in the analysis. Excessive workload, fragmented responsibility, and unclear authority can make attentive practice harder. Addressing those conditions supports better treatment without excusing harmful conduct. Report the observed barrier, the change, the evidence of use, and remaining constraints. Avoid ranking employees by empathy or inferring an IDI orientation from their language. The programme’s developmental aim is better attention to difference and responsive action. A useful review leaves both staff and service users with a clearer, more respectful process and a named responsibility for the next improvement.''','A fictional team rewrites a refusal letter politely but leaves an unusable correction route unchanged.','Test the correction route and improve the practical steps as well as the wording.','Respectful language matters, but dignity also depends on a usable way to correct an error.','Declare the problem solved because the letter sounds warmer.','Tone alone does not repair a process that prevents people from acting on the information.','Where does your part of a process hide consequences that another team sees?','Map one decision’s downstream effects and propose a reviewable change to explanation, agency, or correction.')],
[('Moral exclusion','Treating some people as outside the boundary of ordinary fairness and concern.'),('Dehumanization','Diminishing people’s human qualities or treating them as objects or interchangeable units.'),('Agency','Meaningful ability to understand, express preferences, and act within real choices.'),('Rehumanization','Restoring specificity, standing, and agency without requiring sympathy, disclosure, or agreement.')],
[('Examine the reasoning',['Identify whose interests count and whose disappear.','Distinguish a legitimate boundary from a judgment of human worth.','Ask whether the explanation would remain respectful without a personal story.']),('Improve the record and response',['Describe observable events rather than fixed character labels.','Preserve relevant preferences, context, and uncertainty.','Explain constraints and real choices in accessible language.','Use proportionate safety boundaries and appropriate formal procedures.']),('Review the routine',['Trace consequences across handoffs.','Check whether correction routes are usable.','Address workload and unclear responsibility alongside conduct.','Measure the specific process change without claiming universal transformation.'])],
[('Opotow (1990), Moral Exclusion and Injustice: An Introduction','https://spssi.onlinelibrary.wiley.com/doi/10.1111/j.1540-4560.1990.tb00268.x','Foundational theoretical account of the scope of moral concern. Workplace cases are original applications, not claims about particular employees.'),('Haslam (2006), Dehumanization: An Integrative Review','https://pubmed.ncbi.nlm.nih.gov/16859440/','Theoretical research review distinguishing forms of dehumanization; not a diagnostic classification for staff.'),('Haslam and Loughnan (2014), Dehumanization and infrahumanization','https://pubmed.ncbi.nlm.nih.gov/23808915/','Research review covering mechanisms, evidence, and limitations. No single wording choice establishes a person’s motives.')])
