exec((__import__('pathlib').Path(__file__).parent/'write-packs.py').read_text(encoding='utf-8-sig'))
publish(5,'racial-battle-fatigue','Racial Battle Fatigue and Cumulative Identity-Related Stress','Understand cumulative racialized burdens and practice organizational responses that reduce demands without diagnosing colleagues or requiring disclosure.',[
lesson('Understand cumulative burden without diagnosing a person',['Explain cumulative burden using a fictional sequence.','Distinguish a research concept from a clinical diagnosis.','Identify an organizational condition that can be changed.'],'''Racial battle fatigue describes cumulative strain associated with navigating racialized hostility and repeated racial stressors. William A. Smith and colleagues developed the concept in research on racialized experiences, including Black college students. It should not be converted into a diagnosis made by a supervisor or a checklist applied to a coworker. An employee who seems tired, quiet, or frustrated may have many reasons for that experience. You do not need to determine the person’s health condition in order to examine an unnecessary organizational burden.

The cumulative perspective asks what repeated events require from a person over time. A single interruption may appear small. Repeated demands to explain a name, defend expertise, correct a stereotype, or educate colleagues can consume attention and effort. The person may also need to decide whether responding will create another burden. This is a way to examine a sequence, not a claim that everyone with the same identity experiences it identically. Differences in context, resources, relationships, and personal preference matter.

Research on discrimination and health provides reasons to take these experiences seriously, but population-level associations do not identify the cause of an individual’s symptoms. The course offers organizational learning, not clinical assessment or treatment. Staff who want personal health support should use appropriate professional resources of their choice. Participation in this course never requires describing trauma, identifying a diagnosis, or discussing a private experience with a manager. Fictional cases are sufficient for every activity.

Begin with conditions the organization can observe and change. Is one person repeatedly asked to speak for a group? Are concerns met with requests for more personal testimony rather than examination of the conduct? Does the same employee perform unpaid explanatory work while others receive credit for the project? These questions focus on workload, decision practices, and interpersonal expectations. Addressing them can be justified without proving that someone is ill. A responsible response reduces an identified burden, preserves access to formal support and reporting, and allows the person to choose whether further conversation would be helpful. It does not place responsibility for fixing the environment entirely on the person experiencing the strain.''','A fictional supervisor notices a colleague is quieter after repeatedly being asked to explain racial issues in meetings.','Stop assigning representative duties and offer a private, optional conversation about workload and support.','The response changes an observable burden without claiming to diagnose the colleague or requiring a personal explanation.','Tell the colleague they have racial battle fatigue and record it in their performance notes.','A learning concept is not authority to diagnose or record a health condition; the behavior alone cannot establish a cause.','What repeated demand could be burdensome even if each occurrence seems minor?','List one recurring organizational demand that can be reduced without asking anyone to disclose health information.'),
lesson('Map the work of managing an identity-related incident',['Identify practical and emotional demands in a fictional incident sequence.','Distinguish optional support from compulsory processing.','Propose a redistribution of organizational work.'],'''An identity-related incident can create work long after the original interaction ends. Someone may need to decide whether to respond, locate a reporting route, describe the event, correct a record, manage colleagues’ reactions, and continue the ordinary job. Other people may experience the incident as a brief awkward moment while the affected person carries the follow-up. Mapping those demands helps an organization see responsibilities that would otherwise remain invisible or be misclassified as the person’s difficulty coping.

Separate three kinds of work. Practical work includes arranging a corrected document or an alternative meeting. Explanatory work includes repeatedly describing why an event matters. Relationship-management work includes reassuring others, handling defensiveness, or deciding whether a response will affect future opportunities. These categories are a learning aid, not a clinical model or a measurement scale. They help locate what the organization can own. An appropriate reviewer can examine conduct, a manager can redistribute tasks, and a facilitator can stop requiring one person to educate everyone.

Offer choices rather than prescribing emotional processing. A person may want a direct correction, a formal report, practical support, a confidential resource, time, or no further conversation with a particular colleague. Do not interpret declining a conversation as lack of professionalism or unwillingness to heal. Do not promise confidentiality beyond what the relevant process can provide. Explain the available route and its boundaries clearly, then respect the person’s decisions within the responsibilities that apply to your role.

Redistribution is not the same as speaking over someone. Ask what practical action is welcome when appropriate, but do not make every ordinary corrective step depend on the affected person designing it. For example, a meeting leader can establish a rule against assigning cultural spokesperson duties without asking a colleague to disclose why that rule matters. Where a formal concern has been raised, follow the proper process rather than negotiating an informal resolution around the person. A useful burden map ends with named organizational responsibilities and a check that the response itself has not created another demand for explanation, gratitude, reassurance, or public participation.''','After a fictional identity-related remark, the affected employee is asked to design the team’s training and reassure the speaker.','Assign the organization’s learning and follow-up work to appropriate staff and offer the employee choices about participation.','The organization can own its response without requiring the affected person to provide education or reassurance.','Treat leading the training as the employee’s opportunity to turn the incident into something positive.','That framing can add work and pressure; participation should not become an expectation attached to being harmed.','Which part of a response could become another burden even when described as supportive?','Map practical, explanatory, and relationship-management tasks, then assign appropriate organizational owners.'),
lesson('Respond supportively while preserving boundaries',['Draft a supportive response that avoids health assumptions.','Identify a promise that exceeds a manager’s authority.','Preserve access to formal reporting and professional support.'],'''A supportive response can be direct without being intrusive. Describe the observable issue, acknowledge its significance, and explain what you can do. For example, a manager can say that repeated interruptions and demands for cultural explanation are not necessary for the work and will be addressed. The manager does not need to ask whether the employee is traumatized. A person may choose to discuss an impact, but support should not depend on the disclosure being sufficiently personal or emotionally compelling.

Keep the role clear. A supervisor can address workload, conduct, access, and the responsibilities of the team. A clinician provides health assessment and treatment. An authorized investigator or formal process evaluates certain complaints. A colleague can offer practical assistance and respectful company. These roles can complement one another, but they should not be collapsed into an informal conversation that promises to solve everything. Explain when another role is needed and avoid presenting referral as a way to dismiss the organizational issue.

Language matters because apparent reassurance can shift responsibility. Telling someone not to take an incident personally can minimize the actual conduct. Telling them they must report immediately may ignore their circumstances and the scope of your authority. Telling them everything will remain confidential may be inaccurate. A stronger response explains available options and any relevant limits, asks what practical support would help, and follows through on the actions within your control. Do not request a medical account in a learning discussion.

Check the environment after the initial response. Has the conduct stopped? Has the workload been adjusted? Are colleagues pressuring the person to forgive, educate, or demonstrate that they are fine? Has access to assignments changed after a concern was raised? These are organizational questions that can be reviewed without evaluating someone’s private emotional recovery. Use appropriate authorized channels for concerns about discrimination or retaliation. The aim is dependable support and a less burdensome environment, not a visible performance of resilience. A person should be able to continue their work and choose appropriate support without becoming the public evidence that the team has learned its lesson.''','A fictional manager offers help but promises that anything said will remain completely secret, despite not knowing the reporting obligations of the situation.','Explain the limits of the manager’s role and available options before inviting further details.','Clear boundaries support informed choice and avoid a promise the manager may be unable to keep.','Promise complete secrecy so the employee will feel comfortable sharing.','Unsupported confidentiality assurances can undermine trust and prevent informed decisions about disclosure.','What supportive phrase might unintentionally ask someone to reassure you?','Draft a three-sentence response: acknowledge the observable concern, explain your role, and offer a practical choice.'),
lesson('Reduce recurring burdens and review the environment',['Choose a recurring organizational demand to change.','Select an appropriate process measure without monitoring private distress.','Distinguish a learning intervention from a health outcome claim.'],'''An organization can review whether it has reduced an unnecessary burden without measuring employees’ private distress. If the problem is repeated spokesperson requests, examine how meetings assign expertise and participation. If the problem is repeated retelling of a concern, examine handoffs between authorized offices. If the problem is unequal access to recovery after an incident, examine how practical support is offered. These measures focus on the environment rather than asking people to prove that they feel better.

Choose one narrow change with a clear owner. A meeting protocol might ask for role-related expertise rather than assigning a racial representative. A reporting handoff might explain what information can be shared appropriately so a person does not have to begin again unnecessarily. A project plan might allocate time for participation in equity work rather than assuming it occurs without workload consequences. The change should address the identified demand, not merely add a wellness activity while leaving the demand intact.

Invite feedback through a route that does not require public disclosure. Explain what information is needed, who will review it, and how it will be used. Do not create a roster of people assumed to experience racial battle fatigue or ask managers to rate employees’ resilience. Small-group feedback can be identifying even when names are removed, so use appropriate privacy and analytic support. A lack of complaints is not proof that the environment improved; people may not find the route useful or safe.

Report results proportionately. You may be able to say that meetings no longer assign spokesperson duties, that a handoff requires fewer repeated explanations, or that workload allocation became clearer. You cannot infer from those process changes that the intervention cured stress, eliminated discrimination, or improved a particular person’s health. Those would require different evidence and, in some cases, professional assessment. The practical aim is a workplace that takes responsibility for preventable demands and responds credibly when concerns arise. Continue, revise, or stop the change based on the observed process and appropriate feedback, while preserving individual choice about support and participation.''','A fictional team stops asking staff to represent racial groups and receives fewer concerns at meetings.','Report the changed meeting practice and seek appropriate feedback without claiming that distress has been eliminated.','A process change is observable; private health outcomes cannot be inferred from fewer complaints.','Announce that the intervention cured racial battle fatigue across the team.','The evidence does not support a clinical or universal outcome claim, and silence has multiple explanations.','What would count as an environmental improvement even if nobody shares a personal story?','Create a review plan for one recurring burden, including a process measure, feedback route, owner, and limits on conclusions.')],
[('Cumulative burden','Demands that accumulate through a sequence of events rather than one isolated moment.'),('Racial battle fatigue','A research concept concerning racialized stress; not a diagnosis for supervisors to assign.'),('Organizational response','Changes to conduct, workload, procedures, or access that do not depend on personal disclosure.'),('Support choice','The person can choose among appropriate options; participation or forgiveness is not a condition of practical support.')],
[('Observe without diagnosing',['Describe the recurring conduct or demand.','Do not infer a health condition from quietness, fatigue, or frustration.','Use fictional examples for learning when personal discussion is unwelcome.']),('Reduce the burden',['Map practical, explanatory, and relationship-management work.','Assign organizational learning to appropriate staff.','Offer choices without requiring disclosure, gratitude, or forgiveness.','Explain the boundaries of your role and any information-sharing limits.']),('Review conditions',['Check whether the conduct and demands changed.','Preserve formal reporting and appropriate professional support.','Do not collect private distress ratings or inferred identity labels.','Report process improvements without claiming health effects.'])],
[('Smith, Allen, and Danley (2007), Assume the Position… You Fit the Description','https://journals.sagepub.com/doi/abs/10.1177/0002764207307742','Primary qualitative research on racial battle fatigue among African American male college students. Its sample and setting do not establish prevalence or diagnosis among DHS staff.'),('Nunez-Smith and colleagues (2007), Impact of race on the professional lives of physicians of African descent','https://pubmed.ncbi.nlm.nih.gov/17200221/','Primary qualitative workplace research describing racialized professional experiences and fatigue. It does not justify individual clinical conclusions.'),('Pascoe and Smart Richman (2009), Perceived discrimination and health','https://pubmed.ncbi.nlm.nih.gov/19586161/','Research synthesis provides context for discrimination-health associations, not a clinical screening or causal diagnosis of an individual.')])

publish(6,'restorative-identity-harm','Restorative Responses to Identity-Based Harm','Evaluate when a voluntary restorative response may be appropriate, prepare for unequal power, and build accountable repair without replacing formal protections.',[
lesson('Distinguish restoration from pressure to reconcile',['Distinguish repair from reconciliation and forgiveness.','Identify conditions needed before a restorative conversation.','Explain why participation must remain voluntary.'],'''A restorative response asks what harm occurred, who was affected, what responsibilities follow, and what repair may be possible. It is not simply a meeting in which people apologize and move on. Restoration can involve practical correction, acknowledgment, changed conduct, or an agreement about future interaction. Reconciliation concerns a relationship; forgiveness is a personal choice. Neither should be demanded as proof that the response succeeded. Someone can receive a repair and still choose not to resume a close relationship.

The United Nations restorative-justice handbook emphasizes informed and voluntary participation, preparation, safeguards, and attention to unequal power. Its principal setting is criminal justice. Applying any principles to a workplace requires care, relevant expertise, and compatibility with the formal processes governing that workplace. This course does not turn staff into qualified restorative facilitators or establish a new complaint procedure. It develops judgment about whether such an approach could be considered and what boundaries would need to be protected.

Identity-based harm may involve unequal authority, repeated conduct, threats to opportunity, or concerns about retaliation. A meeting can intensify those problems if the affected person feels compelled to attend or to accept an explanation. Before considering a joint conversation, ask whether participants can decline without a penalty, understand available alternatives, and receive appropriate support. A manager’s friendly invitation can still feel compulsory when the manager controls assignments or evaluations. The practical conditions matter more than describing the conversation as voluntary.

Formal reporting, investigation, accommodation, safety, or other required procedures must remain available. A restorative option must not be offered as the price of avoiding consequences, obtaining support, or having a concern taken seriously. Do not promise secrecy or a particular outcome that you cannot deliver. A useful starting point is separate preparation with a suitably qualified and independent facilitator where appropriate, including a clear explanation of scope and limits. If those conditions cannot be established, declining or postponing the restorative route is responsible practice. The goal is accountable repair with genuine choice, not a quick return to organizational comfort.''','A fictional supervisor tells two employees that attending a restorative meeting will show they are team players. One employee raised an identity-related concern.','Remove the pressure and clarify independent alternatives before considering any restorative option.','Participation tied to perceived teamwork is not a genuine choice, especially where authority is unequal.','Proceed because the supervisor described the meeting as supportive.','Supportive language does not remove the employment pressure created by the invitation.','What consequence could make an apparently optional invitation feel compulsory?','List the conditions that would permit a person to decline a restorative option without losing support or opportunity.'),
lesson('Prepare for power, access, and information boundaries',['Identify a power imbalance in a proposed process.','Specify an access and support need without requiring disclosure.','Draft clear information-sharing boundaries.'],'''Preparation is substantive work. A facilitator needs to understand the concern, the relationships, the relevant formal processes, and whether the proposed format is suitable. Separate conversations may reveal that participants understand the purpose differently: one expects acknowledgment, another expects exoneration, and a manager expects closure. Those differences must be addressed before a joint meeting. A shared room cannot resolve a hidden disagreement about what the room is for or who has authority over the outcome.

Map power concretely. Who controls schedules, references, assignments, evaluations, or access to future opportunities? Who can leave the process without material consequences? Who has a support person or access to advice? An imbalance does not automatically make every restorative option impossible, but it changes the safeguards required and may make a joint format unsuitable. Do not assume that a neutral tone from the facilitator neutralizes the surrounding employment relationship. Independence, preparation, and a credible alternative route matter.

Arrange access before the process begins. Offer understandable materials, communication supports, accessible locations or formats, sufficient time, and the option to identify needs privately through an appropriate route. Avoid requiring a person to explain an identity or diagnosis to the group. Allow participants to consider whether they want a support person where the process permits it. Clarify how pauses, withdrawal, or a change of format will work. These are conditions for informed participation, not rewards for cooperative behavior.

Define the record. Explain what will be noted, who can receive it, how agreements are tracked, and which confidentiality limits apply. Do not invent a blanket promise that everything stays in the room. Distinguish the restorative discussion from any authorized investigation or formal record, and obtain appropriate guidance where the boundaries are unclear. Participants should know whether declining or withdrawing affects any separate process. A well-prepared option may end with the conclusion that no joint conversation should occur. That is not failure; it is evidence that the process respected its limits rather than making participation the predetermined outcome.''','A fictional manager who is the subject of a concern offers to facilitate the restorative meeting and keep all notes.','Seek an appropriately independent process and clarify record boundaries before proceeding.','The manager’s dual role affects power and trust; preparation must address it rather than relying on goodwill.','Proceed if the manager promises to be neutral.','A promise of neutrality does not remove the manager’s stake or control over participants’ opportunities.','Which authority relationship would make withdrawal difficult in this case?','Draft a preparation checklist covering authority, alternatives, access, support, withdrawal, and the record.'),
lesson('Build repair that is specific and accountable',['Translate a general apology into a concrete repair proposal.','Distinguish responsibility from forced agreement about motive.','Specify a reviewable commitment.'],'''A repair agreement should identify what will change. An apology may matter to participants, but it cannot substitute for correcting an inaccurate record, stopping a practice, restoring access, or addressing a continuing burden. The agreement should connect each action to the harm described and to the authority of the person undertaking it. Promising to eliminate bias is not a practical commitment. Promising to correct a misattributed contribution, revise a meeting practice, and review follow-through is more specific.

Responsibility does not always require agreement about every interpretation of motive. People may disagree about why a comment was made while agreeing that it interrupted someone’s participation or repeated an inaccurate claim. A facilitator can help distinguish established events, contested explanations, and possible actions. This is not permission to minimize serious conduct or bypass a formal determination that belongs elsewhere. It is a way to avoid making every practical repair depend on a complete shared account of a person’s internal state.

Do not place the work of repair entirely on the affected person. They may identify what would help, but should not have to create a training program, supervise compliance, or reassure the other participant. Assign actions to those responsible and able to carry them out. Preserve choice about direct contact and future relationship. A commitment should not require public forgiveness, a positive statement about the organization, or withdrawal of a formal concern. Those conditions can turn restoration into pressure and weaken genuine accountability.

Write the agreement in plain language. State the action, responsible person, completion date, evidence of completion, and what happens if the action is not completed. Distinguish what can be promised from what requires another decision maker’s approval. Check whether sharing the agreement itself could expose sensitive information unnecessarily. Establish an appropriate review route and a way to raise a concern about retaliation or new harm. The resulting record should make the practical commitments visible while respecting the boundaries of the process. Success is not measured by how comfortable observers feel at the end of the conversation, but by whether agreed responsibilities are fulfilled without creating another burden.''','A fictional agreement says both employees will be positive and put the incident behind them. The inaccurate project credit remains unchanged.','Specify correction of the credit, responsibility for communicating it, and a follow-up date without requiring forgiveness.','A concrete repair addresses the continuing consequence and can be checked.','Keep the broad positivity agreement because measurable actions would feel punitive.','Vague expectations can pressure the affected person while leaving the actual harm unrepaired.','What practical consequence would remain after a sincere apology in this case?','Write one repair commitment with action, owner, date, completion evidence, and an escalation route.'),
lesson('Evaluate the process without declaring closure for others',['Separate implementation, participant experience, and longer-term outcomes.','Identify an inappropriate success measure.','Choose when to stop or redirect a restorative process.'],'''Restorative approaches have been studied in particular settings, including criminal-justice conferencing. Evidence from those settings cannot be transferred automatically to workplace identity-based harm. A positive average result elsewhere does not prove that a specific meeting is safe, voluntary, or effective here. Evaluate the actual process and remain willing to stop or redirect it. The research can inform questions and safeguards without functioning as a guarantee or a reason to persuade reluctant participants.

Separate three kinds of evidence. Implementation concerns whether agreed actions occurred and safeguards were followed. Participant experience concerns whether people found the process understandable and voluntary, using an appropriate optional feedback route. Longer-term outcomes concern whether conduct, access, or relationships changed. These are not interchangeable. An agreement can be completed while a person remains dissatisfied. A person can value a conversation while the promised organizational correction never happens. Record the distinction rather than collapsing everything into a single success claim.

Do not use forgiveness, public endorsement, emotional calm, or withdrawal of a complaint as required measures of success. People may remain angry, cautious, or unwilling to meet again while making a reasonable choice about the future. They should not be asked to demonstrate recovery for the organization’s benefit. Likewise, the person responsible for a repair should not receive a guarantee that completing it will erase every consequence. Maintain the boundaries between learning, repair, and formal authority throughout the process.

Set conditions for stopping. New pressure, retaliation concerns, inability to participate safely, disputed confidentiality terms, or a facilitator’s lack of appropriate competence may require a pause or referral. Explain the next available route without treating withdrawal as wrongdoing. At review, state which commitments were completed, what remains unresolved, and who holds responsibility. A restorative process can contribute to repair while leaving a relationship changed and a formal matter open. A mature evaluation respects that complexity. It does not claim closure on someone else’s behalf or require an emotionally satisfying ending to recognize a useful, limited improvement.''','A fictional follow-up finds that the promised correction occurred, but one participant declines further meetings.','Record completion of the correction and respect the decision while preserving available support and formal routes.','Completion of an action and willingness to continue a relationship are separate matters.','Mark the process unsuccessful unless the participant publicly forgives the other person.','Forgiveness is personal and cannot serve as a required institutional performance measure.','What would a useful but incomplete repair look like?','Create a follow-up record separating completed actions, optional feedback, unresolved concerns, and next responsibility.')],
[('Repair','A concrete response to harm, such as correction, restored access, or changed conduct.'),('Reconciliation','A change in a relationship; it cannot be required as proof that repair occurred.'),('Informed voluntary participation','A real choice made with understanding of purpose, alternatives, boundaries, and withdrawal.'),('Formal-process boundary','Restorative activity does not replace required procedures or access to complaint and support routes.')],
[('Decide whether to consider the option',['Identify the harm, relevant formal processes, and decision authority.','Check whether participation can be declined without penalty.','Use suitably qualified facilitation and examine independence.']),('Prepare before meeting',['Clarify purpose, alternatives, access, support, and withdrawal.','Name power relationships and safeguards.','Explain records and confidentiality limits accurately.','Pause if the conditions cannot be established.']),('Write and review repair',['Specify action, owner, date, and evidence of completion.','Do not require forgiveness, public testimony, or complaint withdrawal.','Separate implementation from experience and longer-term outcomes.','Redirect through appropriate channels when new harm or pressure appears.'])],
[('UNODC (2020), Handbook on Restorative Justice Programmes, second edition','https://www.unodc.org/documents/justice-and-prison-reform/20-01146_Handbook_on_Restorative_Justice_Programmes.pdf','Authoritative guidance on voluntary participation, safeguards, and programme design. Its justice-system context is distinct from these program-authored workplace exercises.'),('Strang and colleagues (2013), Restorative justice conferencing systematic review','https://www.campbellcollaboration.org/review/restorative-justice-conferencing-recidivism-victim-satisfaction/','Research review on face-to-face criminal-justice conferencing. Outcomes in those studies are not evidence that a workplace identity-harm meeting will be effective or appropriate.')])
