exec((__import__('pathlib').Path(__file__).parent/'write-packs.py').read_text(encoding='utf-8-sig'))
publish(3,'intersectional-discrimination','Intersectional Discrimination: Advanced Case Analysis','Analyze interacting forms of exclusion through carefully bounded cases, avoiding both single-category explanations and assumptions based on identity.',[
lesson('Why separate categories can miss a combined barrier',['Explain the limitation of a single-category comparison.','Identify an interacting mechanism in a fictional case.','Distinguish intersectional analysis from adding identity labels.'],'''Intersectionality is not an exercise in counting identities. It asks how social arrangements interact so that a person’s experience may not be explained adequately by examining one category at a time. Kimberlé Crenshaw’s foundational legal analysis showed how a framework organized around separate race and sex categories could fail to recognize the experiences of Black women. The analytical lesson is to examine the mechanism of exclusion rather than assume that each category operates independently or contributes an identical amount of disadvantage.

Imagine a fictional professional-development opportunity held after normal work hours. Childcare responsibilities, transportation, disability-related fatigue, and access to informal sponsorship may shape whether someone can participate. Listing these factors is only the beginning. An intersectional analysis asks how the arrangements combine. A staff member might have manageable transportation and manageable caregiving separately, yet find that the final bus leaves before the caregiver’s availability begins. The barrier emerges from the relationship between conditions, not from the number of identities assigned to the person.

Race and gender should not disappear into an undifferentiated list of personal circumstances. They can shape how responsibilities are distributed, how credibility is granted, and whose constraints receive accommodation. At the same time, an analyst cannot infer an individual’s circumstances from racial or gender identity. Ask what the case actually establishes. Distinguish an observed event, a plausible mechanism, and a question requiring more information. That distinction allows serious attention to structural patterns without turning a theoretical framework into a stereotype.

Use comparison carefully. If a report shows that women overall and Black staff overall participate at similar rates to others, that does not establish that Black women have comparable access. Broad averages can conceal a combined pattern. But a small subgroup count may also be unstable or identifying. Work with authorized data and appropriate analytic support rather than constructing personal identity profiles for a learning exercise. A good case analysis can begin with the process itself: the timing, eligibility rules, nomination route, and support available. It asks which combination creates a barrier and what change would address that combination without requiring a person to prove that one identity was the sole cause.''','A fictional report finds no overall gender difference and no overall racial difference in access to assignments. A combined subgroup has repeatedly been left out, but the count is small.','Examine the assignment process and consult authorized analysts about a privacy-preserving combined analysis.','Separate averages can miss interacting barriers, while a small subgroup still requires privacy and careful interpretation.','Conclude that the separate averages prove the process is equitable.','Separate summaries do not test whether a combined group experiences a distinct mechanism.','When has a category used in a report hidden an important difference within it?','Draw a process map showing where two conditions combine to restrict an opportunity.'),
lesson('Build an interaction map rather than an identity inventory',['Map a barrier across rules, resources, and interpretation.','Identify a missing fact that could change a case explanation.','Choose a comparison that tests a proposed mechanism.'],'''An interaction map connects a person’s route through a process to the conditions that shape it. Begin with the outcome to be explained: an opportunity missed, a service delayed, a concern dismissed, or an additional burden imposed. Then reconstruct the sequence. What did the person encounter first? What choices were actually available? What information did the organization request, and how did it interpret the response? This sequence prevents the analysis from becoming a collection of identity labels with no account of how anything happened.

Use three columns: rule, resource, and interpretation. A rule might require participation at a fixed time. A resource might be paid release time, accessible transport, or a contact who explains the process. An interpretation might treat a request for flexibility as lack of commitment. The interaction matters because the same written rule can have different consequences depending on available resources and how a request is received. Do not assume that a request was rejected because of bias; document the stated reason and examine comparable responses.

Seek evidence that could disconfirm the first explanation. Perhaps the opportunity was genuinely unavailable to everyone during a particular period. Perhaps the person was never informed of an existing alternative. Perhaps similar flexibility was routinely granted to people with stronger informal sponsorship. Each possibility suggests a different repair. An analyst who asks only for confirming examples can produce an emotionally compelling account that does not accurately explain the decision. Rigorous equity analysis welcomes information that changes the initial interpretation.

Choose comparisons that preserve the relevant context. Comparing every employee to every other employee may obscure differences in role, eligibility, and timing. Comparing only people who completed the process may exclude those blocked at its entrance. State why the selected comparison is useful and what it cannot establish. Crenshaw’s later work on structural and political intersectionality also reminds readers that institutional responses can leave people between categories of support. For this practice, identify which office or process owns the combined issue rather than sending the person repeatedly between separate channels. The map should make responsibility clearer, not create another demand for the person to narrate their identity or repeat painful experiences.''','A fictional employee is referred between an access coordinator and a development coordinator because each says the other owns the barrier to a training assignment.','Map the combined barrier and arrange a coordinated response with clear responsibility.','The interaction is lost when each process treats only one component; coordination can address the actual route to participation.','Ask the employee to choose which identity caused the problem.','The barrier may arise through interacting conditions, and forcing a single identity explanation misstates the analysis.','What missing fact would make you change your first explanation of this case?','Complete a rule-resource-interpretation map and name the person responsible for coordinating the response.'),
lesson('Compare remedies for the combined problem',['Compare a universal improvement with a targeted repair.','Identify an unintended burden in a proposed remedy.','Draft an explanation that preserves individual choice.'],'''A remedy should respond to the mechanism identified, not merely display awareness of multiple identities. If the problem is that training occurs only after hours, a general improvement might provide work-time options. If an inaccessible format also excludes some participants, changing the schedule alone will not solve the combined barrier. A targeted repair may still be needed alongside the general change. Universal and targeted approaches are not mutually exclusive; they answer different parts of the problem.

Test each proposed response against the full route. Who learns about the option? Who can request it without disclosing unnecessary information? Who approves it? Does choosing the alternative affect access to mentoring, visibility, or meaningful participation? A recorded session may provide information while excluding the informal discussion that leads to assignments. A separate route can unintentionally become a lower-value route. The question is whether people can obtain a substantially useful opportunity, not whether the organization can point to any alternative at all.

Preserve the person’s agency. Do not assume that a staff member wants an identity-specific program, a particular mentor, or public recognition of the barrier. Offer relevant options and explain consequences. Where a response involves disability accommodation, discrimination concerns, or other formal rights, use the authorized process and qualified support. This course develops analytical practice; it does not determine legal entitlement or replace professional advice. Avoid presenting an illustrative remedy as a new agency policy.

Evaluate unintended effects across different participants. A scheduling change may improve access for one group while creating a new conflict for another. That does not mean no change is possible. It means the design needs feedback, a clear purpose, and a way to revise. Document which barrier each component addresses and what evidence would indicate that it is working. In a small pilot, confidential individual feedback may reveal a problem that aggregate participation counts miss, but it must be collected through an appropriate route. Keep private course reflections separate. A strong remedy reduces the actual barrier, preserves meaningful participation, and avoids requiring people to become examples for everyone else’s learning.''','A fictional team offers an accessible recording instead of a live development session, but only live attendees can volunteer for follow-up assignments.','Make assignment information and a comparable expression-of-interest route available to all participants.','Access to information is incomplete when the opportunity attached to it remains restricted to one format.','Count access to the recording as proof that the entire opportunity is equitable.','The recording addresses one barrier but leaves the assignment pathway unequal.','Which apparently helpful alternative could become a lower-value route?','For each proposed remedy, state the barrier addressed, participant choice preserved, and remaining access gap.'),
lesson('Write a bounded case conclusion',['Write a conclusion separating findings from hypotheses.','Specify what evidence would justify revising the remedy.','Explain the limits of a fictional analysis.'],'''An advanced case conclusion should be precise enough to be questioned. Begin with the process examined and the evidence available. State the interaction you found, the alternatives you considered, and the information still missing. Avoid a dramatic conclusion that goes beyond the record, such as claiming that every member of a group experiences the same exclusion. Equally, avoid reducing a supported pattern to a personal misunderstanding simply because no single identity category explains it completely.

Use different language for different levels of certainty. An observed rule can be stated directly. A plausible explanation should be identified as a hypothesis. A proposed improvement should be described as something to test or implement within authority. For example, the requirement for after-hours attendance may be documented; its interaction with caregiving and transport may be established in the fictional case; the likely benefit of a new schedule remains a prediction until examined. This disciplined language makes a recommendation stronger because readers can see what supports it.

Name ownership and review. A combined barrier often persists because responsibility is divided among units. Assign a coordinating role without pretending that one person controls every component. Specify who can change the schedule, who controls the format, who communicates opportunities, and who checks the result. Agree on a review date and a way for participants to report an unintended problem. Do not require public disclosure of protected or personal information to demonstrate that the change helped.

The course’s fictional cases are tools for reasoning, not factual claims about DHS employees or communities. Applying the method to actual decisions requires appropriate authority, accurate records, and privacy safeguards. The developmental aim is to move beyond a one-size-fits-all explanation toward attention to how conditions interact. That is compatible with Acceptance and Adaptation in the program’s learning approach, but it does not establish an individual’s IDI orientation. End the analysis with an actionable, limited claim: which barrier will change, why that change is justified, what remains uncertain, and how the organization will know whether meaningful access improved. The result should help a person participate without asking them to simplify their life to fit the organization’s categories.''','A fictional case review identifies interacting schedule and format barriers. The draft report says the process excludes every disabled woman of color.','Limit the conclusion to the documented mechanisms and specify what broader evidence would be needed.','A bounded conclusion preserves the importance of the finding without generalizing beyond the case.','Keep the universal claim because stronger language will force action.','Overstatement undermines the evidence and turns an important case into an unsupported claim about everyone.','Where could a precise limitation make your recommendation more credible?','Write a six-part conclusion: question, evidence, interaction, remedy, uncertainty, and review responsibility.')],
[('Intersectionality','Analysis of how social arrangements and forms of power interact, not a count of identities.'),('Single-axis comparison','An analysis organized around one category that may miss a combined pattern.'),('Interaction map','A sequence connecting rules, resources, interpretations, and consequences.'),('Bounded conclusion','A finding stated at the level justified by the available evidence.')],
[('Map the case',['State the outcome and reconstruct the sequence.','List rules, available resources, and interpretations at each step.','Mark observed facts, hypotheses, and unknowns separately.']),('Test the explanation',['Ask what would disconfirm the proposed interaction.','Choose a relevant comparison and explain its limitations.','Use authorized data and protect small groups from identification.']),('Design the remedy',['Address each component of the combined barrier.','Check whether an alternative offers meaningful opportunity.','Preserve choice and avoid unnecessary identity disclosure.','Name coordination, decision authority, and the review date.'])],
[('Crenshaw (1989), Demarginalizing the Intersection of Race and Sex','https://chicagounbound.uchicago.edu/uclf/vol1989/iss1/8/','Foundational primary legal scholarship on the limits of separate race and sex categories. Cases here are original learning examples, not legal determinations.'),('Crenshaw (1991), Mapping the Margins','https://evallab.unm.edu/restricted-materials/crenshaw-1991---intersectionality.pdf','University-hosted original article on structural and political intersectionality. Its specific context should not be flattened into a universal identity checklist.')])

publish(4,'epistemic-injustice','Epistemic Injustice: Whose Knowledge Counts?','Examine credibility, silence, and the categories used to understand experience, then build a fairer route from knowledge to decisions.',[
lesson('Recognize an unfair credibility discount',['Distinguish an evidence-based credibility question from an identity-based discount.','Identify how status affects whose account is heard.','Propose a fair method for checking a claim.'],'''Epistemic means related to knowledge. Epistemic injustice concerns wrongs people experience in their capacity to contribute knowledge. Miranda Fricker distinguishes testimonial injustice, in which prejudice unfairly lowers a speaker’s credibility, from hermeneutical injustice, in which unequal participation in shared understanding leaves some experiences difficult to explain. These concepts help examine how an organization hears and interprets information. They do not mean that every account must be accepted without questions or that expertise is irrelevant.

A credibility question is appropriate when it concerns the evidence: what the person observed, how they know it, what records support it, and which alternative explanations remain. An unfair discount occurs when a person’s identity or social position substitutes for that inquiry. A resident’s description of an inaccessible process might be dismissed as confusion while the same description from a consultant is treated as a finding. The relevant comparison is how the claim is tested, not whether both speakers have identical credentials.

Status can influence credibility without anyone announcing a rule. A confident tone, professional title, familiar vocabulary, or senior sponsor may make an account easier to hear. People with direct experience may use less familiar language or describe a pattern that the available categories do not capture. Their account can be valuable without being complete. The appropriate response is to ask clarifying questions and examine the process, not to demand that the person translate everything into the institution’s preferred style before the issue deserves attention.

Build a fair route for checking claims. Record the substantive concern separately from impressions of the speaker. Identify what evidence would support or challenge it. Ask whether a similarly specific account from a more powerful person would receive faster investigation. Do not infer that a colleague deliberately silenced someone merely because the first response was poor. Focus on the remedy: a consistent standard for taking information seriously and a way to correct an error. This approach preserves rigorous evaluation while resisting the tendency to confuse social confidence with knowledge. It also makes room for disagreement about facts without turning the speaker’s identity into the subject of judgment.''','A fictional resident reports that a notice is confusing. The team dismisses the account until a consultant repeats the same concern.','Compare how the two accounts were handled and investigate the notice using the same evidence standard.','The concern deserves a consistent inquiry regardless of the speaker’s status.','Accept every account as correct because questioning it would be unjust.','Fair listening includes evidence-based questions; injustice concerns the unfair standard, not the existence of scrutiny.','Whose confidence or title makes you less likely to ask for evidence?','Write the concern without a status label and specify how you would test it.'),
lesson('When the available categories cannot describe the experience',['Explain how a reporting category can hide a problem.','Distinguish silence from agreement.','Propose an additional route for describing an experience.'],'''An organization understands the world partly through categories: complaint type, service need, incident reason, eligibility condition, or performance measure. Categories make information manageable, but they also shape what becomes visible. A person may have a well-founded concern that does not fit the available form. If every report must be classified as either a technical problem or a conduct problem, an experience involving both may be repeatedly misrouted. The absence of a category can become the absence of an organizational response.

Fricker’s account of hermeneutical injustice directs attention to unequal participation in creating shared interpretive resources. Kristie Dotson’s work examines practices of silencing, including conditions under which speakers limit what they say because an audience is unlikely to understand it safely. These frameworks do not establish the reason for any particular silence. A person may be quiet because they agree, disagree, are tired, need time, or judge the setting unsuitable. The lesson is to avoid treating silence as reliable evidence of consent.

Examine the reporting route before asking for more disclosure. What categories are offered? Is there an understandable way to say that none fits? Can someone explain a sequence in their own words? Who reads that explanation, and what happens next? An open text box is not enough if nobody reviews it or if the person must repeatedly retell the account. A useful route gives the information an accountable destination and explains how it can affect a decision.

Invite people affected by the categories to help evaluate them without making participation compulsory. Use fictional examples to test whether the categories can distinguish important mechanisms. Preserve technical or legal definitions that serve a valid purpose, while adding a route for information they do not capture. Do not invent a new category and assume the problem is solved. Check whether staff understand it, whether it leads to an appropriate response, and whether it creates new risks of labeling people. Shared understanding improves when the organization can revise its own vocabulary in response to experience, rather than requiring every experience to fit the vocabulary already available.''','A fictional form offers only staff error or customer error. Reports of confusing instructions are repeatedly returned as incomplete.','Add an accountable route for describing process design problems and review how those reports are handled.','The change gives the uncaptured mechanism a destination rather than blaming the person for not fitting the categories.','Treat the lack of completed forms as proof that no problem exists.','A reporting structure can prevent concerns from appearing in the record; absence of reports is not proof of absence.','Which category in your work might erase a sequence that does not fit neatly?','Test a reporting form with a fictional mixed-cause case and document what information disappears.'),
lesson('Design participation that changes the knowledge base',['Distinguish consultation from decision authority.','Identify a credibility barrier in an engagement plan.','Draft a feedback loop that shows how input affected the work.'],'''An invitation to speak does not by itself establish that knowledge will matter. Participants may attend a meeting, share detailed experience, and discover later that the decision was already fixed. That can convert engagement into extraction: the organization receives stories while retaining all control over their meaning and use. A fairer arrangement explains which questions are open, who decides, what evidence will be considered, and how participants can see what happened to their contribution.

Different kinds of knowledge answer different questions. A service user can explain what a process required in practice. An analyst can estimate patterns in authorized data. A specialist can interpret a technical requirement. A decision maker can explain constraints and authority. None of these roles makes every claim equally reliable, and no single role supplies the whole picture. The aim is to combine relevant knowledge while making disagreements and limitations visible, rather than ranking people once and allowing that rank to determine every conclusion.

Prepare a participation plan around an actual decision. Provide accessible background information and enough time to consider it. Offer ways to contribute that do not require public personal disclosure. Explain how notes will be used and what confidentiality can and cannot be promised. Where participation requires substantial work, consider appropriate compensation within authorization. Do not ask one person to represent an entire community or treat personal experience as a performance that must be emotionally compelling to count.

Close the loop through a response record. Summarize the issue raised, the evidence considered, the change made or declined, and the reason. Invite correction if the summary misrepresents what was said. If a suggestion cannot be adopted because of a verified requirement, explain that constraint specifically rather than invoking policy as a vague ending. This record does not require agreement with every recommendation. It demonstrates that the contribution entered the reasoning. Over time, review whose input regularly receives action and whose is repeatedly deferred. The objective is not merely more participation, but a more accountable relationship between what people know and what the organization decides.''','A fictional advisory group is asked for input after a form has been finalized. Its comments are thanked but never answered.','State what remains changeable and publish a response to each substantive issue, including reasons for deferral.','A visible response connects participation to decisions without falsely promising shared authority.','Describe the meeting as co-design because several participants attended.','Attendance does not establish that participants influenced the design or held decision authority.','When have you mistaken the opportunity to speak for the power to affect a decision?','Draft a response record with issue, evidence, decision, reason, and correction route.'),
lesson('Repair a knowledge failure without claiming perfect understanding',['Identify a repair for a dismissed account.','Describe what remains uncertain after an inquiry.','Choose an organizational measure of improved listening.'],'''Repair begins by acknowledging the specific knowledge failure. If a concern was dismissed because the speaker lacked status, explain that the account should have received a fair inquiry. If the available categories obscured the issue, revise the route and reconsider affected decisions where appropriate. Avoid a general statement about listening better when the problem involved a concrete lost opportunity. Also avoid claiming complete understanding after one conversation. Acknowledgment and inquiry can proceed together without requiring the person to prove their experience repeatedly.

Ask what repair is possible within your authority. It may involve correcting a record, reopening a review, changing a form, or providing a clearer explanation. A person should not have to accept an apology or join a group discussion to access that repair. Where the matter concerns discrimination, retaliation, privacy, or other formal responsibilities, preserve the appropriate process. Epistemic analysis can illuminate how information was mishandled, but it does not replace investigation or create authority to decide a complaint.

Measure the organizational route rather than the speaker’s willingness to trust again. Track whether concerns reach the right reviewer, whether the response addresses the substance, and whether an understandable reason is provided. Use authorized records and avoid gathering sensitive learning disclosures. A higher number of reports after a change may reflect improved access to reporting rather than more underlying problems. A lower number may reflect improvement, fatigue, or loss of trust. Interpret counts alongside the actual process and feedback rather than treating a trend as self-explanatory.

The program’s developmental framework supports moving from a universal assumption about how everyone experiences the organization toward attention to meaningful differences and responsive practice. That does not authorize an IDI label for an individual or require someone to share personal history. A defensible conclusion states what the inquiry established, what the organization changed, and what remains unknown. Repair is more credible when it includes a review date and an accessible correction route. The goal is a system in which relevant knowledge can challenge a decision before harm becomes entrenched, and in which people can see that the organization is capable of learning from accounts it once failed to hear.''','A fictional team discovers that a resident’s accurate concern was dismissed. It asks the resident to attend a public meeting before correcting the record.','Correct the record through the appropriate route and offer, rather than require, further participation.','Repair should not depend on performing the experience for an audience or accepting an apology.','Require a public account so the team can learn a stronger lesson.','The organization’s learning needs do not justify making repair conditional on personal disclosure.','What would repair look like if the person did not want another conversation?','Write a repair plan naming the error, available correction, formal boundaries, owner, and review date.')],
[('Testimonial injustice','An unfair credibility discount connected to prejudice about the speaker.'),('Hermeneutical injustice','An unfair gap in shared understanding connected to unequal participation in making meaning.'),('Silence','Ambiguous information; it does not reliably establish agreement or absence of harm.'),('Response record','A visible account of how a contribution entered a decision and why an action was taken or declined.')],
[('Hear the claim',['Separate the concern from impressions of the speaker.','Ask what evidence would support or challenge it.','Compare how a similar account from a higher-status person would be handled.']),('Examine the route',['Check whether categories capture the mechanism.','Provide a route for a concern that fits no category.','Explain who receives information and what happens next.']),('Return a response',['State the issue, evidence, decision, and reason.','Invite correction of an inaccurate summary.','Repair records or processes without requiring public disclosure.','Review response quality and access, not private attitudes or trust scores.'])],
[('Fricker (2007), Epistemic Injustice: Power and the Ethics of Knowing','https://academic.oup.com/book/32817','Primary philosophical framework. The distinction between testimonial and hermeneutical injustice informs the original workplace examples.'),('Dotson (2011), Tracking Epistemic Violence, Tracking Practices of Silencing','https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1527-2001.2011.01177.x','Primary philosophical analysis of silencing. Silence in a particular workplace cannot be diagnosed from this framework alone.')])

