exec((__import__('pathlib').Path(__file__).parent/'write-packs.py').read_text(encoding='utf-8-sig'))
publish(1,'aversive-racism','Aversive Racism and Discrimination Under Ambiguity','Examine how unequal judgments can persist alongside sincere commitments to fairness, and practice reducing the ambiguity that permits them.',[
lesson('When values and decisions diverge',['Distinguish an aversive-racism hypothesis from a judgment about a colleague.','Identify an ambiguous criterion in a fictional decision.','Separate evidence of unequal treatment from an inference about intent.'],'''A person can sincerely endorse racial equality and still participate in a decision that disadvantages someone because of race. The aversive-racism framework investigates that tension. Its practical value is not a new label for colleagues. It directs attention toward decisions where the rules permit several plausible explanations. An evaluator may describe one applicant as promising and another as unproven despite comparable evidence. Neither description is necessarily wrong in isolation. The important question is whether the standard changes with the person being evaluated.

Dovidio and Gaertner examined simulated selection decisions in their 2000 study. Their work supports examining ambiguity rather than relying only on expressed attitudes. It does not establish that every discretionary decision is racially biased or that an individual can be classified from one encounter. A useful workplace inquiry therefore starts with the decision record: what was known, what counted, what was missing, and when the criteria were chosen. Statements of good intention belong in the conversation, but they cannot substitute for those questions.

Consider the difference between uncertainty and discretion. Uncertainty means the evidence is incomplete. Discretion means someone has authority to interpret evidence or choose among permissible options. Neither can be eliminated entirely in human services. The risk increases when uncertainty is resolved differently for different people and the difference is invisible to review. A familiar applicant receives another interview to clarify a weak example; an unfamiliar applicant is rejected for the same weakness. The extra opportunity, rather than the final score alone, becomes the relevant comparison.

Your task is to make that comparison possible without pretending to read minds. Write the criterion in behavior-based terms. Identify whose evidence was clarified and whose was not. Ask what would happen if the identities were changed while the evidence remained constant. This counterfactual is a reasoning exercise, not proof of discrimination. It can reveal where further examination is needed. Preserve legitimate contextual differences, including disability-related access needs, instead of insisting that fairness always means identical treatment. A stronger conclusion identifies a specific inconsistent practice and a defensible correction, while acknowledging what the available record cannot tell you.''','Two fictional candidates have similarly incomplete work samples. A panel calls one a growth opportunity and the other a risk. No clarification rule was established.','Compare the evidence and offer an equivalent clarification process where the selection rules permit it.','An equivalent opportunity addresses the observable inconsistency without claiming to know anyone’s motives.','Ask panelists whether they believe in equality and accept their reassurance.','A statement of values does not establish how missing evidence was handled for each candidate.','When have you treated familiarity as evidence of ability? Use a fictional example if preferred.','Rewrite one ambiguous criterion as observable evidence and specify how missing information will be handled.'),
lesson('Ambiguity in ordinary service decisions',['Map three points where discretion enters a service decision.','Compare alternative explanations for an uneven pattern.','Propose a consistent method for documenting exceptions.'],'''Ambiguity often enters public service through ordinary words: reasonable, cooperative, ready, difficult, appropriate, or professional. These words can summarize meaningful evidence, but they can also conceal its absence. A reviewer who writes that a caller was uncooperative may mean that a required document was not supplied. Another reviewer may mean that the caller questioned the process. Those are different events with different implications. Replacing the label with the observable event creates an opportunity to respond proportionately rather than to a reputation.

Map a decision from intake to resolution. At each step, ask who can extend a deadline, seek clarification, accept alternative documentation, or refer a case for specialist review. Then ask how a person learns those options exist. An exception available only to confident callers is not equally available in practice. This course does not create authority to waive a requirement. It asks you to examine how existing authority is exercised and whether the published route matches the route people actually experience.

An uneven pattern is a reason to investigate, not a complete explanation. Differences may involve case complexity, communication access, timing, missing information, or unequal assumptions. Examine comparable cases and keep those alternatives visible. Avoid comparing broad group averages while ignoring important process differences. Also avoid using the existence of any possible alternative as a reason to stop examining the pattern. A careful review asks which explanation fits the documented sequence and what additional information would distinguish competing accounts.

Documentation should make reasoning reviewable without adding unnecessary sensitive details. Record the requirement, the relevant evidence, the permitted exception, and the reason it applied. Use the same fields across cases. Do not record speculative racial attitudes, inferred IDI orientations, or a staff member’s private learning response. If a concern involves discrimination or retaliation, preserve the appropriate formal route rather than converting the issue into an informal learning exercise. For everyday process improvement, examine whether comparable situations receive comparable opportunities to be understood. That question makes fairness concrete while leaving room for legitimate differences in need, evidence, and authorized service response.''','A fictional team grants deadline extensions after telephone requests but rarely after written requests. Some callers receive suggestions about documents the written notice never mentions.','Map the extension route and revise the notice and review process so the same authorized options are visible.','The response examines access to discretion and makes the available options more consistent.','Conclude that the disparity proves every telephone reviewer is biased.','The pattern needs explanation; attributing a motive to all reviewers exceeds the evidence and does not repair the route.','Which reassuring label in your work would be more useful as a description of observable events?','Create a four-field exception record: requirement, evidence, authorized option, and reason.'),
lesson('Design a decision that can be checked',['Draft criteria before reviewing a fictional case.','Distinguish useful structure from a rigid rule that blocks access.','Identify a review trigger for inconsistent judgments.'],'''A structured decision process is useful when it makes relevant reasoning visible. Structure is less useful when it simply turns the same vague assumptions into boxes on a form. Requiring a numerical score for professionalism does not resolve what professionalism means. A stronger criterion identifies the behavior needed for the work, the evidence that could demonstrate it, and the range of acceptable ways a person might show that evidence. Clear written communication, for example, should not quietly become a preference for a familiar accent during an oral interview.

Choose criteria before looking at the people or cases being evaluated whenever practical. Otherwise, an appealing candidate or a difficult encounter can reshape what seems important. Specify the weight of each criterion and the method for handling missing information. If an exception is necessary, document it openly and consider whether comparable cases should receive the same opportunity. A process that can never admit new information may be consistent yet still unfair; consistency needs to serve the underlying purpose rather than replace it.

Independent initial judgments can help a group see where interpretations differ before a confident speaker establishes the answer. Ask reviewers to record evidence and uncertainty, then discuss the largest disagreements. Do not assume that averaging scores corrects bias. An average can conceal a systematic problem shared by every reviewer. Examine whether the disagreement concerns evidence, the meaning of a criterion, or an unsupported impression. Resolve those differences with reference to the work rather than seniority or persuasive style.

Build a review trigger into the process. A trigger might be repeated use of an undefined term, unequal opportunities to clarify, or a large difference between initial and final judgments without new evidence. The trigger invites examination; it is not a declaration of wrongdoing. Decide who can review a concern independently and how the people affected can challenge an error. Preserve authorized accommodation and complaint processes. Structure succeeds when it improves the quality and accessibility of the decision and gives people a usable way to question it. It is not a guarantee that bias has disappeared, and it cannot replace thoughtful attention to context.''','A fictional panel adds executive presence after meeting a favored applicant. Two members want to average their scores and proceed.','Return to the preselected job-related criteria and document any justified change before applying it consistently.','The response prevents a preference formed around one person from becoming an unexplained standard for everyone.','Average the scores because numerical results are automatically objective.','Numbers can preserve subjective assumptions; the evidence and meaning behind the scores still need examination.','Where might a form create the appearance of fairness without improving reasoning?','Draft a review trigger for an unexplained change in criteria and identify who can review it.'),
lesson('Check whether the repair changed the pattern',['Select a process measure and an outcome measure.','Explain why a small before-and-after comparison cannot establish causation.','Write a review statement that includes uncertainty.'],'''A revised form is an implementation result. It is not yet evidence that decisions became fairer. After introducing a clarification rule, check whether people actually received clarification, whether the information helped decisions, and whether disparities changed. These are distinct questions. A process can be followed faithfully and still fail to address the original barrier. It can also improve an experience before a small sample provides a stable estimate of changes in final outcomes.

Select measures that correspond to the proposed mechanism. If the problem was unequal access to clarification, examine the proportion of comparable cases offered clarification and the time allowed to respond. If the concern was shifting criteria, examine how often criteria change and whether the reason is documented. An outcome measure might examine selection or completion patterns where collection and analysis are authorized. Do not collect personal identity information simply because it would make a chart more interesting. Use approved data, appropriate privacy protections, and specialist assistance when small groups could be identifiable.

Interpret results with the design in mind. A before-and-after improvement could reflect the revised process, a different mix of cases, staffing changes, or chance. A small pilot may reveal feasibility and obvious harms more readily than a reliable effect size. Record those limitations before celebrating success. Equally, a lack of measurable change does not establish that the underlying concern was imaginary. The intervention may have been weak, inconsistently used, aimed at the wrong step, or evaluated over too short a period.

Close the loop with the people responsible for the process. Report what changed, what was observed, what remains uncertain, and what happens next. Include a route for affected people to describe problems that the chosen measures miss. In the program’s developmental language, movement from Minimization toward Acceptance and Adaptation involves noticing meaningful differences and changing practice in response. It does not require labeling individual staff. A defensible review concludes with a decision to continue, revise, stop, or investigate further, along with an owner and a date. That makes accountability practical without overstating what a training course or a single pilot can prove.''','A fictional team offered all candidates clarification this month. Selection differences narrowed, but only twelve applications were reviewed and job requirements changed.','Report improved consistency in clarification and treat the outcome difference as preliminary.','The record supports a process improvement while the small, changing sample limits causal claims.','Announce that the training eliminated racial bias.','Neither twelve cases nor a narrower difference establishes elimination of bias or isolates the effect of training.','What evidence would make you revise your preferred explanation of a decision pattern?','Write a review note with process adherence, outcomes, alternative explanations, next decision, owner, and date.')],
[('Aversive-racism framework','A framework for examining how egalitarian commitments can coexist with subtle racial discrimination; not a diagnosis of a colleague.'),('Ambiguity','Room for multiple interpretations that may permit standards to shift.'),('Counterfactual comparison','Ask whether the same evidence would receive the same interpretation if identities changed; a prompt for inquiry, not proof.'),('Process evidence','Records of how a decision was reached, including clarification and exceptions.')],
[('Before the decision',['Name the decision and the authority responsible for it.','Write the relevant criteria and acceptable evidence before examining identities.','Specify clarification, accommodation, and exception routes.']),('During review',['Record evidence separately from impressions.','Compare opportunities to provide missing information.','Mark changes in criteria and require a documented reason.','Escalate concerns through the appropriate formal route when needed.']),('After the decision',['Check process adherence and outcomes separately.','List alternative explanations and data limitations.','Assign an owner and date to continue, revise, or stop the change.'])],
[('Dovidio and Gaertner (2000), Aversive racism and selection decisions','https://pubmed.ncbi.nlm.nih.gov/11273391/','Experimental selection research supports examining ambiguous decisions; simulated decisions do not diagnose individual staff.'),('Dovidio, Kawakami, and Gaertner (2002), Implicit and explicit prejudice and interracial interaction','https://pubmed.ncbi.nlm.nih.gov/11811635/','Primary interaction study. Measures and impressions are context-dependent; workplace exercises here are program-authored applications.')])

publish(2,'whiteness-institutional-norm','Whiteness as an Institutional Norm: A Critical Examination','Investigate how historically dominant expectations become ordinary organizational standards, without treating racial identity as an explanation of anyone’s character.',[
lesson('Distinguish identity, norm, and institutional advantage',['Distinguish a person’s racial identity from an institutional norm.','Explain how a default can confer an advantage without an explicit exclusion rule.','Identify evidence needed to examine one organizational expectation.'],'''Whiteness in this course names an institutional relationship, not a biological characteristic or a claim that all White people think alike. The question is how expectations associated with historically dominant White groups can become the unmarked standard for credibility, belonging, and competence. An expectation may feel like common sense to people who learned it early and like an additional translation task to others. Examining that difference does not require denying individual effort, hardship, or variation among White people.

Cheryl Harris’s legal scholarship analyzes whiteness as a protected source of value within American racial history. Victor Ray’s organizational theory examines how racial arrangements can shape agency, resources, credentials, and the gap between formal rules and practice. These are analytical frameworks, not instructions to classify every workplace habit as racist. Their usefulness depends on connecting a claim to a particular history, rule, allocation, or decision. Naming an institution as racialized should begin an inquiry rather than replace evidence with a conclusion.

Consider a workplace that treats familiarity with a particular professional network as proof that a person understands the organization. The network may provide real knowledge. The analytical question is whether the knowledge can be learned or demonstrated through other routes, and whether those routes receive equal recognition. A standard can preserve an inherited advantage when it rewards access to relationships that were unevenly available in the first place. The effect does not depend on every person benefiting from it intending exclusion.

Keep three levels separate when examining a case. Identity concerns how people are socially positioned and identify themselves. A norm concerns an expected way of speaking, behaving, or demonstrating competence. Institutional advantage concerns how that expectation affects access to resources or authority. Evidence at one level does not automatically prove a claim at another. A thoughtful discussion can name racial history and unequal effects while remaining precise about what a particular record shows. It can also invite disagreement about an explanation without requiring colleagues to disclose private experiences or defend their racial identity. The practical goal is a standard that serves the work and can be examined by the people subject to it.''','A fictional workgroup says that knowing established leaders is the best evidence of readiness for a cross-division assignment.','Ask what knowledge the relationships demonstrate and identify other ways to demonstrate it.','The inquiry tests the institutional standard without assuming that everyone in a network has identical motives or experience.','Treat every White employee’s experience as identical.','A structural analysis does not erase differences among individuals or make identity a substitute for evidence.','Which expectation felt obvious to you because someone taught it to you informally?','Separate identity, norm, and resource consequence in one fictional example.'),
lesson('Trace how a default became authoritative',['Construct a short history of a workplace standard.','Distinguish a functional requirement from a inherited preference.','Identify whose knowledge is absent from the standard’s design.'],'''An institutional norm usually has a history, even when nobody currently remembers choosing it. A presentation format may have originated with a particular leader. A meeting time may reflect the schedules of the people who previously held authority. A preferred style of confidence may have developed in a professional setting that excluded many people. History does not automatically invalidate a practice, but it helps distinguish a current functional need from a convention that survives because it is familiar.

Trace the standard through documents and decisions rather than through stereotypes about cultural groups. Ask when it appeared, what problem it was meant to solve, who could participate in creating it, and how exceptions have been handled. If the origin is unknown, record that uncertainty. Do not invent a racial history because a contemporary pattern seems suggestive. You can still evaluate whether the current standard is relevant, transparent, accessible, and applied consistently. Historical explanation and present-day justification are related but separate tasks.

Take a fictional requirement for a polished verbal briefing before a staff member can lead a project. Some verbal communication may be essential. But the requirement may combine several distinct abilities: organizing evidence, answering questions, speaking without notes, using a particular accent, and displaying confidence before senior leaders. Unbundle those elements. Determine which ones the project actually needs and which ones are preferred because they resemble prior leaders. Offer legitimate alternatives for demonstrating the required ability, including accessible formats, rather than lowering an essential standard or assuming one group needs help.

Invite people affected by the standard to examine a draft, while recognizing that an invitation alone does not redistribute authority. Say what can change and who decides. Avoid making one colleague represent a racial group or treating an objection as proof of deficient cultural competence. A review is stronger when it includes contrasting experiences and a clear account of why each proposed requirement remains. Document the functional justification in language a newcomer could understand. That record makes the norm open to later revision instead of allowing familiarity to become its only defense. The result should be greater clarity about the work, not a new unwritten test of ideological agreement.''','A fictional project role requires an unscripted executive briefing, although the work mainly involves careful written analysis and follow-through.','Break the requirement into actual job tasks and accept appropriate evidence for each.','Unbundling reveals which skills are essential and which preferences may unnecessarily narrow access.','Remove every communication requirement because standards are inherently exclusionary.','Communication can be essential; the task is to justify and broaden valid demonstrations rather than abandon the work’s needs.','What would a newcomer need explained about a standard you now take for granted?','Write a brief standard history with known origin, current purpose, missing perspectives, and justified alternatives.'),
lesson('Examine credibility and the benefit of the doubt',['Compare how similar mistakes are interpreted.','Locate the resource consequence of unequal credibility.','Draft a response that changes a practice rather than assigning collective blame.'],'''Credibility is a resource. Being presumed competent can bring additional explanation, another chance, an introduction, or protection from a premature judgment. When similar conduct receives different interpretations, the distribution of that resource deserves examination. One employee’s mistake may be described as a learning experience while another’s becomes evidence that they do not belong. The relevant question is not whether mistakes should have consequences. It is whether the evidence and the opportunity to recover are comparable.

An institutional analysis examines repeated patterns and the rules that allow them. A single difference can have many explanations. Look for comparable responsibilities, available support, the seriousness of the event, and the actual decision sequence. Do not treat a racial difference in outcomes as proof of an individual’s intention. Conversely, do not require an admission of racial intent before considering whether a practice confers unequal advantage. These two errors can occur together: overconfident judgments about people and underdeveloped scrutiny of the organization.

Consider sponsorship. A senior colleague may advocate strongly for someone whose style feels familiar. That advocacy can turn ambiguous evidence into a favorable interpretation. Staff outside that relationship may have to supply more proof for the same opportunity. The improvement is not to prohibit supportive relationships. It is to make opportunities visible, define relevant evidence, and examine how advocacy influences decisions. Where developmental assignments matter, provide a transparent route for expressing interest and a reviewable account of selection rather than relying only on private nomination.

Discuss the practice with language that permits accountability and learning. Describe the specific comparison, explain the consequence, and ask how the standard can be made explicit. Do not ask White staff to confess privilege as the price of participation or ask staff of color to provide painful examples for the group’s education. People can examine a fictional case and still contribute rigorous reasoning. The program’s movement toward Acceptance and Adaptation is supported when differences in experience become information for redesign, not labels attached to individuals. A useful response changes who can access an opportunity and how a decision is explained, while preserving the ability to challenge inaccurate assumptions.''','In a fictional team, two missed deadlines have similar causes. One employee receives coaching and a new assignment; another is removed from consideration with no discussion.','Compare the circumstances and apply a transparent recovery and development process.','The response examines unequal interpretation and opportunity without presuming a motive from identity.','Require staff of color to share personal stories until everyone agrees there is a problem.','Compelled disclosure shifts the burden to affected staff and is not needed to examine the documented decision.','When do you grant the benefit of the doubt, and what evidence supports that choice?','Draft a consistent process for reviewing mistakes and restoring eligibility for an opportunity.'),
lesson('Replace an unexamined norm without creating another',['Design a transparent alternative to a disputed norm.','Specify an access measure and a quality measure.','Explain how to preserve disagreement and review.'],'''Changing an institutional norm requires more than replacing its vocabulary. A team may stop saying culture fit and begin saying alignment while evaluating the same unexplained preferences. Another team may publish inclusive language but continue making important selections through private conversations. The test is whether the route to participation and the reasons for decisions have changed. Look at the actual distribution of information, time, support, and authority rather than the presence of new words alone.

Start with a narrow standard you have authority to revise. Define the work-related purpose, acceptable evidence, and available access supports. Invite review from people with different experiences of the process, including people who previously could not participate. Make the invitation concrete: which part of the draft is open, when feedback will be considered, and how the final decision will be explained. Compensate participation where appropriate and authorized. Do not promise shared decision authority if the final authority remains elsewhere.

Evaluate both access and work quality. If a developmental assignment is opened through a published expression-of-interest process, examine who heard about it, who could apply, and whether participants had the support needed to succeed. Also examine whether the revised process selects relevant capability and delivers the intended work. A wider applicant pool alone does not demonstrate a fair process, and a successful project alone does not establish equitable access. These measures answer different questions and should remain visible together.

Leave room for revision and disagreement. Someone may question whether the new criterion measures the intended skill or whether the review process creates another burden. Treat that criticism as information to examine rather than a sign that the person lacks commitment to equity. A durable standard has reasons that can be stated, evidence that can be reviewed, and an accessible way to contest an error. Document what the organization learned about the old norm without turning colleagues’ racial identities or private reflections into personnel data. The final product is not a declaration that the institution is now free of racialized patterns. It is a more defensible practice, a record of its effects, and a commitment to review it when circumstances or evidence change.''','A fictional team renames culture fit as alignment but keeps private nominations and no written criteria.','Publish the opportunity, define the relevant evidence, and review who gains access under the revised process.','The change addresses the allocation mechanism rather than relying on different vocabulary.','Celebrate the new label as evidence that the institutional problem is solved.','Renaming does not show that opportunities or decision standards have changed.','What feature would make a new standard open to challenge by someone with less authority?','Complete a norm-revision record: purpose, criteria, access routes, decision authority, measures, and review date.')],
[('Institutional norm','An expectation that becomes routine and authoritative within an organization.'),('Unmarked default','A convention presented as simply normal, even though it reflects a particular history and social position.'),('Credibility advantage','Receiving trust, explanation, or another opportunity more readily than others in comparable circumstances.'),('Structural analysis','Examination of rules, resources, and repeated patterns; it does not determine an individual’s character from identity.')],
[('Trace the norm',['Name the exact expectation, not a broad cultural stereotype.','Record its known history and mark unknowns.','Identify the work-related purpose and who could help define it.']),('Test its consequences',['Separate essential capability from preferred style.','Compare access to information, sponsorship, clarification, and recovery after mistakes.','Identify which authority can revise the standard.']),('Create a reviewable alternative',['Publish acceptable evidence and access supports.','Record who decides and how feedback will affect the decision.','Check both access and work quality.','Set a review date and a route to challenge an error.'])],
[('Harris (1993), Whiteness as Property','https://harvardlawreview.org/print/no-volume/whiteness-as-property/','Foundational legal analysis of racialized value and institutional protection; not a statement of current workplace legal obligations.'),('Ray (2019), A Theory of Racialized Organizations','https://journals.sagepub.com/doi/10.1177/0003122418822335','Organizational theory supports examining resources, agency, credentials, and formal-practice gaps. Local applications require local evidence.')])
