// Each conceptual check is distinct from the lesson's applied scenario.
// Tuple: question, correct response, two alternatives, explanatory feedback.
export const conceptualChecks: [string,string,string,string,string][][] = [
 [
 ['Can hardship and racial advantage coexist in one life?','Yes; they describe different conditions and neither supplies the whole account.','No; hardship cancels every form of advantage.','No; advantage means a person has never worked hard.','A person can face serious hardship while encountering fewer barriers related to race. Neither fact erases the other, and neither describes the entire person.'],
 ['What does an opportunity roster establish by itself?','Who participated; the pathway and causes still require examination.','The private intentions of every organizer.','That everyone had an equal chance to learn about it.','A roster can prompt inquiry, but it does not show how information circulated, what criteria were used, or what anyone privately intended.'],
 ['Why offer a fictional example in a privilege discussion?','It allows substantive inquiry without making personal disclosure a condition of learning.','It proves actual experiences are irrelevant.','It allows the facilitator to avoid every difficult question.','A fictional case supports careful practice while participants retain the choice to share or not share personal experience. It complements, rather than invalidates, lived knowledge.'],
 ['Which distinction matters when evaluating an access change?','Completing an activity is different from showing that people could use the opportunity.','Good intentions are identical to improved access.','A public announcement automatically repairs every selection decision.','An announcement is an output. Its usefulness, reach, and connection to a fair decision require follow-up evidence.'],
 ],
 [
 ['What distinguishes a microaggression from any ordinary discourtesy?','A possible identity-based message in its context.','The speaker must admit an intention to harm.','The recipient must react visibly.','The identity-related message and context are central. Neither an admission of harmful intent nor a visible reaction is necessary to examine the interaction.'],
 ['How should intent and impact be related?','Examine both without treating either as complete proof of the other.','Good intention makes an adverse effect impossible.','An adverse effect reveals every private motive.','A stated intention and a reported effect answer different questions. Careful repair can address an effect without claiming complete knowledge of motive.'],
 ['What should shape a bystander response?','The behavior, role, situation, and affected person’s agency.','A rule that every incident requires public confrontation.','A rule that humor makes intervention unnecessary.','Responses should be proportionate and preserve choice. Direct interruption, private discussion, support, or a formal channel may fit different situations.'],
 ['Is forgiveness required for repair to proceed?','No; a person can correct their behavior without requiring forgiveness.','Yes; the affected person must confirm the apology worked.','Yes; otherwise no practical change matters.','Repair includes correcting consequences and changing conduct. The affected person retains the choice about response, forgiveness, and further conversation.'],
 ],
 [
 ['Which statement is an observation rather than an interpretation?','There was a pause before the answer.','The person was hiding something.','The person did not respect the question.','A pause can be observed. Its meaning requires context; avoidance and disrespect are interpretations, not facts established by the pause alone.'],
 ['Why explain the purpose of a request?','It reduces reliance on background knowledge the recipient may not share.','It guarantees the recipient will agree.','It removes every need for questions.','Purpose and context help a person interpret the task, but they do not guarantee agreement or eliminate clarification.'],
 ['What is the purpose of summarizing and inviting correction?','To make your interpretation visible and test it with the speaker.','To demonstrate that your interpretation is authoritative.','To require the speaker to repeat your wording.','A summary should open the interpretation to correction. It checks shared meaning rather than testing whether the other person will accept your version.'],
 ['What separates adaptation from stereotyping?','An adjustment responds to specific information and feedback.','An adjustment follows a fixed rule for everyone in a group.','An adjustment requires imitating another person’s identity.','Adaptation expands communication choices in response to the actual exchange. It does not require imitation or a universal group prescription.'],
 ],
 [
 ['Can the same value lead to different preferences?','Yes; people may protect the same value through different methods.','No; a shared value always produces identical action.','No; different methods prove one person lacks values.','People can share a concern such as respect while interpreting what it requires differently. Explore the purpose and consequences of each method.'],
 ['How should a broad cultural pattern be used?','As a possible question to explore, not a prediction about an individual.','As a rule that overrides the person’s explanation.','As proof of which member of a group is authentic.','Patterns can broaden inquiry, but individual context, variation, and self-definition remain necessary. They do not authorize judgments of cultural authenticity.'],
 ['What establishes that a practice is required?','A verified source and applicable responsibility, not familiarity alone.','The fact that it has always been done.','The fact that the organizer strongly prefers it.','A custom may be useful, but a claimed requirement should be verified. Distinguish the actual purpose and boundary from a negotiable method.'],
 ['What does a workable compromise demonstrate?','Agreement on a particular approach, not necessarily identical values.','That all differences have disappeared.','That the decision should never be revisited.','A compromise can support a task while differences remain. Its effects should still be reviewed and omissions can justify revision.'],
 ],
 [
 ['Which three things should remain distinct when discussing bias?','Associations, endorsed beliefs, and observable behavior.','Identity, moral worth, and a single test score as one measure.','Speed, confidence, and accuracy as the same quality.','An automatic association is not identical to a consciously endorsed belief or an observed action. Decision evidence must still be examined.'],
 ['What does a single IAT result certify?','It does not certify a permanent trait or a particular future action.','A permanent diagnosis of prejudice.','That every future choice will match the result.','Project Implicit describes important limits on individual interpretation. The result can invite reflection, but it is not a diagnosis or a dependable forecast of one action.'],
 ['Which condition makes an IAT activity genuinely optional?','An equally useful non-test route with no required result or explanation.','A required screenshot without a grade.','A public explanation from anyone who declines.','A usable alternative and freedom from disclosure support real choice. A score request or required justification can create pressure even without a formal grade.'],
 ['What best demonstrates a changed decision practice?','Observable use of relevant criteria and review of the resulting decision.','A more reassuring test score alone.','A declaration that training eliminated all bias.','Behavior and process need their own evidence. A test result or completion statement cannot substitute for examining how a decision was made.'],
 ],
 [
 ['Why is a social identity more than a category label?','Its meaning includes the person’s relationship to membership and the surrounding context.','It predicts every preference a person will have.','It must be disclosed whenever another person asks.','Membership can carry different meanings across people and situations. It does not determine every choice or create an obligation to disclose.'],
 ['What does identity salience describe?','How noticeable or relevant an identity becomes in a situation.','A fixed ranking of the importance of all identities.','A measure of whether someone is culturally authentic.','Salience changes with context and experience. It is not an authenticity test or a permanent hierarchy.'],
 ['What distinguishes belonging from a friendly greeting alone?','Meaningful recognition, participation, and room to influence and differ.','A requirement to agree with every decision.','The absence of any discomfort or disagreement.','Welcome can help, but belonging also concerns participation and agency. It does not require universal agreement or an entirely discomfort-free setting.'],
 ['What is the problem with asking one person to approve a whole group’s experience?','It assigns representative authority and responsibility the person may not have chosen.','It recognizes too much individual expertise.','It means the person should never be invited to contribute.','A specific invitation can value expertise while avoiding a claim that one person represents everyone. The solution is better scope and shared responsibility, not exclusion.'],
 ],
 [
 ['Which pairing correctly distinguishes the concepts?','Stereotype: belief; prejudice: evaluation; discrimination: treatment.','Stereotype: legal verdict; prejudice: opportunity; discrimination: thought only.','All three words mean exactly the same thing.','The concepts address related but distinct dimensions. A formal legal finding requires the applicable facts and standards beyond this conceptual distinction.'],
 ['Why can positive stereotypes be limiting?','They can assign expectations or work without examining individual skill and choice.','All positive feedback is inherently harmful.','A desirable trait can never create a burden.','A flattering group assumption can still constrain a person. Specific feedback about demonstrated work avoids replacing evidence with a group expectation.'],
 ['What is a proxy in a decision?','Something used to stand in for a quality that may need more direct evidence.','Proof that a requirement is always unlawful.','A guarantee that the organizer is hostile.','A proxy may or may not be appropriate. Examine its connection to the purpose rather than assuming its legal status or the organizer’s motive.'],
 ['Why describe a concern factually?','It identifies what can be examined without adding unsupported claims about motive.','It removes the need to address consequences.','It guarantees that everyone will agree with the concern.','Precision supports accountability by clarifying the action and evidence. It does not erase consequences or guarantee consensus.'],
 ],
 [
 ['What is the central risk of ethnocentrism?','Treating a familiar cultural frame as the unquestioned universal standard.','Having any personal values at all.','Maintaining every verified safety requirement.','The concern is unexamined universality, not the existence of values or legitimate requirements. Examine the purpose and context of a standard.'],
 ['Can a course discussion establish a participant’s IDI orientation?','No; the course does not administer or replace the licensed assessment.','Yes, from one unfamiliarity or disagreement.','Yes, from whether the participant completes the exercise.','Developmental concepts can inform learning design, but a comment or participation choice is not an individual assessment or a personnel label.'],
 ['Does understanding a practice require endorsing it?','No; understanding can inform a separate evaluation of effects and requirements.','Yes; all culturally explained practices must be accepted.','No understanding is needed before judging unfamiliar practices.','Contextual understanding improves evaluation. Neither automatic endorsement nor immediate rejection supports careful reasoning.'],
 ['How should perspective-taking be treated?','As a provisional interpretation to check, not a claim to know another person’s life.','As proof that imagination replaces the person’s account.','As a way to assign a fixed cultural profile.','An imagined perspective can broaden questions, but it remains limited and should be tested through appropriate context or conversation.'],
 ],
 [
 ['What does intersectional analysis add to a list of identities?','Attention to how conditions and forms of exclusion interact.','A numerical score of disadvantage.','A rule that every combination has the same effect.','The interaction and its mechanism matter. The approach does not rank hardship or assume a universal result from an identity combination.'],
 ['What information should an access inquiry seek first?','The relevant barrier and what would make the activity usable.','A complete private identity and hardship inventory.','Proof that the person is more disadvantaged than others.','Begin with the experience and the necessary decision information. Broad disclosure and hardship rankings often add burden without explaining the mechanism.'],
 ['Why can separate support checklists miss a barrier?','Supports may not connect into a usable whole at the point where they meet.','Specialized responsibilities are always unnecessary.','Any two completed tasks automatically create access.','Specialization can be valuable, but coordination and whole-pathway testing reveal gaps between individually completed tasks.'],
 ['What can one person’s account establish?','A specific experience or problem to examine, without representing everyone in a group.','A universal conclusion about all people sharing an identity.','Nothing useful unless everyone reports the same thing.','A specific account can reveal an important issue. Its significance does not require universal agreement, and its limits should still be stated.'],
 ],
 [
 ['Why specify the dimension of equality?','Equal standing, resources, treatment, and access are related but different claims.','Equality always means physically identical actions.','Equality never concerns rights or standing.','Naming the dimension makes the reasoning clearer. Identical inputs are one possibility, not the entire meaning of equality.'],
 ['When can different support preserve a common standard?','When it changes access to the task rather than the relevant objective being assessed.','Only when everyone receives the same physical method.','Whenever it is called equitable, without further reasoning.','The purpose, barrier, and applicable requirements need examination. A different method can preserve the objective, but the label alone does not justify a change.'],
 ['What makes a fairness explanation examinable?','A stated purpose, relevant criteria, responsible process, and reasons.','The organizer’s assurance of good character alone.','Disclosure of every person’s private circumstances.','Reasons and process can be explained while protecting privacy. Neither personal assurance nor public exposure substitutes for a justified decision.'],
 ['What is the difference between an output and an access effect?','An output is a completed action; an effect concerns what became usable or changed.','They are always the same thing.','Effects can only be judged by whether people praise the organizer.','A changed file or invitation is an output. Review how it functions in the whole pathway before claiming improved access.'],
 ],
];
