import { foundation, sources } from './build';
export default foundation({
 id:'div-f01-white-privilege', number:1, title:'Understanding White Privilege', subtitle:'Examine unearned racial advantages without erasing effort, hardship, or individual variation.', sources:[sources.privilege,sources.fiske],
 cards:[{front:'White privilege',back:'Advantages attached to being treated as white in a particular social context, rather than earned by an individual achievement.'},{front:'Hardship and advantage',back:'A person can face serious hardship and still encounter fewer barriers related to race.'},{front:'Accountability',back:'Examine how access works and act within your responsibility; a confession or identity judgment is not the goal.'}],
 aid:[{heading:'Notice an advantage',items:['Name one ordinary activity: entering a meeting, questioning a decision, finding a mentor, or being recognized as knowledgeable.','Ask what preparation or proof someone else may need to do the same thing.','Separate a directly observed difference from a hypothesis you need to check.']},{heading:'Examine the explanation',items:['List racial assumptions that may matter, alongside class, disability, role, seniority, and other plausible factors.','Identify what evidence could challenge your first explanation.','Do not ask a colleague to disclose painful experiences or represent a racial group.']},{heading:'Use your influence',items:['Choose a fair process change: explicit selection criteria, shared information, or a transparent invitation.','Name the decision owner and a realistic date to revisit the change.','Check access and results, not whether participants used the preferred vocabulary.']}],
 lessons:[
 {title:'An advantage can coexist with effort',objectives:['Distinguish racial advantage from a claim that a person has never struggled.','Identify an unearned condition in a fictional opportunity.','Explain why a group pattern cannot describe every individual life.'],
 teaching:`White privilege is a way of asking which racial barriers a person is less likely to encounter, not a complete account of that person’s life. A white colleague may have grown up poor, experienced disability, survived abuse, or worked exceptionally hard. Recognizing those realities does not settle the separate question of whether being perceived as white made some situations easier. Effort describes what someone did; access describes the conditions under which the effort happened. Both belong in an honest explanation.

Peggy McIntosh’s reflective work asks readers to notice ordinary advantages that often disappear into the background. You need not agree with every example to examine the question. Consider the difference between being trusted until evidence suggests otherwise and having to establish credibility repeatedly before your evidence is heard. An advantage may be an absence of extra scrutiny. It does not require an explicit reward or a conscious request for preferential treatment.

Avoid converting the concept into a verdict about someone’s character. A person’s racial classification does not tell you their intentions, achievements, politics, or exact experiences. At the same time, uncertainty about individual motives should not prevent inquiry into unequal access. A useful conversation can hold the two questions apart: what happened in this situation, and what arrangement would make the opportunity more fairly available? Begin with an example you can describe rather than a claim about who is a good person.`,
 example:`Fictional case: Erik describes working nights to finish college. During a discussion of racial privilege, he worries that his effort is being dismissed. His colleague Maya says that her own qualifications were repeatedly questioned when she entered professional meetings. Neither account cancels the other. The facilitator can recognize Erik’s work and still ask how people are initially recognized as credible. The available stories suggest questions about experience; they do not prove that every meeting treated either person the same way or establish anyone’s motives.`,
 reflection:'Which part of your experience is easy to explain as personal effort? Which conditions made that effort possible? You may use Erik’s fictional account instead of disclosing your history.',action:'Draw two columns: effort and enabling conditions. Place finishing a degree while working in the first; place access to a trusted reference or an affordable route into training in the second. Mark any racial explanation as a question until you have supporting evidence. Write one sentence that recognizes effort while keeping unequal conditions available for discussion.',question:'What is the most useful response to Erik?',choices:['Recognize his effort and examine the separate question of racial barriers.','Tell him hardship means he cannot have racial privilege.','Treat his concern as proof that he is unwilling to learn.'],feedback:['This keeps both personal history and unequal conditions visible without making a character judgment.','Hardship does not establish that race had no effect on access.','A concern is an opportunity to clarify the concept, not sufficient evidence about someone’s willingness.']},
 {title:'When an ordinary pathway is easier for some people',objectives:['Identify a hidden access condition in an informal opportunity.','Compare an individual explanation with a process explanation.','Propose evidence that would help examine unequal access.'],
 teaching:`Advantages can accumulate through ordinary pathways: who hears about an opportunity, who receives encouragement, whose unfamiliarity is forgiven, and who is assumed to fit. None of these moments alone provides a complete explanation of racial inequality. Together, however, they give us places to investigate how opportunity is distributed. An invitation sent through a familiar network can feel neutral to the sender while reaching a narrow group.

Start by tracing the pathway. Ask who receives information, what they must already know, how readiness is judged, and who can question the decision. Then distinguish a pattern from a conclusion about its cause. A list containing mostly white participants is a reason to examine how invitations were issued, not automatic proof about the intention of each organizer. Conversely, a statement of good intention does not show that the pathway was broadly accessible.

Useful evidence includes written eligibility criteria, the channels used to announce an opportunity, the timing of notices, and feedback offered voluntarily. Avoid informal racial inventories of colleagues or demands that employees recount discrimination to validate the inquiry. Work through authorized information and the responsible people. The practical goal is to make relevant opportunities legible and accessible. This can include publishing criteria, widening an announcement, or allowing questions before a deadline. Those choices should be evaluated for their actual effects rather than treated as proof that the underlying issue is solved.`,
 example:`Fictional case: A small project group fills development assignments by asking people they already know. The selections appear to repeat the same social circle. Lena notices that a promising analyst never saw an invitation. The group has no record of who was informed, and its members disagree about what counted as qualification. Lena cannot infer every cause from the roster. She can identify a concrete weakness: access depends on private knowledge and unstated criteria. A public invitation with clear requirements is a testable improvement.`,reflection:'When have you known the unwritten steps in a process? What did that knowledge let you avoid? Consider a process rather than evaluating a coworker.',action:'Map the fictional assignment in four steps: announcement, expression of interest, comparison, and selection. Under each, write what was explicit and what depended on familiarity. Draft an announcement stating purpose, eligibility, deadline, and contact. Specify how you would check whether new people actually received and understood it.',question:'Which response best addresses the observed weakness?',choices:['Publish criteria and an accessible invitation, then review who could participate.','Declare the roster sufficient proof of each organizer’s racial motives.','Keep the process because nobody intended exclusion.'],feedback:['This acts on a visible access condition and leaves room for evidence about effects.','The roster alone does not establish individual motives.','Intention does not answer whether others could find and use the opportunity.']},
 {title:'Listen without asking someone to prove the concept',objectives:['Recognize requests that shift the burden of education to a colleague.','Draft an invitation to hear a perspective without requiring disclosure.','Distinguish listening from immediate self-defense.'],
 teaching:`A conversation about privilege can become a debate about whether someone has suffered enough to count. That structure is rarely helpful. It asks people to present personal pain as evidence and can reward the most dramatic story. A more useful approach starts with a shared example or public source and gives people choices about participation. Nobody needs to disclose family history, financial circumstances, or discrimination in order for a group to examine an access barrier.

Listening does not require accepting every interpretation without question. It means first understanding the account well enough to respond to what was actually said. Separate the description, the effect, and the explanation. A colleague may describe repeated interruptions, explain that they felt dismissed, and interpret the pattern as racialized. You can acknowledge the described effect, ask what response would be useful, and examine the behavior without pretending to know the speaker’s full experience or the interrupter’s mind.

If discomfort arises, pause before seeking reassurance that you are a good person. Reassurance can turn attention away from the issue and require the affected person to care for the listener. A grounded response names what you heard and what you can do. If you disagree, identify the specific interpretation or evidence rather than dismissing the person. Questions about formal concerns belong in appropriate agency channels; a voluntary learning conversation should not become an improvised investigation or a forced public account of a workplace incident.`,
 example:`Fictional case: During an optional discussion, a participant asks Jordan, the only Black colleague in the room, to give an example that will convince everyone white privilege is real. Jordan becomes quiet. The facilitator can intervene without assuming what Jordan feels: “We can use the fictional example we prepared. No one needs to supply a personal experience.” Later, the facilitator offers Jordan a choice about feedback. The learning can continue while the group takes responsibility for using available resources rather than appointing one person its racial educator.`,reflection:'What do you do when you want to defend your intention? What would help you remain curious without asking another person to reassure you?',action:'Write a two-sentence response to the fictional group: first remove the expectation of disclosure, then return to the access question. Practice a listening response beginning with the specific point you heard. Replace “prove it happened” with a question about the process or support the person wants, when a question is welcome.',question:'What should the facilitator do first?',choices:['Remove the disclosure pressure and use the prepared fictional example.','Ask Jordan again because an authentic story would be more persuasive.','End the subject because one participant became quiet.'],feedback:['This protects choice while keeping substantive learning available.','Repeating the request increases the burden and treats a colleague as representative of a group.','Silence has several possible meanings; ending the subject is not the only respectful response.']},
 {title:'Turn recognition into a fairer opportunity',objectives:['Select a concrete change within your responsibility.','Distinguish a symbolic gesture from an access improvement.','Define a follow-up question that checks the effect of the change.'],
 teaching:`Recognizing privilege is a beginning, not a completed action. A person can learn the vocabulary while leaving the same invitation lists, credibility standards, and information gaps intact. Choose a practice you can influence and identify a specific point where an advantage depends on familiarity, assumptions, or unequal access to information. Then work toward a more explicit and usable process.

An effective change does not require you to take over another person’s decisions or speak on behalf of an entire community. You may share information that was previously informal, make selection criteria visible, acknowledge the source of an idea, or question an unsupported assumption before it shapes a decision. Describe the improvement in terms of its purpose and mechanism. “Everyone will know when and how to apply” is more useful than “we will be inclusive.” The first claim can be checked.

Follow-up matters because a change can introduce another barrier. A written announcement may be clearer but inaccessible to someone using assistive technology. A longer application can make criteria explicit while adding unnecessary work. Ask the people responsible for the process to consider these effects and invite feedback through appropriate channels. Preserve fair standards while examining which steps actually assess those standards. Your task is not to certify yourself as free of bias. It is to make a better-supported decision, remain open to correction, and revisit what happened.`,
 example:`Fictional case: After noticing that stretch assignments circulate privately, Noor proposes a monthly list of opportunities with the same eligibility information available to all relevant staff. The manager agrees to test it for two cycles. Noor initially wants to count completed announcements as success. A colleague suggests a better follow-up: can staff find the list, understand the requirements, and ask questions in time? The team also reviews whether the same informal endorsements still determine selection. The public list changes one part of the pathway; it does not automatically repair every part.`,reflection:'Which advantage in your environment could become a shared condition rather than a private exception? What would you need to learn before changing it?',action:'Complete the job aid with one opportunity, one hidden condition, one proposed change, and one person responsible for the decision. Add a follow-up date and two questions: Did access improve? What unintended difficulty appeared? Keep the proposal proportionate and consult the responsible office before changing formal requirements or selection rules.',question:'What would be the strongest evidence that Noor’s change helped?',choices:['Staff can find and use the opportunity information, and selection follows the stated criteria.','Noor reports feeling more aware of privilege.','The team published a list once.'],feedback:['This checks the opportunity pathway and its use rather than only the activity.','Awareness matters but does not establish an improvement in access.','Publication is an output; it does not show that information was usable or selections became more transparent.']}
 ]
});
