"use client";
import { useEffect, useId, useState, type ReactNode } from "react";
import Link from "next/link";
import type { Block, Lesson } from "@/lib/content/courses/source-types";
import { lessonImageOverrides } from "@/lib/content/courses/lesson-image-overrides";
import { duplicateLessonImageKeys } from "@/lib/content/courses/lesson-image-repeat-suppression";

type State={schemaVersion:1;fields:Record<string,string>;submitted:Record<string,boolean>;completed:boolean};
const blank=():State=>({schemaVersion:1,fields:{},submitted:{},completed:false});
function validState(value:unknown):value is State { if(!value||typeof value!=="object")return false; const state=value as State;return state.schemaVersion===1&&typeof state.completed==="boolean"&&!!state.fields&&!!state.submitted&&Object.values(state.fields).every(item=>typeof item==="string")&&Object.values(state.submitted).every(item=>typeof item==="boolean"); }
function Rich({text}:{text:string}) {return <div className="course-rich" dangerouslySetInnerHTML={{__html:text}}/>;}
export function CourseLesson({courseId,lesson,objectives,previous,next,companion,courseOverviewHref}:{courseId:string;lesson:Lesson;objectives:string[];previous?:string;next?:string;companion?:ReactNode;courseOverviewHref?:string}) {
  const overviewHref=courseOverviewHref??`/courses/${courseId}`;
  const [state,setState]=useState<State>(blank); const [loaded,setLoaded]=useState(false); const [message,setMessage]=useState(""); const uid=useId();
  const storageKey=`pac-course:${courseId}:${lesson.id}`;
  useEffect(()=>{let active=true;Promise.resolve().then(()=>{if(!active)return;try{const raw=localStorage.getItem(storageKey);if(raw){const saved:unknown=JSON.parse(raw);if(!validState(saved))throw new Error("Invalid saved notes");setState(saved);}}catch{setMessage("Your saved notes could not be opened. You can still work through this lesson.");}setLoaded(true);});return()=>{active=false;};},[storageKey]);
  function save(nextState:State) {setState(nextState);try{localStorage.setItem(storageKey,JSON.stringify(nextState));localStorage.setItem(`pac-course-resume:${courseId}`,lesson.id);setMessage("Saved.");}catch{setMessage("Your changes could not be saved. Keep this page open and copy any notes you need.");}}
  const field=(key:string,value:string)=>save({...state,fields:{...state.fields,[key]:value},submitted:{...state.submitted,[key]:false}});
  const submit=(key:string)=>save({...state,submitted:{...state.submitted,[key]:true}});
  const reset=(key:string)=>save({...state,fields:{...state.fields,[key]:""},submitted:{...state.submitted,[key]:false}});
  function render(block:Block,index:number) {
    const key=`block-${index}`;const inputId=`${uid}-${key}`;
    switch(block.type){
      case "text":return <section>{block.heading?<h2>{block.heading}</h2>:null}<Rich text={block.body}/></section>;
      case "image":{const replacement=lessonImageOverrides[block.src];const caption=replacement?.caption??block.caption;if(duplicateLessonImageKeys.has(`${courseId}|${lesson.id}|${index}`))return caption?<p className="course-image-note">{caption}</p>:null;return <figure><img src={replacement?.src??block.src} alt={replacement?.alt??block.alt} loading="lazy"/>{caption?<figcaption>{caption}</figcaption>:null}</figure>;}
      case "statement":return <aside className="course-statement"><Rich text={block.body}/></aside>;
      case "quote":return <blockquote><Rich text={block.text}/>{block.cite?<cite>{block.cite}</cite>:null}</blockquote>;
      case "list":{const List=block.ordered?"ol":"ul";return <section>{block.heading?<h2>{block.heading}</h2>:null}<List>{block.items.map((item,i)=><li key={i}><Rich text={item}/></li>)}</List></section>;}
      case "leaderMove":return <section><h2>{block.heading??"Put it into practice"}</h2><h3>What you can change</h3><Rich text={block.control}/><h3>What to watch for</h3><Rich text={block.failure}/><h3>Your next step</h3><Rich text={block.next}/></section>;
      case "accordion":return <section>{block.heading?<h2>{block.heading}</h2>:null}{block.items.map((item,i)=><details key={i}><summary>{item.title}</summary><Rich text={item.body}/></details>)}</section>;
      case "flashcards":return <section>{block.heading?<h2>{block.heading}</h2>:null}<div className="course-flashcards">{block.cards.map((card,i)=><details key={i}><summary><Rich text={card.front}/></summary><Rich text={card.back}/></details>)}</div></section>;
      case "tabs":{const selected=Number(state.fields[key]??0);return <section>{block.heading?<h2>{block.heading}</h2>:null}<div role="tablist" aria-label={block.heading??"Explore perspectives"}>{block.tabs.map((tab,i)=><button key={i} role="tab" id={`${inputId}-tab-${i}`} aria-controls={`${inputId}-panel-${i}`} aria-selected={selected===i} tabIndex={selected===i?0:-1} onKeyDown={event=>{const count=block.tabs.length;const nextIndex=event.key==="ArrowRight"?(i+1)%count:event.key==="ArrowLeft"?(i+count-1)%count:event.key==="Home"?0:event.key==="End"?count-1:undefined;if(nextIndex!==undefined){event.preventDefault();field(key,String(nextIndex));document.getElementById(`${inputId}-tab-${nextIndex}`)?.focus();}}} onClick={()=>field(key,String(i))}>{tab.label}</button>)}</div>{block.tabs.map((tab,i)=><div key={i} role="tabpanel" id={`${inputId}-panel-${i}`} aria-labelledby={`${inputId}-tab-${i}`} hidden={selected!==i}><Rich text={tab.body}/></div>)}</section>;}
      case "timeline":return <section>{block.heading?<h2>{block.heading}</h2>:null}<ol className="course-timeline">{block.events.map((event,i)=><li key={i}><h3>{event.year} — {event.title}</h3><Rich text={event.body}/></li>)}</ol></section>;
      case "knowledgeCheck":{const chosen=state.fields[key];const checked=state.submitted[key];const correct=block.options[Number(chosen)]?.correct;return <fieldset><legend>{block.question}</legend>{block.options.map((option,i)=><label key={i} className="course-choice"><input type="radio" name={inputId} checked={chosen===String(i)} onChange={()=>field(key,String(i))}/><Rich text={option.text}/></label>)}<button disabled={!loaded||chosen===undefined||chosen===""} onClick={()=>submit(key)}>Check answer</button><button onClick={()=>reset(key)}>Try again</button>{checked?<div role="status"><Rich text={correct?block.feedbackCorrect:block.feedbackIncorrect}/></div>:null}</fieldset>;}
      case "sorting":{const selections=block.items.map((_,i)=>state.fields[`${key}-${i}`]??"");return <fieldset><legend>{block.heading??"Match each example"}</legend>{block.items.map((item,i)=><label className="course-sort" key={i}><Rich text={item.text}/><select aria-label={`Category for ${item.text.replace(/<[^>]*>/g,"")}`} value={selections[i]} onChange={event=>save({...state,fields:{...state.fields,[`${key}-${i}`]:event.target.value},submitted:{...state.submitted,[key]:false}})}><option value="">Choose a category</option>{block.categories.map(category=><option key={category}>{category}</option>)}</select>{state.submitted[key]?<span>{selections[i]===item.category?"That fits.":`Consider: ${item.category}`}</span>:null}</label>)}<button disabled={!loaded||selections.some(value=>!value)} onClick={()=>submit(key)}>Check matches</button><button onClick={()=>save({...state,fields:{...state.fields,...Object.fromEntries(block.items.map((_,i)=>[`${key}-${i}`,""]))},submitted:{...state.submitted,[key]:false}})}>Reset</button></fieldset>;}
      case "artifact":return <section><h2>{block.title}</h2><Rich text={block.summary}/>{block.fields.map((item,i)=><p className="course-note" key={i}><strong>{item.label}</strong> {item.value}</p>)}<Rich text={block.action}/><p className="notice" role="note">Browse and download only. Staff notes are not typed or saved on this page.</p><button onClick={()=>{const text=block.title+"\n\n"+block.fields.map((item)=>item.label+": "+item.value).join("\n\n");const url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`${courseId}-${lesson.id}-${index}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download this published draft</button></section>;
      default:throw new Error(`Unsupported course block: ${block.type}`);
    }
  }
  return <article className="course-lesson"><p>{lesson.minutes} minutes</p><h1>{lesson.title}</h1><Rich text={lesson.summary}/><section><h2>What you’ll be able to do</h2><ul>{objectives.map((objective,i)=><li key={i}>{objective}</li>)}</ul></section><fieldset disabled={!loaded} className="course-activities">{lesson.blocks.map((block,index)=><div key={index} data-course-block={block.type}>{render(block,index)}</div>)}
    {companion}
    {lesson.scenario?<section><h2>Try a situation</h2><Rich text={lesson.scenario.context}/><fieldset><legend>{lesson.scenario.prompt}</legend>{lesson.scenario.options.map((option,i)=><label className="course-choice" key={i}><input type="radio" name={`${uid}-scenario`} checked={state.fields.scenario===String(i)} onChange={()=>field("scenario",String(i))}/><Rich text={option.label}/></label>)}<button disabled={!state.fields.scenario} onClick={()=>submit("scenario")}>Consider your choice</button><button onClick={()=>reset("scenario")}>Try another response</button>{state.submitted.scenario?<div role="status"><Rich text={lesson.scenario.options[Number(state.fields.scenario)]?.response??""}/></div>:null}</fieldset></section>:null}
    {lesson.learning?.takeaways.length?<section><h2>Carry this forward</h2><ul>{lesson.learning.takeaways.map((item,i)=><li key={i}><Rich text={item}/></li>)}</ul><Rich text={lesson.learning.evidence}/><Rich text={lesson.learning.appliedNextStep}/></section>:null}
    {lesson.transfer?<section><h2>Your next step</h2><Rich text={lesson.transfer.prompt}/>{lesson.transfer.options.map((option,i)=><label className="course-choice" key={i}><input type="radio" name={`${uid}-transfer`} checked={state.fields.transfer===String(i)} onChange={()=>field("transfer",String(i))}/><Rich text={option}/></label>)}</section>:null}
    <p className="notice" role="note"><strong>Browse and download only. </strong>Course notes are not typed or saved on this page.</p>
    <label className="course-choice"><input type="checkbox" checked={state.completed} onChange={event=>save({...state,completed:event.target.checked})}/>Mark this lesson complete</label>
    <button onClick={()=>{if(window.confirm("Clear your answers and notes for this lesson?"))save(blank());}}>Reset this lesson</button></fieldset><p role="status">{message}</p><nav aria-label="Lesson navigation">{previous?<Link href={previous}>Previous lesson</Link>:<Link href={overviewHref}>Course overview</Link>}{next?<Link href={next}>Next lesson</Link>:<Link href={overviewHref}>Back to course</Link>}</nav></article>;
}
