import "./palette-preview.css";
import styles from "@/components/dsd-experience.module.css";
import { LeadershipDevelopmentStudio } from "@/components/leadership-development-studio";
import Image from "next/image";
import { LearningJourneyLink } from "@/components/learning-journey-link";
import Link from "next/link";
import { LeadershipLifecycleExplorer, SuccessionPracticeTool } from "@/components/leadership-lifecycle-tools";
import { ResourceDownloads } from "@/components/resource-downloads";
import { LEADERSHIP_SOURCES } from "@/lib/content/leadership-lifecycle";
export const metadata={title:"DEIA leadership and growth | One DSD"};
export default async function Page({ searchParams }: { searchParams: Promise<{stage?:string}> }){const {stage}=await searchParams;return <div className={`${styles.page} leadership-palette-preview wrap max-w-6xl py-10`}>
 <Link href="/one-dsd">← One DSD</Link>
 <header className={`${styles.hero} my-7 overflow-hidden rounded-2xl border border-[#ded5c7] bg-[#faf7f1]`}><div className="grid lg:grid-cols-2"><div className="p-7 sm:p-10"><p className={styles.eyebrow}>People grow. Leadership grows with them.</p><h1 className="mt-4 text-4xl font-semibold tracking-tight md:text-5xl">Grow your DEIA leadership</h1><p className="mt-5 text-xl leading-8">Bring your experience, your curiosity, and the kind of leader you want to become. Develop a practice that makes equity, inclusion, and accessibility part of how DSD works.</p><p className="mt-5 leading-7">Explore DEIA in the practice of leadership—whether you are discovering your potential, supporting a team, or shaping the division&apos;s future.</p><a className="mt-6 inline-block rounded-full bg-[#123f60] px-6 py-3 font-semibold text-white" href="#starting-points">Find your starting point →</a></div><Image src="/images/leadership-listening-conversation.webp" width={1599} height={900} alt="A supervisor listens to a colleague who uses a wheelchair during a one-to-one conversation." sizes="(min-width:1024px) 50vw, 100vw" className="h-auto w-full self-center" /></div></header>
 <details className="my-5 border-t border-line pt-4"><summary className="cursor-pointer font-semibold text-[#123f60]">Download this leadership page</summary><ResourceDownloads kind="leadership" id="one-dsd" noun="page" scope="dsd" /></details>
 <nav aria-label="Leadership development" className={styles.sectionNav}><a href="#starting-points">Your starting point</a><a href="#life-cycle">The employee life cycle</a><a href="#growth">Your development</a><a href="#continuity-plan">Succession in practice</a><a href="#connections">Learning and colleagues</a></nav>
 <section className="my-10"><h2 className="text-3xl font-semibold">Learn. Reflect. Practice. Return.</h2><p className="mt-4 max-w-3xl leading-8">Diversity, equity, inclusion, and accessibility shape how we interpret experience, distribute opportunities, and make decisions. This One DSD experience brings One DHS learning into the employee life cycle, with room to examine assumptions and improve the conditions in which people work.</p><div className={`${styles.learningCycle} mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4`}>{[["Learn","Explore a resource and the leadership decision it can inform."],["Reflect","Separate what you observed from what you assumed. Consider whose perspective is missing."],["Practice","Try a supported change or work through a realistic situation."],["Return","Seek feedback, examine what happened, and decide what to keep or change."]].map(([title,body],i)=><article key={title} className={`rounded-xl p-5 ${["bg-[#eef3f8]","bg-[#f2edf7]","bg-[#f7eee2]","bg-[#edf3ef]"][i]}`}><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7">{body}</p></article>)}</div></section>
 <LeadershipDevelopmentStudio />
 <section className="my-10 rounded-xl bg-[#faf3e8] p-7"><p className="text-sm font-semibold uppercase tracking-widest text-[#71502f]">A shared learning area</p><h2 className="mt-3 text-3xl font-semibold">Lead equity through the employee life cycle</h2><p className="mt-4 max-w-3xl leading-8">From role design and recruitment to development, retention, and succession, each stage offers a practical way to grow. Use these situations to explore the capability you chose in your development map.</p></section>
 <LeadershipLifecycleExplorer key={stage??"design"} initialStage={stage} />
 <section id="growth" className="my-10 scroll-mt-8 border-y border-line py-9"><h2 className="text-3xl font-semibold">Grow from where you are</h2><p className="mt-4 max-w-3xl leading-8">This voluntary learning experience has no minimum service requirement. Choose a question that fits your role and interests. Formal training programs and job opportunities have their own requirements.</p><div className={`${styles.growthCards} mt-6 grid gap-5 md:grid-cols-3`}>{[["Exploring leadership","Notice a barrier, facilitate a thoughtful conversation, or help make a process clearer. Practice listening across perspectives and explaining a decision with evidence.","Try co-facilitating a Learning Lab."],["Leading a team","Apply the same equity lens to hiring, feedback, workload, recognition, and development. Ask colleagues what helps them contribute and what needs to change.","Try reviewing how a development opportunity is offered."],["Preparing for broader responsibility","Connect equitable workforce decisions with strategy, resources, and continuity. Use the actual duties of a role to identify what you need to practice and demonstrate.","Try an options brief on a cross-team workforce challenge."]].map(([title,body,example])=><article key={title} className="rounded-xl border border-line p-6"><h3 className="text-2xl font-semibold">{title}</h3><p className="my-4 leading-7">{body}</p><p className="font-semibold leading-7">{example}</p></article>)}</div><p className="mt-6 max-w-3xl leading-7">For a supervisor considering a director role, a useful roadmap begins with the role&apos;s responsibilities: compare them with demonstrated experience, choose a supported practice opportunity, seek feedback, and build examples of what changed. Advancement also depends on the applicable qualifications and selection process.</p><p className="mt-5"><Link href="/resources/pn-accessible-leadership-pathways">Explore accessible pathways and sponsorship →</Link></p></section>
 <section id="development-partners" className={`${styles.supportBand} my-10 rounded-2xl bg-[#f2edf7] p-7 sm:p-9`}><h2 className="text-3xl font-semibold">Support that makes growth possible</h2><div className="mt-6 grid gap-5 md:grid-cols-2"><article><h3 className="text-xl font-semibold">A conversation with a mentor or sponsor</h3><p className="mt-3 leading-7">Bring your development map. Discuss the capability you want to practice, an opportunity that fits, the time and access you need, and how you will receive feedback. Mentoring can help you think through the experience; sponsorship can help make an opportunity available.</p><Link href="/one-dsd/amplify/mentoring" className="mt-4 inline-block font-semibold">Explore mentoring and peers →</Link></article><article><h3 className="text-xl font-semibold">Feedback you can use</h3><ul className="mt-3 list-disc space-y-3 pl-5 leading-7"><li>What did you observe me do, and what difference did it make?</li><li>Whose perspective or access did the approach make room for?</li><li>Where did an assumption or a working condition get in the way?</li><li>What could I try differently next time?</li></ul></article></div><p className="mt-6 max-w-3xl leading-7">You can also bring a question to a Learning Lab or the consultant. Agree on what may be shared, and focus feedback on the work and its effects.</p><Link href="/one-dsd/team/learning-lab" className="mt-4 inline-block font-semibold">Find a learning conversation →</Link></section>
 <p className="max-w-3xl leading-8">A personal development map can connect with a wider continuity need. When colleagues can practice critical work with support, they build experience while the division strengthens its ability to carry that work forward.</p>
 <SuccessionPracticeTool />
 <section className="my-10"><h2 className="text-3xl font-semibold">What meaningful progress could look like</h2><div className="mt-6 grid gap-5 md:grid-cols-2"><article className="rounded-xl bg-[#faf3e8] p-6"><h3 className="text-xl font-semibold">For a person developing</h3><p className="mt-3 leading-7">A clearer aspiration, an opportunity they can access, a skill they have practiced, useful feedback, and a work example they can explain. Growth may mean greater contribution in a current role as well as interest in advancement.</p></article><article className="rounded-xl bg-[#eef3f8] p-6"><h3 className="text-xl font-semibold">For the division</h3><p className="mt-3 leading-7">Clearer criteria, more accessible development opportunities, follow-through on staff feedback, and critical work that more than one person can carry forward. Examine appropriate aggregate patterns with the responsible partners; course completion alone cannot show these outcomes.</p></article></div></section>
 <LearningJourneyLink scope="dsd" compact />
 <section id="connections" className={`${styles.supportBand} my-10 scroll-mt-8 rounded-2xl bg-[#f2edf7] p-7 sm:p-9`}><h2 className="text-3xl font-semibold">Part of the wider One DHS program</h2><p className="mt-4 max-w-3xl leading-8">Reflection becomes richer when it connects with another perspective. Bring a practice question to the One DSD Team, explore mentoring through Amplify, or follow a resource into the wider program.</p><ul className="mt-6 grid gap-5 md:grid-cols-2">{[["Program orientation","/orientation"],["Operationalizing equity","/operationalizing-equity"],["Learning and resources","/learn"],["Practice pathways","/practice"],["One DSD Learning Lab","/one-dsd/team/learning-lab"],["Amplify mentoring and peer learning","/one-dsd/amplify/mentoring"],["Employee resource groups","/employee-resource-groups"],["Explore a question with ASK","/ask"],["Leadership and systems change across DHS","/areas/leadership-systems"],["Find support","/support"]].map(([label,href])=><li key={href}><Link href={href} className="font-semibold">{label} →</Link></li>)}</ul></section>
 <details className="my-8 rounded-xl border border-line p-6"><summary className="cursor-pointer text-xl font-semibold">Sources and opportunities to explore</summary><p className="mt-4 leading-7">These references informed this original program experience. Examples are learning situations, not accounts of named staff.</p><ul className="mt-5 space-y-5">{LEADERSHIP_SOURCES.map(s=><li key={s.href}><a href={s.href}>{s.title} →</a><p className="mt-2 text-sm leading-6">{s.note}</p></li>)}</ul></details>
 </div>}
